### ISSUE TITLE
Ship engineers now show up in refit tech list

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/mekhq#1]
0.3.23

Due to changes made in 1a3a17459cc93bbf287aa306c621498b0315b21a a ships engineer will show up in the tech list when doing refits.

Unconfirmed but they could also show up in the warehouse when parts are in need of repairs

**Comment by Dylan-M** [comment]
Yes, they should only show up in the refit list, and in fact should be the **only** tech to show, when it's their ship being refitted.

However, who says I don't want them to show up in my warehouse? You saying they're not capable of the work? ;)

**Comment by pheonixstorm** [comment]
Since I have to fix a similar bug in my Force Tech patch I think I will go ahead and fix this as well whenever I get around to finishing it. One less thing for you to worry about ralgith.

**Comment by pheonixstorm** [comment]
Fixed in PR #58

**Comment by pheonixstorm** [comment]
Fixed in c0c300d64e698679d9e2d13fbf66c64045f2d0ba
