### ISSUE TITLE
CamOps Training Munitions calculations for large craft

### ISSUE THREAD

**Issue by WildCoyote** [MegaMek/mekhq#1004]
Training Munitions for large craft with missiles is incorrect in the finances tab when using campaign operations peactime costs. Training munitions should be one quarter of the cost of the total munitions. 

Example Trojan dropship should be cost of munitions (30000) times tonnage (15) divided by four (112500).

Currently shows as 590000

Steps for reproduction. 
Start ATB campaign, add Trojan or Union dropship (or any dropship with missile munitions)
Look at training munitions in finance tab. 

Running Windows 10
MekHQ stable 44.0
JAVA version 1.8.0_151

**Comment by sixlettervariables** [comment]
On the latest dev version, for a Trojan (2655) I saw the following:
```
LRM 20 Ammo Bin $ 270,000
LRM 20 Ammo Bin $ 270,000
LRM 20 Ammo Bin $ 270,000
LRM 20 Ammo Bin $ 270,000
SRM 6 Ammo Bin  $ 260,357
SRM 6 Ammo Bin  $ 260,357
AC/10 Ammo Bin  $  24,000
AC/10 Ammo Bin  $  24,000
AC/5 Ammo Bin   $   4,500
AC/5 Ammo Bin   $   4,500
AC/5 Ammo Bin   $   4,500
==========
Subtotal:     $ 1,662,214
Discount:              75 %
Total:        $   415,553
```
It looks like each of these are being calculated correctly. Does something seem out of place?
