### ISSUE TITLE
Large Craft Ammo Reloading Issues

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/mekhq#1005]
### Environment
MHQ 0.45.2
What operating system are you using?  Windows
What java version are you using?  8.191 x64

### Description
When reloading standard ammo bins on a dropship, you can only reload 1 ton of 1 type of ammo. Once the crew has done this, the option to reload all other ammo bays disappears even if they aren't full. 

So far as I can tell, reloading capital weapon ammo is not affected and works normally. 

In the attached campaign file, notice that both LRM10 artemis ammo bays on the Seeker (3054) need reloading. If you reload one, it will refill with the correct 12 shots but then you won't be able to reload the other bay.  The Union (3055) is fully loaded, but I was able to expend ammo by editing the shots needed tag for the gauss and LRM20 (artemis) ammo slots in the CPNX file (the Union has bins with multiple tons of ammo, Seeker does not).  I tried to reload the LRM20 ammo, and was able to reload 6 shots into one of the bins (not a full load), before the reload option for all bins was removed from the repair tab.

### Files
[LC Ammo CPNX.zip](https://github.com/MegaMek/mekhq/files/2699868/LC.Ammo.CPNX.zip)

The archive contains CPNX and custom units. I have other custom files including camo and RATgen data. Let me know if it doesn't load. 

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2699895/mekhqlog.txt)
Don't see anything in here except a whole bunch of failures in getEngineTonnage

**Comment by sixlettervariables** [comment]
I attempted to recreate this issue, but was unable to do so:
```
Stephen Bowles attempts to reload LRM 20 Ammo Bin on Intruder (2655), needs Automatic Success and rolls 9: fixed.
Stephen Bowles attempts to reload LRM 20 Ammo Bin on Intruder (2655), needs Automatic Success and rolls 10: fixed.
Stephen Bowles attempts to reload LRM 20 Ammo Bin on Intruder (2655), needs Automatic Success and rolls 4: fixed.
Stephen Bowles attempts to reload LRM 20 Ammo Bin on Intruder (2655), needs Automatic Success and rolls 7: fixed.
```

**Comment by mkerensky** [comment]
[Missing Units.zip](https://github.com/MegaMek/mekhq/files/2715189/Missing.Units.zip)

**Comment by sixlettervariables** [comment]
I can reproduce with your specific craft, but not with others.

**Comment by sixlettervariables** [comment]
The problem code is here:
```java

    @Override
    public boolean needsFixing() {
        return (shotsNeeded < 0)
                || ((shotsNeeded > 0) && (type.getTonnage(null) <= bayAvailableCapacity())); 
    }

    /**
     * Check all the bins in the same bay that feed the same weapon(s) to determine whether there is
     * sufficient capacity to load more ammo into this bin. In the case of an ammo swap some ammo
     * may need to be removed from another bin in this bay before more can be loaded.
     *
     * @return The amount of unused capacity that can be used to reload ammo.
     */
    private double bayAvailableCapacity() {
        if (null != unit) {
            double space = 0.0;
            for (Part p : unit.getParts()) {
                if (p instanceof LargeCraftAmmoBin) {
                    final LargeCraftAmmoBin bin = (LargeCraftAmmoBin) p;
                    if ((bin.getBayEqNum() == bayEqNum)
                            && (((AmmoType) bin.getType()).getAmmoType() == ((AmmoType) type).getAmmoType())
                            && (((AmmoType) bin.getType()).getRackSize() == ((AmmoType) type).getRackSize())) {
                        space += bin.getCapacity() - bin.getTonnage();
                    }
                }
            }
            return space;
        }
        return 0.0;
    }
```
The second LargeCraftAmmoBin comes back as 10 shots needed *but* the test of tonnage comes back as "all good", causing the unit to display as not Serviceable.

**Comment by sixlettervariables** [comment]
It looks like it won't let you reload less than a ton of ammo into a bin.
