### ISSUE TITLE
New unit with unpiloted elementals fails to load.

### ISSUE THREAD

**Issue by pjfarland** [MegaMek/mekhq#1010]
45.2 Environment
Windows 10
Java version 1.8.0_171

Game fails to load. It's related to the Elementals as deleting them from the cpnx allows the game to load.

Error "Exception in thread "AWT-EventQueue-0" java.lang.StackOverflowError
	at mekhq.campaign.parts.BattleArmorSuit.getStickerPrice(BattleArmorSuit.java:271)
	at mekhq.campaign.parts.BattleArmorSuit.getStickerPrice(BattleArmorSuit.java:279)"
with the last line repeated over and over.

[Last of the Jaguars30600101-10.zip](https://github.com/MegaMek/mekhq/files/2712090/Last.of.the.Jaguars30600101-10.zip)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2712091/mekhqlog.txt)

**Comment by sixlettervariables** [comment]
I can't load that campaign due to missing customs, but I believe I have the error fixed. To double check, the sequence of events:
- You have one or more Battle Armor without pilots.
- You cannot load the Campaign

**Comment by pjfarland** [comment]
Thanks. Shouldn't have had customs though as I haven't even finished building the unit yet. Unless having customs in a separate game, but in the same folder of MekHQ matters?

**Comment by pjfarland** [comment]
It seems that Piloted or not doesn't matter. The issue happened again.
[Last of the Jaguars30600101-13.zip](https://github.com/MegaMek/mekhq/files/2713593/Last.of.the.Jaguars30600101-13.zip)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2713594/mekhqlog.txt)

Digging further it happens with brand new units with no other equipment or personnel. Armor is also not showing up in hanger.
