### ISSUE TITLE
Campigan File *will* load on one computer, will not load in another.

### ISSUE THREAD

**Issue by MageOhki** [MegaMek/mekhq#1019]
This was on request of Devs:

MekHQ .45.2  (Same exact program in fact, MekHQ and related files are on an external HD that's used for this purpose)  MekHQ is set to -Xmx8G in the i4j file  Have tried setting it lower, will not load file on laptop at all.   MekHQ will run otherwise.
Both computers use Windows 10, Desktop: XPS 8930, 16 of ram, i7-8700k, Laptop Pent. N3710, 4 gigs of RAM  Desktop Java: 32 bit 181, 64 bit 191, Laptop Java, both are 191.

Campaign file (attached) will load as noted above on the desktop, will not run on the laptop.  My view is it's performance related, though it's possible it's not.

Logfile is from last unsuccessful attempt to load on laptop.
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2714553/mekhqlog.txt)
Campigan file zipped:
[Onishi's heavy calvary.zip](https://github.com/MegaMek/mekhq/files/2714555/Onishi.s.heavy.calvary.zip)
[mechfiles.zip](https://github.com/MegaMek/mekhq/files/2714557/mechfiles.zip)

**Comment by sixlettervariables** [comment]
This is likely due to the RAM settings with your laptop. Some tuning is required on a larger file with smaller memory machines, especially if you're using 32-bit Java. I can load this CPNX on both my Win10 desktop and Macbook without issues on 0.45.4.
