### ISSUE TITLE
45.2 : Mass repair does not work on some items

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#1028]
Mass repair does not work on some items and the daily log does not explain why. It wont repair the items for the hunchback, or the damaged jumpjet on the vindicator.

![image](https://user-images.githubusercontent.com/1191378/50719250-eeba6f80-10ed-11e9-9f58-6bb091655d86.png)
[a.zip](https://github.com/MegaMek/mekhq/files/2729076/a.zip)

**Comment by sixlettervariables** [comment]
I was able to reproduce this under one condition:
- The Min BTH was <8
- and I did not click Save Options as Default before clicking Start Mass Repair/Salvage

If I increased the Min BTH to 7 for Locations and 8 for Weapons, then clicked Save Options as Default, it would then perform the mass repair as expected.

What this appears to be is a problem where the Mass Repair Options you can see are the ones being used. Please confirm for me that if you increase the Min BTH to 7 for Locations and 8 for Weapons (and click Save) and run the Mass Repair/Salvage that it at least attempts the work. It does in 0.45.3.

**Comment by sixlettervariables** [comment]
Ok, the actual bug is that the dialog does not use the options you are shown when actually performing the repairs.

**Comment by sixlettervariables** [comment]
Fixed in #1039
