### ISSUE TITLE
Dragoon Rating (FMM:Rev) Decreases as Dropship Carrying Capacity is Used

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/mekhq#103]
[337thNaval.zip](https://github.com/MegaMek/mekhq/files/304808/337thNaval.zip)

I thought I'd experiment and see if MHQ can handle my multi-regimental Chaos Campaign force. So far, it seems to be doing a great job. I did notice that as I start adding units that fill up my dropship transport bays, my Dragoons rating for transportation goes down. I have enough carrying capacity for everything, so I'm not sure why this is happening. 

I am still using 3.28. I plan to upgrade to 3.29 this weekend and try again, but I didn't see anything in the release notes that appears to address this one.

**Comment by dericpage** [comment]
We'll need your custom units files to be able to open that campaign.

**Comment by mkerensky** [comment]
[mechset.txt](https://github.com/MegaMek/mekhq/files/306955/mechset.txt)
[Customs.zip](https://github.com/MegaMek/mekhq/files/306956/Customs.zip)
I continued adding units, and my transportation rating went back up again when I added more ground units. It is still not at full. Attached is the newer copy that shows this change. 
[337thNaval.zip](https://github.com/MegaMek/mekhq/files/306962/337thNaval.zip)

Also, the original campaign attachment does have a problem with forceIDs.  I started building this unit before I figured out how to work with forces, and I did some manual editing of the campaign file that gave me duplicate ForceIDs.  I figured out how to fix this and it's been resolved in the copy just attached.

**Comment by pheonixstorm** [comment]
Check the campaign options and make sure you have the unit rating set to Dragoons and not IO Beta.  I can see no other way why the transport rating would go down like that other than using the IO rating.

**Comment by mkerensky** [comment]
My faction is Mercenary, my unit rating is set to use FMM:Rev and my Mercenary tab contract payment is set to use IO Beta TO&E value.

**Comment by pheonixstorm** [comment]
I will try to look at it if I find the time. First I've heard of the dropship rating issue though...

**Comment by mkerensky** [comment]
I've confirmed that it keeps going up as I add more ground units - meks and tanks.  It was only off when I had a force of only aerospace craft, and then it only went down when I started adding aerospace fighters.   With just warships, dropships, jumpships and small craft it was correct.

**Comment by dericpage** [comment]
When you were adding fighters, were you also adding Aero techs at the same time?  If not, it may have been your tech support percentage that was dropping.

**Comment by mkerensky** [comment]
I was adding Aero techs, but not (enough?) astechs - I have roughly 4 astechs per lance and one tech/mechanic per vehicle/squad. When I started, I had mostly large spacecraft with a couple of crewmen each assigned aero tech or astech as a secondary role.  

By the time I finished my unit file, I added a reinforced regiment of mechs, vehicles, infantry and battle armor. In the process, my dropship rating went back up to 97% or so.  I was looking at the actual rating report with a breakdown of numbers by category, and I'm sure it was my dropship rating that went down. I opened a separate ticket where tech support also dropped over the astech issue, but that has now returned to 100% and my dropship rating has not quite done so.

**Comment by Dylan-M** [comment]
Are you still having issues?

**Comment by mkerensky** [comment]
Yes this is still an issue. I see a fix was attempted in the latest build (I'm still using 0.3.32). I'll try the new one and report back.

**Comment by mkerensky** [comment]
I checked this under 0.41.24 and it doesn't seem to be fixed.  I had 5 salvage-grade dropships that I couldn't transport, 37 mothballed units, and 525 light vehicles that had to fit in heavy vehicle bays.  I tried to correct all of these possible issues separately, then saved the game, closed MHQ and loaded it again. No good. My transportation rating seems to be stuck at 98% on the dropship rating. I can attach another copy of the campaign file if it would help, though it really hasn't changed significantly over the copies attached earlier in this thread.

**Comment by dericpage** [comment]
It's your fighters.  Going by your last campaign upload (on June 9), you had 132 fighters but only 90 fighter bays.

**Comment by mkerensky** [comment]
[Dragoons Rating.zip](https://github.com/MegaMek/mekhq/files/528363/Dragoons.Rating.zip)

Strange. I never had that many fighters.  Small Craft plus Fighters sounds about right.  Here's a current copy - my test copy where I added enough transports to completely cover all of my bay needs for each type.

**Comment by dericpage** [comment]
The small craft are likely the issue.

**Comment by dericpage** [comment]
I just merged in the commit from my previous interaction.  That should take care of this issue with the next release.

**Comment by mkerensky** [comment]
Confirmed, this is fixed in 0.41.26.  Thanks!
