### ISSUE TITLE
Allow 0.0% intensity in AtB Settings

### ISSUE THREAD

**Issue by rogueranger1993** [MegaMek/mekhq#1036]
I like to use MekHQ to track my IRL tabletop games, and the AtB markets for units and contracts are very useful. Rather than ask for those two markets to be made available outside of AtB mode, I thought about a second option to give a similar result - allowing the AtB intensity setting to be set to zero. This would allow me to use the AtB markets, but would eliminate the ATB-generated scenarios, thereby allowing me to generate contract scenarios for my games in any way I please with minimal hassle, and it seems like it wouldn't need too much effort to implement such a change on the part of the Devs, either.

**Comment by sixlettervariables** [comment]
Implemented in #1038.
