### ISSUE TITLE
Tech Support Percentage Too Low?

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/mekhq#104]
I have a tech assigned to every unit (aerospace fighters and small craft) and the rest of my force consists of large vessels that are supposed to provide all of their own tech support from their crews. 

Despite this, my FMM:Rev support rating is only 56%.   Is this a bug or am I doing something wrong?
[337thNaval.zip](https://github.com/MegaMek/mekhq/files/304819/337thNaval.zip)

**Comment by dericpage** [comment]
Do you have full astech teams for all your techs?  If so, we'll need your custom units files to be able to open that campaign.

**Comment by mkerensky** [comment]
No it would seem that I don't. When I hire a full pool, I get to 100% tech support. I have a few small craft crewmen acting as astechs as a secondary role. How many am I supposed to have?

My complete astech pool shows that I need 1718 astechs. This is for 68 mechs, 80 aerospace fighters, 94 vehicles and 52 small craft, plus a warship, 10 jumpships and 36 dropships (yes I'm building a giant force) and the astech pool seems excessive for the number of small units in play. 
I'm not sure exactly which custom unit files you need - I've attached one containing the truly customized warship and two mechs. I have a few other unofficial designs flagged as custom, but they're standard with megamek. I have also added entries to mechset to cover my custom units.
[Customs.zip](https://github.com/MegaMek/mekhq/files/306950/Customs.zip)
[mechset.txt](https://github.com/MegaMek/mekhq/files/306951/mechset.txt)

**Comment by pheonixstorm** [comment]
If the numbers you posted are accurate you should have 1764 Astechs and 294 techs. Not sure how the secondary astechs are counted in HQ, but the above is by the book numbers. Large craft such as Dropships, Jumpships, Warships, and Space Stations do not need astechs.

Each tech team is 1 tech and 6 astechs

**Comment by dericpage** [comment]
A full astech pool is 6 astechs per tech minus any permanent astechs you already have.  Similarly, your medic pool should be 4 medics per doctor.

**Comment by mkerensky** [comment]
Is it possible to create a 'personnel platoon' as described in FMM:Rev?  I was looking to set up a couple of regimental admin, astech and medical units.

**Comment by dericpage** [comment]
That's better asked on the Forums rather than here.

**Comment by Dylan-M** [comment]
Closing as invalid.
