### ISSUE TITLE
45.2 : exception when using GM mode to edit VTOL damage

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#1057]
[a.zip](https://github.com/MegaMek/mekhq/files/2813166/a.zip)

Exception error when trying to use GM -> Edit damage for the Harpy VTOL that is in salvage mode, see log file for error.

**Comment by neoancient** [comment]
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: (minimum <= value <= maximum) is false
	at javax.swing.SpinnerNumberModel.<init>(Unknown Source)
	at javax.swing.SpinnerNumberModel.<init>(Unknown Source)
	at megamek.client.ui.swing.UnitEditorDialog.initArmorPanel(UnitEditorDialog.java:235)
	at megamek.client.ui.swing.UnitEditorDialog.initComponents(UnitEditorDialog.java:135)
	at megamek.client.ui.swing.UnitEditorDialog.<init>(UnitEditorDialog.java:120)
	at mekhq.gui.adapter.UnitTableMouseAdapter.actionPerformed(UnitTableMouseAdapter.java:494)

**Comment by sixlettervariables** [comment]
Somehow that VTOL has more internal listed than it should in its rotor.

**Comment by sixlettervariables** [comment]
If you search in your CPNX for:
```xml
<armor points="4" type="Internal"/>
```
Change points to 3 and save it, that should clear that up.

Not sure how that happened.

**Comment by sixlettervariables** [comment]
Ok that was weird.
```java
    @Override
    public void updateConditionFromPart() {
        if(null != unit && unit.getEntity() instanceof VTOL) {
            unit.getEntity().setInternal(unit.getEntity().getOInternal(VTOL.LOC_ROTOR) - damage, VTOL.LOC_ROTOR);
        }
    }
```
Damage is `-1`, so after loading the unit it actually adds one to the internal.

**Comment by sixlettervariables** [comment]
Apparently damage is `-1` because:
```java
    @Override
    public void updateConditionFromEntity(boolean checkForDestruction) {
        if(null != unit) {
            if(IArmorState.ARMOR_DESTROYED == unit.getEntity().getInternal(loc)) {
                remove(false);
            } else {
                damage = unit.getEntity().getOInternal(loc) - unit.getEntity().getInternal(loc);
                if(unit.isLocationBreached(loc)) {
                    breached = true;
                }
            }
        }
    }
```

**Comment by sixlettervariables** [comment]
Because the Rotor part has a damage of -1.
```xml
<damage>-1</damage>
```

**Comment by sixlettervariables** [comment]
Ok so two fixes to your CPNX.

Search for:
```xml
<armor points="4" type="Internal"/>
```
...and make points 3.

Search for:
```xml
<damage>-1</damage>
```
...and make damage 0.

**Comment by sixlettervariables** [comment]
Fixed in the next release.
