### ISSUE TITLE
Medics do not get random skills when generated. 

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/mekhq#106]
Medics seem to always get generated with a skill of 11+. So far as I can tell, all other unit types randomize properly. This is true of medics on the personnel market (using Dylan's method with default settings), Hire new > Medic and Hire Personnel in Bulk.

**Comment by pheonixstorm** [comment]
The medic skill never changes. That itself is not a bug. Medics not having other skills... That could be a bug but I doubt it.

**Comment by mkerensky** [comment]
I figured out how to change this and the astech skill in the campaign options, which meets my needs. I'll call this closed if those skills aren't actually supposed to change according to canon rules.
