### ISSUE TITLE
Modifiers for salvaging a component

### ISSUE THREAD

**Issue by inqistor** [MegaMek/mekhq#1075]
Modifiers for salvaging a Mech component were the same in all MekHQ versions I have checked so far, but closer inspection of StratOps on page 191, gives example in fourth paragraph, indicating that time & modifier should be based on percentage damage to component, so using Repair part of MASTER REPAIR TABLE, not Destroyed part, as it is now (there is +3 difficulty, and 240 minutes now, for all locations).

The overall description is quite lacking in limbs reclamation department, but I wonder, if by analogy to Blown Off Arms with destroyed Left/Right Torso, shouldn't all parts attached to Central Torso albo become Blown Off when CT is destroyed?

**Comment by inqistor** [comment]
I took a quick glance how to repair first issue, you have to change two parts of MekLocation.java:
You have to exchange line 380 `				return 240;`
with lines 393-400
```
               if (percent < 0.25) {
			return 270;
		} else if (percent < 0.5) {
			return 180;
		} else if (percent < 0.75) {
			return 135;
		}
		return 90;

```
with probably adding check for destroyed component 
`if (percent==1.00) return 240;`
, or some logical check for IsDestroyed if it is already defined.
Same change for Difficulty by changing line 
409 				`return 3;`
with lines 422-429

```

		if (percent < 0.25) {
			return 2;
		} else if (percent < 0.5) {
			return 1;
		} else if (percent < 0.75) {
			return 0;
		}
		return -1;

```

with same additional check for destroyed component:
`if (percent==1.00) return 3;`

That should make salvaging of limbs consistent with StratOps

**Comment by sixlettervariables** [comment]
Okay I've got a pull request up which should resolve this issue. MekHQ uses `MissingMekLocation` to handle the `percent == 0.0` logic (percent is not the percent destroyed, but rather the percent intact).
