### ISSUE TITLE
GM adding Infantry doesn't add all soldiers

### ISSUE THREAD

**Issue by pjfarland** [MegaMek/mekhq#1076]
MekHQ 45.3
Java version 1.8.0_201
Platform Windows 10 10.0 (amd64)

GM Adding an infantry unit from AtB Personnel for hire only adds the Lead soldier and unit. The additional soldiers still cost money.
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2858093/mekhqlog.txt)

[Last of the Jaguars30600102.zip](https://github.com/MegaMek/mekhq/files/2858099/Last.of.the.Jaguars30600102.zip)

**Comment by sixlettervariables** [comment]
You referring to doing "Hire full complement"?

**Comment by sixlettervariables** [comment]
I've got a fix for this in #1080

**Comment by sixlettervariables** [comment]
Fixed in the next release.
