### ISSUE TITLE
Feature request: GM recharging JumpShip Drive

### ISSUE THREAD

**Issue by inqistor** [MegaMek/mekhq#1078]
I see few similar requests already, but GM action should be easiest to implement.

It seems, game assumes that you have your own JumpShip all the time. However you should be able to hire a new one just for jump to another system, and in that system another JumpShip can be waiting with already charged Drive. Or your JumpShip could use Recharge Station.
Currently GM can only move directly to planet in a system, which takes neither time, nor money. And planet can be several weeks of travel from Jump Point, so your Drives would recharge faster, than travel takes. Just please add option for GM to Recharge Drive immediately.

**Comment by pjfarland** [comment]
Perhaps a few enhancements. A random roll for available JS would be great as well. 
Also, adding functionality for Lithium-Fusion Battery powered "double" jumps.

**Comment by Windchild292** [comment]
Fixed in PR #1359
