### ISSUE TITLE
MegaMekLab doesn't recognize damaged shoulder

### ISSUE THREAD

**Issue by inqistor** [MegaMek/mekhq#1079]
AFAIK it was the same in all versions so far. It is little tricky to recognize, as you need to put damaged Mech in MekHQ into Mek Lab. Save is from MekHQ 0.45.3.

Lets assume, that after battle you got Mech with damaged shoulder. That arm have weapon installed, but since this is middle of invasion, you don't have neither parts, nor time to replace whole arm, so you decide to change location of weapons.
It is quite easy in Mek Lab. In fact program assumes that such modification takes neither time, nor money, but it seems damaged shoulder is not recognized by Mek Lab. After repair, whole arm is perfectly functioning, despite using no extra parts for repair. I can't issue damaged shoulder manually, as it is impossible to remove shoulder from arm in Critical Locations.

[Repair.zip](https://github.com/MegaMek/megameklab/files/2860287/Repair.zip)

**Comment by RexPearce** [comment]
Looks like there are two issues here: 1) hip/shoulder damage is not preserved, and 2) changing weapon location can sometimes take 0 time.

**Comment by NickAragua** [comment]
Fixed with #2095
