### ISSUE TITLE
Import from MUL Option Does Not Seem to Load Saved Abilities

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/mekhq#108]
I have a bunch of MUL files with pilot abilities and custom mech settings saved into them.  Imported pilots are not getting the abilities, but they are getting their skills and the mech settings (such as reduced MG ammo) are importing correctly.  I have attached one of the MUL files for testing. 
[337th_2nd_Titan.zip](https://github.com/MegaMek/mekhq/files/319146/337th_2nd_Titan.zip)

MekHQ version is 0.3.29.
These MUL files were created with previous versions of MegaMek. The last save was probably under 0.41.15.

**Comment by pheonixstorm** [comment]
I don't think the MUL import was designed to handle this though I could be wrong. Were you able to do this under a previous version of HQ?

**Comment by mkerensky** [comment]
This is the first time I've used HQ. I saw that HQ can handle SPAs for pilots and crews as well as MUL imports and made a first-timer's assumption that HQ would import the SPAs if the MUL file contained them.

**Comment by pheonixstorm** [comment]
There is an import for personnel to transfer from one campaign to another is this is what you are trying to do. If this is an import from something you did in MM then it will probably have to be a feature request to do so. ralgith would know more about it, though with RL claiming his free time it might be awhile before you get an answer.

**Comment by mkerensky** [comment]
I was porting a campaign into MekHQ from saved MM files and a word document. I just edited all of the HQ versions of my pilots and gave them their SPAs back.

**Comment by Dylan-M** [comment]
Fixed by #692
