### ISSUE TITLE
Repair not Completed

### ISSUE THREAD

**Issue by BairdEC** [MegaMek/mekhq#1085]
MekHQ 0.45.3
Win 10
Java (build 1.8.0_201-b09)

A tech was assigned to replace an arm before the game was saved.  On reloading, I advanced the day and the  daily log reported that the repair was successful.  The unit pane still showed the arm as destroyed, and no arm components could be replaced.  The tech was available for work again.  I reloaded the save file twice, and the same thing happened each time.

![repair1](https://user-images.githubusercontent.com/38081112/52902273-cda86c80-31cb-11e9-88da-2133ef9df657.PNG)

![repair2](https://user-images.githubusercontent.com/38081112/52902275-d26d2080-31cb-11e9-8c07-113c8516fd2c.PNG)

[Steel Recon30250730.zip](https://github.com/MegaMek/mekhq/files/2872127/Steel.Recon30250730.zip)
[customs.zip](https://github.com/MegaMek/mekhq/files/2872129/customs.zip)

**Comment by sixlettervariables** [comment]
Bizarre. The replacement listed for that left arm is a heat sink...that's not gonna work.

**Comment by sixlettervariables** [comment]
Ok, so the replacement ID is not a heat sink *but* the replacement part gets grouped with another spare and its ID gets changed. So a heat sink ends up with that ID. I'm trying to identify a fix for your campaign so you can keep on playing.

**Comment by sixlettervariables** [comment]
Try searching for `<replacementId>19538</replacementId>` and changing that number to 6218.

**Comment by BairdEC** [comment]
That worked.  Thanks for looking at it!

**Comment by sixlettervariables** [comment]
Fixed in the next release.
