### ISSUE TITLE
Cant start Special Mission/Big Battle from MekHQ

### ISSUE THREAD

**Issue by Arakash0** [MegaMek/mekhq#1086]
### Environment
MeqHQ 0.45.3
campaign was transferred from 0.43.9 but prior to the bug had no other issues.
Java version 1.8.0_181
Windows 7

### Description
Playing an ATB campaign in MeqHK, i had transferred a save from 0.43.9 and i played 10+ battles in 0.45.3 with no problems until i got a special mission/big battle. I deploy a unit to the mission, but pressing 'start game' doesn't launch megamek.
The first time it happened for a 'big battle' mission, so i just resolved it manually as a defeat(thinking it might just be a one off), but it happened again with the Star League Cache mission you can see in the save. When i asked about it on the slack channel they suggested i report it here.

### Files
[campaign save.zip](https://github.com/MegaMek/mekhq/files/2872148/campaign.save.zip)
[mechfiles.zip](https://github.com/MegaMek/mekhq/files/2872149/mechfiles.zip)
[mekhqlog.zip](https://github.com/MegaMek/mekhq/files/2872150/mekhqlog.zip)

**Comment by CrimsonThunderSB** [comment]
I also...cannot start any special missions, and just like Arakash0, I deployed a unit to the special mission, clicked start, and nothing happens, and this first occurred to me when I attempted to conduct an officer duel special mission, and again, it happened with a civilian riot big battle that will also be uploaded to this post.

[Stormbringing Destroyers bugged.zip](https://github.com/MegaMek/mekhq/files/2873509/Stormbringing.Destroyers.bugged.zip)

**Comment by HammerGS** [comment]
NPE in file:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.gui.BriefingTab.startScenario(BriefingTab.java:650)
	at mekhq.gui.BriefingTab.lambda$initTab$8(BriefingTab.java:268)
```

**Comment by sixlettervariables** [comment]
Line 650: https://github.com/MegaMek/mekhq/commit/a6186f93b58650c976fcf99334387d1f5afe77d4#diff-a97447c3a5f57c4cf521fedd258c2e66R650

**Comment by NickAragua** [comment]
This'll be fixed for the next dev release.

As a work-around, you can try to assign a full force to the big battle/special mission, rather than an individual unit.
