### ISSUE TITLE
Empty Unit list with new campaign

### ISSUE THREAD

**Issue by blackcatf** [MegaMek/mekhq#1087]
### Environment
I'm in version 0.44
(Win10, Java v8 update 201)

### Description
When I start a new campaign, the marketplace unit list is showing up blank [edit: for both the "Purchase Unit" and "Unit Market..." options]. I think the log is showing that it loaded almost 9k units, but only see 17 files loaded (from Cannon Variants and 201st Stryker Regiment folders) during looking in individual folders; do I have to do something upon installing the new version to get it to register the contents of the ZIP folders (MML is loading the cache files just fine). 

I've been able to reproduce the issue on every new campaign (I have another issue with loading a campaign created in v0.42 that I think might be related MHQ isn't loading any unit files but didn't attach that campaign file here).

I'm new to reporting bugs for these programs, so please let me know if I need to add anything else.

### Files
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2872165/mekhqlog.txt)

**Comment by sixlettervariables** [comment]
Per the log: `8899 units loaded.`

Can you attach your campaign.

**Comment by blackcatf** [comment]
I don't have a campaign file because I was starting a new one. I have a different error when loading campaigns made in v0.42 that I think might be related. Here's the campaign file for that; please note that I added ".txt" to the end of the file name to allow it to upload here.
[Battle Born30530704.cpnx.log](https://github.com/MegaMek/mekhq/files/2872337/Battle.Born30530704.cpnx.log)

**Comment by blackcatf** [comment]
I found a workaround for my problem: I can build the unit in MegaMek and save/import the MUL. It still seems odd that I can't add units directly from the MekHQ interface (with a GM mode option, maybe), but this will work for now.
