### ISSUE TITLE
REF (UI, Large Campaign)

### ISSUE THREAD

**Issue by poaw43** [MegaMek/mekhq#1092]
The current dropdown menus for certain actions (assigning techs/personnel to craft) scale poorly for larger units. It makes selecting a specific mech out of dozens of choices tedious and susceptible to errors. A more manageable menu is used for selecting techs when mothballing/activating and customizing units:

![ui request](https://user-images.githubusercontent.com/47794901/53044649-976a3600-34c6-11e9-8ad1-d67408e5d3db.jpg)

**Comment by VicenteCartas** [comment]
I've been looking at the code, I'm going to take a stub at this of keeping the current UI for smaller quantities (like 12 units or less), and use the proposed UI (with column ordering and search filters) if there are more than that.
