### ISSUE TITLE
Request for option in MegaMek HQ Tech assignments

### ISSUE THREAD

**Issue by MageOhki** [MegaMek/mekhq#1098]
Two parts:
First, when selecting techs to say, mothball or activate, it goes in order of tech assignment.  Is it possible to have Techs in that box ordered by *time*?
Second: in Repair Bay, same request, but leave 'assigned' tech on top, and also *leave* him on top til at no time left.  (Current behavior of Repair bay only puts the tech on top at once.)

I'm sure I'll have *more* requests over time...

**Comment by MageOhki** [comment]
Err, just realized, by *time* in the sense of how much time the tech has to work on projects, that day.

**Comment by Windchild292** [comment]
The first has been implemented, the second is a campaign option that does not work as intended. Will open a bugfix for it shortly.
