### ISSUE TITLE
[0.3.29 : Bug] Unassigned patients no longer get selected automatically

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#110]
Previously when pressing the assign (patient) button, the next unassigned patient will be selected automatically. Therefore you can keep on pressing assign. In this latest release, the next unassigned patient no longer get selected automatically. We will have to click patient, click assign, click patient, click assign and so on, a lot of clicking.

**Comment by Akjosch** [comment]
... or alternatively, select multiple patients at once and click "Assign" once.

I'll see how to best implement that. I think I'll just allow the "Assign" button to pick the first available patient when no-one is selected.

**Comment by SirMegaV** [comment]
Yup. I'm using multiple select now. I used to just click assign, so much
faster, especially  after a game with an infantry battalion.

**Comment by Akjosch** [comment]
... and fixed. Pick a doctor, click "Assign" until you can't click anymore, then pick another doctor and repeat until out of patients, doctors, or your mouse breaks down. ;)
