### ISSUE TITLE
Feature Request: Expanded Selection Options/Menus

### ISSUE THREAD

**Issue by MageOhki** [MegaMek/mekhq#1102]
In the TOE tab, the assignment of mech, armor, et al has a submenu like:
![2nd capture](https://user-images.githubusercontent.com/46218554/53234691-58b2b800-364d-11e9-8ec6-b1a3b5a69d56.PNG)
Would it be possble to get other tabs (like Personnel, see below) to do the same if appros?

![1st capture](https://user-images.githubusercontent.com/46218554/53234732-6cf6b500-364d-11e9-84e0-a0850277ba5f.PNG)

(Sorry for the bad circle, but first time using the Snipping tool in WIndows 10)

**Comment by VicenteCartas** [comment]
This and #1092 can be combined together, I'm working on a proposal for this.
