### ISSUE TITLE
45.3 Refit started in MekHQ-MekLab not working

### ISSUE THREAD

**Issue by Arakash0** [MegaMek/mekhq#1114]
### Environment
MeqHQ 0.45.3
Java version 1.8.0_181
Windows 7

### Description
A Custom refit started from inside the MekHQ- MekLab doesnt show its being worked on in the Daily log even after all the parts arrive.

You can see it in the campaign file, the Bombadier-12D thats being supposed to be refitted to a new model but nothing is happening in the daily log.

I dug through my older saves to find a save with this bug, as it was discussed on the forum here: https://bg.battletech.com/forums/index.php?topic=64522.0

### Files
[Campaign File.zip](https://github.com/MegaMek/mekhq/files/2902268/Campaign.File.zip)
[mekhqlog.zip](https://github.com/MegaMek/mekhq/files/2902270/mekhqlog.zip)
[mechfiles.zip](https://github.com/MegaMek/mekhq/files/2902271/mechfiles.zip)

**Comment by VicenteCartas** [comment]
Is this the log file after you try to do the refit?

**Comment by Arakash0** [comment]
Just to check i did gave you the right file 'mekhqlog.txt' is it right?
I believe that's several days, possibly a week(ingame) after i ordered the refit(its an old save from days ago i honestly dont remember). I believe before I uploaded it I also went into GM mode and got all the in transit parts to deliver now to make sure it still wasnt waiting on parts.

**Comment by VicenteCartas** [comment]
That's the right file. The log file gets rewritten every time you start the app, so the best way for us to see if it contains more info would be:
- Start mekhq
- Try to do the refit
- Close mekhq
- Upload that mekhqlog.txt file

That way, if there was an error when you tried to do the refit, there are more chances it will be captured in the log file.

**Comment by Arakash0** [comment]
The problem is, if i cant tell if the refit is working or not without passing a day(or sometimes weeks for the parts to arrive), how could i do the refit then post a log+save directly afterwards?

Just today i attempted to replicate this bug by attempting random refits then seeing if they got stuck and after 3 attempts where they all worked as normal i didnt see the bug.

**Comment by VicenteCartas** [comment]
Not sure actually. Maybe you can add the parts needed first (via GM tools) and then attempt the refit and pass a day to see if there was work actually done?

**Comment by Arakash0** [comment]
Found a way to replicate it. I did what you said in getting the parts first, but i also manually created the exact same Bombadier variant in the MekLab in the game, giving it a different name.
The same bug appeared, but this time i have the log file from right after I pressed 'Begin Refit'.

[campaign file.zip](https://github.com/MegaMek/mekhq/files/2903071/campaign.file.zip)
[mechfiles.zip](https://github.com/MegaMek/mekhq/files/2903072/mechfiles.zip)
[mekhqlog.zip](https://github.com/MegaMek/mekhq/files/2903074/mekhqlog.zip)

**Comment by sixlettervariables** [comment]
I'm unable to reproduce this in 0.45.4 or 0.45.5-SNAPSHOT. If this issue persists let me know and I'll reopen this issue.
