### ISSUE TITLE
Mekhq Adds # of missions partipated in counter

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#112]
I'd like to see a counter, similar to the kill counter, in the pilot details page showing number of missions completed.

**Comment by pheonixstorm** [comment]
In addition to the log entries or counted separate from the log entries? I ask as this would fall in line with my log saver patches and possibly my Time in Service stuff (or auto ranking if I ever code it)

**Comment by VampireSeraphin** [comment]
Separate & in addition to the log entries. I was thinking something simple, just a line similar to the kill counter, sitting above the list of log entries, with Missions Completed:5 or something similar.
