### ISSUE TITLE
Dates are cut off in Personnel log display

### ISSUE THREAD

**Issue by Keatonmac** [MegaMek/mekhq#113]
Hello, developers...

Posting a bug for MekHQ 0.3.29.  When reading a character's Personnel bio, the final number of the date is missing.  You cannot see the year the action took place, just the day and month, and "302" (for 3025, as an example).  An example is this screenshot #1.   

![screen shot i - bio showing missing date](https://cloud.githubusercontent.com/assets/20175361/16398128/2e3d2dfa-3c8e-11e6-86b9-3dafa27c7987.png)

However, if you attempt to Edit Personnel Log, you'll see the date is correctly entered.  It's just not showing on the screen.   

![screen shot ii - edit personnel log](https://cloud.githubusercontent.com/assets/20175361/16398151/4be90c5c-3c8e-11e6-91f0-ffd1536f7bb0.png)

It's not a matter of window size - expanding the window to full size does not expose the missing year digit.  And I cannot find anything in the log file that indicates an issue...all years have four dates that I can see.  Further, this happens if you have developed a new campaign in MekHQ 0.3.29 or imported an existing one from 0.3.21 or older.   A PDF of the campaign file is included. 

[Desolation Angels30250201.pdf](https://github.com/MegaMek/mekhq/files/336063/Desolation.Angels30250201.pdf)

Thank you in advance for all your help...

Keatonmac

**Comment by Akjosch** [comment]
It looks like an Apple-specific styling problem. The default font used for those entries under Windows and Linux is significantly smaller (about the same as the one used in the personnel table on the left side), so they don't have that problem.

Too bad I don't have a system I can test this with. We'll see if I can try to make a fix regardless.

**Comment by Dylan-M** [comment]
@Akjosch I'll try and pull this down for checking today at work. About the only upside to using a Mac for my job ;)

**Comment by wildj79** [comment]
@Dylan-M Looks like @Akjosch fixed this.
![screen shot 2016-11-04 at 6 23 20 pm](https://cloud.githubusercontent.com/assets/2126857/20025395/eed2fc32-a2bb-11e6-8994-d34fe9b1b2d8.png)
