### ISSUE TITLE
ASF refit issues

### ISSUE THREAD

**Issue by pjfarland** [MegaMek/mekhq#114]
Problems with trying to refit either the Cheetah (all versions) or the Tomahawk (all except the C).  None of them will let you even see refit kits under the 'Customise' option.  Clicking on 'Choose refit kit' ends up with absolutely nothing happening.  The Tomahawk C will let you, though the icon for it is the Mech, not the ASF.

**Comment by pheonixstorm** [comment]
The icon issue should be an easy fix, not sure about the rest of it. Post the icon issue in the megamek forums or PM Hammer.
