### ISSUE TITLE
Scenario generation and RAT generation issues, 45.3- Possible FedCom 3058 Link

### ISSUE THREAD

**Issue by Mukaikubo** [MegaMek/mekhq#1140]
### Environment
What version of MekHQ does your issue apply to? 0.45.3
What operating system are you using?  Windows
What java version are you using? 1.8.0_201

### Description
Describe the issue and provide screenshots ingame if able.
I started a clean campaign on a fresh download of mekHQ. I built a simple 2-lance force and put it into a contract. The first campaign file provided (Banjos_sunday.cpnx) is right before new mission roll. When a new mission is generated, it cannot be selected- that is, it does not bring up any information in the pane for the scenario, see screenshot_1. If I save after generating a mission and reload, I get the provided campaign file (Banjos_monday.cpnx). Generated missions now show up normally in the proper scenario pane, but enemy forces do not generate. (screenshot_2). Allied and civilian forces do generate. I switched from RAT generator to using just the Total Warfare RAT, and I got partial generation of forces, but the original problem of no info in the scenario pane still holds. There are no custom units/factions, or there shouldn't be since this is a clean install. If I launch the scenario and manually add units and play through in Megamek, the scenario resolves correctly.

This *appears* to be linked to the problem noted in  #663 where a FedCom enemy in 3058 is causing RAT issues. If I manually replace the enemy to the free worlds league in Banjos_sunday and continue to advance time until I get a scenario, the scenario generates normally, the scenario is selectable with information being displayed correctly, and enemy forces populate as they should. 

### Files
Banjos_sunday is the campaign file before advancing to a new week. On advancing, new scenarios are generated with errors as above.
Banjos_monday is a campaign file after having advanced a few weeks to show a lack of generation of the correct forces.
Screenshots 1 and 2 are of these two situations, with annotations in red.
The logfile is attached as mekhqlog_errors.

Or at least, it should all be, since I never made one of these things before. 

[mekhqlog_errors.txt](https://github.com/MegaMek/mekhq/files/2928080/mekhqlog_errors.txt)
[Banjos_Sunday - Copy.txt](https://github.com/MegaMek/mekhq/files/2928083/Banjos_Sunday.-.Copy.txt)
[Banjos_Monday - Copy.txt](https://github.com/MegaMek/mekhq/files/2928084/Banjos_Monday.-.Copy.txt)
![screenshot_1](https://user-images.githubusercontent.com/17595539/53761090-a8398500-3e92-11e9-8007-6451385f2a05.png)
![screenshot_2](https://user-images.githubusercontent.com/17595539/53761092-aa034880-3e92-11e9-9e8b-9fec4ce8095f.png)

**Comment by Mukaikubo** [comment]
I belatedly realize it'd be better to provide a zip file with the .cpnx files inside than renaming them to .txt files, to avoid possible issues there. Attached a zip file with both campaign files. 
[Banjos_Campaignfiles.zip](https://github.com/MegaMek/mekhq/files/2928144/Banjos_Campaignfiles.zip)

**Comment by wildj79** [comment]
Similar to issue #1106, looks like it should have been fixed in pull request #1108 .

**Comment by Windchild292** [comment]
Fixed by #1108, with the remaining issue being a duplication of #663

#2063 fixes further NPEs discovered while testing this.
