### ISSUE TITLE
[0.45.3 : Bug] [ATB] Cannot Generate Scenario

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#1141]
### Environment
0.45.3

### Description
New scenarios not auto generating on Mondays. GM generate new scenarios not working either. Nothing in log.

Replicate: Load campaign file, select mission "#051". Hit GM Generate Scenario, nothing happen. Go to next Monday, no scenario generated.

### Files
[SirMegaV25090121.zip](https://github.com/MegaMek/mekhq/files/2930595/SirMegaV25090121.zip)
[Customs - SirMegaV - Mechfiles.zip](https://github.com/MegaMek/mekhq/files/2930596/Customs.-.SirMegaV.-.Mechfiles.zip)

**Comment by NickAragua** [comment]
The Opfor Morale is "Very Low", which, according to AtB rules, results in no scenarios being generated for the month. Of course, I had to take MekHQ through a debugger to notice that. :)

**Comment by SirMegaV** [comment]
Very very sorry about that. My bad. :)
