### ISSUE TITLE
45.4 Snapshot 2-27 issue regarding saving as in it won't.

### ISSUE THREAD

**Issue by MageOhki** [MegaMek/mekhq#1142]
In 45.4 snapshot 2-27
Windows 10
Java 8 1.91

45.4 Snapshot 2-27 after recovery from an idle state (if unaware, MekHQ if walking away will throttle down and release memory) does not properly save campigan or log files files.  It will mark the file, but not fill it with *anything*, leaving the save file at zero bytes.  This applies to export files as well.  Further, other issues pops up.
Pre idle state memory load: approx 4400 megs, idle state load 800mb, returned to between 3100 and 3400 mb when this happened.

### Files
Provide the .cpnx campaign file that this issue occurs in.   **Can't**
Provide any custom units that you are using in this campaign so that it will load on the developers machine.  **No point.**
And provide the mekhqlog.txt file for any NPE's or errors that MekHQ might be reporting.  
**Does not save properly, no info.**

**Comment by sixlettervariables** [comment]
As a quick note I can't reproduce this on my W10 machine, but that doesn't mean it isn't something on our end (just yet).

**Comment by sixlettervariables** [comment]
I've made some attempts this AM to reproduce this, but am unable to do so on either my Win10 desktop or my Macbook.
