### ISSUE TITLE
0.45.4 Cant pay-off/delete loan 

### ISSUE THREAD

**Issue by Arakash0** [MegaMek/mekhq#1148]
### Environment
MeqHQ 0.45.4 
Java version 1.8.0_181
Windows 7

### Description
Completing Loans by either "Pay off full balance" or via GM Tools "Remove this Loan" does not remove the loan, and it continues to deduct payments after every month.

No errors visible in the log.

In order to replicate the issue, load the save, go into finances screen then attempt to pay-off or remove the loan in that screen.

I guess as a workaround ill have to add myself a monthly cash asset to repay the monthly deduction.

### Files
[campaign save.zip](https://github.com/MegaMek/mekhq/files/2973686/campaign.save.zip)
[mechfiles.zip](https://github.com/MegaMek/mekhq/files/2973687/mechfiles.zip)

**Comment by VicenteCartas** [comment]
I'll look at this, may be related to the money changes.

**Comment by VicenteCartas** [comment]
This was an issue with the money changes, thanks for reporting it!
