### ISSUE TITLE
[Refits] WoB Omni-fighter refit problems

### ISSUE THREAD

**Issue by pjfarland** [MegaMek/mekhq#116]
The three WoB Spectral Omni-fighters; Shade, Rusalka, and Striga seem to have their Omni status messed up.  The refits on them show as Maintenance or Factory.  It looks as if it's because of the CASE in them.  In all three types the CASE shows up in only in ones with ammo, not in every location that has ammo, and not in consistent locations across the variants.

**Comment by HammerGS** [comment]
Fixed as part of this Megamek commit (https://github.com/MegaMek/megamek/commit/0bb34bc231288c65de21605951231fb1a7735feb).
  

Added the Omni tag which was missing.
