### ISSUE TITLE
New Campaigns Fail to Load

### ISSUE THREAD

**Issue by BairdEC** [MegaMek/mekhq#1161]
### Environment
MekHQ 0.45.3 and 0.45.4
Java (build 1.8.0_201-b09)
Win10

### Description
New campaign files cannot be loaded and cause MeqHQ to crash to the desktop.  The file loads about 75% of the way according to the progress bar, then the loading screen closes.  The initial screen with the start new campaign, load, and quit buttons displays for about half a second and also closes.  Both of the files below display the same behavior; both were created in 0.45.3, although the 0.45.4 version fails to load  the campaigns as well.

I suspect it has something to do with including protomechs since the last section in the log starts with :

Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: megamek.common.Protomech cannot be cast to megamek.common.Infantry

### Files
[customs.zip](https://github.com/MegaMek/mekhq/files/3001328/customs.zip)

[Unsheathed30650416.zip](https://github.com/MegaMek/mekhq/files/3001326/Unsheathed30650416.zip)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/3001342/mekhqlog.txt)

[Vespers Calling30650815.zip](https://github.com/MegaMek/mekhq/files/3001327/Vespers.Calling30650815.zip)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/3001348/mekhqlog.txt)

**Comment by BairdEC** [comment]
Adding a protomech point to a working campaign also causes the campaign file to fail to load.

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/3001439/mekhqlog.txt)
[Steel Recon - Copy.zip](https://github.com/MegaMek/mekhq/files/3001440/Steel.Recon.-.Copy.zip)

**Comment by NickAragua** [comment]
I would suggest trying the just-released 45.5.

**Comment by NickAragua** [comment]
Doh! Guess we didn't get all of the bugs.

**Comment by neoancient** [comment]
While Protomechs are more or less complete in MM and MML, they are not yet fully supported in MekHQ. That said, including them in a campaign shouldn't be causing errors that prevent it from loading.

**Comment by sixlettervariables** [comment]
The failing line of code is ~2 years old--and clearly broken--so it is odd that it showed up now. Disabling peacetime costs would fix this temporarily. If you search in your CPNX for these two and make them `false`, it should load your campaigns:
```xml
<usePeacetimeCost>true</usePeacetimeCost>
```

```xml
<showPeacetimeCost>true</showPeacetimeCost>
```

**Comment by BairdEC** [comment]
The campaign still failed to load after editing those two lines.

[Unsheathed30650416-1.zip](https://github.com/MegaMek/mekhq/files/3011443/Unsheathed30650416-1.zip)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/3011441/mekhqlog.txt)

**Comment by sixlettervariables** [comment]
Interesting, I do not get a failure with the campaign you supplied.

**Comment by BairdEC** [comment]
Maybe it's just time to reboot....
