### ISSUE TITLE
45.4 Can't add loot to scenario (it works in 45.3)

### ISSUE THREAD

**Issue by bsielski** [MegaMek/mekhq#1164]
Linux versions (45.3 and 45.4).
Java version "1.8.0_201"

In 45.4 "Done" button does nothing.
In 45.3 it works.
![](https://i.imgur.com/yLnHRyg.png)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/3017817/mekhqlog.txt)

**Comment by sixlettervariables** [comment]
The log shows the same issue as #1161, which was fixed yesterday. I'll confirm this fixes your issue before I close this issue.

**Comment by PhoenyxCullen** [comment]
I'm not having the error from #1161. I'm getting the start of this error:

Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
	at mekhq.gui.dialog.LootDialog.done(LootDialog.java:313)

My log is attached.
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/3052335/mekhqlog.txt)

**Comment by PhoenyxCullen** [comment]
Use CO Peacetime Op Costs is turned OFF.

**Comment by VicenteCartas** [comment]
Not related to #1161, it's converstion to create money.
