### ISSUE TITLE
0.45.4 No turrets in base defence?

### ISSUE THREAD

**Issue by molemanBT** [MegaMek/mekhq#1166]
Hi, performing a base defence and there are no turrets on my side, there usually are in this scenario
[The Fury30511110.zip](https://github.com/MegaMek/mekhq/files/3020514/The.Fury30511110.zip)

**Comment by Tamren** [comment]
Same here on v0.46. Did a base defence and the base turrets were listed as a group with 0 BV.

**Comment by CrimsonThunderSB** [comment]
Also seeing 0 turrets on base defense on 0.47

**Comment by Windchild292** [comment]
This might be the same as #1455, but I'm not 100% certain on that.

**Comment by plutonick** [comment]
Same here on 0.47.5

**Comment by molemanBT** [comment]
Still occurring on 47.6

**Comment by NickAragua** [comment]
Possibly fixed in PR #1975
