### ISSUE TITLE
[0.3.29 : Bug] Auto damage to Life Support during Edit Damage

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#117]
The moment you enter the GM Mode -> Edit Damage screen and exit 'OK' for aero, small craft, dropship and warship, their life support will be automatically damaged, regardless of any changes.

To test, just add an aero, GM Mode -> Edit Damage, do make any changes except for Life Support, press OK, view at Repair Bay.

**Comment by pheonixstorm** [comment]
Happens in 0.3.30 as well. Will look into that section of code and see what is happening.

**Comment by SirMegaV** [comment]
It has been like that for many releases. Can't remember when.

**Comment by arlith** [comment]
This is a MegaMek issue and not a MHQ issue.  The `UnitEditorDialog` that MHQ Is using comes from MM and you can reproduce this bug in MM by adding an ASF to the lobby, right clicking it and going to "Edit Damage..."  Add an ASF, edit damage, click ok, edit damage and you'll see that life support is checked.

**Comment by arlith** [comment]
Fixed in MegaMek/megamek@c916789.
