### ISSUE TITLE
AutoSave

### ISSUE THREAD

**Issue by mouldsgame** [MegaMek/mekhq#1171]
I would like to request and autosave option be added to MekHQ similiar to the one in Megamek.  I'm sure I'm not the only one who has lost power or had another issue and realized it's been weeks or even months of in game time since you last saved your game.  

Megamek's autosave provides a good template for autosaving the campaign (though I'm sure it's a much different programming task) in that there are two levels autoSave and Paranoid autoSave, and the autosave file can either be overwritten or optionally have the date appended to it.  For Regular Autosave it could happen on Monday's as part of the normal M-Su week, and for Paranoid Autosave daily.  It should probably also autosave whenever the Advance Multiple Days option is used.  

Thanks!  I know this probably isn't anyone's priority but I think it would be a good feature to have, that I'm honestly surprised no one has suggested before as far as I can tell.  I appreciate all the hardwork the past and current developers have put into entertaining me the last 15 years and look forward to all the ways that it will continue to do so into the futire.

**Comment by VicenteCartas** [comment]
Thanks for the idea! I agree it's a pretty nice quality of life improvement.

**Comment by sixlettervariables** [comment]
Implemented in #1187.
