### ISSUE TITLE
45.4 Can't select personnel on market with existing mechs.

### ISSUE THREAD

**Issue by Apocal43** [MegaMek/mekhq#1173]
MekHQ 45.4
Windows 10
Java version 1.8.0_201

### Description
On the personnel market of my campaign, freshly imported from 45.3. Whenever I click on a mechwarrior with an already owned mech, the selection will not take and instead select an individual information cell. Clicking on non-mech owning personnel still works fine. Clicking on elementals with their BA works fine. 

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/3050805/mekhqlog.txt)
[Phantom Frost Supernova Trinary42.zip](https://github.com/MegaMek/mekhq/files/3050807/Phantom.Frost.Supernova.Trinary42.zip)

**Comment by HammerGS** [comment]
Likely related too - 
https://github.com/MegaMek/mekhq/issues/1170

if so fixed here
https://github.com/MegaMek/mekhq/pull/1172

**Comment by VicenteCartas** [comment]
I'll double check this one to see if it's the same issue.

**Comment by VicenteCartas** [comment]
Yes, this is a duplicate.
