### ISSUE TITLE
Ultra AC 20 Ammo delivered with 0 Shots

### ISSUE THREAD

**Issue by BRDiger** [MegaMek/mekhq#1176]
### Environment
0.45.4 Windows 
 Java 1.8.0_181-b13
### Description
The delivered Ammotype is aquired but delivered with 0 shots.
![ultra ac 20](https://user-images.githubusercontent.com/18350902/55744565-86a15f80-5a35-11e9-953f-cbe6d246e733.PNG)

### Files
No Errors refering to this in the logs.

**Comment by sixlettervariables** [comment]
We would need the campaign file to figure this one out.

**Comment by BRDiger** [comment]
The Issue is gone with v0.46.0-rc.2. Might have been a porting issue. Do you still need a file?

**Comment by BRDiger** [comment]
After reading the release notes i´m certain it was Issue #1427
