### ISSUE TITLE
Damaged left/right thrusters cannot be repaired

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#118]
Aero and small crafts that suffered left/right thruster damages cannot be repaired in the repair bay (not listed in the task list). Edit Damages in the GM Mode doesn't help either, left/right thrusters not showing as a damageable part.

**Comment by pheonixstorm** [comment]
Does a save/load fix this or no?

**Comment by SirMegaV** [comment]
No. The only way was to replace the unit.

**Comment by neoancient** [comment]
Duplicated in #151 and fixed in 275c905. GM > Edit Damage relies on MM, and I have fixed the dialog there to show thrusters for small craft.
