### ISSUE TITLE
Mass Training improvement possiblities

### ISSUE THREAD

**Issue by MageOhki** [MegaMek/mekhq#1184]
Improvement/enhancement suggestion (aimed more at larger units)

On Mass training would it be possible to add the following:
1:  Special abilities
2: An option to remove those *without* the skill you see to improve.
(Ie, say you want to improve tech/mech, but *only* of those who already have the skill)

**Comment by Windchild292** [comment]
This can be closed, as I've opened up #1573 and #1574 to replace this and parts of #1542
