### ISSUE TITLE
0.3.29 Tech Assignments Cleared/Lost After HQ Reload

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/mekhq#119]
Assigning techs to individual mechs and then saving and reloading HQ causes the techs to be cleared from the mechs they were assigned to. Each tech's log still states where they were assigned but the data gets cleared and have to reassign them again or the 'unmaintained units" nag pops up. Didnt see anything relevant in the log.

[AssignTech.zip](https://github.com/MegaMek/mekhq/files/338535/AssignTech.zip)

**Comment by pheonixstorm** [comment]
update to 0.3.30 and try again. Will try to look into it and see if I can fix it if it can be duplicated.

**Comment by BLOODWOLF333** [comment]
Yeah I think I'll do that tonight, not really found of this 0.3.29 version :\.  If its related at all.....

1. Created a company worth of mechwarrior pilots
2. Opened megamek (pretty sure i was using 0.3.29's maybe it was 0.3.27 I have two shortcuts since Im still holding onto 0.3.27 due to MML)
3. Generated a company of mechs in MM, saved the mul, and then imported the mul into HQ
4. Deleted the pilots that came with the mechs from MM and assigned my pilots to the various mechs
5. Then assigned my techs to the mechs and at first under the force column in the personnel tab it did not fill in what mech they were assigned to but, didnt think much about it.
6.  Saved and reloaded HQ and seen in the hanger that all the mechs had no techs so had to reassign all techs which then displayed the force they were attached to correctly and also, the mechs ID: #'s had changed when I reloaded HQ.
7.  Saved and reloaded again and again the techs were cleared from the mechs :(

**Comment by BLOODWOLF333** [comment]
Realized I must have opened 0.3.27's megamek to generate my mechs and imported them because my Blackjack's have the quirk 'bad reputation".

**Comment by Akjosch** [comment]
Checked with the attached campaign file in .30's dev environment: The campaign file has no techs assigned to any unit. Doing so and saving the campaign results in proper assignment (`<techId>` data fields). Loading that newly saved campaign keeps the techs as they were assigned.

So ... I can't verify it, sorry. At least not with the provided file or steps.

**Comment by BLOODWOLF333** [comment]
Issue still present in 0.3.30, I click assign tech to [none] then reassign it to the same or a different mech and then listed them as having 2 units.   Im pretty sure this has to do with generating the mechs in MM where they all received their own unique ID #'s and then importing them into HQ and saving.  Reloading then displayed all the mechs with different ID numbers which I think is causing this issue.  Im going to wipe and try again (I think I imported the mechs from another version's MM) with 0.3.30's version of MM and see if I receive the same result.

![mm0](https://cloud.githubusercontent.com/assets/16950832/16474231/9428ad12-3e3a-11e6-8b1d-aa4a60d6155c.png)

**Comment by pheonixstorm** [comment]
Are the tech assignments by lance or assigned directly from the tech. The image shows the latter as you are missing the log entry for the lance lvl assignment. Also, what did you do to get the ID to show up, haven't seen that before.

**Comment by pheonixstorm** [comment]
Nevermind, found it is a MM option. This could be related to #42 
It is possible that this may require a fix on the MM side of things but don't know yet as I haven't checked the code yet. For whatever reason the ID number is screwing with HQ in some way.

**Comment by BLOODWOLF333** [comment]
Yeah I just right click the tech and then assign to the mechs.  I dont understand how assigning four techs to a lance should work so, I just do it the old way.  And my feeling is that those ID's are messing with HQ, in the screenshot that Kintaro was ID: 14 in MM, imported it, assigned tech as it states in the techs log, saved and reload which changed it to ID 18 and can no longer remove the tech from ID 14 which no longer exists.

**Comment by pheonixstorm** [comment]
Lance techs are 1 tech per lance which frees up time for the other techs. 1 tech does the maintenance on 4 machines while the other three have 480 minutes to work on everything else.

**Comment by Akjosch** [comment]
Workaround for now: **Don't use the "show ID" option in MegaMek.**

The underlying cause is that MM mangles the unit names by adding the (internal) ID to them, which MekHQ has no idea about and couldn't care less, but keeps the unique IDs (which you *can't* see without looking into the campaign or game save file directly), leading to great confusion.

**Comment by pheonixstorm** [comment]
If MM/HQ are passing the uuid back and forth it shouldn't be too hard of a fix to either have MM unmangle the name or get HQ to ignore the name and just use the uuid only. At least thats my thought.

**Comment by BLOODWOLF333** [comment]
0.3.30

Deleted the previous mechs
Opened MM and in client settings uncheck unique ID's
Generated my 16 mechs then saved as a mul
Imported into HQ and they still show up with ID numbers.......
Saved and reloaded HQ and now the ID numbers are gone and is fine.

**Comment by BLOODWOLF333** [comment]
This issue is not present in HQ 0.3.32 thanks!
