### ISSUE TITLE
Hanger->GM Mode->Restore Unit  Issues. 

### ISSUE THREAD

**Issue by ebjvent** [MegaMek/mekhq#120]
Morning,

The 'Restore Unit' GM tool accessed via the Hanger is broken. 
Currently it does not:

- Repair Internal armor
- Repair Hip, Shoulder, Actuators Damage
- Replace/Repair Weapons

I've attached a small test campaign so you can try it out. Notice the Chameleon as the perfect example. 

Thanks again

[RefreshMechTest29000101.zip](https://github.com/MegaMek/mekhq/files/339601/RefreshMechTest29000101.zip)

**Comment by Akjosch** [comment]
Thanks for the feedback. Should be fixed in the next version.

(If not, feel free to comment here again)
