### ISSUE TITLE
Cannot join another game using a custom scenario

### ISSUE THREAD

**Issue by DwarbitBK** [MegaMek/mekhq#1200]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
I am using MekHQ version 45.4 on a Windows 10 version 1809 with Java 1.8.0_211.

### Description

While running simultaneous campaigns we are utilizing custom scenarios to assist with the additional forces on the other campaign.  From MekHQ we are unable to Join Game from the custom scenario as it is greyed out on the pop up window.  Please see image listed below.

### Files

![image](https://user-images.githubusercontent.com/34976715/57279213-47c6ef80-705d-11e9-874a-6166253a97ff.png)

[Dwarbithian Argonauts30511127.zip](https://github.com/MegaMek/mekhq/files/3151232/Dwarbithian.Argonauts30511127.zip)

[0 - Customs.zip](https://github.com/MegaMek/mekhq/files/3151274/0.-.Customs.zip)
[factionhints.zip](https://github.com/MegaMek/mekhq/files/3151304/factionhints.zip)
[factions.zip](https://github.com/MegaMek/mekhq/files/3151306/factions.zip)
[planets.zip](https://github.com/MegaMek/mekhq/files/3151310/planets.zip)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/3151315/mekhqlog.txt)

**Comment by VicenteCartas** [comment]
I'm working on this one.

**Comment by DwarbitBK** [comment]
Vicente, I have changed out Java to jdk 1.8.0.202 as that is what PhoenyxCullen is using without issue and am still having the same issue.

**Comment by PhoenyxCullen** [comment]
I have copied his current standing campaign over to my computer and tried the same make a scenario, deploy forces and click "Join Game". I was able to enter the three pieces of information that he doesn't have fields for.

We have already cleared his temporary files from within Java and tried again, to no avail. Is there another java reset method we can try to fix for this method?

**Comment by VicenteCartas** [comment]
Not sure why the layout is going bad in some cased, the code in concrete hasn't been changed in a while. I've been working on relayout the dialog with a different method, but real-life has been crushing lately so I have done very little work on it, sorry :(

**Comment by VicenteCartas** [comment]
Is there anything special about the computer? Multiple monitors, screen resolution, % zoom... I'm pretty sure is something related to the display options which is causing this issue in some scenarios.

**Comment by PhoenyxCullen** [comment]
I'm currently running a laptop with laptop screen and 1 extra monitor connected. It's set to copy my main laptop screen to the external monitor as I have the laptop lid closed. Standard 100% zoom. HDMI external monitor. DwarbitBK will give his setup.

**Comment by DwarbitBK** [comment]
My computer is the same exact computer as PhoenyxCullen but I am using a 25inch monitor (HP 25es) attached to the HDMI port on the side of the laptop as my primary display instead of the laptop.

**Comment by PhoenyxCullen** [comment]
Is there a way to reset his JVM settings and preferences? Just curious.

**Comment by VicenteCartas** [comment]
The JVM used by Mekhq depends on your PATH and JAVA_HOME system environment variable. For example for me both of us their value is:

C:\Program Files\Java\jdk-10.0.2

Could you try a newer JDK?

**Comment by PhoenyxCullen** [comment]
I don't have the issue though. I pulled him from the 211 version and it was still happening then too for him. Oh, you mean the jdk 10 version?

**Comment by VicenteCartas** [comment]
Yeah, try 10, and make sure both variables actually point to version 10. If both machines have the same display settings and the same JDK and it works on one and not on the other I'm out of ideas for now.

**Comment by VicenteCartas** [comment]
Another thing to try: copy from the machine where things work the mmconf (MekHQ\mmconf) directory and use it in the machine which is not working.

**Comment by PhoenyxCullen** [comment]
Where do I check for these path and java_home variables are?

**Comment by VicenteCartas** [comment]
In the Windows start menu, type Environment and you should get an option called "Edit the system environment variables".

Clicking that will open a window, and you have to click the button at the bottom called "Environment variables...".

Then you will see another window, with the user variables on top, and the system variables on the bottom. You want to edit the system variables (and make sure there is no Java stuff in the user variables).

**Comment by DwarbitBK** [comment]
Vicente,

I copied the mmconf folder from PhoenyxCullen's machine, and am getting the same join issue.

**Comment by PhoenyxCullen** [comment]
I have in my path these two folders only:
C:\Program Files (x86)\Common Files\Oracle\Java\javapath
C:\ProgramData\Oracle\Java\javapath

And I have new JAVA_HOME folder env var.

**Comment by DwarbitBK** [comment]
I also have the following in my system environments:
C:\Program Files (x86)\Common Files\Oracle\Java\javapath
C:\ProgramData\Oracle\Java\javapath

**Comment by PhoenyxCullen** [comment]
As for Oracle's JDK downloads (https://www.oracle.com/technetwork/java/javase/downloads/index.html), I do not see a ver 10, just 12,11,and 8.

**Comment by VicenteCartas** [comment]
I get my downloads from the OpenJDK page: http://jdk.java.net/archive/

**Comment by VicenteCartas** [comment]
It may be something else if you both have the same Oracle JDK versions and variables :( I'll see if I can find time soon to update the code to layout the dialog in a different way.

**Comment by PhoenyxCullen** [comment]
Let me know if it's pulled and built and we can try the snapshot when it's created.

**Comment by VicenteCartas** [comment]
Sure, there will be an update on this ticket when it happens.

**Comment by PhoenyxCullen** [comment]
Well, that was an interested test. Networked over a VPN, he ran my copy/set of files with his java instance. My computer did not show an instance of java running. He pulled in his campaign from his computer, opened up the scenario that we've been testing for join and he pulled up my last entry for megamek joining a server. Continuing some tests on our end and we'll let you know.

I think we are going to redownload 0.45.4 from github again.

**Comment by DwarbitBK** [comment]
Vicente, this issue has been resolved after re-downloading the 0.45.4 from Github.  I can now join a custom scenario.

**Comment by PhoenyxCullen** [comment]
I can confirm. I guess we will have to find some way to keep it aligned, say dropbox.

**Comment by VicenteCartas** [comment]
This is great to hear! Thanks for your patience with this issue.
