### ISSUE TITLE
[0.45.4 - Bug/Performance] Purchase Parts Screen Take Forever To Open

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#1206]
### Environment
MekHQ 0.45.4

### Description
Purchase parts screen under Marketplace takes forever to load. When I try to filter, the whole game are frozen(?). No error in log.

### Files
[Customs - SirMegaV - Mechfiles.zip](https://github.com/MegaMek/mekhq/files/3215637/Customs.-.SirMegaV.-.Mechfiles.zip)
[PurchasePartsWindowTakeForeverToOpen_CampaignFile.zip](https://github.com/MegaMek/mekhq/files/3215638/PurchasePartsWindowTakeForeverToOpen_CampaignFile.zip)

**Comment by sixlettervariables** [comment]
This is a dupe of #1205.
