### ISSUE TITLE
Purchase Parts En-Masse

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#121]
For large units in MekHq (anything over company sized) the current system for parts acquisition is extremely tedious. Only one type of part can be purchase at a time (for example, six 30ton upper arm actuators).

A system should be implemented where multiple different parts can be selected and purchased at once. For example, the player should be able to highlight 30 ton mech head, 35 ton mech head, & 40 ton mech head all at once, then right click and have the option to purchase one, or more, of each, in the parts dialog window.

Likewise, the player should be able to highlight some, or all, of the parts in use in the parts in use window, and purchase/gm-add X number of each highlighted part.

This will remove the need to create bone yard files for very large units every time you want to make a new one.

**Comment by BLOODWOLF333** [comment]
I second this request and for everyone else on the forums who posted on the IO thread.  http://bg.battletech.com/forums/index.php?topic=51039.0

**Comment by scJazz2** [comment]
I would add turn off acquisition rolls and XP when doing it

**Comment by HammerGS** [comment]
Another suggest to this is have an Order all parts for that unit option.

So if I have an Atlas I can have a one button option that buys me an Atlas but as parts only.

**Comment by VampireSeraphin** [comment]
I like Akjosh's suggestion as a secondary add in addition to this large individual parts select. 

Right click on the unit(s) -> Order > Replacement body parts, replacement actuators, replacement engine, replacement gyro, replacement systems, replacement for all parts, ammo and fuel

**Comment by molemanBT** [comment]
I would like a reminder of how many parts of the item I just used I have remaining, i.e. if I replace a lower arm conduit, I'd like to know I have 1 left and so need to order a few more. Would save the mad scramble when you run out of armour all of a sudden!

**Comment by BLOODWOLF333** [comment]
We kinda already have that.  In the overview tab/parts in use it lists how many parts you have in use and then how many you have stored in the warehouse back when AJ updated it.

**Comment by VampireSeraphin** [comment]
Has anyone looked into this recently? For players of large campaigns it is one of the remaining very large quality of life improvements yet to be done.
