### ISSUE TITLE
Can't custom rank system make specific rank officer?

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/mekhq#1211]
### Environment
Ver 0.45.4
Windows 7

### Description
When I make the custom rank system, I can't make WOs officer, the Officer tab is false and cannot be modified. Since it is the custom rank system, can't I make some ranks officer?

**Comment by purpledragon2** [comment]
I would also like the ability to change flags between officer and enlisted.  I would also like to add a Non-Commissioned Officer to that flag as well.

**Comment by Windchild292** [comment]
Subsumed by #2203 and #2204
