### ISSUE TITLE
Feature request: Mechwarrior total earnings

### ISSUE THREAD

**Issue by molemanBT** [MegaMek/mekhq#1218]
Hi,

As always, fab work!

I was wondering if you would implement somewhere where we can see a total earnings that a mechwarrior has earned since joining the company, including money from shares. Perhaps under 'Time in service' on the personnel tab?

I thought it would add a nice bit of immersion/fluff to see how much each person has earned since they joined the company, taking into account their shares (I usually set my share % to 50). I had this thought whilst deciding if any of my MWs are rich enough to set up their own spin off Merc company when one of my games was getting a little stale.

Thanks!

**Comment by NickAragua** [comment]
I like this idea. The only caveat is that this feature will only work going forward once implemented, as we don't currently retain that information.

**Comment by molemanBT** [comment]
Fine by me, thanks :)

**Comment by molemanBT** [comment]
Any news? I know you guys are busy

**Comment by Windchild292** [comment]
@molemanBT 
I'm going to implement this, as it looks like a nice thing to have for personnel.
