### ISSUE TITLE
Tech assigned to unit can "repair all" after battle

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#122]
Can we get an option to assign a single tech to a unit in the repair screen, and that tech uses all their repair time each day on that unit until it is repaired? Basically automate all the repairs for a single unit.

**Comment by mkerensky** [comment]
What happens when that tech fails a roll and the repair has to go to a tech with a higher skill level, or you have a really difficult repair and want to assign extra time to it?

**Comment by Bonepart** [comment]
While not exactly the same, I think the Mass Repair Mass Salvage function would do what you want.

**Comment by Windchild292** [comment]
Closing as covered by the automatically run MRMS on New Day option.
