### ISSUE TITLE
Generate from Template, Fails to Generate OpFor per campaign file

### ISSUE THREAD

**Issue by PhoenyxCullen** [MegaMek/mekhq#1224]
Trying to start using nickaragua Scenario Templates and StratCon HTML, I have a template that is working for me, but failing on DwarbitBK's campaign file. It is generating 0 OpFor while mine is working. I even copied his campaign file over to my workspace and I'm still having the same problem with his campaign, not sure where to go next with the troubleshooting.

### Environment
We have matched my current java version to 1.8.0_202 with both the SE and the JDK installed and they're both 64 bit versions.
We are currently using the 0.45.4 version of MekHQ.
We are currently on Windows 10 1809 (10.0.17763 Build 17763).

### Description
DwarbitBK will provide the screenshot shortly.

### Files
[Dwarbithian Argonauts30511230.zip](https://github.com/MegaMek/mekhq/files/3357112/Dwarbithian.Argonauts30511230.zip)
[forcegenerator.zip](https://github.com/MegaMek/mekhq/files/3357113/forcegenerator.zip)
[Reinforcements Intercepted.zip](https://github.com/MegaMek/mekhq/files/3357114/Reinforcements.Intercepted.zip)
[0 - Customs.zip](https://github.com/MegaMek/mekhq/files/3357116/0.-.Customs.zip)

Further information can be provided if asked.

**Comment by DwarbitBK** [comment]
Here is my screenshot.
![ScenarioScreenShot](https://user-images.githubusercontent.com/34976715/60631069-66720a00-9db2-11e9-8d14-c39ad9bc5e83.JPG)

**Comment by PhoenyxCullen** [comment]
Oh, he also has the mekhq/data/scenario modifiers folder with the scenario modifiers that I have. The set with the current un-released nightly build.

**Comment by NickAragua** [comment]
Ok, it looks like the campaign failing to generate opfor has "use vehicles" turned off entirely, which caused an error in the force generation routine. As a workaround put that setting back on - but if you don't want enemy vehicles, you can set the odds of mixed and vehicle lances to 0.

A fix will be forthcoming to address the situation.

**Comment by DwarbitBK** [comment]
Thanks NickAragua.  I will give that a try.

Respectfully,
Brian Keller


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by DwarbitBK** [comment]
NickAragua,

The enemy units are loading but the date is missing from the briefing room,
and the start game is grayed out.  Please see attached screenshot.

Respectfully,
Brian Keller


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by NickAragua** [comment]
Once you click 'finalize', you will have to go back into the edit scenario dialog and pick the date manually. The logic for picking the battle date has not been implemented yet.

**Comment by PhoenyxCullen** [comment]
> It was working on mine, but it didn't change. So after, finalilze, edit
> again and pick date, then save?



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by NickAragua** [comment]
Correct.
