### ISSUE TITLE
BUG: Self-crewed units requiring an Engineer cannot be Activated

### ISSUE THREAD

**Issue by MaxSizeis** [MegaMek/mekhq#1238]
Currently Mothballed dropships can't be un-mothballed in MekHQ.  Consider a GM option to un-mothball any unit.
As a current work around, the entire unit must be replaced.

Quoting SO pg 175...

The time required to place larger units (WarShips, Drop-Ships, JumpShips, Space Stations and Large Naval Vessel Support Vehicles) in mothballs is equal to one Maintenance/Repair Cycle per 500 tons. The same amount of time is required to return them to operational status.

It should be possible but it is not implemented in MHQ correctly.

**Comment by sixlettervariables** [comment]
I've implemented GM mode mothballing and activation for all units. The reason Activate is not available is there is no "engineer" to perform the activation (because it is self crewed). I'll keep this open to research that bug.

**Comment by sixlettervariables** [comment]
The fix in PR #1239 restores the crew to the vessel before attempting activation. This should allow self maintained units to activate themselves (if the crew is still available).
