### ISSUE TITLE
[3.30 : Bug] Daily Log and Time/Date

### ISSUE THREAD

**Issue by drkrough** [MegaMek/mekhq#124]
Hopefully this is in the right place and/or format.

Howdy,

My campaign has hit a bug. Quick facts:
Using ATB
Started Jan 1 3025
Currently May 12 3041
Fought an ATB battle on this date
Pending battles with ATB, but not on the current date (5/15)

When I hit "Advance Day", the Daily Log will not update, nor will the Date in the Title Bar. The Daily Log is attached. I go to View > Detach Daily Log and review the log, and in the middle of the log I see this:

Saladin Assault Hover Tank (Armor) #5 has been removed from the unit roster.**Thursday, May 13 3041**

Mashed together, just like that. I can keep hitting Advance Day, and it'll continue to append the next day's log until I hit May 15, when I have to fight a battle. Title bar still shows May 12, however, now my battle is available to Start Game (telling me that obviously the game knows it is on the 15th.)

Not being a programmer, I have no clue why this is happening, so hopefully this info helps.

Regards,
DRK

**Comment by Akjosch** [comment]
Sounds like some error preventing a proper resolution of the day. We'll need at least the MekHQ log and if possible the campaign file with all the custom units.

You can attach those in GitHub when you comment.

**Comment by drkrough** [comment]
Okay. I actually went and deleted out all my custom units from the file (not because I didn't want to share, but to see if the bug existed without any custom units) and the problem still persists. The save file represents that cleaner state (I hope.) If you still need them, I can add them later. Rather than zipping, I just renamed the cpnx file since it just seems to be xml stuff. 

Please let me know if I can do more.
Regards,
DRK

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/361310/mekhqlog.txt)
[Redcoat Raiders30410512 Testing Glitch 2.cpnx.txt](https://github.com/MegaMek/mekhq/files/361311/Redcoat.Raiders30410512.Testing.Glitch.2.cpnx.txt)

**Comment by Akjosch** [comment]
Should be fixed in next release or daily. Looks like trying to fix a vehicle stabiliser *outside* of the vehicle was the problem.
