### ISSUE TITLE
[0.45.4 : Bug] Cannot Salvage

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#1240]
### Environment

MekHQ 0.45.4

### Description

Mission Type: Guerrilla Warfare
Salvage Percentage: 100%

During resolution after a battle, all salvageable units were greyed out despite my contract having 100% salvage rights. Lots of error in  error log.

To replicate:
1. Load campaign
2. Select mission #052
3. Select second last scenario, hide and seek
4. Load save game
5. end the game, control battlefield

### Files

[CannotSalvageLog.txt](https://github.com/MegaMek/mekhq/files/3481031/CannotSalvageLog.txt)
[Uploading CannotSalvageCampaign.zip…]()
[Uploading CannotSalvageGame.sav.gz…]()

**Comment by neoancient** [comment]
It looks like the campaign zip and the save game never finished uploading.

**Comment by SirMegaV** [comment]
Let me upload again.

[CannotSalvageCampaign.zip](https://github.com/MegaMek/mekhq/files/3488428/CannotSalvageCampaign.zip)
[CannotSalvageGame.sav.gz](https://github.com/MegaMek/mekhq/files/3488429/CannotSalvageGame.sav.gz)
