### ISSUE TITLE
Near 100% Defection Rate

### ISSUE THREAD

**Issue by BairdEC** [MegaMek/mekhq#1248]
### Environment
0.46.0-rc.2
Java build 1.8.0_221-b11
Win10

### Description
Nearly all captured prisoners are willing to defect.

### Files
Pre-battle campaign save:
[Steel Recon30291020.zip](https://github.com/MegaMek/mekhq/files/3511527/Steel.Recon30291020.zip)

Last turn of the battle autosave :
[autosave.sav.gz](https://github.com/MegaMek/mekhq/files/3511529/autosave.sav.gz)

[customs.zip](https://github.com/MegaMek/mekhq/files/3511528/customs.zip)

![Prisoners](https://user-images.githubusercontent.com/38081112/63205137-16df5900-c055-11e9-8600-5837c97533a6.PNG)

**Comment by NickAragua** [comment]
I looked into it, and it appears that the target number for a defection is implemented as 10 + enemy force skill rating - unit rating. If you're using CamOps rating that "unit rating" number is literally unit rating / 10, so if you have like a 100 unit rating and fighting a C-rated unit, the TN might look like 10 + 3 - 10 = 3. This should probably be adjusted to something a little less crazy.

**Comment by BairdEC** [comment]
I'm using the FM: Mercenaries system, and the opfor in this mission is green/F.  The company is rated A*(176) in the screen footer.  Guess that explains it,

**Comment by swang300** [comment]
Relevant roll is at ResolveScenarioTracker:1179

How about instead of getUnitRatingMod(), use getUnitRatingAsInteger()-2?  That seem to be what AtB 2.31 Campaign System 858-870 implies.
