### ISSUE TITLE
Tech Names Missing in Event Log

### ISSUE THREAD

**Issue by BairdEC** [MegaMek/mekhq#1249]
### Environment
0.46.0-rc.2
Java build 1.8.0_221-b11
Win10

### Description
The event log does not show the tech name for repairs and salvage.

![Repair Log](https://user-images.githubusercontent.com/38081112/63205311-69ba1000-c057-11e9-8cbd-afecc2d891f9.PNG)

### Files
[Steel Recon30291020.zip](https://github.com/MegaMek/mekhq/files/3511540/Steel.Recon30291020.zip)
[customs.zip](https://github.com/MegaMek/mekhq/files/3511541/customs.zip)

**Comment by inqistor** [comment]
Actually it misses both Tech name, and Component name. I can report the same, my Campaign is transferred from 45.3, but apart from missing names, repairs seems to works as intended.

**Comment by NickAragua** [comment]
The good news is that this doesn't seem to be happening in the current dev branch. Not really sure what fixed it, though.

**Comment by sixlettervariables** [comment]
Fixed by #1255.
