### ISSUE TITLE
Warehouse sorting by total value is wrong.

### ISSUE THREAD

**Issue by plutonick** [MegaMek/mekhq#1250]
When in the Warehouse tab, when sorting by Total Value, the sorting messed up.

![image](https://user-images.githubusercontent.com/8420602/63218814-9c096180-c16c-11e9-8289-74c919a10125.png)

I am using version 0.45.4

**Comment by sixlettervariables** [comment]
Classic case of sorting.by string and not the value itself.

**Comment by sixlettervariables** [comment]
Closed by #1550
