### ISSUE TITLE
Changing Omni config can result in part duping

### ISSUE THREAD

**Issue by RexPearce** [MegaMek/mekhq#1254]
When changing Omni configs, several parts are not tracked correctly in warehouse, which results in a part duplication bug.

To reproduce:
 - Open attached campaign "OmniPartDuping.cpnx"
 - Note the hanger has a Daishi Prime and a Daishi A, both in perfect condition
 - Note that the warehouse has no parts
 - Change Daishi A to salvage, and remove all its pods
 - Change the Daishi Prime's configuration to "A" and complete it
 - Note the hanger now has two Daishi A's (the original one salvaged and the newly configured one)
 - Change the original salvaged Dashi A's configuration to "Prime" and complete it
 - Note the hanger has a Daishi A and a Daishi Prime
 - Note the warehouse has many functional parts that shouldn't exist. i.e. the warehouse should be empty.

[OmniPartDuping.zip](https://github.com/MegaMek/mekhq/files/3513257/OmniPartDuping.zip)

MekHQ 0.46.0-rc.2
Ubuntu 18.0.4.4
Java version 1.8.0_222

**Comment by RexPearce** [comment]
I ran the above test again on 0.47.11-Dev and it passed without issue.

**Comment by Windchild292** [comment]
You are confirming this as fixed @RexPearce?

**Comment by RexPearce** [comment]
Yeah, in cases like this should I close it myself, or would you guys prefer to do it?

**Comment by Windchild292** [comment]
Either way works.

Closing as fixed since being opened.
