### ISSUE TITLE
RFE: Add On Leave Personnel Status

### ISSUE THREAD

**Issue by dannylambourne** [MegaMek/mekhq#1258]
Edited:
Add the ability to have personnel be on leave, which would mean they are an active member of the force but they cannot be deployed nor are they paid.

Original:
"Hammer directed me to here from the Megamek forum have an idea for the personnel tab!

is there a way of adding an extra tab on the personnel / change status tab / to an option like on assignment (paid but not active). I was thinking to use it for company members in detached units, home bases or contacts and informants.  

many thanks

danny"

**Comment by purpledragon2** [comment]
I would like to see something like this implemented too.  It would allow for a little more flexibility to use the program as a RP tool.

**Comment by dannylambourne** [comment]
hi yes 

not available for contracts or transport just on the pay roll (more for roleplay/fluff)
if you have a home base not on the contract planet you could have troops on leave or contacts and informants that are not combat, or detached units on special missions office on outreach.

danny

**Comment by Windchild292** [comment]
I'm dividing this into two parts. One is adding a new personnel status for On Leave (which I will handle post-random death), the second is handling separate locations for personnel. The first is hard but in general okay to implement, the second is nasty.

**Comment by IllianiCBT** [comment]
Closing as resolved
