### ISSUE TITLE
Cannot Save MHQ Campaign with Nekohono'O HQ on Roster

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/mekhq#126]
I've done testing with this in both 0.3.29 and 0.3.30.  If I purchase a Nekohono'O (HQ) or a custom variant I made of it and have it on the unit's rolls, I can't save my campaign. This also happens if I buy a refit kit and customize a standard or variant Nekohono'O.  I can save again if I remove the HQ ship from the roster and/or cancel the customization. I can also save if I use GM mode to add the HQ dropship or complete the refit. 

Attached is the log file from my campaign, which is admittedly large and has custom unit files in it, so I didn't attach it. 
[mekhqlog7_26NekoHQ.txt](https://github.com/MegaMek/mekhq/files/383931/mekhqlog7_26NekoHQ.txt)

I was able to duplicate the issue using the stock Black Widow campaign. To reproduce the issue, I:
- Added 10,000,000,000 cbills to my funds to cover the purchase price
- Set the campaign date to May 8, 3078 to cover the introduction date
- Unchecked 'only support personnel can make acquisition rolls' and set acquisition skill to 'administration' in the Repair and Acquisition tab of campaign options
- Used GM mode to give one of the pilots a +5 administration skill 
- Bought a Nekohono'O (HQ) dropship from the Purchase Unit screen

**Comment by Akjosch** [comment]
Seems to be with saving C3i-capable units, which the Naval C3 counts as, I guess. Still, I can't reproduce it with the steps given.

I added a few checks in the isEnemyOf() methods of MegaMek, so that shouldn't prevent you from saving the game now. Still, we'd need the actual campaign save and custom units to make 100% sure it's fixed.

**Comment by mkerensky** [comment]
I have custom princess behaviors, rats, camos, portraits, maps and units in my campaign, and the campaign file itself is about 82mb.  Perhaps I should send the whole customized MHQ package?  It is 151mb zipped.

**Comment by Akjosch** [comment]
Well, you might just check the next daily MekHQ off http://mm.akjosch.de/ and see if it fixes it, if that's easier for you.

**Comment by mkerensky** [comment]
Thanks.  I'll check the daily build and see if it works. I don't mind attaching my files, either - I just wasn't sure how large of a file the site here can handle at once, or how much I need to include for the campaign to load correctly.

**Comment by pheonixstorm** [comment]
The campaign file is plain text so it compresses very nicely even if it IS 82mb. As long as the custom units and the campaign file are there the rest doesn't really matter (as far as I've seen anyway).

**Comment by mkerensky** [comment]
[337thTest2.7z.txt](https://github.com/MegaMek/mekhq/files/386005/337thTest2.7z.txt)

Very well, then.  Here is the campaign file, the MML custom units directory for it, and a separate custom units.zip file that I use. The campaign unit is full of units from both.

**Comment by mkerensky** [comment]
When I checked the daily build page a few days ago, the last build appeared to be from 7/14.  I see there's a 7/29 build now - would that have the c3i / isEnemyOf  changes in it?

**Comment by Akjosch** [comment]
My MekHQ daily build #118 and later should have the fixes. Unless you have some strange caching issues, there should be one successful build for every day since quite some time (It's really creepily *strange* how few failed builds we produce ...).

**Comment by mkerensky** [comment]
I think we can call this one fixed.  After testing with both the daily build and the new 0.3.31 release, it seems to be resolved.  Thanks!
