### ISSUE TITLE
RFE: In Contract Market, hyperlink the system/location to the Interstellar Map

### ISSUE THREAD

**Issue by RexPearce** [MegaMek/mekhq#1261]
When reviewing contracts, it'd be convenient to click a link to see system/planet stats (gravity, atmosphere, etc.) for the contract location. Clicking the link could just switch to the Interstellar Map with the relevant system in-focus.

**Comment by Windchild292** [comment]
I've picked this up, slightly expanded it to also include it on the Briefing Room tab, and am now just trying to figure out getting the hyperlink display working properly on the Contract Screen before I can open a PR.
