### ISSUE TITLE
RFE: In Interstellar Map, indicate which systems are capitals or hiring halls

### ISSUE THREAD

**Issue by RexPearce** [MegaMek/mekhq#1262]
When playing AtB, capitals and hiring halls will generate additional contracts each month. This can be important when starting out and Dragoon rating is low. However, I haven't figured out any way to identify these systems, other than looking in the XML for which system is the capital for faction for a given era.

I'd be nice if the map showed capital systems and hiring halls with a different icon. (maybe a star instead of a dot for capitals?) If that can't easily be done, even just a note in the text description that's updated as capitals/halls move around by era would be helpful.

**Comment by NickAragua** [comment]
Implemented with #1396
