### ISSUE TITLE
Make spouse requires the personnel to be have a surname

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/mekhq#1263]
### Environment
Ver 0.46.0-rc.2
Windows 7

### Description
As title says. When you have two personnels, male and female, but without a surname, you may choose 'no name change' when you choose 'choose spouse(mate)' but it also makes no change and the personnels are not married at all.... Only if you give them a surname it is possible to marry them.

**Comment by purpledragon2** [comment]
IF implemented, I would like this to be optional.  I use the spouse to assume marriage between some personnel so that there can be some children with both parents in the unit.  However, for reasons of information tracking (assuming divorce and name-change back to maiden) I don't ever use the last name, though there is the option to hiphenate; which I may start using.

**Comment by Windchild292** [comment]
Will be investigating this now, and I don't understand what you mean by that @purpledragon2. As far as I am reading, the only thing needing to be fixed it so handle the lack of surname on either or both sides, which would still allow for what you are saying if I am understanding you correctly.

**Comment by Windchild292** [comment]
I can confirm this is a bug in how we are handling marriages. I am in the process of fixing it, and have come up with some expansion ideas originating from this bug with will be brought up in another issue/PR.

**Comment by purpledragon2** [comment]
@Windchild292 : If in a large unit, there is no hyperlink to go to the spouses information.  If, in the course of story as part of RP, the two married persons divorce, and the woman, or whomever, goes back to her(his) maiden name,...      There's no way to track the maiden name in the program as it is now.  Unless if through the use of hyphenated last names.

**Comment by purpledragon2** [comment]
Going back and reading the OP, it now reads differently from what I originally understood.  I just wanted to make sure that we tracked the maiden name if married name was forced.

**Comment by Windchild292** [comment]
We are tracking the maiden name as is, and I'm ensuring that if one side has a maiden name and the other doesn't it will work correctly @purpledragon2.

**Comment by sixlettervariables** [comment]
Fixed by #1401
