### ISSUE TITLE
BV for air princess not at 100% when entering MegaMek

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/mekhq#1270]
[Blake.zip](https://github.com/MegaMek/mekhq/files/3543992/Blake.zip)
![WrongBV](https://user-images.githubusercontent.com/20606833/63736527-5d049b80-c851-11e9-8c9b-1f668f5e965f.jpg)
In the 47.0 version 

Upon entering a mission with bot air support it gives a BV in HQ and a number of units 
When going to MegaMek all the bot units are loaded, but when going to the next screen for deployment, the Air Bot is listed as having a BV which is significantly lower than it's max BV which matches the number sent by HQ.  

This can be seen in the attached picture.  

A save is attached if needed.  Let me know if any additional information is needed.

**Comment by sixlettervariables** [comment]
I believe this is fixed by https://github.com/MegaMek/megamek/pull/2274
