### ISSUE TITLE
Graphic issue with prisoners who are vehicle drivers 

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/mekhq#1271]
![offscreen](https://user-images.githubusercontent.com/20606833/63736857-8a9e1480-c852-11e9-87b7-699ccbbeeb7f.jpg)

On version 47.0  
The screen for prisoners who are vehicle drivers goes of the screen for some reason.  
My vehicle drivers are fine, and all my other prisoners who have other jobs are fine, the issue only occurs for the given subset.

**Comment by Windchild292** [comment]
Closing as this appears to have been fixed during the changes to the panel in question.
