### ISSUE TITLE
0.47.0 Change Biography Zero Sized

### ISSUE THREAD

**Issue by SVNaas** [MegaMek/mekhq#1275]
### Environment
MehHQ 0.47.0
Windows 10

### Description
Opening Change Biography opens the window with only the bar visible and requires resizing to be used, issue has been mentioned before and was evidently fixed in other locations but not here. No errors in log.

### Files
![image](https://user-images.githubusercontent.com/37005983/63968065-aeea3300-ca96-11e9-97a2-a078c8df2307.png)

**Comment by sixlettervariables** [comment]
There were a few more places that I found while testing.

**Comment by sixlettervariables** [comment]
Fixed in #1278
