### ISSUE TITLE
0.3.31 Consistent freezing 

### ISSUE THREAD

**Issue by guybtg** [MegaMek/mekhq#128]
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/392829/mekhqlog.txt)

I've been trying the new MekHQ build, and I've been having pretty consistent freezes on the client every 10-14 days. MekHQ won't even be able to close once it locks up.  The only way I'm able to close it once it freezes is to go into Task Manager and end the process.

**Comment by pheonixstorm** [comment]
Need Java version and HQ log file. There may be something in the log on why it is freezing but I doubt it.

**Comment by pheonixstorm** [comment]
What version of Java are you using and what windows version.

Is that log from the last time it froze?

**Comment by Akjosch** [comment]
Log looks clean, we might actually needs a [heap dump](https://github.com/MegaMek/megamek/wiki/Creating-a-Heap-Dump) from the time it is already "frozen".

**Comment by guybtg** [comment]
I realized that I was running a version of Java that was 4 years out of date, which explains quite a bit. It's looking like smooth sailing once  updated.
