### ISSUE TITLE
[ATB] Automatic monthly dependents conversion (to support/mechwarrior)

### ISSUE THREAD

**Issue by Kendricke** [MegaMek/mekhq#1281]
Per ATB: Once per month, you can convert a dependent to a Green Mechwarrior, Tech, Admin, or Medic. I can do this manually right now, but it would be helpful if this were built right into MekHQ:

Possible implementations:
- An automated pop-up with drop down to select new role
- A note/link in Daily Log to update a dependent to a new role

**Comment by IllianiCBT** [comment]
While not automatic, the Education Module addresses the problem described by the OP. Closing as resolved.
