### ISSUE TITLE
[ATB] Automatically Add ATB Win Conditions to ATB Battles

### ISSUE THREAD

**Issue by Kendricke** [MegaMek/mekhq#1283]
ATB has multiple victory conditions which are not reflected in game options files for MekHQ.  As an ATB player, it would be nice not to have to track battle conditions manually every time.

**Comment by NickAragua** [comment]
Surprisingly enough, I'm actually working on a feature like that. ETA probably next dev release.

**Comment by NickAragua** [comment]
This will be in the next dev release.
