### ISSUE TITLE
Can't get contracts from Comstar's capital planet in v0.46

### ISSUE THREAD

**Issue by Tamren** [MegaMek/mekhq#1284]
In one of my previous campaigns I remember doing a contract for Comstar against pirates, I got that contract because I was on Terra at the end of the month and it was added to the list on the next board refresh because Terra is Comstar's capital planet. I started a new campaign today in v0.46 and tried to do the same thing as a test, but it didn't work. (both campaigns are set in 3025)

It still works back in v0.43.1 which is the version I was using previously. I tested a few other faction capitals like Taurus and Luthien in v0.46 and both of those work properly in regards to contract generation. If you advance the date while you are on Terra you can even get WoB and RotS contracts, so it seems like Comstar has a missing link somewhere.

**Comment by sixlettervariables** [comment]
Can you please upload an affected campaign?

**Comment by Tamren** [comment]
Ok here it is. This savegame is from the v0.46.0 stable release and uses the default settings. The only thing I did to change it was use the GM tools to edit the date from 3067 to 3050. The date is set to January 31 and your merc company (that has nothing in it) is located on Terra. When you press the button to advance one day it refreshes the contract market, the expected behaviour is that you are guaranteed to get a Comstar contract offer that month, but this doesn't happen.

[comstar bug test.zip](https://github.com/MegaMek/mekhq/files/3638678/comstar.bug.test.zip)

**Comment by Windchild292** [comment]
I've had this happen to me, I spent around a year orbiting Terra and did not get a single contract.

I just tested it on v0.47.2, I do not get Comstar Contracts but I do get WoB and RotS Contracts (different companies in different periods). If you use GM mode and generate contacts, Comstar Contracts are also not generated.

**Comment by neoancient** [comment]
ComStar didn't start hiring mercs until around 3028, so the two earlier dates shouldn't generate contracts anyway.

**Comment by Windchild292** [comment]
I wonder if the bug is related to that @neoancient? Would make sense that it never enables at that point, so no contracts are available.

**Comment by neoancient** [comment]
It was years ago that I wrote that part of the contract generator, but from what I remember ComStar is tagged as non-combatant, which means that normally they don't generate contracts at all. The exception is during times of war. Around the beginning of 4SW they started hiring mercs for pirate hunting, then after a brief period in 3050 they're tagged at war with the Clans. I think you should still be getting pirate duty in 3050. My best guess is that the war against pirates isn't overriding the non-combatant status.
