### ISSUE TITLE
[ATB] Personnel Market showing non-role personnel

### ISSUE THREAD

**Issue by Kendricke** [MegaMek/mekhq#1285]
When playing through ATB campaign, personnel market will sometimes/often show multiple personnel with no roles and unknown skills. 

![image](https://user-images.githubusercontent.com/24977517/64191245-e9542700-ce2c-11e9-935b-c0fb1c41de52.png)

**Comment by Kendricke** [comment]
This is happening in both 36.0 Stable and 37.0 snapshot.  I've done this with a clean campaign multiple times.

**Comment by NickAragua** [comment]
This usually happens when you go into a contract before turning off targeted personnel recruitement.
