### ISSUE TITLE
Parts in Use - Funds Refresh

### ISSUE THREAD

**Issue by Nitedawn** [MegaMek/mekhq#129]
Hi Guys,

If I buy or buy in bulk from the 'parts in use' overview tab the funds label as the bottom of the GUI does not refresh and the finance tab balance sheet is not updated, however the new purchases are listed in the warehouse tab.  Though it does not show it it does subtract new purchases from available funds.

I don't get this issue when buying from the Marketplace but buying from the Marketplace updates the finance tabs balance sheet with the purchases from the 'parts in use' overview tab.

Cheers

**Comment by Akjosch** [comment]
The finance tab should refresh when you open it (because it otherwise takes too long to re-calculate it every button click). I'm very sure it did before, maybe we broke something in the meantime. :)

**Comment by Nitedawn** [comment]
Forgot to add save game :) 

[MekHQ_save.zip](https://github.com/MegaMek/mekhq/files/395034/MekHQ_save.zip)

**Comment by pheonixstorm** [comment]
Using parts in use does not subtract the cost of the part, just tested it. Nothing subtracted and no ledger entry.
