### ISSUE TITLE
Export Campaign Subset

### ISSUE THREAD

**Issue by jbhuddleston** [MegaMek/mekhq#1290]
### Environment
MekHQ 0.47.0
Windows

Export Campaign Subset

Exported:
2 Regular Mech Techs
A Dictator dropship and crew (3 pilots, 13 gunners and 3 crewmembers)
12 BL7-KTQ Black Knight mechs
2048 points of armour
8 of each type of actuator (7 foot from one pile and 1 foot from another pile, otherwise 8 from same pile)
24 Medium Lasers
6 PPCs
33 Small Lasers
Chose destructive but no other options.

Result in generated file:
Campaign Operations options were in effect by default so I loaded my FourAmigos Campaign preset to override them.
All settings overriden correctly except the skill level of personnel (mech techs raised to Veteran) and the XP to raise current skills (costs for new skills and special abilities were correct). GM Mode Edit then save without change forced the correct XP costs to be presented and the skill level to revert to Regular. Needed to do this for every person.

The dropship technician was unassigned and could not be forced to be assigned on day 1 but was automatically assigned after advancing the day.
Astechs had to be obtained (not transferred) and the astechs for the dropship could only be added after advancing the day (once the tech was assigned).

Most spare parts were incorrectly transferred.
2048 points of armour, correct (id 1, quantity 2048)
7 foot actuators from one pile and one foot actuator from another pile became 7 instances of id 8, quantity 2 (after saving the file this is reduced to one instance of id 8, quantity 2)
All other part transfers generated N instances of id Last Part Number + N, quantity 1. All were reduced to quantity 1 on save.
- these should be id++, quantity N
Mech parts for all complete mechs were generated after advancing the day.

The campaign options in the source campaign were altered as well.
The XP costs were changed to Campaign Ops levels but the XP awards were not changed.
The skill level settings were changed to Campaign Ops levels as were the special abilities costs.
The personnel XP costs for Special abilities, Current skills and new skills are all at Campaign Ops levels as are personnel skill levels.

After loading my FourAmigos campaign preset the special abilities and new skills costs are fixed but the current skills and skill levels are not. GM Mode Edit then save fixes each individual as with the other file.

On another attempt selecting campaign values to be retained, ALL campaign options were set to Campaign Ops for the generated campaign and the original campaign was affected as above.

Exporting in non-destructive mode causes the original campaign Personnel special abilities and new skill costs to change but leaves the current skill costs alone. The Campaign options are again affected as in other tests. The generated campaign behaves exactly as in the first test.

**Comment by NickAragua** [comment]
Is it possible to provide a copy of the source campaign?

**Comment by jbhuddleston** [comment]
Sorry, here are all the relevant files.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jbhuddleston** [comment]
[FourAmigos.zip](https://github.com/MegaMek/mekhq/files/3620855/FourAmigos.zip)

Sorry, here are the relevant files.

**Comment by NickAragua** [comment]
Note that temporary astechs won't get exported - that was not an intended part of this feature.

**Comment by jbhuddleston** [comment]
Thanks much. I had a look at the code this morning. Re temp Astechs, ack silly of me to think so :-)
