### ISSUE TITLE
Problems Refitting Rifleman via Meklab in MekHQ...

### ISSUE THREAD

**Issue by Nar11** [MegaMek/mekhq#1296]
nvironment
MekHQ 0.46.0
Windows 7 Ultimate
Could not find on MekHQlog.txt; Megameklog.txt says Java version 1.8.0_171 (not so sure because it also states my windows its 10 even though its really 7)

Description
Trying to refit my Rifleman RFL-3N via meklab. I change tech lvl to Standard. Then i drop all the weapons and ammo but the 2 large lasers and put in a pair of ultra AC/5 for the arms and a ton of ammo for the CT. Thats it.

Mech status switch to reffiting but it never seems to update the time (or the even show) to complete it, even after months of passing time and making sure i have all the needed parts.

Done some testing: I have tried getting the parts before making the customization and it still says i need 9 double heat sinks (though i have 10 already) and one Ultra AC/5 ammo bin (which btw doesnt show in the parts market but still have due to cancelling a prior try)

Even tried doing some custom job to my stalker, dropping things and getting lrm20 with artemis with the same result...

Files
[Refit Problem RFL-3N.zip](https://github.com/MegaMek/mekhq/files/3663874/Refit.Problem.RFL-3N.zip)

**Comment by Nar11** [comment]
[megameklog.txt](https://github.com/MegaMek/mekhq/files/3664132/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/3664133/mekhqlog.txt)

**Comment by HammerGS** [comment]
Did a quirk search of the log and found these references, 

> 11:11:27,211 ERROR [mekhq.campaign.parts.Refit] {AWT-EventQueue-0} 
> part with id 0 not found for refit of RFL-3N Mk II (Class D (Maintenance)/16560 minutes/415,000 C-Bill)
> 
> 11:12:32,645 ERROR [mekhq.campaign.parts.Refit] {AWT-EventQueue-0} 
> part with id 0 not found for refit of RFL-3N Mk II (Class D (Maintenance)/16560 minutes/415,000 C-Bill)
> 
> 11:12:33,908 ERROR [mekhq.campaign.parts.Refit] {AWT-EventQueue-0} 
> part with id 0 not found for refit of RFL-3N Mk II (Class D (Maintenance)/16560 minutes/415,000 C-Bill)
> 
> 11:12:36,524 ERROR [mekhq.campaign.parts.Refit] {AWT-EventQueue-0} 
> part with id 0 not found for refit of RFL-3N Mk II (Class D (Maintenance)/16560 minutes/415,000 C-Bill)
> 
> 11:12:39,192 ERROR [mekhq.campaign.parts.Refit] {AWT-EventQueue-0} 
> part with id 0 not found for refit of RFL-3N Mk II (Class D (Maintenance)/16560 minutes/415,000 C-Bill)

Din't see any NPE's but did find a couple of these.

> java.io.FileNotFoundException: mmconf\mekhq.preferences (El sistema no puede encontrar el archivo especificado)
> 	at java.io.FileInputStream.open0(Native Method)
> 	at java.io.FileInputStream.open(Unknown Source)
> 	at java.io.FileInputStream.<init>(Unknown Source)
> 	at java.io.FileInputStream.<init>(Unknown Source)
> 	at mekhq.preferences.MekHqPreferences.loadFromFile(MekHqPreferences.java:54)
> 	at mekhq.MekHQ.startup(MekHQ.java:285)
> 	at mekhq.MekHQ.main(MekHQ.java:357)
