### ISSUE TITLE
enhancement: personnel overview ATB inclusion

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#1299]
When running ATB rules with leadership rules on the personnel overview tab it would be nice if your current and max atb personnel counts were listed.  something along the lines of a single line under each column (combat, non-combat) 26/30 leadership combat limit, 28/30 leadership non-combat limit.  
 could even go the extra mile and add a note that would appear listing the retirement roll penalty if you are over the limit i.e.  "35/24 leadership combat limit-OVER LIMIT 1 point retirement penalty"
or "52/24 leadership non-combat limit-OVER LIMIT 2 point retirement penalty"

Right now it isn't hard to calculate it out myself, once you figure out what the software counts as "1 person", but I find myself doing it often, and it should be pretty easy as these are values the software already calculates.

**Comment by molemanBT** [comment]
I would like this too :)

**Comment by purpledragon2** [comment]
This would be nice to have.

**Comment by Bluespacer** [comment]
I think this would be useful.
