### ISSUE TITLE
Mechs hot-loading LRMs during battle.

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/mekhq#13]
Scjazz informed me that this is a bug when I told him about it and according to TacOps a mech should not be able to turn hot-loading on while in battle when it was set to off in the lobby.  Running the mekHQ 0.3.21 bundle of programs and I can turn hot-loading on when enemy mech get too close and turn it back off when the armor in that area where the ammo is stored gets too thin.  I actually like the bug and find it usefull but, I guess those aren't the rules.  Will attach game log and the rest of the files zipped up when I get home from work today.  Was supposed to do this last night but, ran out of time.

**Comment by arlith** [comment]
How are you turning hot-loading on and off?

**Comment by BLOODWOLF333** [comment]
In battle I go into the systems tab on the mech, click the LRM ammo and in the mode drop down box below it I select hot-load and MM announces that it will be hot-loaded next turn and it works.

**Comment by BLOODWOLF333** [comment]
[hotloadbug.zip](https://github.com/MegaMek/mekhq/files/125742/hotloadbug.zip)

**Comment by arlith** [comment]
You've got a gamelog, a megameklog, and a cpnx file.  Could you attach a MM saved game?

**Comment by BLOODWOLF333** [comment]
[HLGAMESAVE.zip](https://github.com/MegaMek/mekhq/files/125864/HLGAMESAVE.zip)

**Comment by BLOODWOLF333** [comment]
Been putting off downloading the latest release but, does this bug still apply?

**Comment by arlith** [comment]
This is really a MM bug.  I can't remember if there was a ticket in MM for it or not.  I remember looking into it and confirming that it was in fact a problem.  I don't recall if I fixed it or not.

**Comment by BLOODWOLF333** [comment]
Yeah thats my bad I put it on the HQ tracker, can I move it or just have to close it and create a new one.  You've commented on it already. https://github.com/MegaMek/mekhq/issues/13

Date: Thu, 21 Apr 2016 07:18:54 -0700

**Comment by arlith** [comment]
If there's a MM issue, you can close this one.

**Comment by BLOODWOLF333** [comment]
I will make one on the MM tracker then.
