### ISSUE TITLE
Cannot Advance Day past 4/21/3078

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/mekhq#130]
I've managed to hang something up in the attached campaign to where I can't advance the day. I'm having trouble figuring out what it is from the log - it looks like it might be one or more parts on order. Help?

[mekhqadvanceDayErrors.zip](https://github.com/MegaMek/mekhq/files/394722/mekhqadvanceDayErrors.zip)

**Comment by HammerGS** [comment]
Relevant NPE from Log:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.campaign.parts.EnginePart.getAvailability(EnginePart.java:220)
	at mekhq.campaign.unit.Unit.getAvailability(Unit.java:3261)
	at mekhq.campaign.unit.UnitOrder.getAllAcquisitionMods(UnitOrder.java:283)
	at mekhq.campaign.Campaign.getTargetForAcquisition(Campaign.java:5916)
	at mekhq.campaign.Campaign.acquireEquipment(Campaign.java:1695)
	at mekhq.campaign.market.ShoppingList.newDay(ShoppingList.java:151)
	at mekhq.campaign.Campaign.newDay(Campaign.java:2438)
	at mekhq.gui.CampaignGUI.advanceDay(CampaignGUI.java:4111)
	at mekhq.gui.CampaignGUI.access$5100(CampaignGUI.java:280)
	at mekhq.gui.CampaignGUI$106.actionPerformed(CampaignGUI.java:3322)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)

**Comment by mkerensky** [comment]
This apparently rates as a bug, so might I ask what the log says is happening?

**Comment by arlith** [comment]
This is the code at the line failing:

```java
int year = campaign.getCalendar().get(GregorianCalendar.YEAR);
```

It looks like you have an `EnginePart` with a null `Campaign` reference.

**Comment by mkerensky** [comment]
I have dozens of engines in inventory, most have been there a while from using the Add as GM option. The others were salvaged and repaired.  Any way for me to tell which one is bad?

**Comment by mkerensky** [comment]
Maybe this?

<part id="386072" type="mekhq.campaign.parts.MissingEnginePart">
			<id>386072</id>
			<name>280 Light Engine</name>
			<unitTonnage>70</unitTonnage>
			<hits>0</hits>
			<timeSpent>0</timeSpent>
			<mode>0</mode>
			<skillMin>1</skillMin>
			<unitId>bdd6a493-483f-4507-8daf-adf220b2dba2</unitId>
			<workingOvertime>false</workingOvertime>
			<shorthandedMod>0</shorthandedMod>
			<refitId>null</refitId>
			<daysToArrival>0</daysToArrival>
			<brandNew>false</brandNew>
			<quantity>1</quantity>
			<daysToWait>0</daysToWait>
			<replacementId>-1</replacementId>
			<quality>3</quality>
			<isTeamSalvaging>false</isTeamSalvaging>
			<parentPartId>-1</parentPartId>
			<daysToWait>0</daysToWait>
			<replacementId>-1</replacementId>
			<engineType>5</engineType>
			<engineRating>280</engineRating>
			<engineFlags>0</engineFlags>
			<forHover>false</forHover>
		</part>

**Comment by arlith** [comment]
Yea, I looked at the XML, and I didn't see the `Campaign` reference in any of parts XML, so I'm not precisely certain where it's stored.  Someone else more familiar with MHQ may have to chime in.  The `Campaign` reference is passed when a part is instantiated, and I thought about chasing down whether there's a case where it can be null, but there were a number of references and I didn't really have the time.

**Comment by Akjosch** [comment]
Loading up the campaign save, I can say that `Campaign#refreshNetworks()` is crazily expensive. Why does MekHQ even *care* for C3 networks?

**Comment by arlith** [comment]
I had noticed that the campaign took quite a long time to load, but I didn't bother to look why (I started loading it, then got pulled away and forgot about it, came back and noticed it was still loading, thought it was strange,  then it finished.  I didn't really think about how long it had taken, but I bet it was a while).

I know that I have had to fix the MM ECM computation code in the past for what may be similar reasons.  Basically, it was recomputing all of the ECM in the game for each unit in the game at the end of every turn (for sensor information in DB games I believe).  Caching the ECM computation sped things up considerably for games with a large number of entities.

**Comment by mkerensky** [comment]
I did further testing with this and fixed the advance day problem.  The log shows a Maxim I Company Command variant on order that's trying to load with parts. When I deleted this and reordered it (rolling successfully this time), I was able to proceed.

Strangely, the Hangar tab was also unable to display properly as long as the Maxim entry was in the procurement list, and that issue also cleared up.

The campaign file takes about 15-20 minutes to load for me. I thought that was just because it has so many units and personnel in it and accepted it as normal.

I also thought that MekHQ cares about C3 networks so that it can drop a properly configured C3 lance/company/Level II  into MM when it launches a scenario, which it currently does a good job with.

**Comment by Akjosch** [comment]
Yes, the Maxim tank is the one which has the broken parts, I just wasn't able to hunt down *where* they get created in the first place.

**Comment by mkerensky** [comment]
If it helps, the tank on order is replacing one that was totally destroyed in the most recently completed scenario of the contract that's still in progress. The destroyed tank was a member of Mosquito company, 6th armored battalion. 

Mosquito company is C3-enabled. Since we got to talking about C3 networks in this thread, maybe the broken network is part of what happened...

**Comment by Akjosch** [comment]
The C3 loading "problem" is unrelated; I commented out the offending method and it still broke as usual. Turns out, unit orders weren't initialised properly on load.

There are some other issues your campaign file shows (like the fact that the parts are checked if they are "spare" some 2 *billion* times), but the specific bug should be fixed in the next daily/release.

**Comment by pheonixstorm** [comment]
HQ tracks C3 networks so it can get passed correctly into MM. There may be some areas where that code can be rewritten to run faster but I have never looked at it and it has caused its fair share of issues in the past.
