### ISSUE TITLE
Bonus levels on Leadership skills not included in Overview > Unit rating tab

### ISSUE THREAD

**Issue by molemanBT** [MegaMek/mekhq#1306]
My Company commander has several 'bonus' +1's in leadership related stats (leadership, strategy, tactics). These +1's do not show up on the Unit rating tab in mekhq. For example, she has 1 level of leadership, and 2 bonus levels, making +3 (you can see this on the personnel tab) however, Unit rating only sees the +1.

I think this also occurs with other instances such as strategy levels giving a re roll on weather conditions etc. (i.e. she has a bonus +1 on strategy and tactics, however, no re roll on scenarios).

I don't know if this problem recurs elsewhere too.

### Environment
What version of MekHQ does your issue apply to? Latest
What operating system are you using?  Windows

[The Nidhoggr30250516.zip](https://github.com/MegaMek/mekhq/files/3707422/The.Nidhoggr30250516.zip)

**Comment by Windchild292** [comment]
Can confirm that the bonus is not applied to the Unit Rating for FM:M(r).

**Comment by Windchild292** [comment]
For FM:M(r), I believe the changes would need to be applied in FieldManualMercRevDragoonsRating.java getCommanderValue method.

**Comment by sixlettervariables** [comment]
Implemented in #1373
