### ISSUE TITLE
Units and parts are always limited by year when you attempt to refit the unit on MekHQ.

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/mekhq#1310]
### Environment
Ver 0.47.0

### Description
For example, if you have a unit with year of 3145 and a Radical Heat Sink System, you may have it if the campaign's tech level is unofficial and does not check 'Limit Units and Parts by Year' even if your year is below of that. But, if you want to edit it on MekHQ by 'Customize in Mek Lab', it is not possible because the year restriction is conflict with the campaign's current year.

**Comment by NickAragua** [comment]
You also have to change the unit's tech level from "intro" or "standard" to "advanced", "experimental" or "unofficial".

**Comment by binaryspica** [comment]
> You also have to change the unit's tech level from "intro" or "standard" to "advanced", "experimental" or "unofficial".

So, even if some item is valid on the individual unit's own year, the individual unit's tech is have to be unofficial as well if the year is not matched with the year of the campaign?

**Comment by NickAragua** [comment]
Something like that. e.g. if you want to put a binary laser on a 3028 Wolfhound, you have to set its tech level to Experimental.

**Comment by binaryspica** [comment]
I did but it was failed because the year is fixed to your campaign's year.

**Comment by Windchild292** [comment]
Subsumed by #1589.
