### ISSUE TITLE
Unable to assign wounded

### ISSUE THREAD

**Issue by purpledragon2** [MegaMek/mekhq#132]
I just finished a battle AtB.  One of my warriors took a head hit during the fight and has the corresponding dmg applied to his person.  When I go to the infirmary, I can highlight the warrior and the doctor but can not assign him.  clicking the assign button has the button do a little "highlight/light flash" as if it is doing something; but, the warrior does not get moved.  I have tried to choose different doctors.  temp medics is at full strength.   I have advanced the day.  Only thing left is save game and reload to see if that fixes it.

troubleshooting attempted per this conversation  http://bg.battletech.com/forums/index.php?topic=53976.msg1243992;topicseen#new

Sysinfo:

AMD phenome 9850 quad core 2.5 Ghz
RAM = 4 GB
64 bit operating sys
using windows 7 home premium SP1

NVIDIA Graphics Card GeForce GTS 250

campaign file attached per request; no custom units (the custom files, I believe will include Ralgith's customs if I include it.  If you still want, just let me know).  
[Current Game.zip](https://github.com/MegaMek/mekhq/files/405923/Current.Game.zip)

**Comment by pheonixstorm** [comment]
@purpledragon2 with all the updates and work done to medical so far is this still an issue for you or has it been resolved?

**Comment by purpledragon2** [comment]
I have not been able to recreate this issue.  Do I need to close it?

**Comment by pheonixstorm** [comment]
It is possible this was one of the 0-day injuries though I have not looked at the campaign file.

Since it isn't happening anymore you can probably close this for now. If it happens again you can come back and reopen this ticket.

**Comment by purpledragon2** [comment]
unable to recreate.
