### ISSUE TITLE
47.1 unable to complete scenarios that have been manually added 

### ISSUE THREAD

**Issue by servo01** [MegaMek/mekhq#1327]
47.1
Linux

Scenarios that have been added manually (without use of the Scenario Template Editor) will play normally, but upon completion -after being asked which side controlled the battlefield- return to the MegaMek lobby (rather than displaying salvage/kill log/injuries/etc) and will not import any information back to MekHQ.

Attempting to load and replay from a save file or to resolve the scenario manually are also unsuccessful.

Issue encountered with clean install, using supplied campaign with unmodified settings upon "load last save" - Received error message when attempting to save.

![Screenshot_2019-11-07_17-40-14](https://user-images.githubusercontent.com/30708294/68442509-0d621a80-0186-11ea-8cf5-ac46411c6921.png)
![Screenshot_2019-11-07_17-40-36](https://user-images.githubusercontent.com/30708294/68442512-118e3800-0186-11ea-97b4-22e21ce9457f.png)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/3822570/mekhqlog.txt)

**Comment by NickAragua** [comment]
Man, we've got too many damn features. :D
