### ISSUE TITLE
47.1 Issue with Allied Traitors mission resolution

### ISSUE THREAD

**Issue by illrede** [MegaMek/mekhq#1329]
![Allied Traitors](https://user-images.githubusercontent.com/57513507/68445523-28de1d00-01a8-11ea-818a-dcc3bfc500e7.png)

0.47.1, Windows, Java (build 1.8.0_231-b11)

When resolving the Allied Traitors special mission, enemy units destroyed (supposed to show up in the "force withdrawal" area show up in the "preserve" area, meaning the "force withdrawal" objective can't be met. Player unit does not show up in the "preserve" area.

**Comment by NickAragua** [comment]
Appreciate the feedback. Should be easily fixable. As a workaround meanwhile, you can manually declare the scenario a victory in the subsequent screen.

**Comment by illrede** [comment]
![Civilian Help](https://user-images.githubusercontent.com/57513507/68446275-4a400880-01aa-11ea-9eb3-7ef4d30212fe.png)

There was also a problem with the "Civilian Help" special mission where the survival objective was duplicated and the first one had no option for selecting units.

**Comment by NickAragua** [comment]
Yeah, looks like there's an issue that affected pretty much all atb scenarios that require individual unit deployment.
