### ISSUE TITLE
[0.3.31 : Error] Traitor then ejected units not available for salvage

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#133]
As per title, Princess' units /traitor to myself then ejected is not available for salvage at the end of the game.

Attached campaign file, game's last round and custom units for testing. Check the round reports and you will notice that I /traitor and ejected 2 Intrepid Assault Crafts and a Jumbo dropship.

[TraitorThenEjectedUnitsNotForSalvage.rar.txt](https://github.com/MegaMek/mekhq/files/408745/TraitorThenEjectedUnitsNotForSalvage.rar.txt)

**Comment by mkerensky** [comment]
You can do that with /traitor and princess?  I knew that you could kick princess out, connect a second client and traitor the units over, if that's what you're doing.

**Comment by SirMegaV** [comment]
Yup. That's what I did. Kick princess, login as Princess, then traitor then
eject.

**Comment by Dylan-M** [comment]
I would have to say this isn't likely to ever be supported. Just eject them when you log in, if you have to log in anyway to /traitor. The reason they're not being offered for salvage is that the game doesn't see them as enemy units after you /traitor them. It seems them as **your** units.
