### ISSUE TITLE
SIMCA ambulance can not be purchased nor added...  (AtB)

### ISSUE THREAD

**Issue by purpledragon2** [MegaMek/mekhq#1332]
SIMCA ambulance can neither be purchased nor GM added

###
PC = i9 9900k with GTX 2080ti GPU.  
MekHQ vers. 0.47.1
 Windows 10 Home
Java version 1.8.0_231
	Platform Windows 10 10.0 (amd64)
	Total memory available to MegaMek: 932,352 kB

(Delete the above lines)

### Description
attempting to purchase the SIMCA throws "unit not found" every time you advance the day.  Might be a contact on planet or might not.  If there is one, then nothing else.  
Attempting to GM add the SIMCA produces no result.  

### Files
[Autosave-0-My Campaign-30190104.cpnx.gz](https://github.com/MegaMek/mekhq/files/3829657/Autosave-0-My.Campaign-30190104.cpnx.gz)
[custom_spa.txt](https://github.com/MegaMek/mekhq/files/3829658/custom_spa.txt)

**Comment by HammerGS** [comment]
Need the Megameklog.txt and mekhqlog.txt files as well.

**Comment by CrimsonThunderSB** [comment]
I have something with this same unit that is likely causing my campaign to not load if I should put it in a different issue...I will explain whats happening.

**Comment by purpledragon2** [comment]
[Uploading megameklog.txt…]()
[Uploading mekhqlog.txt…]()

**Comment by purpledragon2** [comment]
Happy to give anything that can help to determine the problems.

**Comment by sixlettervariables** [comment]
Related #1333

**Comment by neoancient** [comment]
The problem with loading a campaign that contains a support vehicle was fixed in #1334.
