### ISSUE TITLE
NPE when completing a scenario if captured vehicle has a critical commander hit

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/mekhq#134]
I did a scenario against a number of vehicles. One of the enemy vehicles (entity from the MUL is below) was immobilized but also suffered a commander hit. When resolving the fight in MekHQ, a NPE was thrown (see below). The problem is related to the line ` <tcriticals commander="hit"/>`.

Entity:

		<entity chassis="Condor Heavy Hover Tank" model="(Flamer)" type="Hover" commander="false" offboard="false" hidden="false" deployment="0" deploymentZone="-1" neverDeployed="false" externalId="74d77c63-5869-4845-bcc3-0f1b40fd6913" camoCategory="-- No Camo --">
			<pilot name="Noboru bin Altair" size="4" nick="" gunnery="5" piloting="6" ejected="false" externalId="7eb1e82c-d2fe-456c-b83e-bddac038815a"/>
      <motive damage="9" penalty="2"/>
      <tcriticals commander="hit"/>
      Tanks have special needs, so don't delete any ammo slots.
      The first slot in a location is at index="1".
			<location index="0"> Body
				<slot index="1" type="IS Vehicle Flamer Ammo" shots="19"/>
				<slot index="2" type="IS Ammo MG - Full" shots="198"/>
			</location>
			<location index="1"> Front
				<armor points="27"/>
			</location>
			<location index="2"> Right
				<armor points="9"/>
			</location>
			<location index="5"> Turret
				<armor points="19"/>
			</location>
		</entity>

Error:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.campaign.unit.Unit.isCommander(Unit.java:3163)
	at mekhq.campaign.ResolveScenarioTracker.checkStatusOfPersonnel(ResolveScenarioTracker.java:683)
	at mekhq.campaign.ResolveScenarioTracker.processMulFiles(ResolveScenarioTracker.java:188)

**Comment by pheonixstorm** [comment]
This has already been reported in #67

**Comment by neoancient** [comment]
Fixed in [a3a90a4].
