### ISSUE TITLE
Number of Text issues in ATB briefings  

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/mekhq#1343]
With the new 47.1 release there are a number of Text issues in ATB briefings.  

Where previously they would list who controlled the battlefield after the battle, these descriptors are missing in this release from all missions.  

Further on the probe mission it lists 

Destroy, cripple or force the withdrawal of at least 25% of the following enemy force(s):
	Chaos March
	
Ensure that at least 25% individual units from the following force(s) and unit(s) survive: 

Meaning while I am racing to do 25% damage to the enemy, they need to do over 75% damage to me.  

Other mission types should be double checked for the new format, but if I see any others I will further update this issue.

**Comment by CrimsonThunderSB** [comment]
the same thing is happening in 0.47.2, if a probe should be only destroying 25% of enemy forces, then it should be 75% of your own forces need to survive, not 25%.  Also, unless the ATB rules are planning to be changed, there is no way to tell who controls the battlefield at the end of every scenario.  I shall inform of any other bugs I can note if I can find them.

**Comment by Rince-Wind** [comment]
Extraction: Attacker has some wrong conditions as well:
You have to keep 2/3s of your units alive (currently in game: half)
You have to save 1/2 of the civilians (currently in game: 2/3s)

**Comment by NickAragua** [comment]
Thanks guys, keep it coming. I'll batch the fixes up for next release.

**Comment by Rince-Wind** [comment]
Breakthrough (Attacker):
Text says to reach south edge. Deployment was in the south, making this rather easy.

**Comment by molemanBT** [comment]
Not sure if this belongs here or a new issue:

The scenario briefings have become insufficient in detail, for example, Star League Cache, no longer instructs how many mechs I should be deploying, I appreciate the brevity of the new descriptions, however, I think the previous descriptions were much more effective for a computer game, below is the information for Star League Cache 1:


Destroy, cripple or force the withdrawal of at least 100% of the following enemy force(s):
	Lyran Commonwealth
	

Ensure that at least 1 individual units from the following force(s) and unit(s) survive:
	

Ensure that at least 1 individual units from the following force(s) and unit(s) survive:
	Tech

**Comment by molemanBT** [comment]
Resolving the above mission was confusing also, I've attached an image, I lost the fight as the tech punched out of the MCY-99. In the Objective status screen, the instructions are to 'check the status of scenario objectives', it says 'preserve 1' above my mech and the MCY-99. Both boxes are auto ticked. The MCY was destroyed (ejected from) but the Hermes was fine. I do not know if the boxes should be ticked to indicate destroyed, or unticked.

Some more plain language would help in this section, i.e. tick the boxes of the mechs that survived, if that is what is being asked.

Apologies if this sounds over critical.
<img width="300" alt="obj stat" src="https://user-images.githubusercontent.com/22913396/69801125-7b6e9000-11ce-11ea-895d-853901e72d33.PNG">

**Comment by MarcJC** [comment]
Extraction attacker briefing does not mention the time limit for the scenario, or any other end conditions, implying that all enemy units need to be destroyed.

**Comment by NickAragua** [comment]
Status update for pending fix:

Battlefield control descriptions - updated
Probe briefing - updated
Breakthrough briefing - updated
Extraction briefing - updated
Briefings for special missions mention what to deploy - done

**Comment by NickAragua** [comment]
@molemanBT For scenarios which require manual unit assignment, the objectives won't fully populate until after you assign the unit and refresh the scenario (by clicking away from it and then coming back). I'll need to spend some time thinking about the objective UI on the scenario resolution screen.

**Comment by NickAragua** [comment]
I'll keep this open in case other issues come up, but I think I've caught all of the briefing issues (and then some). The objective section of the scenario resolution screen now features more detailed instructions.

**Comment by Windchild292** [comment]
I think we can close this given there has been no comments since December, thoughts @NickAragua?

**Comment by NickAragua** [comment]
Yeah, I think so.

**Comment by MarcJC** [comment]
I know we wanted this one closed but I just hit Star league Cache mission 2 

this is the info you get 

[code]
Use the TO&E interface to deploy a single unit to this scenario.

Destroy, cripple or force the withdrawal of at least 100% of the following enemy force(s):
	Chaos March
	

Ensure that at least 1 individual units from the following force(s) and unit(s) survive:
	

Ensure that at least 1 individual units from the following force(s) and unit(s) survive:
	Tech
	

Destroy, cripple or force the withdrawal of at least 100% of the following enemy force(s):
	Chaos March
	

Ensure that at least 100% individual units from the following force(s) and unit(s) survive:
	

Winner controls the battlefield after the battle. 
[/code]

If I was first starting to play ATB I would have no clue what was going on here.  
In the old briefing it tells you that a cache was found and if it was you or the enemy that found it.  
I think this is the one that your tech is piloting the SL mech but there is no way for a new player to know which side the tech is on.  There is also no text about the employer wanting to take the mech if the fight is pre 3050  

I think these things need to be in the briefing text, for the next version.  
I know SL Cache 1 was listed above in the ticket, but I would assume that needs to be checked also.  

Sorry to have to reopen a closed ticket, I wish I could let this one just stay closed.

**Comment by HammerGS** [comment]
Re-open pending review.

**Comment by MarcJC** [comment]
Played through the the SL Cache 2 mission, and no tech appears as the SL mech is being piloted by princess.  The resolution tech however attempts to find the tech mentioned and assigns a penalty because no tech was deployed.  This code line (which I assume was copied over from SL Cache 1) needs to be removed from SL2

**Comment by MarcJC** [comment]
Found another one on the Prison Break special mission 

[code]
Ensure that at least 1 individual units from the following force(s) and unit(s) survive:
	Vixen (Incubus) (Standard)
	 for at least 8 turns

Ensure that at least 1 individual units from the following force(s) and unit(s) survive:
	Prisoners
	1 bonus roll per surviving unit
	 for at least 8 turns

Destroy, cripple or force the withdrawal of at least 100% of the following enemy force(s):
	Guards
	Grants battlefield control
[/code]

The last line of Grants battlefield control is very vague.  

I think what this is trying to say is that if you defeat 100% of the guards in the eight rounds you get control of the battlefield , otherwise the guards control the battlefield.  

In which case (If I am reading it right) it would make more sense to say - Completion of this objective gives control of the battlefield to the Prisoners, otherwise the Guards control the battlefield.

**Comment by Windchild292** [comment]
Thoughts on this display for the Prison Break?
![image](https://user-images.githubusercontent.com/39067288/83544564-1ae94400-a4cc-11ea-81ac-a6b418eac6b6.png)

**Comment by CrimsonThunderSB** [comment]
> Thoughts on this display for the Prison Break?
> ![image](https://user-images.githubusercontent.com/39067288/83544564-1ae94400-a4cc-11ea-81ac-a6b418eac6b6.png)

I think that's really good actually

**Comment by MarcJC** [comment]
While it is pretty good I am putting my idiot hat on to look at it.  
When I look at the last lines it still implies that 100% of the guards are needed to be defeated for the mission to be a success.  
I still think we need the word "if" or to label the objective "optional" so that it is clear that you can win without defeating all the guards.

**Comment by Windchild292** [comment]
I'm going to open up a RFE for that, as that would be beyond just a text issue fix.
