### ISSUE TITLE
When assigning techs to units in 47.2, skills listed as "unknown"

### ISSUE THREAD

**Issue by illrede** [MegaMek/mekhq#1344]
Version 0.47.2, Windows, Java (build 1.8.0_231-b11)

In MekHQ, when assigning a tech to a unit in hanger, the available techs have a skill rating of "unknown".

For confirmation testing opened old (47.1) campaign file without that issue in 47.2.

![skill unknown issue](https://user-images.githubusercontent.com/57513507/68986960-9adee380-07f2-11ea-9793-0ed5dd85383d.png)

**Comment by sixlettervariables** [comment]
All of that code is pretty old and was not changed in 47.1 -> 47.2. Can you add a copy of your CPNX, any customs, and your Mekhqlog.txt?

**Comment by illrede** [comment]
Further testing, issue happens only when assigning (mech) techs to protomechs (not Battlemechs, or Aero Techs to Aerospace, BA Techs to Battle Armor or Mechanics to Tanks) in the Hanger tab.

**Comment by illrede** [comment]
[Blood Follows30670101.zip](https://github.com/MegaMek/mekhq/files/3854075/Blood.Follows30670101.zip)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/3854077/mekhqlog.txt)

**Comment by sixlettervariables** [comment]
Protomech was the ticket, thanks.
