### ISSUE TITLE
Against the Bot via mekhq documentation/manual

### ISSUE THREAD

**Issue by Menzius** [MegaMek/mekhq#135]
The current help file mekhq/docs/against_the_bot.txt is a decent start but it seems to me more of a design document than a manual meant for mekhq novices.

Thus I had the idea to create a full documentation for AtB in mekhq. The goal is to create a file/set of files which allow someone to get a grasp on AtB with the least amount of effort, including gathering information/help from external sources. There have been several pastebins, youtube videos and forum threads (esp. http://bg.battletech.com/forums/index.php?PHPSESSID=ijol3jbfeeegso2dvfe1d2itn0&topic=41494.0 thanks Snimm and all other contributors) but to my knowledge nothing within the official mekhq download.

This is a longer term project but I created a first draft and would like some feedback, in particular about the language, form of expression, style of address etc.. 

Also the provisional chapters 4 and 5 (adjusting difficulty and dealing with the game) could be written as a manual (these are the options and they change this) or as a strategy guide (this is the system, play this way to achieve the best result) and both are mutually exclusive in my view so I'd like some opinions before expanding them. Both type of questions seem to come up on the forum or IRC. 
[AtB documentation.txt](https://github.com/MegaMek/mekhq/files/418231/AtB.documentation.txt)

**Comment by HammerGS** [comment]
I'll start a thread on the Megamek.info forums and attached the document there.  I can also start a thread on the official forum but won't be able to sticky the forum.

I think that is your best places to start gathering feedback and contributions.

Thoughts?

**Comment by Menzius** [comment]
I agree that both forums are a good place to get feedback, I do lurk but dont have an active account yet. If you think the text is of a quality level required to start an open discussion I'd be obliged if you post it.

**Comment by HammerGS** [comment]
I think as a launching point the document is good.  Let me know if you want me to post as a Dev or if you'll do it.

If you post on our MegaMek forums I'll make sure it gets stickied.

**Comment by Menzius** [comment]
Go ahead and post please, I do not have an account on megamek.info yet and my bt.com account is probably lost in the sands of time.

**Comment by HammerGS** [comment]
Posts are up on the official and our forums.

**Comment by neoancient** [comment]
The master document is now available for public viewing on Google Docs here: [Against the Bot manual] (https://docs.google.com/document/d/1kLdZ-hF4B-uVeKH0Qb8IQ7fOwV8HA8bW1Ta_e3c8w9g/edit?usp=sharing). Anybody who would like to contribute can send me an email address via forum PM or email (my username at megamek.org) and I will give you edit permissions.

**Comment by arlith** [comment]
Google Docs is a good option.  Ralgith and I have been discussing options.  We have considered making the GitHub wiki publicly writable, and having the AtB manual be there.  Seems to me like there are plenty of people who would contribute if it's easy to edit.

**Comment by Menzius** [comment]
I finished chapter three and fixed some minor typos. The most recent version is attached.

I am not sure if posting this documentation on a wiki is the best way to publish it because it requires an extra step in the search for information. Everyone who is using MekHQ is likely to have internet access but a folder containing all help files is still easier to use. On the other hand it might allow the use of some screenshots and a better layout.

The suggestion to include the rules.xls in the official download is very good and makes writing this manual a bit easier. I hope that the original/current rules creator agrees and the file will be included in the MekHQ archive.

At this point I don't think it is useful to include MegaMek or BattleTech descriptions in this file, There should be better ways to explain to the user what they are, e.g. on the website or in the general readme file. A wiki would be a different situation of course.

I am still looking for opinions on how to write chapter 4 and 5. I don't want to spoiler things for people looking to figure out the system for themselves, which would happen if I write it as a walkthrough but at the same time there are frequent questions about not only the options but the actual play.

@neoancient 
I looked at your AtB option preset and the only significant difference to what I'm writing here is the maintenance part. Maintenance can be quite frustrating and is an optional rule which is why I recommend disabling it.
[AtB documentation 19_8.txt](https://github.com/MegaMek/mekhq/files/427760/AtB.documentation.19_8.txt)

**Comment by GustavKuriga** [comment]
I would definitely suggest an online wiki.

**Comment by pheonixstorm** [comment]
Wiki would be nice
Using this to create a searchable PDF would be nice too. Can be done with OpenOffice, maybe MS Office (don't use it so don't know).

**Comment by neoancient** [comment]
We don't have to choose between a text document distributed with MHQ and a wiki. My plan is to include this document in the docs folder of MHQ as a handy reference document, while the wiki can be much more detailed.

I have updated the Google Docs copy to reflect the latest changes.

**Comment by arlith** [comment]
> I would definitely suggest an online wiki.

Apparently, we already have one.  Our plan has been to using the GitHub wiki at : https://github.com/MegaMek/megamek/wiki.  I had thought that we needed to edit user permissions to allow users to edit it, but from what I can tell, any user can edit the wiki automatically.

**Comment by purpledragon2** [comment]
It is a mistake to assume everyone using mekhq has internet access.  I, for example, download the new version to a flash drive and when I see my friend who lives in the boonies and plays this I copy the newer version over to his computer.

**Comment by arlith** [comment]
I agree that it is a mistake, however I also think that an editing environment that encourages collaboration (like a wiki) will lead to a better document.  Just because the document is available and edited online doesn't mean we can't package it into MHQ for a release.  For instance, the GitHub wikis can be checked out via git.

**Comment by Menzius** [comment]
I have been finally able to work some more on this and here is the latest version.
Chapters 1-3 have some minor changes, mostly to make them consistent with the current MekHQ release.
Chapter 4 was completely reworked and expanded, I decided to focus on options to make the game easier and only made some general points about how to play. 

to do: Chapter 5 and Chapter 6. Chapter 6 (FAQ) is going to be an ongoing affair as long as new questions  come up. 

[AtB documentation 02_10.txt](https://github.com/MegaMek/mekhq/files/504910/AtB.documentation.02_10.txt)

**Comment by Windchild292** [comment]
Closing as largely outdated for documentation.
