### ISSUE TITLE
Ubuntu18.04 can't extract 47.2.

### ISSUE THREAD

**Issue by Bludlust135** [MegaMek/mekhq#1356]
when trying to extract the freshly downloaded version 47.2 of MekHQ, I get an error.
I'm on Ubuntu 18.04, java version "openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)"
The error is the following,

" Error opening file "/media/Drive 2/gaming/Battletech/MegaMek/MegaMekHQ/mekhq-0.47.2/data/boards/buildings_no_basement/Ueberlandstra?e 2.board":Invalid or incomplete multibyte or wide character."

**Comment by sixlettervariables** [comment]
This is during extraction or when running MekHQ?

**Comment by Bludlust135** [comment]
During Extraction

**Comment by sixlettervariables** [comment]
Okay, so your file system is not set for UTF8 file names. You'll want to look into converting your locale to UTF8 if feasible.

In the meantime we can look into renaming that file for 0.47.3.

**Comment by Bludlust135** [comment]
OK, I will do that. FYI... prior to 47.2, I had no trouble on this machine
with this exact set up....


Thanks for the help

**Comment by sixlettervariables** [comment]
That's helpful to know, the file is 6 years old. I wonder if our archive is to blame. @neoancient

**Comment by Bludlust135** [comment]
checking on my past installations of MekHQ, back to 43.11-RC5, I find that
file has the proper character gliph, (
*ß). *

**Comment by Bludlust135** [comment]
Attempted to install again, and got another error. Same one with a
different file name. This time under data/camo/periphery/Magistracy of
canopus.a folder has the accented a in the name. I removed that folder and
was then able to install. I copied the deleted file and folder from a
working copy of MekHQ, (47.1).

**Comment by neoancient** [comment]
I'm running Ubuntu 18.04.3 and I don't have any problems with extraction.

**Comment by sixlettervariables** [comment]
What is the SHA-256 of the .tar.gz you downloaded @Bludlust135 ? I get:
```
wsl:~$ sha256sum mekhq-0.47.2.tar.gz
cd0ba7d96a4d3c6f96db1bd1ebb35445b77eb4b646b9b1b11b8afbb37ce52c16 *mekhq-0.47.2.tar.gz
```

**Comment by sixlettervariables** [comment]
Comparisons of the 0.47.2 and 0.47.2 tar.gz and zip show that there are differences in the archives:
```
D:\xxx\Downloads>dir mekhq-0.47.1.tar\mekhq-0.47.1\data\boards\buildings_no_basement\Ue*.*
 Volume in drive D is Data
 Volume Serial Number is DAE7-DADC

 Directory of D:\xxx\Downloads\mekhq-0.47.1.tar\mekhq-0.47.1\data\boards\buildings_no_basement

11/05/2019  11:25 PM             5,707 Ueberlandstraße 2.board
               1 File(s)          5,707 bytes
               0 Dir(s)  916,039,569,408 bytes free

D:\xxx\Downloads\mekhq-0.47.1.tar>cd ..

D:\xxx\Downloads>dir mekhq-0.47.2.tar\mekhq-0.47.2\data\boards\buildings_no_basement\Ue*.*
 Volume in drive D is Data
 Volume Serial Number is DAE7-DADC

 Directory of D:\xxx\Downloads\mekhq-0.47.2.tar\mekhq-0.47.2\data\boards\buildings_no_basement

11/15/2019  04:37 PM             5,982 Ueberlandstra▀e 2.board
               1 File(s)          5,982 bytes
               0 Dir(s)  916,039,569,408 bytes free

D:\xxx\Downloads>dir mekhq-windows-0.47.2\data\boards\buildings_no_basement\Ue*.*
 Volume in drive D is Data
 Volume Serial Number is DAE7-DADC

 Directory of D:\xxx\Downloads\mekhq-windows-0.47.2\data\boards\buildings_no_basement

11/15/2019  02:37 PM             5,982 Ueberlandstra�e 2.board
               1 File(s)          5,982 bytes
               0 Dir(s)  916,039,569,408 bytes free
```
We'll have to take a look at why the 0.47.2 archives were created that way.

**Comment by Bludlust135** [comment]
this is my check sum. it is different from yours.

c4b9267dd4224f68ec070414b6acdb4046968271bb4ea1df4b1f0beba0c6e7c1
 mekhq-0.47.2.tar.gz
