### ISSUE TITLE
Quality of Life Feature Request:  Group Techs by Type and Skill Level on Hangar Tab

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/mekhq#1363]
We already have the desired functionality on the TOE > Assign Tech to Force right-click menu option. I'd just like to see available techs grouped by type and skill level on the Hangar > Assign Tech menu option.

Setting this request up here so it can be tracked. I can get it done after my current feature is finished unless somebody beats me to it.

**Comment by sixlettervariables** [comment]
I presume in the hangar you're looking for just the skill level sub-menus? It currently only pops a list of appropriately typed techs.

**Comment by sixlettervariables** [comment]
Is this what you were looking for?

![Screen Shot 2020-01-17 at 1 21 12 AM](https://user-images.githubusercontent.com/8238690/72588891-b3897980-38c7-11ea-8d0a-23d47883fca5.png)

![Screen Shot 2020-01-17 at 1 20 59 AM](https://user-images.githubusercontent.com/8238690/72588892-b4221000-38c7-11ea-9245-e951aad4a0e0.png)

**Comment by mkerensky** [comment]
Yes that's it.

**Comment by HammerGS** [comment]
Implemented..
