### ISSUE TITLE
MekHQ fails to compile

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/mekhq#1364]
### Environment
What version of MekHQ does your issue apply to? 16b36cd8f and following
What operating system are you using?  Windows, Mac, or Linux? Ubuntu Linux 19.10
What java version are you using?  11.0.5-ea

### Description
gradle compileJava task fails:
% ./gradlew assembleUnixDist
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true

> Task :MekHQ:compileJava
/home/mjackson/gitwork/mekhq/MekHQ/src/mekhq/campaign/mission/atb/scenario/BreakthroughBuiltInScenario.java:133: error: cannot find symbol
                        OffBoardDirection.getOpposite(OffBoardDirection.translateBoardStart(getStart())))
                                         ^
  symbol:   method getOpposite(OffBoardDirection)
  location: class OffBoardDirection
/home/mjackson/gitwork/mekhq/MekHQ/src/mekhq/campaign/mission/atb/scenario/BreakthroughBuiltInScenario.java:135: error: cannot find symbol
                        OffBoardDirection.getOpposite(OffBoardDirection.translateBoardStart(getEnemyHome())));
                                         ^
  symbol:   method getOpposite(OffBoardDirection)
  location: class OffBoardDirection
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/mjackson/gitwork/mekhq/MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

> Task :MekHQ:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':MekHQ:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
2 actionable tasks: 1 executed, 1 up-to-date

Commits 9cd944829 and previous build fine for me using the same setup.

**Comment by NickAragua** [comment]
Yeah, you gotta update the gradle project, as a change was made in the MegaMek jar that MekHQ is dependent on.

**Comment by mhjacks** [comment]
I wound up deleting my local maven repo.  Maybe too heavy handed, but it worked.   :) Thanks!

**Comment by sixlettervariables** [comment]
It only checks for updates every so often, and in some cases I've had to do that myself.

**Comment by neoancient** [comment]
It's every 24 hours by default.
