### ISSUE TITLE
Possible Issue with Salvage/Exchange Rights

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/mekhq#1365]
From this forum Post
https://bg.battletech.com/forums/index.php?topic=67776.0
### Environment
What version of MekHQ does your issue apply to? Looks like up to 47.2

### Description
Post 1
> So I've played MekHQ off and on for maybe 4 or 5 years I guess. I could have sworn in the past, I could Renegotiate Salvage Rights. Am I mis-remembering? If not, was it taken out? I have all 4 admin slots filled, and all four have a good Negotiation skill. I have my game set to use Field Manual: Merc (revised) rules, and in that particular manual, Salvage Rights *can* be negotiated.

Post 2

> There are some restrictions on it, but I can verify that the option to negotiate Salvage Rights does appear for at least some contracts, although it's probably labeled as something else.  If you increase that, you decrease Salvage, and usually vice versa.  The choice between normal salvage and Exchange doesn't seem to be negotiable, and Exchange Rights don't seem to function properly (or at least didn't in previous versions of MekHQ, so it's been a while since I accepted any contracts with "Exchange Rights").

### Files
None Available but will ask

**Comment by neoancient** [comment]
Salvage right cannot be renegotiated in AtB. See the v2.29 rules included in the docs folder.
