### ISSUE TITLE
Unit Rating FM:M(r): Default Quality Value is Elite

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/mekhq#1369]
The default value for Average Skill Rating is Elite, so you end up with a Quality of 40 and an overall Dragoons Rating of D(40) with a completely empty company. This should be changed to either None or N/A, with a 0 
![image](https://user-images.githubusercontent.com/39067288/71521661-a6143d00-288f-11ea-85e7-167b6ccb861a.png)

**Comment by sixlettervariables** [comment]
I believe the skill rating should be N/A if you have no personnel. Likewise, if you cannot calculate a Dragoon Rating it should be N/A.
