### ISSUE TITLE
Unit Rating FM:M(r): 0 dividends produce 0 results with non-zero divisors

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/mekhq#1370]
I'm not certain this is an issue, but it does appear to be. If you have a dividend of 0, and a divisor that isn't zero, I believe that it should say 100% for Dropship Capacity, Tech Support, Medical Support, and HR Support. Furthermore, it should be discussed whether 0/0 should produce 100% or 0%.
![image](https://user-images.githubusercontent.com/39067288/71522073-356e2000-2891-11ea-966a-cd90ea6ef1fc.png)

**Comment by sixlettervariables** [comment]
100% sounds Okay, but N/A may be a simpler option. It will likely depend on the code in question.

**Comment by Windchild292** [comment]
Based on the code, implementing 100% for 0/0 and 0/4 is significantly easier to do.

**Comment by Windchild292** [comment]
Based on the code, I'd change this to a bug. It was handled, but broke because of an issue of if statement ordering
