### ISSUE TITLE
Critical hits didn't transfer

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/mekhq#138]
I fired an LRM 20 at the rear of of a Griffin and critted the LTR, but there were no available crits. The crits didn't transfer to the CT as they should.

   LRM 20 at Griffin GRF-1N (Draconis Combine); needs 8, rolls 8 : 12 missile(s) hit (using Rear table).

        Griffin GRF-1N (Draconis Combine) takes 2 damage to LTR.
             6 Internal Structure remaining.
            Critical hit on LT. Roll is 11; 2 locations.
            Location has no more hittable critical slots.

**Comment by beerockxs** [comment]
Were the other crits already hit at the beginning of that weapons attack phase?
If not, no bug.

**Comment by Dylan-M** [comment]
Not a MHQ Issue.
