### ISSUE TITLE
Implement Aurigan Coalition 

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/mekhq#1380]
The Sourcebook House Arano - The Aurigan Coalition should be added into MekHQ. This will consist of adding the ranks, adding the factions, applying the changes to the planetary systems, and changing system events.

**Comment by Windchild292** [comment]
You can put me on this one, I've applied the Ranking System, created the Factions (ARC and ARD), added the war, and will be working on the events.

**Comment by NickAragua** [comment]
That reminds me, I should include the Sleipnir/Vargr APCs in the rat generator data update.

**Comment by Windchild292** [comment]
RAT is done, as are the planetary system changes. I'm half way done the events and will hopefully be done by end-of-week.

**Comment by NickAragua** [comment]
Implemented with PR #1398
