### ISSUE TITLE
Dark UI theme

### ISSUE THREAD

**Issue by twhws** [MegaMek/mekhq#1385]
Is it possible to have a dark theme in addition to ones already available ? Standard "black text on white background" is killing my eyes way too much, especially after long sessions.

**Comment by twhws** [comment]
Additional info. I've tried to force Java to use a specific LAF (Darcula, to be precise) via -Dswing.defaultlaf, but nothing changes. I guess MekHQ is rewriting this by a previously selected theme ?

**Comment by HammerGS** [comment]
Open request on the Megamek side as well - https://github.com/MegaMek/megamek/issues/1479

**Comment by DevCharly** [comment]
You could try FlatLaf (https://github.com/JFormDesigner/FlatLaf), which runs fine with Java 8+

**Comment by sixlettervariables** [comment]
Implemented in #1431.
