### ISSUE TITLE
Force Icons and Unit Sizes

### ISSUE THREAD

**Issue by txsoldier94** [MegaMek/mekhq#139]
Would it be possible to separate the echelon/unit size designator from the unit icons, and make that something that could be added on? That would reduce the number of icons necessary for any given force.

Apologies if this has already been addressed.

**Comment by pheonixstorm** [comment]
ralgith started working on an editor for the toe icons but hasn't been able to finish it yet due to RL.

**Comment by Dylan-M** [comment]
This was added in commit 78bc5f3
