### ISSUE TITLE
Critical campaign loading failure.

### ISSUE THREAD

**Issue by LancePatchwork** [MegaMek/mekhq#1390]
If a player save a unit wich come from the sourcebook Wolf & Blake - jihad it will corrupt the save as the XML parser will freak out when it sees the & sign.

Happent a few time and i fixed it manually by removing the offending character from my saves everytime. Might want to change the database and remove the & or store the sourcebook name in the save differently.

**Comment by sixlettervariables** [comment]
I've added the Gallowglas GAL-4GLSA from the source book and it saves/loads just fine. Is there a specific unit you've added?

**Comment by sixlettervariables** [comment]
I see now, this is a refit on one of those units.

**Comment by sixlettervariables** [comment]
Example failure:
[issue-1390-refitting.zip](https://github.com/MegaMek/mekhq/files/4054923/issue-1390-refitting.zip)

**Comment by LancePatchwork** [comment]
Yes my by bad forgot to specify a refit.

**Comment by sixlettervariables** [comment]
Fixed in #1391, available in the next release.
