### ISSUE TITLE
Logging Maintenance Rolls Option

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#14]
Logging Maintenance Rolls Option: If it is turned ON any unit that must make a maintenance roll during Advance Day will have the Maintenance History entries in the CPNX. Turning the logging option OFF doesn't remove the Maintenance History entry. Wasting a few KB (5kb) of space for every unit in the Campaign.

I would suggest that turning the Maintenance Logging Off should clear all the maintenance entries in the next save.

Attached is Customs, starting point for campaign and same campaign 40 or 50 days later.
[Maintenance Bug.zip](https://github.com/MegaMek/mekhq/files/133527/Maintenance.Bug.zip)

**Comment by Dylan-M** [comment]
I edited the title because this is an enhancement rather than a bug, and it is also fixed in 0a75c9c9.
