### ISSUE TITLE
Add Multi-Word Last Name Support

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/mekhq#1404]
This enhancement request is to add support for multi-word surnames (for example John Jacobson Smith, where John is the first name and Jacobson Smith is the surname). The primary area that will need to be changed is in how this is handled during marriages.

Only names of size 1 or 2 are currently supported as of #1401, and this will enhance that.

**Comment by Windchild292** [comment]
You can assign this to me as part of my personnel changes.

**Comment by VicenteCartas** [comment]
I would probably leave surname as a string where users can put as many words as they want, and remove logic related to marriages name changes. There are countries for example where people getting married won't change their last names, so it seems to be better to let the users just adjust last names if they feel like it.

Pretty much the same with kid names, the logic on how to decide the last name of the kids or other surnames depends on the country.

**Comment by Windchild292** [comment]
I've split it into Given Name and Surname in my changes, with the ability to easily customize how surnames work in the options menu.
