### ISSUE TITLE
Display Mother and Father for Children in the Force

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/mekhq#1405]
We currently have ancestor tags in the save file which records who the mother and father (if applicable) of children borne to members of the Force, but that information is not displayed. We should display this information in the Family Information Section of the Personnel Log.

**Comment by Windchild292** [comment]
I'll be picking this up, I'm pretty sure it will be an easy one to finish following up on #1406.

**Comment by sixlettervariables** [comment]
Closed by #1409
