### ISSUE TITLE
Add Setting to Automatically Select Premade MegaMek Maps for Scenarios

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/mekhq#1412]
This is an enhancement to implement a setting that, when selected, will occasionally (maybe make this configurable) select a premade map from the data folder when a scenario is generated.

**Comment by SimonLandmine** [comment]
Having had a look at what I think are the board generation guidelines for MekHQ (I could be wrong!), it looks like there might not be many valid premade maps as, if I'm looking at the right guidelines, the MekHQ maps are sized in multiples of 5, while many of the premade maps are sized in multiples of mapsheets (16x17). Additionally, while some of the battles are on fixed-size maps, many of them appear to have a random seed size, amended by force-size-based modifiers, which would result in a wide range of potential sizes. Also, the current dynamic terrain generation types provide a wide range of possible battlefield terrains, which would require quite a number of premade maps to replicate.

Doesn't mean that this isn't a bad idea, though ...
1. Generate map size under the current rules.
2. If there are 1+ premade maps that matches the generated size, add a small %age chance of picking a map randomly selected from that list (perhaps increase chance based on number of size-matching premade maps, but keep low, so the same battlefield doesn't keep cropping up).
3. If no premade maps exist of the generated size, or premade map chance not generated, use dynamic random generation as per usual.

Potential downside: Might result in the selection of maps that were designed with a specific scenario in mind, and just happen to match the generated dimensions.

**Comment by SimonLandmine** [comment]
Suggestion made by user on a Discord thread to allow some leeway for map size - e.g. if premade maps are within a certain tolerance of the 'generated map size', then they could be selected.

**Comment by Windchild292** [comment]
This is part of StratCon
