### ISSUE TITLE
Enhancement to Purchase Parts menu option

### ISSUE THREAD

**Issue by MageOhki** [MegaMek/mekhq#1429]
### Environment
Using Snapshot 47.3 

### Description
Under the Overview tab, Parts in use, there's an option while GM mode is engaged to add parts in bulk.  Under the Marketplace, Purchase Parts, while in GM mode you can only add one part at a time.  Would it be possible to *add* add parts in bulk to that section?

**Comment by Windchild292** [comment]
Yep, and I changed them to use the same ordering. PR will be opening up shortly
