### ISSUE TITLE
Getting Pregnant should show in Personnel Log

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#144]
Request an entry in Personnel Log for the date of getting pregnant also the delivery date.

**Comment by pheonixstorm** [comment]
easy enough, want the date of birth in the log too?

**Comment by scJazz2** [comment]
as mentioned... also the delivery date... so yeah date of birth

**Comment by Akjosch** [comment]
Shouldn't be too easy to add. A quick look into my general notes says something about a typical human pregnancy length being normally distributed around a mean of 252 days with a standard deviation of 9 days. Generate the conception (insemination) day instead of birth day, add a log file entry some weeks later when the docs find out during the regular check-up, done.

**Comment by scJazz2** [comment]
I don't think we need that level of detail but if you want go ahead.

**Comment by purpledragon2** [comment]
That level of detail would be cool for RP purposes.  But, I agree that it is not necessary for the scope of the game.

**Comment by pheonixstorm** [comment]
Akjosch... that is WAAAAAAY more than what is needed. So NO NO NO. There is already an entry in the daily log for conception and birth. The only thing this would add would be a personal log entry using what is already coded. PR done in 5-10 minutes. The question next though is if this extra logging should be optional. 

I really don't see the need to clog up my logs with conception dates. Don't really care about those and doubt I would find the log entry for when the child was born useful either. For regimental sized forces this could be too much information to track, though with the recent changes to how the logs are handled it may need testing. Things HAVE gotten better with the logs anyway. So I think optional may be the way to go. Guess when I have the time I will take care of this.

**Comment by Dylan-M** [comment]
Closing, since this was merged.
