### ISSUE TITLE
Unable to assign any units in TO&E to Dropship 0.47.3

### ISSUE THREAD

**Issue by CrimsonThunderSB** [MegaMek/mekhq#1441]
MekHQ 0.47.3
Windows 10

On the TO&E, unless I am doing something wrong, when I am attempting to assign a lance to a dropship, I keep getting an error that states that there are too many units of a type, and it does not matter which type of unit it is.  I have tried everything from Mechs, Aerospace Fighters, infantry, etc. And it all gets the same error, even though there is room for them on a drop ship.

![Bugged screen shot](https://user-images.githubusercontent.com/47725829/73602752-9e0e8380-4546-11ea-9375-f81d293e5962.png)

[Bugged Stormbringing Destroyers.zip](https://github.com/MegaMek/mekhq/files/4143526/Bugged.Stormbringing.Destroyers.zip)

**Comment by NickAragua** [comment]
Should be fixed, going to verify over the next couple of days.

**Comment by CrimsonThunderSB** [comment]
> Should be fixed, going to verify over the next couple of days.

Sounds great, please keep us informed, keep up the great work :D

**Comment by CrimsonThunderSB** [comment]
as of 0.47.4 the issue is still not fixed

**Comment by rroby1** [comment]
Wanted to report that I am running 0.47.4 and have no problems assigning units to dropships.

**Comment by mkerensky** [comment]
I found and corrected a few additional bugs with this, which should be available in 0.47.5.
These bugs affected selections of support vehicles and infantry, and tanks to a certain degree.

In testing, I am able to assign a nearly full complement to a Colossus class dropship (over 100 units), deploy the whole mess to a scenario and have all the units load in the dropship's bays properly in the lobby.

**Comment by Windchild292** [comment]
This has been fixed and is working in latest develop.
