### ISSUE TITLE
Planetary Acquisition can infinite loop under certain conditions

### ISSUE THREAD

**Issue by sixlettervariables** [MegaMek/mekhq#1447]
Updated information: It appears an issue with Planetary acquisition in Campaign Options is the root of this bug.  While solved on a short term basis, leaving this for future attempts to resolve the underlying problem for others.  (Turning Planetary acquisition off solved all the problems, my suspicion is it's related to purchasing in general, but I'm not a coder anymore, and I have no clue.)

Edit note: Other issue about internal to MHQ MML in unoffical tech level *not* showing battlearmor bays in Transport bays remains.

_Originally posted by @MageOhki in https://github.com/MegaMek/mekhq/issues/1444#issuecomment-581164000_

**Comment by servo01** [comment]
ANY part acquisition roll is causing my fresh install of 47.3 to lock completely. - Even with planetary acquisition turned off.

**Comment by sixlettervariables** [comment]
Fixed that as well @servo01, thanks for the heads up.

**Comment by sixlettervariables** [comment]
Fixed in #1448.
