### ISSUE TITLE
Force Icon does not appear in MekHQ

### ISSUE THREAD

**Issue by BlueThing00** [MegaMek/mekhq#145]
This zip contains two images.  One works as Force Icon and the other does not.  Both were created with MS Paint.

[MechBattalionIcons.zip](https://github.com/MegaMek/mekhq/files/447410/MechBattalionIcons.zip)

**Comment by scJazz2** [comment]
I don't think it is a bug

I think it was the lack of transparent

(one has transparency and works the other doesn't and does not.

**Comment by Dylan-M** [comment]
MS Paint is a pile of garbage, and not an approved editor for images used by the software. As @scJazz2 pointed out, this is an issue with the image rather than the software. Hence, closing this as WAD (Working as Designed)
