### ISSUE TITLE
0.47.3 - No Civilian Units Generated as Part of a Scenario

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/mekhq#1455]
I was testing out and trying to get all the potential line colours for the hangar tab on a test game, and it generated a Civilian enemy force with no units as part of the OpFor for a contract. That save file and the log are both attached.

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/4162695/mekhqlog.txt)

[HangarColours.zip](https://github.com/MegaMek/mekhq/files/4162697/HangarColours.zip)

**Comment by NickAragua** [comment]
Looking at the code, the only way this exception happens is if the RAT Generator hasn't finished populating yet.

**Comment by Windchild292** [comment]
And I've had this happen multiple times now, once an hour after I loaded a game...

**Comment by NickAragua** [comment]
Yeah, the log indicates the RATs finished loading some time after the exception was thrown. I'll introduce some defensive coding to the generate method that will have it wait a little bit.

**Comment by NickAragua** [comment]
I'll leave this open so we can keep an eye on it once this fix goes out.

**Comment by Windchild292** [comment]
@NickAragua 
There have been a pair of reports of this fix not working.

**Comment by Windchild292** [comment]
Closing as a duplicate of #1166
