### ISSUE TITLE
RFE: Separate Folder to Hold User Files

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/mekhq#1477]
This is from Discord: "silly question, but I don't suppose you can set up a "my crap" folder seperate from the install path? and just point mekhq at it for your saves, settings, and customs?"

**Comment by binaryspica** [comment]
At least we need a clean blank folder for the default custom folder. For now data/mechfiles is filled by a bunch of canon data stuffs and I am always fear that I might touch any of these, and it is not so easy to identify which one is my own.

Well, you may make a folder and put your stuffs within there, but anyway a default folder should be blank, at least.

**Comment by neoancient** [comment]
As far as I know this isn't documented anywhere, and I'm not sure where the best place would be to document it, but if there is a folder named "userdata" MM/MML/MHQ  will look there first. So campaigns would be in userdata/campaigns, settings would be in userdata/mmconf, and customs would be in userdata/data/mechfiles. This allows user customized data to be transferred easily between installations. It does not support setting a specific directory outside the installation, but I don't see a reason to do it that way unless you're going to share the same data between different installations, which is probably not a great idea (assuming they are different versions).

**Comment by Windchild292** [comment]
I'm pretty sure that is exactly what the original poster was asking for, as an easier way to move data between installations. I think adding documentation for this would be a very good idea, as it would make user installation moves easier.

**Comment by binaryspica** [comment]
And can we have an option to select either only view default cache/custom units? After put the custom units it is merged with the default cache lists so sometimes I wonder that it is the canon unit or my custom one.

**Comment by rroby1** [comment]
Not sure the userdata folder idea works for everything. I’ve created my own awards system, placed all for the files in the proper folder structure in userdata, and the awards do not show up.when I put the files in “normal” folder structure they show up. Images are the same.

**Comment by Windchild292** [comment]
@rroby1 
If you know of any other issues, please let me know. I'm planning on implementing this one in the near future

**Comment by Kailan7401** [comment]
Here's a list of things that I manually update each version for reference. I'm not sure which things I can put into userdata and which things aren't implemented yet

![image](https://user-images.githubusercontent.com/32316785/74579639-5fb1a380-4fdf-11ea-84b8-6ec032789471.png)

**Comment by rroby1** [comment]
Not sure if this should be included here or as a separate issue. The unitQuicksOverride.xml file resides in the mmconfig folder. moving this to userdata/mmconfig appears to not work. being able to place this file in the userdata folder would also allow this file to move over to new instances easily.

**Comment by Windchild292** [comment]
Here is great

**Comment by Windchild292** [comment]
Forgot to say, you can assign this to me.

**Comment by Windchild292** [comment]
Missing folders mentioned in #854
data/boards
data/images/force
data/images/portraits
data/rat
data/universe/awards
data/images/awards

**Comment by Windchild292** [comment]
Merging everything into https://github.com/MegaMek/megamek/issues/1050

**Comment by Windchild292** [comment]
Just to clarify my wording, this was closed for duplicating https://github.com/MegaMek/megamek/issues/1050
