### ISSUE TITLE
Can't Change Capital Missile Ammo Types for Space Units

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/mekhq#148]
The biggie here is that I can't reload my AR10/Killer Whale launchers with the Santa Annas I have in stock. I was also under the impression that the AR10 was supposed to support a configurable loadout of Barracuda, White Shark or Killer Whale missiles. I am aware that this is more complex than for most weapons since each missile type weighs a different amount. 

I tested fighters and dropships mounting standard weapons, including MMLs and ATMs, and ammo swaps for those seem to be working as expected.

The attached campaign file has the correct administrators and such set up so you can add units and ammo. Add a Texas battleship or an Overlord A3 dropship to work with AR10s. 

[G3ck0 4rmy30721203.zip](https://github.com/MegaMek/mekhq/files/452018/G3ck0.4rmy30721203.zip)

**Comment by Dylan-M** [comment]
I'm making this Post-Stable, since it will likely be addressed by the Repair/Refit refactoring that @Akjosch is doing.

**Comment by neoancient** [comment]
Weapon bay ammo reloading was implemented with the recent dropship construction feature.
