### ISSUE TITLE
Customize Hangar and Repair Tab Colors

### ISSUE THREAD

**Issue by sixlettervariables** [MegaMek/mekhq#1480]
Now that #1385 is implemented, certain screens are not ideal under dark themes. Much like MegaMekLab allows customizing its colors for certain indications, we should allow the user to choose their own color scheme for the Hangar and Repair Tabs.

> The following is an example of every colour I've seen on this tab.
![image](https://user-images.githubusercontent.com/39067288/73896100-d74d3900-484f-11ea-9257-9ce0ebbd7976.png)
>
> [HangarColours.zip](https://github.com/MegaMek/mekhq/files/4162704/HangarColours.zip)
>
> _Originally posted by @Windchild292 in https://github.com/MegaMek/mekhq/issues/1376#issuecomment-582684004_

**Comment by Windchild292** [comment]
I've implemented this in MekHQ Options.
