### ISSUE TITLE
Unable to assign mech to force in TO&E 0.47.4 

### ISSUE THREAD

**Issue by rroby1** [MegaMek/mekhq#1481]
### Environment
MekHQ 0.47.4
Windows 10
JAVA 1.8.0_241

### Description
After upgrading a Marauder via MML within MHQ and assigning both a tech and pilot I was unable to add the Mech to a force in the TO&E. The mech did not even show. It’s in the hanger and is undamaged. 

I did us the GM tools to complete the upgrade. 

Further investigation: 
When I originally mothballed the unit it had been assigned to force. This force id was carried over into the mothballed state. When the unit was activated it was "reassigned" to the original force with no crew. Due to the unit already being assigned to a force it could not be "reassigned" which is by design. 

This is less of a bug and more of an enhancement request that if a unit is mothballed when assigned to a force that original force id be stripped from the unit.

**Comment by Windchild292** [comment]
Question, does the mech have a pilot?

**Comment by rroby1** [comment]
Yes. After completing the upgrade I assigned both a pilot and tech.

**Comment by Windchild292** [comment]
Ah, this is working as intended. We save the information about the unit and try to restore it after it has been loaded. I'll add an option to disable the mothball information save.
