### ISSUE TITLE
Hire Full Complement does no record recruitment for tracking time in service

### ISSUE THREAD

**Issue by rroby1** [MegaMek/mekhq#1482]
### Environment
MMHQ 0.46.1 & 0.47.4
Windows 10
JAVA 1.8.0_241

### Description
When in the hanger when you right click on a unit and select "hire full complement" the new personnel do not get a <recruitment> tag in the campaign XML file with the track time in service selected. Their recruit date does shows in the personal log. 

Hiring personnel in all other ways appears to work normally.

**Comment by Windchild292** [comment]
Assign this to me, I'll fix it as part of my personnel changes
