### ISSUE TITLE
New Campaign, Portrait Generation not turning off MechWarrior

### ISSUE THREAD

**Issue by FastJack-MD** [MegaMek/mekhq#1484]
When going into the Campaign Settings, I unchecked all the Roles for Portrait generation, so I can choose when to add a portrait or not. But it was not saving when I was saving the campaign file, and every time I opened it back up, MechWarrior was still checked off.

I checked the campaign file, and the tag for Portrait generation was showing below:

`<usePortraitForType>[Z@e35783b,</usePortraitForType>`

I was able to manually change it to the true/false line but when I save the campaign file again, it the overwrites it:

`<usePortraitForType>[Z@1e31d527,</usePortraitForType>`

**Comment by neoancient** [comment]
Duplicate of #1476
