### ISSUE TITLE
Export Personnel to CSV does not work 0.47.4

### ISSUE THREAD

**Issue by rroby1** [MegaMek/mekhq#1486]
### Environment
MHQ 0.47.4
Windows 10
JAVA 1.8.0_241

### Description
Export personnel to CSV does not work. The Save File dialog box comes up. You're able to choose the folder to save the file. When you click on Save the dialog box closes and a blank information window opens. No file is generated.

**Comment by Windchild292** [comment]
Assign this to me, I'll fix it as part of the personnel changes.

**Comment by Windchild292** [comment]
Fixed this and unit export to csv in my current branch.
