### ISSUE TITLE
0.47.4 Portrait Generation/Random Origin Search Radius values will not save

### ISSUE THREAD

**Issue by servo01** [MegaMek/mekhq#1488]
Both values reset to the default settings upon reboot.

Have attempted to use different Campaign Options Preset files, and tested an unmodified fresh install - Issue remains 

To recreate: Open Campaign Options, change values for either settings and save. Settings revert to defaults upon reboot.

**Comment by Windchild292** [comment]
Portrait generation is a copy of #1476, i'll take a look at the other part shortly

**Comment by Windchild292** [comment]
Can confirm the other part, and have fixed it. It is saving properly, just a typo in looking for it when reading the file.
