### ISSUE TITLE
RFE: Solely Rank-based Salaries

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/mekhq#149]
I dont know what the formula is in HQ to calculate the salary but, I try to do it like the real world military setting every base salary to 1000 and then changing the multiplier for each rank to increase their pay.

![example](https://cloud.githubusercontent.com/assets/16950832/18228015/dbadc684-71fe-11e6-8bf5-58a1e9ba5e3d.png)
![github](https://cloud.githubusercontent.com/assets/16950832/18228016/e0a79e58-71fe-11e6-8c90-73414d1b1567.png)

I am not allowed to do that in HQ.  If a person has two roles then it multiplies the salaries I'm guessing.

Could we have just a check box option "Base salaries off rank" which would set all base salaries to 1000 and only go off the rank pay multiplier regardless of if they have one or two roles?

**Comment by BLOODWOLF333** [comment]
@pheonixstorm

**Comment by IllianiCBT** [comment]
I'm going to get this resolved shortly. What I plan to do is add an option that disables salary increases from secondary roles. This way you can achieve the desired use-case, but in a way that is more universally useful.
