### ISSUE TITLE
Medical Report will not display for personnel with active injury 0.47.4

### ISSUE THREAD

**Issue by servo01** [MegaMek/mekhq#1492]
Medical Report will not open for personnel who have active injury 
Report will open/display successfully once injury is resolved

To recreate issue:
- Turn on Use Advanced Medical Rules under Campaign Option
- GM edit injury for personnel
- Attempt to open Medical Report for icon beneath Character Portrait

**Comment by Windchild292** [comment]
I've also found this bug while testing changes in that area, and am currently working to fix it. You can assign this to me.
