### ISSUE TITLE
Determining a person's rank system.

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/mekhq#150]
HQ goes off of whatever the primary role would use as the rank system for a person.  But, if I want a person to have the primary role of admin/xyz so that they can get the xp for the work of the previous "x" week(s) and they are a vessel pilot and should be using the navy rank system HQ will change it to the 'other" rank system since admin is a misc skill.

![github0](https://cloud.githubusercontent.com/assets/16950832/18228052/e57530b6-71ff-11e6-8b4a-15ab36206886.png)

My idea is to have it go off of the MW/ASF/Naval/Vee/Infantry/Tech ranks whether that skill is the primary or secondary role when the other role is designated as a misc position.  If a person's roles are mechwarrior and tech then it would go off the primary role rank system in such cases.

**Comment by BLOODWOLF333** [comment]
@pheonixstorm

**Comment by purpledragon2** [comment]
Actually, I think the rank system would be better if it were based on service arm; e.g. Army, Navy, Air Force, Marines, Police, Other...

**Comment by Dylan-M** [comment]
@purpledragon2 This isn't the US Armed Forces.

**Comment by purpledragon2** [comment]
@Dylan-M  I understand this is not the US armed forces.  I was just commenting to what I believed would make it better.

**Comment by Dylan-M** [comment]
But BattleTech doesn't have service arms like those ;)

Not to mention there are no rules for splitting them this way. MekHQ is supposed to follow the official rules, where such rules exist. We only "make things up" for when there are no rules to cover it. In those cases we use our best judgement to fill in the gaps. Sadly, rules for this exist.

Feel free to start designing an alternative ruleset. Once I add plugin capability to MHQ, you can easily write, or have someone else write, a plugin based on your ruleset.

**Comment by BLOODWOLF333** [comment]
So if I have an admin/logistics / vessel pilot who is an officer so primary role should be admin in my mind.
My vessel crewmembers use the Navy ranks.
My admin column is blank so its using the mechwarrior rank system by default which is USMC.
I have to to have this officers primary role as admin so he will get the xp every X weeks.
He only sees combat when I enter a new planet and other times does nothing so is only way he can get xp.
But primary role of admin forces my mechwarrior rank system on this navy personnel.

So, Im asking for either still allow the xp every X weeks when a person's primary OR secondary role is admin.  Or somehow make it where admin/* is a lower priority than the other rank systems so that if this officer's secondary profession is /vessel pilot it uses my Navy rank system instead of the administrators rank system which is his primary.  Because admin = priority low and all others priority high.

**Comment by Windchild292** [comment]
Currently MekHQ's releases have 18 hardcoded systems (I added the Aurigan Coalition in... January, I think), with the next having 19. I've been opening multiple rank RFEs based on previous issues and comments from other players as part of setting up a project to modernize ranks over the past few hours.

Further, this issue is, as per the complete discussion, subsumed by #2200, #2201, #2202, #2204, #2205, #2206.
