### ISSUE TITLE
Problems of Graphic view of the priority unit on the Personnel tab if you assign the person as both pilot and tech.

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/mekhq#1505]
### Environment
Ver 0.47.4

### Description
Well, I have checked many times, but I am confused why it may changed.

On the Personnel tab, and if you change the view to the Graphic, some person's Unit Assignment section is different with General view, if the person is both a pilot of a unit and also a tech of the different unit. In General view, it always shows the unit it pilots on the Unit Assignment section. But, in Graphic view some personnel shows the unit the person works as the tech on the Unit Assingment section.

I don't know what makes it to change the priority, but I guess that it matters for the weight of the unit - it seems that if you put the person as the tech of the heavier unit and also assign the same person as the pilot of the lighter unit, the Graphic view shows the heavier unit as the the person's basic unit.

**Comment by Windchild292** [comment]
This is a bug, fixing now.
