### ISSUE TITLE
Hanger tab's status says that units are considered as damaged when the pilot have the hits

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/mekhq#1508]
### Environment
Ver 0.47.4

### Description
As title says. If you have a fully repaired unit, but its pilot is damaged(NOT counts the commander of the Command Console, though), the unit's status says that it is damaged(light/moderate/heavy depend on the damage on the pilot) even if the unit is fully repaired. Not only the Battle Armor, but the other units include Battlemechs and Aerospace Fighter are also suffers the same problem.

Also, for Combat Vehicles, if you have the damaged personnel among the vehicle crew, the most undamaged crew is considered as the main pilot of the vehicle, ignores the rank.

**Comment by Windchild292** [comment]
The first bit is a side effect of #1376, the second is a new bug for me. I'll take a look at fixing part 2.
