### ISSUE TITLE
Cannot change/randomize Portrait on the person with hits.

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/mekhq#1511]
### Environment
Ver 0.47.4

### Description
As title says. I have seen many case that the person with at least one hit or more are not able to change the portrait or randomize at all.

**Comment by Windchild292** [comment]
I'm pretty sure this is just #1476, because I a) can't recreate this without first causing that error, and b) have gone through the code for this and found nothing to support this happening otherwise.

**Comment by Windchild292** [comment]
Unless we get more information about this, we can close it.

**Comment by binaryspica** [comment]
> Unless we get more information about this, we can close it.

Thanks.

**Comment by Windchild292** [comment]
My pleasure
