### ISSUE TITLE
AtB enemy bot deploys infantry forces

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#152]
Princess handles infantry better now that she used to, and AtB can already deploy most tanks, mechs, and VTOLs.

What would it take to get AtB deploying infantry in most battles? Possibly using a second bot similar to scenarios that use civilians to keep performance hits minimal.

**Comment by pheonixstorm** [comment]
Does the AtB rules show infantry as being used? If not that would be the first item to change.

**Comment by VampireSeraphin** [comment]
Definitely rules for friendly infantry doing things outside of MM. I'm not sure about enemy infantry. There aren't many RATs for them.

**Comment by scJazz2** [comment]
Unless something drastic has changed... giving Princess VTOLs is a bad idea. Likewise she doesn't have a handle on things like Dig-In, Field Gun movement, going up and down in Buildings. Again unless something has changed. Willing to consider this idea if testing shows Princess is more educated.

**Comment by mkerensky** [comment]
I've got some infantry files and infantry RATs for all the major IS factions, if you're interested. They may help with this project.

**Comment by HammerGS** [comment]
@mkerensky I was just thinking last week we could use RATs for infantry.  What I'd like to have is RATs that fit as an infantry category under the existing RATs.

Can you open a separate ticket under MegaMek tracker and zip them up their.  I'll have a look and see whats the best way to add them.

**Comment by VampireSeraphin** [comment]
I've done some tinkering, and test games, with modified XOTL vee rats that contain infantry. AtB generates and runs those games just fine. I've quite enjoyed them actually. As long as doubled vees is in effect, the number of tanks stay about correct.

It would be easier if it had a similar option to "pad spare BV with infantry" though.

So far, the major stumbling block for me in my tinkering has been finding sources for infantry distribution by type, so far I've only found AFFC (40% foot, 40% Mech, 20% Jump).

I also don't know how to add a RAT to AtB. I remember it requiring a custom universe file in the past when Neo's RATS were separate. That means I can only use modified existing RATS if I want AtB to see them properly.

**Comment by scJazz2** [comment]
To add a RAT
The RAT must be in the rat folder in data and an entry must be made in...

/data/universe/ratinfo.xml

**Comment by scJazz2** [comment]
@mkerensky I certainly would like to see those RATs and Infantry Files. Can you post them?

**Comment by mkerensky** [comment]
It was requested that I open a separate ticket for the RATs and BLKs.  I did so here:  https://github.com/MegaMek/mekhq/issues/154   3 weeks ago, failing to notice that it was supposed to be under the MegaMek tracker rather than HQ - oops.  Can you guys move that ticket easily, or should I just create it again?

**Comment by HammerGS** [comment]
I'm aware of where they are but haven't had time to review or integrate them.

**Comment by NickAragua** [comment]
Well, it took over a year, but now you'll occasionally see the bot deploy some infantry.
