### ISSUE TITLE
Hire Full Complement for JumpShips & DropShips

### ISSUE THREAD

**Issue by rroby1** [MegaMek/mekhq#1525]
### Environment
MHQ 0.47.4 (though it does also appear in 0.461)
Java version 1.8.0_241
Platform Windows 10 10.0 (x86)

### Description
Using Hire Full Complement or GM adding full complement. As an example the Scout Jumpship has a crew of 4 officers, 17 enlisted, and 5 bay personnel listed. Using hire full complement only hires 11 (2 pilots, 1 navigator, and 8 crew).

This only appears to be an issue with drop ships and jump ships. Warships appears to work OK, but not totally sure as I have to manually count the hired personnel. Haven't tried stations.

**Comment by neoancient** [comment]
Right now it only hires the minimum crew as defined by the construction rules.

**Comment by mkerensky** [comment]
Your bay personnel don't count towards the JumpShip's total.  That number is the (maximum) unit crew + 1 technician (ie 4+1 for a light vehicle bay due to the maximum 4 crew for a 50 ton vee), and they're considered part of a transport bay by the rules. 

I have plans to do some work with extra crewmembers to fill the space between minimum construction values and installed crew quarters. I should get to it sometime this year.

**Comment by rroby1** [comment]
The "frustrating" part is that its hire "full" complement. One would expect this to actually do what it says and hire the full complement. I suppose a "quick fix" would be just change from "full" to "minimum" to reflect better what is really happening. 

So ignoring the bay personnel I would expect to hire 21 (4 officers & 17 enlisted) when I click on hire full complement. Meanwhile if it says "hire minimum complement" I wouldn't expect to hire 21 and the 11 makes sense. 

Good to know on the bay personnel. Wasn't sure about how that worked, but the fact that the software is only hiring the minimum crew is where the "problem" is.

**Comment by neoancient** [comment]
I'm not saying it should be that way. I'm explaining where the number comes from.

**Comment by rroby1** [comment]
@neoancient 
That’s exactly how I took it.

**Comment by Windchild292** [comment]
I'm viewing this as mostly an enhancement, but it is somewhat of a bug based on the specific wording of the tool tip.
