### ISSUE TITLE
Enhancement Request - Crew Summary 

### ISSUE THREAD

**Issue by rroby1** [MegaMek/mekhq#1526]
Related to #1525 & #1395 

For those units which have larger crew complements it would be nice to be able to see a crew summary showing the required crew numbers by position (officer / enlisted and navigator / gunner, etc). as well as the number of currently assigned personnel in those categories. 

This would make it much easier for the user to hire or reassign individuals for these units versus having to use hire full complement.

**Comment by Windchild292** [comment]
Subsumed by #2035
