### ISSUE TITLE
0.47.5-SNAPSHOT: Begin Refit Should be Disabled For Negative Unallocated Armour Points

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/mekhq#1529]
![image](https://user-images.githubusercontent.com/39067288/75485832-69d98780-5979-11ea-8cab-e2a98521d0a0.png)

I can currently start a refit with negative armour points in MekHQ at Tech Level Advanced.

**Comment by purpledragon2** [comment]
47.5 is out?  I'm not seeing the download.

**Comment by HammerGS** [comment]
This a bug from something being run by Contributor. Basically a bug caught in development.

**Comment by Windchild292** [comment]
Sorry for the confusion @purpledragon2, this was something I noticed while testing some of the code I was working on. As Hammer said, a bug caught during development.
