### ISSUE TITLE
Request: Some improvements for marriage

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/mekhq#1534]
### Environment
Ver 0.47.4

### Description

It would be too late make a suggestion, for there is a good mega-update. 

Well, is it possible to make the difference by marriage for the change of procreation? It is easy to expect that someone with a partner will have much better chance to have a child, rather than any random friend of your force. 

Also, while it is possible to have a child without marry to someone, can't we nominate the father(or in some case, an another mother...) of the child with the command?

And... it would be better if we can only choose the personnel that is able to participate procreation(for the force with too much personnel), but it would be complicated a bit. Also it is not that important issue, because the rate of random procreation is too low.

**Comment by Windchild292** [comment]
The chance of procreation is now a setting divided between the two types, but the chance was always rarer for people without a spouse (a tenth of the married chance).

The second is the Family Editing GUI.

The last one is... on my TODO list, I just missed it when finalizing this wave. I would consider it an issue that should be fixed as part of #1533.

**Comment by binaryspica** [comment]
Oh, it was lucky that most of these are already on your list.

**Comment by Windchild292** [comment]
Technically they all are, the second one is just something I'm not likely to do.

**Comment by Windchild292** [comment]
Edit: Thank you for the reminder on number 3 though, I'm going to fix and test the radial issues for you and then implement number 3.

**Comment by binaryspica** [comment]
I have to say thank you, actually.

**Comment by Windchild292** [comment]
I've opened up #1569 for part 2, have part 1 coded as part of #1533, while part 3 will be implemented in a PR that is just waiting for #1533 to be merged to open. This can be closed.

**Comment by binaryspica** [comment]
Thanks, but isn't 1569 just make the tree, that is not editable?
