### ISSUE TITLE
Conventional Infantry RATs and BLKs

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/mekhq#154]
[Conventional Infantry.zip](https://github.com/MegaMek/mekhq/files/459858/Conventional.Infantry.zip)

The ZIP archive contains my faction-specific infantry RATs. I'm using a mix of 3085 platoons, field guns and faction specific platoons I created (attached). In the case of the faction specific units, they all have options set for the latest model of the infantry armor kit and small arms/support weapons listed for that faction in Tech Manual and/or appropriate handbooks. 

In the case of 3085 platoons, I allowed everyone access to the Corporate units. I had not yet finished reading TRO3085 when I wrote these, so there may be a few platoons that are mis-assigned in the tables.

**Comment by scJazz2** [comment]
haha... which is why I couldn't find it in MM < my bad

**Comment by sixlettervariables** [comment]
@mkerensky anything to do with this?

**Comment by mkerensky** [comment]
I don't think so.  I've switched over to using the ForceGenerator for this, and I've customized my own tables to suit my needs.
