### ISSUE TITLE
Salary bug involving comma separator

### ISSUE THREAD

**Issue by TheodoreKuritasGhost** [MegaMek/mekhq#1540]
I've been affected since version 0.46 with this problem: somewhere around that time the default personnel salaries started using a comma separator for figures above one thousand (a MechWarrior's base salary of fifteen hundred C-bills is 1,500, whereas in earlier versions it was 1500 without a separator). This causes issues at least using Windows 10 when your computer locale is set to a place that doesn't separate thousands with commas. In my case, MekHQ reads 1,500 as one and a half (1.5) since here the comma is used as a decimal point, and as a result a regular MechWarrior would only get a salary of 2 C-bills per month rounded up. Is it possible to revert the default salaries to the format without a separator?

**Comment by Windchild292** [comment]
I'll take a look at this.

**Comment by Windchild292** [comment]
I am unable to recreate this after changing my locale (in both places, too) to Spain, and I'm not seeing a possible cause in the saved files. The comma difference is only display-side from what I can tell.

The option is saved as:
`		<salaryTypeBase>0 CSB,1500 CSB,1500 CSB,900 CSB,900 CSB,900 CSB,900 CSB,960 CSB,750 CSB,960 CSB,900 CSB,1000 CSB,1000 CSB,1000 CSB,1000 CSB,800 CSB,800 CSB,800 CSB,800 CSB,400 CSB,1500 CSB,400 CSB,500 CSB,500 CSB,500 CSB,500 CSB</salaryTypeBase>`

And a customized salary is saved as:
`			<salary>2738 CSB</salary>
`

Does this happen with new save files, pre-0.46 save files, or both?

**Comment by TheodoreKuritasGhost** [comment]
It happens whenever I start a new campaign. When selecting and viewing Campaign Settings In the launcher, the values look like the upper image in the attached pic: all look correct, thousands separated by commas. Yet when I actually start the campaign and am in the MekHQ base screen, checking the Campaign Settings looks like the lower image in the pic. Somewhere between the launcher and the actual MekHQ, the program interprets the "1,500" as one and a half, and rounds it to 2 for every troop type with a base salary above a thousand C-bills. If I type the correct values without a comma into the Campaign Settings tab (ie. just "1500" for the MWs, Aerojocks, etc.) MekHQ uses the correct values. I first noticed this behaviour with 0.46, I'm currently using 0.47.4; in the earlier versions (I looked into 0.3.12, 0.3.27 and 0.43.10-RC4) the salaries work correctly and these versions don't use commas in the Personnel/Salaries tab. I did check the various .xmls in the 0.47.4 directory and they indeed are in the "1500 CSB" format. I'm using Windows 10, English language, with Finland as the locale.

![mekhqsalarybug](https://user-images.githubusercontent.com/61749224/75809013-b1ed1580-5d90-11ea-93e1-19475f44ca09.jpg)

**Comment by Windchild292** [comment]
I'll switch to Finland as my locale, which form of English are you using?

**Comment by TheodoreKuritasGhost** [comment]
Windows 10 Display Language is "English (United States)", Country or region "Finland", Regional format "Finnish (Finland)". I might add that in the pre-0.46 versions of MekHQ everything else was in English but I still got the date in the main MekHQ window in Finnish with these settings.

**Comment by Windchild292** [comment]
I can confirm this is a bug in both 0.46.1 and 0.47.4, but cannot recreate it on my develop branch. However, given the lack of a fix I suspect that might be because of an issue in how I am building this.

**Comment by Windchild292** [comment]
I've got what I believe to be a fix coded, I swapped to using the spinners like the field above it.

However, I am unable to verify that this is the proper fix because I cannot recreate the issue when building through gradle.

**Comment by Windchild292** [comment]
@TheodoreKuritasGhost 
Please let me know if this continues in the next release if this is still happening and I'll take another look at the problem.
