### ISSUE TITLE
Suggested Enhancement(s)

### ISSUE THREAD

**Issue by MageOhki** [MegaMek/mekhq#1542]
Current versions of MekHQ

1: Separate out ground support vehicles from ground combat vehicles in hanger.  Currently all are under tanks.
2: I _don't_ know if this is possible (or practical), but the following changes in personnel areas for the tab may work better:
A: Separate out VTOL personnel from Vehicle crews.
B: once assigned to a combat vee or a support vee, have them show up on seperate blocks?
C: Same as above for Small Craft, Dropships and jumpships?

3: When showing techs for refits, would it be possible to sort them by the skill roll (ie, 4+, 5+), best roll to worst roll, then a secondary sort by time open?

4: Mass Training
A: Add special abilities 
B: set it so you can select those with the skill you're targeting, or without it at all.

5: Training/Spending XP:
special abilities: While Clan tech knowledge is buyable, Tech Speicalists (Internal, Armor, Weapons) are not, can that be added?

6: Weigh Secondary skills more suited for the role the hiree has.
(Example: I get a Mechwarrior with Tech: Aero, or a Aerospace pilot with Tech: Battle Armor, *really*?)

7: GM Tools multi select on mothball and activate items off right click menu.  At this time, you have to select one at a time...

**Comment by Windchild292** [comment]
Each one of these should be their own issue, and I'm pretty sure you've already opened an issue for 7. 6 is a can of worms that I've started initial planning for (zero promises), and I think a four tiered search for 3 is best (Tech type, skill, rank, time open)

**Comment by Windchild292** [comment]
I've actually run into issues relating to number 7 for my testing, so I'll fix that one.

**Comment by Windchild292** [comment]
Number 3 will be implemented in #1544, just realised it now when reviewing the two big groupings of RFEs.

**Comment by Windchild292** [comment]
1: #1571
2: #1572
3: Implemented in #1544
4: #1573 and #1574
5: Clan Tech Knowledge is purchasable? Also, do we have ideas on how much they should cost? 
6: #1576
7: Implemented in #1544 

Need replies for the fifth suggestion, but once that is done this story can be closed.
