### ISSUE TITLE
RFE: Astech Skill Addition

### ISSUE THREAD

**Issue by jschmetzer** [MegaMek/mekhq#1543]
### Environment
47.4 Mac

### Description
Request Astech Skill be made more accessible; not currently available as an XP skill purchase. 
MVP: Astech skill added to right-click XP purchase menu as an option for all personnel types. 
Bonus: Allow Mass Training to add Astech from scratch
Bonus example: I hire an infantry platoon. I want them to be able to serve as astechs. Right now I would need to GM mode each soldier, individually, and edit to add the skill. Be great to be able to select all by type (ie Soldier) and add Astech skill at minimum value.

**Comment by NickAragua** [comment]
You can actually accomplish this today. Go to campaign options -> skills tab, and set the required XP values to something other than -1.

**Comment by jschmetzer** [comment]
Doh. My bad. :)

**Comment by NickAragua** [comment]
Didn't actually occur to me, either until I researched it a little just now.
