### ISSUE TITLE
[Request] Advance Day from Within Personnel Market+choose default sort order.

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#155]
Simple one this time. Can we get a button to advance the day from within the personnel market. Its a pain to close and reopen it dozens of times for the recruitment methods that refresh daily.

Likewise, can we make it so MekHq remembers what sort column you specified last time so you don't have to resort every time you open the personnel market.

**Comment by Windchild292** [comment]
Actually, #1546 was the second part that needed to be implemented. This can be closed as both parts have been implemented in MekHQ

**Comment by HammerGS** [comment]
Implemented
