### ISSUE TITLE
Use Ammo by Type Appears Nonfunctional

### ISSUE THREAD

**Issue by jschmetzer** [MegaMek/mekhq#1558]
47.4 
Java version 1.8.0_221
Platform Mac OS X 10.15.3 (x86_64)

campaign file attached, when 'use ammo by type' is checked an SRM 6 is not reloaded from multiple SRM 2s. 

[Test30670103.cpnx.zip](https://github.com/MegaMek/mekhq/files/4333676/Test30670103.cpnx.zip)

**Comment by Windchild292** [comment]
I can confirm this is an issue, and dates back to 0.46 at the latest

**Comment by Windchild292** [comment]
Subsumed by #1665.
