### ISSUE TITLE
Advancing Days

### ISSUE THREAD

**Issue by 69chrisd69123** [MegaMek/mekhq#1566]
### Environment
MekHQ 0.47.4
Windows
Java unknown checked mekhqlog text

### Description
Trying to advance multiple days and only get a bar in the middle of the screen that says advancing days but nothing happens. see screenshot

### Files

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/4350515/mekhqlog.txt)

not letting me load the campaign cpnx file says it is unsupported

![advancing days](https://user-images.githubusercontent.com/42626937/76991546-05ba3b80-6907-11ea-915d-a8db6f3a61d2.png)

**Comment by Windchild292** [comment]
Try expanding the box

**Comment by 69chrisd69123** [comment]
Bloody hell that works thank you

Sent via the Samsung Galaxy Note10+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Windchild292** [comment]
Welcome
