### ISSUE TITLE
[AtB] Can't pass retirement screen

### ISSUE THREAD

**Issue by toastmayhem** [MegaMek/mekhq#157]
When opening the retirement/defection window I get a graphical error where I am unable to see anything unless I mouse over it first. Also am unable to advance a day despite having the funds to pay retiring personnel. Unable to GM past either.

Am unable to upload zip file for some reason so have attached dropbox link to it. Sorry for the trouble.

https://www.dropbox.com/s/ccsu0h1jpz2gqt6/Retirement.zip?dl=0

**Comment by neoancient** [comment]
I am unable to reproduce the problem. The graphics are normal when I try your campaign and I am able to advance without issue. We have seen odd graphics phenomena that seem to be connected to running MekHQ with Java 8 on Windows when there are multiple graphics adapters. Does this describe your system?

**Comment by neoancient** [comment]
Closing due to inability to reproduce and lack of response from OP.
