### ISSUE TITLE
Scenario Resolution: ejected+fled pilots lose hits

### ISSUE THREAD

**Issue by ObviousTech** [MegaMek/mekhq#158]
Have a mechwarrior take some hits during the game.
Eject.  (With ejected mechwarriors auto flee.)
During resolution, the # of hits slider will be 0 for this mechwarrior, despite it having taken some hits during the scenario.

Attached saves: campaign, before ejection, at end of round with ejection, end of game.
Affected unit in save: Lancelot - Lieutenant SG Eddie Marabian

[eject to heal.zip](https://github.com/MegaMek/mekhq/files/465188/eject.to.heal.zip)

**Comment by Dylan-M** [comment]
This may happen regardless of AtB, I haven't looked into it.

**Comment by mkerensky** [comment]
I've had this happen without using ATB, and without the "ejected pilots flee" option on - I think it may be a problem with hit tracking for ejected pilots in general.
