### ISSUE TITLE
Request: Override Introduction/Extinction/Prototype dates on Parts

### ISSUE THREAD

**Issue by FourMansGamesAdmin** [MegaMek/mekhq#1586]
Make it so that a GM can customize the manufacturing dates (Prototype, Production, Common, and Extinction) on parts so that they show up in the parts list and Meklab on dates/eras other than canon.

Ex: Light PPC- canon dates: 3067 common; no other dates listed.
Mod: Light PPC- custom dates: 3000 prototype, 3025 production, 3050 common.

**Comment by neoancient** [comment]
This is not feasible.

**Comment by FourMansGamesAdmin** [comment]
Your saying that you can't add a segment of override code that uses a player input to overwrite the default code?

**Comment by HammerGS** [comment]
This is a massive job. Every piece of equipment is hard coded into Megamek. It’s not like a external file that can be swapped.

**Comment by FourMansGamesAdmin** [comment]
I understand this.  I have looked at the code a little.  It was when I was not as familiar with coding, since then I have had some experience.  Even if its hard coded, we are talking about a variable set by the appropriate script.  Why can't you just add an additional script that locates all of these weapon scripts either through a find function or a hard reference and then update the variable based on GM inputs on a new option screen or tab in the campaign options.

MekHq already has the ability to locate and display these variable in the Purchase Parts menu and MekLab Equipment tab.  So the ability to locate should be somewhat easy.  After that, its just a matter of updating the variables based on the input entered into the input field, unless they are private variables.  Even then a public function either in the parent script or added to each weapon script could be used to pass the variable updates into the script so it can local update the variables.  

Now mind you, I say all of this based on my experience programing in C# and not Java, so I may be missing a key piece of information.  However, it seems that while it would be monotonous, it would not be unfeasible or all that difficult.

**Comment by HammerGS** [comment]
Your welcome to submit a pull request.

**Comment by FourMansGamesAdmin** [comment]
I would if I had any experience in Java.  As I don't, all I can do at this moment is request it and discuss the whys.

**Comment by neoancient** [comment]
Though it is not enforced through language features, equipment data needs to be treated as immutable to ensure consistency between the client and the server. Though it is possible to change the values, it has the potential to break the current design.

**Comment by FourMansGamesAdmin** [comment]
Ok.  Thank you for that explanation.  This is something that I can understand.  

Related but side question, the core values need to remain static but could the purchase parts and Meklab be made to see a side value instead of the core value without breaking the current design?  (Ex.  Introduction and IntroductionB) 

Again, thank you.
