### ISSUE TITLE
RFE: Mass refits with the same kit

### ISSUE THREAD

**Issue by ajac09** [MegaMek/mekhq#1587]
Request mass ability to provide kits for mechs vehicles and other units.

**Comment by HammerGS** [comment]
We'll need a lot more details on this.

**Comment by ajac09** [comment]
Like what?  Just want to be able to select more then one unit at time to give refit kits....like 100 awesomes of one type I should be able to give them all the same refit kit or something.

**Comment by Windchild292** [comment]
Ah, you mean mass refits to the same kit?

For example, if I have 11 Awesome AWS-8Q, I can refit them all to AWS-8R using the same dialog?

**Comment by ajac09** [comment]
Yes sir.
