### ISSUE TITLE
Crashing on loading save // MissingMekGyro.java(162)

### ISSUE THREAD

**Issue by ThatGuy435** [MegaMek/mekhq#16]
I'm running the latest MqkHQ (0.3.24-git from the Releases page) and am getting odd behavior and crashes after salvaging post-scenario. After salvaging, the UI stops updating. If I save and reload MekHQ, the GUI crashes but the Java Runtime stays running in the background forever (or at least to ~3hr).

I haven't been able to find anything related to this with the Google, so I'm reporting it here.

Campaign file (renamed cpnx -> txt)
[Riker's Raiders30250909-2-BROKEN.txt](https://github.com/MegaMek/mekhq/files/138565/Riker.s.Raiders30250909-2-BROKEN.txt)

mekhqlog.txt
[mekhqlog-PostEndTask.txt](https://github.com/MegaMek/mekhq/files/138564/mekhqlog-PostEndTask.txt)

**Comment by Kurios** [comment]
I had the same issue. it was fixed in the more recent versions (that just arnt released yet). If you run the current dev code from this repo, it should fix it.

Clone of:
https://github.com/MegaMek/mekhq/issues/15

**Comment by ThatGuy435** [comment]
Ack, of course its in the one place I didn't look - closed tickets. Any idiots guide to compiling from source?

**Comment by Dylan-M** [comment]
In this case, don't bother. Just wait for tomorrow ;)

I started prepping for a release today, and I'll be finishing it tonight/tomorrow.

**Comment by Kurios** [comment]
Familiar with Java? My lazy way is to get a copy of eclipse (its already got a eclipse project definition in it to make life easier... 

http://www.eclipse.org/downloads/packages/eclipse-ide-java-developers/mars1

pull the source code for  this project with git. 

Load the project into eclipse and hit the run button... simple (not really)

If you have some familiarity with java though, It may be useful. That way you can push bug fixes back :)

(If you want, feel free to contact me. skype@kuriomister )

**Comment by ThatGuy435** [comment]
You guys are awesome. I'm a sysadmin, not a programmer, so while I can probably compile it (though it looks like I don't have to - thanks Dylan-M!), I'd be hopeless at actually fixing the code.

**Comment by arlith** [comment]
If you have java and ant and not Eclipse, there's a jar task in MM for building a jar, you could just checkout the repo, then `ant jar` and then `java -jar MegaMek.jar`.  It's possibly easier than getting Eclipse, if you can run ant at the command line easily.

**Comment by ThatGuy435** [comment]
Managed to get it built with ant and java; just had to add ant to the path. Can confirm, able to load the save file I posted with the original report.

**Comment by ThatGuy435** [comment]
Release v0.3.25 seems to completely resolve this, closing the issue.
