### ISSUE TITLE
Cannot scroll through spouses

### ISSUE THREAD

**Issue by FastJack-MD** [MegaMek/mekhq#1612]
Love that you set up the non-cis family options, but when trying to choose a spouse for a character, if you have an amount of PCs that fills out the menu, it doesn't allow you to scroll through the list.

**Comment by Windchild292** [comment]
This is on my list for the near future, just waiting on a related PR before adding it.

**Comment by FastJack-MD** [comment]
Is there a way to work around it before the next release?

**Comment by Windchild292** [comment]
🤔 
Marrying most of your force will work, and the list is smaller than it was before (it formerly included prisoners, and personnel that were dead, missing, or retired). As the list is by age then alphabetically by name, you should be able to marry anyone to the youngest grouping of personnel, then continue that forward. However, I do know that is not the easiest thing to do.

Annoyingly, I added the scrollbar check to the wrong menu, and I apologize about the inconvenience that is going to cause.

Also, this comment led me to discover a very well hidden bug in the potential spouse logic, which I have now fixed.
