### ISSUE TITLE
RFE: Option: Don't Reset Finances Table on New Year

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/mekhq#1614]
This is an option to keep the contents of the Finances table and not having it carryover when the year changes.

This would really be best done when adding a reset button to said table at the same time, as otherwise it will eventually get unusable (#1615)

**Comment by purpledragon2** [comment]
Maybe if it could write the year's finances to hard drive then have the ability to pull it up for view???

**Comment by Windchild292** [comment]
I've not seen a similar one, but this is for keeping the whole thing in the campaign files... probably with a note that the setting is not recommended.
