### ISSUE TITLE
RFE: Time in Service (TIS) and Time in Rank (TIR) should also have an option to display in months, years and combo. TIR should be added, others are using this method to promote personnel.

### ISSUE THREAD

**Issue by PhoenyxCullen** [MegaMek/mekhq#1624]
* Time in Service (TIS) and Time in Rank (TIR) should also have an option to display in months, years and combo.
* TIR should be added, as others are using this method to promote personnel.

**Comment by Windchild292** [comment]
Can you please split this into two things, one for Time in Rank and the other for Time in Rank and Time in Service to have the display option?

**Comment by PhoenyxCullen** [comment]
Sure. Close this one.
