### ISSUE TITLE
Issue when Resolving Scenarios with the Bad Intel modifier

### ISSUE THREAD

**Issue by CrimsonThunderSB** [MegaMek/mekhq#1631]
0.47.5

For some reason, when I resolve a scenario (even when manually doing so without an actual battle), when I have a House or a Liaison unit attached to the unit, every time I have selected the bad intel modifier whether its the air or the ground modifier, the objective always counts as failed, even if its completely unscathed.  This is a bit annoying as this has severely hurt my contract score for the mission I am currently on as much as a -4 contract score penalty...which I really don't need to have happen....if you need the modifier file, please let me know.

![image](https://user-images.githubusercontent.com/47725829/78458353-a5552900-767e-11ea-8a34-4b076e2cc436.png)

![image](https://user-images.githubusercontent.com/47725829/78458378-c6b61500-767e-11ea-928f-e67dbee62f42.png)

**Comment by Windchild292** [comment]
A save file could prove useful.

**Comment by CrimsonThunderSB** [comment]
[Stormbringing Destroyers Bugged.zip](https://github.com/MegaMek/mekhq/files/4432770/Stormbringing.Destroyers.Bugged.zip)
sorry about that...there is the file...though I don't think I saw any errors in the log file...but its a bit annoying, it occurred shortly after changing everything over to the new version,.  This is even occurring when I have the template modifier with enemy artillery activated, if you even try to solve the battle scenario manually with no battle file selected, the attached unit here (being the phoenix hawk, but will occur with any mech), the objective of preserving the attached unit seems to automatically fail, even with no battle damage, and this causes the contract score to decrease by 4.  I am not sure what happened.

**Comment by CrimsonThunderSB** [comment]
@Windchild292 I am also trying to see where its coming from, and it looks like it may be coming from the scenario generator when you try to regenerate forces when creating the scenario...possibly

**Comment by Windchild292** [comment]
I've recreated this, and I think it is related to the scenario editor. I'm going to take a look into fixing this now
