### ISSUE TITLE
47.5 Issue - All random marriages default to same sex 

### ISSUE THREAD

**Issue by servo01** [MegaMek/mekhq#1632]
To recreate with a fresh install, load the last campaign save and enter:

Campaign Options/Personnel/Family Settings

- and adjust chance of random marriage sufficiently high to trigger a random marriage when advancing days. 

Even with same sex spouse disabled and set to 0, all random marriages are still same sex.

**Comment by Windchild292** [comment]
🤦‍♂ 
Yeah, that is a current bug. I accidentally swapped the two in a the comparison. For the time being, the fix is to swap the two values and enable them both, with a zero value if you want to disable random same sex marriage.
