### ISSUE TITLE
Base Salaries Not Displaying Correctly 0.47.5

### ISSUE THREAD

**Issue by rroby1** [MegaMek/mekhq#1635]
### Environment
0.47.5

### Description
Base salaries portion of the personnel tab boxes aren't large enough to show values. 
See below.
I have expanded the dialog box as large as I can, but these fields don't change. 

### Files
![person tab](https://user-images.githubusercontent.com/61069665/78599426-19c6ce00-781f-11ea-8f77-64be97a8c229.png)

**Comment by sixlettervariables** [comment]
As a workaround can you try another theme?

**Comment by rroby1** [comment]
Just checked. All other themes work fine. It's just Nimbus that displays as above.

**Comment by Windchild292** [comment]
Interesting/weird

**Comment by rroby1** [comment]
The Family Options portion is also not displaying correctly under Nimbus. 
![family options](https://user-images.githubusercontent.com/61069665/78668285-6d312e80-78a8-11ea-8ce0-19026d5aeaa5.png)

**Comment by rroby1** [comment]
When I have a little more time I'll take a look at the other screens under Nimbus to see if there are any other problems.

**Comment by Windchild292** [comment]
That would be great, as I could then hit the others at the same time (as I'm betting the issue probably originates in similar places.)

**Comment by rroby1** [comment]
The above are the only places I see an issue with Nimbus in MekHQ.

**Comment by Windchild292** [comment]
The family options were also issues for darkmode, which has been fixed.
