### ISSUE TITLE
[Request] Larger maps when Aeros present

### ISSUE THREAD

**Issue by EMaher81** [MegaMek/mekhq#1637]
In AtB games when Princess is bringing Aeros, suggest automatically increasing map size to allow player a chance to shoot down fighters before they start their attack run. Love the more dangerous (47.5) Princess!

**Comment by binaryspica** [comment]
If it is available, then set the extra-deep deployment by default seems an another option, to give enough chance to check incomming aero and react.

**Comment by ajac09** [comment]
wish their was a way to set up strafing and bombing strikes before they get onto the map.
