### ISSUE TITLE
Incorrect Extra Time multiplier

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/mekhq#164]
Rules state a maximum of 4 times the normal time for repairs. It should not be 8 times at max.

SO pg 182

Broken in commit fe99cd87107124d58c65eb620b85f4323c409eed

**Comment by scJazz2** [comment]
Are you certain about this fix? Cause the 8.0 multiplier is actually 1/8th time for doing repairs faster than the listed time required.

For instance you could use an Elite Tech to blow through armor repairs by telling him to fix faster.

From SO 182
Rush Jobs: Sometimes conditions (or force commanders) require
a quick turnaround on repairs. Rush jobs are more difficult
than standard repairs, and are more likely to break down at the
worst possible moment. Any Technical Team with a Regular or higher Experience Rating
may perform a rush job. To do so, they must voluntarily lower their
eff ective Experience Rating for the duration of the rush job. By
reducing its Experience Rating by one, a Technical Team can make
a repair in half the usual time; a two-rating experience reduction
enables them to make the repair in one-fourth the usual time;
and a three-rating experience reduction enables them to make
the repair in one-eighth the usual time. If necessary, round up in
all cases.

**Comment by pheonixstorm** [comment]
The Rush Job multiplier is correct, this bug is only for Extra Time spent on repairs which is a maximum of 4 times the standard time.

**Comment by Dylan-M** [comment]
Fixed by e6f8396
