### ISSUE TITLE
Cannot Save Mechlab Refit

### ISSUE THREAD

**Issue by ajac09** [MegaMek/mekhq#1649]
Getting issues with unable to save games. Also had some meklab issues inside being unable to save maybe same bug.
[customs.zip](https://github.com/MegaMek/mekhq/files/4461750/customs.zip)
[Heavy Calvary27810224.zip](https://github.com/MegaMek/mekhq/files/4461751/Heavy.Calvary27810224.zip)

**Comment by Windchild292** [comment]
I'll take a look shortly

**Comment by Windchild292** [comment]
I've fixed the save issues, but I'll need more information about the latter MekLab issues (how to replicate it) to proceed.
This is the fixed campaign file.
[Heavy Calvary27810224.zip](https://github.com/MegaMek/mekhq/files/4462055/Heavy.Calvary27810224.zip)

**Comment by ajac09** [comment]
Let me try it again. I tried to remake the enforcer and thats when the bug happened here are the steps:

Opened up campaign
Went to hanger
click one enforcer enf-4r 
right clicked choose customize in meklab
Clicked on equipment 
Hit remove all
clicked on ballistic  weapons
added ac-20
went back to structure 
changed to unoffical tech
changed to xl engine
went back to Equipment
added ac-20 ammo x 2
went to energy weapons
added er large laser
Added medium laser
added .5 tons of armor
hit auto allocate 
changed heat sink to double 
assigned critical tab
removed lowe arm right arm
added ac-20
Heat sinks to both torso ammo one teach each torso
er large to left arm 
medium laser to left arm
Hit begin refit..

this time all worked fine.

**Comment by Windchild292** [comment]
I cannot recreate the issue @ajac09, but it is not likely to be a related to the first issue.

**Comment by Windchild292** [comment]
Closing this as I've been unable to recreate the refit issue after continued testing
