### ISSUE TITLE
GM Mode > Repair Unit does not fix ASF engine damage, and GM Mode >Edit Damage fixes it only temporarily

### ISSUE THREAD

**Issue by crazys1** [MegaMek/mekhq#167]
Version: 0.3.33

Description:

Using "GM Mode > Repair Unit" on an ASF that has engine damage does not fix the engine damage. Also, if you use GM Mode >Edit Damage to fix the engine, the engine gets fixed until you save and load the campaign. However, using a tech to repair the engine does work as it should.

To reproduce:

1. Start a new campaign; the exact settings do not matter. You can also see this bug with an existing campaign, but this procedure uses a new one so that there are the fewest factors involved.
2. Add an ASF of any kind.
3. In the Hangar, select the ASF and do "GM Mode >Edit Damage", add 3 engine hits, and click OK.
4. Do "GM Mode > Repair Unit". The engine damage does not get fixed.
5. Do "GM Mode >Edit Damage", remove the engine hits, and click OK. The engine is now repaired. BUT...
6. Save the campaign.
7. Load the campaign.  Notice that the ASF's engine damage has returned!
8. (Optional) Fix the engine using a tech. The engine will remain fixed even after a reload, as it should.

**Comment by crazys1** [comment]
This bug is probably fixed by the fix that neoancient made for https://github.com/MegaMek/mekhq/issues/146.

**Comment by neoancient** [comment]
It wasn't fixed then, but it was fixed by 4d43127.
