### ISSUE TITLE
Although same sex marriages are ticked off, I got a same sex marriage nonetheless

### ISSUE THREAD

**Issue by plutonick** [MegaMek/mekhq#1674]
I am fine with that, as long as they are both happy together, but perhaps a dev should look into it.

Version: 0.47.5

![image](https://user-images.githubusercontent.com/8420602/79256335-829dee00-7e90-11ea-87c3-50e0b1a3fd08.png)
![image](https://user-images.githubusercontent.com/8420602/79256369-92b5cd80-7e90-11ea-9dc7-774be84f4324.png)
![image](https://user-images.githubusercontent.com/8420602/79256389-9ea18f80-7e90-11ea-8857-895a19afb5ec.png)

**Comment by Windchild292** [comment]
This is a bug that has been resolved in latest develop.
