### ISSUE TITLE
Cant save again 

### ISSUE THREAD

**Issue by ajac09** [MegaMek/mekhq#1678]
cant save again
[mechfiles.zip](https://github.com/MegaMek/mekhq/files/4496677/mechfiles.zip)

**Comment by Kailan7401** [comment]
[Heavy Calvary27811101.zip](https://github.com/MegaMek/mekhq/files/4496695/Heavy.Calvary27811101.zip)

Here you go, see if this helps! I was able to solve the issue permanently by disabling pregnancy, which eventually breaks the save one last time. After it's fixed that time, you shouldn't have any more issues.

**Comment by ajac09** [comment]
oh that is what is causing the issue lol

**Comment by Windchild292** [comment]
Looks like Kailan has fixed the issue, so I'll close the ticket.
