### ISSUE TITLE
RFE: Please add Edge to Experience Tab

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#168]
In Campaign Options > Experience Tab > Skill Costs

Please add an entry for Edge and allow it to be purchased like a skill.

**Comment by VampireSeraphin** [comment]
+1 for this request.

**Comment by purpledragon2** [comment]
+1 for this request.

**Comment by mkerensky** [comment]
+1 more for this. 

Any chance to increase the functionality of edge to allow a reroll of any tracked skill, so it would be useful for, say, admins, techs and doctors to spend points on?

**Comment by scJazz2** [comment]
Topic was discussed last night and the overwhelming consensus was "YES". The skill should work for anyone failing a roll.

**Comment by NickAragua** [comment]
This has been implemented.
