### ISSUE TITLE
Can't save 

### ISSUE THREAD

**Issue by plutonick** [MegaMek/mekhq#1682]
Error message says to provide the log file but since I can't save, I am not sure if the logfile is updated.

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/4497383/mekhqlog.txt)

Latest save.
[Peace Operations30301203.zip](https://github.com/MegaMek/mekhq/files/4497393/Peace.Operations30301203.zip)

### Environment
47.5 - windows

**Comment by Windchild292** [comment]
Can I get the megameklog.txt for that same issue?

**Comment by plutonick** [comment]
[megameklog.txt](https://github.com/MegaMek/mekhq/files/4498676/megameklog.txt)

sure!

**Comment by Windchild292** [comment]
That's the fixed file, with the option that can cause it turned off and any cases fixed.
[Peace Operations30301203.zip](https://github.com/MegaMek/mekhq/files/4499509/Peace.Operations30301203.zip)

**Comment by plutonick** [comment]
thanks for the fix. Was pregnancy causing this?

**Comment by Windchild292** [comment]
It was.
