### ISSUE TITLE
RFE: Log name changes with auto marriages

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/mekhq#1683]
With the new random marriage chances, people seem to be changing their names all the time.  
Since I don't have everyone's last names memorized, I have no idea what their name was before the change.  

Would it be possible when the game automatically changes someone's name with a marriage, to log what the previous name was and what they have changed to?  A simple line on the person's history log would be fine.

**Comment by Windchild292** [comment]
That's a good idea, I'll look into implementations shortly.
