### ISSUE TITLE
Field Gunners (AC20) reload loop/bug

### ISSUE THREAD

**Issue by plutonick** [MegaMek/mekhq#1687]
Mekhq 4.75

Reloading Field Gunners ac20 is creating a loop. The reload is successful but no ammo is used and unit is still in repaid bay. Click reload continues the loop.

![image](https://user-images.githubusercontent.com/8420602/79788528-74007c80-8351-11ea-9ab9-d5602929621f.png)

**Comment by ChaoticInsanity** [comment]
plutonick, do you have an example test campaign that you could upload? As of right now I have not been able to reproduce this bug in v47.5 or the current development snapshot.

**Comment by Windchild292** [comment]
I'll also check with the other reporter of this bug to see if either can provide one @ChaoticInsanity

**Comment by Windchild292** [comment]
The other reporter provided the following save where it is occuring @ChaoticInsanity : 

[ac-20_field_gun_problem.zip](https://github.com/MegaMek/mekhq/files/4596433/ac-20_field_gun_problem.zip)

**Comment by Windchild292** [comment]
Forgot to add the customs:
[customs.zip](https://github.com/MegaMek/mekhq/files/4596440/customs.zip)

**Comment by ChaoticInsanity** [comment]
Hmmm weird on my Mac the campaign showed the reload as out of time and when I advanced to the next day it reloaded normally. I'm going to run the test again on my Parallels Windows VM and see if I get different results.

        MekHQ 0.47.5
        Java vendor Oracle Corporation
        Java version 1.8.0_162
        Platform Mac OS X 10.14.6 (x86_64)

**Comment by ChaoticInsanity** [comment]
I'm getting the same results using Mac or Windows.

	MekHQ 0.47.5
	Java vendor Oracle Corporation
	Java version 1.8.0_251
	Platform Windows 10 10.0 (amd64)

**Comment by sixlettervariables** [comment]
Advancing the day I could perform the task, none of the infantry had time left to work on parts. Works in #2229.
