### ISSUE TITLE
Marriage age preferences unusable on IntelliJ based themes

### ISSUE THREAD

**Issue by ChaoticInsanity** [MegaMek/mekhq#1690]
### Environment
MekHQ 47.5
All operating systems
Java version 1.8.0_162

### Description
The marriage age preferences on the Personnel tab are less than 1 character wide in the Flat Darcula and Flat IntelliJ themes making them unusable. You do not need an active campaign to reproduce this bug.

Theme Flat Darcula
<img width="337" alt="Theme Flat-Darcula" src="https://user-images.githubusercontent.com/54778193/80239216-d3021200-862d-11ea-86f4-96d6b9d59f83.png">

Theme Flat IntelliJ
<img width="294" alt="Theme Flat-IntelliJ" src="https://user-images.githubusercontent.com/54778193/80239232-dc8b7a00-862d-11ea-9ae0-f4871cf9eb9f.png">

Theme Flat Dark
<img width="304" alt="Theme Flat-Dark" src="https://user-images.githubusercontent.com/54778193/80239239-deedd400-862d-11ea-931e-b879083d789e.png">

**Comment by Windchild292** [comment]
I'll retest on Flat IntelliJ, but I believe I've resolved this since 0.47.5

**Comment by Windchild292** [comment]
This has been resolved.
