### ISSUE TITLE
Filter personal by secondary role as well as primary role

### ISSUE THREAD

**Issue by StuartSlaugh** [MegaMek/mekhq#1691]
Would it be possible to have personal be filtered by secondary roles as well as primary roles in the personal filters?  By this I mean that if my commander is both a MechWarrior and a Admin/Command that he would show up in both the MechWarrior and the Administrators filters.

**Comment by Windchild292** [comment]
Ah, personnel tab stuff. Yes, that would be possible and I'll handle this.
