### ISSUE TITLE
Scenario Resolution Fails

### ISSUE THREAD

**Issue by BairdEC** [MegaMek/mekhq#1692]
### Environment
	MekHQ 0.47.5
	Java version 1.8.0_251
	Platform Windows 10 10.0 (x86)

### Description
After completing a scenario, MHQ does not finish loading after the "Did you control the battlefield?" prompt.  The MM lobby screen's button alternates between "I'm done" and "Not done".  If I try to resolve manually in MHQ with the .mul file, MHQ doesn't appear to do anything.  I suspect that it might have to do with changing a campaign option in MHQ while MM was running, but I had changed the option (prisoner vs. bondsman) back before completing the scenario.  Up till now, I hadn't had any problems resolving scenarios.
 
### Files
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/4533879/mekhqlog.txt)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/4533881/megameklog.txt)
[customs.zip](https://github.com/MegaMek/mekhq/files/4533884/customs.zip)
[Steel Recon 2.zip](https://github.com/MegaMek/mekhq/files/4533883/Steel.Recon.2.zip) (.mul)
[customs.zip](https://github.com/MegaMek/mekhq/files/4533884/customs.zip)
[Steel Recon 230570331.zip](https://github.com/MegaMek/mekhq/files/4533885/Steel.Recon.230570331.zip) (.cpnx)
[lastturn.sav.gz](https://github.com/MegaMek/mekhq/files/4533886/lastturn.sav.gz)

**Comment by Windchild292** [comment]
Where you fighting a clan faction?

**Comment by BairdEC** [comment]
Yes, I was.

**Comment by Windchild292** [comment]
Base bug is due to an issue with clanner name migration, where it fails to migrate because of a bloodname check. That has been resolved by #1663, but I'm looking to see if there is a workaround for 0.47.5 now

**Comment by Windchild292** [comment]
The true only workaround I can find is to add a second word to every clanner name, as that should prevent the issue. However, you can also just hit okay a bunch of times and it will eventually force the dialog through, although you cannot capture prisoners if that is the case.

**Comment by BairdEC** [comment]
Adding a last name to all the clan pilots in the .mul file worked.  Thanks!

**Comment by Windchild292** [comment]
Welcome, and sorry for the inconvenience.
