### ISSUE TITLE
Determine Father Based on Spouse at Time of Birth

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/mekhq#1698]
In 47.5 I had two married people; Christopher Bachleda married Ruth Hale and then she got pregnant. 

When Ruth had a baby boy she is listed as Jaicus Hale parent. 

It also lists Christopher as her spouse.  

However Christopher is only listed as having Ruth Hale as a spouse and has no link in his family information to his son.

Jaicus Hale is listed as having Ruth as parent but has no link to Christopher.  

Also when attempting to click Jaicus Hale on the daily log nothing happens.  All other names in the daily log properly link to the personnel records  

Campaign zip with log and attached customs  attached  
[Ulric's Behemoths30581102.zip](https://github.com/MegaMek/mekhq/files/4541827/Ulric.s.Behemoths30581102.zip)

A way to right click on people and add family links would be very helpful

**Comment by Windchild292** [comment]
Ruth Hale was not married to Christopher when she conceived, and all links are generated based on spouse at the time of conception.

The family editor is current WIP, with no timeline for completion.

**Comment by MarcJC** [comment]
I know the marriage and pregnancy happened at the same time, think there was a shotgun wedding involved.  

Should there be an option to attach parenthood to spouses at time of birth?

**Comment by Windchild292** [comment]
That could easily be done through a setting, and I think it is a good addition.

**Comment by MarcJC** [comment]
Was there any luck on why trying to click on the child Jaicus in the daily log failed?

**Comment by Windchild292** [comment]
For that I believe the issue is that he id is not added to the campaign until after the birth is logged in the daily log, so the link cannot be created at the time of birth. I'm not certain, but that is my current guess on the matter.
I'll handle both changes together, given how closely linked they are.

**Comment by Windchild292** [comment]
Question, would you prefer it to be based on any former spouses that became a former spouse post-conception first, then the spouse at the time of birth @MarcJC?

(alternative wording, if a spouse dies between conception and birth and the person remarries, would you prefer the father be the one who died or the one at birth)

**Comment by MarcJC** [comment]
I think the base case should be that when a child is born look at the person who gave birth and attach them and any spouses they have as parents of the child(ren)  

seems like the easiest logic and makes sense for what ever nuclear family is in play.  Aka he might not be your father but he has always been your dad.  

Once the family editor tool is available it makes sense to use that to add any missing genetic links that way if desired.

**Comment by Windchild292** [comment]
The default will be the current version, with the option to set it based on the spouse at birth
