### ISSUE TITLE
Can't save Campaign anymore

### ISSUE THREAD

**Issue by RyuWanderfalke** [MegaMek/mekhq#1699]
What version of MekHQ does your issue apply to? -> 0.47.5
What operating system are you using?  Windows, Mac, or Linux? -> Win 10
What java version are you using?  -> Java version 1.8.0_251
![errormessage](https://user-images.githubusercontent.com/64443549/80427249-982b0300-88e7-11ea-9851-c7dfda3eb0a5.jpg)
As it shows on the screenshot. Can't save the campaign anymore. The problem persists after restarting the program. No idea why. Worked fine for many hours - until now. There was a crash during loading a save. Didn't think anything of it, but after restarting the app, the issue occured... so dunno what broke or why exactly.
 Any help is appreciated.
[CampaignAndCustoms.zip](https://github.com/MegaMek/mekhq/files/4542304/CampaignAndCustoms.zip)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/4542306/mekhqlog.txt)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/4542317/megameklog.txt)

**Comment by Windchild292** [comment]
Can I please get the MegaMeklog.text file?

**Comment by RyuWanderfalke** [comment]
Thx for the quick response. Have edited the file in the OP.

**Comment by Windchild292** [comment]
This should fix it, and I've removed any chance of the issue happening again in this version (Random Procreation is disabled, which has been fixed for the next dev release) [Schwarze Legion1.zip](https://github.com/MegaMek/mekhq/files/4542333/Schwarze.Legion1.zip)

My apologies for the inconvenience.

**Comment by RyuWanderfalke** [comment]
No apologies needed, but many thanks given for the quick help / fix! :)
