### ISSUE TITLE
RFE: Please add manual modifier to Dragoon/Ops rating

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#171]
<s>Currently, the code for Rating doesn't cover defaulting on loans. Rather than implementing that (although that would be nice as well)</s> please add a manual field for modifying the Rating. A field in the Campaign Options > General Tab would suffice allow a +/- 100 value with a floor of 1.

**Comment by dericpage** [comment]
Not that this directly impacts the idea of manually adjusting unit ratings, but just for the sake of clairity:

The Dragoons rating does cover defaulted loans at -25pts per default.  It should show up under the Financial section of the summary.  If it's not showing up or is incorrect, it should be reported as a bug.

I don't believe IntOps reputation covers loan defaults RAW, though I haven't finished reading the final release (code is still based on beta).

**Comment by scJazz2** [comment]
Could add this as a Menu Item under Manage Campaign > Unit Rating Modifier
