### ISSUE TITLE
Broken Save

### ISSUE THREAD

**Issue by RJ-42** [MegaMek/mekhq#1721]
### Environment
Version 47.5
Windows 10

### Description
Game is unable to save.
Have tried multiple times to progress and save again.

### Files
Provide the .cpnx campaign file that this issue occurs in.

[Devils8.zip](https://github.com/MegaMek/mekhq/files/4568321/Devils8.zip)

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/4568314/mekhqlog.txt)

**Comment by Windchild292** [comment]
Can I get the MegaMekLog please?

**Comment by RJ-42** [comment]
[megameklog.txt](https://github.com/MegaMek/mekhq/files/4568348/megameklog.txt)

Here it is.

**Comment by Windchild292** [comment]
[Devils8.zip](https://github.com/MegaMek/mekhq/files/4568366/Devils8.zip)
Here is a fixed save, my apologies for the inconvenience.

**Comment by RJ-42** [comment]
That was amazingly fast.  Thank you.
