### ISSUE TITLE
Refit does not save original part quality when part is cloned

### ISSUE THREAD

**Issue by ChaoticInsanity** [MegaMek/mekhq#1725]
While implementing a refit operation the original quality of a part is not retained. All cloned parts are the part default QUALITY_D.

**Comment by Windchild292** [comment]
The Part Quality change might better done by making it mandatory in Part::clone, as that is one field that likely should be cloned at all times.
As far as I can tell in the code base, this is fine to implement as any new acquisitions would be cloned off the default part of that type, not an existing modified part.

**Comment by ChaoticInsanity** [comment]
Well if I am understanding the abstract implementations of Part::clone correctly, that would mean the change should be made in Part::copyBaseData. Would that solution be preferred?

**Comment by Windchild292** [comment]
I think that would be the best implementation.
