### ISSUE TITLE
Unit model issue

### ISSUE THREAD

**Issue by Piratikal** [MegaMek/mekhq#1731]
### Environment
47.6
Windows
Java 8

### Description
Unit model issue
Customized a Tomahawk THK-63 aerospace fighter with clantech and instead of going back to the normal unit model it switched to the model for the Tomahawk Prime mech. Happens whether I use GM Mode to finish customization or let my tech do the work.

![Toma](https://user-images.githubusercontent.com/64233510/81227179-fcba2200-8fb9-11ea-9456-deb6d8ff5643.PNG)

Models are for the Cheetah GTX-6P-UK and Cheetah GTX-6Q-UK mechs also show up as the model for the Cheetah aerospace fighter when trying to buy them.

![Chee](https://user-images.githubusercontent.com/64233510/81227680-cf21a880-8fba-11ea-8109-a660b65c3254.PNG)

### Files
[mekhqlog.zip](https://github.com/MegaMek/mekhq/files/4589442/mekhqlog.zip)

No other custom units or files.

**Comment by Windchild292** [comment]
Can we get the MegaMekLog.txt file too?

**Comment by HammerGS** [comment]
The issue is the unofficial/unsupported units aren't in the Mechset.

**Comment by teerayne** [comment]
[megameklog.zip](https://github.com/MegaMek/mekhq/files/4589478/megameklog.zip)

**Comment by Windchild292** [comment]
The unit is unofficial/unsupported, and thus this is invalid.
