### ISSUE TITLE
Price/Availability Modifiers for Santa Anna Missiles

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/mekhq#174]
At present, Santa Anna warheads for Killer Whale/AR10 launchers cost the same as the base ammo type (20,000 per missile). According to the rules in Jihad Hot Spots: 3070 (as I read them), the base price for a Santa Anna should be about 22,500,000.  Being a restricted and rather rare item, I would think the availability modifier should be +2 or so higher than standard ammo.

**Comment by HammerGS** [comment]
Side note. IO updated costs and rules for all nukes.

**Comment by HammerGS** [comment]
This is going to sit open, as it will likely require code changes I can't handle.

**Comment by Dylan-M** [comment]
@HammerGS That's what makes GH so awesome. We can assign multiple people to an Issue.

**Comment by HammerGS** [comment]
This has been fixed, commit unknown but @mkerensky remembers it.
