### ISSUE TITLE
Custom refit Scourge not deploying

### ISSUE THREAD

**Issue by MrMagolor** [MegaMek/mekhq#1755]
### Environment
0.46.1, Windows 10.

### Description
A custom refit of a Scourge that I made will not deploy, despite having a capable pilot, and the fact that other custom refits work, including the previous refit I used for the exact same 'mech.

### Files
This is the day exactly before the battle. The lance in question is the Assault Lance.
I have also included the file for the variant itself.
[Scourge SCG-MG2.zip](https://github.com/MegaMek/mekhq/files/4646218/Scourge.SCG-MG2.zip)
[MrMagolorSave.zip](https://github.com/MegaMek/mekhq/files/4646215/MrMagolorSave.zip)

**Comment by MrMagolor** [comment]
I have tried removing other units from the lance, but it still does not deploy.

**Comment by MrMagolor** [comment]
Also, upon loading the match, it calls it an "illegal unit design", despite the campaign being set to Unofficial tech level.

**Comment by neoancient** [comment]
"Allow illegal units" is a separate setting from tech level.

**Comment by Windchild292** [comment]
This is just an invalid design, and can be loaded correctly when allow invalid designs is enabled. Closing as invalid.
