### ISSUE TITLE
Please remove debug code for StartingPlanet Vector and very Close items from MHQ Log

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#176]
Tired of having to scroll past this stuff. It contributes to RSI. It has been there too long. Get rid of it for now please. There is no point in having this text clutter up the log.

Hanseatic League faction did not have a long enough startingPlanet vector
Illyrian Palatinate faction did not have a long enough startingPlanet vector
Jarnfolk faction did not have a long enough startingPlanet vector
Lothian League faction did not have a long enough startingPlanet vector
Malagrotta Cooperative faction did not have a long enough startingPlanet vector
Marik Commonwealth faction did not have a long enough startingPlanet vector
Marik-Stewart Commonwealth faction did not have a long enough startingPlanet vector
Morgraine's Valkyrate faction did not have a long enough startingPlanet vector
Barony of Strang faction did not have a long enough startingPlanet vector
Mosiro Archipelago faction did not have a long enough startingPlanet vector
New Colony Region faction did not have a long enough startingPlanet vector
Nueva Castile faction did not have a long enough startingPlanet vector
Oberon Confederation faction did not have a long enough startingPlanet vector
Ohrenson-Zion Province faction did not have a long enough startingPlanet vector
Oriente Protectorate faction did not have a long enough startingPlanet vector
Principality of Gibson faction did not have a long enough startingPlanet vector
Principality of Regulus faction did not have a long enough startingPlanet vector
Rasalhague Dominion faction did not have a long enough startingPlanet vector
Raven Alliance faction did not have a long enough startingPlanet vector
Regulan Fiefs faction did not have a long enough startingPlanet vector
Regulan Free States faction did not have a long enough startingPlanet vector
Rim Commonality faction did not have a long enough startingPlanet vector
Rim Territories faction did not have a long enough startingPlanet vector
Saiph Triumvirate faction did not have a long enough startingPlanet vector
Sarna Protectorate faction did not have a long enough startingPlanet vector
Chesterton Trade League faction did not have a long enough startingPlanet vector
Silver Hawk Coalition faction did not have a long enough startingPlanet vector
Star League-in-Exile faction did not have a long enough startingPlanet vector
Stewart Commonality faction did not have a long enough startingPlanet vector
Styk Commonality faction did not have a long enough startingPlanet vector
Styk Protectorate faction did not have a long enough startingPlanet vector
Taurian Homeworlds faction did not have a long enough startingPlanet vector
Terracap Confederation faction did not have a long enough startingPlanet vector
The Barrens faction did not have a long enough startingPlanet vector
The Protectorate faction did not have a long enough startingPlanet vector
Tortuga Dominions faction did not have a long enough startingPlanet vector
United Hindu Collective faction did not have a long enough startingPlanet vector

Extremly close planets detected. Data error? Cambridge Perimeter Defense Station <-> Cambridge: 0.513 ly
Extremly close planets detected. Data error? Cambridge <-> Cambridge Perimeter Defense Station: 0.513 ly

**Comment by Dylan-M** [comment]
Rather than delete them from the log, it would instead be better if they were fixed. They are in fact errors, and the logging will not be removed.

**Comment by firefly2442** [comment]
I think these are fixed now except for the "Cambridge Perimeter Defense Station" message.

```
12:07:10,533 WARN [mekhq.campaign.universe.Planets] {Planet Loader} 
Extremly close planets detected. Data error? Cambridge Perimeter Defense Station <-> Cambridge: 0.828 ly

12:07:10,541 WARN [mekhq.campaign.universe.Planets] {Planet Loader} 
Extremly close planets detected. Data error? Cambridge <-> Cambridge Perimeter Defense Station: 0.828 ly
```
