### ISSUE TITLE
Scenario view in Briefing room cuts off TO&E

### ISSUE THREAD

**Issue by AaronGullickson** [MegaMek/mekhq#1768]
### Environment
MekHQ v0.47.6
Mac OSX 
Java 8

### Description
The view of the TO&E in the scenario view on the Briefing Room tab is cut off. You can use the arrow key to move up and down it but you can't see more than the first few units listed. I have experimented with multiple themes and the problem persists. The two text areas also take up a bunch of unnecessary empty space. 

<img width="588" alt="Screen Shot 2020-05-27 at 10 07 23 AM" src="https://user-images.githubusercontent.com/16107446/83051093-5a162180-a002-11ea-8b3b-da2ba2c65010.png">

I suspect the issue has to do with some AtB GUI elements that are not present in this campaign and the way free space is being picked up.

**Comment by Windchild292** [comment]
I wonder if this is the same as #1506

**Comment by AaronGullickson** [comment]
Yes, it is. I looked for other reports, but my search-fu failed. I will add it to the linked issues.
