### ISSUE TITLE
Unable to load campaign with custom layered force icon

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/mekhq#179]
Based off force icon branch, also observed in my custom branch which has additional commits from mekhq/master

Included error log and test campaign with a single force using the new layered icon.

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/504204/mekhqlog.txt)
[My Campaign30670101.zip](https://github.com/MegaMek/mekhq/files/504205/My.Campaign30670101.zip)

**Comment by pheonixstorm** [comment]
The fix didn't entirely work. It allows for the campaign to load but the layered force icon shows the default image rather than the created image. 

I tried it using just the " added and it worked

**Comment by pheonixstorm** [comment]
Same error from forcestub.java line 137, do you want to reopen this ticket, create a new one, or none of the above?

**Comment by Dylan-M** [comment]
Fixed with 941987275bd450b220a01784c3fe7be6f70aacd4
