### ISSUE TITLE
Hanger Value of Battle Armor much greater than Purchase Price

### ISSUE THREAD

**Issue by illrede** [MegaMek/mekhq#1795]
Searched for issues with word "Battlearmor", did not find issue

Using MekHQ 0.47.6 dev with Windows 10
java (build 1.8.0_241-b07)

Battle armor in hanger is priced (and sold for) as much as 10 times it costs (and is paid for) in the Purchase Units screen.

![Battle Armor Cost Bug](https://user-images.githubusercontent.com/57513507/83773981-2fa41400-a653-11ea-9f5e-5c022fa6eea4.png)
![Battle Armor Cost Bug2](https://user-images.githubusercontent.com/57513507/83774026-392d7c00-a653-11ea-86f4-ff46bcb4f3cf.png)

[Tercio Saltillo30930228.zip](https://github.com/MegaMek/mekhq/files/4730959/Tercio.Saltillo30930228.zip)

[factions.zip](https://github.com/MegaMek/mekhq/files/4730968/factions.zip)

**Comment by illrede** [comment]
There is also a possible issue with contract monthly pay (the monthly payouts for contracts of many months duration being comparable to what was to have been total contract payout).

![Contract Monthly Pay Possible Bug](https://user-images.githubusercontent.com/57513507/83903443-2470e700-a72c-11ea-90ff-28864d03b6a5.png)

**Comment by illrede** [comment]
I am seeing the same issue in 47.7

**Comment by illrede** [comment]
The issue is present in 0.47.8

Using MekHQ 0.47.8 dev with Windows 10
java (build 1.8.0_261-b12)


Describing the issue- the Hanger Value of units does not match the Unit List price of units. When units are sold, they are sold at the Hanger Value (obtaining over 30 million C-Bills for a squad of Leonidas Battle Armor). The TOE tab shows lance price based on unit prices.


[My Campaign31270625.zip](https://github.com/MegaMek/mekhq/files/5024178/My.Campaign31270625.zip)

**Comment by sixlettervariables** [comment]
This is due to `entity.getPriceMultiplier` for `Infantry` returning 5x because BA are anti-mech trained:
https://github.com/MegaMek/megamek/blob/d5a0f6eb05bb06caa98c7f0891b9ced09400ba99/megamek/src/megamek/common/Infantry.java#L1611-L1618

You purchase at their cost, but we sell them using a sell value computed by equipment costs multiplied by the entities price multiplier

**Comment by HammerGS** [comment]
Related https://github.com/MegaMek/mekhq/issues/2552

**Comment by IllianiCBT** [comment]
Closing as resolved
