### ISSUE TITLE
News.xml not being displayed in the daily feed

### ISSUE THREAD

**Issue by jschmetzer** [MegaMek/mekhq#1797]
Mekhq47.6
Mac

47.6 does not appear to be reading the news.xml into the daily feed. I started a fresh campaign, set the date to the day before a news item (10/21/3013) and advanced the day and saw nothing.

I *think* I saw it in previous versions, around Victor SD's birthday, but I couldn't replicate it this morning.

**Comment by jschmetzer** [comment]
Edit to add: works in last stable

**Comment by sixlettervariables** [comment]
The bug is that our news items are read as if they are dates with UTC times (correct), however, our campaign is sending over times with a local timezone. The fact that both refer to midnight is irrelevant, as those only line up if your local timezone is UTC.
