### ISSUE TITLE
New hires don't get portraits/Randomise portraits doesn't work

### ISSUE THREAD

**Issue by molemanBT** [MegaMek/mekhq#1806]
Release 0.47.6

Same save file as #1803, megamek doesn't seem to be able to locate the portraits folder?

**Comment by Windchild292** [comment]
Can I please see your portrait paths? I cannot recreate this on 0.47.6

**Comment by molemanBT** [comment]
D:\mekhq-windows-0.47.6\data\images\portraits\Female

It's on a USB stick, might that be it?

**Comment by Windchild292** [comment]
Wait, do you have any remaining unique portraits? The system will only assign unique portraits, so each portrait is only assigned once. I would recommend duplicating one of the portraits, giving it a unique name, then trying to generate a portrait.

**Comment by molemanBT** [comment]
Ah, that is potentially a cause, I've since added hundreds more pictures on a new save and it has been working from the start.

Thanks.
