### ISSUE TITLE
Purchasing ammo not possible from overview>Parts in use tab?

### ISSUE THREAD

**Issue by molemanBT** [MegaMek/mekhq#1807]
0.46.7 again, same save as #1803

Missile/AC Ammo isn't present in the parts in use tab, only empty ammo bins? This makes it impossible to stock up on ammo unless you need to buy some in the repair bay parts acquisition tab. 

Also, when you do buy ammo in this tab it arrives instantly, which is strange.

**Comment by molemanBT** [comment]
Still occurring, has the unfortunate knock on effect that if you're using an extinct weapon (eg Gauss Rifle in 3025) you can't use the free parts bonus from missions to 'find a cache'

**Comment by molemanBT** [comment]
the above refers to ordering ammo through the repair bay tab, which i think is where most people would do it from

**Comment by sixlettervariables** [comment]
I'm able to purchase AC and missile ammo from the parts-in-use report.

Working on confirming the repair bay works.

**Comment by sixlettervariables** [comment]
I couldn't purchase ammo from the repair bay's parts acquisition dialog if the ammo type had changed on the bin. I have a fix for it in my omnibus Ammo fix PR.
