### ISSUE TITLE
Awards Tracker Excel Error

### ISSUE THREAD

**Issue by rroby1** [MegaMek/mekhq#1823]
### Environment
What version of MekHQ does your issue apply to? 0.47.7
What operating system are you using?  Windows 10 10.0 (x86)
What java version are you using?  1.8.0_251
Excel 2010

### Description
Using the Excel based Award Tracker file I am unable to actually load the campaign data. I followed the instructions on the Campaign Kills tab and saved my campaign in the ...\docs\Award Stuff folder as CampaignDataForAwards.cpnx. When clicking Data - Refresh All I receive the following error 

![Error Message](https://user-images.githubusercontent.com/61069665/85716724-c136fc80-b6ba-11ea-86b0-962b44018a28.png)

Clicking through with OK leads to a long list of data ranges which failed to refresh.

**Comment by Windchild292** [comment]
Is your origin node set to a Battalion level force?
If so, I would need a campaign file and any custom mechs to verify this as an issue.

**Comment by rroby1** [comment]
My origin node is a brigade. Setting it to battalion results in the same error. If this is supposed to be limited to battalion or smaller it would be good to document that. 

I've added the campaign I use for testing stuff. I think I got all of the custom items, but if something is missing please let me know. 

[Spartans.zip](https://github.com/MegaMek/mekhq/files/4840621/Spartans.zip)

On a side note. Changing the force icon works great. Thank you for implementing that!

**Comment by Windchild292** [comment]
The save file provided was not set to a battalion level force, but had brigade tiers. That broke the generation in question. Once that was fixed, the tables were loaded properly.

It is documented in the Excel file, in the blurb that states how to use the pivot table.
