### ISSUE TITLE
Award Tracker F9 Key Does Not Do What the File Thinks it Does

### ISSUE THREAD

**Issue by rroby1** [MegaMek/mekhq#1824]
### Environment
What version of MekHQ does your issue apply to? 0.47.7
What operating system are you using? Windows 10 10.0 (x86)
What java version are you using? 1.8.0_251
Excel 2010

### Description
In the Award Tracker Excel File on the Origin Tab pressing F9 does not "reroll". It brings up the Windows 10 search window.

**Comment by rroby1** [comment]
May have tracked this down. I am using a laptop, which has shortcuts mapped to the function keys. F9 is search. Holding the Fn key while pressing F9 causes F9 to function as expected in Excel. 

I'll note my external keyboard I some times use with my laptop does not have the Fn key and pressing F9 on it results in the search window. Using the Formulas tab -> Calculate Now shortcut works regardless of which keyboard I use.  

Perhaps some documentation in the readme file will help minimize the issue tickets. It's the first place I went to figure out how to use the file.

**Comment by sixlettervariables** [comment]
Are you saying the F9 shortcut doesn't work as expected in Excel? We don't really have control over that, nor keyboard layouts (etc) outside of our software.

If I've read this wrong and you're using F9 in our software I'll reopen this. Thanks!

**Comment by rroby1** [comment]
The Excel file says to press F9. However depending on your keyboard layout it will not recalculate the spreadsheet, but instead open the Windows search window. While you can't control the keyboard layout you certainly can control the wording used in the spreadsheet. Telling users to press F9 and it not doing what they or you thinks it will do will lead to a lot of frustration and trouble tickets. 

Better to tell them to use Formulas -> Calculate Now. This works regardless of you keyboard layout.

**Comment by sixlettervariables** [comment]
I thought you said F9 did work, but rather your laptop requires you to hit Fn too. In any case, the award tracker is not official. We'll certainly take a pull request to update the language if it could be improved.

**Comment by rroby1** [comment]
On my laptop F9 alone brings up the Windows search window. It does not cause the Excel spreadsheet to recalculate. Pressing Fn and F9 does get Excel to recalculate. The spreadsheet it's self says to just press F9. 

Perhaps adding information in the readme file as to how to get Excel to recalculate and point the user to the readme in the Excel file would work. I've only used Github to report issues and commented. If I knew how to do more I would be happy to make the changes. I just don't really know how to use Github that well.

**Comment by Windchild292** [comment]
That is because laptops override the F9 key, in a standard keyboard it is properly documented as F9. FN just means use the normal F9 key instead of the override.
