### ISSUE TITLE
Award Tracker Origin Tab #NAME? Errors

### ISSUE THREAD

**Issue by rroby1** [MegaMek/mekhq#1827]
### Environment
What version of MekHQ does your issue apply to? 0.47.7
What operating system are you using? Windows 10 10.0 (x86)
What java version are you using? 1.8.0_251
Excel 2010

### Description
Continuing to play around with the awards tracking excel file. On the Origin tab the large yellow box (C3-J10) shows a #NAME? error. Same for the Education column (column I). If there is anything in the Skill column (column J) it also shows the #NAME? error. Recalculating does not change this.  

I suspect this is due to a newer version of Excel being used to set up the formulas using a function that is not supported in Excel 2010. 

The file is totally useless in Open Office 4.1.3. Pretty much every column on the table contains errors. Anyone relying on this software is out of luck without significant work. 

If there is a minimum version of Excel which is required this should be documented. Can't assume everyone has the latest version of Office. Letting people know what minimum version is needed would be nice.

**Comment by Windchild292** [comment]
Minimum excel version is 2016, due to the use of the CONCAT function. I've opened a PR to make the documentation state as such

**Comment by BullseyeSmith** [comment]
@Windchild292, sorry for leaving you this headache.  I should have clarified that it was not backwards compatible.
