### ISSUE TITLE
Faction ceasing to exist breaks existing contracts

### ISSUE THREAD

**Issue by AQGadget** [MegaMek/mekhq#1828]
Running a noble house in the Federated Suns. 3040 rolls over to 3041 and the daily log appends January 1st to the end of Dec 31st's log. No contract update, no market update. January 2nd returns to normal operation. It happens again February 1st. Had to edit my affiliated faction and the contract from FedSuns to FedCom, rewind time and advance through Feb 1st again. Markets update, contract updates

### Environment
MekHQ-windows 0.47.6

### Files

[campaign_and_logs.zip](https://github.com/MegaMek/mekhq/files/4841099/campaign_and_logs.zip)

[customs.zip](https://github.com/MegaMek/mekhq/files/4841096/customs.zip)

**Comment by NickAragua** [comment]
Fixed with PR #1831. Note that you won't get any more generated contracts until you manually switch your faction to FedCom, but at least you'll be able to advance the day without the process aborting in the middle.
