### ISSUE TITLE
Something weird happening with retirements (tech related?)

### ISSUE THREAD

**Issue by molemanBT** [MegaMek/mekhq#1829]
v.0.47.7

At the yearly retirement dialogue, sometimes it will trigger twice on the same day, i.e. I will perform the first instance, pay the retirement funds, then when I go to advance the day, it will happen again. I believe it may occur if one of the retirees is a tech of some kind. On a related note, if you pay the second day's fees again, you can continue, however, some of your units will still be being maintained by a retired tech. I think this may have been occurring in the previous build too.

Save game attached, simply advance a day, the retirement interface should pop up (increase the modifier to guarantee a tech failure?)
[error.zip](https://github.com/MegaMek/mekhq/files/4842005/error.zip)

**Comment by Windchild292** [comment]
The cause is using the advance days dialog, as that forces a double trigger.
