### ISSUE TITLE
No Deployment Limits

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#1840]
I'm using MekHQ 0.47.7

I started a campaign in 0.47.6 and soon after updated to 0.47.7. Recently, on my second mission I noticed that I had no limits to lance deployment whatsoever. I can deploy any number of lances, with any number of units (even zero!), with any weight value.

The campaign choices regarding lance weight and size appear to do nothing. The option regarding the camouflage of attached units doesn't have any effect either, they will share my colors on Megamek. I can't tell if any other option lost its effect on the game.

A save game is attached, at the day of a scenario deployment.
[MekHQDeploymentbug.zip](https://github.com/MegaMek/mekhq/files/4881833/MekHQDeploymentbug.zip)

**Comment by sixlettervariables** [comment]
Zero may be a bug (if it let you start the game), but you can certainly deploy more or less than the requested amount.

**Comment by JonhyBurner** [comment]
I could have sworn the program prevented me from deploying before. But I think I was induced in error by the description of the lance weight campaign options in the guides. I guess I'll have to practice some self-restraint. Zero units don't allow for a game to start, I was refering to a lance with no units along with others.

So apparently the only issue is the ally camouflage not working, which is hardly a problem.

**Comment by sixlettervariables** [comment]
Ally camouflage should function, so that's a bug!

**Comment by Windchild292** [comment]
I'm looking into it now, just opening up my other PR

**Comment by Windchild292** [comment]
Yeah, I misunderstood what the person was asking and have now fixed the issue with a proper implementation.

**Comment by Windchild292** [comment]
Rereading this, the issue was fixed in #1844.
