### ISSUE TITLE
Order the personnel by date of enter service/captured?

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/mekhq#1843]
### Environment
Ver 0.47.7

### Description
That's mainly the problem on prisoners. If you have many prisoners, it is merged to only one prison and I have no idea who is the prisoner captured on what battle at all. You can know individual prisoners by select the prisoner, but it only shows one person's information. But I want to arrange them by captured date.

It would be better if I can grouping them, and perhaps order by original faction seems works too on some situation, but the date of enter service/captured seems a easy solution for this.

**Comment by Windchild292** [comment]
Subsumed by 2207
