### ISSUE TITLE
Mass training not filtering out ineligible personnel

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/mekhq#185]
Using mass training you could train inactive personnel such as retired, mia, and kia as well as prisoners and dependents.

**Comment by Akjosch** [comment]
A note: "dependants" aren't the problem, they are supposed to accumulate XP and be able to be trained into some other role than Astech.

**Comment by pheonixstorm** [comment]
It could go either way for training but normally based on AtB and the old FM:Mercs rules they would not actually qualify for training until they became part of the unit. Keep it or change it as you did with allow/disallow prisoners. As long as kia, mia, and prisoners are kept clear it satisfies the report.
