### ISSUE TITLE
Sandblaster issue in 0.47.7

### ISSUE THREAD

**Issue by CrimsonThunderSB** [MegaMek/mekhq#1858]
mekhq 0.47.1

### Description
The newest update has added new abilities by default in the against the bot, and originally before, sandblaster was one of the special abilities that could be on a character.  In this recent update, it appears that while it appears to still be present in general, its not possible gain it as an ability via spending xp for special abilities.  It was available in the previous versions, however i don't know if i am doing something wrong or what.  I did manually add the special ability to one of my mechwarriors to see if it would solve the issue (since the prerequisite i only see is regular gunnery in a mech), i should be able to gain this ability if i spent 40xp.  Is this a bug, or am i not doing something right?

### Files
[The Stormbringing Destroyers.zip](https://github.com/MegaMek/mekhq/files/4907901/The.Stormbringing.Destroyers.zip)

**Comment by Windchild292** [comment]
It does appear to be a bug.

**Comment by buzzzz2138** [comment]
Found this issue in 0.48.

**Comment by Windchild292** [comment]
It is still open, and as such has not been fixed.

**Comment by pheonixstorm** [comment]
The likely cause is PR #1756 

Still present in 0.49.10
