### ISSUE TITLE
Personnel flag for same gender marriage?

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/mekhq#1859]
### Environment
Ver 0.47.7

### Description
Well, the personal preference of individual member in my force is not my business, but allows all of them to do so is somewhat weird. It is also annoying to use choose spouse as well.

So, what about the flag on the individual personnel to turn on the same gender marriage? If it is turned on, the personnel accepts random same gender marriage and also the person is listed on the personal candidate of same gender marriage. If it is not, the person is neither subjected to the same gender marriage or on the list.

I think that it should be separated with original trying to marry flag and use it to the marriage to the different gender; someone just wants the different gender, someone doesn't care for either one, and someone ONLY wants the same one. It helps me to arrange the marriage based on my personnel's preference as well. :P

**Comment by Windchild292** [comment]
This is covered by something I'm in the initial stages of design for currently, and will be a better implementation than a flag.

**Comment by Windchild292** [comment]
Duplicates #876
