### ISSUE TITLE
'Trying to Marry' Flag is not able to choose when you select both male and female personnel

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/mekhq#1860]
### Environment
Ver 0.47.7

### Description
As title says. If you only choose either male or female members, you can use special flags.../Trying to Marry. But only one member of different gender is among your multi-selected personnel, you can't choose it at all.

**Comment by Windchild292** [comment]
Just tested it and looked at the code, this is working as intended and does allow you to select multiple genders for personnel. However, it does not show up if any single one of the selection has the flag set differently than the rest, which is on purpose.

**Comment by binaryspica** [comment]
Oops, Then it was the actual problem. Thanks for clarify this.
