### ISSUE TITLE
RFE:  Add "Mass Repair" button to Command Center tab

### ISSUE THREAD

**Issue by Kendricke** [MegaMek/mekhq#1866]
As a player, I would like to have the Mass Repair function within the Command Center, because I want to keep my most used actions within the same Command Center tab as much as possible.

**Comment by Kendricke** [comment]
Alternatively, it might be nice to have an option to check that would have Mass Repair and Salvage run every time I Advance a Day.

**Comment by Windchild292** [comment]
#2011 implements the button, and I'm testing a second branch that implements an option for new day.
