### ISSUE TITLE
47.7 - NPE - New Hire Mechwarriors not able to be previewed in Personnel 

### ISSUE THREAD

**Issue by Kendricke** [MegaMek/mekhq#1870]
47.7 Dev snapshot - Win10

Searching and seems similar to description previously fixed:  https://github.com/MegaMek/mekhq/issues/1330

Twice now I've hired an elite mechwarrior while out on contract and neither would show up when selected in Personnel tab.  I can promote/demote/assign to mech/remove from roster (which I did with previous one using GM mode), but I can't actually see them.  This time, pretty sure the guy isn't pregnant.  Also, only pattern I saw was that both were elite with special abilities as I hired them. 

![image](https://user-images.githubusercontent.com/24977517/87830094-38346080-c835-11ea-96f6-24b946eca69b.png)

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/4940225/mekhqlog.txt)

[Kendricke's Templars30160105.zip](https://github.com/MegaMek/mekhq/files/4940234/Kendricke.s.Templars30160105.zip)

**Comment by sixlettervariables** [comment]
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.campaign.personnel.Person.getLastRankChangeDateAsString(Person.java:1184)
```

**Comment by NickAragua** [comment]
I encountered this as well, and it appears to have been resolved in the current state of the repo

**Comment by Windchild292** [comment]
This comes from Time in Rank not being initialized properly, and has been fixed at the current point in the repo

**Comment by HammerGS** [comment]
Fixed in https://github.com/MegaMek/mekhq/issues/1847

**Comment by Windchild292** [comment]
Disable Time in Rank and Time in Service to prevent any issues currently, and both are fixed in the repo at this time.
