### ISSUE TITLE
Could deploy mech undergoing refit

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/mekhq#1874]
Was watching the Casual Joker stream and they had an Archer undergoing refit, it was about 1/3 of the way into the refit. A mission came up (playing AtB) and they deployed the Command lance which the Archer was part of. The Archer was able to deploy under the old configuration.

No save game or cpnx files available.

### Environment
What version of MekHQ does your issue apply to? 47.7
What operating system are you using?  Windows,

**Comment by Windchild292** [comment]
I cannot recreate this on 47.6, 47.7, nor latest develop.

**Comment by HammerGS** [comment]
Interesting, They'd taken an Archer 2R and bought a kit for it to Archer 5-KH-UK.  The kit arrived and the refit started. They advanced about 3-4 days into the refit. Then the mission came up. That's when they where able to deploy it.

**Comment by sixlettervariables** [comment]
I've looked through Unit::checkDeployment and where we use it, and it seems okay. The only way this would have happened would be if the refit was cancelled somehow (like maybe the tech was reassigned or something odd?).
