### ISSUE TITLE
"Connect to Game" window bugged

### ISSUE THREAD

**Issue by Vengeant** [MegaMek/mekhq#1892]
### Environment
What version of MekHQ does your issue apply to? **0.46.1 Stable**
What operating system are you using?  Windows, Mac, or Linux?  **Windows**
What java version are you using?  **Java version 1.8.0_261**

### Description
In MekHQ, whenever I go to the Briefing Room, select my Scenario, then "Join Game", the normal dialog box with 3 blanks in it has truncated blanks.  Looks like this:
https://steamuserimages-a.akamaihd.net/ugc/1460807257587463941/5A219309B22DB50381773057B081AF0CC6DA2865/

I am able to click within these blanks and use keyboard commands (End, Home) and type away, but of course I cannot see what is in that blank.  If I type correctly and then hit Okay, I can still connect with the name I intend to use.  It's just the truncated display length of those fields that is preventing visibility -- no function seems to be lost.

Troubleshooting narrows this down to the mekhq.preferences file.  We are able to duplicate the bug by:

1 - Save a Preset
2 - Copy to someone else's computer running the same MMHQ version, and "Load a Preset" from the Campaign Options
3 - Join a scenario from the Briefing Room.  It should have this bugged window now.*

* there is a chance that it is a specific setting we are using which trips the bug

Workaround:

1 - With MekHQ not running, copy a fresh mekhq.preferences file that ships with MekHQ 0.46.1 on top of the "bugged" one in \mmconf
2 - Load up MekHQ, notice the Join Game window is back to normal

Something is broken with (1) how this version of MekHQ saves a Preset file, (2) the "Load a Preset" function, or as mentioned above (3) some specific setting we have chosen in our campaign which is a catalyst for the bug... that is causing the mekhq.preferences file to get mangled.  Also, might be unrelated, but when we loaded the Preset file that I'd saved, we noticed that all of the Campaign Options carried over *except* the Custom Ranks I set up on the settings "host".  Worth mentioning, in case this is part of the issue somehow.

### Files
I don't currently have a malfunctioning campaign anymore, due to applying the workaround I mentioned above -- and so cannot attach a .cpnx example file.  I don't think it is anything that requires the campaign file, but if you cannot reproduce it, let me know, and I'll see what I can do.

Here's a ZIP with the mekhq.preferences file that I think has whatever problem we're seeing, and the Preset file that, when used, we have the problem afterwards.
[mmconf.corrupted.zip](https://github.com/MegaMek/mekhq/files/5013147/mmconf.corrupted.zip)

**Comment by Windchild292** [comment]
I'm going to take this opportunity to standardize the dialogs between MekHQ and MegaMek.
