### ISSUE TITLE
47.8 - Portrait Folder Documentation Issues

### ISSUE THREAD

**Issue by Kendricke** [MegaMek/mekhq#1904]
I can't get portraits to randomly assign from Aero Pilot folder.  I can assign them directly, but they won't work randomly. 

Folder for "Aero Pilot" is in Male/Female folders directly.  

I've renamed the folder to Aero, Aero Pilots, Aerospace Pilot, Aerospace Pilots, ASF, and have attempted to move the folder under Naval.  Nothing works.  Instead, the game will pull from my top level custom "Kendricke's Templars" portraits folder instead.  If I remove that folder, it defaults to the default image.  

Save game attached. 

[Kendricke's Templars30181216.zip](https://github.com/MegaMek/mekhq/files/5031133/Kendricke.s.Templars30181216.zip)

**Comment by Windchild292** [comment]
Generation is working fine for me, only the one portrait in the folder generates for aerospace pilots.

![image](https://user-images.githubusercontent.com/39067288/89465024-6f64a600-d73f-11ea-8c2f-91dcd3216735.png)

**Comment by Kendricke** [comment]
I may have misspelled something earlier, but after seeing your screenshot I tried "Aerospace Pilot" and that did the trick this time. 

Please note that the documentation in the docs folder says "/Aero Pilot", however.

**Comment by Windchild292** [comment]
That would make sense, I never updated the documentation when I updated the roles.
