### ISSUE TITLE
Finish button doesn't work in scenario resolution

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/mekhq#191]
I just finished a scenario in MegaMek and went through the resolution dialog, but the "Finish" button appears to be broken.  I tried resolving the scenario manually and I still had a problem.

Log attached.

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/515934/mekhqlog.txt)

**Comment by Akjosch** [comment]
Copy & paste error on my part. As a workaround, try to disable the advanced medical setting in the campaign options.
