### ISSUE TITLE
IndexOutOfBoundsException at java.util.ArrayList.rangeCheck

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#193]
Just migrated to 0.41.24. Attached save game on Sunday. Click advance day and will hit this error. Noticed that scenarios generated for the week do no have OpFor.
[IndexOutOfBoundsExceptionAtjava.util.ArrayList.rangeCheckError.zip](https://github.com/MegaMek/mekhq/files/519242/IndexOutOfBoundsExceptionAtjava.util.ArrayList.rangeCheckError.zip)

**Comment by Akjosch** [comment]
Missing the "Command Van (Standard)" BLK file.

**Comment by Akjosch** [comment]
Just analysing the provided log, it seems that AtB somehow managed to set the enemy force weight at "colossal" or "super heavy", and there are not RATs for that.

**Comment by SirMegaV** [comment]
Strange... Command Van was in MM 2 version back. I think Ymir X is missing
from this version too. I'm not with PC now, I'll add later, or you can copy
over from previous version.

**Comment by Akjosch** [comment]
Looks like it's simply a case of the development data set for MekHQ not being exactly the same as the MegaMek one. Doesn't matter for the packaged versions.

**Comment by HammerGS** [comment]
My bad...those units are in the coming Primitives V package.  I moved the old ones to build the new ones and committed those moves my mistake.

**Comment by Akjosch** [comment]
Note that you either don't have "proper" RATs selected or are using custom ones, so I can't be 100% sure the following patch fill fix every one of your problems, but at least the errors (which basically stem from the fact that MHQ tried to generate an ultra-assault lance against you and couldn't find any RAT to do it with) should be fixed.

**Comment by neoancient** [comment]
It should not be trying to generate a colossal in the first place. I probably missed converting somewhere between the EntityWeightClass values (light == 1) and the AtB tables (light == 0).

**Comment by Akjosch** [comment]
The value is simply what `mekhq.campaign.force.Lance#getWeightClass(Campaign)` returns if the lance's mean weight is over 97.5 (for example, a typical Steiner scout lance of four Atlases).

**Comment by SirMegaV** [comment]
I'm not using any custom rats. I defaulted everything to the original, use
Neo's RAT generator and removed all my custom RATs from the folder.

**Comment by neoancient** [comment]
Ah, I didn't look closely enough and I misunderstood where that data was coming from. Now that I've had enough sleep and I've looked in more detail I agree that it's resolved.
