### ISSUE TITLE
Hotlinked family members break when person dies/retires

### ISSUE THREAD

**Issue by molemanBT** [MegaMek/mekhq#1937]
0.47.9 

As above, makes it very difficult to flick through a person's family.

As an example, go to Mechwarrior Adrine Mellouk and click on her father.

This campaign is imported from 0.47.6, if that affects anything?
[The Ill Winds30300309.cpnx.gz](https://github.com/MegaMek/mekhq/files/5091463/The.Ill.Winds30300309.cpnx.gz)

**Comment by Windchild292** [comment]
This is due to the filter, and is partially fixed by the addition of the All Personnel filter in the next release.

**Comment by Windchild292** [comment]
Fixed in latest develop.
