### ISSUE TITLE
Campaign Loading Error

### ISSUE THREAD

**Issue by Clappie** [MegaMek/mekhq#194]
Hello, I am very much new to both Github and MekHQ/MegaMek. I hope I am doing this correctly.

Using MekHQ 0.41.24. I have gotten this error with two different/new campaigns.

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/519665/mekhqlog.txt)

[Save.zip](https://github.com/MegaMek/mekhq/files/519670/Save.zip)

**Comment by pheonixstorm** [comment]
There was an additional bug with the new layered force icons that was caught after the release. It has already been fixed. For now you can edit your campaign (if old) or start over and hold off on using the new force icon editor until the next release.

To edit your campaign use a text editor such as notepad++ and look for the line number in the hq log. Match the line and you should see the icon entry section. At the end add " before the >

So, broken it looks like <iconentry key="Pieces/Frames/>
It should actually read <iconentry key="Pieces/Frames/"> notice the missing " ? It is an easy fix, but looking over that giant wall of text can be intimidating so... try it or don't, just make sure to backup your campaign before you do in case you break something.

**Comment by Dylan-M** [comment]
This issue was already reported and fixed. Closing. Please feel free to drop by the MegaMek Public Slack if you need help fixing your campaign (Once loaded, change your force icons to something else)
http://megamek.org:3000/

**Comment by Clappie** [comment]
Thank you very much! I was able to get it working based on your guidelines Pheonixstorm!

**Comment by pheonixstorm** [comment]
that will work for a quick fix. But I suggest not using them at all until the next release unless you want to contently editing your campaign.
