### ISSUE TITLE
RFE: Abilities info hover

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/mekhq#1941]
It would be awesome if, when viewing a person, to be able to hover over any abilities they have (Human TRO, Weapon Spec, etc...) and see the description text of the ability so we know what they do for abilities that aren't often used.

**Comment by Windchild292** [comment]
Where do you mean for this? If you mean under edit person, that is already how it works.

**Comment by kipstafoo** [comment]
@Windchild292 Good question. I meant in the 'personnel' tab and the 'to&e' tab. Or pretty much anywhere we're showing a person w/ their skills , injuries, log, etc...

**Comment by HammerGS** [comment]
I've seen the guys on the Casual Joker stream mention this as well.

**Comment by Windchild292** [comment]
Ah, this one shouldn't be too hard to do then. I'll look into it during my lunch break

**Comment by kipstafoo** [comment]
Awesome, thanks! I'd do it myself if I wasn't so under water with work. :)
