### ISSUE TITLE
Dropship display and Dropship Bay Bug Issue.

### ISSUE THREAD

**Issue by MageOhki** [MegaMek/mekhq#1945]
Part of our job as users, is to *help* you find frigging bugs, isn't it?  (runs from the devs who want to mallet them...)

### Environment
47.9, but campigan file started much earlier
Windows 10
Java latest version

### Description
Refitted Dropships not displaying proper sprite, Stock Dropships not showing open bays
![MMHQBay1](https://user-images.githubusercontent.com/46218554/90670998-49e09d80-e211-11ea-95d4-38a1f57186a5.gif)
Refitted dropship issue is 1
Stock Dropships issue is 2.

### Files
You poor, doomed coder (Recommend setting MMHQ's memory to at *least* 8G, I use 16G.)
Campaign File
[OHC1.zip](https://github.com/MegaMek/mekhq/files/5098294/OHC1.zip)
Custom FIles
[OHC1.customs.zip](https://github.com/MegaMek/mekhq/files/5098299/OHC1.customs.zip)

**Comment by Windchild292** [comment]
What version did you purchase the dropships without bays in? I'm guessing it was the one right after dropships with bays were released.

This is a known issue whose fix is to sell and repurchase the dropships.

**Comment by Windchild292** [comment]
Temporary indev issue, discussed how to fix with the opener and am thus closing.
