### ISSUE TITLE
Bug Report: Dropship customization assign critical not showing arcs, while in MML (same version) it is.

### ISSUE THREAD

**Issue by MageOhki** [MegaMek/mekhq#1946]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
47.9, Windows 10, Java Latest
### Description
While in MML (same package), dropship assign critical arcs *are* showing, in MHQ's customization tab, they are *not*
![Customizationtab](https://user-images.githubusercontent.com/46218554/90675786-2cfb9880-e218-11ea-912c-f10ec709bace.gif)

Update: When adding *new* weapons/removing old ones, *it appeared*.  WTF, Over?  But oddly:
![Cutom issue 2](https://user-images.githubusercontent.com/46218554/90676296-05f19680-e219-11ea-86eb-6ce917fecd66.gif)

### Files ###
Don't belive any are needed

**Comment by Windchild292** [comment]
Any ideas on this one @neoancient?

**Comment by Windchild292** [comment]
Fixed in #2055
