### ISSUE TITLE
Purchase Refit Kits without Applying the Refit

### ISSUE THREAD

**Issue by mouldsgame** [MegaMek/mekhq#1959]
I would like to request that an option be added to the Available Refits window that allows you to purchase refit kits but not begin the refit at that time.  Specifically I was thinking around Omni's where it would make sense to have several different configurations ready to go at any times.   Currently you can just go through with the refit but this can take weeks or months if you are using planetary acquisition.

**Comment by jschmetzer** [comment]
+1 to this

**Comment by RexPearce** [comment]
This might be related to #1251. Omni's probably shouldn't require refit kits for pod changes.

**Comment by Windchild292** [comment]
Subsumed by #3170
