### ISSUE TITLE
47.9 Repair tasks can conflict resulting in impossible rolls & destroyed parts

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/mekhq#1967]
### Environment
Version 47.9
Windows 10
Java version 1.8.0_261

### Description
Somehow, two repair tasks are active that require the same part - in this case, a Mech Left Leg (70 tons) that needs replacement on two separate Grasshoppers. Only one such part is present in the Warehouse. When Advance Day is pressed and the tasks complete (both having taken more hours than were available in one day), if the first task succeeds, the second task is listed as "Needs Impossible" and the location is destroyed as if due to a failed tech roll (if said rule is active, which it is in this save). 

I am uncertain how both tasks managed to become active simultaneously, given that only one replacement part is available. 

Reproduction steps: load the attached campaign file and press Advance Day. As long as the first replacement is successful, the second will fail. If the first replacement fails due to a low roll (needs 4, so a roll of 2 or 3), then the second replacement will be successful, as the part will not be consumed and the MoF is not high enough to damage or destroy it. 

### Files
[RepairBug-Coppercoats.cpnx.gz](https://github.com/MegaMek/mekhq/files/5120842/RepairBug-Coppercoats.cpnx.gz)
No custom units or other custom files.

**Comment by gsparks3** [comment]
Ah, I think I have a save that demonstrates how such a situation can come about. See below.
[Coppercoats.zip](https://github.com/MegaMek/mekhq/files/5179000/Coppercoats.zip)

Details of note:
In the Warehouse, there is a single Mech Left Leg (70 tons) available. 
In the Repair Bay, the task to replace the Grasshopper's left leg is active, but needs more time (315 minutes) to be completed. 
Also in the Repair Bay, the task to replace the Guillotine's left leg is _not_ active, but is shown in green with "Replacement part available" - this would be the same Mech Left Leg (70 tons). It seems the issue is due to the part not being somehow flagged as "already in use for a replacement" (e.g. the Reserved for Refit status used during customizations).

**Comment by inqistor** [comment]
Yeah, I just got the same issue with Heat Sinks. 3 were needed, but I had only 2. I tried to salvage one more, but I think I failed (didn't pay close attention to it), but there was suddenly third Heat Sing available, so I began repair with that one also. Suddenly next day there was IMPOSSIBLE, and part destroyed. The point is, that it started with correctly showing that there is no third part available (sorry, no save), and then it seems one of the part flagged for repair became unflagged.

**Comment by sixlettervariables** [comment]
This one will take a bit of thought. We already track this for refits but not for repairs. Ultimately we should be tagging the part with its PartWork, or, have a list of parts being "used" by a task and exclude those when picking a valid part.

**Comment by sixlettervariables** [comment]
Setting this up from a clean campaign I'm having problems reproducing the issue:
![image](https://user-images.githubusercontent.com/8238690/94731635-1c6c3100-0333-11eb-9a6f-6b4fd904bc61.png)
![image](https://user-images.githubusercontent.com/8238690/94731650-22621200-0333-11eb-9c24-dc760c3090e2.png)

**Comment by sixlettervariables** [comment]
Okay, here is an interesting find after loading my CPNX:
![image](https://user-images.githubusercontent.com/8238690/94732053-b633de00-0333-11eb-8902-53ce3652488c.png)

It appears we are not saving the replacement ID details.
