### ISSUE TITLE
MekHQ: Small Craft - Single Hex ECM

### ISSUE THREAD

**Issue by FourMansGamesAdmin** [MegaMek/mekhq#1970]
### Environment
MekHQ 0.46.1 and above.
Windows 10
Java version 1.8.0_231

### Description
MekLab in MekHQ is automatically adding a 0.1 ton Single Hex ECM piece of equipment to all SmallCraft and will not allow the player to refit the craft because this item cannot be removed or allocated.

### Files
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/5127266/mekhqlog.txt)
[megameklog.txt](https://github.com/MegaMek/megamek/files/5127268/megameklog.txt)
[Mordel Campaign - Allies30250711.zip](https://github.com/MegaMek/megamek/files/5127269/Mordel.Campaign.-.Allies30250711.zip)

**Comment by Windchild292** [comment]
Isn't this a MML issue @HammerGS?

**Comment by HammerGS** [comment]
Says refit and MekHQ so assuming it’s another refit issue.

**Comment by Windchild292** [comment]
On further look it might be... and if so I wonder if it was fixed in #2025

**Comment by RexPearce** [comment]
Looked into this a bit, the Single-Hex ECM is being added here:

https://github.com/MegaMek/megamek/blob/908699cc60a02a5d806676f009984635dea5c4a4/megamek/src/megamek/common/Entity.java#L12035-L12050
```
        // FIXME: This is a really hacky way to to do it that results in small
        // craft having
        // ECM when the rule is not in effect and in non-space maps
```

**Comment by Sleet01** [comment]
This is now causing Small Craft to turn up as invalid after they are configured, as the Test Small Craft doesn't think IS BA ECM is appropriate.  I'll wrap this into the aerospace work I'm doing for internal bomb bays.
