### ISSUE TITLE
LAMs can't be assigned in the personnel screen

### ISSUE THREAD

**Issue by VicenteCartas** [MegaMek/mekhq#1972]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
What version of MekHQ does your issue apply to? 0.47.9
What operating system are you using?  Windows, Mac, or Linux? Windows
What java version are you using?  11

### Description
The attached campaign was started by generating a mul in megamek, and then importing it into mekhq. The Phoenix Hawk LAM appears on the Hangar, but on the Personnel tab, is not possible to select it when assigning a mech to a mechwarrior (it doesn't appear in the list of Medium mechs).

### Files
[BT Campaign 3058.zip](https://github.com/MegaMek/mekhq/files/5134048/BT.Campaign.3058.zip)

**Comment by NickAragua** [comment]
Mechwarrior needs to have a secondary 'aerospace pilot' role (and probably have a couple of points in piloting/gunnery for aerospace)

**Comment by VicenteCartas** [comment]
That totally worked, thanks!
