### ISSUE TITLE
Add Ransom Mech to Salvage Options in Mission Resolution

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#198]
Can we get an option to ransom a mech instead of salvaging it in the mission resolution screen. This would be some % of the mechs worth, probably set in the campaign options.

Similarly, I'd like to see an option to ransom prisoners instead of just setting them free added to the prisoner options.

**Comment by pheonixstorm** [comment]
For prisoner ransom so far only AtB has a basic system in place but it does not remove the ransomed prisoners. Even then you can remove them and add the ransom to the ledger yourself.

For units you can just sell the salvage as is for the ransom

In either case it can be done manually so not sure when the devs might tackle this but I agree both options would be nice to have.
