### ISSUE TITLE
java.lang.NullPointerException - mekhq.campaign.force.Lance.writeToXml(Lance.java:472)

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/mekhq#1983]
Went to save the campaign and got this error. I've heavily restructured my unit.

### Environment
What version of MekHQ does your issue apply to? 47.10 SNAPSHOT
What operating system are you using?  Windows, 

### Description
```
21:48:42,342 INFO [mekhq.gui.CampaignGUI] {AWT-EventQueue-0} 
menuSaveXmlActionPerformed(ActionEvent) : Saving campaign...

21:48:57,183 ERROR [mekhq.gui.CampaignGUI] {AWT-EventQueue-0} 
saveCampaign(Campaign campaign, File file) : null
java.lang.NullPointerException
	at mekhq.campaign.force.Lance.writeToXml(Lance.java:472)
	at mekhq.campaign.Campaign.writeToXml(Campaign.java:4639)
	at mekhq.gui.CampaignGUI.saveCampaign(CampaignGUI.java:1341)
	at mekhq.gui.CampaignGUI.menuSaveXmlActionPerformed(CampaignGUI.java:1307)
```

### Files
This is an older save file.
[Autosave-1-The Harriers-30460614.cpnx.gz](https://github.com/MegaMek/mekhq/files/5159979/Autosave-1-The.Harriers-30460614.cpnx.gz)

[megameklog.txt](https://github.com/MegaMek/mekhq/files/5159991/megameklog.txt)

**Comment by Windchild292** [comment]
Fix will be up in 30, testing now

**Comment by Windchild292** [comment]
Ignore that, I cannot build because of repeated gradle issues.
