### ISSUE TITLE
Large Game Option suggestion 1: Disabling GM/Player ability to assign marriages

### ISSUE THREAD

**Issue by MageOhki** [MegaMek/mekhq#1984]
### Environment
47.9, WIndows 10, Latest Java.

### Description
As noted, discussions with Windchild, this is a major performance issue, and is really noticeable with tens of thousands of personnel.  An option to disable the ability to assign marriages would speed up the single personnel selection (right click for menu)

### Files
Should not be needed

**Comment by Windchild292** [comment]
This is only a potential performance issue with tens of thousands of personnel.
