### ISSUE TITLE
Handling Bays in MMHQ

### ISSUE THREAD

**Issue by MageOhki** [MegaMek/mekhq#1988]
Environment
47.9, WIndows 10, Latest Java.
Description
in 1388, I suggested letting ultra light (under 20t) vees count, in groups as 1 light vee.  Suggestion is for 2 light vees (or groups) to count as 1 heavy vee, 2 heavy vee as 1 superheavy vee.
Files

Should not be needed

**Comment by Windchild292** [comment]
@HammerGS 
Rules question/clarification on this one.

**Comment by Windchild292** [comment]
@HammerGS second ping on rules question/clarification on this one.

**Comment by Windchild292** [comment]
Closing as unofficial based on previous discussion with the opener.
