### ISSUE TITLE
Failure to resolve battle automatically or manually

### ISSUE THREAD

**Issue by monbvol** [MegaMek/mekhq#199]
[MekHQBugReports.zip](https://github.com/MegaMek/mekhq/files/530750/MekHQBugReports.zip)

Could not resolve my second battle in my current AtB campaign.  Included completed fight mul in zip for reference.

**Comment by neoancient** [comment]
Did you save the campaign after a failed resolution attempt? In the campaign file the allied and enemy forces are in the state of a resolved scenario, though even so I don't see any way for the campaign to have gotten in that state.

**Comment by monbvol** [comment]
Yes I saved the campaign after the initial failure to resolve for the
battle that still shows as pending.

**Comment by neoancient** [comment]
Now that I've looked at the advanced medical bug I see what happened. It occured while applying the resolution to the campaign and only part of it was applied. This left the scenario in an illegal state. I added a check in  d5362c4 to allow it to process the resolution, but there are some other changes I can make that will improve the way allied units are handled.

**Comment by monbvol** [comment]
Glad to hear it.  Looking forward to the next release.
