### ISSUE TITLE
GameOptions Dialog Okay button shows as disabled after recent code changes

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/mekhq#20]
Tested this with my fork as well as most recent HQ commit.

HQ starts up correctly but when trying to set the options for megamek the ok button is greyed out as if disabled. I did not find any errors in the log file though I did notice that HQ loaded the campaign options three time.
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/141356/mekhqlog.txt)

**Comment by Dylan-M** [comment]
Fixed in ec84325
