### ISSUE TITLE
Cannot Resolve Battle Automatically or Manually 0.41.24

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/mekhq#200]
[Cannot Resolve Battle.zip](https://github.com/MegaMek/mekhq/files/531149/Cannot.Resolve.Battle.zip)

This may or may not be the same issue as #199, so I'm reporting it separately just in case. 

The MHQ log file seems to indicate that there is a problem with Advanced Medical. This did not occur when using the same attached campaign file under 0.3.32.  I had this problem last week after I first upgraded, and thought it was because of a bunch of units I deployed to the scenario, then removed in the MM lobby plus a version upgrade between starting and finishing the battle. I started the whole thing over using the same version and only deploying the units I actually meant to participate, and I'm getting the same resolution errors - that's what is attached.

**Comment by pheonixstorm** [comment]
Known bug and I think fixed in 0.41.25

**Comment by mkerensky** [comment]
Yes, just downloaded and tested with 0.41.25.  It seems to be working now.  Thanks!
