### ISSUE TITLE
Required heat sinks not determined properly on vehicle refit

### ISSUE THREAD

**Issue by RexPearce** [MegaMek/mekhq#2007]
A patch is attached below.

To reproduce:

1. start a new campaign
2. Add (GM) a "Manticore Heavy Tank (Standard)" to the hanger
3. Customize the Manticore in the Mek Lab
4. In the Mek Lab:
A. note there are 3 heat sinks listed in the summary
B. change the engine type to ICE
C. note there are now 13 Heat Sinks listed in the summary
D. note that no additional heat sinks are listed under "Parts required"

The bug is using engine size to determine the number of critical-free heat sinks (which doesn't apply to vehicles) instead of the engine type.

Patch: [Vehicle_refit_HS_fix.zip](https://github.com/MegaMek/mekhq/files/5228621/Vehicle_refit_HS_fix.zip)

Contents of patch, for reference:
```
--- MekHQ/src/mekhq/campaign/parts/Refit.java-orig
+++ MekHQ/src/mekhq/campaign/parts/Refit.java
@@ -899,10 +899,10 @@ public class Refit extends Part implements IPartWork, IAcquisitionWork {
             // We're only concerned with heat sinks that have to be installed in excess of what
             // may be provided by the engine.
             if (oldUnit.getEntity().hasEngine()) {
-                oldHS = Math.max(0, oldHS - oldUnit.getEntity().getEngine().integralHeatSinkCapacity(false));
+                oldHS = Math.max(0, oldHS - oldUnit.getEntity().getEngine().getWeightFreeEngineHeatSinks());
             }
             if (newEntity.hasEngine()) {
-                newHS = Math.max(0, newHS - newEntity.getEngine().integralHeatSinkCapacity(false));
+                newHS = Math.max(0, newHS - newEntity.getEngine().getWeightFreeEngineHeatSinks());
             }
             if (oldHS != newHS) {
                 Part hsPart = heatSinkPart(newEntity); // only single HS allowed, so they have to be of the same type
```

**Comment by HammerGS** [comment]
Hi, it would be better if you could create Pull Requests for code and in general.

https://github.com/MegaMek/megamek/wiki/Creating-a-Pull-Request%28PR%29-if-an-outside-contributor

**Comment by RexPearce** [comment]
Thanks for the link. It looks like the PR worked, but let me know if there are any issues.
