### ISSUE TITLE
Updated force icons

### ISSUE THREAD

**Issue by wildfire142** [MegaMek/mekhq#203]
I've re-tweaked the infantry icons to be a base type infantry and adjustments to make specific types, have also created tracked, wheeled and hover infantry type icons.

looking at the files github has some older ones so have included the entire package in the zip, would recommend removing all the old one and using these, there are slight improvements to many of them.

new file further down coments

**Comment by Akjosch** [comment]
Notes on future-proofing the file names before this gets merged in by overly eager hammers or similar:

`Adjustments/scuba.png` should be `Adjustments/Scuba.png`

We might as well do the whole alphabet range and add `Alphanumerics/F.png`, `Alphanumerics/J.png`, `Alphanumerics/K.png`, `Alphanumerics/N.png`, `Alphanumerics/O.png`, `Alphanumerics/R.png`, `Alphanumerics/U.png`, `Alphanumerics/W.png`, `Alphanumerics/Y.png` and `Alphanumerics/Z.png`

`Background/merc.png` should be `Background/Merc.png`

The underscores in several file names in the `Formations` directory should be replaced with spaces and capitalised (that'll likely break some people's current images, but that's life when you're on non-stable releases): `05 Lance_augmented.png`, `07 Company_task_force.png`, `14 Field_Army.png`, `15 Army_Group.png`, `16 Level_I.png`, `17 Level_II.png`.

`Logos/FederatedCommonwealth.png` should be `Logos/Federated Commonwealth.png` (add the space) same for `Logos/CircinusFederation.png`, `Logos/LyranAlliance.png`, `Logos/MarianHegemony.png`and `Logos/OutworldsAlliance.png`.

MoC has two logos: `Logos/Magistracy of Canopus.png` and `Logos/MagistracyofCanopus.png`; the latter can go.

Same for Clan Wolverine: `ClanWolverine.png` can be deleted.

`Logos/Rim World republic logo.png` should be `Logos/Rim Worlds Republic.png` (note: "Worlds", not "World").

`Logos/Word of blake.png` should be `Logos/Word of Blake.png`

`Type` has a whole bunch of underscores and capitalisation mismatches.

**Comment by wildfire142** [comment]
Corrections being made to source files will have a new zip up in a while.

will get started on the other letters but those are the only ones listed in the symbology section of StratOps which is why they came first.

**Comment by wildfire142** [comment]
Changes made as suggested by Akjosch
[Force Icons v6.zip](https://github.com/MegaMek/mekhq/files/535926/Force.Icons.v6.zip)

**Comment by wildfire142** [comment]
As asked for the rest of the alphanumeric changes including Low letters so they don't clash with the infantry, recon and command symbols.

[More Alphanumeric Icons.zip](https://github.com/MegaMek/mekhq/files/536851/More.Alphanumeric.Icons.zip)

**Comment by Dylan-M** [comment]
These are now included in 285e4991be04212177dc4cc92b91ba757ea40222
