### ISSUE TITLE
47.10 Campaign Options from Preset Fail

### ISSUE THREAD

**Issue by jschmetzer** [MegaMek/mekhq#2032]
### Environment
v47.10
Mac OS

### Description
When saving a custom campaign options preset, the values do not appear to be translating correctly to the loaded game; for example, record keeping switches from FM:MercR to CamOps; acquisition role choice changes, AtB is unselected...  when I read the XML of the saved preset it looks correct, but doesn't load that way. 

I'm not convinced its writing correct values into the preset, either, but I don't have an example.

To recreate: load game with attached XML preset, then compare values loaded against stored.

### Files

[Jason.xml.zip](https://github.com/MegaMek/mekhq/files/5255572/Jason.xml.zip)

**Comment by Windchild292** [comment]
Running on the dev branch, this is working fine for me? From where are you loading the preset?

**Comment by jschmetzer** [comment]
I DL'd the new release, began a new campaign with AtB presets, set 3030-01-01, then went through and adjusted the campaign values, then hit 'confirm and save'. When the game loaded the values were not what I had selected, so I repeated and got same result.

Let me unzip it again, and try again clean. Maybe I had a bad unzip.

**Comment by Windchild292** [comment]
Interesting... how I tested (on load) works, but there appears to be some issues after that.

**Comment by Windchild292** [comment]
Found an issue which may be the cause... needed to do on change instead of if the value is true.

**Comment by Windchild292** [comment]
... I forgot to save the updated options to the campaign when loading from preset...

PR opened with a fix.

**Comment by jschmetzer** [comment]
I want to say 'glad I could help' but that made you do a bunch of work... :) So I'll just say 'glad you found something!"

**Comment by Windchild292** [comment]
Nah, I'm glad you pointed it out so it could be fixed... one of those annoying errors that is easy to miss on testing especially when you are focusing on the more substantial changes to skills and special abilities... and this one wasn't a bad fix just... one you find the final issue and facepalm about
