### ISSUE TITLE
47.10 Bug: 1st of the Month not showing in logs

### ISSUE THREAD

**Issue by Kendricke** [MegaMek/mekhq#2039]
Whenever I advance to the 1st day of a new month, the log freezes on the last day of the previous month.  My finances increase if I'm on contract, and unit/contract markets update, but the log does not  show the new day has happened.  If I advance the day again, the log correctly advances to the 2nd day of the month.  

This occurs with Advance Day OR Advance to Next Month options.  

[Kendricke's Templars30211029.zip](https://github.com/MegaMek/mekhq/files/5262546/Kendricke.s.Templars30211029.zip)
[customs.zip](https://github.com/MegaMek/mekhq/files/5262549/customs.zip)
[awards.zip](https://github.com/MegaMek/mekhq/files/5262551/awards.zip)
[images-awards.zip](https://github.com/MegaMek/mekhq/files/5262553/images-awards.zip)

**Comment by Kendricke** [comment]
Quick note on this.  I confirmed that I actually have NOT been getting monthly payments on contract since 47.10.  You should be able to see that in the attached files already.  

If your fix takes care of this, great.  Just clarifying since my original report looked like I was getting paid.

**Comment by Windchild292** [comment]
The fix handles payment as well.
