### ISSUE TITLE
Null Portrait Category Causes Campaign Save Failure

### ISSUE THREAD

**Issue by inqistor** [MegaMek/mekhq#2041]
WINDOWS 10. I just downloaded 47.10, copied my save file from 47.9 and all worked fine. Even saved after some repairs. Then I run short battle, and suddenly I can not save campaign again. I tried to advance a day, but still can not save. It writes to send mekhqlog.txt, so here it is:
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5263027/mekhqlog.txt)

**Comment by Windchild292** [comment]
I will need your campaign, customs, and megameklog.txt.

Additionally, I will need the MUL for the combat in question if possible.

**Comment by inqistor** [comment]
I think I have saved mul. Here it is together with last working save, and megameklog.txt. What is exactly campaign, and customs?
[BadSave.zip](https://github.com/MegaMek/mekhq/files/5263086/BadSave.zip)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/5263087/megameklog.txt)

**Comment by Windchild292** [comment]
Okay, I've found the issue... something that should not be possible occured.

**Comment by Windchild292** [comment]
There is a work around... all you need to do is assign Nuutti Takala a portrait.

The campaign is the save file, customs are any custom units you use for the campaign in question.

**Comment by Windchild292** [comment]
I'm in the process of completely reworking portraits, so this will not be possible in the near future.... but I have not found a way for this to occur as of yet in that process.

**Comment by inqistor** [comment]
Well, nothing happens when I try to assign portrait to it. Random, or not. Deleted sucker, but still can't save.

**Comment by Windchild292** [comment]
Can I get the log after he was deleted?

**Comment by inqistor** [comment]
Here ya go

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5263141/mekhqlog.txt)

**Comment by Windchild292** [comment]
and the megamek one too. Our logging writes to both in MekHQ

**Comment by inqistor** [comment]
And another one

[megameklog.txt](https://github.com/MegaMek/mekhq/files/5263145/megameklog.txt)

**Comment by Windchild292** [comment]
Page Aranda is the next one causing issues. Neither are in the pre-issue save. Did you create the pair in MegaMek?

**Comment by inqistor** [comment]
Nah, those are random crewmen created for bot side by MegaMek. Although I generated two artillery units for a first time.

**Comment by inqistor** [comment]
OK, same issue here. Can't change portrait, and deleted him. Still not working. But I just get rid of all prisoners, and now can save. It seems whole bunch got corrupted. But I must say it is my first mission under 47.10.

**Comment by Windchild292** [comment]
Go to the personnel tab, prisoner filter. Remove all prisoners. That will fix the issue. For how it is happening now, I cannot think of a file change that should cause this... I haven't merged any portrait generation changes since 0.47.9 to my knowledge.

For any programmers, the issue here is that a non-nullable value is being set to null. I've got a rework in progress that will remove this issue permanently.

**Comment by inqistor** [comment]
It might be non-nullable in MekHQ, but something else in MegaMek, and got confused during conversion.

**Comment by Windchild292** [comment]
Yeah, that is likely correct. Similar issues exist with camouflage currently, but... same rework will handle those.

**Comment by inqistor** [comment]
I just finished another combat, and got the same issue - can't save. I've deleted all prisoners, and saving works. It seems you have now bug in 47.10.
It might be one of my campaign setting causing this, as I have turned on quite a lots of modifiers. But everything worked under 47.9.

**Comment by Windchild292** [comment]
I'll take another look, but I'm going to push hard to get the underlying issues with Camo and Portraits fixed before our next dev release.

I would recommend reverting to the previous release and I shall do my best to get this issue fixed for our next release, but I cannot promise it (time constraints... this is a sadly obvious symptom of a major underlying issue I'm trying to fix, but one that requires significant work to fix).

**Comment by Windchild292** [comment]
Looking at it with clear eyes, this is fixed by https://github.com/MegaMek/megamek/pull/2230
