### ISSUE TITLE
AtB Prisoner Defection Appears Disabled

### ISSUE THREAD

**Issue by jschmetzer** [MegaMek/mekhq#2042]
### Environment
47.10
Mac OS

### Description
When prisoners are taken, none appear to be rolling the defection check; I installed a clean 47.10, did the following steps to test:

1.  Enabled AtB, GM created new contract and scenario
2. In MM screen, added a bunch of infantry platoons (to get a significant number of prisoners)
3. used /victory to win the scenario
3. claimed all infantry as prisoner.
4. completed scenario and checked prisoner status. No defections from 100+ prisoners.

### Files
[prisoner_test.mul.zip](https://github.com/MegaMek/mekhq/files/5264879/prisoner_test.mul.zip)
[prisonertest.cpnx.gz](https://github.com/MegaMek/mekhq/files/5264880/prisonertest.cpnx.gz)

**Comment by Windchild292** [comment]
Will look into this in the morning. Can I also see the megameklog.txt and mekhqlog.txt for additional information.

**Comment by jschmetzer** [comment]
:( Oops. I deleted the install already. Sorry I should have grabbed the logs.

**Comment by Windchild292** [comment]
AtB Random Enemy Capture is disabled on the supplied campaign. This is different from the prisoner capture option under personnel, and is at the bottom of the scenarios options on the AtB tab.

There is a story open to merge the two, but that has not been implemented as of this time.
