### ISSUE TITLE
47.11-Dev Multiple copies of refit kits in Choose Refit Kit menu?

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/mekhq#2043]
### Environment
Version 47.11-Dev (https://github.com/MegaMek/mekhq/actions/runs/267659737)
Windows 10
Java version 1.8.0_261

### Description
When opening the Customize -> Choose Refit Kit menu from the Hangar, duplicate entries are displayed for available refit kits. Initially entries were duplicated 2 times, but after saving and reloading entries are now duplicated 3 times. Saving and reloading once more did not cause further duplication. 
![image](https://user-images.githubusercontent.com/59574316/93955921-db669200-fd1e-11ea-923e-057eb558baf5.png)
Note: duplication does NOT reproduce if save is opened in MekHQ v47.10 - cause for this is unknown. 

### Files
[Coppercoats.cpnx.gz](https://github.com/MegaMek/mekhq/files/5265069/Coppercoats.cpnx.gz)
No custom units or other files.
[megameklog.txt](https://github.com/MegaMek/mekhq/files/5265084/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5265085/mekhqlog.txt)

**Comment by RexPearce** [comment]
I opened your campaign file with the latest dev, and wasn't able to reproduce.

Is it possible you have duplicate unit files in your install? I remember having similar behavior when I unzipped the mechfiles/vehicles.zip file. Are there duplicated entries in the Marketplace -> Purchase Unit menu as well?

**Comment by Windchild292** [comment]
Also clear the unit cache

**Comment by gsparks3** [comment]
Still not sure what caused the issue in the first place, but deleting units.cache resolved the issue.
