### ISSUE TITLE
Load Saved Game Starts In Wrong Folder

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/mekhq#207]
I still have HQ0.3.32 on my desktop in case I forgot to transfer something.  I setup a scenario and then saved just as a precaution because Im worried about if the resolution bug is fixed in 0.41.25 which Im about to test.  I screwed up and forgot to give the opfor turrets so /reset.  Then /load ERB and it set the opfor as a ghost.  File>replace players was greyed out,  Added a 3rd and could not transfer the ghost's units over to #3.  /kick 2 and it then transferred her units but, still listed Simulation[Ghost}.  Could not configure any of her units.  /who listed only me the player, replacePlayer 2 -b:Princess -c:SIM failed since there was no player 2.  I realize this is partly a MM issue as well.  So exited back to HQ then clicked Load from a saved game and it listed a bunch of old saves from my 0.3.32 and not the ERB.sav.  It starts out in my 0.3.32 folder instead of the 0.41.25 folder why?  The CPNX maybe still lists that filepath or something?

I doubt these will be any help:
[HQoddity.zip](https://github.com/MegaMek/mekhq/files/543355/HQoddity.zip)

**Comment by Dylan-M** [comment]
Actually this is WAD (Working As Designed), if you copied over your mmconf folder. The programs store your "last X" info in files inside of mmconf.
