### ISSUE TITLE
Additional options for prisoners in Personnel tab

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#2079]
Please add the ability to sort prisoners by willing/not willing to defect.  Sorting by "rank" or other column does not do this.

Also, please add the ability to use the "Free" option with multiple prisoners selected.

**Comment by Windchild292** [comment]
As of 0.47.10 Rank sorts prisoners first by prisoner status and then by individual rank, as part of #1926

The latter is an enhancement.
