### ISSUE TITLE
RAT Generator Faction Dropdown Box Empty

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/mekhq#208]
Was working the last time I loaded this save.  Now doesnt populate, makhqlog has a whole block of listening for clients nullx1,000.  Then a: 
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at megamek.client.ratgenerator.UnitTable.generateTable(UnitTable.java:97) 
On this second time of attempting to load my save I just created tonight.

![github0](https://cloud.githubusercontent.com/assets/16950832/19584607/520edc1a-970b-11e6-934f-ced9e763812b.png)

AFFS-FSAC-2REG-2BN-3CO
[RATgeninop.zip](https://github.com/MegaMek/mekhq/files/543383/RATgeninop.zip)

**Comment by BLOODWOLF333** [comment]
After thinking about this, it might be because I copied my default.zip RAT from 0.3.32 over into 0.41.25 since i put my turret RATs into that version.  Will re-extract the 0.41.25 RATs, put my turrets in, and retest when I get home.

**Comment by neoancient** [comment]
The custom RATs have nothing to do with the RAT generator. Also, this is a MM issue. I added some checks to prevent the NPEs in MegaMek/megamek@2f21933. I have not tracked down the reason it sometimes does not populate the faction list, but I'm pretty sure it has to do with the data not being loaded yet and the event handler not working correctly. As a workaround, you can click on "show minor factions" to make it refresh.

**Comment by BLOODWOLF333** [comment]
@akjosch: Ok ill do that.  Takes way too long to extract that whole file and then add in my turret RATs and rezip anyways.
@neoancient: Ah, i didnt try the show minor factions box.  And I dont know why I posted this on the HQ tracker, wasnt paying attention.  Close?

**Comment by neoancient** [comment]
If you could open one on the MM tracker, I'll be less likely to forget to look at it.
