### ISSUE TITLE
RFE: AtB: Vary unit quality in the Unit Market

### ISSUE THREAD

**Issue by RexPearce** [MegaMek/mekhq#2085]
It'd be cool to have some variety in the quality of the units offered for sale in the Unit Market (along with prices to match). So that  you have choice between a pristine mech from the factory that costs more, or a discounted option from the Mercenary Market but the parts are mostly A/B rating.

This could be extended furthered by have some units be randomly damaged (e.g. missing engine, gyro, weapons, limbs, etc.) for an even greater discount. (Could even be hidden: Surprise, that Black Market Marauder doesn't have an engine!)

**Comment by purpledragon2** [comment]
I've always thought there should be an option for this.  Furthermore, it should extend to the equipment available to allies and opfor.  I suggest an option to vary unit/equipment quality for each based on location from and unit ratings where it applies to allies and opfor.
