### ISSUE TITLE
MML in MHQ: changing equipment on omnimeks treated same as battlemek

### ISSUE THREAD

**Issue by Aries144** [MegaMek/mekhq#209]
Modifying weapons on omnimeks results in same (class A or higher) time cost as a regular mek even though it should be an omni pod change with a significant time savings.

**Comment by Question2** [comment]
If you want to repod it, you need to do so via the "use refit kit" option instead of customizing it in the mech lab.

**Comment by Dylan-M** [comment]
@Question2 Incorrect. Custom repods are supported. However, they **_are_** broken at the moment.

**Comment by Question2** [comment]
That's odd, i can't find any mention of custom repods in the history.txt file. The latest mention i can find of omni pods is for 3.17 : + Bug [#682]: Omni pod refits are not working correctly.

I've always had to make custom repods by making another variant via the mek lab first and then refitting it in the hangar via refit kits. Are you supposed to be able to make a new omni variant from scratch in the mek lab and have the refit times treated as class A as long as you don't break the omni pod rules?
