### ISSUE TITLE
Unable to Add Unit in Add Loot/Potential Rewards dialog of editing scenario

### ISSUE THREAD

**Issue by inqistor** [MegaMek/mekhq#2091]
WINDOWS 10, 47.10

I checked it in new campaign, and behavior is the same. No matter what type of unit I choose, nothing shows up on Summary tab, no matter what unit I check. Add button doesn't work, and whole interface is unresponsive. It takes some fancy moving to be able to click Cancel finally.

Moreover, it seems to be some global error in MekHQ database, because the same behavior happens in MegaMek battle, when started from MekHQ campaign. Nothing shows up, when you try to Add Unit to force from list. Clear MegaMek instance seems to work fine in that case.

**Comment by Windchild292** [comment]
MegaMeklog and mekhqlog are both required for this

**Comment by inqistor** [comment]
I am not sure you need logs, because I can reproduce this by just starting up new campaign, and creating first scenario, so it should fail on other computers too.

[megameklog.txt](https://github.com/MegaMek/mekhq/files/5317496/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5317497/mekhqlog.txt)

**Comment by Windchild292** [comment]
The logs are to speed up development and make it easier for us to track down the location.
Unit selector bug, I'll handle it later today

**Comment by Windchild292** [comment]
Fix opened for the MekHQ bug, the MegaMek side I cannot recreate nor find an error for but suspect it might be related to preferences. I did find two other minor bugs, which I will fix now.
