### ISSUE TITLE
Artillery Crews hired using "hire full compliment" automatically get artillery skill

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#210]
Can we get a change so that if you have the "use separate artillery skill" option enabled in the campaign option, any vehicles crews hired for an artillery unit with "hire full complement" automatically get that skill?

**Comment by pheonixstorm** [comment]
I don't think this would be too difficult to add, though it might not happen till after stable. Might want to ask ralgith in the slack channel.

**Comment by neoancient** [comment]
If memory serves, only a single crew member (other than the driver) is required to have the artillery skill. The other gunners presumably help reload or fire defensive weapons. I would say that a random number of the crew should have the skill, with the minimum being the number of artillery pieces (usually one) up to a maximum of all the gunners.

**Comment by mkerensky** [comment]
Would that cause the artillery skill to be averaged with a bunch of 0s for the overall vehicle crew skill if only one member had it?

**Comment by mkerensky** [comment]
Also on this topic, it would be nice to have the same feature available to hire infantry with the antimek skill.

**Comment by neoancient** [comment]
When HQ generates the aggregate Crew object used by MM, the artillery rating is determined by the gunner with the best rank, and all others are ignored. This is unlike gunnery, which uses the average of all the gunners.
