### ISSUE TITLE
Edge Point Usage For Support Personnel

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/mekhq#211]
Asking for a feature to allow support personnel to spend accumulated edge points on their specific activities like on a failed repair roll that would destroy a part, failed healing checks, failed acquisition checks, etc.

[BWCPNX.zip](https://github.com/MegaMek/mekhq/files/549502/BWCPNX.zip)

**Comment by mkerensky** [comment]
I've got this one.

**Comment by NickAragua** [comment]
I believe this has been implemented.
