### ISSUE TITLE
Include temperature indicator in scenario brief

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#2129]
Extreme temperature prevents deploying non-XCT infantry in MegaMek, but the scenario brief doesn't indicate if this condition is present.  For example, it may only indicate "Moderate snowfall", but not indicate the temperature is -50.  If this is known ahead of time, conventional infantry can be undeployed/not deployed from the scenario rather than manually removed in the MegaMek lobby or during deployment.

Please include a temperature indicator in the scenario brief, either the exact temperature or an indicator if it is outside what is considered 'normal' i.e. 
"Weather: Moderate Snowfall/Extreme Cold" or "Weather: Moderate Snowfall (-50C)"
"Weather: Clear/Extreme Heat" or "Weather: Clear (+45C)"

**Comment by Rewstyr** [comment]
Hasn't this been completed?
