### ISSUE TITLE
CO Rating not including heavy vehicles in tech count

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/mekhq#213]
Noticed this tonight that when pulling up the unit rating it was only counting light vehicles under tech support.

Light Vehicles Not Transported:           23
Heavy Vehicles Not Transported:           16

Tank Techs:       23 needed

Checked the code and sure enough  it was only calling getLightVeeCount()
Fix in PR #214

**Comment by dericpage** [comment]
This was already handled in my [more_detailed_unit_rating](https://github.com/MegaMek/mekhq/tree/feature/more_detailed_unit_rating) branch which I just merged this morning.

**Comment by mkerensky** [comment]
Is it possible that a similar code block would be causing my transportation rating to be slightly off?  I have another open ticket on that specific issue, and submission of my save file suggested that my small craft weren't being counted as properly transported even though they have bays.
