### ISSUE TITLE
Difficult to distinguish between “Deployed” and “Non-Deployed” forces in TO&E

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#2130]
### Environment

0.47.11

### Description

Compared to older MekHQ, in version 0.47.11, it is difficult to distinguish between “Deployed” and “Non-Deployed” forces in TO&E. Photo attached.

![image](https://user-images.githubusercontent.com/17064665/95431666-223fc300-0980-11eb-8ff8-d655dc8bdda9.png)

**Comment by Windchild292** [comment]
This is happening in certain themes only.
