### ISSUE TITLE
0.47.11 Bug - TO&E display error when mechwarrior change unit

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#2135]
### Environment

0.47.11

### Description

TO&E display error when mechwarrior change unit, see attached image. Also during this display error, the mouse scroll will not scroll properly.

To replicate
1. Load campaign
2. Go TO&E, HQ Groud Command, Command Lance
3. Pick anyone there, go to pilot, change unit
4. Go back to TO&E tab, you can see the display error

### Files

[SirMegaV25101103-1.cpnx.gz](https://github.com/MegaMek/mekhq/files/5358450/SirMegaV25101103-1.cpnx.gz)

![Untitled 1](https://user-images.githubusercontent.com/17064665/95645636-baaa8480-0af3-11eb-85bc-c3f2b7cc037a.png)
![Untitled 2](https://user-images.githubusercontent.com/17064665/95645637-bbdbb180-0af3-11eb-9752-621bcb6a90aa.png)

**Comment by Windchild292** [comment]
I will require your customs to continue.

Furthermore, I cannot recreate this on my testing campaign

**Comment by SirMegaV** [comment]
Forgot about the customs... attached.

[Customs - SirMegaV - Mechfiles.zip](https://github.com/MegaMek/mekhq/files/5394897/Customs.-.SirMegaV.-.Mechfiles.zip)

**Comment by Windchild292** [comment]
What Java version are you using?

**Comment by SirMegaV** [comment]
java version "1.8.0_161"

Actually I've been having this issue since a year or two ago, previous Java version too.

Also happening to tank units.

**Comment by Windchild292** [comment]
Please update your Java version to 11, as this might be due to an issue with EoL Java.

This can be done at https://adoptopenjdk.net/

**Comment by SirMegaV** [comment]
Updated to releasejdk-11.0.9+11.1 - HotSpot, simple test on another PC via
remote access seems OK. Will have a more comprehensive test when our
lockdown is over.



<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Windchild292** [comment]
Closing as a Java issue.
