### ISSUE TITLE
Bugged "Ally Status" screen

### ISSUE THREAD

**Issue by WalderFrey** [MegaMek/mekhq#2136]
### Environment
What version of MekHQ does your issue apply to?

0.46.1

What operating system are you using?  Windows, Mac, or Linux?

Windows 7

What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.

Java vendor Oracle Corporation Java version 10.0.1

### Description
I get a screen like the attached file frequently for the "ally status" that doesn't have the checkboxes on it to check if destroyed or not

### Files

[megameklog.txt](https://github.com/MegaMek/mekhq/files/5359826/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5359827/mekhqlog.txt)
![buggedallyscreen](https://user-images.githubusercontent.com/72669298/95663415-b5a20100-0b04-11eb-94bd-97011ebbe789.png)
[Company of Heroes30250228(postbattle).zip](https://github.com/MegaMek/mekhq/files/5359830/Company.of.Heroes30250228.postbattle.zip)
[customs.zip](https://github.com/MegaMek/mekhq/files/5359834/customs.zip)

**Comment by Windchild292** [comment]
This dialog has seen a significant amount of work since 46.1, with the screen in question removed. I would recommend upgrading to the latest dev release if this is a constant problem.
