### ISSUE TITLE
Bug: GM Tools Mothballing issue

### ISSUE THREAD

**Issue by MageOhki** [MegaMek/mekhq#2138]
### Environment
47.11 
Win 10
Latest Java 8

### Description
GM Tools, Mothball unit or mass mothball does not work.  In Command Center/daily log, says mothballing, but in Hanger, remains previous status
### Files
On request only (no one really wants a 400mb file, do they?)

**Comment by sixlettervariables** [comment]
Did you get any exceptions in your log?

**Comment by MageOhki** [comment]
Info and Warns, yes, but not involving mothballing/activating (which does work), at all.  Nothing *in* the log files at all.  If it's a campaign  issue...  
[customs.zip](https://github.com/MegaMek/mekhq/files/5360356/customs.zip)
[OHC4.zip](https://github.com/MegaMek/mekhq/files/5360357/OHC4.zip)

Update: at 1633 MDT, Windchild and I were discussing it, can confirm the bug

**Comment by Windchild292** [comment]
Introduced in #2082
