### ISSUE TITLE
47.11 Award Tracker Excel sheet query issue

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/mekhq#2139]
### Environment
47.11
Windows 10

### Description
In its as-downloaded state (uploaded here for ease of use), the Award Tracker Excel sheet will fail if used on a 47.11 campaign (or, I believe, campaigns from several previous versions, but in any case the fix is the same). 

Reproduction steps:
1. Download the supplied sheet and campaign file. 
2. Set up the file path and filename on the Settings sheet as usual.
3. Open the Queries and Connections viewer, then press Refresh All. 
4. Observe the error (see below)
![image](https://user-images.githubusercontent.com/59574316/95669053-fec87400-0b49-11eb-9f48-976f930a2385.png)
After hitting "OK", all queries except for "Units-Drivers" will complete, but the table will not update properly.
![image](https://user-images.githubusercontent.com/59574316/95669065-28819b00-0b4a-11eb-8f88-f9a79ab9387a.png)

A simple modification can fix this. Open the "Units-Drivers" query and delete the steps named "Expanded driverId" and "Renamed Columns1". Close and save the query, and after refreshing once more the data should load properly. 

### Files
[Coppercoats.cpnx.gz](https://github.com/MegaMek/mekhq/files/5360508/Coppercoats.cpnx.gz)
[AwardTracker.xlsx](https://github.com/MegaMek/mekhq/files/5360509/AwardTracker.xlsx)

**Comment by Windchild292** [comment]
This appears to only be happening on your campaign, not on any of my campaigns. All are from the same version, and if I use your changes it breaks the file.

Furthermore, the provided campaign is not in the correct format, with two VTOLs not being in the specified order. This breaks further queries.

**Comment by gsparks3** [comment]
Whoops, forgot about those VTOLs. They've never deployed anyway so I can just delete them from the TO&E. Updated campaign file attached. That does not seem to have been the issue, but it does look like the issue may be with my campaign rather than the Excel sheet. 

Further testing and/or re-testing:
1. Fresh copy of the Excel sheet from 47.11 vs [your older example campaign](https://github.com/MegaMek/mekhq/pull/1670#issuecomment-619376067), everything works perfectly.

2. Fresh copy of the Excel sheet from 47.11 vs [my adjusted campaign](https://github.com/MegaMek/mekhq/files/5388471/CoppercoatsAdjusted.cpnx.gz), breaks as described above.

3. Excel sheet modified as described above vs my adjusted campaign: _almost_ everything works perfectly. All companies and lances that actually exist in the TO&E are correctly loaded under the Coppercoats top-level battalion. However, there's also a few weird (blank)•(blank)•(blank)•(blank) entries on the bottom of the table. Not sure where those came from, doesn't really matter for my purposes since all the units I actually care about work properly. 

4. Excel sheet modified as described above vs your example campaign: breaks. That at least makes sense; the reason why the change was required in the first place is that my campaign save somehow has a different data structure, and the queries are "rigid", so if they don't match the data structure bad things happen. I thought maybe the data structures for the campaign saves had changed at some point, but if you've gotten this to work with more recently created campaigns, then probably the actual problem is with _my_ campaign file. Don't ask me how it wound up like that ...

For reference, after checking back, I've had this same issue (_with this specific campaign file_) since at least August 10th, the last time the award tracker sheet was updated. It's possible that the weird data structure in my campaign save existed even before that, but prior to that point I didn't have a handle on how to properly structure the TO&E to get it to work properly, so I wouldn't have noticed. 

If you've got a recently created campaign save that you've verified works, I'd call that good enough evidence that the problem is on my end, and you can close this. I actually spotted _another_ potential issue while testing this, but I think I want to verify that I can reproduce said issue on a different campaign before filing that as a report, given the level of weirdness going on with this campaign.

**Comment by Windchild292** [comment]
Tried again this morning, found out it occurs occasionally for reasons I cannot tell (likely Excel-side decision making). I've got a fix for it that I'll open soon.
