### ISSUE TITLE
REQ:  Astech standalone personnel Dropdown

### ISSUE THREAD

**Issue by MageOhki** [MegaMek/mekhq#2140]
### Environment
N/A
### Description
Request: Could we in Personnel Tab have a stand alone drop down (see red arrow below) for AsTechs?  In large games, sorting though *all* the support personnel is a bit of a pain.
![Request](https://user-images.githubusercontent.com/46218554/95777092-c11b3680-0c82-11eb-87d8-e06044da84f9.gif)

### Files
Not Needed

**Comment by Windchild292** [comment]
Already implemented as part of the MekHQ Option Use Individual Role Filters
