### ISSUE TITLE
[47.11-] Subcontract Offers Revert to Standard Contracts on Load

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/mekhq#2141]
When saving a game with subcontract offers present in the contract market, the subcontract offers revert to standard contracts when the game is loaded.

To reproduce: 
- Take a garrison contract
- Wait until subcontract offer is generated (to help simulate it, make the subcontract roll always result in a subcontract)
- Save game
- Quit
- Load game: subcontract offer will now be a standard contract

Should be reproducible with any AtB-enabled campaign.

**Comment by Windchild292** [comment]
We don't write parentContract to file.
