### ISSUE TITLE
0.47.1 mekhq save fail

### ISSUE THREAD

**Issue by cjfarls** [MegaMek/mekhq#2145]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
What version of MekHQ does your issue apply to? 0.47.10
What operating system are you using?  Windows, Mac, or Linux? Windows
What java version are you using?  1.8.0_241

### Description
Won't save the game after my last battle/repairs/etc.  Pop-up box suggested I submit a bug report with the log file.  Have also attached the cpnx file renamed as a txt.
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5389521/mekhqlog.txt)
[Rupard's Roughriders 3034-01.txt](https://github.com/MegaMek/mekhq/files/5389531/Rupard.s.Roughriders.3034-01.txt)

**Comment by Windchild292** [comment]
Issue is a null toughness value for a bot force. Did you edit the OpFor in MegaMek?

**Comment by Windchild292** [comment]
Additionally, can I please get the MegaMeklog.txt file

**Comment by cjfarls** [comment]
Yes I did to make them a bit tougher....  I take it I shouldn't do that?

-Chris

________________________________

**Comment by Windchild292** [comment]
I'm just trying to track down the issue, and that is likely the origin.

**Comment by Windchild292** [comment]
I misread the version number. This is almost certainly the portraits bug, although in a different place than I've seen it before.
Please update to 0.47.11 and if this continues I'll take another look.
