### ISSUE TITLE
StratCon: Briefing Tab Not Finding Lances to Deploy

### ISSUE THREAD

**Issue by jschmetzer** [MegaMek/mekhq#2150]
### Environment
Java version 1.8.0_261
Platform Windows 10 10.0 (x86)
47.12 as of #2148 

### Description
Generated Contract to test Stratcon
Generated lance and assigned forces in TOE
Contract begins; get 'you have not deployed minimum forces'
No lances show in Briefing tab to deploy

### Files
[test_campaign_w_logs.zip](https://github.com/MegaMek/mekhq/files/5393751/test_campaign_w_logs.zip)

**Comment by NickAragua** [comment]
To be eligible to show up in the briefing tab, a lance needs at least three units in it (I think they also have to be ground units) - the test lance has just one Locust.
