### ISSUE TITLE
Enhancement: Add the SPA Clan Tech Knowledge to the "Spend XP > Special Abilities list"

### ISSUE THREAD

**Issue by molemanBT** [MegaMek/mekhq#2158]
As per title, makes perfect narrative sense that after earning say 20XP bumbling around inside a clan mech for a year a tech would gain the experience necessary to remove the clan tech penalty. Would make using Clan Mechs possible once you capture them (Currently Elite techs that function well on IS mechs are reliably breaking components on my clan mechs every month).

Ah, I've just seen I can manually add it using the campaign options, I assume it may have been left out deliberately as it's unofficial? If so, ignore this.

**Comment by Windchild292** [comment]
This is already a default SPA in all of our presets.
