### ISSUE TITLE
Vehicle Crew & LAM Pilot salaries resetting to zero in Personnel tab of Campaign Options

### ISSUE THREAD

**Issue by Felderburg** [MegaMek/mekhq#2188]
### Environment
This happens in 46.1 and 47.11
Windows
Java version 8 build 271 (build 1.8.0_271-b09)

### Description
In "Campaign Options" in the "Personnel" tab, there is an option to change salaries of the different types of personnel. The Vehicle Crew and LAM Pilot are at 0 by default. When I change them, either by typing a number or using the scroll arrows, and click "Confirm", they have returned to 0 the next time I open the Campaign Options. Other roles I have tested maintain whatever number I set it to.

### Files
This has happened in every campaign I have, including the ones packaged with the program, so I will not attach files unless requested.

**Comment by sixlettervariables** [comment]
Good catch, older CPNX files would not have the correct number of salary entries and that caused newer versions to not let you update the salaries.

**Comment by sixlettervariables** [comment]
This will land in the next dev snapshot.
