### ISSUE TITLE
Overview/Hangar Breakdown does not include support vehicles in count

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/mekhq#219]
Found this out while checking infantry tech counts. In the example campaign the breakdown only shows the 4 scorpion tanks but not the 4 J-37 support vehicles.

[Support Vee Test.zip](https://github.com/MegaMek/mekhq/files/565941/Support.Vee.Test.zip)

**Comment by dericpage** [comment]
When I load up that campaign it works as expected.  I see 4 Scorpion Light Tanks and 4 J-37 Ordinance Transports in the hanger tab.  In the report, I see the following:
    Light Vehicle Bays:          8 needed /   0 available

        Mechanics:                    8 needed /    0 available

Looks like its counting both sets of vehicles.  Is there a different part of the report you're thinking is off?

**Comment by pheonixstorm** [comment]
Not the correct section. This is a different bug not related to the unit rating.
![hangarbreakdowntab](https://cloud.githubusercontent.com/assets/1787879/19943534/3a969980-a10e-11e6-92f9-2f2074e16ef3.png)

**Comment by Dylan-M** [comment]
Just needs a category added for Support Vehicles. They shouldn't be included there with combat vehicles. That would be like adding conventional fighters to ASF.

**Comment by Windchild292** [comment]
I'm going to add this with some future proofing, but it will just ensure that we don't have any missing units in the Hangar tab.

**Comment by NickAragua** [comment]
Four years later, this is fixed.
