### ISSUE TITLE
[47.11]: Unit Market: Units Reset to Open Market upon load 

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/mekhq#2193]
Take on a garrison contract. Go to planet, start contract.
If you're a dev, cheat and modify the "check for subcontract" roll so you are guaranteed to get a subcontract. 
Cycle days until the next month rolls around.
Now you've got a subcontract.

Save the game.

Load the game.
Subcontract is no longer listed as subcontract, but, rather as a regular full contract.

**Comment by NickAragua** [comment]
As a note, we also appear to be resetting the unit market for all on-sale units in the Unit Market to "Open Market" from whatever it was before the save.

**Comment by Windchild292** [comment]
The first bit is #2141, the second is a new bug on my end. I'll fix the second as part of this story.

**Comment by NickAragua** [comment]
lol I can't believe I actually entered that already. Guess I'm starting to go senile.

**Comment by Windchild292** [comment]
Oh, the second bug is I forgot to add .name()... to it used toString() instead to save...
