### ISSUE TITLE
Classpath fix for MM/MML jar files broken by commit ec84325

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/mekhq#22]
Commit ec84325c8469e47c6394ffc2b0809a37bbed5b4d reverted the fix made in 6db68affcde2764644d02a8b712cb653b05c1ae9

**Comment by Dylan-M** [comment]
Bah, I forgot to add it to .gitignore like I had planned on lol

I'll fix it shortly.

**Comment by pheonixstorm** [comment]
And after that big fuss you made too :speak_no_evil:

**Comment by Dylan-M** [comment]
Fixed in e870e94.
