### ISSUE TITLE
NPE when updating unit rating and infantry have no troopers

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/mekhq#220]
Setting up a test campaign for a followup to #215 and went to check if the rating overview was showing how many tech were needed but instead the Unit rating page (menu option) would not display. Instead I got several NPEs in the log about

> CampaignOpsReputation.updateTotalSkill()

[infantry techs.txt](https://github.com/MegaMek/mekhq/files/566040/infantry.techs.txt)
[rating npe.zip](https://github.com/MegaMek/mekhq/files/566099/rating.npe.zip)

**Comment by dericpage** [comment]
Do you have the campaign you were using for testing?  The spot in the code where you got the error suggests that an Infantry entity was passed in to the method but that entity had no crew.  Sounds like you might have an Infantry unit in your campaign with no troopers assigned to it.

**Comment by pheonixstorm** [comment]
rating npe.zip is the campaign I started for testing.

**Comment by dericpage** [comment]
Yep, that campaign has a bunch of infantry platoons without any troopers in them.  I'll get a fix in for that sometime tomorrow.

**Comment by dericpage** [comment]
Change has been merged and should be fixed with the next release.
