### ISSUE TITLE
RFE: Add Addition Personnel Groupings and Customize Rank Grouping by All Groupings

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/mekhq#2205]
This RFE calls for the implementation of expanded groupings and a way to customize the rank setup by personnel role groupings.

As of time of writing, I can think of the following personnel groupings split by three greater grouping of combat, support, and civilian.

For Combat, the groupings are: MechWarrior, Aerospace, Vehicle Crew, Naval, Infantry
For Support, the groupings are: Tech, Medicae, Administrator
For Civilians, the current grouping is Dependent

This subsumes #793, but that issue should be referred to for further information and opinions on the topic in question.

**Comment by Felderburg** [comment]
I'm a fan of all the rank RFEs you've added. I'd just like to make sure that each role can still have its own set of ranks; even though some of my roles have essentially the same system, I have all the recruits named by their role (tech recruit, MW recruit, etc.).

**Comment by MageOhki** [comment]
The problem I have here, is Naval ranks tend to *differ* from "ground" ranks, so this might want to be taken into account.
