### ISSUE TITLE
47.13 Stock save games STILL fail to load

### ISSUE THREAD

**Issue by servo01** [MegaMek/mekhq#2216]
47.13
Linux

Attempted to load last and stock saves with the new version and ran into the same campaign loading error popup detailed in #2213:

Fresh install with no modifications or alterations

"Load Last Save' From the boot screen or attempting to load the stock save games from the Campaign folder produce campaign loading error popup. Selecting 'Start New Campaign' loads without issue.

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5512393/mekhqlog.txt)

**Comment by sixlettervariables** [comment]
Different exception:
```
mekhq.campaign.personnel.Person.getLastRankChangeDateAsString(Person.java:1184)
```

**Comment by sixlettervariables** [comment]
That log file is incomplete, so I don't have an exception there to go from.

**Comment by sixlettervariables** [comment]
The CPNX given in #2213 works under the new release:

https://github.com/MegaMek/mekhq/issues/2213#issuecomment-723742582
