### ISSUE TITLE
[47.13] Save failed, NPE in Log

### ISSUE THREAD

**Issue by MalachiteKell** [MegaMek/mekhq#2217]
### Environment
MekHQ 47.13
Windows
Java OpenJDK 1.8.0_265

After loading a campaign from a previous version (30310211b), advanced a day, played one scenario, and was unable to save (30310212), with error https://imgur.com/a/nBlS0Gs. Advanced an additional day (30310213), attempted to save again, received the same error. Save files were generated and have been attached.
Recreation; Loading 30310211B, advancing one day, and attempting to save should generate the above error again.

### Files
[The White Wolf Squadron30310213.cpnx.gz](https://github.com/MegaMek/mekhq/files/5513112/The.White.Wolf.Squadron30310213.cpnx.gz)
[The White Wolf Squadron30310212.cpnx.gz](https://github.com/MegaMek/mekhq/files/5513113/The.White.Wolf.Squadron30310212.cpnx.gz)
[The White Wolf Squadron30310211b.cpnx.gz](https://github.com/MegaMek/mekhq/files/5513114/The.White.Wolf.Squadron30310211b.cpnx.gz)

[Customs.zip](https://github.com/MegaMek/mekhq/files/5513118/Customs.zip)

[megameklog.txt](https://github.com/MegaMek/mekhq/files/5513122/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5513123/mekhqlog.txt)

**Comment by sixlettervariables** [comment]
Tests covering this in #2224.
