### ISSUE TITLE
47.13 Cannot Refit

### ISSUE THREAD

**Issue by Flibjib** [MegaMek/mekhq#2219]
47.13
Cannot refit units, window fails to appear for refit kit selection.

[Cavaliere Ghiottone30550103.cpnx.gz](https://github.com/MegaMek/mekhq/files/5514405/Cavaliere.Ghiottone30550103.cpnx.gz)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/5514406/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5514407/mekhqlog.txt)

**Comment by sixlettervariables** [comment]
Should be handled by #2218, but I'll double check. Apologies for breaking these releases hard!

**Comment by sixlettervariables** [comment]
Tests covering this bug are in #2224.
