### ISSUE TITLE
RFE: Allow AtB Tactics rerolls of wind/fog conditions

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/mekhq#2228]
What it says in the title: In AtB campaigns, the Tactics skill rerolls allows for rerolling "Weather" conditions, but not Wind and Fog. Given the significant effects from e.g. Heavy Fog or a F4 Tornado, it would be nice to be able to use rerolls for those as well.

**Comment by NickAragua** [comment]
That checkbox rerolls all three.
