### ISSUE TITLE
Mass Repair assigns techs working maintenance to long jobs

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#223]
Not a bug, but the mass repair tool should include some sort of option to account for the amount of time a tech has to complete a repair. In my test case, it assigned a tech who had only 15 minutes per day left after completing unit maintenance to a 900+ minute limb replacement because they were the most skilled. This will cause it to take days to complete when choosing a slightly less skilled tech would complete the repair in 2 days.

I'm thinking some sort of "Max days to complete" setting added to the dialog window perhaps. This should probably be able to go fairly high, since aero repairs take a very long time.

**Comment by Dylan-M** [comment]
Not sure if "Max Days to Complete" is the way to go, maybe just have an option to "Seek personnel with least maintenance hours" or something.

**Comment by mkerensky** [comment]
Seems like you'd want to be sure to assign your least-skilled techs to maintenance and free up more repair time on your highly-skilled techs when gearing up to use this feature...

**Comment by Dylan-M** [comment]
Umm... never. Skilled techs have to do maintenance, because less skilled techs destroy your units.

**Comment by mkerensky** [comment]
Ah, right.  I don't use maintenance rolls (mainly because you're right, and after the first week half my unit was down, and after two I had nothing I could deploy), so forgot about that.

**Comment by kipstafoo** [comment]
How about just a checkbox and spinner in the main settings for MRMS (not in the specific items). The checkbox will allow you to turn on 'Limit number of days for a repair' and the spinner will have numbers from 1 to 14.

If you want to turn on the limiter, knock yourself out. If you don't, then let the system have fun figuring out which tech to use.

Right now the system is hard-coded to sort techs first by ascending skill level then by ascending XP available in an effort to skill up the least skill techs first. I will be adding the ability to choose how the techlist is sorted, so this may alleviate some of the above conditions, until you get down to just only a few techs available.

**Comment by molemanBT** [comment]
If I may, a way to see which Tech is doing the job and the ability to remove them from a job would be good. 

Once had a repair occur over the time span of a retirement roll, the tech retired and so the work just never got done, and I didn't spot it for a week or so, until I GM fixed it.

**Comment by kipstafoo** [comment]
Seeing what techs do what rolls somewhat defeats the purpose of MRM, in my opinion, as it's meant to be a one (or two) click operation.

As for the retirement roll scenario, I'm not sure how that's related to MRMS. That sounds like a bug related to the general tech system as the MRMS simply using the core repair code. You should file that as a new issue.

**Comment by purpledragon2** [comment]
I'm sorry, I'm confused.  I try to keep up with the conversations in the MHQ and MM developments in case I have an idea I think might be useful.  Anyway, I am not sure what MRMs have to do with this post.  As I understand MRM to mean Medium Ranged Missiles.  I'm sure the S is supposed to be something, but I have not seen it referenced.  I know we are talking about Mass Repair, but I have no idea what the second M or the S could stand for.

**Comment by HammerGS** [comment]
MRMS = Mass Repair Mass Salvage

**Comment by molemanBT** [comment]
Would being able to remove a tech from a job help with this? If you spot a guy who's going to take 15 days to finish a job, removing him and giving the job to someone else would sort this.

**Comment by HammerGS** [comment]
Closing per Slack comment from Kispstafoo. 

Already done as you can tell it to prioritize repairs to complete that day and, afair, if it will go over it'll use the tech with the most time left.
