### ISSUE TITLE
47.14 NPE on AtB turret deployment with no buildings

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/mekhq#2233]
### Environment
47.14
Windows 10
Java 11.0.8

### Description
Depending on campaign settings, it is possible for AtB opfor rolls to generate "Local Forces" that include turrets. These are always generated for a fight in some level of Urban terrain by default, so buildings exist for them to be placed into. However, Tactics rerolls can change the terrain to one with no buildings. If this occurs, the bot will experience a NPE during deployment due to there being no buildings to place the turrets into. 

Reproduction steps: 
1. Load the supplied campaign and navigate to the Briefing Room panel. Note that the Pending scenario has Local Forces containing turrets and is set in Light Urban (Town-wooded) terrain. 
2. Use a Tactics reroll to alter the terrain type. Very often this will change the Map to a type that does not have buildings. If it does not, reroll again (you may need to quit and reload for more rerolls if it is uncooperative, but in my testing it was relatively common). 
3. Start Game and begin deploying units; the NPE occurs when Princess attempts to deploy a turret. 

### Files
[AtB_TurretDeploymentNPE.cpnx.gz](https://github.com/MegaMek/mekhq/files/5551274/AtB_TurretDeploymentNPE.cpnx.gz)
No custom units or other files. 
No errors in mekhqlog.txt, multiple errors in megameklog.txt.
[megameklog.txt](https://github.com/MegaMek/mekhq/files/5551281/megameklog.txt)

**Comment by NickAragua** [comment]
Fixed with megamek PR #2474
