### ISSUE TITLE
Cannot assign anti-personnel weapon to BA if one (or more?) are destroyed

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#2242]
Fielding a squad of Achileus Light Battle Armor (WoB) [TAG] in a 47.14 MekHQ campaign, I noticed the anti-personnel mount is empty.  So after the MegMek session closed (with one trooper killed, so 5 out of 6 suits) I tried to use the MegaMek Lab panel to mount a weapon there.  While the weapon can be selected and added to the mount, and the design is well under weight, the "Begin Refit" button is disabled.  I tried with another squad which had all members, and it was working.

**Comment by sixlettervariables** [comment]
We'll need a campaign for this as refit bugs are notoriously complex.

**Comment by Windchild292** [comment]
Closing as no information provided after nearly a year.
