### ISSUE TITLE
Enhancement: do not keep around spare AmmoBins

### ISSUE THREAD

**Issue by sixlettervariables** [MegaMek/mekhq#2243]
Since `AmmoBin`s are free and we recreate them as necessary all over MHQ, I propose we no longer keep spare bins in the warehouse. This would simplify some of the odd logic we have spread throughout the program and would avoid some of the ambiguities and inconsistencies between the types of bins w.r.t. spare bins.

This would be a somewhat major change, but one I don't think is unreasonable. You can't do anything with a spare ammo bin, except use it to replace a MissingAmmoBin. Even still, a clone of the AmmoBin is made and the old one is removed and not even re-used.

Are there any pro's to keeping them around as viable spare parts?

EDIT: I forgot to add that we have some "interesting" bugs when we detect compatible parts for ammo bins.

**Comment by SuperStucco** [comment]
Maybe... I've got a unit on a Guerrilla Warfare contract so parts availability is essentially nil.  I have one unit with a damaged (thankfully empty at the time) UAC 10 ammo bin.  Its not letting me get a replacement, except through GM tools.  Had another unit with a similarly damaged Light Gauss bin.


![Damaged ammo bin](https://user-images.githubusercontent.com/70451747/100804131-8d8a9c00-33e9-11eb-8eb3-fbbedb7afa9c.png)

The only way to handle this without GM-ing it is through salvage.  The new system would have to handle this e.g. pre-emptively salvage them for later use.

**Comment by sixlettervariables** [comment]
AmmoBins have availability equal to their ammo. But I agree that you should be able to fix them for free, even if you can't buy the ammo.

Out of curiosity, can you switch the ammo types on a missing bin?

**Comment by SuperStucco** [comment]
No, I can't swap ammo on a damaged bin.  The right-click context menu only shows two of the three bins.

**Comment by sixlettervariables** [comment]
I'll see about adding changing munitions for missing bins so you can replace them.

**Comment by sixlettervariables** [comment]
This was much simpler to implement.

@SuperStucco you'll be able to, for free, replace a missing bin for any ammo type. You just won't be able to re-load it (but you could then change the munition type).

**Comment by SuperStucco** [comment]
Much obliged.  Looking forward to all the fixes and critical updates in the next stable release.
