### ISSUE TITLE
IS Techs have Clan Knowledge quirk before Invasion

### ISSUE THREAD

**Issue by Kendricke** [MegaMek/mekhq#2246]
Mech Tech available for hire with "Clan Tech Knowledge" quirk in year 3024. 

![image](https://user-images.githubusercontent.com/24977517/100576054-28706280-3292-11eb-91e5-84189f51fea7.png)

**Comment by Windchild292** [comment]
We do not track dates for SPA introduction, and thus this is an enhancement.

**Comment by repligator** [comment]
Clan Tech Knowledge is no longer present in MHQ (see https://github.com/MegaMek/mekhq/pull/4863 ), rendering this issue moot. Closing.
