### ISSUE TITLE
Mass Repair auto scrap & replace impossible to repair parts

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#225]
I'd like to request that the option to automatically scrap and replace parts that are damaged and impossible to repair from a failed repair roll be added to the mass repair tool.

**Comment by BLOODWOLF333** [comment]
I just had a ding-bat tech fail and destroy the LT on my marauder.  I remember you said before @kipstafoo that you would need a cpnx to test your code on.  Here you go.

0.41.25
[Impossible.zip](https://github.com/MegaMek/mekhq/files/574159/Impossible.zip)

**Comment by Kendricke** [comment]
I didn't realize for a couple of weeks in-game that one of the mechs needing mass repair had an impossible to repair arm.  Sure, that's on me, but it would have greatly helpful if the techs could have handled that without my personal divine intervention.

**Comment by kipstafoo** [comment]
MRMS was just completely overhauled (i.e., checked in yesterday). This was in before, but it wasn't working properly. It should be now.
