### ISSUE TITLE
Bug: Cannot swap ammo types in bins

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#2267]
Bit of a weird one here: the right-click context menu in 47.14 is insisting the ammo bins are loaded with the alternate ammunition that I select, but the various displays (TO&E, Hangar, Repair Bay) only show the original load.  When the unit is loaded into a scenario its loaded with the original load.  I can't swap ammunition types for any of the units, or any of the weapon types.

I've tried GM adding other units and ammunition types, and they won't change out either.

![No ammo swap](https://user-images.githubusercontent.com/70451747/101268583-c300f380-3721-11eb-82f7-ccf509b1a37a.png)

[Brilliant Light III-Gamma30730223.cpnx.gz](https://github.com/MegaMek/mekhq/files/5648102/Brilliant.Light.III-Gamma30730223.cpnx.gz)

**Comment by sixlettervariables** [comment]
Sometimes the Entity gets out of sync with the AmmoBin. Does a save/reload fix this?

**Comment by sixlettervariables** [comment]
Also, loading a bin will persist the ammo type to the underlying Entity (used by MM).

**Comment by SuperStucco** [comment]
> Sometimes the Entity gets out of sync with the AmmoBin. Does a save/reload fix this?

Oh yeah, the old "Turn it off and back on again" is one of the first tools pulled out of the toolkit.  No dice on that.
