### ISSUE TITLE
[dev] - unable to reload half MG ammo bin with MG ammo

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/mekhq#2268]
Go to the repair bay and try to reload the Exterminator. 

[customs.zip](https://github.com/MegaMek/mekhq/files/5660150/customs.zip)

**Comment by sixlettervariables** [comment]
I believe I saw this and fixed it in my PR and will confirm.

**Comment by sixlettervariables** [comment]
Okay, yes this is because AmmoType.T_MG is not listed in MegaMek as an ammo type where you could swap with another compatible type.

**Comment by sixlettervariables** [comment]
Second half of the fix will be in MHQ.
