### ISSUE TITLE
Can't select bombs for LAM bomb bays 0.47.14

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/mekhq#2276]
### Environment
MekHQ 0.47.14, Win10

### Description
I have a pair of LAMs in my hangar with internal bomb bays.  MekHQ won't let me select bombs for them.

Perhaps this is related to this bug?  https://github.com/MegaMek/megamek/issues/2501

**Comment by sixlettervariables** [comment]
I'm unable to reproduce as of #2229, I added a WSP-100, filled my warehouse with random bombs, and then assigned them to the LAM:
![image](https://user-images.githubusercontent.com/8238690/102002335-7c833a00-3cc9-11eb-9d9b-b15c20e3f040.png)
I was able to un-assign/change them out without any issue.
