### ISSUE TITLE
Campaign Ops Unit Rating -- Heavy Vee Bays Affecting Display of Light Vee Bays

### ISSUE THREAD

**Issue by dericpage** [MegaMek/mekhq#228]
If a unit has no dropships but does have heavy vehicles, it can cause the display of the light vehicle bays to show as negative.  In general, the unit rating report needs to better indicate how heavy vee bays can be used for storing light vees while still displaying the actual number of light vee bays.

**Comment by Dylan-M** [comment]
@dericpage Look at how I handled it for the Overview tab. I think that works correctly.

**Comment by dericpage** [comment]
Yeah, I see how that works pretty clear.  Unfortunately, it doesn't fit the format I've got going with the unit ratings (though a consistency argument can be made for changing that).  What I'm thinking of going with is something like:
`Transportation:      10
    Mech Bays:                   0 needed /  12 available
    Fighter Bays:                0 needed /   0 available
    Small Craft Bays:            0 needed /   0 available
    Protomech Bays:              0 needed /   0 available
    Heavy Vehicle Bays:          4 needed /  12 available
    Light Vehicle Bays:          4 needed /   8 available (0 light + 8 excess heavy)
    BA Bays:                     0 needed /   0 available
    Infantry Bays:               0 needed /   3 available
    Docking Collars:             1 needed /   0 available
    Has Jumpships?              No
    Has Warships?               No`

**Comment by Dylan-M** [comment]
I'm good with that, also feel free to adjust Overview to match if you want heh

**Comment by dericpage** [comment]
Changes merged.  This should be fixed with the next release.
