### ISSUE TITLE
47.15 Contracts Cannot Be Generated

### ISSUE THREAD

**Issue by jschmetzer** [MegaMek/mekhq#2283]
### Environment
47.15
Java version 1.8.0_251
Platform Mac OS X 10.16 (x86_64)
Total memory available to MegaMek: 1,864,192 kB

Fresh campaign, 3030, on Galatea, stock AtB Default campaign presets.

1. No contracts available on campaign first load.
2. GM Generate yields error: Unable to GM-generate contract from the current location. Increase contract search radius or travel to a border world for better odds of success.
3. Log shows recurrent: WARN [mekhq.campaign.market.ContractMarket] {AWT-EventQueue-0} 
generateAtBContract(), line 323 : Could not generate an AtB Contract because we ran out of retries!

[contract_gen_fail.zip](https://github.com/MegaMek/mekhq/files/5684805/contract_gen_fail.zip)
cpnx, logs attached

**Comment by NickAragua** [comment]
Confirmed, I've encountered this as well in my campaign.

**Comment by sixlettervariables** [comment]
Were there other warnings? Usually it spits out a Why it had to retry.

**Comment by NickAragua** [comment]
Nope, nothing else.

**Comment by sixlettervariables** [comment]
FFS: https://github.com/MegaMek/mekhq/blob/3d6f5a5c9539967bee6ffd9b8ffa0f18dc5ec54f/MekHQ/src/mekhq/campaign/market/ContractMarket.java#L301-L302

If you pass 0, you get 0.

**Comment by NickAragua** [comment]
Heh, doesn't leave much room for a workaround.

**Comment by sixlettervariables** [comment]
Yeah didn't see this bug in my last push to fix before RC1.
