### ISSUE TITLE
Request: Add Bondsmen to Prisoners list, or allow them to be sorted separately

### ISSUE THREAD

**Issue by BowtieBob** [MegaMek/mekhq#2287]
At the moment, the only way I've found to see my bondsmen is to list all personnel, then sort by rank.  I would think the Bondsmen should be in the Prisoners list, but otherwise, it would be helpful for them to have their own category for sorting purposes.

mekhq-windows-0.46.1

**Comment by Windchild292** [comment]
Bondsmen are properly included in the prisoners sort, with prisoners having undergone a rework since 0.46.1

**Comment by BowtieBob** [comment]
I just tried it on 0.47.14, but it isn't showing the Bondsmen as Prisoners for me.

![image](https://user-images.githubusercontent.com/70545594/102128566-afd1e000-3e13-11eb-855f-317e32e0f56e.png)
![image](https://user-images.githubusercontent.com/70545594/102128627-c24c1980-3e13-11eb-8402-1f1247f2fe77.png)

**Comment by Windchild292** [comment]
Feth, missed it in the rework. Opened up a PR to fix that bug.
