### ISSUE TITLE
Can't reload DropShip ammo in 47.15

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#2296]
In the attached campaign file, the DropShip ammo bins are at zero (even though they were previously at least partially full), and cannot be reloaded.  Using GM Restore doesn't change this either.

[Brilliant Light III-Gamma30730715.cpnx.gz](https://github.com/MegaMek/mekhq/files/5718383/Brilliant.Light.III-Gamma30730715.cpnx.gz)

Edit: whoops, custom BA:
[Custom BA.zip](https://github.com/MegaMek/mekhq/files/5718420/Custom.BA.zip)

**Comment by sixlettervariables** [comment]
Missing customs:
```
17:41:52,747 ERROR [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
checkUnits(), line 1193 : Could not load the following units: 
Longinus BA Level I [Gauss]
IS Standard BA Level I [SL]
Achileus BA Level I [Flamer]
```

**Comment by sixlettervariables** [comment]
I'm not currently able to reproduce on my campaigns, but that doesn't mean there isn't a problem.

**Comment by SuperStucco** [comment]
Sorry 'bout the missing BA - they're normal, just with a different name since the MUL-generated chassis/model names twist my head around too many times.

The game was first generated in 47.14, where there were several bits of weirdness e.g. insisting the bins needed to be unloaded in the Repair Bay.  I hope it's not an inherited issue that needs to be cleared up by starting from scratch.

**Comment by sixlettervariables** [comment]
Which dropships have no ammo? I don't see any needing to be reloaded.

**Comment by sixlettervariables** [comment]
oh I see the entities themselves are showing no ammo bays.

**Comment by sixlettervariables** [comment]
Adding a new dropship does not appear to have that issue, but that's on the latest. I'll try looking into the cause this weekend on 0.47.15 and see why.

**Comment by SuperStucco** [comment]
While you're in there, check the Union-X (3065) data.  There's 7.5 tons of Gauss ammo and 13.5 tons of LRM 20 ammo in the nose.  As far as I can tell, half-tons of ammo aren't valid in standard rules.

**Comment by sixlettervariables** [comment]
Do you have a copy of that Campaign from 0.47.14?

**Comment by sixlettervariables** [comment]
Investigating another campaign, I found the cause of this.
https://github.com/MegaMek/mekhq/issues/2299#issuecomment-748675578

**Comment by sixlettervariables** [comment]
If you have a save from 0.47.14 I can fix it for you (basically replacing `<capacity>` with `<size>` and `</capacity>` with `</size>`). Just attach it to this issue.
