### ISSUE TITLE
47.15 Infinite loop after hitting Start Mass Repair/Salvage?

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/mekhq#2297]
### Environment
47.15
Windows 10
Java version 11.0.8

### Description
MekHQ locked up after hitting "Select Active Units" and "Start Mass Repair/Salvage". Buttons in said menu are no longer responding, but program overall is _not_ listed as Not Responding. CPU usage is moderate and fluctuating, but continuous. Immediately prior to this I had completed a scenario and disbanded a few infantry units I wasn't using. 

Screenshot as of bug: 
![image](https://user-images.githubusercontent.com/59574316/102697959-0cfcd580-4208-11eb-8974-3d7c99cb57fa.png)

### Files
Error in mekhqlog, but I'm not certain if it has anything to do with the issue. Didn't see anything in megameklog.

[megameklog.txt](https://github.com/MegaMek/mekhq/files/5720049/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5720050/mekhqlog.txt)

Will edit to add campaign save file and reproduction steps if I can get it to reproduce after force-quitting. Annoyingly, I don't have a save immediately prior to the error - might have to redo the scenario as well.

**Comment by gsparks3** [comment]
Okay, loading from the save and trying to Mass Repair _before_ completing the scenario had no issues, but after completing the scenario again (and saving before testing further) I can now consistently reproduce the issue. Not sure why it changed exactly, but debug tools should tell you more.

Save: 
[Coppercoats.cpnx.gz](https://github.com/MegaMek/mekhq/files/5720109/Coppercoats.cpnx.gz)
No custom units. 

Reproduction steps:
1. Load campaign file
2. Navigate to Repair Bay and open Mass Repair/Salvage menu
3. Click Select Active Units
4. Click Start Mass Repair/Salvage

**Comment by sixlettervariables** [comment]
Error from the log:
```
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index -3 out of bounds for length 50
	at megamek.client.ui.swing.widget.InfantryMapSet.setEntity(InfantryMapSet.java:83)
	at megamek.client.ui.swing.unitDisplay.ArmorPanel.displayMech(ArmorPanel.java:256)
	at megamek.client.ui.swing.unitDisplay.UnitDisplay.displayEntity(UnitDisplay.java:313)
	at megamek.client.ui.swing.ReportDisplay.hyperlinkUpdate(ReportDisplay.java:315)
	at java.desktop/javax.swing.JEditorPane.fireHyperlinkUpdate(JEditorPane.java:345)
```

**Comment by sixlettervariables** [comment]
The infinite loop is in the conversion from LRM 15 ammo to LRM 5 ammo. The warehouse has enough shots but the load bin routine believes there is not enough. Investigating the correct fix now.
