### ISSUE TITLE
Remember last campaign save dir

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/mekhq#230]
It would be great if MHQ remembered what the last directory used to save/load campaign files was. I have an external dir that I attach to my google drive. I could symlink it to the 'campaigns' directory within the install but I prefer to keep it external. MHQ automatically looks in the 'campaigns' dir every time, but I think it would be good if we simply looked at the last used dir.

**Comment by pheonixstorm** [comment]
Someone had a feature like this in their fork I think, but nice idea, would love to keep my campaigns and other assorted data on my network drive so I don't have to keep copying everything over each time I do a custom or use the release/daily builds

**Comment by VicenteCartas** [comment]
This was fixed by PR #1084
