### ISSUE TITLE
Ammo reloading problem in 0.47.15

### ISSUE THREAD

**Issue by mjbroekman** [MegaMek/mekhq#2307]
### Environment
What version of MekHQ does your issue apply to?  0.47.15

What operating system are you using?  Windows, Mac, or Linux?  Mac
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.
15.0.1

### Description
Describe the issue and provide screenshots ingame if able.
SRM4 and SRM2 reloads never complete with both manual and mass repair. SRM2 ammo bins always leave 2 shots unloaded. SRM4 ammo bins always leave 1 shot unloaded.

![Screen Shot 2020-12-21 at 5 16 47 PM](https://user-images.githubusercontent.com/5141448/102827311-538d3400-43b0-11eb-9d59-c270733dcbb0.png)

And provide the steps you have taken to reproduce the issue in the campaign file if applicable.
If you scrap the ammo bin, replace the ammo, and have a tech reload an SRM2 or SRM4 ammo bin, it will only add 48 (for SRM2) or 24 (for SRM4) shots, leaving 2 or 1 respectively to be loaded. This results in techs spending their time infinitely attempting to reload those shots and not actually completing the repairs if Mass Repair / Salvage is being used.

### Files
Provide the .cpnx campaign file that this issue occurs in.
[Vidarion30331009.cpnx.gz](https://github.com/MegaMek/mekhq/files/5726795/Vidarion30331009.cpnx.gz)

And provide the megameklog.txt and mekhqlog.txt files for any NPE's or errors that MekHQ might be reporting.
[megameklog.txt](https://github.com/MegaMek/mekhq/files/5726801/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5726802/mekhqlog.txt)

**Comment by sixlettervariables** [comment]
I believe this was fixed, but I'll confirm with your specific campaign.

**Comment by sixlettervariables** [comment]
Infinite loop in MRMS fixed in https://github.com/MegaMek/mekhq/pull/2300

**Comment by sixlettervariables** [comment]
Yes this is fixed in the latest develop.
