### ISSUE TITLE
Captured mechwarriors from MegaMek all show up as male in MekHQ with no portrait

### ISSUE THREAD

**Issue by mjbroekman** [MegaMek/mekhq#2315]
### Environment
What version of MekHQ does your issue apply to? Occurs in both 0.47.14 and 0.47.15
What operating system are you using?  Windows, Mac, or Linux?       
   Platform Mac OS X 10.15.7 (x86_64)

What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.
        Java version 15.0.1

### Description
After combat in megamek, all captured personnel show up as prisoners.

Vehicle drivers and gunners are properly gendered and given an appropriate portrait, but mechwarriors are always Male and have no portrait despite their names.

I saw that 0.47.15 included the fix for ProtoMech pilots and thought that maybe it also fixed regular Mek pilots, but the portrait issue remains in 0.47.15.

I can assign portraits after the fact but randomized portraits do not work and they do not get set by MegaMek in the deployment screen or after combat.

#### Prisoner tab screenshots
![Screen Shot 2020-12-23 at 8 11 05 PM](https://user-images.githubusercontent.com/5141448/103047912-fe415600-455a-11eb-8d5b-6711e4261b85.png)

![Screen Shot 2020-12-23 at 8 10 23 PM](https://user-images.githubusercontent.com/5141448/103047878-e5d13b80-455a-11eb-8bab-b5d78bea9f2e.png)

### Files
Provide the .cpnx campaign file that this issue occurs in.
[Vidarion30350401.cpnx.gz](https://github.com/MegaMek/mekhq/files/5737656/Vidarion30350401.cpnx.gz)

And provide the megameklog.txt and mekhqlog.txt files for any NPE's or errors that MekHQ might be reporting.
[megameklog.txt](https://github.com/MegaMek/mekhq/files/5737652/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5737653/mekhqlog.txt)

**Comment by gsparks3** [comment]
The "everyone is male" bug has been fixed for the next build (see #2303). Less certain about the portrait issue.

**Comment by Windchild292** [comment]
I'll look at the portrait issue in the morrow, however gender has been fixed.

**Comment by Windchild292** [comment]
Portraits has been fixed in #2330
