### ISSUE TITLE
Feature Request (AtB): Track Bonus Hire rewards similar to Bonus Parts

### ISSUE THREAD

**Issue by mjbroekman** [MegaMek/mekhq#2316]
Currently, if a scenario reward results in bonus rolls, one of the possible rewards is a 'Bonus Hire'. However, if you don't immediately use it, there is no way to track how many of them you have once you advance the day and sometimes you don't need another mouth to feed right away.

Requested feature is to have the 'Bonus Hire' count tracked similar to the Bonus Parts and usable in the Hire Personnel screens as well as visible in the Personnel Breakdown overview.

**Comment by repligator** [comment]
Bonus Hires were removed in https://github.com/MegaMek/mekhq/pull/4931 . Closing as no longer applicable.
