### ISSUE TITLE
47.15 Simultaneous bonus part rolls not additive?

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/mekhq#2319]
### Environment
47.15
Windows 10
Java 11.0.8

### Description
In my current campaign, after a Big Battle: Civilian Riot, multiple bonus rolls occurred (1/surviving Loyalist unit, as usual). One of these rolls was 3 bonus parts; another was 2 bonus parts. I was under the impression that these bonuses normally stacked, i.e. I should have 5 total bonus parts. However, after using one Bonus Part to acquire a 300 Fusion Engine (75 tons), I noticed that I only had 2 bonus parts left, as if only the 3 bonus parts roll had been counted. Cause uncertain; my hypothesis is that the bonus effects "overlapped" rather than stacking, but I could be totally wrong.

All of the bonus rolls, and the acquisition of the fusion engine using a bonus part, are visible in the daily log of the supplied campaign file. Opening the Find Parts menu will show 2 Bonus Parts remaining (at least for me). 

### Files
[Coppercoats.cpnx.gz](https://github.com/MegaMek/mekhq/files/5741086/Coppercoats.cpnx.gz)
No custom units or other files.

**Comment by sixlettervariables** [comment]
I've been walking the code and can't really see how that occurred:
https://github.com/MegaMek/mekhq/blob/776aa1d1a9dc6b22856ad5a360da8eefb0d37f05/MekHQ/src/mekhq/campaign/mission/AtBContract.java#L673-L677
Unfortunately the campaign log supports your claim, but I can't reason through how it happens.

**Comment by gsparks3** [comment]
Wacky. Maybe `numBonusParts` was somehow at -2 from previous shenanigans. I know there was some weirdness there that got fixed in a previous release. Closing this for now.

**Comment by Windchild292** [comment]
That is actually possible. There was a bug that would allow bonus parts to end up in the negative
