### ISSUE TITLE
47.15 Campaign loading error

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/mekhq#2325]
### Environment
47.15
Windows 10
Java 11.0.8

### Description
Suddenly cannot load a campaign save file (or the corresponding campaign autosave), with error window as shown below. Cause uncertain. Save and logs attached. NPE in megameklog. Oddly, I don't remember doing anything with this particular save recently. 

![image](https://user-images.githubusercontent.com/59574316/103180127-de62a880-4860-11eb-8554-2e0f727fb96f.png)

### Files
No custom units or other files. 
[Coppercoats.cpnx.gz](https://github.com/MegaMek/mekhq/files/5745218/Coppercoats.cpnx.gz)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5745219/mekhqlog.txt)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/5745223/megameklog.txt)
[debug.log](https://github.com/MegaMek/mekhq/files/5745224/debug.log)

**Comment by sixlettervariables** [comment]
```

16:31:39,645 ERROR [mekhq.gui.dialog.DataLoadingDialog$Task] {AWT-EventQueue-0} 
done(), line 262 : null
java.lang.NullPointerException
	at mekhq.Utilities.unscrambleEquipmentNumbers(Utilities.java:1179)
	at mekhq.campaign.io.CampaignXmlParser.lambda$parse$0(CampaignXmlParser.java:420)
	at mekhq.campaign.Hangar.lambda$forEachUnit$0(Hangar.java:116)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at mekhq.campaign.Hangar.forEachUnit(Hangar.java:116)
	at mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:388)
	at mekhq.campaign.CampaignFactory.createCampaign(CampaignFactory.java:83)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:193)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:125)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by sixlettervariables** [comment]
Adding the appropriate defensive null check:
```
17:01:37,959 WARN [mekhq.campaign.parts.equipment.AmmoBin] {AWT-EventQueue-0} 
getMounted(), line 297 : Missing valid equipment for Half Machine Gun Ammo Bin to manage ammo on unit Heavy Tracked APC (Standard) #3
```

**Comment by sixlettervariables** [comment]
That unit has an extra ammo bin somehow tied to a non-existent piece of equipment:
```
17:22:23,476 INFO [mekhq.gui.adapter.UnitTableMouseAdapter$1] {AWT-EventQueue-0} 
actionPerformed(), line 1045 : Heavy Tracked APC (Standard) #3 (a6049b78-a351-4277-b5e1-81c7097cf9f1)
	29566: Vehicle Front
	29567: Armor (Standard)
	29568: Vehicle Stabiliser
	29569: Vehicle Right Side
	29570: Armor (Standard)
	29571: Vehicle Stabiliser
	29572: Vehicle Left Side
	29573: Armor (Standard)
	29574: Vehicle Stabiliser
	29575: Vehicle Rear
	29576: Armor (Standard)
	29577: Vehicle Stabiliser
	29579: Machine Gun (eq#1; Machine Gun)
	29580: Machine Gun (eq#0; Machine Gun)
	29582: Half Machine Gun Ammo Bin (eq#4; Half Machine Gun Ammo; missing!)
	29583: 100 ICE [Vehicle] Engine
	29584: Motive System
	29585: Vehicle Sensors
	30077: Half Machine Gun Ammo Bin (eq#2; Half Machine Gun Ammo)
```

**Comment by sixlettervariables** [comment]
After fixing the unscramble logic I get this:
```
17:44:01,565 INFO [mekhq.gui.adapter.UnitTableMouseAdapter$1] {AWT-EventQueue-0} 
actionPerformed(), line 1045 : Heavy Tracked APC (Standard) #3 (a6049b78-a351-4277-b5e1-81c7097cf9f1)
	29566: Vehicle Front
	29567: Armor (Standard)
	29568: Vehicle Stabiliser
	29569: Vehicle Right Side
	29570: Armor (Standard)
	29571: Vehicle Stabiliser
	29572: Vehicle Left Side
	29573: Armor (Standard)
	29574: Vehicle Stabiliser
	29575: Vehicle Rear
	29576: Armor (Standard)
	29577: Vehicle Stabiliser
	29579: Machine Gun (eq#1; Machine Gun)
	29580: Machine Gun (eq#0; Machine Gun)
	29582: Half Machine Gun Ammo Bin (eq#2; Half Machine Gun Ammo)
	29583: 100 ICE [Vehicle] Engine
	29584: Motive System
	29585: Vehicle Sensors
```
This leaves you with an unloaded bin, but otherwise resolves the issue. Any ideas what you were doing with that unit?

**Comment by sixlettervariables** [comment]
Manually resolved the equipment numbers for you:
[Coppercoats (3).cpnx.zip](https://github.com/MegaMek/mekhq/files/5745375/Coppercoats.3.cpnx.zip)

**Comment by gsparks3** [comment]
Not completely sure how the unit wound up like that, but I have a thought. IIRC, I got a Heavy Tracked APC of some non-standard type as a bonus reward, and had my unoccupied elite Engineer mechanic convert it to a Standard model via refit. Again IIRC, the refit was so short that it completed immediately (i.e. the same day, less than 480 minutes), and oddly, it didn't give a report of said customization finishing in the Daily Log. Something might have gotten messed up during the refit. I'll mess around a little and see if I can reproduce the issue on my end ... after making a fresh backup of the campaign save. 

Thanks for the fixed save. The best older copy I had was from way earlier, and I really didn't want to redo all I'd done in that campaign.

**Comment by gsparks3** [comment]
Okay, that reproduced quickly. GM added a Heavy Tracked APC (MG), had my mechanic work on it to convert it to a Heavy Tracked APC (Standard). This time the daily log showed "120 minutes remaining" after starting the refit. After advancing to the next day, not only did the daily log bug out a bit (continuing to display the previous day's log entries as well as the new day's entries), it did NOT give any log report for completion of the refit, even though the unit was visibly converted in the Hangar - same as what I remember before. On saving the campaign file and attempting to reload, it bugged out again as it did previously. Save attached in case it's relevant, although you should be able to reproduce this yourself fairly easily ... hopefully. Never know with some of these bugs. 

[CoppercoatsCopy.cpnx.gz](https://github.com/MegaMek/mekhq/files/5745597/CoppercoatsCopy.cpnx.gz)

**Comment by sixlettervariables** [comment]
I'll check on that tomorrow if I have time, thank you for the reproduction!
