### ISSUE TITLE
RFE: Auto-hire Astechs/Medics

### ISSUE THREAD

**Issue by jschmetzer** [MegaMek/mekhq#2333]
Request a setting checkbox that would activate an auto-hire astechs and medics for technicians and doctors in AtB games for large units.

**Comment by NickAragua** [comment]
Good news, you can do that already: marketplace -> astech/medic pool -> bring all tech/medical teams to full strength. Automatically hires enough temp astechs/medics to fill out all such crews.

**Comment by jschmetzer** [comment]
I was unclear, my bad; I meant an option that have that manual action happen automatically every time I hire or fire a tech. So I don't have to keep going back every time.

**Comment by Windchild292** [comment]
There is now a MekHQ option to automatically fill the pool on a new day, which I believe covers this.
