### ISSUE TITLE
Feature Request: Option to set starting mode for LAMs

### ISSUE THREAD

**Issue by BowtieBob** [MegaMek/mekhq#2336]
I recently fought a scenario with only a pair of LAMs and I kept dying in the first round because in order to convert to airmech mode, I had to stand still for an entire turn.  My start point was close enough to the enemy start that they could easily get to me before I could take off.  It would be nice if there was an option to set the starting mode for a LAM so that they don't have to stand around for the entire first round.

**Comment by neoancient** [comment]
It's on the deployment tab of the configuration dialog in the MegaMek lounge.
![Screenshot from 2020-12-30 10-09-42](https://user-images.githubusercontent.com/16927464/103366134-6924ec80-4a87-11eb-8bcb-0ce617bc3aec.png)
