### ISSUE TITLE
47.15 Can repair internal structure on an arm with a damaged shoulder actuator

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/mekhq#2339]
### Environment
47.15
Windows 10
Java 11.0.8

### Description
I have a Phoenix Hawk with a damaged arm (with a damaged shoulder actuator), and unusually, the "Repair" option for the internal structure is _not_ grayed out. It does, however, warn me that I am attempting to repair or replace a component on an arm with a damaged shoulder actuator if I try to assign a tech to the repair task. This goes against the usual (and rules-compliant) behavior of disallowing repair of the internal structure of a limb with a damaged shoulder or hip actuator. 

![image](https://user-images.githubusercontent.com/59574316/103467740-0ef28880-4d20-11eb-8c5a-f075372cf89a.png)
![image](https://user-images.githubusercontent.com/59574316/103467749-216cc200-4d20-11eb-83ca-9a38a170f873.png)

### Files
[Coppercoats.cpnx.gz](https://github.com/MegaMek/mekhq/files/5760946/Coppercoats.cpnx.gz)
No custom units or other files.

**Comment by sixlettervariables** [comment]
The nag is for equipment but is being applied to the limb because it is only checking for a destroyed hip/shoulder to block repairs.

In my work for #2331 I have made it such that repairs are blocked for limbs with damaged hips or shoulders. This prevents you from eating time on meaningless repairs.

**Comment by sixlettervariables** [comment]
Using #2331 with some improvements to the repair details:
![image](https://user-images.githubusercontent.com/8238690/103485884-a363f600-4dc7-11eb-80e0-1b42c38457ff.png)

**Comment by SuperStucco** [comment]
I can think of certain circumstances where this could cause issues.  For example, in a contract with limited supplied e.g. guerrilla operations purchasing a whole new arm is out of the question, so its repair the arm/replace damaged parts and leave the shoulder buggered just to have _something_ that stands a chance of operating through the next scenario.  You need to remove everything to replace the arm later, but it's still better for the circumstances in the moment.

**Comment by sixlettervariables** [comment]
@SuperStucco did it actually work when you repaired the arm? It didn't appear to in my testing of `MekLocation`, made it sort of out of sync with its underlying location and crits.

**Comment by HammerGS** [comment]
To me that fits into the Jury-Rigging rules. Strat.Ops - pg 187

**Comment by SuperStucco** [comment]
> @SuperStucco did it actually work when you repaired the arm? It didn't appear to in my testing of `MekLocation`, made it sort of out of sync with its underlying location and crits.
> 
> However, I hear what you're saying and can revise #2331 to handle that as well.

Seemed to work - I was able to replace equipment and the displayed IS value was updated.  The shoulder was still buggered, as expected.



> To me that fits into the Jury-Rigging rules. Strat.Ops - pg 187

I can see that being the case for the IS and shoulder, not necessarily for the other actuators/equipment/weapons.  Which brings up another point - what about omni-pod swapping in an arm with a damaged shoulder?
