### ISSUE TITLE
Use consistent weather conditions when generating scenarios

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#2340]
Some weather conditions such as 'Sleet' include others, such as 'Moderate Gale' for wind, 'Ice', and 'Extreme temperature (-40)'.  Scenarios can generate with conflicting wind conditions i.e.

`Wind direction is Northeast.  Wind strength is Calm.  The weather is Sleet.  Visibility is Daylight.`

Conditions should not be both 'Sleet' for weather and 'Calm' for wind strength.

**Comment by purpledragon2** [comment]
Sleet with calm winds happens fairly frequently in the midwestern U.S.  That's where you get the continuing ice build up storms that rend trees down the center.  However, I do believe that there should be a little more consistency of weather in battles where they happen on the same date or within a day of each other.

**Comment by SuperStucco** [comment]
Real life, yes - for example, I bet you have sleet conditions, wind or no, without -40 C temperatures.  Same with heavy snowfall occurring at warmer than -50 C.

But, the book has it (and certain other weather conditions) as specifically including a set of wind and temperature conditions.

**Comment by Windchild292** [comment]
This is invalid. AtB Scenarios generate weather as per AtB rules, as found near the bottom of the Battle Tab of the AtB rules included in our releases.
