### ISSUE TITLE
Reloading error for Stuka, Chippewa and Chapparral Artillery Tank

### ISSUE THREAD

**Issue by GentlemanGrunt** [MegaMek/mekhq#2341]
### Environment
Megamek 0.47.15, MegaMek HQ specifically. Windows 10. 64 bit Java for windows, ver 8, Update 271

### Description
Stukas, Chippewa and Chapparral Artillery tank have reloading issues in the Repair Bay. Attempts to reload the Stukas and Chippewa lead to action being completed according to rolls and script, but the task remains. 

![Error 4](https://user-images.githubusercontent.com/76921822/103489885-04de9180-4dd5-11eb-9f20-5421f8eebab1.jpg)
![Error 3](https://user-images.githubusercontent.com/76921822/103489886-05772800-4dd5-11eb-8179-508ebe25edb2.jpg)

Chapparral has issue loading Arrow IV and SRM 6, with it attempting to load their respective ammo type and then replacing each other. (Load Arrow IV and SRM 6 task shows up. Load SRM 6 and Arrow IV task shows up, replacing each other on the unit entry.)

![Error 2](https://user-images.githubusercontent.com/76921822/103489872-e5476900-4dd4-11eb-9a0d-1f7b25f16e0c.jpg)
![Error 1](https://user-images.githubusercontent.com/76921822/103489873-e5dfff80-4dd4-11eb-8e11-584bd921dca1.jpg)

Attempting to use GM Mode to restore unit just results in the game crashing. It does not go into a Not Responding state, but nothing can be clicked or changed. Attempting to resolve the task but unable to maybe?

From what I can tell though, when loaded up into Megamek, the unit still functions as normal with no ammo issues.

### Files
[Brothers30520612.cpnx.gz](https://github.com/MegaMek/megamek/files/5762341/Brothers30520612.cpnx.gz)

[mekhqlog.txt](https://github.com/MegaMek/megamek/files/5762342/mekhqlog.txt)

[megameklog.txt](https://github.com/MegaMek/mekhq/files/5762358/megameklog.txt)

Playername: Brothers

**Comment by GentlemanGrunt** [comment]
Added it in, thank you.

**Comment by sixlettervariables** [comment]
I have a hunch the underlying equipment is mismatched similar to https://github.com/MegaMek/mekhq/issues/2299#issuecomment-748640658

**Comment by sixlettervariables** [comment]
Yes, looks like a refit issue or some other (unexpected) problem:
```
14:50:05,080 WARN [mekhq.Utilities] {SwingWorker-pool-1-thread-1} 
unscrambleEquipmentNumbers(), line 1309 : Could not unscramble equipment for Chaparral Missile Artillery Tank (Standard) Mk II (59efb9ab-4402-4540-9310-be1e7a34773f)

 - SRM 6 Ammo equipmentNum: 7

Equipment Parts:
 0: Arrow IV Front Arrow IV 
 1: Medium Laser Right Medium Laser 
 2: Medium Laser Left Medium Laser 
 3: SRM 6 Rear SRM 6 
 8: Arrow IV Ammo Bin Body Arrow IV Ammo 
 5: Arrow IV Homing Ammo Bin Body Arrow IV Homing Ammo 
 7: Arrow IV Ammo Body Arrow IV Ammo 
 7: SRM 6 Ammo Body <Incorrect>  (Missing)
 4: Trailer Hitch Rear Trailer Hitch 
 6: Arrow IV Homing Ammo Bin Body Arrow IV Homing Ammo 

Equipment:
 0: Arrow IV Arrow IV
 1: Medium Laser Medium Laser
 2: Medium Laser Medium Laser
 3: SRM 6 SRM 6
 4: Trailer Hitch Trailer Hitch
 5: Arrow IV Homing Ammo Arrow IV Homing Ammo
 6: Arrow IV Homing Ammo Arrow IV Homing Ammo
 7: Arrow IV Ammo Arrow IV Ammo
 8: Arrow IV Ammo Arrow IV Ammo
```

**Comment by sixlettervariables** [comment]
The ammo issue with the Stukas and Chippewa is fixed in the next release.

The Chaparral needs to be removed and GM replaced as it's quite out of sync.

**Comment by GentlemanGrunt** [comment]
Maybe? The game was recently moved to 0.47.15 from stable, but there were no issues before a scenario was started. Issues started after the scenario. All things are in the repair bay and I can complete tasks. 

No refit was done on the Arrow IV though. One was attempted on the stable, but it wasn't allowed to be completed.

**Comment by sixlettervariables** [comment]
Okay, good information. I'll look into why that bin showed up.

**Comment by sixlettervariables** [comment]
I need the following to debug your Campaign more:
```
09:53:37,889 ERROR [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
checkUnits(), line 1206 : Could not load the following units: 
Stuka STU-K5 AGR
Atlas Atlas Heavy
```

**Comment by GentlemanGrunt** [comment]
Added in those two mech files. There are two copies of the Stuka, one as an blk and one as an mtf as it saved as both for some reason?
[Mechfiles.zip](https://github.com/MegaMek/mekhq/files/5765643/Mechfiles.zip)

**Comment by sixlettervariables** [comment]
Interesting, my fix for the filename garbling on different operating systems will only write the MTF or the BLK, but not both.

**Comment by GentlemanGrunt** [comment]
That might be my fault for it, I was sent the Stuka by my brother for the campaign, and he may have just saved it as an mtf from lack of knowing better.

**Comment by sixlettervariables** [comment]
I have fixes for the two classes of errors seen in this CPNX.
