### ISSUE TITLE
47.16 Mechwarrior portraits from campaign imported from v47.15 not displaying

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/mekhq#2346]
### Environment
MekHQ 47.16
Windows 10
Java 11.0.8

### Description
In MekHQ version 47.15, my campaign save had portraits assigned for all MechWarriors (image example below).
![image](https://user-images.githubusercontent.com/59574316/103701397-f8446f80-4f73-11eb-8267-5609d95aafb3.png)

When the same campaign save is loaded in MekHQ v47.16, the portraits are not displayed, reverting to the default ? portrait (image example below). 
![image](https://user-images.githubusercontent.com/59574316/103701664-69842280-4f74-11eb-9325-b1acea56ace7.png)

This appears to have been caused by the change in the file path (#2330), which is correct for future use and fixes other issues, but does not match the path in transferred save-data. Note that this _only_ affects transferred saves (from 47.15 and possibly earlier versions as well), and only MechWarrior portraits. Any portraits assigned using MekHQ 47.16 should work properly, and even any non-MechWarrior portraits in transferred saves should work properly, as only the one file path was changed. 

This issue can be manually resolved by the user. Steps:
1. Extract the campaign save, if it is currently compressed. 
2. Open the save in a text editor of your choice.
3. Perform a Find-Replace All operation, replacing 
\<portraitCategory>Male/Mechwarrior/\</portraitCategory>
with
\<portraitCategory>Male/MechWarrior/\</portraitCategory>
and replacing
\<portraitCategory>Female/Mechwarrior/\</portraitCategory>
with
\<portraitCategory>Female/MechWarrior/\</portraitCategory>
4. Save the changes (you may wish to save this as a new file in case of any issues).
5. Load the adjusted campaign file in MekHQ v47.16 and it should work, with MW portraits now displaying properly. 

Alternately, simply assigning new portraits using MekHQ v47.16, e.g. using the Randomize Portrait(s) context menu command, also works but the above preserves any previous portrait choices. 

### Files
v47.15 campaign file provided below for testing, if desired.
[Coppercoats.cpnx.gz](https://github.com/MegaMek/mekhq/files/5772749/Coppercoats.cpnx.gz)

Nothing in the log files.

**Comment by sixlettervariables** [comment]
In `AbstractDirectory` we could make the `TreeMap` case insensitive for Windows, which chould "fix" this issue going forward @Windchild292:
```
    /**
     * A map of the category names to the sub-categories. Please note that this
     * map includes the root category, if the root category contains any items.
     */
    protected TreeMap<String, Categorized> categories = new TreeMap<>(StringUtil.stringComparator());

    /**
     * A map of item names to the <code>ItemFile</code>s in the root
     * category
     */
    protected TreeMap<String, Object> items = new TreeMap<>(StringUtil.stringComparator());
```
It's correct for Linux and MacOS.

**Comment by sixlettervariables** [comment]
You'd still have the problem where a CPNX saved on Windows _may_ not load on Linux/MacOS depending on how strict they were with portrait file names.

**Comment by Windchild292** [comment]
This will not be fixed. Strict file names are required to ensure cross-platform compatibility. This was caused by an issue caught in dev versions, and the manual fix will be required for it.
