### ISSUE TITLE
Clan Bulk Hire recruiting mercenaries

### ISSUE THREAD

**Issue by BowtieBob** [MegaMek/mekhq#2348]
### Environment
What version of MekHQ does your issue apply to? 0.47.16
What operating system are you using?  Windows
What java version are you using? Java 8 Update 231

### Description
Started a new campaign in 0.47.16 and while recruiting personnel, I noticed that my clan unit based on Huntress has recruited a bunch of mercenaries when using the Bulk Hire tool.
![image](https://user-images.githubusercontent.com/70545594/103805769-abb36f80-5019-11eb-83ca-1d80c8d7b00a.png)

### Files
[NightstalkersBaseline_temp.cpnx.zip](https://github.com/MegaMek/mekhq/files/5777512/NightstalkersBaseline_temp.cpnx.zip)

**Comment by BowtieBob** [comment]
I found that turning off "Randomize Origin" stops the Mercenaries from being bulk hired.  I was hoping this option would pick from nearby planets to set the origin of my forces so that everyone wasn't from Huntress.  Regardless, I don't think there are too many mercenaries operating from Huntress in 3059 to be hired.

**Comment by sixlettervariables** [comment]
That's the fallback if an origin cannot be found. I don't believe I play tested it with a clan campaign.

**Comment by sixlettervariables** [comment]
I have a reasonable fix, but it still doesn't _quite_ get the feel correct for Clan play. It is close, but the planet choice isn't amazing. Basically you get a rare chance of other clans being an origin, and a very rare chance of a non-clan origin. Pre dark ages this should be reasonably accurate, aside from their planets not being on sibko planets.

**Comment by BowtieBob** [comment]
One thing I would add is that non-clan origins should only be for freebirth characters. 
Also, will this give a more random originating planet than it currently does? As it is, I have a couple thousand people in my unit and all of them are from Huntress.

**Comment by sixlettervariables** [comment]
No, this won't resolve the freebirth issue. That is going to take more work than I think is appropriate this late in the stage for 0.48. I can pick it back up for 0.49.+

Yes, this will make them choose from more planets (based on your configured radius):
![image](https://user-images.githubusercontent.com/8238690/104025931-4be0d400-5193-11eb-8197-bb1cea574b5f.png)
