### ISSUE TITLE
Forces not available in deployment screen

### ISSUE THREAD

**Issue by BowtieBob** [MegaMek/mekhq#2358]
### Environment
What version of MekHQ does your issue apply to? 0.47.16
What operating system are you using?  Windows
What java version are you using?  ver 8

### Description
Most of my forces are not showing in the deployment list. I have a full clan cluster of units broken down by stars, but only four of them appear to be deployable. 

### Files
[Nightstalkers30610921 - Arrive at Hamburg.cpnx.zip](https://github.com/MegaMek/mekhq/files/5792127/Nightstalkers30610921.-.Arrive.at.Hamburg.cpnx.zip)
[customs.zip](https://github.com/MegaMek/mekhq/files/5792128/customs.zip)
[logs.zip](https://github.com/MegaMek/mekhq/files/5792129/logs.zip)

**Comment by BowtieBob** [comment]
After removing one unit from each force and then reading them, all of my forces are now showing up correctly in the deployment screen. 

I started a new campaign for 0.47.16, but I imported the units and TO&E from 0.47.15. It's possible a corruption happened during the import.

**Comment by sixlettervariables** [comment]
This is interesting, your Forces under the campaign are correct. However, we separately track _Lances_ within your forces for AtB purposes (though I'm not entirely sure why). In your case, the Campaign lists only six lances. I'm digging into this more.

**Comment by sixlettervariables** [comment]
I'm not sure _how_ this came to pass, but I have a fix that will ensure we have the current available forces in your AtB list upon load. With the fix I've proposed:
![image](https://user-images.githubusercontent.com/8238690/104519627-bcd72000-55c7-11eb-81ae-d355435da054.png)
