### ISSUE TITLE
MekHQ will not start

### ISSUE THREAD

**Issue by zupkuck** [MegaMek/mekhq#236]
I unzipped MekHQ for Windows, dev update 0.3.31 and created a new AtB campaign. 

The next time I went to open MekHQ from the .exe file, nothing happened. It didn't appear in Task Manager. 

Attached are the log and campaign files. I am not using custom units. 
[MekHQissue.zip](https://github.com/MegaMek/mekhq/files/572780/MekHQissue.zip)

**Comment by pheonixstorm** [comment]
Update to the latest version and see if it still happens. Also what version of Java are you using. Do you have any anti-virus running as well??

**Comment by ebjvent** [comment]
I'm having sort of the same issue. 

It seems sometime after 0.3.32 someone is compiling against jdk 1.8. But there has been no mention of this anywhere in the MekHQ change logs that a new version of jabba is required.

From the development team standpoint, unless you're using jabba 1.8 features, you should be compiling against the lowest sdk you possibly can. You're completely screwing people like me who are stuck on Java 7. And if you do require Java 8, you should probably put a mention of the change in the change logs (whenever you move to java 9.) Save someone like me about 1gb of downloading (each version from today till one worked) and a couple hours of trying each build to see which one works... I have limited bandwidth ya know...

Thanks,

Exception in thread "main" java.lang.UnsupportedClassVersionError: mekhq/MekHQ : Unsupported major.minor version 52.0

**Comment by Dylan-M** [comment]
@ebjvent That is a completely separate issue. We did a poll on the CBT forums before moving forward with the version upgrade, and yes we are (or are planning to be) using Java 8 features. There is no such thing as "Stuck on Java 7" either. If your OS is that old, it's time for an update. Sorry, but we cannot keep supporting people who are using out of support OSes that are almost 10 years past their shelf life.

**Comment by ebjvent** [comment]
@Dylan-M  If broad cross platform, cross architecture support wasn't the goal of MegaMek, then what's the point of using a horribly unoptimal language like Java in the first place?

Again, If you're using Java 8 features, that's perfectly fine. My beef is it not being included in MekHQ change log. This is v0.3.33's change log:

> AtB preset.
> Reworked AtB RAT subsystem and added option to use RAT Generator
> Updated MegaMek.jar to 0.41.23
> Updated MegaMekLab.jar to 0.1.59

How hard is it to up "Updated Minimum Requirements to Java 8."  Not very hard I imagine.

Now as for your comments about being "no such thing" as being stuck on java 7. Obviously, you never have worked in a corporate computing environment. In any event, there are quite a few Linux Distros that do not have official Java 8 support, or have only recently supported Java 8. Slackware comes to mind.

Either way that doesn't matter. My beef is with the information not being presented to the user. Thus one such as my self wasting time and bandwidth checking each build until I found one that works. If you're using it, all the better, I will just stick with v0.3.32.

**Comment by pheonixstorm** [comment]
People still use Slackware??

**Comment by Dylan-M** [comment]
You're right, it doesn't matter. This software is not designed for enterprise environments (which, as a Systems Engineer for a software development company I'm _very_ familiar with), it is designed for your private and personal OS. Where, you can always compiled a new version of Java if you're not able to get it from your distro's repositories. I'll be honest, I really don't have sympathy here. You're trying to do something unsupported, and we're trying to give users the best experience we can. This means keeping up with the times. As for not having it in the changelog, I don't believe we've ever put that in the log before. We can, however, do so going forward.

**Comment by neoancient** [comment]
I cannot reproduce the issue. I can open the campaign both in the latest version and in 3.31. I found no errors in the log.
