### ISSUE TITLE
RFE: Add min/max age requirements for roles and allow re-assignment back to 'None' as a primary role

### ISSUE THREAD

**Issue by mjbroekman** [MegaMek/mekhq#2363]
### Environment
 	MekHQ 0.47.16
	Java version 15.0.1
	Platform Mac OS X 10.15.7 (x86_64)

### Description
Currently, when children are born, they are generated as per normal characters, which means they can sometimes have skills, abilities, and implants on day 1.

Example:
This 1yro has gained enough XP to get Piloting and Gunnery Mech... they were generated with the rest.
![Screen Shot 2021-01-11 at 10 54 59 PM](https://user-images.githubusercontent.com/5141448/104267655-0b69aa80-5460-11eb-8e74-72bcac9f14bf.png)

Additionally, they gain XP and, depending on how periodic XP is granted, can be trained as combat personnel (typically 5xp each for piloting and gunnery) within 2 years (and mechtechs are even easier to train).

### Suggestion
- Add minimum age requirements for roles (configurable in Campaign Options):
-- 16 for adminstration roles
-- 14-16 for combat roles
-- 12 for tech roles
-- 12 for medical roles
-- 5 for Astech
-- 0 for None, Child

- Add configurable maximum age limits for roles (configurable in Campaign Options)

- Add a 'Retiree' role that characters acquire upon hitting the maximum age limits
-- These are NOT _retired_ characters (removed from the roster), these are experienced characters that are on the roster but too old to perform in their old roles.

- Add a 'Child' role that newborns default to and that characters below age 16 can be assigned to.

- Allow anyone, at any time, to be assigned the 'None' role.

- Reduce XP gain for children to 1xp per X months (defaulting to 1 per 6 months) up to the time they go into a role with task-based XP gain.

- Add optional XP gain for children on their birthdays (configurable in the Campaign options)

- Add 'training' XP such that 'Retiree' characters convey 1 XP per period of time to a random character that is lower skilled and in their former role. (Greybeards showing the kids what's what).

Additionally, I would submit that newborns should be generated with zero XP, no skills, and no abilities.

**Comment by Windchild292** [comment]
I've started making changes to PersonnelRoles in #2352. First up is an Enum swapover, then I can make the other changes far easier.

**Comment by Windchild292** [comment]
The Child, Retiree, and None primary roles have been combined into the single Dependant Personnel Role. None is only valid as a secondary role in our internal implementation from now on.

**Comment by repligator** [comment]
99.99% implemented during 49.19, 49.20, 50.00, and 50.1. In particular, see https://github.com/MegaMek/mekhq/pull/4521 . Closing as completed. If anyone feels that one of the features mentioned has not been addressed, please consider opening a new issue to focus on that particular feature.
