### ISSUE TITLE
Error replacing Heat Sink in Puma Mech

### ISSUE THREAD

**Issue by BowtieBob** [MegaMek/mekhq#2365]
### Environment
What version of MekHQ does your issue apply to? 0.47.16
What operating system are you using?  Windows
What java version are you using?  AdoptOpenJDK 11.0.9.1

### Description
In the attached campaign file, if I try to replace the Double Heat Sink in the Puma Mech in the repair bay, nothing seems to happen. An error is generated in the mekhqlog file dealing with AeroHeatSink.  When I try to advance the day, the header at the top of the screen no longer shows the correct day, and the Daily Activity log just adds info to the end of the previous day rather than only showing one day at a time.
![image](https://user-images.githubusercontent.com/70545594/104466538-f6356e80-557a-11eb-960c-8c4cac6d430f.png)

Note, the Daily Activity Log error only seems to occur when "Run Mass Repair/Salvage on New Day" is turned on, but the Heat Sink error happens any time I try to repair the heat sink.  Attempting to restore the unit using GM mode also causes the error.

### Files
[Nightstalkers30611015-TEST.cpnx.zip](https://github.com/MegaMek/mekhq/files/5809261/Nightstalkers30611015-TEST.cpnx.zip)
[customs.zip](https://github.com/MegaMek/mekhq/files/5809262/customs.zip)
[mekhqlog.zip](https://github.com/MegaMek/mekhq/files/5809263/mekhqlog.zip)

**Comment by sixlettervariables** [comment]
```
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: class mekhq.campaign.parts.AeroHeatSink cannot be cast to class mekhq.campaign.parts.equipment.EquipmentPart (mekhq.campaign.parts.AeroHeatSink and mekhq.campaign.parts.equipment.EquipmentPart are in unnamed module of loader 'app')
	at mekhq.campaign.parts.equipment.MissingEquipmentPart.fix(MissingEquipmentPart.java:177)
	at mekhq.campaign.parts.MissingPart.succeed(MissingPart.java:124)
	at mekhq.campaign.Campaign.fixPart(Campaign.java:2868)
	at mekhq.gui.RepairTab.doTask(RepairTab.java:627)
	at mekhq.gui.RepairTab.lambda$initTab$4(RepairTab.java:291)
```

**Comment by sixlettervariables** [comment]
Using my debug menu:
```
13:28:41,824 INFO [mekhq.gui.adapter.UnitTableMouseAdapter$1] {AWT-EventQueue-0} 
actionPerformed(), line 1035 : Puma (Adder) Prime (2e01d93b-b22e-412b-91a8-2413265cf71d)
	644: Mech Head (Clan Endo Steel) mekhq.campaign.parts.MekLocation
	645: Armor (Ferro-Fibrous) mekhq.campaign.parts.Armor
	646: Mech Center Torso (Clan Endo Steel) mekhq.campaign.parts.MekLocation
...
	8153: Double Heat Sink mekhq.campaign.parts.equipment.MissingHeatSink
...
```
It certainly looks like the correct part is on the Mech.

**Comment by sixlettervariables** [comment]
Figured it out.

**Comment by sixlettervariables** [comment]
With the fix:
![image](https://user-images.githubusercontent.com/8238690/104497671-b6857b80-55a8-11eb-85f5-ca246d9f34f4.png)
