### ISSUE TITLE
Remove Tech From Lance assignments upon retiring

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#237]
Currently when a tech retires they are still considered assigned to their lance by MekHq. It a scavenger hunt when several techs retire in a large unit to see which lances need new techs, and the old ones must be manually removed.

Techs should be removed from the lance as well as any units when they retire.

**Comment by pheonixstorm** [comment]
Is this happening only with the Lance Techs or for all techs in general?

**Comment by pheonixstorm** [comment]
Hope to have a PR for this by the end of the weekend. The fix is partially done atm.

**Comment by VampireSeraphin** [comment]
This is not resolved in the new 41.27 release. Let me clarify what I'm seeing so we're all on the same page. 

In the unit TO&E tab, techs can be assigned to a force (my lance, etc...)

If the tech assigned to a force retires, MekHq does not remove them from their assigned force. The force must be manually right clicked on, and "remove tech from force" selected to remove them. Replacement techs cannot be added till the old ones are removed manually because a force with an assigned tech disables the assignment of more techs.

**Comment by neoancient** [comment]
That stops it from happening, but you'll still have to edit the campaign file. Search for the lance name and remove the line that starts with <techId> from the force node.

**Comment by VampireSeraphin** [comment]
Can you put the line I need to delete in a quote box just so I can be certain I've got it 100% correct? ty.

**Comment by neoancient** [comment]
The details will be different, but this is what the force node looks like. Find the one that has the name of your lance where this one says `<name>Striker Lance</name>` and remove the line that says `<techId>f81f1b0f-1678-4ff8-9ff5-71737c3f1631</techId>` here (yours will have a different value). If you have more than one lance with the same name, temporarily change it to something unique before you save the campaign so you can be sure you have the right one.
```
<force id="4" type="mekhq.campaign.force.Force">
	<name>Striker Lance</name>
	<desc></desc>
	<iconCategory>Mech/</iconCategory>
	<iconFileName>mmech.png</iconFileName>
	<scenarioId>-1</scenarioId>
	<techId>f81f1b0f-1678-4ff8-9ff5-71737c3f1631</techId>
	<units>
		<unit id="7d7ed6fc-dbe0-4c7f-ae29-4fc357cac9ca"/>
		<unit id="5ff50c94-8f0f-4c20-8a00-ffad59f3ffb6"/>
		<unit id="69b910f6-ef6c-42ec-b5f4-6529351a11ff"/>
		<unit id="f5a9556a-5be8-45fc-86be-45b86fae701f"/>
	</units>
</force>
```

**Comment by VampireSeraphin** [comment]
I've got a full regiment in my current campaign. So, that's a ton of lances to edit. Before I jump into the cpnx with an editor, will manually removing the techs from the force in mekHq reset the force node?

**Comment by neoancient** [comment]
You only need to do this for those that have an assigned tech that is no longer active. Removing that line from the campaign file won't have any other effect.

**Comment by VampireSeraphin** [comment]
Ok, this is only needed to remove techs that are stuck when you import to
the new version then? I think I see.
