### ISSUE TITLE
Techs stuck on assignment

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/mekhq#239]
I often get techs that are stuck on an assignment. For example, I have a tech that's assigned to 4 units. If I assign it to 'none', it's still assigned to two and I can't figure out what it's assigned to.

It would be nice to have a better interface for assigning techs to units to be able to determine what techs with multiple assignments are and to properly manage them.

**Comment by pheonixstorm** [comment]
How are you assigning the techs. By unit, by lance, or by tech.

ie
Lance assigned in TOE
Unit assigned in hangar
Tech assigned in personnel

In the personnel tab and selecting the tech, does it show as still assigned to 2 units or is it blank? Need more information on how to reproduce it.

**Comment by mkerensky** [comment]
I have seen this as well.  I have a mix of tech assignments, with most being assigned as techs from the personnel tab.  In my case, I think it is linked to having the tech assigned to a vehicle or ASF that gets reduced to salvage quality and then stripped in hangar or sold. I have a large force that keeps some spare units in mothballs and has a tech/mechanic for every active unit. When a vehicle/ASF is wrecked, I assign its tech to a replacement if I have one, and that's when I noticed this issue.

**Comment by kipstafoo** [comment]
I agree with your scenario... I think that is the most likely culprit. That being said, I have not been able to reproduce it yet. I have yet to do a deep dive on this part of the code to confirm or refute the idea. I have submitted a fix though that'll repair techs that have ghost assignments.

**Comment by djmbm** [comment]
This will also, likely, occur if you GM Remove a unit.

**Comment by kipstafoo** [comment]
I have confirmed that, at least in the latest dev release, selling a unit, GM removing a unit and auto-removing a unit after scrapping the last location all properly remove the unit from the technician's list.

**Comment by neoancient** [comment]
This is the same issue as #237.
