### ISSUE TITLE
NPE: Unable to add Hopping Jack and Jumping Jack SPAs to list of available SPAs

### ISSUE THREAD

**Issue by mjbroekman** [MegaMek/mekhq#2397]
### Environment
 	MekHQ 0.47.16
	Java vendor N/A (openjdk)
	Java version 15.0.1
	Platform Mac OS X 10.15.7 (x86_64)

### Description
At some point, I removed the Hopping Jack and Jumping Jack SPAs (via Campaign Options) because they were appearing very frequently and, occasionally, on pilots that were not in meks with JumpJets.

However, now I would like to add them back to the available SPAs and I am not able to.

When I go into the Campaign Options to the Special Abilities tab and click 'Add Another Special Ability', the dialogue box appears with the SPAs that are not currently available. If I select either Hopping Jack or Jumping Jack and press 'Done', nothing happens. This appears to be the result of an NPE on the Display Name

![Screen Shot 2021-01-24 at 12 26 21 PM](https://user-images.githubusercontent.com/5141448/105638368-41376780-5e40-11eb-8df8-b98fd781c6be.png)
![Screen Shot 2021-01-24 at 12 26 48 PM](https://user-images.githubusercontent.com/5141448/105638373-45fc1b80-5e40-11eb-8d29-6f1de895ac29.png)

`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "mekhq.campaign.personnel.SpecialAbility.getDisplayName()" because the return value of "java.util.Hashtable.get(Object)" is null
	at mekhq.gui.dialog.EditSpecialAbilityDialog.getPrereqAbilDesc(EditSpecialAbilityDialog.java:438)
	at mekhq.gui.dialog.EditSpecialAbilityDialog.initComponents(EditSpecialAbilityDialog.java:157)
	at mekhq.gui.dialog.EditSpecialAbilityDialog.<init>(EditSpecialAbilityDialog.java:94)
	at mekhq.gui.dialog.SelectUnusedAbilityDialog.done(SelectUnusedAbilityDialog.java:154)
	at mekhq.gui.dialog.SelectUnusedAbilityDialog.access$000(SelectUnusedAbilityDialog.java:49)
	at mekhq.gui.dialog.SelectUnusedAbilityDialog$1.actionPerformed(SelectUnusedAbilityDialog.java:94)
`

Normally, this should pop up another window with prerequiste information, xp cost, etc.

For example, with Dodge (which I hit cancel afterwards to not add it)
![Screen Shot 2021-01-24 at 12 26 36 PM](https://user-images.githubusercontent.com/5141448/105638398-675d0780-5e40-11eb-8bff-34893fdbea30.png)

Additionally, I noticed in the defaultspa.xml file, both Hopping Jack and Jumping Jack were listed as requiring Piloting/Mech or **Gunnery**/Protomech. I'm pretty sure that should be _Piloting_/Protomech rather than Gunnery.

### Files
[Knights of the Periphery30050410.cpnx.gz](https://github.com/MegaMek/mekhq/files/5862812/Knights.of.the.Periphery30050410.cpnx.gz)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5862820/mekhqlog.txt)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/5862821/megameklog.txt)

**Comment by Windchild292** [comment]
The latter is because there is no Piloting/ProtoMech
