### ISSUE TITLE
Damaged mech not in Repair Bay

### ISSUE THREAD

**Issue by BowtieBob** [MegaMek/mekhq#2398]
### Environment
What version of MekHQ does your issue apply to? 0.47.16
What operating system are you using?  Windows
What java version are you using?  AdoptOpenJDK version 11.0.9.1

### Description
I have a mech with moderate damage (Dasher Prime), but it is not in the Repair Bay.

![image](https://user-images.githubusercontent.com/70545594/105910797-0de70b00-5fef-11eb-9b77-e1960297fd8c.png)
![image](https://user-images.githubusercontent.com/70545594/105910855-1dfeea80-5fef-11eb-97ca-688abf87eba1.png)

### Files
[Nightstalkers30620630.cpnx.zip](https://github.com/MegaMek/mekhq/files/5876402/Nightstalkers30620630.cpnx.zip)
[megameklog.zip](https://github.com/MegaMek/mekhq/files/5876396/megameklog.zip)
[customs.zip](https://github.com/MegaMek/mekhq/files/5876399/customs.zip)

**Comment by BowtieBob** [comment]
Ok, I'm not sure why, but after advancing forward a couple of days, it seems to have fixed itself.  I'm guessing the auto repair must have finally kicked in.

**Comment by Windchild292** [comment]
I cannot recreate this locally using the provided save file.

**Comment by BowtieBob** [comment]
It's weird, if I open that save file (or many of the save files before that one) I end up with two damaged mechs in my repair bay. I'm not sure what happened, but it seems to have fixed itself.

**Comment by sixlettervariables** [comment]
I'm unable to reproduce this either, let's re-open if you see it again.
