### ISSUE TITLE
Request: allow to assign Vehicle Crew to Combat Vehicle.

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/mekhq#2403]
### Environment
Ver 0.47.16

### Description
As title says. For now, only Vehicle Driver and Vehicle Gunner are assigned to a combat vehicle, but actually many crewmembers are not either driver or gunner.

I wish we had a role 'Vehicle Commander' but it should be on the another thread.

**Comment by Windchild292** [comment]
Vehicle Crewmembers are for Support Vehicles and rely on having the Tech/Mechanic skill. This is because, unlike Support Vehicles, Combat Vehicles do not specify the number of crew that are required to be gunners. MekHQ therefore assumes that all Combat Vehicle crew are gunners.
