### ISSUE TITLE
Bug: maintenance/repair is calling heatsink on IS Mech Clan tech

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#2406]
Attached campaign file is version 47.16.  There is a maintenance report that a double heatsink on the Panther PNT-16K failed a maintenance check.  It shows as being Clan tech for both maintenance and repair, however... it's not.

Nothing special has been customized on this unit, should be bog-standard.

[Heatsink bug.cpnx.gz](https://github.com/MegaMek/mekhq/files/5914154/Heatsink.bug.cpnx.gz)

There's a number of other customized units in the campaign but none are mixing IS/Clan heat sinks.  Not sure if it's related, but the megamek.log file shows a number of unscrambleEquipmentNumbers() warnings (but for other units, not this Panther).

[megameklog.txt](https://github.com/MegaMek/mekhq/files/5914183/megameklog.txt)

**Comment by BowtieBob** [comment]
Just a thought, but since the game will attempt to use aero heat sinks for repairs, is it possible that at some point that unit got a standard HS replaced by a clan HS and it just didn't cause an error like the aero ones do?

**Comment by sixlettervariables** [comment]
Need your customs:
```
checkUnits(), line 1224 : Could not load the following units: 
Avatar AV1-OC (3)
Crab CRB-45(C)
Avatar AV1-OF (C)
Hawk Moth Gunship (Gauss-C)
Owens OWC-4
IS Standard BA Level I [LRR]
Owens OW-1A(C)
Black Hawk-KU BHKU-OW(C)
Firestarter FS9-OW(C)
Black Hawk (Nova) (Dervish)
Armored Personnel Carrier (Tracked HQ)
Jump Stealth Level I (Laser)
Ironsides IRN-SD1(C)
Tengu BA Level I [Plasma]
Mechanized Wheeled Level I (Gauss)
Fenrir BA Level I [SPL]
Black Hawk-KU BHKU-OB (2)
Longinus BA Level I [MG]
Purifier BA Level I [PPC]
Mechanized Tracked Level I (LRM)
Mechanized Wheeled Level I (Laser)
```

**Comment by SuperStucco** [comment]
Here you go:
[BIIIG-customs.zip](https://github.com/MegaMek/mekhq/files/5937383/BIIIG-customs.zip)
[Infantry Pack.zip](https://github.com/MegaMek/mekhq/files/5937385/Infantry.Pack.zip)

There's a few more infantry in there than what is being actively used, but at this point it's easier to include the whole package rather than digging out the individual designs.

**Comment by sixlettervariables** [comment]
Yep, that's a clan double heat sink!
```
		<part id="18972" type="mekhq.campaign.parts.equipment.HeatSink">
			<id>18972</id>
			<name>Double Heat Sink</name>
			<unitTonnage>35</unitTonnage>
			<hits>1</hits>
			<mode>NORMAL</mode>
			<skillMin>1</skillMin>
			<unitId>e36673d8-cbac-492c-8d0a-ca6b41e4b7a2</unitId>
			<brandNew>true</brandNew>
			<quantity>1</quantity>
			<quality>0</quality>
			<equipmentNum>4</equipmentNum>
			<typeName>CLDoubleHeatSink</typeName>
			<size>1.0</size>
			<equipTonnage>1.0</equipTonnage>
		</part>
```
If you change that `typeName` to `ISDoubleHeatSink` it'll fix your problem.

I believe this is fixed by #2366, which fixed the other heat sink bugs.

**Comment by SuperStucco** [comment]
What should I be using to unpack/repack the GZ campaign files to do this?

**Comment by Windchild292** [comment]
I personally use 7-zip, although you can load the campaign in MHQ then resave it without the .gz extension and it will save without it.
