### ISSUE TITLE
Program Freeze trying to Purchase Units

### ISSUE THREAD

**Issue by JoshWaltzing** [MegaMek/mekhq#2407]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
0.46.1
Windows
Java 1.8.0_201-b09

### Description
In each campaign, be a built-in campaign or a custom campaign, as soon as I click on the Purchase Units or Parts menu, the program freezes and I am forced to CTRL>ALT>DELETE to shut down the program. This just started today after I used MegaMekLab to build a new Aerospace fighter. It was working prior to that build in the Lab. I save that build file to a separate folder than the MegaMek folder so I wouldn't interfere. The lab seems to still function correctly has I have built two other meks in the program since with no problems but the HQ continues to crash. 
I have opened several of the built-in campaigns to the same result. 
[JoshWaltzingBugReport.zip](https://github.com/MegaMek/mekhq/files/5923365/JoshWaltzingBugReport.zip)

### Files
Attached a Zip file that has several custom units, the logs, and the campaign files.

**Comment by sixlettervariables** [comment]
I fixed a number of performance issues with that screen since 0.46.1.

You may try deleting your units.cache to see if that helps, but I'm not certain that's a fix.

**Comment by sixlettervariables** [comment]
So we won't be fixing this bug in a future release of 0.46.1, as it will be superseded by 0.48 when that lands in the near future.
