### ISSUE TITLE
day advances improperly

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#2411]
version 47.16 java 11

advancing day in the attached save, several things happen.
-date at top doesn't change
-daily log is not reset, new days log amended to end of old days log
-cycling month does do special event and morale rolls, but contracts DO NOT pay out their monthly incomes
-sometimes ordering a repair uses time but continues to show the item unchanged as if the repair didn't occur.  no entry for the repair is shown in the log.  repeatedly ordering the repair continues to use time.  when advance day occurs improperly repair status doesn't change.

saving after advancing day and reloading loads the game on the new day, log displays properly, stuck repairs are complete, but contract payouts are still missing.  no idea as to possible triggers of the issue.  sometimes i can go a few weeks without the reload, sometimes i have to do it every day.

[error.zip](https://github.com/MegaMek/mekhq/files/5938646/error.zip)

**Comment by BowtieBob** [comment]
Sounds like the Aero Heat Sink bug. Try going back to a good save and deleting all of your Aero Heat Sinks in inventory.

**Comment by Windchild292** [comment]
Fixed in #2366
