### ISSUE TITLE
RFE-Changing bondsman status should not be a GM only option

### ISSUE THREAD

**Issue by BowtieBob** [MegaMek/mekhq#2414]
Currently (0.47.16) in order to change a person from a Bondsman to Free requires enabling GM mode. Bondsman status should be something any commander can change, so I'm not sure why it would need to be under the GM options.

**Comment by Windchild292** [comment]
This is working as intended. Bondsmen are not fully implemented at the current time, but are a form of prisoner, albeit one that is willing to work with the company. They are not freely swappable to a free member of the force, but that can be changed by a person as the GM.
