### ISSUE TITLE
After Eject, Next Scenario Will Not Deploy Unit In MM #6

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/mekhq#242]
Same thing as issue #6 again but, in 0.41.25HQ now.  Warhammer pilot was slapped with two AC20 rounds from a Demolisher last game and ejected.  Fixed the mech up and three days later deploy on another scenario.  Warhammer shows up in the lobby and am able to configure it (searchlight) but, once inside MM it doesnt allow you to deploy the WHM.  Tried removing the WHR from my TO&E and then reassigning to first lance and same result.  Am going to try to delete the units cache and see if maybe for some reason MM has it deployment on some other round than the start.

[Deploymentbug.zip](https://github.com/MegaMek/mekhq/files/579754/Deploymentbug.zip)

**Comment by BLOODWOLF333** [comment]
Restarting HQ gets around the issue.

**Comment by neoancient** [comment]
It's apparently something that doesn't get saved to the campaign file (or doesn't get loaded from it, but I didn't see anything in the file that looked suspicious). If it happens again, try posting a saved game from MM.

**Comment by Dylan-M** [comment]
Initial suspicions:
1. Crew ejected state isn't reset
2. Unit ejected state isn't reset
3. Both of the above?

Both of those states should be getting reset post-scenario resolution.
