### ISSUE TITLE
NPE: Advance Day stuck

### ISSUE THREAD

**Issue by Zumbleguy** [MegaMek/mekhq#2427]
MekHQ 0.47.17
Windows 10
Java 11

When clicking the Advance Day button, the day doesn't advance along the top of the screen.
The Daily Activity Log does show a day advance but only appends the log directly below the previous day.
![13241](https://user-images.githubusercontent.com/52971972/108327285-489e2680-71dc-11eb-99fb-f5dd8a5dea38.png)

I have no idea how to reproduce this. It does work as intended after loading a save in my experience, but, when it happens, clicking on "Advance Day" would simply continue to write in the activity log in the same way. (and write more of the same NPEs in the mekhqlog.txt)

[Lucre Lancers30200313.zip](https://github.com/MegaMek/mekhq/files/6001251/Lucre.Lancers30200313.zip)
Save file inside. No customs.
[megameklog.txt](https://github.com/MegaMek/mekhq/files/6001253/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6001257/mekhqlog.txt)

**Comment by HammerGS** [comment]
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.campaign.parts.Part.getQualityName(Part.java:257)
	at mekhq.campaign.Campaign.doMaintenance(Campaign.java:6358)
	at mekhq.campaign.Campaign.processNewDayUnits(Campaign.java:3273)
	at mekhq.campaign.Campaign.newDay(Campaign.java:3411)
	at mekhq.campaign.CampaignController.advanceDay(CampaignController.java:82)
	at mekhq.gui.dialog.PersonnelMarketDialog.lambda$initComponents$1(PersonnelMarketDialog.java:258)
```

**Comment by HammerGS** [comment]
Also lots of errors like this:

10:26:08,393 ERROR [megamek.client.ratgenerator.RATGenerator] {AWT-EventQueue-0} 
parseModelNode(), line 1054 : Jump Platoon (GL) not found.

10:26:08,409 ERROR [megamek.client.ratgenerator.RATGenerator] {AWT-EventQueue-0} 
parseModelNode(), line 1054 : Peregrine (2969) not found.

10:26:08,493 ERROR [megamek.client.ratgenerator.RATGenerator] {AWT-EventQueue-0} 
parseModelNode(), line 1054 : Jump Platoon (GL) not found.

10:26:08,509 ERROR [megamek.client.ratgenerator.RATGenerator] {AWT-EventQueue-0} 
parseModelNode(), line 1054 : Peregrine (2969) not found.

10:27:21,858 ERROR [mekhq.module.atb.AtBEventProcessor] {AWT-EventQueue-0} 
addRecruitUnit(), line 225 : Personnel market could not find BattleArmor for recruit from faction FS

10:27:24,559 ERROR [mekhq.module.atb.AtBEventProcessor] {AWT-EventQueue-0} 
addRecruitUnit(), line 225 : Personnel market could not find ProtoMek for recruit from faction LA

10:27:24,559 ERROR [mekhq.module.atb.AtBEventProcessor] {AWT-EventQueue-0} 
addRecruitUnit(), line 225 : Personnel market could not find ProtoMek for recruit from faction FS

10:27:33,544 ERROR [mekhq.module.atb.AtBEventProcessor] {AWT-EventQueue-0} 
addRecruitUnit(), line 225 : Personnel market could not find BattleArmor for recruit from faction FS

10:29:52,025 ERROR [mekhq.module.atb.AtBEventProcessor] {AWT-EventQueue-0} 
addRecruitUnit(), line 225 : Personnel market could not find BattleArmor for recruit from faction ARC

10:29:52,025 ERROR [mekhq.module.atb.AtBEventProcessor] {AWT-EventQueue-0} 
addRecruitUnit(), line 225 : Personnel market could not find ProtoMek for recruit from faction TC

10:30:45,682 ERROR [mekhq.campaign.parts.Refit] {AWT-EventQueue-0} 
calculate(), line 490 : null missing part for Cargo Bay #1 during refit calculations

10:33:27,361 ERROR [mekhq.module.atb.AtBEventProcessor] {AWT-EventQueue-0} 
addRecruitUnit(), line 225 : Personnel market could not find BattleArmor for recruit from faction LA

I'll look into the unit errors.

**Comment by sixlettervariables** [comment]
That part error means either:
A. There is no campaign object for the part, or
B. There are no campaign options for the campaign
Both of which I did not believe was possible.

**Comment by sixlettervariables** [comment]
I can't seem to reproduce this with the provided campaign. Perhaps a save-reload fixes this very odd corner case.
