### ISSUE TITLE
A pregnant widow can't give birth.

### ISSUE THREAD

**Issue by jsv** [MegaMek/mekhq#243]
If pregnant woman's spouse gets killed, she remains pregnant forever. From the look of things, something crashes in or around the **Person.birth** call due to no longer present spouse id (if I edit the savegame to add the dead spouse id back manually, the girl gives birth ok) and then the rest of the day can't process normally (no visual feedback on pressing "advance day": the day log does not update, etc).

In the attached savefile, Petra Wattu is the girl in question and Howard Wattu is her late husband. Note that they have another child already, so there exists a corresponding ancestors pair. I still don't get where things go wrong, from the look at the code it should've just created another pair with unknown father. But then I'm no Java programmer...
[nobirth.zip](https://github.com/MegaMek/mekhq/files/583540/nobirth.zip)

_I think it would be better to track who actually got the girl pregnant instead of expecting that to be her current spouse. And not being in a relationship doesn't strike me as a valid excuse for getting pregnant from null either... :)_

**Comment by Akjosch** [comment]
We don't care for genetics right now, so keeping track of the biological father is *way* down on the priority list.

**Comment by jsv** [comment]
Fair enough. After all, that's a wargame, not a soap opera :)
