### ISSUE TITLE
Additional images for TOE Force Icons

### ISSUE THREAD

**Issue by BowtieBob** [MegaMek/mekhq#2441]
I created some additional pieces for the TOE force icons if you want to add them to the default download.
Mostly, they are just variations of the Alphanumerics set to work better with the Battle Armor type.  There is also a new unit type combining the icons of wheeled, tracked, and hover vehicles for units with multiple types.

![image](https://user-images.githubusercontent.com/70545594/109193429-f7eb7800-775d-11eb-99a4-9a6d584d92cd.png)

[images.zip](https://github.com/MegaMek/mekhq/files/6044794/images.zip)

**Comment by Windchild292** [comment]
Renamed the vehicle one to Vehicle Assorted, and 

One comment... would you mind doing Low Left versions for H-Z? Just the single letters would be great.

**Comment by BowtieBob** [comment]
Here you go.
[H-Z Low Left.zip](https://github.com/MegaMek/mekhq/files/6046099/H-Z.Low.Left.zip)

**Comment by Windchild292** [comment]
Added in https://github.com/MegaMek/mekhq/commit/3e554f5233eeea10210d97e3cc52d610c4ca7474
