### ISSUE TITLE
Ranks reverting to Second Star League

### ISSUE THREAD

**Issue by BowtieBob** [MegaMek/mekhq#2442]
### Environment
What version of MekHQ does your issue apply to? 0.47.17
What operating system are you using?  Windows
What java version are you using? 	 AdoptOpenJDK version 11.0.9.1

### Description
After setting my rank system to First Star League, the rank structure will eventually change back to Second Star League instead.
![image](https://user-images.githubusercontent.com/70545594/109247855-44f53b80-77aa-11eb-8300-c07f6ffa8263.png)
Note the Lieutenant rank of the First Star League, but the Rank System in the drop down says Second Star League.  This is after reloading my campaign.

![image](https://user-images.githubusercontent.com/70545594/109247944-78d06100-77aa-11eb-8c67-3ec3fc01d11b.png)
The drop down now shows "Second Star League" in the location that "First Star League" used to be.  If I chose this option (or the one at the top of the list), the ranks change to Second Star League ranks.

![image](https://user-images.githubusercontent.com/70545594/109248225-06ac4c00-77ab-11eb-8fcd-a40b5568106b.png)
Reloaded after changing to Federated Suns ranks.

![image](https://user-images.githubusercontent.com/70545594/109248291-26dc0b00-77ab-11eb-9fb5-cd68ef6bbe03.png)
Here is the text from the .cpnx file after changing to "First Star League" ranks

![image](https://user-images.githubusercontent.com/70545594/109248365-46733380-77ab-11eb-8457-ee096c616eb7.png)
Here is the text from the .cpnx file after changing to "Federated Suns" ranks

The ranks are actually showing correctly when I open the campaign, but I have noticed that it will eventually switch back to the actual Second Star League ranks (I'm not sure what actually causes that to happen yet)

### Files
[Devestators30250409-1SL.cpnx.zip](https://github.com/MegaMek/mekhq/files/6047119/Devestators30250409-1SL.cpnx.zip)
This has a save with Fed Suns ranks and another with 1st Star League ranks.

**Comment by Windchild292** [comment]
This was a bugfix, behaviour is expected, and no new migration will be added.

**Comment by BowtieBob** [comment]
How is it expected behavior for the ranks to continually switch back to second star league on their own?

**Comment by monbvol** [comment]
This still seems to happen with some campaigns on version 0.49 but not all.

https://www.mediafire.com/file/x1sa58s1t4vw8km/SecondStarLeague.mp4/file

May come down to how the Custom ranks are handled now versus previous versions.
