### ISSUE TITLE
Window panes not scrolling by page

### ISSUE THREAD

**Issue by BowtieBob** [MegaMek/mekhq#2446]
### Environment
What version of MekHQ does your issue apply to? 0.47.17
What operating system are you using?  Windows
What java version are you using?  openjdk 11

### Description
Some of the detail screens are able to scroll by page when you select the bar of the scroll bar (normal Windows behavior), but many of them only scroll one line at a time instead. This makes scrolling tedious when a mouse wheel is not available.
Here are the ones I have found so far that only scroll one line at a time:

 TOE tab, Pilot and Unit detail tabs
 Briefing Room tab, Mission list
 Briefing Room tab, Scenario details
 Interstellar Map tab, System details
 Personnel tab, Personnel details
 Hanger tab, Unit details

**Comment by BowtieBob** [comment]
Oddly enough, the Lance Deployment pane on the Briefing Room tab DOES work correctly when clicking on the scroll bar, but when scrolling using a mouse wheel, it only moves a fraction of a line at a time.  This is the only pane I've noticed that scrolls that slowly when using a mouse wheel.

**Comment by sixlettervariables** [comment]
This is by design for most tables with scroll bars, per [JTable's Scrollable interface implementation](https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/JTable.html#getScrollableUnitIncrement(java.awt.Rectangle,int,int)):
> Returns the scroll increment (in pixels) that completely exposes one new row or column (depending on the orientation).
> This method is called each time the user requests a unit scroll.

It may be possible to override this, but I'm not sure what a reasonable setting would be.

**Comment by sixlettervariables** [comment]
We did it to ourselves:
https://github.com/MegaMek/mekhq/blob/65555bd0c6f33b163b2cc27ca6cc7480c733ac19/MekHQ/src/mekhq/gui/view/ScrollablePanel.java#L45-L51
