### ISSUE TITLE
Vehicle Tracked Force Icon is weirdly interacts with the other icon parts.

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/mekhq#2448]
### Environment
Ver 0.47.17

### Description
![r1](https://user-images.githubusercontent.com/47907439/109993374-9162ed00-7d4f-11eb-91d8-dc918d50610d.png)
As you see, if I try to make the armored artillery icon, the circle of artillery icon and the oval of armor icon are overlapped.

It must be looks like that;
![600px-Military_Symbol_-_Friendly_Unit_(Solid_Light_1 5x1_Frame)-_Artillery_-_Mechanized_(NATO_APP-6) svg](https://user-images.githubusercontent.com/47907439/109994555-c4f24700-7d50-11eb-93f7-8d22d91671f1.png)

Also it seems that the others are also overlapping with the same tracked one. Also tracked small and artillery all have the same problem. I think that the oval must be bigger, as well as adjust the point of the items in adjustments tab.

**Comment by BowtieBob** [comment]
It looks like the tracked small artillery option is set to be used with the artillery tube small as shown below:
![image](https://user-images.githubusercontent.com/70545594/110016471-ad807300-7cea-11eb-9c3b-0a40c5cc543a.png)

It isn't centered like you have it, but it makes it more consistent when using hover or tracked types (which need the artillery circle above them)

**Comment by binaryspica** [comment]
Perhaps, but the big tracked icon seems the way to follow [APP-6](https://en.wikipedia.org/wiki/NATO_Joint_Military_Symbology)...,

**Comment by wildfire142** [comment]
I orginally made these files based on the stratOps warfare symbology pages and going by their examples the artillery modifier was above the motive indicator for both the examples  so mea culpa :) 

![Warfare Symbology_Symbols](https://user-images.githubusercontent.com/17962865/110168705-7647ba00-7def-11eb-906a-a8036fdfa5d6.jpg)

**Comment by Kailan7401** [comment]
I made an SP artillery piece a while back cause I ran into the same issue. Just drop this into your MekHQ\data\images\force\Pieces\Type directory. https://i.imgur.com/GvDzzLy.png

**Comment by Kailan7401** [comment]
Fixed for .49, don't know how to close issues because I'm github illiterate

**Comment by sixlettervariables** [comment]
We can do that for you :)

**Comment by Windchild292** [comment]
We've not merged in the changes for this yet, and should keep it open until we do
