### ISSUE TITLE
Custom Ranks are not loaded at all.

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/mekhq#2449]
### Environment
Ver 0.48.0
Windows 10
OpenJDK build 11.0.10+9

### Description
As title says. You may save the settings, but when you load it then MekHQ does not loads custom rank settings at all and it is changed to Second Star League. Of course if you open the settings and you will find that the custom tab in the rank is empty.

When I checked XML save files, I found that the settings are saved properly. So I think that the problem is the load part - although the setting is saved properly(I made it once again and saved) it does not applied when I load it again.

**Comment by purpledragon2** [comment]
I am experiencing this as well.  I rely heavily on custom ranks.  

ver 0.48.0
Windows 10
JAVA 8 update 231

**Comment by purpledragon2** [comment]
I don't know if this might be related or possibly help point to a potential problem:

On load, it is not remembering the rank system I use, nor is it collapsing the personnel if "Group by Unit" is already checkmarked.

**Comment by DwarbitBK** [comment]
I found that all rank systems were showing as Second Star League when I loaded 48.0 with Java(TM) SE Runtime Environment (build 1.8.0_281-b09).

**Comment by RAldrich** [comment]
Same issue - I was able to work around it by replacing the Second Star League rank .xml data with my custom ranks.
