### ISSUE TITLE
[AtB] Bonus payments are not made.

### ISSUE THREAD

**Issue by jsv** [MegaMek/mekhq#245]
When playing with shares off, the bonus payments to the personnel are never actually deduced from the cash. It's said in RetirementDefectionTracker that the bonus is handled by dialog, but, as far as I can tell, the dialog only calculates the total and no transaction ever occurs.

**Comment by pheonixstorm** [comment]
If I am reading this right you need to manually apply the bonus for it to do anything.

**Comment by jsv** [comment]
@pheonixstorm, maybe I'm missing something obvious, but I do not see how I can do that short of writing down the sum and then adding the transaction in GM mode. There are "pay bonus" checkboxes (I check a lot of them and the corresponded rolls are affected), there is "Roll" button, and after that on the next screen there is "OK" button. After all is done, I see a single "Final payout" transaction, but it does not include the bonus (otherwise the sum would be much bigger).
