### ISSUE TITLE
Injury report disappears when an old campaign is loaded

### ISSUE THREAD

**Issue by MechSalvager** [MegaMek/mekhq#2450]
### Environment
MekHQ 0.48.0
Windows 10 10.0 (x86)
Java version 1.8.0_281

### Description
When loading an old campaign the Injury Report does not show up on the information screen in the personnel tab (Use any of the included campaigns in the MekHQ 0.48.0 download, we will take Black Widow Company, Church's Independent Company, Wolf's Dragoons as an example).

### Files
[megameklog.txt](https://github.com/MegaMek/mekhq/files/6095322/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6095323/mekhqlog.txt)
![MekHQ bug](https://user-images.githubusercontent.com/62211084/110207219-472e5880-7e82-11eb-8c97-6633ad02df4b.png)

**Comment by sixlettervariables** [comment]
You need to enable Advanced Medical under Campaign Options:
![image](https://user-images.githubusercontent.com/8238690/110209753-218e5880-7e5c-11eb-8776-8bc16359861e.png)

Then you will see the injury pane:
![image](https://user-images.githubusercontent.com/8238690/110209771-310da180-7e5c-11eb-9d96-4aa7124dd4f5.png)
