### ISSUE TITLE
campaign not loading

### ISSUE THREAD

**Issue by mchapman1970** [MegaMek/mekhq#2459]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
What version of MekHQ does your issue apply to? 0.48.0
What operating system are you using?  Windows, Mac, or Linux? windows
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file. 11
(Delete the above lines)

### Description
Describe the issue and provide screenshots ingame if able.  just not opening on some of my campaign files
[megameklog.txt](https://github.com/MegaMek/mekhq/files/6131754/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6131755/mekhqlog.txt)
[customs.zip](https://github.com/MegaMek/mekhq/files/6131758/customs.zip)
[1st Federation Army30310101.zip](https://github.com/MegaMek/mekhq/files/6131771/1st.Federation.Army30310101.zip)

Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the campaign file if applicable.
(Delete the above lines)

### Files
Provide the .cpnx campaign file that this issue occurs in.
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the megameklog.txt and mekhqlog.txt files for any NPE's or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual megameklog.txt and mekhqlog.txt files
(Delete the above lines)

**Comment by sixlettervariables** [comment]
The exception is for an equipment part that does not have a type, which gets filtered out eventually. Not sure why it wasn't filtered out by that point.
