### ISSUE TITLE
RAT Generator doesn't seem to generate any VTOLs.

### ISSUE THREAD

**Issue by jsv** [MegaMek/mekhq#246]
When using the RAT generator, I never see any VTOLs on unit markets, nor I'm able to get one using GM tools/RAT Roller. If I switch to traditional tables, I start seeing a decent amount of Ferrets and Warriors.

**Comment by scJazz2** [comment]
If you are using AtB there is an option to not generate VTOLs. It is on by default because Princess can not use them correctly.

**Comment by jsv** [comment]
I'm aware of that, but as far as I know that option is not supposed to affect market generation and RAT Roller. If I use xotl tables instead of the RAT generator, I still see VTOLs on the market even if they are excluded from opfor generation.
If Megamek's random army creation dialog is anything to judge by, the new RAT generator by default do not include VTOLs in tank tables it generates. You can either request a VTOL table (treating VTOL as a separate unit type); or you can ask for the tank unit type, but when you do that, VTOL movement subtype is off by default.
