### ISSUE TITLE
Option to hide completed missions

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/mekhq#2460]
### Environment
Ver 0.48.0

### Description
As title says. Each times I end a contract or mission, it is stacked in the 'current mission' tab of Briefing Room. And it makes me very annoying to actually track the active mission, for the tab has every single missions what I have played. Can we just get rid of completed missions on the tab, and check the list of completed missions on elsewhere?

**Comment by gsparks3** [comment]
While not a code-fix, one thing I do is to edit the mission name, which you can still do post-completion. Makes it much easier to tell the difference between completed and active missions.

**Comment by Windchild292** [comment]
Just double checking, you mean this? 
![Temp](https://user-images.githubusercontent.com/39067288/110983707-16459c00-8338-11eb-976b-8a2457c5661b.png)

**Comment by Windchild292** [comment]
Just double checking, you mean this? 
![Temp](https://user-images.githubusercontent.com/39067288/110983707-16459c00-8338-11eb-976b-8a2457c5661b.png)

**Comment by binaryspica** [comment]
Exactly. The list is gone too long when I play the campaign for a long time, and I have to remove to get rid of it but I don't want to remove the memory of old missions.

**Comment by Windchild292** [comment]
I don't see the issue there? The current missions are always at the top, then they are sorted by status. I could move the status to the front of the name?

**Comment by binaryspica** [comment]
It would be better I think. The part of the annoying thing is the longer mission names(missions generated by AtB has randomly generated codes so the contract name is usually very long) so I can't check if what is the active missions right now.

**Comment by gsparks3** [comment]
You can change those randomly generated codes as well f(or each mission); I would strongly recommend it given how long and un-descriptive they are. It's just a default identifier to start with.

**Comment by Windchild292** [comment]
Would a default formatting like mine above be better?

{{Starting Year}} - {{Employer Code}} - {{Planet}} {{Mission Type}}

**Comment by binaryspica** [comment]
Sure it is definitely better. 

Although adding the month of the contract seems better for me, for sometimes the contract only lasts for some months and you may have more than one contracts per a year. As your example you have two contracts on 2953. But perhaps around two to three at most per a year and sorted by the end date is already enough.

**Comment by Windchild292** [comment]
![Temp](https://user-images.githubusercontent.com/39067288/110999275-223c5880-834e-11eb-852f-7e20513a87e8.png)
Yeah... not sold on how this looks. Visually the original version is significantly better. I've got a backend start date sort added, and swapped the naming style around. I think I'll keep those two parts, and revert them starting with their status.
