### ISSUE TITLE
[48.0] Duplicate subcontract cannot be accessed

### ISSUE THREAD

**Issue by Tecmes** [MegaMek/mekhq#2485]
As you can see in the savefile, there are three active contracts. However two have the same name ("New Subcontract") and when trying to view them, only one can be seen. It is evident in the save because there is a pending battle in the second subcontract, but it can't be accessed and therefore can't be run.
[Subcontract_Bug.cpnx.gz](https://github.com/MegaMek/mekhq/files/6216349/Subcontract_Bug.cpnx.gz)

**Comment by Tecmes** [comment]
I tried manually editing the cpnx and changing the duplicate names, and it fixes the issue, which proves that it just is a matter of making sure there are no duplicates... (or using the ID rather than the name I guess!)

**Comment by Windchild292** [comment]
I decided to swap this over to use objects instead of the string and id, which should guarantee no duplication.
