### ISSUE TITLE
48.0 MekHQ does not allow the purchase of units of any kind.  

### ISSUE THREAD

**Issue by screamingbluemessiah** [MegaMek/mekhq#2486]
### Environment
48

### Description
MekHQ does not allow the purchasing of units (of any kind)
![image](https://user-images.githubusercontent.com/81521878/112756623-0d99ca80-8fb4-11eb-87d4-6e78190931b5.png)

**Comment by Windchild292** [comment]
I'd require your campaign file (.cpnx or .cpnx.gz), any customs, your log files (megameklog.txt and mekhqlog.txt), and a pair of checks on your end to ensure that there is a mechfiles folder containing 'Mechs and that you have at least one of the purchase IS and purchase Clan options enabled.

**Comment by screamingbluemessiah** [comment]
megamek, meklab all work.  it is only mekhq that can't seem to find files.  Nothing has been moved from the install locations.  Previous version worked with the same settings I am currently using.  None of the campaigns work.  I have attached a brand new campaign along with the txt files and a screen shot of the folders.   
















    On Sunday, March 28, 2021, 11:30:47 AM EDT, Justin Bowen ***@***.***> wrote:  
 
 


I'd require your campaign file (.cpnx or .cpnx.gz), any customs, your log files (megameklog.txt and mekhqlog.txt), and a pair of checks on your end to ensure that there is a mechfiles folder containing 'Mechs and that you have at least one of the purchase IS and purchase Clan options enabled.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.



| 
| 
| 
|  |  |

 |

 |
| 
|  | 
48.0 MekHQ does not allow the purchase of units of any kind. · Issue #...

Environment 48 Description MekHQ does not allow the purchasing of units (of any kind) Files
 |

 |

 |





| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Build software better, together

GitHub is where people build software. More than 56 million people use GitHub to discover, fork, and contribute ...
 |

 |

 |




  
MMRandom: generating RNG type #1
Parsing customWeaponOrder.xml
...Parsing finished.
	Total number of custom weapon order entries: 0
mod_weapons failed for Shen Long Battle Armor [David Light Gauss] - Invalid quirk!
mod_weapons failed for Shen Long Battle Armor [Interdictor] - Invalid quirk!
mod_weapons failed for Shen Long Battle Armor [MG] - Invalid quirk!
mod_weapons failed for Shen Long Battle Armor [MRM] - Invalid quirk!
mod_weapons failed for Shen Long Battle Armor [Pop-Up Mine] - Invalid quirk!
mod_weapons failed for Shen Long Battle Armor [SRM] - Invalid quirk!
mod_weapons failed for Taranis Battle Armor (Standard) - Invalid quirk!
mod_weapons failed for Shen Long Battle Armor [David Light Gauss] - Invalid quirk!
mod_weapons failed for Shen Long Battle Armor [Interdictor] - Invalid quirk!
mod_weapons failed for Shen Long Battle Armor [MG] - Invalid quirk!
mod_weapons failed for Shen Long Battle Armor [MRM] - Invalid quirk!
mod_weapons failed for Shen Long Battle Armor [Pop-Up Mine] - Invalid quirk!
mod_weapons failed for Shen Long Battle Armor [SRM] - Invalid quirk!
mod_weapons failed for Taranis Battle Armor (Standard) - Invalid quirk!
mod_weapons failed for Nagasawa (Standard) - Invalid quirk!
mod_weapons failed for Cheetah OF-17A-R - Invalid quirk!
mod_weapons failed for Corax C - Invalid quirk!
mod_weapons failed for Umbra RF-1 - Invalid quirk!
mod_weapons failed for Scytha XR - Invalid quirk!
mod_weapons failed for Starfire SF-1X (Prototype) - Invalid quirk!
Security framework of XStream not explicitly initialized, using predefined black list on your own risk.
ammo_feed_problems	RT	1	SRM 2 failed for Sentinel STN-3K - Small Laser != SRM 2
stable_weapon	RA	2	CLLBXAC5 failed for Man O' War (Gargoyle) Prime - SRM 6 != CLLBXAC5
stable_weapon	RA	6	CLSRM6 failed for Man O' War (Gargoyle) Prime - LB 5-X AC != CLSRM6
stable_weapon	LA	2	CLLBXAC5 failed for Man O' War (Gargoyle) Prime - SRM 6 != CLLBXAC5
stable_weapon	LA	6	CLSRM6 failed for Man O' War (Gargoyle) Prime - LB 5-X AC != CLSRM6
mod_weapons	CT	11	Small Laser failed for Mercury MCY-97 - MASC is not a weapon!
mod_weapons	CT	11	Small Laser failed for Mercury MCY-99 - MASC is not a weapon!
ammo_feed_problems	RT	1	ISStreakSRM2 failed for Sentinel STN-3L - Small Laser != ISStreakSRM2
stable_weapon	RA	2	CLERMediumLaser failed for Man O' War (Gargoyle) T - Streak SRM 6 != CLERMediumLaser
stable_weapon	RA	3	CLERMediumLaser failed for Man O' War (Gargoyle) T - Streak SRM 6 != CLERMediumLaser
stable_weapon	RA	4	CLERMediumLaser failed for Man O' War (Gargoyle) T - ProtoMech AC/8 != CLERMediumLaser
stable_weapon	RA	5	CLERMediumLaser failed for Man O' War (Gargoyle) T - ProtoMech AC/8 != CLERMediumLaser
stable_weapon	RA	6	CLERMediumLaser failed for Man O' War (Gargoyle) T - ProtoMech AC/8 != CLERMediumLaser
stable_weapon	RA	7	CLERMediumLaser failed for Man O' War (Gargoyle) T - ProtoMech AC/8 != CLERMediumLaser
stable_weapon	LA	2	CLATM9 failed for Man O' War (Gargoyle) T - Streak SRM 6 != CLATM9
stable_weapon	LA	6	TSEMP Cannon failed for Man O' War (Gargoyle) T - ProtoMech AC/8 != TSEMP Cannon
ammo_feed_problems	RT	1	SRM 2 failed for Sentinel STN-3K - Small Laser != SRM 2
stable_weapon	RA	2	CLLBXAC5 failed for Man O' War (Gargoyle) Prime - SRM 6 != CLLBXAC5
stable_weapon	RA	6	CLSRM6 failed for Man O' War (Gargoyle) Prime - LB 5-X AC != CLSRM6
stable_weapon	LA	2	CLLBXAC5 failed for Man O' War (Gargoyle) Prime - SRM 6 != CLLBXAC5
stable_weapon	LA	6	CLSRM6 failed for Man O' War (Gargoyle) Prime - LB 5-X AC != CLSRM6
mod_weapons	CT	11	Small Laser failed for Mercury MCY-97 - MASC is not a weapon!
mod_weapons	CT	11	Small Laser failed for Mercury MCY-99 - MASC is not a weapon!
ammo_feed_problems	RT	1	ISStreakSRM2 failed for Sentinel STN-3L - Small Laser != ISStreakSRM2
stable_weapon	RA	2	CLERMediumLaser failed for Man O' War (Gargoyle) T - Streak SRM 6 != CLERMediumLaser
stable_weapon	RA	3	CLERMediumLaser failed for Man O' War (Gargoyle) T - Streak SRM 6 != CLERMediumLaser
stable_weapon	RA	4	CLERMediumLaser failed for Man O' War (Gargoyle) T - ProtoMech AC/8 != CLERMediumLaser
stable_weapon	RA	5	CLERMediumLaser failed for Man O' War (Gargoyle) T - ProtoMech AC/8 != CLERMediumLaser
stable_weapon	RA	6	CLERMediumLaser failed for Man O' War (Gargoyle) T - ProtoMech AC/8 != CLERMediumLaser
stable_weapon	RA	7	CLERMediumLaser failed for Man O' War (Gargoyle) T - ProtoMech AC/8 != CLERMediumLaser
stable_weapon	LA	2	CLATM9 failed for Man O' War (Gargoyle) T - Streak SRM 6 != CLATM9
stable_weapon	LA	6	TSEMP Cannon failed for Man O' War (Gargoyle) T - ProtoMech AC/8 != TSEMP Cannon
Loading atlas: data\images\units\defaults\defaults_atlas.png
Loading atlas: data\images\units\DamageDecals\DamageDecals_atlas.png
Loading atlas: data\images\units\mechs\mechs_atlas.png
Loading atlas: data\images\units\mechs\mechs_atlas.png
Loading atlas: data\images\units\mechs\mechs_atlas.png
Loading atlas: data\images\units\defaults\defaults_atlas.png
Loading atlas: data\images\units\mechs\mechs_atlas.png
Loading atlas: data\images\units\mechs\mechs_atlas.png
Loading atlas: data\images\units\mechs\mechs_atlas.png
Loading atlas: data\images\units\mechs\mechs_atlas.png
Loading atlas: data\images\units\fighter\fighter_atlas.png
mod_weapons failed for Shen Long Battle Armor [David Light Gauss] - Invalid quirk!
mod_weapons failed for Shen Long Battle Armor [Interdictor] - Invalid quirk!
mod_weapons failed for Shen Long Battle Armor [MG] - Invalid quirk!
mod_weapons failed for Shen Long Battle Armor [MRM] - Invalid quirk!
mod_weapons failed for Shen Long Battle Armor [Pop-Up Mine] - Invalid quirk!
mod_weapons failed for Shen Long Battle Armor [SRM] - Invalid quirk!
mod_weapons failed for Taranis Battle Armor (Standard) - Invalid quirk!

**Comment by HammerGS** [comment]
I don't see the attachments only a partial list from a log.

**Comment by Windchild292** [comment]
Attachments only go through properly when you post on GitHub, not when you reply to the email.

**Comment by screamingbluemessiah** [comment]
[My Campaign30670117.cpnx.gz](https://github.com/MegaMek/mekhq/files/6218196/My.Campaign30670117.cpnx.gz)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6218198/mekhqlog.txt)
![image](https://user-images.githubusercontent.com/81521878/112770165-5fae1080-8ff3-11eb-9321-5eeb9a2e54d5.png)
[Uploading megameklog.txt…]()

**Comment by Windchild292** [comment]
I cannot recreate using the provided campaign file. I'd delete the units.cache, that should resolve the issue. If it does not, please post the megameklog.txt, as I cannot open the provided one.

**Comment by screamingbluemessiah** [comment]
Deleting the units cache fixed the problem.  Thanks!

**Comment by Windchild292** [comment]
Glad it's working, closing this
