### ISSUE TITLE
Break up long garrison contracts with alternate enemies

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#2487]
Garrison contracts can stretch out to a year and half to two years.  That's a long time to be facing yet more of the same of what the contract-defined enemy is.  It would be nice if the contract was less "Fight this specific enemy for ___ years" and more "Protect this location against all threats".

To do this, most of the time the OpFor would be the enemy defined in the contract.  But once in a while (particularly if the enemy morale score is very low), this would be switched up for a few scenarios to a different enemy.  This would be based on the system location, with pirates always being a possibility.  Once those scenarios are resolved it will switch back to the contract defined one.

This would require doing something to handle the Enemy Morale score.  Potentially, the score for the main OpFor would be tracked separately from the current setting, with the latter being used for whoever is current.  Or the main OpFor score is cached when the alternate shows up, and is restored after.

**Comment by binaryspica** [comment]
I don't think that low moral changes the enemy, although the moral do affects rate of attack from the faction.

Can't they have multiple enemy at once? If you are keep defend a place, then it is your opponent who choose to fight or not, not you.

**Comment by NickAragua** [comment]
I'm thinking, every time you hit 'rout' on a defensive contract, you get a new set of bad guys.

**Comment by SuperStucco** [comment]
I dig it - it gets around the problem of having to cache/restore morale or other settings.

It could also be combined with the opposition rating i.e. green opponents would bow out when they first hit rout, while elite ones could be at rout for several weeks before dropping out.
