### ISSUE TITLE
v0.46 PSRX Personnel Files not importing into 0.48

### ISSUE THREAD

**Issue by TriplerSDMB** [MegaMek/mekhq#2489]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
What version of MekHQ does your issue apply to?
Windows 10 10.0, Java 1.8.0_281

### Description
In establishing a new CPNX file (migrating from stable 0.46 to 0.48), I exported my unit personnel to a PRSX file, with the intent on importing them into v0.48 stable MegaMek.  I can find the file, but personnel do not load into the unit, nor seem to appear after saving the campaign file.  I don't think the import of PRSX files is working correctly

### Files
CPNX File and PRSX files attached
[19 SDMB30560901 (Benchmark File PAX Mechs Awards and Pay setup).zip](https://github.com/MegaMek/mekhq/files/6253600/19.SDMB30560901.Benchmark.File.PAX.Mechs.Awards.and.Pay.setup.zip)

**Comment by Windchild292** [comment]
Bug in loading awards

**Comment by TriplerSDMB** [comment]
After seeing **Windchild292**'s comments, I went back into the 0.46 CPNX file, removed all awards from personnel, and re-exported them to a new PRSX file.  I then opened 0.48 and was sucessfully able to import the personnel to the unit.
