### ISSUE TITLE
RFE: Allow Extra Time on Maintenance

### ISSUE THREAD

**Issue by ndilday** [MegaMek/mekhq#2491]
Reading over _Strategic Operations_, it seems like the modifiers for taking extra time should also be allowed on maintenance checks. This could be accomlished by adding an additional menu options in the Hangar to modify the maintenance of a specific unit with extra time (and rush maintenance, I suppose).

**Comment by NickAragua** [comment]
Looking at it in a little more detail, extra time is allowed for maintenance checks, but not 'rush'. 

This will make those maintenance rules a little less nightmarish to use, though especially for units just starting out with all green techs and such.

**Comment by NickAragua** [comment]
Implemented with #2537
