### ISSUE TITLE
release-win-java8 - mekhq-windows-0.49.0-SNAPSHOT - Unable to launch contract *StratCon*

### ISSUE THREAD

**Issue by sldfgunslinger2766** [MegaMek/mekhq#2498]
### Environment
What version of MekHQ does your issue apply to? release-win-java8 - mekhq-windows-0.49.0-SNAPSHOT
What operating system are you using?  Windows, Mac, or Linux? Win 10  Pro, 20H2-19042.867
What java version are you using?  Open JDK 11

### Description
When attempting to generate/launch a contract, after pressing 'Accept' to start a contract, the contract does not disappear from the list and it doesn't seem to 'start'. The advance fee for the contract is paid and shows in the Finances tab, but the actual contract name does not appear anywhere in the Briefing Room or StratCon tabs. I have also attepted to transit to the contract planet and advance days until the contract starts, with no success. 

### Files
[Logs-Settings-Screenshots.zip](https://github.com/MegaMek/mekhq/files/6281786/Logs-Settings-Screenshots.zip)

**Comment by Kailan7401** [comment]
I'm having the identical issue, also using Open JDK 11, Win 10, and a fresh campaign. To add to the above, I found that unchecking stratcon in the options does allow me to start a contract, but as expected, re-enabling stratcon once the it has been accepted borks (technical computer terminology, I know) the campaign.

**Comment by NickAragua** [comment]
[data.zip](https://github.com/MegaMek/mekhq/files/6282467/data.zip)

This was due to some data folders missing from the build script. The attached zip file contains the missing folders, unzip it into your data subdirectory. Leaving this open for now so others can find it as well.

**Comment by NickAragua** [comment]
Anyone that downloads the build from after this was fixed will get the correct data files, so this can be closed out.
