### ISSUE TITLE
0.49-DEV-StratCon: Active old-style contract functions but generates many NPEs

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/mekhq#2499]
### Environment
StratCon alpha test build
Windows 10
OpenJDK 11.0.10

### Description
When turning on the "Use StratCon campaign rules" campaign option with an old-style contract active, the old contract continues to function as it did previously, with no visible issues in MekHQ, but many NPEs show up in the logs. Might need to be looked into for compatibility/error-handling purposes at some point. Logs provided for informational purposes, game save provided for reproduction purposes. 

### Files
[CoppercoatsTest.cpnx.gz](https://github.com/MegaMek/mekhq/files/6282735/CoppercoatsTest.cpnx.gz)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/6282742/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6282743/mekhqlog.txt)

**Comment by NickAragua** [comment]
Fixed with commit 52905d6975e3cd97a4babfbb3b2093702769b837
