### ISSUE TITLE
0.49-DEV-StratCon - Units deployed to incorrect Track

### ISSUE THREAD

**Issue by Kailan7401** [MegaMek/mekhq#2500]
### Environment
StratCon alpha test build
Windows 10
OpenJDK 11.0.10

### Description
Deployed Units show up on Track 0 regardless of which track you attempt to assign them to. In the below example I attempted to deploy a unit to 6,4 Track 1, but it showed up in 6,4 Track 0. The issues seems to persist no matter which unit I choose or which role they have. Assigning defenders to enemies attacking on Tracks other than 0 works as expected. 

![image](https://user-images.githubusercontent.com/32316785/114260758-cbd83d80-9a11-11eb-853b-81411d138f98.png)
![image](https://user-images.githubusercontent.com/32316785/114260823-1063d900-9a12-11eb-8f05-5d005efe70c4.png)

### Files
[Campaign Info.zip](https://github.com/MegaMek/mekhq/files/6289347/Campaign.Info.zip)
(I'm not sure how to find the error log, I can add that if needed)

**Comment by NickAragua** [comment]
Fixed with commit aed743fbfb83156948808ac6e325d6b1cc2608a3
