### ISSUE TITLE
0.49-DEV-StratCon - Visual Bug with Camo Assignment on Contract Screen

### ISSUE THREAD

**Issue by Kailan7401** [MegaMek/mekhq#2501]
### Environment
StratCon alpha test build
Windows 10
OpenJDK 11.0.10

### Description
Clicking on Edit Mission in the Briefing Room and changing Ally Camo visually shows the changed camo to appear as the Enemy Camo. Clicking Ok and returning to the screen fixes the issue and the camo is shows on the correct faction. I double checked and the issue doesn't seem present in .48 Stable. The reverse (Changing Enemy Camo) seems to work without issue.

![image](https://user-images.githubusercontent.com/32316785/114261069-7e5cd000-9a13-11eb-8b8b-82e46e2f5d11.png)
![image](https://user-images.githubusercontent.com/32316785/114261088-a4827000-9a13-11eb-9e06-41aa42b5959d.png)
![image](https://user-images.githubusercontent.com/32316785/114261113-cf6cc400-9a13-11eb-9355-a9695696c0f4.png)
![image](https://user-images.githubusercontent.com/32316785/114261133-eca19280-9a13-11eb-9af9-4081fd4cf91f.png)

### Steps to Reproduce
Step 1: In Briefing Room, click Edit Mission
Step 2: Click Ally Camo, choose new camo, and confirm
Step 3: Chosen camo visually appears on the Enemy Camo box instead of Ally Camo box.
Step 4: Confirm and reenter Edit Mission tab
Step 5: Camo now correctly appears in Ally Camo box

### Files
[Campaign Info.zip](https://github.com/MegaMek/mekhq/files/6289347/Campaign.Info.zip)
(I'm not sure how to find the error log, I can add that if needed)

**Comment by Kailan7401** [comment]
Edit:

Starting a new game seems to ignore the mission's camo settings for OpFor, and they default to the green color they were assigned when the contract was generated.

![image](https://user-images.githubusercontent.com/32316785/114261546-0f34ab00-9a16-11eb-9519-f832e9f62cf0.png)

**Comment by Windchild292** [comment]
Was the latter an already generated scenario @Kailan7401? We don't make changes to previously generated but uncompleted scenarios when the camouflage is edited, so that would be expected. The first issue is a copy-paste error on my end.
