### ISSUE TITLE
0.49-DEV-StratCon - (Suggestion) Various UI Improvements

### ISSUE THREAD

**Issue by Kailan7401** [MegaMek/mekhq#2502]
### Environment
StratCon alpha test build
Windows 10
OpenJDK 11.0.10

### Description
Allowing options in the Scenario Setup Wizard to sort alphabetically or by BV would be super helpful!
![image](https://user-images.githubusercontent.com/32316785/114261233-6a659e00-9a14-11eb-86ed-59963e0c9db7.png)

Changing the font color and/or making the font bold for friendly units on the map screen would help readability
![image](https://user-images.githubusercontent.com/32316785/114261293-bdd7ec00-9a14-11eb-84c8-d3d0327850bd.png)

**Comment by NickAragua** [comment]
Due to laziness, changed force list to sort by alphabetical order. Blue player force text and boxes changed to cyan. If that doesn't work, I'll have to look at some kind of dynamic coloring scheme based on the color of the underlying hex.

**Comment by NickAragua** [comment]
We'll consider this one completed for now, can revisit it later if the changes made don't cut the mustard.
