### ISSUE TITLE
0.49.0-SNAPSHOT (Stratcon) = Deployed Lances do not return

### ISSUE THREAD

**Issue by PadraigTseng** [MegaMek/mekhq#2504]
### Environment
MekHQ 0.49.0-SNAPSHOT
Windows 10
Java vendor AdoptOpenJDK
Java version 11.0.10

### Description
Deployed Lances do not return when they are supposed to.  Attached Save is 2/22/3025 and all should have returned but have not.

### Files
[Grimm Bastards30250222.cpnx.gz](https://github.com/MegaMek/mekhq/files/6290523/Grimm.Bastards30250222.cpnx.gz)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/6290526/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6290527/mekhqlog.txt)

**Comment by NickAragua** [comment]
Fixed with commit fde52dde21e6d6cc956e34fc3f2cbd477e99e461

For some reason, there was a phantom scenario attached to the track with no deployment/resolution/return date. Added code to clean those up.
