### ISSUE TITLE
StratCon - Giving some awards create visual bug on personnel

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#2505]
MekHQ 0.49.0-SNAPSHOT
OpenJDK 11

Giving any award below and including "Longevity" will remove all skill names from the personnel view window. It becomes baked into the save.

**Comment by gsparks3** [comment]
Providing a save with the mentioned bug for reproduction purposes:
[Coppercoats.cpnx.gz](https://github.com/MegaMek/mekhq/files/6291903/Coppercoats.cpnx.gz)

**Comment by Windchild292** [comment]
This may be the return of a bug I thought fixed by Java 11, can I get some logs for this

**Comment by gsparks3** [comment]
Nothing in megameklog, but some suggestive-looking errors in mekhqlog:
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6291983/mekhqlog.txt)

**Comment by Windchild292** [comment]
Yup, that's the same issue.
