### ISSUE TITLE
AtB - Generic Soldier in Personnel Market, with no Unit

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#2516]
Environment
MekHQ 0.48.0
Compiled on 2021-03-05T15:43:22Z
Today is 2021-04-06
Java vendor Oracle Corporation
Java version 1.8.0_281
Platform Windows 10 10.0 (amd64)
Total memory available to MegaMek: 7,456,768 kB

As title - a generic "Soldier" pops up pretty often in the marketplace without a unit.  Perhaps its an intentional filler soldier.  But I would guess its supposed to have a unit attached to it.  I am now in 3060 date range.  I never noticed this happen in earlier dates.  Maybe its an invalid unit or something?  2 Screen examples attached. 

Other info is same campaign and customs as my last post, if that is needed again.
![solo soldier](https://user-images.githubusercontent.com/23645569/114663934-a6bd2680-9cc0-11eb-8181-3fa979ce1858.png)
![Screenshot 2021-04-10 194712](https://user-images.githubusercontent.com/23645569/114663942-aae94400-9cc0-11eb-8a71-29bbd5c87767.png)

**Comment by Kailan7401** [comment]
That's working as intended to my knowledge, I hire them pretty often to replenish my infantry losses.

**Comment by Windchild292** [comment]
Working as intended
