### ISSUE TITLE
0.49-DEV-StratCon - Player can reinforce infinitely through leadership bonuses

### ISSUE THREAD

**Issue by Kailan7401** [MegaMek/mekhq#2520]
### Environment
StratCon alpha test build (MekHQ CI with Gradle #1168: Pull request #2144)
Windows 10
OpenJDK 11.0.10

_Lance Leader to Base
Stop sending reinforcements
The map's already full_

### Description
Right click > managing a scenario that allows additional leadership based reinforcements, you can select your desired reinforcements, close the window, reopen it, and repeat the process infinitely. It's possible to reinforce with your entire TO&E in this fashion
![image](https://user-images.githubusercontent.com/32316785/115035115-2e947200-9f07-11eb-9b5e-41712c7fe5f9.png)

### Files
Save game included with active battle
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6325580/mekhqlog.txt)
[Campaign Info.zip](https://github.com/MegaMek/mekhq/files/6325583/Campaign.Info.zip)

**Comment by NickAragua** [comment]
Fixed with commit ed3e5f5abe005b11fb49a199f3ee32ef849bfb8e
