### ISSUE TITLE
0.49-DEV-StratCon - Battles are not removed from the AtB Campaign State Map when the associated scenario is GM Mode removed

### ISSUE THREAD

**Issue by Kailan7401** [MegaMek/mekhq#2523]
### Environment
StratCon alpha test build (MekHQ CI with Gradle #1168: Pull request #2144)
Windows 10
OpenJDK 11.0.10

_This battle's way to hard
It won't hurt to cheat a bit
Dangit, borked my map :(_

### Description
Removing a pending battle via GM Mode in the Briefing Room results in the battle being removed from the scenario list as intended, but the battle remains in the AtB Campaign State Map forever, taunting me and my poor life choices.

### Files
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6325932/mekhqlog.txt)
[Campaign Info (GM Mode Delete).zip](https://github.com/MegaMek/mekhq/files/6325941/Campaign.Info.GM.Mode.Delete.zip)

**Comment by NickAragua** [comment]
Fixed with commit becffdc94075004fa3890bb36799389a48105c33
