### ISSUE TITLE
0.49-DEV-StratCon - Advanced day forfeited battles still show as pending but are unfightable due to being in the past

### ISSUE THREAD

**Issue by Kailan7401** [MegaMek/mekhq#2524]
### Environment
StratCon alpha test build (MekHQ CI with Gradle #1168: Pull request #2144)
Windows 10
OpenJDK 11.0.10

### Description
Advancing the day while you have a pending battle will show a message stating the battle will end in defeat, but in actuality the battle still shows as pending the next day. While I believe the plan is for this to be intended functionality (?), the battle is unfightable without manually editing the battle to show the correct date.

**Comment by NickAragua** [comment]
Should be fixed with commit 3d8916caadfbc4085e509724142f929fc9d7f1d5
