### ISSUE TITLE
0.49-DEV-StratCon - Selecting multiple reinforcements at a time only rolls once if you have VP available

### ISSUE THREAD

**Issue by Kailan7401** [MegaMek/mekhq#2525]
### Environment
StratCon alpha test build (MekHQ CI with Gradle #1168: Pull request #2144)
Windows 10
OpenJDK 11.0.10

### Description
Right clicking a pending scenario and assigning reinforcements by shift clicking to add multiple units at once only causes one reinforcement roll regardless of how many reinforcements are requested. In my test case, I had 3 VP available and requested 7 lances of reinforcements at once. The 3 VP disappeared as intended, but only one reinforcement roll was made, and all 7 reinforcements were added to the battle. If you attempt to do the above with 0 VP available, however, the reinforcement rolls are made correctly.
![image](https://user-images.githubusercontent.com/32316785/115044420-75d33080-9f10-11eb-9dee-efccfc210b9e.png)
![image](https://user-images.githubusercontent.com/32316785/115044549-956a5900-9f10-11eb-98c2-1d3d97134d25.png)

Corollary: Selecting too many reinforcements at once can scroll the accept button off the screen and force the player to close the window via the top right X button.

**Comment by NickAragua** [comment]
No haiku, no fix.

**Comment by Kailan7401** [comment]
_Kailan's Bug Reports
Concise, informative, but...
no haiku, no fix_

**Comment by NickAragua** [comment]
_Looking at it now,
this no longer happens in
current StratCon build._

Closing for now, but let me know if it happens again.
