### ISSUE TITLE
Destroyed Cockpits

### ISSUE THREAD

**Issue by inqistor** [MegaMek/mekhq#2528]
MekHQ 48.0 under WINDOWS 10. Fresh install, and fresh campaign.

I'm not sure when it occurred, but it seems to happen either in MegaMek, or during transfer of units back to MekHQ, after battle. Most of Mechs somehow have destroyed Cockpits. I suspect it happens after any head hit, but it is just wild guess.
I could be terribly unlucky, but 75% of Mechs with destroyed cockpit, and some of them not even damaged internal head structure, seems suspicious.

MekHQ save
[cockpit.zip](https://github.com/MegaMek/mekhq/files/6335941/cockpit.zip)

MegaMek save
[autosave.sav.gz](https://github.com/MegaMek/mekhq/files/6335948/autosave.sav.gz)

Compressed logs
[logs.zip](https://github.com/MegaMek/mekhq/files/6335963/logs.zip)

**Comment by NickAragua** [comment]
Per this ruling: https://bg.battletech.com/forums/strategic-operations/answered-repairing-an-ejected-cockpit/, when a mechwarrior ejects from a mech, the cockpit is treated as destroyed. For "full head" ejection system, the head is treated as 'blown off'.
