### ISSUE TITLE
Strat Con - Allies Defending Enemy Air Base & Related

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#2530]
### Environment
	Compiled on 2021-04-19T03:22:44Z
	Today is 2021-04-19
	Java vendor AdoptOpenJDK
	Java version 11.0.10
	Platform Windows 10 10.0 (amd64)
	Total memory available to MegaMek: 4,167,680 kB

### Description
2 possible issues:

1.  Found an enemy air base by accident.  A scenario was generated.  However MY ally has an air lance at the enemy air base.  I think it is supposed to be enemy air wing.  Screen attached (DC is my ally - there is no enemy air wing - FRR has 2 mech lances and turrets).  Pretty sure this is a bug.

2.  Not sure on this one.  After completing above scenario - I (ok really mostly my allied air wing from above) destroyed turrets, but not 75% of existing units.  However resolutions screen says base will be considered destroyed.   Not sure if this is intentional, or it is related to the enemy not having an air wing there and it misses them in the count and thus counts the base as destroyed.  Screen attached.
![Allies Set as Defending Airbase](https://user-images.githubusercontent.com/23645569/115340844-19208180-a16d-11eb-94f4-213129e30677.png)
![Destruction of Base](https://user-images.githubusercontent.com/23645569/115340879-28073400-a16d-11eb-86ee-efa238f63e63.png)
![Destruction of Base2](https://user-images.githubusercontent.com/23645569/115340894-2e95ab80-a16d-11eb-87dc-3fdc070087af.png)

I apologize I hit advance day before I saved, but can give you the later cpx file if needed.

Also - some minor things:  All scenarios I am listed as (Defender) even if, like this one, I am clearly the attacker.
May just be a coincidence, but every scenario I have had (out of 5) have all generated on a Monday.  Maybe intentional.
MM does not seem to be generating enemy pilot SPAs for vet plus pilots.  Or if it is, its so rare I cant remember seeing it.  They are generated in the stable release.
Pop-up between "do you want to save all units" in MM and the actual popup where it asks you to save the .mul is very long - like 1 minute.  All buttons freeze during this time.

**Comment by NickAragua** [comment]
The facility generation mechanism was applying the incorrect facility modifers. Unfortunately, this is done at contract creation, so the fix in c4f072fa1b346d244a7d682f0872ce7034f5d6f3 will only apply to future contracts. Also fixed setting scenario dates, they can now occur any time during the week.

A430dcc10a7a51ac34fc883c6433562909a7f4822 removes the unnecessary (Defender) description from the scenario type.

SPAs appear to work, loading up a test scenario showed a Vedette with an SPA. 

Destroying the turrets is all that is required to destroy the facility, you don't even have to touch the mobile units. This is in case the garrison is too tough for you, lets you have the option of getting in with some fast units/aircraft, zapping the buildings and getting out.
