### ISSUE TITLE
StratCon - Allied Turrets generated but not deployed in Capture Scenario

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#2533]
Compiled on 2021-04-19T03:22:44Z
Today is 2021-04-19
Java vendor AdoptOpenJDK
Java version 11.0.10
Platform Windows 10 10.0 (amd64)
Total memory available to MegaMek: 4,167,680 kB

As title.  I am trying to capture an enemy Pilot (killed him with a PPC headshot unfortunately and failed).

Turrets generated in scenario but not deployed.  Screen attached.

![No Allied Turrets](https://user-images.githubusercontent.com/23645569/115439259-fc6b6480-a1d3-11eb-8a47-7db3da254b93.png)

EDIT:  Also - dont have a screen but a Pursuit scenario generated last night - where my team is fleeing.  Allied units did not start with "escape" orders and stayed at south edge and fought.  Restarted scenario and gave them escape order in lobby and they ran properly.

Also - related suggestion - perhaps a right click ability to give an order to a friendly unit mid-match?  Like if I am outmatched and want to retreat and want to order an allied unit to retreat too?

**Comment by NickAragua** [comment]
This is an unfortunate side effect of the procedurally generated maps - turrets can only be deployed on buildings and the map in question does not have buildings. Therefore, the turrets are simply ignored.

To have allied units retreat, you can kick the bot controlling it (/who in the chat window to get a bot listing, then /kick #) then replace it, setting the destination/retreat edges to the desired edge.

As far as the pursuit scenario goes, the "integrated" and "house" units should be fleeing with you but the "primary allies" do not count towards the objective - it's unfair to expect the player to babysit a whole lance of whatever gets spewed out of the RAT generator.

**Comment by Thom293** [comment]
Thank you.  On the pursuit thing, the contract was House and neither the allied officer or extra lance had the escape order.

**Comment by NickAragua** [comment]
I'll take a look at the behavior of the officer bot separately, then.
