### ISSUE TITLE
StratCon - Clan and IS Endo-Steel limbs are mutually substitable

### ISSUE THREAD

**Issue by Zumbleguy** [MegaMek/mekhq#2534]
### Environment
MekHQ 0.49.0-SNAPSHOT 
Windows 7
Java version 11.0.10

### Description
Clan Endo-Steel limbs can be used on IS Endo-Steel equipped Mechs and vice-versa. After I discovered that in an active campaign by accident (after discovering a Clan Endo-Steel right arm on a damaged IS Mech), I decided to check whether it would be reproduced on a fresh MekHQ StratCon install (19/04, specifically) in a fresh campaign.
![Image1](https://user-images.githubusercontent.com/52971972/115438959-b5eb2980-a216-11eb-8dfa-a1db3b99b0c5.png)
![Image2](https://user-images.githubusercontent.com/52971972/115439039-cdc2ad80-a216-11eb-9393-2936869cc80d.png)
Steps taken to reproduce:
1. Added two units with built-in Endo-Steel, one using Clan tech base and the other using the Inner Sphere one.
2. Salvaged limbs by standard procedure (salvaging armor and equipment, then salvaged the limb itself)
3. Sold the limb to avoid it being used in repair.
4. Added the limb of a different tech base.
5. Repaired the Mech using said limb.
I did not test whether this bug would be reproduced using different internal structure types (like Endo-Composite), armor types (like Ferro-Fibrous) or weapons that are available to both tech bases while having different stats. However, it does not seen possible to use TSM-equipped limbs for non-TSM equipped Mechs.
### Files
[Designated Testing Unit30670102.cpnx.gz](https://github.com/MegaMek/mekhq/files/6345608/Designated.Testing.Unit30670102.cpnx.gz)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/6345610/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6345612/mekhqlog.txt)

**Comment by Windchild292** [comment]
I'm pretty sure this isn't caused by StratCon, but rather a separate bug.

**Comment by Zumbleguy** [comment]
> 
> 
> I'm pretty sure this isn't caused by StratCon, but rather a separate bug.

Since I managed to reproduce it on stable, it is a separate bug. Armor works correctly, interestingly enough - it's the limbs that are the problem.

**Comment by Windchild292** [comment]
I don't know the code well, but it is likely a missing isClan check.
