### ISSUE TITLE
StratCom - Convoy Attack has "any" for OpFor and Convoy starting location

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#2536]
Compiled on 2021-04-19T03:22:44Z
Today is 2021-04-19
Java vendor AdoptOpenJDK
Java version 11.0.10
Platform Windows 10 10.0 (amd64)
Total memory available to MegaMek: 4,167,680 kB

Title.  Screens attached.  Obviously needs a starting edge for this particular scenario.

Also 2nd screen shows the Any in MM, and that some some 2/3 and 2/4 pilots are not getting SPAs in MM.  This may be intentional, or it may be a result of me disabling some of them in MHQ (the TerrainMaster and sensor geek ones, specifically).  Not sure if all vet and elite pilots are supposed to get SPAs, but Just wanted to point it out just in case. (split into #2643)
![Convoy attack deploy3](https://user-images.githubusercontent.com/23645569/115468054-19b22a00-a1f8-11eb-997e-416d200ea240.png)
![Convoy attack deploy and SPA](https://user-images.githubusercontent.com/23645569/115468149-46664180-a1f8-11eb-91fd-0afd7c7d2fac.png)

**Comment by Windchild292** [comment]
The latter is a bug on my list, but I'm not sure it's been raised before.

**Comment by Windchild292** [comment]
Also, try to keep it to one topic per issue

**Comment by Thom293** [comment]
> Also, try to keep it to one topic per issue

Will do.  Sorry didnt want to spam.

**Comment by Windchild292** [comment]
Split the second into #2643

**Comment by Thom293** [comment]
Tested this a number of times today, seem to be working now.  Seems to have been fixed as a side effect of another change.  I dont think you can generate as a "Convoy Attack (Defender)" any more.  Closing.
