### ISSUE TITLE
AtB Allow Custom Modify % Chance of Battle by Role

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#254]
First - I must thank the team for the mass salvage/repair option.  It reduces the only tedious part of the game.  Thanks.

So here, a low priority suggestion:

In campaign options, on AtB tab, it lists chance of battle by role, and has an "intensity" ticker that is modifiable.  However, it increases or decreases the chance for ALL types in lock-step fashion.  This is useful, but perhaps an additional option.

Request:

Make the %s individually modifyiable.  I love bug battles, but they overwhelm it at some times.  So for instance I would like to manually change Scout to 20%, and Fight and Defend to 60%, etc.

Again - just a suggestion.  Thanks for the great product.

**Comment by neoancient** [comment]
The requirement deployment role is not only the one most characteristic of the mission type, but it sets the tempo of the mission. Raid contracts are supposed to be high-intensity. That's part of the reason the pay is higher. If you lower the frequency of scout battles relative to the others, it throws everything off.

**Comment by VampireSeraphin** [comment]
It would be nice to be able to set the intensity to 0 though for those cushy contracts deep in safe space. Right now 0.1 is the lowest possible IIRC.

**Comment by neoancient** [comment]
Who hires mercenaries to garrison worlds deep in safe space?

**Comment by pheonixstorm** [comment]
Fluff wise all the houses. It frees up the more reliable house units. I would have to look it up but there are several instances of mercs being hired to free up house units so they could be moved to the frontlines.

As for this.. the suggestion is off the mark slightly. The roles are fine, but the overall tempo should be set per contract. Garrison should have a much lower tempo while raids would be much higher.

**Comment by Thom293** [comment]
Yeah - I understand that scout battles are priority in some contracts.  All I was asking is the option to modify it for personal reasons.  Light mech battles become so common that they get old, and my heavy and assault lances almost never fight.  All of my best pilots are in my scout lances because they fight every week, and a heavy fights every 3.  I was asking for the option to change the "chance for battle by role" to customize.  For instance, I was going to change scouting to 20% and fight and defend to 60% each.  It is just a customization option.  Its just another way of changing intensity (which is already a option) by weight class/role.

I know some medium lances cant fit in the scout role, but some of the scout fights are bad matches even for medium lances.
