### ISSUE TITLE
Artemis FCS Not Sharing Location Missing Error Message

### ISSUE THREAD

**Issue by Dzlan** [MegaMek/mekhq#2546]
![Capture](https://user-images.githubusercontent.com/22495256/116392563-b027c080-a874-11eb-8049-079d7d2e0ada.PNG)
### Environment
0.48.0
Windows
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.
openjdk 11 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

### Description
Attempted to edit a mech to a Clan/Innersphere Mix
[Dzlan SP.cpnx.gz](https://github.com/MegaMek/mekhq/files/6391257/Dzlan.SP.cpnx.gz)

[megameklog.txt](https://github.com/MegaMek/mekhq/files/6391264/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6391267/mekhqlog.txt)

**Comment by HammerGS** [comment]
Was this the unit you mentioned in Discord where you placed the Artemis in the wrong place?

**Comment by Windchild292** [comment]
Looks like it. That shouldn't have been allowed to save, and I note a few other errors in the logs.

**Comment by Windchild292** [comment]
Fixed the other log errors in https://github.com/MegaMek/megamek/pull/2802 and https://github.com/MegaMek/megamek/pull/2803

**Comment by Dzlan** [comment]
I spent some time comparing my build to the original before narrowing it down to the Artemis FCS not being in the same limb as the LRM20 Artemis.
Wasn't aware it was a requirement.

Thanks,

**Comment by Windchild292** [comment]
This has been fixed in MML
