### ISSUE TITLE
AtB SPAs for AI pilots in MM

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#255]
Another low priority issue. 

When AtB generates a battle and you start the scenario and switch to MM, veteran/elite enemy pilots there dont get any Special Pilot Abilities (whereas ones generated via the Personnel Market do have them).  Is that addable without too much trouble?  SPAs wont always be useful to the bot because of how it will roll gunnery SPAs that arent always applicable to the specific weapon/mech, but general ones like Sniper, Melee Master, Hot Dog, Hopping Jack, etc would be helpful to the bot if it gets lucky with a roll and might sometimes increase difficulty.  Even if it rolls one that isnt helpful in the specific battle, it would come into play when you convince a prisoner to defect.

Just an idea.

**Comment by pheonixstorm** [comment]
It wouldn't be too difficult I think, but it would first (probably) need to be added to the core AtB rules before it would be added into MekHQ.

Also, not everyone uses SPAs so that would also have to be taken into account.

**Comment by Thom293** [comment]
Oh yeah I guess it technically is not part of those rules.  Its default for your people, but not for the OpFor.  I didnt consider that.

Perhaps a MM option?  AtB wouldnt have to be futzed with then...

**Comment by neoancient** [comment]
It's been requested several times. After the next stable release I plan to overhaul opfor generation and I'll look at doing it then.

**Comment by pheonixstorm** [comment]
Actually it isn't the default setting for the player usually. At least not for standard HQ play. I don't think it is the default for AtB either.

**Comment by Thom293** [comment]
I am pretty sure it is the default AtB setting.  Pilots get a "free" SPA when they hit veteran and elite levels.  Others can be purchased for XP.  The Personnel market generates them correctly, and it also auto-assigns the free SPA when you advance their piloting/gunnery to the correct level.  It only seems that the MM OpFor pilots dont get them.  Perhaps I am remembering incorrectly, but I think it is the AtB default as it is something you have to do during company creation.  

Regardless, thanks for looking at the issue.

On a somewhat related note, when is the last time Princess was updated?  She seems a little smarter to me, but that may just be because I am rusty.

**Comment by NickAragua** [comment]
Randomly generated non-player units in AtB are able to get SPAs as of PR #1235
