### ISSUE TITLE
Infantry Salvage Values are absurdly high.

### ISSUE THREAD

**Issue by Dzlan** [MegaMek/mekhq#2552]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
0.48.0
Windows 10
openjdk 11 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

### Description
![Capture](https://user-images.githubusercontent.com/22495256/116495869-e6f2ea80-a8f7-11eb-9f47-59d0c2c79f6b.PNG)

I notice infantry have absurd values in salvage screen. You can get this full amount via ransom.

### Files
[megameklog.txt](https://github.com/MegaMek/mekhq/files/6395971/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6395978/mekhqlog.txt)

**Comment by Thom293** [comment]
Came here to post same thing.  My screen is from Dev Snapshot.  Note field gunners and Mechanized bridgelayer.

![Screenshot 2021-04-28 221202](https://user-images.githubusercontent.com/23645569/116498389-3fca7080-a86f-11eb-831f-c1f4833a2b5c.png)

**Comment by HammerGS** [comment]
These are RAW see Tech Manual pg 276

_Darrell’s conventional infantry platoon is a motorized formation of 28 troopers. These troops possess standard laser rifles as a Primary weapon, and carry no Secondary weapons. After consulting the Conventional Infantry Weapons costs table (pp. 298-301), Darrell looks up the cost of the laser rifle (1,250 C-bills), and finds that the base trooper cost for the platoon will be 70,710.678 C-bills (2,000
x √[1,250] = 70,710.678). As these troops are motorized, this base per-trooper cost becomes 113,137.085 C-bills (70,710.678 x 1.6 for motorized = 113,137.085). The entire 28-man platoon costs 3,167,838 C-bills (113,137.085 x 28 = 3,167,838.38, rounded down to 3,167,838). This is considered
the platoon’s final value (unless Darrell chooses to spring for anti-’Mech training)._

If made Anti-Mek then multiply that by 5.

**Comment by Thom293** [comment]
Wow.  Well, not sure if its possible to just errata it for MHQ or give them a salvage value of zero or something.  

6 infantry platoons is approx 84M Cbills for salvage.  Approximately 4 lances of Heavy + mechs in 3050.

**Comment by HammerGS** [comment]
> 6 infantry platoons is approx 84M Cbills for salvage. Approximately 4 lances of Heavy + mechs in 3050.

Yep, sell the infantry and retire.

**Comment by Humonitarian** [comment]
How I interpret it, the cost of infantry is based on their training costs, which means they include the actual soldiers crewing them, and the years they spent in training reaching a normal Small Arms skill.

For MekHQ and salvage specifically, it would make more sense to calculate the value of these platoons based on their equipment alone.

So counting up the cost of the APCs, weapons and armor (which I've only seen used this way in the MekLab refit tab within MekHQ). The "training" value of soldiers would come back in the form of ransoms from the captured wounded soldier, that is, handled separately.

**Comment by repligator** [comment]
For Battle Armor, MHQ explicitly excludes training costs when purchasing/selling a unit. Perhaps something similar could be implemented for Conventional Infantry?

**Comment by IllianiCBT** [comment]
Closing as resolved
