### ISSUE TITLE
49.0 4/28 Personnel Market Unavailable During Contract

### ISSUE THREAD

**Issue by jschmetzer** [MegaMek/mekhq#2553]
What version of MekHQ does your issue apply to? 49.0 Snapshot as of 4/28
What operating system are you using?  Mac

### Description
Opened new download, started campaign w/ default AtB, GM-added a new active contract, day-advanced to Monday and saw 'Personnel Market Updated' hyperlink. 

Clicking link does nothing, selecting menu option does nothing.

Market is accessible outside active contract dates.

[Pers_Test.zip](https://github.com/MegaMek/mekhq/files/6399132/Pers_Test.zip)

**Comment by Windchild292** [comment]
#2556 and #2557 fix the two bugs raised here, as I found a second one in the logs.
