### ISSUE TITLE
Details not provided on automated personnel removal

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#2558]
After advancing a day on a campaign on 48.0, I was greeted with this:

```
Hujja Fida has been removed from the personnel roster.  
Tähti Hunter has been removed from the personnel roster.  
Private Ciera Burday has been removed from the personnel roster.  
Robert Simechek has been removed from the personnel roster.
```

They don't show up under the Personnel tab, under Inactive or Retired or anywhere else.

I have several hundred personnel, I don't know who is doing what strictly by name.  As most of them have rank of some kind I can sort-of narrow this down to dependent astechs and/or admins, but otherwise have no idea what they were doing.  I am now short personnel in some areas but don't have a means of knowing where.

When personnel are removed like this, there should be some kind of additional information, such as primary/secondary role and unit/force assignment.

Savegame is attached.  There are a few custom units in play, but hopefully not required for looking at this issue.
[Hagaar's Hornets30700101.cpnx.gz](https://github.com/MegaMek/mekhq/files/6401237/Hagaar.s.Hornets30700101.cpnx.gz)

**Comment by Windchild292** [comment]
I'd like a save game before this occurs to make sure about the reasoning @SuperStucco.

**Comment by SuperStucco** [comment]
I've already pushed past the daily autosaves, so the closest I have is this one:
[Hagaar's Hornets30691202.cpnx.gz](https://github.com/MegaMek/mekhq/files/6403087/Hagaar.s.Hornets30691202.cpnx.gz)

**Comment by Windchild292** [comment]
Dependents join and leave as per the AtB Ruleset, which can be enabled/disabled (each side of it) in the AtB Campaign Options Tab.
