### ISSUE TITLE
MM StratCon - 1 minute hang between Save pop ups

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#2559]
Compiled on 2021-04-19T03:22:44Z
Today is 2021-04-19
Java vendor AdoptOpenJDK
Java version 11.0.10
Platform Windows 10 10.0 (amd64)
Total memory available to MegaMek: 4,167,680 kB

Playing through MHQ for StratCom nightly release from yesterday.  Approximate 1 min hang between "Do you want to save a file of all units?" and the save dialoge for the .mul file.  No buttons can be pressed during this hang.  Never happened in any other version for me.  Happens every single time.  Can provide a campaign file if needed.

**Comment by Thom293** [comment]
> Without logs and save this will be very difficult to troubleshoot.

I will gladly supply a log.  Which one?

Although it happens every single time over multiple versions, so I assumed it was not just my system.  Should be able to test by just opening a scenario in megamek through MHQ.  Then /victory in MM and it should give you the delay before you save the .mul file.

**Comment by HammerGS** [comment]
Per the report template. Would need megameklog.txt, MekHQlog.txt, the cpnx file. Steps to recreate.

**Comment by Windchild292** [comment]
Closing due to lack of information and as a StratCon issue predating it's original release, much less the huge number of bugfixes for it since 0.49.0.
