### ISSUE TITLE
RFE: reset unit maintenance location when in transit

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#2563]
During a mission, a deployed unit is assigned a maintenance location/"Site" based on mission type and available support e.g. on a recon raid with an engineering unit equipped with lift hoists, "Field workshop" is selected.  However, when the mission is over and the formation is in transit to another system, the maintenance location is still listed as "Field workshop" despite the unit no longer being in the field (or even on planet).  This affects maintenance checks performed while in transit.

When a mission is finished, please have unit maintenance locations reset.  The easiest way is to simply set all to "Transport Bay", but bonus points for having campaign settings which allow setting different locations by unit type (Mech, Tank, etc.).  For example I like to set ground and VTOL units to "Maintenance Facility" as they are in their respective cubicles and not actively operating, while aerospace fighters are set to "Transport Bay" as they are performing routine patrols.

**Comment by IllianiCBT** [comment]
Closing as resolved (manually closing to make it easier for me to see what issues still need actioning).
