### ISSUE TITLE
Rank System Information Improvement

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/mekhq#2566]
### Environment
Ver 0.49.0
Windows 10
OpenJDK build 11.0.11+9

### Description
As title says. You may define the custom rank and can export it properly, but you cannot import individual ranks, neither such defined ranks are saved and applied when you click 'Confirm' the setting. 

Also, although it is possible to load the custom rank defined in pre-0.48.0., it is not possible to modify and save the 'custom' rank tab either. 

Sure those rank does have E0 Rank.

**Comment by Windchild292** [comment]
I can definitely do so on my end, having reloaded the custom rank system I'm working on after saving and shutting down my computer post-release. I'm going to need more information for this.

**Comment by binaryspica** [comment]
Well, it seems that I have saved it properly, with short size of system code. But It blows up my 'Custom' Rank in return. Then, if I make an another custom rank and press confirm, both of them are simply removed from the settings.

Perhaps, isn't it have some bad reaction if the campaign already have a custom rank?

**Comment by Windchild292** [comment]
Oh, you are trying to create two campaign custom rank systems....

That's not supported, as mentioned in the Rank System Type selection combo box tool tip.... and I missed adding that to the base description. (which I'll fix soon)

**Comment by Windchild292** [comment]
I don't understand the rest of what you are trying to say

**Comment by binaryspica** [comment]
Oh, that was part of the reason. I didn't aware that still only one custom rank on the campaign is supported. If I try to make it, only the custom rank what I selected when I press 'confirm' survives. Otherwise, both custom ranks are simply removed.

Also, the 'Custom' rank, the custom rank of the pre-0.49.0, cannot be modified in 0.49.0. I have tested it again by 0.47.17 and 0.49.0, and it is sure that the tab named 'custom' can't be modified at all. But can I change it to new custom rank supported by 0.49.0 and replace it properly?

**Comment by binaryspica** [comment]
An another question; is the custom rank system does not saves if there is at least one personnel with a rank and I try to remove the rank by replace the name by '-'?

**Comment by Windchild292** [comment]
Ah, found an issue with our build script. Please follow this post to create the folders required.
https://bg.battletech.com/forums/megamek-games/new-development-snapshot-0-49-0-for-megamek-megameklab-and-mekhq/msg1720531/#msg1720531

If you swap the rank system it will validate and fix the ranks of any invalid personnel.
