### ISSUE TITLE
User Rank System export removes User Rank System

### ISSUE THREAD

**Issue by monbvol** [MegaMek/mekhq#2569]
MekHQ 0.49.0
Windows 10
Java Open JDK v11

As you can see from the attached video when exporting User Rank Systems it completely removes the User Rank System.

https://user-images.githubusercontent.com/17420975/116828409-51539700-ab53-11eb-9823-5ba58dc6cf91.mp4

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6412266/mekhqlog.txt)

[AToW.zip](https://github.com/MegaMek/mekhq/files/6412268/AToW.zip)

**Comment by Windchild292** [comment]
This is a build script issue. Please follow this post to create the folders required.
https://bg.battletech.com/forums/megamek-games/new-development-snapshot-0-49-0-for-megamek-megameklab-and-mekhq/msg1720531/#msg1720531
