### ISSUE TITLE
[49.0] Scenario Reroll function has strange behaviour

### ISSUE THREAD

**Issue by Tecmes** [MegaMek/mekhq#2572]
(Using AtB/StratCon, haven't checked without)
When using rerolls on a mission ahead of the mission day, it seems to work, but come the mission day, the reroll count is reset and it's possible to reroll again. I don't hink that's intentional?

**Comment by Tecmes** [comment]
I was not able to reproduce my own bug in 49.1+390.

**Comment by Windchild292** [comment]
Closing as both I and the opener cannot recreate this.
