### ISSUE TITLE
0.49 - Mechwarrior Base Salary is 0

### ISSUE THREAD

**Issue by BowtieBob** [MegaMek/mekhq#2573]
### Environment
What version of MekHQ does your issue apply to? 0.49.0
What operating system are you using?  Windows
What java version are you using? 11

### Description
I just started a new campaign in 0.49.0, and while going through the options, I noticed that the base salary for MechWarriors is set to 0

![image](https://user-images.githubusercontent.com/70545594/116929115-9515d180-ac23-11eb-99fa-f72b898dc83a.png)

**Comment by BowtieBob** [comment]
Also, when I change the Value to be 1500 and click "Confirm" the value resets to 0 after reopening the campaign settings screen

**Comment by Windchild292** [comment]
Fix is already open, just not merged. Off by 1 error
