### ISSUE TITLE
RFE - Change default button on startup screen

### ISSUE THREAD

**Issue by BowtieBob** [MegaMek/mekhq#2576]
Can you change the default button on the startup screen to be either "Load a Campaign" or "Load Last Save"?

**Comment by Windchild292** [comment]
If by this you mean the first button, I'd personally rather keep it with the same order as it is currently as it keeps both load types together.

This is also the exact same order used in HBS BattleTech and Democracy 4 (albeit the latter does not have the Load Last Save/Continue button) [just my previous two played games].

Closing based on that.

**Comment by BowtieBob** [comment]
I'm asking more for usability than changing the order of the buttons. It would be nice to be able to click "Enter" when the screen loads to automatically load the last save rather than having to tab over first. The default button should be the one used the most often IMHO.

**Comment by sixlettervariables** [comment]
Do we have data to support that being the correct default?
