### ISSUE TITLE
Inconsistent date/time formats

### ISSUE THREAD

**Issue by gloowa** [MegaMek/mekhq#259]
Hi, i am a long term fan of MekHQ and for the longest time i had but one issue: date format.
It's not a big issue, but it's one of those very annoying small things.

In some places, MekHQ uses middle endian format of month/day/year.

In others (daily log for instance) it uses system locale, with full day and month names, STILL in middle endian order: 
środa, października 22 3045 (wednesday, October 22nd 3045) - so still month, day, year.

I realise that all MekHQ devs are most likely from United States, but please give us the option to use standard big or little endinan formats of dd/mm/yyyy or yyyy/mm/dd, uniformly, everywhere. Or at least option for all date/time fields to be in ISO 8601 format would be appreciated. https://en.wikipedia.org/wiki/ISO_8601

The mm/dd/yyyy date format is only used by two countries on the planet: United States and Federated States of Micronesia, for the rest of us it extremely confusing.

I hope i didn't come off as condesending or aggressive, my english is not perfect.

**Comment by Dylan-M** [comment]
To make this worse, some places do use ISO 8601, which is my preferred date format despite being from the USA ;)

Also, we have devs from all over the world: US, CA, and DE for sure.

**Comment by gloowa** [comment]
Sorry about writing here but github removed messaging system a while back - I decided to weigh in and forked the repo to address this by myself. Unfortunately i'm having issues with importing the project into eclipse - when i import the forked repo using EGit, it downloads everything, then (i presume?) unpacks it and then hangs for around 10 minutes and then Eclipse crashes. Tried increasing eclipse memory allowance but it didn't make a difference. After i restart Eclipse, it looks like it only imported .jar's in the lib directory.

Is that something anyone encountered?

**Comment by Dylan-M** [comment]
It is not. There shouldn't be any "unpacking", since it isn't packed in any way shape or form. EGit is just a java based, Eclipse integrated, frontend for git. I posted on the CBT forums awhile back a step-by-step on how to bring the projects in via EGit, but of course the staff there ignored my request to sticky.

**Comment by gloowa** [comment]
Ok, i've just found a bug report on eclipse page which might explain what's happening to me - basically import existing projects option appears to be broken, and one needs to use a workaround.

Gonna post if i manage to work anything out.

**Comment by gloowa** [comment]
Hey, i managed past the Eclipse issues.

I created a branch with my changes
https://github.com/gloowa/mekhq/tree/fix_for_date_formats_%23259

It turned out to be pretty straight-forward task, (if quite tedious) but i have several design questions to make this pull-request worthy:

1) General feedback on whether the approach i chose is acceptable. This is my first attempt at this and i learned the code as i went, so it might be a little rough.

2) As it currently stands, MekHQ loads and saves dates to/from xml (AtBConfiguration, LogEntry, etc)  in two formats - either ISO date (yyyy-mm-dd) or ISO date+time (yyyy-mm-dd hh:mm:ss). Do we want to change it to use a single format? And if so, do we care about backwards compability?

3) What should be the date formats avaliable? So far i've added:
- ISO (short: yyyy-MM-dd  long: yyyy-MM-dd  time: yyyy-MM-dd HH:mm:ss)
- little endian (short: dd-MM-yyyy  long: EEEE dd MMMM yyyy  time: dd-MM-yyyy HH:mm)
- middle endian (short: MM/dd/yyyy  long: EEEE MMMM/dd/yyyy  time: MM/dd/yyyy HH:mm)
Middle endian long date looks bad in particular, perhaps changing the month name to month number would be in order?

4) I've had to add Campaign arguments to some constructors and methods (mostly in XYZModel classes). So far it works well, but i wonder if there is any scenario in which those models are used without Campaign loaded and running? (in which case NullPointerExceptions would ensue)

**Comment by djmbm** [comment]
First off, I wouldn't even bother with supporting multiple formats. Make it all standardized on the ISO 8601 format and let people deal with it. As for loading in dates/times we don't want to change that either, and it won't matter if we change all dates/times to displaying in the same format.

If you really want to support people changing it, then we store it in ISO 8601 always, as we do now, but display it using proper localization: http://stackoverflow.com/questions/4594519/how-do-i-get-localized-date-pattern-string

**Comment by gloowa** [comment]
Well, multiple display formats are already in (and are localized), with options dialog changes to select one of 3 presets. If by localized you mean localized displayed date then that's already in. If by localized you mean localized date pattern (for instance, tt/mm/jjjj for german or dd/mm/rrrr for polish, etc) that can be easily added. Currently labels are stored in .resource, but i could replace using them with call to .toLocalizedPattern() from respective DateFormat.

Regarding loading/saving xml - i replaced all instances of inline string date format patterns with either:
CampaignOptions.DATE_FORMAT_ISO_SHORT (when original pattern was yyyy-MM-dd)
or:
CampaignOptions.DATE_TIME_FORMAT_ISO (when original pattern was yyyy-MM-dd HH:mm:ss)

Hence my question - half the classes used format without time, the other half used format with time - do want to unify this? Without additional changes, simply changing the pattern will break backward compability - ParseException every time you try to load xml with old pattern.

Also, around 3 classes used pattern yyyy-MM-dd **hh**:mm:ss rather than yyyy-MM-dd **HH**:mm:ss which means they were saving/loading using 12 hour clock without am/pm suffixes. Fortunately this doesn't break when you change pattern to HH.

**Comment by Dylan-M** [comment]
We will always want to maintain load capability with saves from older version.

As for localization, I'm talking about picking up the System's locale automatically and automatically performing localization, with the ability to override in the settings. That's why I posted the link ;)

**Comment by gloowa** [comment]
SimpleDateFormat does localization by default - if the pattern is "MMM" it will write 3 letter abbreviation of the month, localized using runtime locale. For "MMMM" it will do the same, except full month name will be displayed. So that's already working in the branch - whatever your system locale is, the date will be localized using that locale.

That link is about localized patterns, the other way around: "i have a SimpleDateFormat object set up and configured, now show me it's pattern using localized symbols for days, months, years, etc, for instance: _YYYY-MM-DD_ for english but _JJJJ-MM-TT_ for German".

As for load capability, that's not really a problem, just have to add try/catch blocks where dates are being loaded, with different formats used until one succeeds, so i can fix that easy.

Option to override locale would be best served if done on an application level and setting it is fairly trivial, but question is how exactly do that without making it hard to refactor if (when?) MekHQ starts supporting different languages.

As far as i can see, there are no MekHQ options, only campaign options, and i think both date format and locale would belong in application settings, rather than being a campaign-specific setting. Having date formats change when loading a different campaign is a bit weird.

Doing it this way has other benefits - because we know there can only be one application-settings object, we make it a singleton, which makes it super easy to use proper date formats anywhere, without passing any arguments to given method, reducing the argument list clutter.

_So the way i see it would be to create new config class with application specific settings, plus it's gui, and have locale and date format options there, saved separate from campaign._

I can do that all, but i ask - do you want me to?

**Comment by Dylan-M** [comment]
I would actually recommend this be done within MM, where we already support defining a date format (I believe under client options), and then making MML and MHQ use that option and it's back end code to do date strings. This would have the most benefit overall, since any project that uses MM as a lib can have access to it.

**Comment by sixlettervariables** [comment]
This likely won't get done in the 0.45.X line, but I've begun work on this as a side project. This is a very involved item.

**Comment by Windchild292** [comment]
https://i.imgur.com/OKpDV2q.png
