### ISSUE TITLE
Rank resetting time-in-rank and Domini rank/class

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#2592]
Using 48.0, loading a campaign rests the rank system to to "Second Star League".  For most factions it's simple enough to change campaign options back to the relevant system.  However, with WoB and presumably ComStar the time-in-rank modifier disappears.  In other words, a member who has a rank of Zombie Acolyte Delta Epsilon VI (six years at Acolyte Delta) is reset to just Zombie Acolyte Epsilon.

Also, turning on the time-in-rank option not only changed the rank system back to "Second Star League" but also removed all of the Domini ranks and classes.

If WoB/ComStar time-in-rank is supported it should not reset with rank system changes.  It would be nice if this was automatically generated based on the time-in-rank option setting. 

Edit: Also, Precentor rank is not holding i.e. after loading and changing rank system from "Second Star League" to "Word of Blake", everyone with previous rank of Precentor is changed to Demi-Precentor.  Per FM:ComStar this isn't an official rank with WoBM/ComStar only, with the equivalent being a long-serving Adept or junior Precentor.

**Comment by Windchild292** [comment]
Known and fixed issue.

**Comment by nicholassmith897** [comment]
This is not fixed, unless version with fix has not been released yet.

**Comment by HammerGS** [comment]
> This is not fixed, unless version with fix has not been released yet.

The fix is in the Development branch and hasn't been ported back to Stable.

**Comment by nicholassmith897** [comment]
> > This is not fixed, unless version with fix has not been released yet.
> 
> The fix is in the Development branch and hasn't been ported back to Stable.

That would explain it, I'm on Stable.
