### ISSUE TITLE
Cannot ransom, win 10, 48.0

### ISSUE THREAD

**Issue by 907deadsalmon** [MegaMek/mekhq#2597]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
48.0 MekHQ
Windows 10
Java version 11.0.10
### Description
Cannot select option to ransom prisoners
![Screenshot (64)](https://user-images.githubusercontent.com/83892309/117558182-78183e80-b027-11eb-95fd-8c764531b337.png)

### Files
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6446826/mekhqlog.txt)
[SimpleFolk30670506.cpnx.gz](https://github.com/MegaMek/mekhq/files/6446825/SimpleFolk30670506.cpnx.gz)

**Comment by Windchild292** [comment]
I completely forgot that I made ransom into an option, and that's why. Ransom is current disabled.
