### ISSUE TITLE
Memory leak, or something. 3.25 MekHQ

### ISSUE THREAD

**Issue by creativeballance** [MegaMek/mekhq#26]
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/160757/mekhqlog.txt)

After playing a couple of battles, response time begins to slow down. Seen in bots first, but eventually even the client for MekHQ and MegaMek stop responding.

**Comment by pheonixstorm** [comment]
As I posted in the MM forum, the program ran out of memory. 

So, two things to check. First, how much system memory does your computer have. The second is how much memory is allocated in the mekhq.l4j file. Default is 1.2Gb, but based on the log it looks like it only used 528mb before it ran out.

You can read up on this here https://github.com/MegaMek/megamek/wiki/Memory-and-our-software

**Comment by creativeballance** [comment]
Computer has 16 GB. Win 10 64 bit.
The l4j file his 1024m.
I tried changing to 2048m, but it does not run at all.

**Comment by pheonixstorm** [comment]
Follow the directions in the link provided above and post what Java is reporting as available.

**Comment by creativeballance** [comment]
Getting:
'grep' is not recognized as an internal or external command when typing the
commandline.
Removed the Grep portion, got:
Unrecognized option: -XX+PrintFlagsFinal
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by pheonixstorm** [comment]
Well THAT was unexpected.

**Comment by creativeballance** [comment]
Can we just say that Java is screwed up on my computer? Everything is a
fresh install on this computer, as I just reinstalled windows on Saturday.
Would you say that this may be a memory error on my computer's parts as
opposed to an actual bug in the software?

**Comment by Dylan-M** [comment]
If you're getting the grep not found it's because you haven't installed UnxUtils like that link mentions you need to do for Windows. Or if you have, then you haven't edited your PATH to include their folder on the system search path, which is also mentioned in passing.

At any rate, since you're having a larger issue, could you please from a cmd prompt do this:
java -version

And report the results?

Thanks.

**Comment by creativeballance** [comment]
I see.
Maxheap size: 268435456
So...256 MB?
I know my system is 16 GB - any ideas how I can allocate more to Java?

**Comment by Haranin** [comment]
Played some mekhq this morning, computer updated while at lunch, and now mekhq will not start (any version). Tried uninstalling java and reinstalling, rebooting and downloading to the newest version. Not sure what happened....
[megameklog.txt](https://github.com/MegaMek/mekhq/files/167973/megameklog.txt)

**Comment by djmbm** [comment]
@creativeballance Follow the instructions for changing memory settings in that wiki entry.

**Comment by creativeballance** [comment]
I have tried editing a file to change the settings. If I said at any higher
than 10 24 mega mac will not start. Java is only reporting 256 Megs of
memory regardless of what the configuration file is set to.

**Comment by Dylan-M** [comment]
@creativeballance There was a bit of an error in the memory page before.

Could you please visit:
https://github.com/MegaMek/megamek/wiki/Memory-and-our-software
again and test with a lot of values until you have a better idea of what your max is.

I'm honestly wondering if you have the 32bit JVM instead of the 64bit, and this would limit your usable RAM to around 1200M for the JVM. This is why I also asked you to give us the output of 'java -version', and I would still like that as well please.

**Comment by creativeballance** [comment]
Must have missed that request:
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) Client VM (build 25.73-b02, mixed mode)

For some reason today when I'm using the "java -XX:+PrintFlagsFinal
-Xmx2048M 2>&1 | grep MaxHeapSize" command, I get no response. Just a blank
line under the command.

**Comment by Dylan-M** [comment]
Try testing with different values per the instructions please. Such as 1024, 1200, 1600, etc...

**Comment by Dylan-M** [comment]
Still waiting on user feedback, I'm inclined to say there is no bug here.

**Comment by creativeballance** [comment]
I'm sorry that I left this open. I'm 99% sure at this point it was caused
by my Processor having a memory address issue.

On Oct 2, 2016 3:15 PM, "Dylan Myers" <notifications@github.com> wrote:

Still waiting on user feedback, I'm inclined to say there is no bug here.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MegaMek/mekhq/issues/26#issuecomment-250999823>, or mute
the thread

**Comment by Dylan-M** [comment]
No worries, closing as invalid.
