### ISSUE TITLE
[49.1+390] Blank scenario created before Mission start

### ISSUE THREAD

**Issue by Tecmes** [MegaMek/mekhq#2603]
I  before finishing another one, and .
As I had just accepted a new Mission, an Assassinate  scenario immediately appeared in my Briefing Room, though it had not Date and no details (no OpFor, though it had condition sets).

The save is in the pre-start situation. But even when the mission start was reached and I was on-planet, it still was blank.

Note that this mission was accepted before the end of the previous one. ALso I did not reach the planet before mission start, in case it could be related.  

[Pending Scenario before mission start.cpnx.gz](https://github.com/MegaMek/mekhq/files/6453593/Pending.Scenario.before.mission.start.cpnx.gz)

**Comment by NickAragua** [comment]
This is likely an issue with "fixed" objective scenarios for the contract. As a "work-around", you can ignore them until you stumble upon them in the StratCon UI.
