### ISSUE TITLE
RFE: bomb load presets

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#2605]
I would like to see a system for storing preset bomb loadouts, called from the "Select bombs" dialog.  This would be a pulldown with a list of names, such as "Interdiction" "Anti-armor (light)" and "Fire support".  Each would load out the fighter in a different way.  For example:

- Interdiction: max out on Thunder/FASCAM bombs
- Anti-armor (light): 2 x rocket pods, 1 x cluster bomb, 2 x inferno bombs
- Fire support: 1 x TAG, max out on Arrow IV

This is called from the current dialog so choices can be fine tuned if desired.

Loadouts will be stored in separate XML files, allowing for user creation and editing.  Eventually a dedicated GUI would be nice but a few easily tweaked configurations to start with should serve most users well.

Loadouts will have a couple of options to control how many are loaded.  Fixed number will try to load the indicated number, while maxed out will try to fill all remaining bomb hardpoints/thrust points.  While multiple types can be selected only one should be set as maxed out to avoid complex calculations.  There will need to be some error handling to prevent loading more bombs than can be carried.  The best I can think of, is the initial load of the data calculates the minimum hardpoints and thrust required for each loadout.  When the dialog is brought up for a specific fighter the dropdown list is filtered so only the valid loadouts are available.

The preset loadouts may also be of use when generating air support OpFor.  Currently the numbers are a bit too random for my taste e.g. one will have 9 (!) light FAE bombs, another will have 4 cluster bombs, another will have nothing at all.  The map type, scenario type, and selected player units can be used to pick a loadout that's more rational.

**Comment by HammerGS** [comment]
As we've said before we are a small volunteer team. RFE's like this will likely never get done. Please consider our ability to do the RFE before opening it.
