### ISSUE TITLE
[49.1+390] Mech not repairable due to unclear torso/arm issue

### ISSUE THREAD

**Issue by Tecmes** [MegaMek/mekhq#2609]
Normally MHQ handles the issue of unrepairable torso parts, removing/scrapping the part therein well.
But I've had twice the same issue in 49.1+390 with a mech having a destroyed torso/arm and not being able to repair any of it. I tried salvaging and removing parts in those locations, but none remain.
The only way I found to fix was to salvage pretty much all the Mech and then "rebuild" it.
Maybe there's something I don't get, but it seems something is wrong.

Example included.
[unrepairable_mech_torso.cpnx.gz](https://github.com/MegaMek/mekhq/files/6460879/unrepairable_mech_torso.cpnx.gz)

**Comment by Tecmes** [comment]
Still in +398. It seems that autorepair doesn't deal with parts that needs scrapping anymore. I've had the issue with arms, side torsoes* and legs.

(*) Yeah, I'm not sure. It's not a plural one uses frequently, unless you work in a mannequin assembly line or something.

**Comment by Windchild292** [comment]
This is likely due to the underlying parts cleanup by @sixlettervariables. I'd guess a comparison is not properly implemented in the equals for the specific part, but I'm not certain.

As for the word... "torsos" is the correct spelling, although it just looks wrong.

**Comment by sixlettervariables** [comment]
Yeah, likely a part without correct equals implementation, or a new way a part can be "broken" from the MM side I didn't handle (or realize should be handled).

**Comment by sixlettervariables** [comment]
Looks like there is an LRM-10 in the left torso that cannot be salvaged and can only be scrapped:
![image](https://user-images.githubusercontent.com/8238690/122809318-f2c9b000-d29b-11eb-8789-6e412c20e10b.png)
After scrapping the LRM-10:
![image](https://user-images.githubusercontent.com/8238690/122809361-04ab5300-d29c-11eb-9de4-b74cba72f85a.png)

**Comment by sixlettervariables** [comment]
Would messaging like this help?
![image](https://user-images.githubusercontent.com/8238690/122812215-67521e00-d29f-11eb-9562-5eda5a8276f3.png)

**Comment by NickAragua** [comment]
Hell yeah. Does it do that for multiple parts that are in the way, too?

**Comment by sixlettervariables** [comment]
But of course.

**Comment by NickAragua** [comment]
Heh, that'll solve like half the complaints we get about MekHQ's repair interface.
