### ISSUE TITLE
Tech continues refit after retiring

### ISSUE THREAD

**Issue by chriskessel** [MegaMek/mekhq#261]
I had a post-contract retirement and the mech tech working on a refit retired. Yet it says he continues to work on the refit and it won't let me assign it to someone else :)

**Comment by pheonixstorm** [comment]
Known bug I believe. The refit system is getting an overhaul though I don't know when it will be finished. I think its next followed by the repair system. One of the devs might swing by with more info.

**Comment by neoancient** [comment]
This is not identical to #237, but has the same basic cause.
