### ISSUE TITLE
Assigning reinforcements will duplicate leadership units

### ISSUE THREAD

**Issue by AndrewChianpestersdevsofmegamek** [MegaMek/mekhq#2616]
Assigning reinforcements after assigning leadership units will duplicate the leadership units that I assigned. I am using the build from Stratcon data fixes #2.  I am using Windows 11, and Java 11 from open JDK. 
![2021-05-15](https://user-images.githubusercontent.com/83780383/118370488-e56f2680-b575-11eb-928d-6d29e8f60ced.png)
![2021-05-15 (11)](https://user-images.githubusercontent.com/83780383/118370492-e7d18080-b575-11eb-8e10-107d15151cc4.png)

**Comment by Tecmes** [comment]
I think you might be asked how you deployed the reinforcement: via the Campaign tab (stratcon interface) or via the TO&E right-click menus?

**Comment by AndrewChianpestersdevsofmegamek** [comment]
I used the stratcon interface to assign all of them.

**Comment by NickAragua** [comment]
This was fixed in 49.2
