### ISSUE TITLE
Advanced Medical: Patient not added to infirmary until day is advanced.

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#262]
I noticed this in the new advanced medical dialog. An NPC with an injury added in the new panel with the paper doll does not show up in the infirmary until the day is advanced. This makes it impossible to assign a doctor to them on the same day.

I did NOT check if running a battle bypasses this. It may.

**Comment by Dylan-M** [comment]
Anything that forces a re-check (running a battle, saving and reloading, etc...) will definitely get them to show up.
