### ISSUE TITLE
Manually add/remove pregnancies & children.

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#263]
Now that MekHq supports more advanced options for NPC pregnancy, there should be some options to manually assign them. That way the player can assign them at appropriate moments in their story arc.

Might as well add an adoption option for children as well so their can be added to a family.

**Comment by pheonixstorm** [comment]
The issue with adoption is the lack of blood relation. Anyone who shares an ancestor can't marry. So if one side of the family has kids and the other side adopts a kid (who has been dating something in the other side of the family) your story won't allow you to marry then unless you do so BEFORE the adoption.

The feature would be nice but it also adds a bit of complication to how things work after.

As for adding/removing pregnancies.. simple simple, consider it coded. Getting it merged... I can post a PR when done but can't make any promises on when ralgith might actually accept it.

**Comment by VampireSeraphin** [comment]
This appears to be complete and can probably be closed.
