### ISSUE TITLE
[49.1+398] Scheduled procurement attempts do not happen

### ISSUE THREAD

**Issue by Tecmes** [MegaMek/mekhq#2632]
The listed procurement attempts in the Command Center sometimes just don't get rolled. I'm not sure what causes this, but they're "old" parts.
Maybe it's because of StratCon deployement locks?

[procurement_not_rolled.cpnx.gz](https://github.com/MegaMek/mekhq/files/6529043/procurement_not_rolled.cpnx.gz)

**Comment by Tecmes** [comment]
I think this can be closed. IF I have a solid lead and way to reproduce, I'll open a fresh report,, but I haven't had the issue for a while.

**Comment by Windchild292** [comment]
Closing based on the opener's comments.
