### ISSUE TITLE
[49.1] Advance Days Dialog Modality Based on Current Functionality

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#2636]
When using the "Advance Multiple Days" feature, opening maintenance reports or news reports will immediately push them behind the Multiple Days window, rendering them impossible to interact with. Other links like contract or personnel market are unaffected.

MekHQ 49.1
OpenJDK 11

**Comment by Windchild292** [comment]
The first is due to the modality of the dialog. It is required for how processing currently works. I've got some initial code that will fix it, but it's slow going.

**Comment by Windchild292** [comment]
Also, this should be three issues... I'll divide it for this one, but in future please separate bugs into individual issues so we can handle them easier.
