### ISSUE TITLE
AtB OpFor do not Generate SPAs as per AtB rules

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/mekhq#2643]
This was raised in #2536, although it was already on my list of issues before that point.

**Comment by Thom293** [comment]
Reading Nicks recent comment in #3289 it seems that perhaps they are being generated per CamOps page 70 for Stratcon, at least.  So, dont know if there are two separate systems generating them?  One for StratCon and one for AtB?  Or just one system?  Market Pilots are incorrect under either system, I think.

**Comment by Windchild292** [comment]
This wasn't actually an issue, just a misread as they don't always generate.
