### ISSUE TITLE
Vehicle gunnery skills not showing same as personnel screen

### ISSUE THREAD

**Issue by Southernskies** [MegaMek/mekhq#265]
Running some 1-man APCs and the Gunnery is showing as 7+ instead of their correct skill level on the TO&E page.
This carries over into MegaMek itself when a game is launched.

![mekhq_vehiclecrewerror](https://cloud.githubusercontent.com/assets/24500523/21077243/25a2c004-bf99-11e6-82e8-c38dce465a82.jpg)

[Solaris VII Challenge30250601.zip](https://github.com/MegaMek/mekhq/files/644158/Solaris.VII.Challenge30250601.zip)

**Comment by jayof9s** [comment]
This has actually been something that bothered me for a while. At some point (years ago now) the driver's gunnery stopped contributing to the average in a vehicle. Regardless of if it's 1 man or 7 it should be counted towards the average. If it's 1 it obviously NEEDS to be.

**Comment by Dylan-M** [comment]
I thought the rules explicitly excluded drivers from the gunnery score of the overall crew EXCEPT in the case of 1 crew vehicles? I thought that was why Tah made the change actually.

**Comment by neoancient** [comment]
Per TacOps 218-219 any vehicle over 15 tons has one driver and the rest are gunners. I'm not aware of any rules for combining personnel scores, but it seems to me that drivers are excluded from gunning exceptmfor single-crewed vehicles.

**Comment by Southernskies** [comment]
Would be nice to be able to assign gunners on larger vehicles to specific guns.  Have a few Weapon Specialists in another game that I am sure aren't benefiting from it.
 

    On Monday, 12 December 2016, 6:11, neoancient <notifications@github.com> wrote:
 

 Per TacOps 218-219 any vehicle over 15 tons has one driver and the rest are gunners. I'm not aware of any rules for combining personnel scores, but it seems to me that drivers are excluded from gunning exceptmfor single-crewed vehicles.—

**Comment by pheonixstorm** [comment]
As far as I know if the SPA isn't assigned to the commander of the vehicle it doesn't get used.

**Comment by neoancient** [comment]
The official rules treat the vehicle and the crew as a single entity. As far as the rules are concerned it the vehicle has driving and gunnery skill ratings and SPAs. The purpose of the TacOps rules on crew size is to limit crew actions in smaller vehicles (cannot fire are clear a jam in the same round with one gunner) and to tie addtional target prnalties to the number of gunners. I can find no rules that govern integrating new crew with differing skill levels; as far as I can tell they simply count toward the minimum crew requirements but the piloting and gunnery skill of the vehicle are unchanged.

What MekHQ does is a common sense approach to combining individual crew skills to make a single aggregate crew skill. As this approach is not defined by the rules, there are certain aspects that are unclear, such as how individual SPAs should be dealt with. But this is a separate issue. For the issue at hand, though I haven't looked at the code yet it seems to me that MekHQ is treating the crew member as a driver only and is computing the stats as if there is no gunner, when it should be treating the single crew members as both driver and gunner.

**Comment by jayof9s** [comment]
If the rules for this are covered anywhere, it would be ATOW. However, I'm not finding much in there and it seems to expect you'll determine who is doing each action so there would be no averaging necessary. Which obviously does not work for MM.

Unless there are rules I'm still inclined for the driver to count into the average. More than a few vehicles are fluffed to have some portion of the gunnery under command by the driver.

Based on discussions we've had previously, I have always been under the impression that all personnel need to have an SPA for it to work. But that's not what is implemented (currently it just looks at the Commander of the unit) and obviously there's room for debate. For instance, why would gunners need something like Maneuverability Ace for it to work. I was thinking that was an actual rule but I'm not actually sure about it and I'm again not finding anything.

**Comment by neoancient** [comment]
While one could argue that the explicit statements that the driver contols the gunnery in some vehicles implies that the driver normally does not, it is not clear that this is true when not explicitly stated in the fluff, or that the driver could not gun if necessary even though the vehicle might not have been designed for it. Lacking any way to determine for certain whether the driver can gun in a given vehicle, we have to choose one approach to apply to all vehicles, and given the choice between including the driver, which we know is correct in at least some cases, or excluding the driver, which is based on assumptions, I favor the former. On top of that, it should be the easiest to implement. I would, however, exclude a driver that has no gunnery skill, and I'm inclined to go further and only include the driver if it helps the overall skill. A driver who can shoot but is not very good at it would more likely leave the weapons to dedicated gunners.

**Comment by Dylan-M** [comment]
What we need to do is have the OP post a rules clarification request on the subject for TPTB; instead of making assumptions.

**Comment by jayof9s** [comment]
Where would they ask? The rules simply don't exist so there's nothing to clarify.

**Comment by Dylan-M** [comment]
The rules offered earlier where it's specified that the driver is included for single crew vees?

**Comment by scJazz2** [comment]
This is probably related...
Vees of 15 tons or less only have one crew. So the G/P should be exactly what the Crew Members skills are... but they are not. See attached Zip of empty campaign with 1 Savannah Master and 1 Ferret

[Vee PnG ScrewUp.zip](https://github.com/MegaMek/mekhq/files/646928/Vee.PnG.ScrewUp.zip)

**Comment by Southernskies** [comment]
This is more an artifact of being able to use RPG level of detail in a Unit level of detail rule system.  Not sure how difficult it would be to code an IF>THEN statement.

IF {crew=1} THEN {gunnery=driver}
IF {crew>1} THEN {gunner=average of gunners}

**Comment by Dylan-M** [comment]
@scJazz2 Way to just say the exact same thing as the original report...

@Southernskies That's basically what the code as written is supposed to be doing already.
