### ISSUE TITLE
Hanger Breakdown doesn't correctly include superheavy combat vehicle types of Wheeled, Hovercraft, VTOL and WiGE.

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/mekhq#2659]
### Environment
Ver 0.49.1

### Description
On Command Center you may see available reports. Among them is Hanger Breakdown, which shows the number of units on your disposal. Most units are represented correctly, but it doesn't shows heavy/assault class Hovercraft, medium/heavy class VTOL, Superheavy class Wheeled and WiGE. 

You may have heavy/assault class hovercraft by add a superheavy hovercraft, and you may have medium/heavy class VTOL by add a superheavy VTOL. But while the breakdown counts the total number of the units with same type, it doesn't have the section to show such weight class. 

Also Wheeled and WiGE doesn't have superheavy section either.

**Comment by Windchild292** [comment]
Heavy and Assault hovercraft do not exist, nor do medium/heavy VTOL. The missing super heavy sections are bugs, which I will handle.

There also exists bugs in our base weight code (as we do not properly handle the Tech Manual and TacOps rules), which I'll open up an issue in MegaMek for.
