### ISSUE TITLE
[Stratcon] Leadership deployement doubles units

### ISSUE THREAD

**Issue by Tecmes** [MegaMek/mekhq#2661]
[49.2+410]
When using Leadership on a defend lance to deploy extra non-Mech units, you can deploy units from an alread-deployed lance (already reported). But if you do, those units get deployed in two copies...
For example if you deploy a Lance including four mechs and two BAs, and then choose to deploy the same BAs through leadership (a motive for that would be that if the Lance is reinforcement and you're not sure it's going to make the roll), you get four BAs in the lobby, two copies of each.
(Note that if you delete one of the units in the lobby, it deletes both copies)
If you keep them in game, things get weird, as selecting one selects both.

**Comment by NickAragua** [comment]
Fixed with PR #2671
