### ISSUE TITLE
Stratcon AI heavy bombers are always have maximum possible bombs and doesn't care for its cruising speed

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/mekhq#2674]
### Environment
Ver 0.49.1

### Description
Yes it may not a problem for many bombers, but it is very serious problem for heavy bombers.

![r1](https://user-images.githubusercontent.com/47907439/120349313-fc18ca00-c338-11eb-9d5e-4021a9b25765.png)

For example, I have two ally bombers on the mission, and one of them is Thunderbird TRB-D36. As you see, its basic movement is 5/8. It may have up to 20 bombs, sure, but it will reduce its movement to 1/2, which is not a good move. Although aerospace units CAN takeoff with flanking movement, but always work with flanking movement of up to 2 seems quite punitive for such bombers. Isn't better to adjust the number of bombs to keep at least cruising speed of 2?

Asides, what the hell on the idea of carry inferno bombs on here? Yes in the most times it is not an issue and is a very effective bomb, sure, but the mission's terrain is HEAVY **URBAN** and the ally is come to defend(actually, evacuate the ally) it rather than attack or raze it. I don't think that burn your own city is something helpful to defend your one. Is it better to make a new post for this - choose the right bombs for the missions, especially for depend missions on the terrain? Such as put Rocket Launchers instead of the other bombs, as my aero wings do on the same mission to avoid collateral damage. Yes it's only a computer game and destroying the building doesn't affects anything on here, but it's somewhat weird that what the defending wings have seems nothing but raze their own ground....

**Comment by SuperStucco** [comment]
... or FAE bombs flying over a city.  But maybe for Capellans?  😉

I too would certainly like to see a little more variation in selection of OpFor external ordnance.  For example, if the player is fielding conventional forces, carry a mix of cluster and inferno; if in high winds don't carry rocket pods; if in darkness carry rockets not bombs (spotting range issues); if the ground forces carry TAG use laser guided bombs; if ground forces have many LRMs, carry an external TAG pod; etc.  I'd be glad to help mapping out some of the logic for this.

**Comment by NickAragua** [comment]
Context is pretty easy for a person to figure out, not so much for a simple "roll some dice to determine bomb type, roll some dice to determine how many bombs" routine. The effort involved in make changes like this is going to be pretty high with a relatively low payout, so I'm not sure it will be a high priority at this time.

**Comment by gsparks3** [comment]
The "low thrust from overloaded heavy ASF" issue at least might be relatively easy to fix. If we define, say, 3/5 as the minimum acceptable thrust on an aerospace unit, then you can just remove any bombs that put it below that level of thrust after the initial random loading. Nicely objective and easy to define in code. 

The other part of the request (using "appropriate" bomb types) is definitely much harder. Enough conditionals to make it a complex problem to crack and probably not worth the effort while in the process of getting StratCon off the ground.

**Comment by NickAragua** [comment]
Do we really care about low thrust for overloaded ASF though? On the ground map, 1/2 aero movement still lets them move 16/32 hexes per turn, which is basically most of the map.

**Comment by SuperStucco** [comment]
There's thrust expenditure for accelerating/decelerating, power turns, changing altitude, and (when enabled) evasion.  I do agree with the 3/5 minimum as it gives a few options without pushing into overthrust with the associated risks.  And people do play on larger maps to give aerospace room to breathe, where 16 hexes a round isn't that much.

**Comment by binaryspica** [comment]
While 1/2 aero movement can move enough distance, but the problem is it's 1/**2**. You don't always need to use 2 aero move but it is quite often, although the bombers rarely need 3 or more aero move. And flanking movement for aero makes them to suffer the penalty on the control roll as well.

**Comment by SuperStucco** [comment]
Might have something for this shortly.
