### ISSUE TITLE
0.49.2 DEV Nightly (5/29/21) - Repair Extra Time Modifiers Are Ignored

### ISSUE THREAD

**Issue by Kailan7401** [MegaMek/mekhq#2679]
### Environment
0.49.2 DEV Nightly (5/29/21)
Windows 10
OpenJDK 11.0.10

### Haiku
_Dude, I told you to
Take your friggin time on this!
These parts cost a ton!_

### Description
As near as I can tell, extra time modifiers are not being taken into account properly for repairs that take more than 480 minutes and have to be completed the next day. In the below example, I get a target of 6 to repair a battlemech's right leg. Since the repair is too time intensive to complete that day, the repairs carry over and are completed the next. In that case, however, the target changes back to 9 (presumably ignoring the -3 modifier due to extra time, though I can't confirm that's precisely where the discrepancy is coming from). This issue does not seem to occur on repairs that are completed same day. Hammer did mention to me that there were changes recently to overtime, and in my example the tech in my example is utilizing overtime to complete the repairs. I'm not sure if that has anything to do with the issue or not.
 
![image](https://user-images.githubusercontent.com/32316785/120565829-e0044e00-c448-11eb-8f5c-6d3b37164f91.png)
![image](https://user-images.githubusercontent.com/32316785/120566021-425d4e80-c449-11eb-8915-edcdfc1c2f94.png)
![image](https://user-images.githubusercontent.com/32316785/120566080-7173c000-c449-11eb-980b-5c8a61d49757.png)

**Comment by Kailan7401** [comment]
Forgot da files

[McAllister's Marauders25050914.zip](https://github.com/MegaMek/mekhq/files/6588141/McAllister.s.Marauders25050914.zip)
[Campaign Data.zip](https://github.com/MegaMek/mekhq/files/6588163/Campaign.Data.zip)

**Comment by NickAragua** [comment]
Looks like the problem is that you have Overtime on, which introduces a +3 modifier.

**Comment by Kailan7401** [comment]
oh golly, I didn't know that! Ok then! Working as intended!

**Comment by NickAragua** [comment]
We could probably do a better job if indicating that overtime will occur, though, to avoid confusion.

**Comment by NickAragua** [comment]
Looks like Person.isTaskOvertime() considers the task to not be overtime if it'll take longer than "normal tech minutes left + overtime tech minutes left", which I'm not sure is correct. Going to wait for others to weigh in on how to solve this.

**Comment by sixlettervariables** [comment]
It looks like `isTaskOvertime` conflates whether or not the task is overtime with whether or not the tech has overtime to work on the task.

**Comment by sixlettervariables** [comment]
That `+3 (difficulty)` is not from overtime (which would be tagged `+3 (overtime)`), but instead because it is a class E part. The overtime calculation comes into play on the day where the time left calculation is correct; but that's behind the scenes at that point and you don't see the why.

The change to `Person::isTaskOvertime` I suggest above _should_ cause you to see the correct rolls required. But you'll still see a variable possibility on the last chunk of work time based on how much overtime your tech has left.

**Comment by NickAragua** [comment]
I'm wondering if the extra time provided by Overtime shouldn't be applied across multiple days for lengthy repairs? Currently, it only seems to be getting applied to the last day, which I'm not sure matches the intent of the rules.

**Comment by sixlettervariables** [comment]
@NickAragua I added an additional bit of defense to ensure you were "charged" for OT no matter the "day" it occurred.
