### ISSUE TITLE
Pilots always killed if resolve manually

### ISSUE THREAD

**Issue by Chichengunga** [MegaMek/mekhq#268]
in the most recent version, regardless of how much damage you select pilots to have, they end the scenario killed. Normally you can select how many pilot hits but even with selection no hits, pilots all die.

**Comment by mnmib1** [comment]
See bug 270 for what actually happens

**Comment by neoancient** [comment]
Please provide a campaign file eith any custom umits and either a saved game or a battle resolution file.

**Comment by Chichengunga** [comment]
here is a link to everything needed to load my campaign. Its a big file as i have a lot of custom stuff. I don't think the custom fluff is needed but included it anyhow. 

The issue again is when i try to manually resolve usually i scenario i don't want to play, i can select which mechs are lost or recovered and how much damage my pilots take. Regardless of how many pilot hits i give them, then end up KIA. I'm trying to resolve the mission manually without playing that particular scenario at all so i don't have a saved game or resolution file. This used to work in previous versions. 

https://1drv.ms/u/s!ApQLixPr5mFsmqQXtieNa2vmvgSlYQ

**Comment by neoancient** [comment]
It was easy enough to make a test case from the additional information provided.
