### ISSUE TITLE
Scheduled procurement not happening

### ISSUE THREAD

**Issue by Tecmes** [MegaMek/mekhq#2682]
This is a bug reopen. I have confirmed this happens in 49.2+410.
Here's a save. If you advance day, you'll see that the procurement rolls are not made, eventhough the Logistics people are not busy. In fact, if you add a new procurement, it gets rolled, but not the others.
I'm afraid I have no idea about the reason why they aren't rolled.

[no_procurement.cpnx.gz](https://github.com/MegaMek/mekhq/files/6593447/no_procurement.cpnx.gz)

**Comment by sixlettervariables** [comment]
Need some customs:
![image](https://user-images.githubusercontent.com/8238690/122774246-06aeeb00-d277-11eb-9ff3-81a836c4f98e.png)

**Comment by sixlettervariables** [comment]
I removed those two units and enabled verbose acquisition logging:
```
No contacts available for LB 2-X AC Ammo on Chaine Cluster (7)  No contacts available for Upper Arm Actuator 60 tons on Chaine Cluster (7)
No contacts available for Mech Right Arm 60 tons (100%) on Chaine Cluster (7)
No contacts available for Mech Right Leg (Endo Steel) 65 tons (100%) on Chaine Cluster (7)
...skipped a whole bunch more of these
No contacts available for Armor (Ferro-Fibrous) on Chaine Cluster (7) 
Can't search for LB 2-X AC Ammo on Far Reach because: The clans and inner sphere do not trade supplies 
Can't search for Upper Arm Actuator 60 tons on Far Reach because: The clans and inner sphere do not trade supplies 
Can't search for Mech Right Arm 60 tons (100%) on Far Reach because: The clans and inner sphere do not trade supplies 
...skipped more...
Can't search for Armor (Ferro-Fibrous) on Far Reach because: The clans and inner sphere do not trade supplies 
Can't search for LB 2-X AC Ammo on Rondane because: The clans and inner sphere do not trade supplies
...skipped more...
Can't search for Armor (Ferro-Fibrous) on Paran because: The clans and inner sphere do not trade supplies
```
Looks like where you are isn't fruitful for supplies.

**Comment by sixlettervariables** [comment]
I can't reproduce the rolls not occurring, so I would recommend enabling verbose acquisition logs and let me know if it occurs then (you'll see no attempts to do anything in the log).
