### ISSUE TITLE
Unable to select second subcontract.

### ISSUE THREAD

**Issue by watts11** [MegaMek/mekhq#2692]
### Environment
Windows 10, Java 8u291 64-bit, MekHQ 48.0

### Description
I'm running an AtB campaign and took a second subcontract during a garrison contract (i.e. three active contracts total).  Both subcontracts have the name "New Subcontract."  When I go to the Briefing Room tab, clicking on either subcontract in the mission dropdown opens up the first one.  In other words, there is no way to run a scenario from the second contract.  It appears that all subcontracts are being generated using the same name, then the dropdown references the subcontract by name and not ID.  When I open up the save file and manually edit the XML, I can change the name of the second subcontract (e.g. to "New Subcontract 2") and now it appears to run fine.  I can select the second subcontract from the missions dropdown and run a scenario as expected.  These subcontracts should probably be created with unique names.

### Files
MekHQ campaign file:
[EXSTERNO30520812.cpnx.gz](https://github.com/MegaMek/mekhq/files/6633019/EXSTERNO30520812.cpnx.gz)

MekHQ campaign with edit to make it work:
[EXSTERNO30520812_2.cpnx.gz](https://github.com/MegaMek/mekhq/files/6633020/EXSTERNO30520812_2.cpnx.gz)

**Comment by Windchild292** [comment]
Fixed in https://github.com/MegaMek/mekhq/pull/2668

**Comment by watts11** [comment]
Great!  Sorry I didn't see that one.

**Comment by Windchild292** [comment]
No worries :)
