### ISSUE TITLE
RFE: Coloured Unit Assignment in Personnel Tab

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/mekhq#2696]
"Would it be possible to have the Unit Assignment column in the Personnel tab for a specific person be the same color the unit's line in the Hanger is due to damage? 

It would be helpful if the Unit Assignment column in the Personnel tab was color coded according to the assigned unit's status (yellow for light damage etc), and even better if the same color coding could apply to the right click submenu in the Assign to Unit-> As Pilot -> Mek -> Medium -> (coloring begins) damaged/not full ammo Wolverine is yellow, inoperable Shadow Hawk is red; as an example. Add Unit in the right click on ToE menu would also benefit from this, as that is also not colored for damaged units; though currently once in the ToE it's colored red if the unit is damaged. However this means having to inspect the Hangar tab to see what (potentially very similar named units) are damaged and what is not or removing and adding units you think aren't damaged until you get one that isn't red in the ToE.

It is sometimes takes some time to tell which out of your units is undamaged (such as when you pull Stinger number 4 out of mothballs/reserve lance while Stinger number 2 and Stinger number 5 are unpiloted due to battle damage) to assign crew to, as unless I'm missing something the Hanger right click on unit menu doesn't have an assign crew option, just an assign tech option. This might also work instead of coloring the Unit Assignment column for the purpose." - Comment in #2589 

I've split off the assign person to unit in the hangar tab to #2695, as this is not the first time I've heard this request.

**Comment by Duuvian** [comment]
Thanks for that, I'll make RFE posts for suggestions in the future. I have a whole list of them, would it be better for you to have them in individual RFE posts, in small groupings of similar issues such as hangar tab suggestions in on one RFE post, or is it OK to list them all out in one post? I assumed small groupings but I see the labels already allow you to do that so I figured I would ask before I make a lot of RFE posts.

**Comment by Windchild292** [comment]
Try to keep it to a single RFE per post. However, do note we are a very small team and thus the ability to handle a large number of enhancements is not high unless they are on the simpler side.

**Comment by Duuvian** [comment]
OK thanks. I will post my list on another forums first and see if any are outright bad suggestions before I make a lot of RFE posts. Most seem simple from my end with a few exceptions but I also have no experience in coding.

As far as helping,  I could make some midi files if you would like some small sized audio files, or I could make some custom units such as infantry variants that might make sense but aren't in the source material, or put together some custom scenario templates as I have played with that before to make coastal scenarios for a water world I had a contract on. Or I could write and/or copy and paste text flavor/lore descriptions for units from a sources I have access to like Sarna, I've always enjoyed reading things like that. I'm not sure how useful these things would be though for your project.

I will attach the txt file I'm keeping suggestions in, just in case you are curious what I'll be asking about on another forums. I will post it in the MekHQ thread next time I'm there.
[MekHQ suggestions.txt](https://github.com/MegaMek/mekhq/files/6675106/MekHQ.suggestions.txt)
