### ISSUE TITLE
Multiple Manual Resolution Bugs

### ISSUE THREAD

**Issue by mnmib1** [MegaMek/mekhq#270]
MekHQ v41.27 windows version

There are multiple problems with the manual resolution.  I have included the campaign file (Stewarts Home Guard), the Battle Resolution file (Battle Resolution.mul), the gamelog.html, the salvage file (salvage.mul), megameklog.txt and the memameklog.txt.  There are no customs.

This scenario was a draw, so neither side controlled the battlefield.

If, during manual resolution, I click on we did control the battlefield:

1:  It recovers our salvage (normally a good thing but not in this case).

2:  I then check the gamelog and find the Wasp ID:57 and the Icarus ID:74 have been destroyed and are in the graveyard.  So I check total loss for these 2 units.

3:  I procede to the next page (pilot recovery).  The Wasp and Icarus pilots are both marked as dead.  I correct the number of hits (0 for Asad, and 1 for Castillo).  After resolution they will have the correct hits, but both will be listed as KIA.

4:  I proceed to claim kills.  The only kills for me to claim are the Wasp and Icarus.  These are MY 'Mechs not the enemy's.  The enemy Awsome ID:18 does not even show up in the list.

If, during manual resolution, I click on we did not control the battlefield:

1:  All of my 'Mechs are listed as total losses, including 'Mechs that never suffered any damage.  I have to manually uncheck each one.

2:  All of my pilots are listed as MIA with the execption of the Wasp and Icarus which are still listed as dead.  I have to uncheck all of my pilots and correct the 2 KIAs.

3:  Same as 4 above.  Both 'Mechs belong to me and the enemy 'Mech is not on the list.

Either way, whether I control the battlefield or not, manual resolve is not working properly.

I have noted that the IDs MekHQ is using prior to and during resoultion, do not match the IDs MegaMek is using.  For example during resolution, the very 1st unit on the list is a Stalker ID:235.  The highest ID assigned to my units by MegaMek is 81.  The ID assigned by MegaMek to the above mentioned Stalker is 42.  This may have nothing to do with the resolution problem, but I thought I would mention it as a possible cause to look at.

On related note, it may be helpful to create individual .mul files for each player at the end of a game.  One for each player (including any and all bot players).  This may help with recovery.  It may even be useful to have individual salvage files.

**Comment by mnmib1** [comment]
I could not post the attached files here, so I posted them on the BattleTech forums at the following 2 links:

http://bg.battletech.com/forums/index.php?topic=55691.msg1281742#msg1281742
http://bg.battletech.com/forums/index.php?topic=55691.msg1281746#msg1281746

**Comment by HammerGS** [comment]
Uploading from saves Forum post

[Manual Resolution Problems 1.zip](https://github.com/MegaMek/mekhq/files/653530/Manual.Resolution.Problems.1.zip)
[Manual Resolution Problems 2.zip](https://github.com/MegaMek/mekhq/files/653531/Manual.Resolution.Problems.2.zip)

**Comment by neoancient** [comment]
From the battle resolution file I can see that you kept an infantry platoon under your control and transferred the remainder of your forces to bot control. However, your forces appear in the MUL where the enemy forces belong and the enemy forces are listed as your allies, which means that you assigned the teams incorrectly. If you switch the <allies> and <salvage> sections, as I have in the attached file, you will find that it resolves correctly with the exception of the assigned kills, which were recorded in keeping with the declared team designations.
[Battle Resolution - corrected.mul.zip](https://github.com/MegaMek/mekhq/files/673537/Battle.Resolution.-.corrected.mul.zip)
