### ISSUE TITLE
Feature request: Double map sizes

### ISSUE THREAD

**Issue by Tamren** [MegaMek/mekhq#2706]
It would be nice if there was a option we could enable in mekhq that doubles the map size of generated missions. This is primarily for people who like incorporating air units because the default sizes are so small ASFs and dropships moving at anything but their slowest speed don't have time to do much before they immediately fly off the map again. But it could also be used by anyone who likes slower more strategic gameplay, especially when a large number of units is used.

Whenever a mission is randomly generated the game would simply double the X/Y dimensions. So 10x30 becomes 20x60 and so on. Scenarios that have a specific fixed size are unchanged except for Breakthrough and Chase who have their width doubled from 18 to 36 tiles. This gives you more room to move about in, but does not modify the length of the map because that would make those scenarios harder or easier depending on the side you play.

**Comment by NickAragua** [comment]
Legacy AtB will no longer be supported (except with bugfixes) going forward, and StratCon generally has larger map sizes (unless your force BV is exceedingly low).

**Comment by Tamren** [comment]
I see, in that case I'll wait for StratCon to settle a bit more before I re-evaluate the need for this.
