### ISSUE TITLE
[UI] Tech crew names in hangar not cut by elipses

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#2707]
MekHQ 49.2
OpenJDK 11

Not sure when it started, but in the hangar tab, too large tech crew names no longer get cut with elipses. Instead they get two lines for their names, which results in visual oddites.

![MechTech name borked](https://user-images.githubusercontent.com/67933202/122682568-2cde7780-d1f2-11eb-93c8-49a60c9b739b.png)

![MechTech name even more borked](https://user-images.githubusercontent.com/67933202/122682575-3a93fd00-d1f2-11eb-91fd-b477c6f57871.png)

I don't think files are needed, to reproduce, just reduce the size of the tech crew column.

**Comment by sixlettervariables** [comment]
I don't believe this has anything to do with the length of their names (the HTML logic for the `Force` column is the same as the `Tech Crew` column). I get those visual oddities with just short names too.

I believe this is a rendering bug.

**Comment by Windchild292** [comment]
The problem appears to be because it uses HTML as part of the backend sorting.

**Comment by sixlettervariables** [comment]
I've only seen this once we went to Java 11 if that helps narrow it down any.

**Comment by Windchild292** [comment]
It occurred as part of my sorting improvements, definitely relating to the HTML

**Comment by Windchild292** [comment]
The ellipses isn't possible due to the age of Swing, which uses HTML 3.2. Ellipses functionality was added around HTML 5.
