### ISSUE TITLE
[StratCon] Mismatch between Convoy Scenario location and strategic objective

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#2726]
MekHQ 49.2

In a extract mission, I had a convoy attack scenario appear at (1, 3) of the map, and the corresponding message in the objectives to "engage and defeat the forces at 1,3".

But then I advanced the day and the convoy moved to (2,2) - pleasantly surprised by that, by the way - but apparently, StratCon doesn't track that. When I finished that scenario, I received the support points (not the VP, but that might be a different bug), but the strategic objective was not completed, because apparently I didn't fight the forces at the right location.

**Comment by NickAragua** [comment]
This should be fixed with PR #2756.
