### ISSUE TITLE
[StratCon] Pursuit scenario errors

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#2728]
MekHQ 49.2

A "pursuit" scenario appeared with all kinds of wrong:

My lance (the pursued) starts at North edge, but the OpFor spawns at the South edge, not exactly pursuers...

An extra grounded dropship spawns with altitude 5 in megamek.

If the campaign savefile is needed, I have it. Logs apparently show no related errors.

[megameklog.txt](https://github.com/MegaMek/mekhq/files/6720285/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6720286/mekhqlog.txt)

**Comment by SuperStucco** [comment]
I've encountered other deployment issues with Pursuit scenarios even when at the same edge, such as OpFor (chaser) deploying at the start of game and player (chased) deploying several rounds later.  The much larger, in numbers and class, size of the OpFor turns it from 'pursuit' to an unwinnable 'breakthrough'.

**Comment by NickAragua** [comment]
In PR #2756, fixed an issue with the Pursuit scenario where the opfor was incorrectly configured to bee-line for the opposite edge. Note that reinforcements are intendended to spawn at the opposite edge.
