### ISSUE TITLE
[49.2] Conflict alternativeFactionCodes (factions.xml) with use of traditional RATs

### ISSUE THREAD

**Issue by AlvarOldebrecht** [MegaMek/mekhq#2736]
### Environment
MekHQ 49.2 (error occurs not with MekHQ 48.0)
Windows 10
Java SE Development Kit 16.0.1 (64-bit)
Java 8 Update 291 (64-bit)

### Description
Units for factions with the new implemented alternativeFactionCodes in factions.xml cannot generate units if "Use traditional Rats" is activated under Campaign Options> Against the Bot.

An example RAT for MOC and TH for the year 2580 is attached. The RAT for MOC works because there is no alternativeFactionCodes. This RAT does not work with TH because an alternativeFactionCodes is defined.

The error can be repeated for all corresponding factions in all RATs. The attached error code is output in mekhqlog.txt. 

### Files
[MekHQ 49-2.zip](https://github.com/MegaMek/mekhq/files/6776323/MekHQ.49-2.zip)

with logs, savegame, rats

**Comment by Windchild292** [comment]
I just learned that Java has two separate ArrayLists... one of which works properly, the other of which (that I unknowingly used) does not.
