### ISSUE TITLE
Victory points not accumulating in StratCon

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#2737]
In the attached 49.2 campaign save, even though victory points are being earned in scenarios they are not being added in StratCon.

[Jansenn's Horde30400209.cpnx.gz](https://github.com/MegaMek/mekhq/files/6793603/Jansenn.s.Horde30400209.cpnx.gz)

They were working for the first couple of contracts/missions but not the last two.

This should cover the custom units:
[Customs.zip](https://github.com/MegaMek/mekhq/files/6793613/Customs.zip)

**Comment by yoshiwars** [comment]
I am also having this problem after upgrading to 0.49.7 mid mission:
[The Pew Pew Pews30320702.cpnx.gz](https://github.com/MegaMek/mekhq/files/8188545/The.Pew.Pew.Pews30320702.cpnx.gz)

This should cover the custom units too:
[customs.zip](https://github.com/MegaMek/mekhq/files/8188567/customs.zip)

Thank you!

**Comment by SuperStucco** [comment]
Closing this myself, this has resolved through some fixes and clarifications.
