### ISSUE TITLE
[49.2] Game freezes when using advance multiple days dialogue with unmantained units

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#2738]
MekHQ 49.2

To reproduce: remove a tech from a unit, go to the advance multiple days dialogue and choose any option. When the nag about the unmantained units appears, click cancel. If you then close the multiple days window, the game freezes, and the entire window becomes unresponsive.

Here's a save were this happens consistently, in case you can't reproduce it
[Lisbon's Shadows30300920.cpnx.gz](https://github.com/MegaMek/mekhq/files/6794990/Lisbon.s.Shadows30300920.cpnx.gz)
[customs.zip](https://github.com/MegaMek/mekhq/files/6794991/customs.zip)

logs show no errors
[megameklog.txt](https://github.com/MegaMek/mekhq/files/6794992/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6794993/mekhqlog.txt)

**Comment by sixlettervariables** [comment]
This should have been fixed by #2719, but I'd you're on a nightly after let me know and we'll reopen.
