### ISSUE TITLE
No warning for pending scenarios on advance day

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#2748]
In the attached 49.2 campaign, using the advance day with a pending day does not give a warning.  The MekHQ settings do not disable the nag dialog, so it should be nagging.

[Autosave-1-Jansenn's Horde-30420212.cpnx.gz](https://github.com/MegaMek/mekhq/files/6831525/Autosave-1-Jansenn.s.Horde-30420212.cpnx.gz)

[Customs.zip](https://github.com/MegaMek/mekhq/files/6831592/Customs.zip)

**Comment by Windchild292** [comment]
I'm going to need the following to properly check, as no log was included.

![image](https://user-images.githubusercontent.com/39067288/126919324-c87ead9a-706c-44ae-9bab-a7c8fba623db.png)

**Comment by SuperStucco** [comment]
This should cover it.

[Customs.zip](https://github.com/MegaMek/mekhq/files/6904404/Customs.zip)

Unrelated but interesting, the Gazelle (Heavy Vehicle) is stock OOTB from ...\dropships.ZIP\TRO3057R.

**Comment by Windchild292** [comment]
Duplicates #2709, fixed by #2711
