### ISSUE TITLE
Easily see how much of a part/ammo is in stock when using one/reloading?

### ISSUE THREAD

**Issue by molemanBT** [MegaMek/mekhq#275]
Hi,

Is there a way to implement a reminder of how many parts you have left? For example, replacing a lower arm activator, at the moment if you don't have the part it will tell you '0 in stock, 0 on order' but if you have at least one, it will just say ‘in stock’. Would it be possible to have it say ‘5 in stock’ just to make it easier to predict ammo/armour shortages.

Many thanks

**Comment by purpledragon2** [comment]
I second this.  In a long running campaign, if you are not in the habit of going to the warehouse or the parts in use tab for every turn (day) then you might easily forget to re-order something that you use quite a bit of.

**Comment by NickAragua** [comment]
This is implemented for armor and ammo in PR #597.
