### ISSUE TITLE
StratCon: Force can deploy to a mission that does not exist

### ISSUE THREAD

**Issue by vipersbrood** [MegaMek/mekhq#2755]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
V 0.49.2
Windows
Java SDK16

### Description
Able to deploy force to a battle not listed under briefings. Unable to end contract in StratCon. Error shows in log "java.lang.reflect.InvocationTargetException"

### Files
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6837460/mekhqlog.txt)
[Broodlings30340224.cpnx.gz](https://github.com/MegaMek/mekhq/files/6837462/Broodlings30340224.cpnx.gz)

**Comment by NickAragua** [comment]
Fixed with PR #2756
