### ISSUE TITLE
Impossible Kick NPE and Hang

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/mekhq#276]
First things first I was able to continue the game with the skip command so this can be low priority.

Using HQ playing a mission in MegaMek

Error appears to be occurring when a DFA coincides with a domino effect move (of my mech may or may not make a difference) occurs before an allied princess mech attempts a kick on the DFAed mech.
The game appeared to hang with the text that my ally was deciding it's physical attacks.
I was able to bypass the error with the skip command and then went to look at the logs.

It appears that the DFA moved the enemy mech before the kicks from the enemy and the ally mech were calaulated (they were trying to kick each other)  
The log lists both of their kicks as impossible which I believe occurred because after the move the mechs were no longer in the adjacent hexes and therefore looked invalid to the program.
I am not sure if the domino effect and/or having to ask me which way to move my mech is part of the issue.

As I mentioned the log states a NPE so I figure this is something that might need looking at.

I don't know if this is necessarily a HQ problem but it seems the catalyst forums are down so I was not able to confirm the bug there before posting it here. 

Let me know if any other log files are needed 

Edit: tried to continue by clicking done on the physical attack screen no response, had to quit MegaMek

[gamelog - Imposible kick.zip](https://github.com/MegaMek/mekhq/files/665535/gamelog.-.Imposible.kick.zip)

[mekhqlog - Imposible kick.zip](https://github.com/MegaMek/mekhq/files/665536/mekhqlog.-.Imposible.kick.zip)

[autosave.sav.gz](https://github.com/MegaMek/mekhq/files/665537/autosave.sav.gz)

**Comment by pheonixstorm** [comment]
This is a MM bug and should be reposted on the MM tracker.
