### ISSUE TITLE
Cannot Customize VTOL in MekLab

### ISSUE THREAD

**Issue by jschmetzer** [MegaMek/mekhq#2774]
### Environment
49.03 Snapshot from Build Nightly CI #470
Mac

Bug: cannot add VTOL to meklab (click has no effect) for customization

To recreate:
1. generate an empty new campaign using default Taharqa preset campaign settings
2. GM add a VTOL
3. Attempt, using right-click menus from Hangar screen, to customize with MekLab

Can add a campaign file if necessary, but I tested with raw campaign with default settings.

**Comment by Windchild292** [comment]
This holds for most forms of unit customization.
