### ISSUE TITLE
[49.2] Customize Personnel dropdowns letter quick scrolling is broken

### ISSUE THREAD

**Issue by SVNaas** [MegaMek/mekhq#2786]
### Environment
MekHQ 49.2
Windows 10
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file. (this is actually missing from my mekhqlog.txt file and only present in the megameklog.txt which MekHQ is populating)
Java version 11.0.11

### Description
When customizing personnel via the GM edit tool in MekHQ the dropdowns exhibit strange/broken behaviours. Behaviours as follows:
If the gender dropdown is opened and the keyboard is used to select the already selected gender the name is rerolled, this is likely unintended behaviour as no actual change took place. Suggestion: Change it to a click/commit reroll when the dropdown menu closes?
When Origin faction is expanded using the letter keys to search doesn't work always work and often just fails to do anything entirely, when the letter keys do work they navigate the menu as if using the arrow keys.
Origin System and Planet behave in the same way.
If a clan origin faction is selected and deselected the Phenotype menu remains accessible and only becomes unavailable after being expanded, the phenotype will fail to apply but it is likely unintended behaviour.

### Files
No exceptions are present in logs related to this (other than seemingly outdated customs due to quirks and some weapons being renamed). Customs not included as there are no units yet in the campaign, only three personnel. Customs can be provided if needed to recreate the behaviour.
[Winterfold30490101.cpnx.gz](https://github.com/MegaMek/mekhq/files/6918936/Winterfold30490101.cpnx.gz)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6918921/mekhqlog.txt)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/6918922/megameklog.txt)

**Comment by Windchild292** [comment]
Thinking about name generation on gender changes... I'm just going to remove it. The cause is because of base Java functionality.

The text search no longer working is due to Java and will need further investigation as part of the base components setup.

Phenotype is a bug.
