### ISSUE TITLE
Upgraded Quasit MilitiaMech versions appearing ahead of tech introduction

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#2789]
The QUA-51M and QUA-51P Quasit MilitiaMechs mount MMLs and a plasma rifle, respectively.  However they can still appear in generated civilian forces well ahead of the introduction of those weapons (I've had both appear in pre-3040 campaigns).  This is likely due to their appearance in [..\data\rat\rat_default.zip\Against The Bot\CivilianUnits.txt](https://github.com/MegaMek/mekhq/blob/master/MekHQ/data/rat/Against%20The%20Bot/CivilianUnits.txt) and [..\data\rat\rat_default.zip\Against The Bot\CivilianUnits_CivMech.txt](https://github.com/MegaMek/mekhq/blob/master/MekHQ/data/rat/Against%20The%20Bot/CivilianUnits_CivMech.txt).  As far as I can tell, that's the only place selection of civilian units happens - the ..\data\forcegenerator XMLs or ..\userdata\data\forcegenerator override XMLs don't appear to have an effect on their selection.

Because the civilian RATs don't include year/era selection, in the short term it might make sense to remove these advanced units.  Longer term I'd like to see the same forcegenerator XML files (or a successor - the formatting could be a bit easier) being used for all unit selection, whether it's frontline combat, civilians, or turrets.

**Comment by Windchild292** [comment]
Duplicates #1416
