### ISSUE TITLE
Feature Request: Rank Insignia and Medals

### ISSUE THREAD

**Issue by mnmib1** [MegaMek/mekhq#279]
Rank insignia and medals.

**Comment by purpledragon2** [comment]
+1  I know this one is being worked on.

**Comment by firefly2442** [comment]
See PR https://github.com/MegaMek/mekhq/pull/801

**Comment by Windchild292** [comment]
Hasn't this been implemented by PR #801?

**Comment by HammerGS** [comment]
Implemented
