### ISSUE TITLE
[48.0] Unable to right click single units in 'personnel' tab.

### ISSUE THREAD

**Issue by Skye-Storm** [MegaMek/mekhq#2790]
### Environment
Version: 0.48.0
OS: Windows
Java: 1.8.0_271

### Description
After a battle in a campaign, I was unable to right click singular units in the personnel tab. If multiple units were clicked then the option would be available. I had two saves post battle and one before. The save prior the battles suffered no issues. The saves after the battle did (one without advancing the day and one with.)

Using a prior save that still functioned, I attempted to duplicate the process as best as I could. Buy and selling the same equipment, removing the same people, etc. Was unable to duplicate the instance.

### Files
[Trilani Union20210809.cpnx.gz](https://github.com/MegaMek/mekhq/files/6928494/Trilani.Union20210809.cpnx.gz)
[Customs.zip](https://github.com/MegaMek/mekhq/files/6928497/Customs.zip)
[megameklablog.txt](https://github.com/MegaMek/mekhq/files/6928490/megameklablog.txt)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/6928491/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6928492/mekhqlog.txt)

**Comment by Windchild292** [comment]
This shouldn't be possible. A person has a null birthday...

**Comment by Windchild292** [comment]
Adding a default value, but... it shouldn't be possible regardless outside of save file editing or maybe a failure during game completion. Opening up a fix with the default.
