### ISSUE TITLE
Missing faction change event for Aldebaran, Gan Singh and Zurich for the year 2367

### ISSUE THREAD

**Issue by AlvarOldebrecht** [MegaMek/mekhq#2799]
Missing events in system_events.xml for the Aldebaran, Gan Singh and Zurich systems for the year 2367, where the systems transition from the Duchy of Liao to the Capellan Confederation.

**Comment by Windchild292** [comment]
Source?

**Comment by AlvarOldebrecht** [comment]
The Duchy of Liao ceased to exist in 2366. First, this record is in the factions.xml

        <shortname>DoL</shortname>.
        <fullname>Duchy of Liao</fullname>.
        <eraMods>1,0,0,1,2,3,2,1,0</eraMods>
        <nameGenerator>CC</nameGenerator>
        <colorRGB>2,166,79</colorRGB>
        <tags>is,minor</tags>
        <start>2315</start>
        <end>2366</end>
        <successor>CC</successor>
        
       Second: Handbook: House Liao, p. 17, "Capellan Confederation Founding, 2366" and Handbook: House Liao, p. 13, "Timeline: 
        Capellan Zone 2367"

**Comment by Windchild292** [comment]
Fixed by https://github.com/MegaMek/mekhq/commit/de605e8675ce7571272c80156e5a7eb9822d4042
