### ISSUE TITLE
Feature Request: Discrete Portait Folders

### ISSUE THREAD

**Issue by mnmib1** [MegaMek/mekhq#280]
Discreet portrait folders.  Some of my pictures (a lot of the ink effect) are perfect for soldiers.  I have a lot of people in suits (doctors/admins).  Others are good for MechWarriors.  And my battle armor pictures are only good for battle armor.  Ralgith should know what I'm talking about.  He had some ideas about how to implement this years ago.

**Comment by Kendricke** [comment]
I would like to +1 this request.  I have literally hundreds of custom portraits I've created for use in specific roles which I'm currently manually assigning each time I bring on a new recruit.

**Comment by Kendricke** [comment]
Related:  https://github.com/MegaMek/mekhq/issues/471

**Comment by Bonepart** [comment]
Seems like a reasonable request and it's been around for awhile. I don't think it should be TOO hard to implement. I'll try to look into it in the near future.

**Comment by Qwertronix** [comment]
Nice to see this is in the 0.43.5 code! If I could make just one suggestion though, any chance we can get a similar single folder for all "Tech" personnel like was done for "Admin"? Not a big deal, but I don't think most people will want separate sets of portraits for each different tech role.

**Comment by Kendricke** [comment]
I actually do have separate portraits I use for different types of techs and admin.  Is it possible to just run a check to see if different subfolders exist?  If not, use the base tech or admin folder?

**Comment by Qwertronix** [comment]
Sure, I think a layered fallback would work. Search for folder with the exact name first, then group name, then if still not found then the gender one.

**Comment by Kendricke** [comment]
For purposes of troubleshooting (and actually better using the feature), can we get a list of the folder structure we should be using moving forward?  I can't find this in documentation or notes and some of the roles dont' seem to be working and the layered fallback mentioned in #534 doesn't seem to be working, either.

**Comment by Qwertronix** [comment]
I'll update my files to the dev snapshot and take a look at what's not working. 

The basic structure is that first it looks for a folder with the exact name of the primary role. If that folder doesn't exist, is empty, or contains only pictures which are already assigned, it is skipped. Next it checks for "group" folders, if it applies to the role. Those are `Admin/`, `Tech/`, `Medical/` and `Vessel Crew/`. Same here, if empty, etc., skip. Next it looks for the `Combat/` or `Support/` folders. If it still hasn't found any possible portraits, it finally goes back to the regular gendered `Male/` and `Female/` folders. 

If it _does_ find at least one eligible picture in one of those folders, it stops there and picks a random picture from the eligible ones in that folder. In this case it will not look further, so if you put pictures in both `MechWarrior/` and `Combat/`, Mechwarriors should never be assigned one of the pictures in the combat folder unless all the MW-specific pictures are already assigned.

**Comment by SirMegaV** [comment]
Just a suggestion, can you put that info.txt in the portrait folder and
make skeleton folders so that the user doesn't create a folder with the
wrong name?

**Comment by Qwertronix** [comment]
That makes sense. I don't see why not. 

I'm retesting most use cases to see if I'm missing anything and see if there's situations where it wouldn't work... but this is the same code that I've been using and testing without issues for a couple weeks now, so any specifics on what's not working or how, in which circumstances, etc. ideally with campaign files and such would help.

**Comment by Windchild292** [comment]
All that appears left to do here is add documentation, which I've written and opened up a PR for. I think we can finally close this one, three and a bit years later.
