### ISSUE TITLE
[49.3][StratCon] Grounded Dropship Scenario Fails to Start - Issues in Lobby

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#2809]
Windows 10
MekHQ 49.3 - Nightly from 21-07-2021

This is a grounded dropship scenario where the allied dropship was changed to my own. There are also a couple of allied aerospace units from an Allied AirBase. Starting the scenario hangs the lobby during the opfor loading. If started at that point, the enemy units actually load and the mission carries on normally, albeit without the aero units.

Changing almost anything related to any team, like changing OpFor's team number, or changing the ownersip of the dropship, allows the lobby to load the main opfor units, only to hang again after that.

After a long while (several minutes) the lobby asks if I want the assigned units to the dropship to start loaded (in the ToE, I do have units assigned to it, but I don't believe this to matter). It asks about the aero units and the ground units. Regardless of the answer, the lobby then disconnects and exits.
Strangely, the second time this prompt appeared, I answered yes, the aero units loaded into the lobby (but not the dropship), the ground units loaded into the dropship (which I then unloaded) and I was able to carry out the mission. I haven't managed to get that behaviour again.

The reason I put this in MekHQ (I could be wrong though) is because if I edit the scenario and regenerate the bot forces, an allied dropship is rolled and the lobby loads with no issue, so the problems appear to be related to the generated OpFor from the campaign.

[Lisbon's Shadows DropshipScenarioBug.cpnx.gz](https://github.com/MegaMek/mekhq/files/6998100/Lisbon.s.Shadows.DropshipScenarioBug.cpnx.gz)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/6998101/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6998103/mekhqlog.txt)
[customs.zip](https://github.com/MegaMek/mekhq/files/6998104/customs.zip)

**Comment by NickAragua** [comment]
This has been fixed
