### ISSUE TITLE
[0.48] Mission Enemy changed and not being applied

### ISSUE THREAD

**Issue by buzzzz2138** [MegaMek/mekhq#2813]
### Environment
0.48
Win 10
OpenJKD 11

### Description
The autosave is just before the error.  Advance a day for it to continue.  The zip file has the custom mechs as well. 
The next day should be a Monday and that will cause new scenarios to be created.  The mission contract is for Rebels.  Originally it was for clan wolf, but was changed to Rebels, via edit mission, because Clan wolf doesn't invade the plant, called The Edge, until march of 3050.  The current data is around November of 3049. 
It appears that any new missions have clan wolf as the enemy when it should be Rebels. 

The March 3050 date for the invasion of The Edge comes from the book Clan Wolf, page 57. 

### Files
[customs.zip](https://github.com/MegaMek/mekhq/files/7009173/customs.zip)
It's a 7zip file but githut doesn't allow those to be uploaded so name change to .zip.  Open with 7Zip.

**Comment by Windchild292** [comment]
Hey, I'm unable to open the file properly. Can you instead use 7 zip to zip it into a zip file instead of the current system?

**Comment by buzzzz2138** [comment]
[Tmp.zip](https://github.com/MegaMek/mekhq/files/7009209/Tmp.zip)
Try this.

**Comment by buzzzz2138** [comment]
It was late so wasn't thinking clearly when I created the file.

**Comment by Windchild292** [comment]
That one works, thanks

**Comment by Windchild292** [comment]
The bot name doesn't change, but the OpFor faction is Rebels.

**Comment by Windchild292** [comment]
Working as intended. You can customize the bot name separate from the OpFor faction.

**Comment by buzzzz2138** [comment]
Shouldn't the Bot name not updating be the bug then?

**Comment by Windchild292** [comment]
That's working as intended. Because a player may want to have a bot name that does not line up with the OpFor faction, we cannot do an automatic change.

**Comment by buzzzz2138** [comment]
A RFE for a Default Bot Name selection in the Edit Mission screen?
