### ISSUE TITLE
Several daily/monthly events failed to occur on 1st of month

### ISSUE THREAD

**Issue by TheSilentK21** [MegaMek/mekhq#2816]
### Environment
MekHQ v49.2
Win 10 Home
Java 11.0.11 2021-04-20

### Description
Certain events failed to happen on the first of the month. Experience, refits, and I think maintenance and morale rolls all got skipped; repairs in progress stayed in progress and didn't advance. Contract did not pay out, salaries were not paid, nor was overhead expenses. Also the displayed date was behaving oddly... still showed the 30th on the log and header until I reloaded that save, then it displayed the 1st.

### Files
[megameklog.txt](https://github.com/MegaMek/mekhq/files/7011412/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7011413/mekhqlog.txt)
[Fighting Bulldogs30500630 Glitched 1.cpnx.gz](https://github.com/MegaMek/mekhq/files/7011414/Fighting.Bulldogs30500630.Glitched.1.cpnx.gz)
[Fighting Bulldogs30500701.cpnx.gz](https://github.com/MegaMek/mekhq/files/7011430/Fighting.Bulldogs30500701.cpnx.gz)
(Note that certain actions were performed before realizing it wasn't still the 30th; two repairs were GM mode completed and this save is from after funds were added and removed for monthly expenses when I realized that hadn't happened.)
[AllMyCustoms8-18-21.zip](https://github.com/MegaMek/mekhq/files/7011486/AllMyCustoms8-18-21.zip)

**Comment by Tecmes** [comment]
I remember having had this exact issue multiple times.
Often, the date for the 1st day would appear in the log pane, but directly after the 30th date, without clearing the pane and without line break, something like "January 30thFebruary 1st".
I never posted a report because I've never been able to find a way to reproduce reliably.

**Comment by Windchild292** [comment]
They are normally had to recreate, but should have an exception in the logs that we can use to figure out the problem (normally, at least).
