### ISSUE TITLE
RFE [0.48] Modify Default Bot Name in Mission Edit

### ISSUE THREAD

**Issue by buzzzz2138** [MegaMek/mekhq#2824]
### Environment
0.48
Windows 10
OpenJKD 11.

### Description
When selecting the Edit Mission in the Briefing Room, changing the Enemy does not change the Bot Name. 
This RFE is to have either a checkbox to update the bot name or text box to enter default bot name. 
Otherwise it can be difficult to know what type of forces are populating the AtB force. 
For example, if you have a contract near the clan invasion and start with a contract against the clans then change it over, it will say something like Clan Wolf for the Bot name, but the units won't have any clan mechs. 
Adding this feature would reduce that confusion and allow it be kept the way it is not as well.

**Comment by Windchild292** [comment]
You can already change the bot name in the top right of the dialog.
