### ISSUE TITLE
Dropship Doors Breaking on Loading

### ISSUE THREAD

**Issue by EngelNUL** [MegaMek/mekhq#2829]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
0.48.0
Windows
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7025963/mekhqlog.txt)
[Thirdwave Defense Industries30350508.cpnx.gz](https://github.com/MegaMek/mekhq/files/7025965/Thirdwave.Defense.Industries30350508.cpnx.gz)

SE 8

### Description
Dropship doors damaged when load game or return from mission in MM
![image](https://user-images.githubusercontent.com/89315989/130331078-aa0e6e3e-2854-439f-b459-fb6856595e3e.png)

**Comment by Windchild292** [comment]
I'm going to need your customs, both the Union and the Wasp Mk II's

**Comment by Windchild292** [comment]
Closing given the lack of response in a year.
