### ISSUE TITLE
[49.3] Daily Log unintended behaviour(?) when clicking names causes it to load All Personnel

### ISSUE THREAD

**Issue by SVNaas** [MegaMek/mekhq#2837]
Clicking on a personnel member's name in the daily log takes you to All Personnel, in older versions this used to default to Active Personnel (or just the person without changing the active role filter). This can be misleading as it will show the KIA, MIA, and Retired personnel in the list and, therefore, likely shouldn't default to All. The only thing this suggestion would prevent showing is Prisoners, as they aren't shown as Active Personnel and would need to either be included in the Active filter or filtered to if clicked in the Daily Log.

**Comment by Windchild292** [comment]
Intended and desired behaviour, as it will only change the filter if it cannot find the person with the current filter. The change was due to the expanded filter options and the unintended behaviour of a link not showing the person if they weren't on the current filter.
