### ISSUE TITLE
Feature Request: Option to set a default SPA for all personnel and if using AtB rules generate SPAs for prisoners

### ISSUE THREAD

**Issue by SVNaas** [MegaMek/mekhq#2839]
Given a lot of users utilise SPAs, it would likely be a good idea to have a toggle somewhere in the game options to set it so any personnel with a Clan origin generate with Clan Pilot Training (if they belong to a pilot skilled role). This would be a QoL change to help with the tedium of having to always edit pilots. Secondary to this (and to avoid issue clutter), prisoners should generate SPAs when captured per the AtB rules. Something they don't currently do if ranked at veteran or above.

**Comment by Windchild292** [comment]
1) Duplicates #403, with the player being the only difference.
2) Duplicates #2643
In future, please open one issue per request.
