### ISSUE TITLE
[49.3] Oversight: LAM Pilots have no applicable role filter

### ISSUE THREAD

**Issue by SVNaas** [MegaMek/mekhq#2840]
LAM pilots lack a filter applied to them/for themselves. As such they don't show up as MechWarriors or if using filters other than the non-role specific ones, such as All, Active, etc.

**Comment by Windchild292** [comment]
Invalid. LAM Pilots show up under the MechWarriors grouping and the LAM Pilot grouping when using the individual role filter setup. There is a bug with both MechWarriors types showing up when using individual roles though
