### ISSUE TITLE
[0.49.3] [Stratcon] When starting game in scenario, units do not populate and then server is disconnected.

### ISSUE THREAD

**Issue by Psykoraptor** [MegaMek/mekhq#2843]
What version of MekHQ does your issue apply to?
0.49.3
What operating system are you using?  Windows, Mac, or Linux?
Windows 10
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.
11

When on contract and you get a scenario, units are listed in MekHQ. When you click 'Start Game' it loads into MegaMek only showing the lance deployed, not the allies or OpFor. Then after a time, the game disconnects. Even when the Delay Timer is set to max in MekHQ.

[megameklog.txt](https://github.com/MegaMek/mekhq/files/7050843/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7050844/mekhqlog.txt)
[Taurian Irregulars27810221.cpnx.gz](https://github.com/MegaMek/mekhq/files/7050846/Taurian.Irregulars27810221.cpnx.gz)

**Comment by Question2** [comment]
Ive had this happen as well. Without stratcon. Its random so its impossible to replicate 100% of the time...sometimes when starting a scenario, allies and opfor are not loaded properly.


The disconnect issue seems to be a seperate issue.

**Comment by Windchild292** [comment]
I believe this is resolved along with #3063, which will be part of 0.49.7. If they fail to load in 0.49.7, please open a new issue.
