### ISSUE TITLE
(0.48.0) Game Fails to Save

### ISSUE THREAD

**Issue by bunnielab** [MegaMek/mekhq#2853]
### Environment
What version of MekHQ does your issue apply to?
Version 0.48.0
What operating system are you using?  Windows, Mac, or Linux?
Win 10
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.
Java version 11.0.12

### Description
Describe the issue and provide screenshots ingame if able.
Game gives the following error when I try to save a given campaign:
![image](https://user-images.githubusercontent.com/89744066/131259532-1763101b-bd8e-4b3d-bc63-7632ea9b40d3.png)
And provide the steps you have taken to reproduce the issue in the campaign file if applicable.
I cannot seem to reproduce the error deliberately although it has occured in 2-3 campaigns out of maybe 6-7 played.  

### Files
EDIT 8/29/21 1:34est - Replaced logs with correct ones
[entitystatus.txt](https://github.com/MegaMek/mekhq/files/7072957/entitystatus.txt)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/7072958/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7072959/mekhqlog.txt)

**Comment by Windchild292** [comment]
The logs have nothing in them, which means that they aren't the ones that are from this error message.
We'll need the proper logs, the campaign file, and any custom units.

**Comment by Windchild292** [comment]
User had the program running in program files. I'm waiting to hear back about if moving it fixed the issue

**Comment by Windchild292** [comment]
No further comments about issues, I believe this to be fixed.
