### ISSUE TITLE
RFE Filter or flag for pregnant personnel

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/mekhq#2863]
Please could you add some kind of notation for pregnant personnel, perhaps a yes/no column in the 'fluff info' or 'biographical info' view, or maybe highlight their row on the table a bright colour (similar to injured personnel)?

This would be very helpful, facilitating prevention of Dwarf Fortress style pregnant combatants :)

**Comment by Windchild292** [comment]
Expected Due Date will be the added column

**Comment by Windchild292** [comment]
Ended up adding a whole filter for dates, so all of the tracked ones are displayed, and a pregnancy colour
