### ISSUE TITLE
Feature Request: Additional configuration options

### ISSUE THREAD

**Issue by mnmib1** [MegaMek/mekhq#289]
Additional functions when configuring a player.  Right now you can add an initiative bonus or minefields by right-clicking on the player.  This is good for giving a player's entire force an initiative bonus/malus without it being permanent.  However, many forces in the field manuals, sourcebooks, etc. gain a bonus/malus to gunnery and/or piloting under certain conditions only.  For example: The 20th Arcturan Guards, in ice or heavy snowfall, gain a 2 point bonus for all piloting rolls.  It would be much easier to add this here, as a temporary effect, rather than changing each MechWarrior's piloting skill, and then changing it back.  This would begin to allow force specific bonuses.
Including a gunnery and piloting team bonus on the configuration tab would go a long way.

**Comment by mnmib1** [comment]
Sorry wrong place.  Please move to MM.

**Comment by pheonixstorm** [comment]
Unless something changed you will have to start a new ticket on the MM tracker. GH doesn't allow for moving tickets like sf.net did.

**Comment by HammerGS** [comment]
Also keep in mind the tracker on SF is reviewed on a regular basis. I've opened this one over their years ago. So there is really no point in duplicating stuff on the two trackers.

We made an exception for that for one bug, that we received additional information on and felt it was better here.
