### ISSUE TITLE
RFE: Check box for option to have prisoners be generated with looking to marry flag set to off

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/mekhq#2895]
When prisoners are created after a battle they are looking to marry.  Some commands my look unfavorably at their prisoners getting married.  If a check box could be available in the options to have all generated prisoners created with their looking to marry flag set to off it would be helpful.  

This RFE does not apply to people set to prisoner after their initial generation.  If a person is set to be a prisoner manually it is out of scope for this RFE to adjust their status.

**Comment by Windchild292** [comment]
The flags are meant to be overrides, so I'm going to do it as an option to prevent/enable marriage for prisoners instead.

**Comment by MarcJC** [comment]
Either way should work as long as one toggle turns it off.
