### ISSUE TITLE
RFE: Check box to cause created prisoners to have thier trying to get pregnant flag set to off

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/mekhq#2896]
When female prisoners are created after a battle they are trying to get pregnant.  Some commands my look unfavorably at their prisoners getting pregnant.  If a check box could be available in the options to have all generated prisoners created with their trying to get pregnant flag set to off it would be helpful.  

This RFE does not apply to people set to prisoner after their initial generation.  If a person is set to be a prisoner manually it is out of scope for this RFE to adjust their status.

**Comment by Windchild292** [comment]
The flags are meant to be overrides, so I'm going to do it as an option to prevent/enable procreation for prisoners instead.
