### ISSUE TITLE
Extinct components still purchasable in 3028 even with disallow extinct units turned on

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#290]
In 41.28, i have disallow extinct units turned on in 3028, but i can still purchase mech endo-steel locations (arms, head, etc).

I can also purchase plenty of extinct items like artemis ammo.

MML ammo is also strangely available even though it hasn't been invented in 3028 yet.

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/673479/mekhqlog.txt)

Github is being stupid and refusing to accept my .zip file, so i uploaded it here : http://www.mediafire.com/file/smm8pv9sszxcc17/test.zip. It contains the campaign save and the custom mechs.

**Comment by Question2** [comment]
Probably related : if you check the unit market you can see plenty of extinct units offered for sale, even with disallow extinct units on.

[test.gz](https://github.com/MegaMek/mekhq/files/674195/test.gz)

**Comment by neoancient** [comment]
This was fixed with the IOTech feature.
