### ISSUE TITLE
49.3 : ATB, Prison Break awarded vehicles that are stuck at 0/0 movement despite showing no signs of damage

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#2900]
Just finished a prison break mission that awarded me a heavy wheeled APC and armored personnel carrier. Both vehicles are crippled at 0/0 movement despite showing no signs of damage. All allied vehicles in the mission fled off the board without taking damage.

![image](https://user-images.githubusercontent.com/1191378/136675637-11e86e6c-9fac-4d0f-8cd1-245df2724275.png)
[mechfiles.zip](https://github.com/MegaMek/mekhq/files/7316516/mechfiles.zip)

[b.zip](https://github.com/MegaMek/mekhq/files/7316518/b.zip)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7316519/mekhqlog.txt)

**Comment by Windchild292** [comment]
Duplicates #2323, just hire/assign a crew
