### ISSUE TITLE
0.49.3: AtB Lobby Connection Issues

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#2902]
After I selected "all attached units are player controlled" in the ATB options, bot units no longer load at all in the lobby. I have restarted mekhq multiple times and tried starting the scenarion multiple times, but each time it simply loads my units then refuses to load the bot's units.

![image](https://user-images.githubusercontent.com/1191378/137141697-1b2cd0e5-26f1-429b-8d29-7500c842db34.png)
[b.zip](https://github.com/MegaMek/mekhq/files/7338454/b.zip)
[mechfiles.zip](https://github.com/MegaMek/mekhq/files/7338455/mechfiles.zip)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/7338456/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7338457/mekhqlog.txt)

**Comment by Windchild292** [comment]
The option is not related and is working properly from the image in question... but this definitely recreates on my laptop.

**Comment by Question2** [comment]
Yes, the option does let you control allied units, but it prevents the opfor bot from loading their units.

**Comment by Windchild292** [comment]
"The option is not related and is working properly."

There is a connection issue, but it isn't related to the option

**Comment by kernhe** [comment]
May be related (duplication) of #2956

**Comment by Windchild292** [comment]
What's your Java RAM assignment for MekHQ and MegaMek?
Please attach the "MegaMek.l4j.ini" and "MekHQ.l4j.ini" files to this.

**Comment by Windchild292** [comment]
Closing given there's been no updates in two months and there's been a huge amount of related changes.
