### ISSUE TITLE
RFE: Allow a GM override to force complete a contract when an extension occurs 

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/mekhq#2919]
Related to previous issue 2918 in 49.3 when my contract was extended, I had no way to force the completion of the contract.  My attempts to go back into the complete contract button just gave the same extension message (with the same extension time frame)  

It would be nice if there was a way to GM override a contract extension, for whatever reason a GM desires.  
Perhaps a hyperlink could be placed after the message is printed, and when clicking would open a window for the GM to complete the mission and enter any required details.  

Thank you.

**Comment by IllianiCBT** [comment]
This functionality has been in for a while. Closing as resolved.
