### ISSUE TITLE
Starleague cache 1: IndexOutOfBoundsException when generating enemy

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#292]
Got an index out of bounds error when mekhq was attempting to generate the opfor for a star league cache mission.

[test.gz](https://github.com/MegaMek/mekhq/files/678142/test.gz)

Edit : Reloading the campaign save appears to have generated an opfor, but the opfor is of the wrong weight class and there are now two allied tech bots, one of which has 3 heavy units in it.

It looks like mekhq incorrectly assigned the 3 heavy mech lance to tech allied instead of rebels enemy. Then it incorrectly generated a second opfor (the 3 light mech lance).

**Comment by neoancient** [comment]
The scenario generated a primitive 'Mech, which involves no enemy. The `IndexOutOfBoundsException` came from trying to select a non-existent enemy, and the unusual symptoms on reload come from not finding an enemy, generating one, and jamming into the wrong place (where the tech was originally generated), then generating a new tech force after it.
