### ISSUE TITLE
[RFE] Order multiple from Repair bay> Parts Acquisition box

### ISSUE THREAD

**Issue by FelixGold** [MegaMek/mekhq#2925]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
MekHQ 0.49.3
Windows
Java 11

### Description
I think it would be useful to add an "Order X" button when acquiring items you are missing equipment on the Parts Acquisition box, so you can order multiple tons of ammo, or backup weapons that are in demand rather than ordering a single part, then navigating to another part of the program to order more.
![](https://media.discordapp.net/attachments/458706545379639296/903032416019562526/unknown.png)

**Comment by repligator** [comment]
Closing as completed.
