### ISSUE TITLE
MekHQ 0.48.0 Can't Access Hangar

### ISSUE THREAD

**Issue by Decimus-Vitalis** [MegaMek/mekhq#2928]
### Environment
MekHQ 0.48.0
Windows 10
Java 1.8.0_241

### Description
Unable to view hangar fully enter hangar - does not load unless clicked on. When advancing days, command center does not reset with new text and date at top of screen does not update.

### Files
[Co-op SLDF Remnants30420101.cpnx.gz](https://github.com/MegaMek/mekhq/files/7435866/Co-op.SLDF.Remnants30420101.cpnx.gz)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7435864/mekhqlog.txt)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/7435860/megameklog.txt)
![MekHQ Hanger Error](https://user-images.githubusercontent.com/93338720/139297958-6e34e6d7-51f5-4f87-9d5b-049b46d07b68.png)
![MekHQ Dates Error](https://user-images.githubusercontent.com/93338720/139298027-35b361de-a900-45a8-bf15-1efd6fb844a0.png)

**Comment by Windchild292** [comment]
It's attempting to refit into a unit file that doesn't exist as part of the save, namely the Mad Cat (Timber Wolf) Freyja. Based on the name, can I assume this campaign file was being passed around? If so, someone forgot to send a mechfile with the save.
