### ISSUE TITLE
Rank System Pay Multiplier Extended Decimal

### ISSUE THREAD

**Issue by rroby1** [MegaMek/mekhq#2931]
### Environment
MekHQ  version: 0.49.3
Operating system: Windows 10 
Java vendor Eclipse Adoptium
Java version 11.0.13

### Description
While setting up a custom rank and adjusting the pay multiplier several ranks "extend" the decimal. Rate E1 shows 1.1 while E2 shows 1.2000000000000002.   

Rates E2, E4, E7, E10, E11, E13 - E18, E20, WO3, WO5 - WO9, O1, O3, O5, O8, and O10 - O20 all exhibit this same thing. 

### Files

![image](https://user-images.githubusercontent.com/61069665/139426414-4bc858ea-f83e-4eaa-a5bc-7615ac764ed7.png)

**Comment by Windchild292** [comment]
This is a known and open bug in OpenJDK: https://bugs.openjdk.java.net/browse/JDK-8220811
