### ISSUE TITLE
[49.4-Snapshot] Every personnel becomes a driver when assigned to a vehicle

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#2932]
MekHQ 49.4 Snapshot - Nightly 558
Win 10

I noticed when putting crew (drivers and gunners) in a tank that the ToE showed them all as drivers. Checking the personnel tab confirms it:

![Screenshot 2021-10-29 155412](https://user-images.githubusercontent.com/67933202/139457971-d154b544-11dc-4005-9d81-a906037e50fe.png)

How it looks in the ToE:
![Screenshot 2021-10-29 160833](https://user-images.githubusercontent.com/67933202/139459001-fa14be7d-56bc-4d71-b767-197a6dfadaa8.png)

I also noticed that the soldier platoon in the ToE is also considered to be full of drivers

![Screenshot 2021-10-29 155523](https://user-images.githubusercontent.com/67933202/139458094-6dcba428-2565-4ffc-af2c-4c1ccd35636a.png)

Very early campaign save:
[Lisbon's Ravagers NoContract 5.cpnx.gz](https://github.com/MegaMek/mekhq/files/7442928/Lisbon.s.Ravagers.NoContract.5.cpnx.gz)
Recent campaign save:
[Lisbon's Ravagers NoContract 5.cpnx.gz](https://github.com/MegaMek/mekhq/files/7442939/Lisbon.s.Ravagers.NoContract.5.cpnx.gz)

Logs
[megameklog.txt](https://github.com/MegaMek/mekhq/files/7442944/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7442945/mekhqlog.txt)

**Comment by Windchild292** [comment]
This is a display issue, and thankfully not a tracking issue

**Comment by Windchild292** [comment]
https://cdn.discordapp.com/attachments/458706545379639296/907064678394494976/unknown.png

It also occurs on the Personnel Tab.

**Comment by Windchild292** [comment]
It also occurs on the personnel tab.

![Example](https://cdn.discordapp.com/attachments/458706545379639296/907064678394494976/unknown.png)

**Comment by NickAragua** [comment]
Likely fixed with #2963
