### ISSUE TITLE
49.4 snapshot MegaMek shutdowns right after loading from MekHQ 

### ISSUE THREAD

**Issue by deadduck866** [MegaMek/mekhq#2934]
When starting a mission in MekHq, Megamek loads and then shuts down right away.
this seems to be affecting older MekHQs versions as well
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7447778/mekhqlog.txt)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/7447779/megameklog.txt)
[My Campaign31500531.cpnx.gz](https://github.com/MegaMek/mekhq/files/7447794/My.Campaign31500531.cpnx.gz)

**Comment by NickAragua** [comment]
Needs a pair of customs.

**Comment by NickAragua** [comment]
Never mind, got it.

**Comment by NickAragua** [comment]
Fixed with PR #3226
