### ISSUE TITLE
[49.4 Mac] Themes not changing when menu selected 

### ISSUE THREAD

**Issue by cam-smith** [MegaMek/mekhq#2935]
### Environment
0.49.4
Mac OS 11.6
java -v
openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment Homebrew (build 16.0.2+0)
OpenJDK 64-Bit Server VM Homebrew (build 16.0.2+0, mixed mode, sharing)

### Description
On the main ui 
window, choose File > Themes > Flat Darcula
Theme doesn't change.  Infact after Mac OS X none of the menu options appear to do anything.

### Files
<img width="942" alt="Screen Shot 2021-11-01 at 1 11 43 am" src="https://user-images.githubusercontent.com/7206764/139590179-61692dda-ce40-435d-b432-29db5f1cece0.png">

**Comment by Windchild292** [comment]
We do not support Java 16 at this time, our maximum supported version is Java 11.
