### ISSUE TITLE
Contract market incorrectly calculating transport amount as 0 c-bills

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#294]
The second cadre duty contract (the one for Obeedah) in this campaign save has a 100% transport fee clause, but the contract includes 0 c-bills for transport fees, which can't be correct as the transport fee to the planet is roughly 1.2 million c-bills.

Im guessing this is because the planet has two names and MekHQ is looking up the older name which is no longer in use to calculate the transport amount, and since it cant find the planet its generating a transport amount of 0 c-bills.

[test.gz](https://github.com/MegaMek/mekhq/files/679615/test.gz)

**Comment by neoancient** [comment]
The planet lookup routines changed and this was not updated.
