### ISSUE TITLE
Old campaign loads but cannot save. 

### ISSUE THREAD

**Issue by Faolind** [MegaMek/mekhq#2940]
### Environment
MekHQ 0.48.0
Windows 10
JDK 17 x64
An old campaign that loaded properly

### Description
Game cannot save. All I did was re-add missing custom portraits to the personnel. I have retried with no changes and it indeed cannot save. I tried loading a modified version (modified with a .gz addition) and it still cannot save. Since .cpnx cannot be uploaded here I had to upload that modified version (.gz), as well as modify the test save the same way (it creates a scrap file .cpnx that cannot load). This reporting system wont let me add the old custom mechs either, as they are .mtf or .blk
not sure how to fix that so unfortunately this is the best I can do without instruction.

### Files
Provide the .cpnx campaign file that this issue occurs in.
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the megameklog.txt and mekhqlog.txt files for any NPE's or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual megameklog.txt and mekhqlog.txt files
(Delete the above lines)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7481797/mekhqlo
[Haruna_s Harriers30500902 - Copy.cpnx.gz](https://github.com/MegaMek/mekhq/files/7481803/Haruna_s.Harriers30500902.-.Copy.cpnx.gz)
g.txt)
[test.cpnx.gz](https://github.com/MegaMek/mekhq/files/7481827/test.cpnx.gz)

**Comment by Faolind** [comment]
I did a test with another old campaign file that has no customs and that one can be saved.

**Comment by Windchild292** [comment]
JDK 17 is not currently supported. Please downgrade to Java 11
