### ISSUE TITLE
[49.5] Buying several part using the "Buy" button in "Parts in use" only show 1 bought. Visual bug only.

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#2948]
MekHQ 49.5
Win 10

When buying through the "Parts in use" window, if you click several times in the "Buy" button, the parts are added properly in the window, but in the command tab it only shows one.

The parts are procured as normal, and every other window, like the warehouse show the numbers bought/in transit normally. When buying using "Buy in bulk" the number of parts bought show up properly.

**Comment by Windchild292** [comment]
Can we get some visuals to ensure it isn't the same as #1418?

**Comment by JonhyBurner** [comment]
![image](https://user-images.githubusercontent.com/67933202/140674564-c434fd25-602b-4289-9358-cd2bcd708e8e.png)

A very curious discover: resizing the window immediately updates the number to the proper amount.

**Comment by Windchild292** [comment]
Duplicates #1418, with comment to consider the comments here added.
