### ISSUE TITLE
[49.5][StratCon] Deployed "Defend" lance with "Stay Deployed" active can be deployed elsewhere

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#2954]
MekHQ 49.5
Win 10

As the image shows, a Recon lance stumbled upon a scenario, but I can reinforce with a Defend lance that is checked to "Remain deployed", by spending VPs/SPs. If chosen, the lance changes locations, and the points are spent. Probably shouldn't even be on the list to begin with.

![image](https://user-images.githubusercontent.com/67933202/141667934-cb700b14-0669-48f9-b133-d7740e28c4cb.png)

[Lisbon's Ravagers30170121.cpnx.gz](https://github.com/MegaMek/mekhq/files/7533202/Lisbon.s.Ravagers30170121.cpnx.gz)
Logs:
[megameklog.txt](https://github.com/MegaMek/mekhq/files/7533205/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7533206/mekhqlog.txt)

**Comment by NickAragua** [comment]
Thinking about it some more, the Defend lance isn't in the normal "deploy until return date" cycle - it's been sitting there for a while and is probably ready to go, so I think it may be ok for it to be deployable to scenarios on the same track.

**Comment by JonhyBurner** [comment]
That explanation is as good as any other, but the realist in me still finds it odd that a defend lance acting as a garrison for a facility manages to deploy on a hex across the map where a supposedly much nimbler recon lance just stubled upon enemy forces and into an immediate scenario.

But since you can give a slow lance the recon role and a fast lance a defend role, that point is somewhat mute.
