### ISSUE TITLE
[49.5] Bots fail to load in a new MegaMek battle

### ISSUE THREAD

**Issue by HomoLiberatorus** [MegaMek/mekhq#2956]
### Environment
MekHQ 0.49.5
Windows 10
Java 11.0.11

### Description
Basically, the title. Sometimes a specific bot (like a house officer) fails to load, ending up on enemy's side without its units. In this test campaign, however, a bot loads without units AND bots after it do not load at all.
Steps to reproduce:
1. Start a pending battle through MekHQ
2. Wait for the bots to load
3. Continue waiting
4. Look at the Task Manager and see that MegaMek's resource usage has dropped to 0% CPU/RND MB memory/0% Disk
5. (optional) Get disconnected for no obvious reason while waiting

### Files
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7570763/mekhqlog.txt)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/7570765/megameklog.txt)
[My Campaign30670306.zip](https://github.com/MegaMek/mekhq/files/7570766/My.Campaign30670306.zip)

There are no customs. I assumed that a unit with a fully-crewed McKenna fielding company-sized detachments with custom designs might be the cause of that problem. Using a company-sized one deploying a lance confirmed it was not. Regenerating forces didn't help either in earlier testing.

**Comment by kernhe** [comment]
This bug is also valid for 
MekHQ 0.49.3 and .5
OS: Linux
Java: openjdk 11.0.11 2021-04-20

Sometimes it is just enough to simply close megamek and start the battle again. And if this is not working I experienced that if I "Regenerate Bot Forces" the battle will start >90%. (but that is not a real user experience)

**Comment by Windchild292** [comment]
What's your Java RAM assignment for MekHQ and MegaMek?

Please attach the "MegaMek.l4j.ini" and "MekHQ.l4j.ini" files to this.

**Comment by HomoLiberatorus** [comment]
[l4j.zip](https://github.com/MegaMek/mekhq/files/7573792/l4j.zip)
2 GB each. I don't think that's that, Chief.

**Comment by HomoLiberatorus** [comment]
> This bug is also valid for MekHQ 0.49.3 and .5 OS: Linux Java: openjdk 11.0.11 2021-04-20
> 
> Sometimes it is just enough to simply close megamek and start the battle again. And if this is not working I experienced that if I "Regenerate Bot Forces" the battle will start >90%. (but that is not a real user experience)

Actually, I had not encountered that at all for 0.49.3.
Regenerate Bot Forces... doesn't always help in my case.

**Comment by Duuvian** [comment]
In File >MekHQ Options > Miscellaneous Options there is a delay timer you can increase and that might help but I can't be sure.

**Comment by Strycker1776** [comment]
Windows 10
Java 11
Mekhq 49.5

I have the same problem.  Most scenarios I have to manually assign forces to one or more bots.

**Comment by Windchild292** [comment]
I believe this is resolved along with #3063, which will be part of 0.49.7. If they fail to load in 0.49.7, please open a new issue.
