### ISSUE TITLE
[49.5][StratCon] Scenario deployment issues when multiple forces committed

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#2958]
MekHQ 49.5
Win 10

When a "Defend facility" scenario appeared, I deployed 3 forces to the scenario in the "manage scenario" window (using ctrl-click).
![image](https://user-images.githubusercontent.com/67933202/142735596-267925ce-298f-4585-9442-bbf336d8b38d.png)

They appear in the briefing tab like so:
![image](https://user-images.githubusercontent.com/67933202/142735659-e2dbd793-8472-4fad-bc48-3ac2385baba4.png)

I saved the campaign (as usual before a battle).
Starting the scenario only deployed the "Skadi" lance, so I reloaded the campaign save, and the scenario in the briefing tab looked like this:
(Loading the game from scratch has the same results)
![image](https://user-images.githubusercontent.com/67933202/142735766-b397a69a-6dff-488a-a80a-cc064b4fd27c.png)

To note that the loose units there are exactly the ones not loading before.
Starting the scenario loads the units just fine, but individually (as in, with the deployment delay according to the speed of each one, by themselves)

Save with scenario but no deployments:
[Lisbon's Ravagers Pre-Battle.cpnx.gz](https://github.com/MegaMek/mekhq/files/7574928/Lisbon.s.Ravagers.Pre-Battle.cpnx.gz)
[megameklog - before.txt](https://github.com/MegaMek/mekhq/files/7574934/megameklog.-.before.txt)
[mekhqlog - before.txt](https://github.com/MegaMek/mekhq/files/7574935/mekhqlog.-.before.txt)

Save with the deployment done:
[Lisbon's Ravagers BattleDay.cpnx.gz](https://github.com/MegaMek/mekhq/files/7574929/Lisbon.s.Ravagers.BattleDay.cpnx.gz)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/7574936/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7574937/mekhqlog.txt)

**Comment by JonhyBurner** [comment]
After a similar thing happened recently, I believe I found the issue: the disappearing forces were set to non-combat.

Weird by itself, because I don't remember doing that change to the scout lance, but I can't exclude human error from the possibilities.. Feel free to close this if it no longer qualifies as a bug.

**Comment by Windchild292** [comment]
StratCon doesn't support Non Combat forces

**Comment by Windchild292** [comment]
Duplicates #2749
