### ISSUE TITLE
[49.5] java.lang.ClassNotFoundException: mekhq.campaign.personnel.PersonnelOptions Fresh Install

### ISSUE THREAD

**Issue by buzzzz2138** [MegaMek/mekhq#2971]
### Environment
49.5 MekHQ
Windows 10
OpenJDK 11

### Description
Every time someone connect, they get disconnected.  This happens to remote users and localhost users.
Open Campaign.
Briefing tab, select scenario, start scenario.
Open separate megamek instance and try to join. 
The separate window will just hang, while the MekHQ Megamek window show the other window disconnected.
Remote users will see the window for just a instant and then be disconnected. 
Everyone is running 49.5

### Files
Log: (Megamek has the error)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/7592991/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7593001/mekhqlog.txt)

Campaign:
[FireBugs30501004_Testing.cpnx.gz](https://github.com/MegaMek/mekhq/files/7592998/FireBugs30501004_Testing.cpnx.gz)

Custom mechs:
[customs.zip](https://github.com/MegaMek/mekhq/files/7592999/customs.zip)

**Comment by Windchild292** [comment]
Already fixed
