### ISSUE TITLE
StratCon doesn't always hit strategic objectives with Integrated command rights

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#2973]
With 49.5 (and at least as far back as 49.2), missions/contracts with Integrated command rights don't fully make attempts to resolve the strategic objectives for the track.

For example, it may identify two facilities to capture or destroy and a specific engagement.  Though recon cannot specifically be conducted by the player to search for these, they may be revealed through formations with the Scout role deployed in an adjacent strategic hex, or through a friendly Early Warning facility revealing the entire track.  Even though these are notionally important to completing the mission they may not be addressed with specific scenarios before the mission expires, resulting in a mission fail.  This is even more prevalent with low enemy morale which results in low operational tempo/fewer scenarios generated.

I would like to see a little more intelligent behavior for generating scenarios with command rights that prevent the player from selecting deployments.  Where a strategic objective has been identified, it should have a scenario generated in relatively short order.  All identified strategic objectives should be addressed with at least one scenario before the expiration of the contract.  If there has not been at least one attempt at each location-based objective, then the odds of a contract extension should be increased.

**Comment by NickAragua** [comment]
This is actually intended behavior - when you're under integrated command, you're not actually responsible for completing the objective, just for maintaining a positive VP count. I thought I'd put logic in to avoid displaying strategic objectives in the objective area in that case, but I'll need to double check it.

**Comment by SuperStucco** [comment]
From a 49.5 campaign:

![StratCon integrated command objectives](https://user-images.githubusercontent.com/70451747/143519045-6ddf1e78-7ff7-4311-bbc5-9893500064b1.png)

**Comment by NickAragua** [comment]
Yeah, I'll need to adjust that.
