### ISSUE TITLE
MekHQ Nightly CI -- starter(s) for lab missing

### ISSUE THREAD

**Issue by kernhe** [MegaMek/mekhq#2974]
MekHQ Nightly CI (https://github.com/MegaMek/mekhq/actions/runs/1497343503) provides the archive release-win-java11.zip.
It contains "mekhq-0.49.6-SNAPSHOT.zip" where hq, hq.bat, mm-startup, and mm-startup.bat are present. 

Missing: lab and lab.bat

The MegaMekLab.jar is present.

Quick workaround: copy the required starters from previous release (0.49.5)... it works.

**Comment by Windchild292** [comment]
Do not use the workaround, it will cause issues due to the wave of dependency updates that are being done across the suite for 0.49.6.

**Comment by Windchild292** [comment]
This predates the current Gradle changes.
