### ISSUE TITLE
Stratcon deploying invalid units

### ISSUE THREAD

**Issue by Strycker1776** [MegaMek/mekhq#2978]
Mekhq 49.5
Windows 10
Java 11
Stratcon tries to deploy turrets to maps without buildings and blue water naval to maps without water.

**Comment by OrbMonky** [comment]
Have a scenario which generated with a 'specific map' which may be cause of this, even after rerolling the map type and regenerating bot forces it still wants to assign naval units.

Post re-roll/regen file is appended with -1
[Helena's Valkyries30271108.cpnx.gz](https://github.com/MegaMek/mekhq/files/7740409/Helena.s.Valkyries30271108.cpnx.gz)
[Helena's Valkyries30271108-1.cpnx.gz](https://github.com/MegaMek/mekhq/files/7740410/Helena.s.Valkyries30271108-1.cpnx.gz)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/7740412/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7740413/mekhqlog.txt)
[Helena's Valkyries.zip](https://github.com/MegaMek/mekhq/files/7740416/Helena.s.Valkyries.zip)

**Comment by NickAragua** [comment]
There's not really a way to address this, as we don't exactly know what the map will look like until we have entered MegaMek. If a turret or a boat or other unit can't deploy, then it should simply be disregarded for the purposes of the scenario.
