### ISSUE TITLE
Stratcon forcing deployment of non combat force

### ISSUE THREAD

**Issue by Strycker1776** [MegaMek/mekhq#2980]
Windows 10
Java 11
Mekhq 49.5

Stratcon is forcing deployment of force marked as non-combat in the toe to an assassination mission.

I believe these forces should be exempt from missions.
Also, Since the mission doesn't show up on the map, I can't reinforce without going through the toe.  I believe that the toe is supposed to be a last resort.

**Comment by Windchild292** [comment]
Duplicates #2749
