### ISSUE TITLE
0.49.5 Spouse killed in action/widowed personnel log entries are backwards

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/mekhq#2983]
0.49.5
Windows 10
Java version 11.0.13

![unknown](https://user-images.githubusercontent.com/55139229/144158613-83bd8b88-6e21-4428-8421-9566c97ec889.png)
![unknown](https://user-images.githubusercontent.com/55139229/144158617-6884086d-7b39-46bb-a826-1938db59367b.png)

Personnel log entries for spouse widowed and spouse killed in action are reversed.
[Forlorn Hope31060819.cpnx.gz](https://github.com/MegaMek/mekhq/files/7630144/Forlorn.Hope31060819.cpnx.gz)

[fhcustom.zip](https://github.com/MegaMek/mekhq/files/7630149/fhcustom.zip)

**Comment by Windchild292** [comment]
Working as expected, logging will be updated to handle edge cases like this when the base modules are merged.

**Comment by Gribbly1** [comment]
This is working differently to previous versions. The entries are on the wrong person, and this occurs with all fatalities with spouses.

It isn't an edge case - the entry for spouse being killed is appearing on the dead person, not the spouse. There is no corresponding entry on the living partner for their spouse being killed, but the dead partner has an entry indicating their living partner is now dead. 

Wendell was killed. On the day he was killed it states his partner was KIA (non-combatant still alive). Katey does not have the entry for Wendell's death in the log either. MHQ thinks the wrong person was killed, from the perspective of log entries.

**Comment by Gribbly1** [comment]
![image](https://user-images.githubusercontent.com/55139229/144296408-84521b7a-e228-4d81-a867-bc0b42ebe25a.png)

![image](https://user-images.githubusercontent.com/55139229/144296532-04d35954-ada8-4699-be0e-e8e277184fb6.png)

These are similar entries for 0.47.9 - first person is dead, second person living. 0.48 versions seem to have the same bug.

**Comment by Windchild292** [comment]
Reopening due to clarification.
