### ISSUE TITLE
RFE: Time in Service Time in Rank not in Personnel Export

### ISSUE THREAD

**Issue by johnboyjjb** [MegaMek/mekhq#2985]
When Time in Service and Time in Rank were added to MekHQ, the Personnel Export was not updated to include these columns. Not sure how many people use this functionality but since training and rank aren't systemic but user controlled, I would like to use these to coordinate these things, much like the awards spreadsheet that was generated.

**Comment by Windchild292** [comment]
Closing as this will be added by #2864.
