### ISSUE TITLE
Doubled kill counts for vehicle crews

### ISSUE THREAD

**Issue by EvilAtlas** [MegaMek/mekhq#2993]
### Environment
I'm using 0.49.5 on Windows. The Java version is 11.0.13.

### Description
Kill records for vehicle crewmembers since switching to 0.49.5 (which happened around January 1, 3069 in game) are doubled.
![image](https://user-images.githubusercontent.com/94950654/144724097-991fc8f3-355c-4b3c-8d13-cdcb8ecb2232.png)

This has happened for all crew I've looked at so far. Most have been first assigned to their vehicles since switching to 0.49.5 and Stratcon, but a few (including the one in the screenshot) have been assigned since before then. This is likely linked to the crew assignments being doubled in the TO&E, as shown here (and reported as a bug elsewhere):
![image](https://user-images.githubusercontent.com/94950654/144724166-d7259b04-882d-4d82-97a4-37192ccd9a92.png)

### Files
[duplicatekillsbugfiles.zip](https://github.com/MegaMek/mekhq/files/7654673/duplicatekillsbugfiles.zip)

**Comment by OrbMonky** [comment]
[My Campaign30670101.cpnx.zip](https://github.com/MegaMek/mekhq/files/7654794/My.Campaign30670101.cpnx.zip)
[logs.zip](https://github.com/MegaMek/mekhq/files/7654795/logs.zip)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/7654796/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7654797/mekhqlog.txt)

Able to reproduce by having an opponent abandon unit / die to source other than destruction from a unit that is registered in mekhq as part of the mission (created laser carrier in megamek after launching mission, used it to kill wasps, wasps show as killed but no one credited in the end of mission wrap up, assigning kills generated double-credit to the vehicle crew). Was not able to cause this error with standard kills already belonging to the unit.

**Comment by OrbMonky** [comment]
Appears to also affect dropships (or any multi crew entity). Seems to be triggered by assignment bug assigning people as Driver, if you assign a gunner first (ie; no crew on the vehicle) it won't let you assign a driver (except pilots for dropships due to having multiple possible pilots).

**Comment by JonhyBurner** [comment]
Just wanted to add that, in my campaign at least, vehicle drivers get just one kill, while other crewmembers get the double kill, but apparently, the scenario XP is not doubled, just the kill count.
