### ISSUE TITLE
AtB Megamek lobby is unresponsive

### ISSUE THREAD

**Issue by EvilAtlas** [MegaMek/mekhq#3006]
### Environment
I'm using 0.49.5 on Windows. Java version is 11.0.13.

### Description
I launched a convoy defense scenario from MekHQ as part of an AtB campaign. Megamek loads up properly, with all the units and bots apparently loading into the lobby, but while I can get the submenus to open when right-clicking on the units, attempting to load my battle armor onto my omnimech or set up the enemy C3i network has no apparent effect in the main lobby view, though the linking options available in the submenus for the latter do appear to update. In hopes that it was just an interface issue and things were set up correctly, I hit the done button, but the only effect was the button switching to a "not done" button as if I wasn't the only person in the lobby. Clicking the button repeatedly has no effect beyond switching that "ready" status.

![image](https://user-images.githubusercontent.com/94950654/145730843-cd3cda3e-cc1d-4b4b-b222-c1c987e0d509.png)
![image](https://user-images.githubusercontent.com/94950654/145730858-a7095632-c7ff-4500-a637-2457025de7fa.png)

I closed and relaunched the battle repeatedly with no better luck, and neither did restarting MekHQ. I launched a separate battle that I had for the same day, a "Prevent Recon" mission, and that battle worked perfectly. After finishing that battle and saving the game, I once again tried to launch the convoy defense mission, which failed to launch or respond just as it had before.

Opening the edit menu in MekHQ and regenerating the bot forces does fix the issue, allowing the battle armor to be loaded and the mission to be launched. (There was only one C3i unit in the regenerated opposition, but I suspect that would have worked as well.)

### Files
[unresponsivelobby.zip](https://github.com/MegaMek/mekhq/files/7699933/unresponsivelobby.zip)

**Comment by Windchild292** [comment]
I believe this is resolved along with #3063, which will be part of 0.49.7. If this occurs in 0.49.7, please open a new issue.
