### ISSUE TITLE
Quasit variant has wrong era (equipped with MML's but showing up in 3027)

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#3011]
### Environment
Windows 10
49.5
jdk-11.0.11.9-hots

### Description
Quasit variant with MML's showing up in 3027 with tech level limits enabled.

### Files
![image](https://user-images.githubusercontent.com/59293682/146706178-efa582aa-76ac-4d1e-acf5-fdfbaf72ca92.png)
![image](https://user-images.githubusercontent.com/59293682/146706227-c69ad351-c7fb-483d-9b32-617195e9cba1.png)

**Comment by HammerGS** [comment]
The Civilian RAT are not divided by introduction date. Its a known issue that would need an extensive rewrite of those RATs

**Comment by Windchild292** [comment]
Duplicates #1416
