### ISSUE TITLE
After-action MUL file causiong MekHQ to lock up 0.49.5

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/mekhq#3023]
The attached after-action MUL file is causing MekHQ to lock up.  The only way I can get out of it is kill the process.  Log file and MUL file attached.
[After-action MUL file problem.zip](https://github.com/MegaMek/mekhq/files/7776500/After-action.MUL.file.problem.zip)

**Comment by NickAragua** [comment]
Can we also get the campaign save/customs with the relevant scenario pending?

**Comment by BLR-IIC** [comment]
Here's the relevant campaign save file:

[4th Jaguar Dragoons - Clan Smoke Jaguar30220222.cpnx.gz](https://github.com/MegaMek/mekhq/files/7776513/4th.Jaguar.Dragoons.-.Clan.Smoke.Jaguar30220222.cpnx.gz)

**Comment by NickAragua** [comment]
There are about twenty-thirty customs that I don't have, can we supply those as well?

**Comment by BLR-IIC** [comment]
Sure, none of them are a Sentinel as called out in one of the log files, if that's any help:
[4th Jaguar Dragoons Customs.zip](https://github.com/MegaMek/mekhq/files/7776523/4th.Jaguar.Dragoons.Customs.zip)

**Comment by NickAragua** [comment]
![image](https://user-images.githubusercontent.com/29387808/147398299-975bd648-d8a6-4e73-9cac-f47bba12d867.png)

Still a few left. Recognize any of these guys?

**Comment by BLR-IIC** [comment]
Here they are.  Hope this helps!

[Some missing customs.zip](https://github.com/MegaMek/mekhq/files/7776531/Some.missing.customs.zip)
