### ISSUE TITLE
Nightly #622 wont save correctly

### ISSUE THREAD

**Issue by Krrast** [MegaMek/mekhq#3028]
### Environment
MekHQ Nightly #622
Windows
JDK 11

### Description
Just downloaded nightly #622, first time I tried to save it popped up an error and requested a bug report.  I attempted to save multiple times, reloaded and tried to save again after performing different actions, every time the save bugs out. 

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7781981/mekhqlog.txt)
[Black Hand30761003.cpnx.gz](https://github.com/MegaMek/mekhq/files/7781982/Black.Hand30761003.cpnx.gz)

**Comment by Windchild292** [comment]
There's a known issue with that nightly that has been resolved in MHQ Nightly 623.

Also, in future please include all of the logs within the logs folder, as they are required for proper debugging.
