### ISSUE TITLE
[49.6] Campagin-File import fails on Sturmfeur (Standard)

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/mekhq#3039]
Importing a campaign from 49.3 to 49.6 results in an error message. The Sturmfeur (Standard) tank cannot be imported, properly. The issue can be solved if the blk. file is added as custom unit.

**Comment by HammerGS** [comment]
This will require a manual fix to your cons file. 

see here. 
https://github.com/MegaMek/megamek/wiki/Name-Issues-with-Units

**Comment by mwberlindeu** [comment]
Issue manually fixed.
