### ISSUE TITLE
[MekHQ : 0.42.0] Size of Medical Report Card not consistent

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#304]
Medical report card's window size is different for each individual depending on the information in the medical report card. And most of the time, the window size is bigger than my PC screen.

**Comment by BLOODWOLF333** [comment]
Related to #298

**Comment by Windchild292** [comment]
This is identical to #298, and has been resolved with that story (I'm testing on a tiny laptop, the resizing is what was needed)
