### ISSUE TITLE
Nullpointer exception

### ISSUE THREAD

**Issue by kernhe** [MegaMek/mekhq#3062]
### Environment
Version: 0.49.7 Build 636 
OS: Linux 
openjdk 11.0.13 2021-10-19

### Description
Anytime I click on the map in "AtB Campain State" where it is stated "Hostile Force Detected" a dialog pops up: "Uncaught java.lang.NullpointerException detected" 

I think it has to do with the deployment dialog, because it only happens when I click hex tiles with potential battles. Any empty hex tile can be clicked without an issue.

### Files
[mekhq.log](https://github.com/MegaMek/mekhq/files/7857248/mekhq.log)

Edit: buildnumber was interpreted as an issue, because I wrote #+number

**Comment by Windchild292** [comment]
We'll need the campaign files and customs to debug this, and please include all of the logs, not just the one.

**Comment by kernhe** [comment]
OK, no problem. What do you mean by customs?

**Comment by kernhe** [comment]
### Additional Logs
[entitystatus.txt](https://github.com/MegaMek/mekhq/files/7857381/entitystatus.txt)
[legacy.log](https://github.com/MegaMek/mekhq/files/7857382/legacy.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/7857383/megamek.log)
[megameklab.log](https://github.com/MegaMek/mekhq/files/7857384/megameklab.log)

**Comment by Windchild292** [comment]
Primarily mechfiles/customs, but also any custom awards setups and other custom user data.

**Comment by kernhe** [comment]
For the current campain it would be quite a task to provide all the custom mechs, because the whole unit consists of "Franken-Mechs" as we were stranded on Butte Hole with no valid spare parts.

So I tried to set up a "Debug Commando" with just 4 mechs.

NullpointerExceptions happen -- but I always can continue:

(1) when I "Add New Force" in T&OE  

(2) when I add a unit in the T&OE

(3) when I assign a Tech to my unit in T&OE

(3) when I load this campaign, I'll also get the Nullpointer Exception

(4) when I activate the StratCon in the config and I'll close the Option window

(5) when I add an injury...




Attached you'll find all logs and saves for this Debug Commando. That's all you'll need, because there are only standard units. 

### Logs
[entitystatus.txt](https://github.com/MegaMek/mekhq/files/7857522/entitystatus.txt)
[legacy.log](https://github.com/MegaMek/mekhq/files/7857523/legacy.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/7857524/megamek.log)
[megameklab.log](https://github.com/MegaMek/mekhq/files/7857525/megameklab.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/7857526/mekhq.log)

### "Campaign"
[Debuggers30470114.cpnx.gz](https://github.com/MegaMek/mekhq/files/7857528/Debuggers30470114.cpnx.gz)



### General
Version: 0.49.7 Build 636
OS: Linux x86_64
openjdk 11.0.13 2021-10-19

**Comment by Windchild292** [comment]
That works, but you can just zip the mechfiles/customs folder in future to prevent having to create a new campaign each time and for scenarios that don't recreate in all cases.
