### ISSUE TITLE
StratCom AtB deploys Mech from future 

### ISSUE THREAD

**Issue by kernhe** [MegaMek/mekhq#3064]
### Environment
0.49.7 Build 636 

### Description
I had this once in the past with 0.49.3 and thought it was just a glitch, but now it happens again. It's November 3047 and the bot (Chainelaine Isles) uses again a Quasit MilitiaMech (QUA-51P) with a Plasma Rifle. In the database you'll find for that configuration the availability in the year 3074.

**Comment by HammerGS** [comment]
Known issue with civilian RATs.

**Comment by kernhe** [comment]
Thanks!
