### ISSUE TITLE
Early Years RAT Gen creates No Opfor but RATs create placeholder Opfor

### ISSUE THREAD

**Issue by johnboyjjb** [MegaMek/mekhq#3072]
### Environment
0.49.6
Windows 10
Whatever Java you guys linked to. MekHQlog.txt no longer contains version info (or I'm blind)

### Description
I'm used to generating my own opfor because I'm "special" playing in 2433. When I have generate from RATs turned on and "Allow later RATs" things generally work fine. The units aren't right for era but it works.

When I have generate from RATs turned on and uncheck "Allow later RATs" I get bots generated with no units. This also works but can make reconciling the battle and scoring victory points difficult without modify the save file (which I don't like doing)
![image](https://user-images.githubusercontent.com/75278541/149707534-c27574da-0abd-47d1-9f1c-6336792c576f.png)

When I have generate from RAT Generator turned on I get no OpFor.
![image](https://user-images.githubusercontent.com/75278541/149707818-6a06ec4c-624d-44c7-b110-44c91fc7e361.png)

I won't go into the fact that all 3 of my scenarios are in "pitch black" which seems to roll up way more often than the tables dictate.

I can upload files as necessary but I virtually no tinkering on your own will allow replication.

**Comment by johnboyjjb** [comment]
I prefer leaving RAT Generator turned on because the Unit Market repopulates with the RAT Generator but with the RAT tables I get an empty unit market and I get the weird date at the bottom of the Daily Activity Log that has otherwise been fixed quite nicely.

**Comment by Windchild292** [comment]
As per the details this requires the campaign file, any customs, and all logs. In 0.49.6 they are now named MegaMek.log, MegaMekLab.log, MekHQ.log, and Legacy.log. I'm not sure if all of the old *text.log ones were removed at that point or have been since then.

**Comment by johnboyjjb** [comment]
[entitystatus.txt](https://github.com/MegaMek/mekhq/files/7883722/entitystatus.txt)
[megamek.log](https://github.com/MegaMek/mekhq/files/7883723/megamek.log)
[megameklab.log](https://github.com/MegaMek/mekhq/files/7883724/megameklab.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/7883725/mek
[customs.zip](https://github.com/MegaMek/mekhq/files/7883745/customs.zip)
hq.log)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7883726/mekhqlog.txt)
[BS Concepts.cpnx.gz](https://github.com/MegaMek/mekhq/files/7883729/BS.Concepts.cpnx.gz)

**Comment by Windchild292** [comment]
Resolved in [this commit](https://github.com/MegaMek/megamek/commit/47bca7fa97d7d6ba105796d60f4756a7bc510d72)
