### ISSUE TITLE
[0.49.7 644] Uncaught java.lang.InternalError

### ISSUE THREAD

**Issue by kernhe** [MegaMek/mekhq#3076]
### Environment
V: 0.49.7 build 644
OS: linux 
Java: openjdk 11.0.13 2021-10-19
[Debuggers30470114_Injury.cpnx.gz](https://github.com/MegaMek/mekhq/files/7890644/Debuggers30470114_Injury.cpnx.gz)

### Description
A dialog informing me about an uncaught java.lang.InternalException will pop up when you examine an injured person.
- Advanced Medical rules on (!)

Steps to reproduce in attached save file:
1) go personal tab
2) select corporal David Rousseaux 
3) click the green cross in injury report
4) window will pop up with that shows the injury report together with uncaught  java.lang.InternalError
.... 4 will repeat anytime you move the cursor into the injury report window. You can close the window with Done button and continue game.

### Files
[Debuggers30470114_Injury.cpnx.gz](https://github.com/MegaMek/mekhq/files/7892123/Debuggers30470114_Injury.cpnx.gz)
[entitystatus.txt](https://github.com/MegaMek/mekhq/files/7892125/entitystatus.txt)
[legacy.log](https://github.com/MegaMek/mekhq/files/7892127/legacy.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/7892128/megamek.log)
[megameklab.log](https://github.com/MegaMek/mekhq/files/7892129/megameklab.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/7892130/mekhq.log)

**Comment by Windchild292** [comment]
Can you please attach your MekHQ.l4j.ini file? It's potentially related to the values in that file.

**Comment by Windchild292** [comment]
Ignore the above, missed that this is for Linux.

There's an open JDK bug for this issue, and I'll see what I can do for a workaround.
https://bugs.openjdk.java.net/browse/JDK-6689349

**Comment by kernhe** [comment]
Sorry, didn't know this is a general issue.

**Comment by Windchild292** [comment]
We still need to handle it internally, with a workaround if possible.

I've got a fix that should work, but can you please try https://github.com/MegaMek/mekhq/pull/3078 out and ensure it does (I don't have Linux access to test the fix).

**Comment by Windchild292** [comment]
(releases for that fix are located at https://github.com/MegaMek/mekhq/actions/runs/1719057020)

**Comment by kernhe** [comment]
Just checked ... and let's start with the positive information: mml-starter for lab works fine :-)

Sad news: now the injury use case generates Uncaught.java.lang.InternalError and Uncaught.java.lang.StackOverflowErrors ... in an endless loop, so I have to kill HQ.
But I have some huge logs for you:

* [megameklab.log](https://github.com/MegaMek/mekhq/files/7899734/megameklab.log)
* [megamek.log](https://github.com/MegaMek/mekhq/files/7899735/megamek.log)
* [legacy.log](https://github.com/MegaMek/mekhq/files/7899736/legacy.log)
* [mekhq.log](https://github.com/MegaMek/mekhq/files/7899732/mekhq.log)

**Comment by Windchild292** [comment]
I was catching the wrong type of throwable, so it shouldn't have done anything different than before...
But here's version 2, hopefully working a lot better: https://github.com/MegaMek/mekhq/actions/runs/1719862120

**Comment by kernhe** [comment]
OK, the whole folder mechfiles were missing in this build, but I was to deal with this.

Result: Great work! no more exceptions popping up.

**Comment by kernhe** [comment]
did a second test, everything is fine. 
Will close the issue now.

**Comment by Windchild292** [comment]
Please leave the issue open until the fix is merged.
