### ISSUE TITLE
0.49.7 build 647 -- files/folders missing

### ISSUE THREAD

**Issue by kernhe** [MegaMek/mekhq#3083]
In the (non-windows) archive mekhq-0.49.7-SNAPSHOT.zip the following folders are missing:

* data/boards
* data/forcegenerator
* data/mapsetup
* data/mechfiles
* data/rat
* data/scenarios
* data/sounds

Files missing: 
* data/canonUnitQuirks.xml
* data/unitQuirksSchema.xsd
* data/unit_roles.txt

* mmconf/keyBindingSchema.xsl
* mmconf/unitQuirksOverride.xml

**Comment by kernhe** [comment]
Update: with the latest snapshot 049.9-686 everything is fine again.

I think you can close this bug, and if anything strange will happen again, I will report it ASAP.

**Comment by Windchild292** [comment]
Closing as fixed... without making any changes....
