### ISSUE TITLE
Colored Units From MM Does Not Apply To HQ

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/mekhq#309]
![image](https://cloud.githubusercontent.com/assets/16950832/21965023/d6c233da-db1c-11e6-9f1e-25c12aff92b5.png)

Low priority, just a heads-up that the colored/royal-units feature we have in MM doesnt apply to HQ in the TO&E or in the hangar.  Obviously the images I have are different from everyone else's so, what would I need to provide for this bug report if anything? 0.42.0 (kipsta's custom .exe for the new MRS)

**Comment by Dylan-M** [comment]
Not sure what you're talking about, because they're very clearly working in the screenshot you've got above. None of the ones you're showing have anything special done to the icons, except the blurring shadow effect. I can see that effect. It definitely uses the same icons as MegaMek, so long as it's packaged properly. I can't speak for Kipsta's custom releases. You're on your own if something is missing there.

**Comment by kipstafoo** [comment]
Mine was simply an .exe ... what BW did with it after I gave delivered it, well, I can't say. :)

**Comment by BLOODWOLF333** [comment]
I will move kipsta's .exe out and put the stock one back in to make sure but, i made color units that includes all four of those mechs in the screen shot so, those enforcers should have red cockpits/eyes and a grey AC barrel in the RA, it also doesnt show the red cockpit and grey LL barrel on my marauder but, I will re-test with he stock HQ.exe and then post the cpnx, customs, and colored units if this applies to both versions.
Before I did the enforcers but what the grasshopper and warhammer should be looking like:
![image](https://cloud.githubusercontent.com/assets/16950832/21986225/3c3a5150-dbc4-11e6-8151-76a6621fdce1.png)

**Comment by BLOODWOLF333** [comment]
Ok with the stock 0.42.0 HQ application same result.  The colored units feature does not apply inside the HQ program.
![github](https://cloud.githubusercontent.com/assets/16950832/22007325/6038ce7e-dc37-11e6-9b8c-37db5b5c764f.png)
![github0](https://cloud.githubusercontent.com/assets/16950832/22007326/603b516c-dc37-11e6-846b-d23ca12c42ff.png)

CPNX and colored units
[HQColoredUnits.zip](https://github.com/MegaMek/mekhq/files/709977/HQColoredUnits.zip)

**Comment by HammerGS** [comment]
What you see in the screen shot is the units with the camo applied. Whats missing is the coloring from the Royal Units.  The color cockpits, missile launchers, etc

**Comment by Windchild292** [comment]
This was either fixed when I standardizing entity image between MegaMek and MekHQ or before then.
