### ISSUE TITLE
[0.49.7-SNAPHOT] Starting New Campaign from the File Menu breaks Daily Activity Log

### ISSUE THREAD

**Issue by HeckfyEx** [MegaMek/mekhq#3095]
### Environment
0.49.7-SNAPHOT
Windows 10
Java Vendor: AdoptOpenJDK
Java Version: 11.0.11 

### Description
Starting New Campaign from File Menu stops Daily Activity Log from reporting changes to the company, while some system messages do appear e.g. mass repair/salvage or notice that there's no one to procure equipment.

**Comment by Windchild292** [comment]
I believe this has to do with how we recreate the panel, and thus I'll likely handle this alongside #3081.

My current plan is to make it a single panel for all uses. If that doesn't work, then I'll look at isolating MHQ's daily reports into their own class.

**Comment by Windchild292** [comment]
Subsumed by #3149
