### ISSUE TITLE
[0.49.7] Umlauts in Medical Details

### ISSUE THREAD

**Issue by kernhe** [MegaMek/mekhq#3097]
### Environment
V: 0.49.7 - 654
OS: linux
Java: openjdk 11.0.13 2021-10-19

### Campaign Options
+ Personal: Medical >> Use Advanced Medical Rules (Unofficial, but I like 'em)

### Description
As shown in attached image, the medical details window does not show any umlauts (äöü).
![Umlauts](https://user-images.githubusercontent.com/1056746/151535672-08542653-f70e-4d69-8a6b-ecd43c5971d1.png)

How to reproduce:
* Change your rank system to "KungsArme" (Rasalhague), there you have the rank of Löjtnant (with o umlaut) and then go to personal tab > Injury Report

Additional question: can we change the font in this report? Words ending with a letter that end with y or g do not look nice, because the letter is a bit truncated on the right open side.

**Comment by kernhe** [comment]
OK, I did my homework and figured out that the problem is the font itself. 

data/fonts/angelina.TTF is used for the Injury Report and the font does not provide any umlauts at all.

Suggestion: just use the default font

**Comment by kernhe** [comment]
Quick fix: rename or remove data/fonts/angelina.TTF ... then the Injury Report will use the default font.

**Comment by Windchild292** [comment]
I've opened up https://github.com/MegaMek/megamek/pull/3428 to create FontComboBox, a new component needed for font selection.

I've also opened https://github.com/MegaMek/megamek/pull/3427, https://github.com/MegaMek/megameklab/pull/1024, and https://github.com/MegaMek/mekhq/pull/3107, the primary enhancement in them being a far better Font loading setup.

Once the four PRs are merged I'll be able to proceed in making the font an option selectable in MHQ Options.

**Comment by kernhe** [comment]
Looking forward to test it! (Really, no sarcasm)
