### ISSUE TITLE
3.25 : NPE when advancing a day

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#31]
Last thing i did was start repairing damaged equipment in the warheouse (a lot of them) before advancing a day, and i got a NPE.

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException

Save game is attached.
[#battletech.zip](https://github.com/MegaMek/mekhq/files/182376/battletech.zip)

**Comment by Akjosch** [comment]
You assigned Cpt. Travis Riviera (who has like no tech skills, at all) to work on repairing an AMS.

I'm not sure if that assignment should be made *totally* impossible (yes, it will always fail, but you could still gain XP from it I guess, while burning through equipment), but the code certainly needs a guard there, just in case.

**Comment by arlith** [comment]
I don't think the UI is supposed to allow people without the proper skill to be assigned to a repair job.  There's potentially a bug in how this assignment was allowed.  (I'm not super familiar with MHQ code, so I may be wrong).

**Comment by Dylan-M** [comment]
@arlith No, you are correct. An assignment should not be allowed unless the person has the proper tech skills.

**Comment by Question2** [comment]
Hmm, in the warehouse, i was simply clicking the "do task" button without checking which tech was going to be assigned (since i pretty much have all elite techs anyway). I guess at some point Cpt Travis Riviera (a vessel gunner) got selected. Not sure why he would show in the list of techs for the warehouse though, if hes a vessel gunner.

**Comment by arlith** [comment]
I think that, for large craft, the crew performs repairs/maintenance.  That may be how this came about, I dunno if the code around repairing/maintaining large craft is fully implemented.

**Comment by Dylan-M** [comment]
Not quite, there is an "Engineer" for vessels.

**Comment by Akjosch** [comment]
Manually removing the repair job from the cpnx file allows the day to advance normally and without any errors in log.

This doesn't fix the issue; it just lets Question2 play the game.

[battletech.zip](https://github.com/MegaMek/mekhq/files/182449/battletech.zip)

**Comment by Question2** [comment]
Thanks for the help!

**Comment by Akjosch** [comment]
So ... try as I might, I still didn't manage to replicate the behaviour. Anybody has any more luck?

At best, we can add some extra checks to make sure nobody with no tech skills gets assigned and that a day gets passed (with an automatic failure) if a broken save game includes such.

**Comment by Dylan-M** [comment]
If we add such extra checks, I'd rather that on campaign loading that person got un-assigned from the repair. Or if it's difficult on loading, then on the advance day checks for repairs.

As for how this can happen? It's easy: Have a tech skill on someone, assign them to a repair, and then remove the tech skill from them. Whups!

**Comment by Akjosch** [comment]
Well, a fix-at-load-time check won't help us with people messing up their game state by abusing the GM tools ...

**Comment by Akjosch** [comment]
Added an NPE guard in `newDay()` and a report line stating that the non-tech was removed from repairing the part.
