### ISSUE TITLE
Graphical malfunction

### ISSUE THREAD

**Issue by arrahnuuk** [MegaMek/mekhq#310]
Every instance of MekHQ and megamek seem to create this problem with graphics.
![mekhq and mega](https://cloud.githubusercontent.com/assets/7980477/21969800/32f59da4-db5e-11e6-9998-131d9d1eab24.png)
The graphics bug out each time the cursor mouses over a button, the whole screen seems to reset using that button as the upper left edge of the screen. Each resize of the window momentarilly fixes the problem until the next glitch. 
This is happening on a windows 10 64 bit computer with a 1070 using the latest driver from evga, and java 8 u112.

**Comment by BLOODWOLF333** [comment]
Create a new folder on your desktop, paste into it your cpnx file, log files, and any custom units your campaign file uses, and then zip/archive it and upload here so they can diagnose the bug please.

**Comment by arrahnuuk** [comment]
Its a problem with the whole package, it happens in megamek as well without using mekhq at all.
 I downloaded a new zip, put it into a new separate folder, then started megamek without adding anything in, and the following happened after using the create random army.
![newglitch](https://cloud.githubusercontent.com/assets/7980477/22008231/8024b8d4-dc36-11e6-963c-bac48618f2d7.png)
The same problem happens in mekhq, on a clean install before even starting a campaign, while I am selecting rules. I've already tried different java versions, as well as driver updates.

**Comment by HammerGS** [comment]
We had people report similar issues based on their video card.  In particular the Radeon Cards, their is a program installed outside the drivers that causes this issue.  I believe its called Radeon Pro.

That said people have also comment on seeing the same thing with NVIDIA cards that have been paired with Intel graphics cards.  

The solution in both bases has been to disable the programs interfering with the display.

**Comment by arrahnuuk** [comment]
I removed both the nvidia gaming experience and some msi bloat that came with the motherboard. Not sure which one did it, but with the removal of those programs the problem has been resolved. Thanks so much.

**Comment by HammerGS** [comment]
Glad its working. I have an NVIDIA card and the Geforce Experience has never impacted the programs.  But I have had issues as well with my new laptop (which is a MSI one).

**Comment by HammerGS** [comment]
While this is closed, anyone that finds it refer to wiki entry about 1/2 way down. 
https://github.com/MegaMek/megamek/wiki/Known-Issues-and-Workarounds
