### ISSUE TITLE
49.7-SNAPSHOT Contract Completion Retirement Uncaught ConMod

### ISSUE THREAD

**Issue by SnyderPhilip** [MegaMek/mekhq#3102]
### Environment
49.7-SNAPSHOT (Nightly MekHQ CI with Gradle #1926) Windows 10

### Description
Attempting to complete a contract in the currently nightly build, brings a Uncaught Exception that prevents the contract from completing.  It makes the retirement/defection roll, and but does not complete the contract.  It is not extending the contract due to an emergency clause, that aspect works normally, and correctly.  (although I wonder about extending the contract on a raid where you've met the early completion criteria)
[mekhq.log](https://github.com/MegaMek/mekhq/files/7981491/mekhq.log)
[Lone Star Regulars.zip](https://github.com/MegaMek/mekhq/files/7981510/Lone.Star.Regulars.zip)

**Comment by Windchild292** [comment]
Can I please get the rest of the log files

**Comment by SnyderPhilip** [comment]
I can't think of any other one that you need but, here's the MegaMek log.
[megamek.log](https://github.com/MegaMek/mekhq/files/7981539/megamek.log)
[megameklab.log](https://github.com/MegaMek/mekhq/files/7981547/megameklab.log)
.
