### ISSUE TITLE
0.49.7-SNAPSHOT - Selecting "Only Generate OmniMechs" in Company Generator Gives Less Mechs Than Expected

### ISSUE THREAD

**Issue by stonewall072** [MegaMek/mekhq#3112]
0.49.7-SNAPSHOT
Windows 10
Java Version: 17

Using the company generator, and turning "Starting Simulation" off, if "Only Generate OmniMechs" is selected, the force does not get filled out completely. For example: I ask it to generate a company -> three lances -> four mechs per lance, but only end up with 9 mechs. Personnel is generated correctly, but they do not get units.  In two instances of testing, only a single mech was generated.

If this option isn't selected, a full 12 mechs are generated consistently.

**Comment by Windchild292** [comment]
This is expected behaviour. The tooltip for the "Only Generate OmniMechs" option explains this.

```Only allow OmniMechs to be generated.
General / Inner Sphere Faction: This option may lead to gaps in the force, as the Star League didn't have OmniMechs and OmniMech availability varies heavily even after their Inner Sphere introduction.
Clan Faction: This option may lead to gaps in the force unless the following steps are taken. First, ensure that year is 2876 or later. Second, enable the Only Generate Star League 'Mechs option as that will force generation to a minimum of Clan Frontline BattleMechs.
```

Also, immediately downgrade your Java to Java 11 or you will have issues going forward.
