### ISSUE TITLE
Game opens itself into the MekHQ window through every window.

### ISSUE THREAD

**Issue by AttackHelicopter6784** [MegaMek/mekhq#3120]
48.0

Windows

I cannot find the version in the log, but I just now installed whatever version of Java it asked me to install.

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/62526666/154365205-b9a7813b-98b9-454a-a4f0-f6f47a1e5a44.png">

I add starting financials, open purchase unit, and then purchase some units, and then suddenly the UI disintegrates. This also happens at complete random when just looking through menus. This issue makes the game totally unplayable.

[My Campaign30670101.cpnx.gz](https://github.com/MegaMek/mekhq/files/8083905/My.Campaign30670101.cpnx.gz)

And provide the megameklog.txt and mekhqlog.txt files for any NPE's or errors that MekHQ might be reporting.
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/8083910/mekhqlog.txt)

**Comment by HammerGS** [comment]
Try this - 
https://github.com/MegaMek/megamek/wiki/Known-Issues-and-Workarounds#weird-artifactsscreen-distortions

**Comment by AttackHelicopter6784** [comment]
> Try this - https://github.com/MegaMek/megamek/wiki/Known-Issues-and-Workarounds#weird-artifactsscreen-distortions

Game is working now, willl post again if it stops working. Thanks.
