### ISSUE TITLE
[49.7] Installing the given version of Java is not working

### ISSUE THREAD

**Issue by AttackHelicopter6784** [MegaMek/mekhq#3126]
### Environment
49.7
Windows
I'm downloading the one that appears from the message telling me to install java.

### Description
I am unable to open the game, and it's telling me that I need java version 11.0.0. It then opens a Java page, and I install Java from the opened page, but it doesn't change anything.

### Files
I cannot even launch the game.

No logs have been made.

**Comment by HammerGS** [comment]
Please use these directions. We have no control of the pop up. 

https://github.com/MegaMek/megamek/wiki/Updating-to-Adoptium

**Comment by AttackHelicopter6784** [comment]
> Please use these directions. We have no control of the pop up.
> 
> https://github.com/MegaMek/megamek/wiki/Updating-to-Adoptium

Thanks, doing it now, will close the issue if this fixes it.
