### ISSUE TITLE
Prisoners counting towards combatants total for defection rolls.

### ISSUE THREAD

**Issue by hodlum** [MegaMek/mekhq#313]
Tested on version 0.42.0

**Comment by scJazz2** [comment]
Can you attach a Campaign Save (and any Customs required to load it) that can be used for testing?

**Comment by hodlum** [comment]
sorry, bad click on file load.

**Comment by hodlum** [comment]
[Voidborn Vagabonds30291108 - Copy.txt](https://github.com/MegaMek/mekhq/files/717387/Voidborn.Vagabonds30291108.-.Copy.txt)

**Comment by hodlum** [comment]
did some small testing. removing prisoners so that pilots + warriors + prisoners = 24 removes leadership penalties during roll.

commander leadership is currently 2.
