### ISSUE TITLE
Unable to load campaign save

### ISSUE THREAD

**Issue by TheCloptologist** [MegaMek/mekhq#3130]
### Environment
49.7
Windows 10
Java Version 11.0.14.1

### Description
Upon trying to load a save game. The save game will not lead and produces an error.
![javaw_XOikwEX1hd](https://user-images.githubusercontent.com/9296835/155033387-5951f8eb-2940-43a3-9efc-06d71bbdbd44.png)

I was able to load a save from earlier, but when I try to save and load my last good save. I receive the error. 

I did notice in the mekhq.log file, this line. "Caused by: org.xml.sax.SAXParseException; lineNumber: 11182; columnNumber: 4; The element type "unitOrder" must be terminated by the matching end-tag "</unitOrder>".

### Files
 Corrupted Save file: [Uber Weapons Unlimited30270326.cpnx.gz](https://github.com/MegaMek/mekhq/files/8112383/Uber.Weapons.Unlimited30270326.cpnx.gz)

Last good save:  [Uber Weapons Unlimited30270319.cpnx.gz](https://github.com/MegaMek/mekhq/files/8112387/Uber.Weapons.Unlimited30270319.cpnx.gz)

[megamek.log](https://github.com/MegaMek/mekhq/files/8112377/megamek.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/8112378/mekhq.log)

**Comment by Windchild292** [comment]
Fix PR is open, and I've attached the corrected save file. Sorry for the inconvenience, it's a copy/paste bug on my end.
[Uber.Weapons.Unlimited30270326.cpnx.gz](https://github.com/MegaMek/mekhq/files/8112484/Uber.Weapons.Unlimited30270326.cpnx.gz)
