### ISSUE TITLE
0.49.7 - StratCon scenario fails to load properly in MegaMek

### ISSUE THREAD

**Issue by Pinetree74** [MegaMek/mekhq#3135]
### Environment
0.49.7
Windows 10
Java Vendor: AdoptOpenJDK
Java Version: 11.0.9.1

### Description
When I tried to start a Stratcon- generated scenario it initially loaded with my units and a Liaison Officer Bot but no Liaison Officer unit and without an OpFor. After about 10 minutes the opfor would load but the Liaison officer unit would still be blank. The LO bot is also set to the wrong team. I've tested this twice and is reproducible. 

![image](https://user-images.githubusercontent.com/100340781/155486414-bb97050e-6b77-4689-9d82-5b5bb8e07783.png)

![image](https://user-images.githubusercontent.com/100340781/155486269-3b76d632-a4e0-4fc2-8844-62709d8c4812.png)

Campaign is pretty vanilla, Unit was generated with the Company generator and there are no customs. Logs, MekHQ & MegaMek saves attached.

### Files

[logs.zip](https://github.com/MegaMek/mekhq/files/8130850/logs.zip)
[Stratcon-error.sav.gz](https://github.com/MegaMek/mekhq/files/8130853/Stratcon-error.sav.gz)
[Freyberg's Circus30350328.cpnx.gz](https://github.com/MegaMek/mekhq/files/8130855/Freyberg.s.Circus30350328.cpnx.gz)

**Comment by repligator** [comment]
Loads fine under latest nightly. Closing.
