### ISSUE TITLE
49.7 Null pointer when trying to assign a pilot with an existing mek to a new mek

### ISSUE THREAD

**Issue by pakfront** [MegaMek/mekhq#3138]
### Environment
mekhq.MekHQ.initializeLogging(MekHQ.java:290) - Starting MekHQ v0.49.7
	Release Date: 2022-02-18
	Today: 2022-02-24
	Origin Project: MekHQ
	Java Vendor: AdoptOpenJDK
	Java Version: 11.0.10
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 2 GB

### Description
New feature allows assigning a pilot of an existing mek to another mek, but that consistently causes a null pointer exception.
In this case, try assigning any pilot with an existing mek the unassigned Wolverine.

### Files
[mekhq.log](https://github.com/MegaMek/mekhq/files/8137932/mekhq.log)
[Vigo's Venture30350225.cpnx.gz](https://github.com/MegaMek/mekhq/files/8137936/Vigo.s.Venture30350225.cpnx.gz)

**Comment by Windchild292** [comment]
Subsumed by #3146 (didn't notice this was the same originally)
