### ISSUE TITLE
Unable to load MekHQ campaign save - unitOrder element

### ISSUE THREAD

**Issue by EmeraldRogue** [MegaMek/mekhq#3139]
### Environment
MekHQ 49.7
Platform: Windows 10 10.0 (amd64)
Java Version: 11.0.13

### Description
On trying to load a save game, the save game does not load and produces an error:

![image](https://user-images.githubusercontent.com/100393482/155641648-e0a00d54-d6c3-4f59-8026-10bff01a4c4f.png)

I was able to load this save successfully earlier today, but now I get the error message every time I try to load the save file. Spotted the following error in the MekHQ log file:

21:19:22,082 ERROR [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-2-thread-2}
mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:107) - 
org.xml.sax.SAXParseException; lineNumber: 11280; columnNumber: 4; The element type "unitOrder" must be terminated by the matching end-tag "</unitOrder>".

### Files

[The Capellan Wolves30370521.cpnx.gz](https://github.com/MegaMek/mekhq/files/8137947/The.Capellan.Wolves30370521.cpnx.gz)
[mekhq.log](https://github.com/MegaMek/mekhq/files/8137948/mekhq.log)

**Comment by HammerGS** [comment]
One of the players on Discord has this as a workaround 

Using a good text editor like Notepad++

If anyone has the same issue, and until the nightlies work again, unzip the save file, find instances of "<unitOrder>" and on the block ending, instead of another "<unitOrder>", put "</unitOrder>" and the save should load again
 So it would be 
<unitOrder>
something
</unitOrder>

Make sure to keep a backup of your save.

**Comment by EmeraldRogue** [comment]
Thanks, I was able to edit the save and get it working again as a workaround for whatever happened in the first place.

**Comment by Windchild292** [comment]
This is fixed in latest develop, but I'm leaving this open with the following workaround from @HammerGS and our Discord:
```
Using a good text editor like Notepad++

If anyone has the same issue, and until the nightlies work again, unzip the save file, find instances of <unitOrder> and on the block ending, instead of another <unitOrder>, put </unitOrder> and the save should load again
So it would be
<unitOrder>
something
</unitOrder>

Make sure to keep a backup of your save.
```

**Comment by Windchild292** [comment]
Resolved in latest - closing given no further comments
