### ISSUE TITLE
[0.49.7 : Bug] NPE When Assigning Crews

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#3146]
### Environment
0.49.7 MekHQ

### Description
NPE When Assigning Crews

Many units (or all) affected. Example:
- Load campaign
- Go to TO&E
- Go to 511st Airborne
- Go to existing VTOL pilot
- Assign 1 pilot to another empty VTOL (Crew 0/5)
- Error pop up and the VTOL suddenly have Crew 2/5 (the pilot takes 2 crew slots if you look from the TO&E)
- Cannot transfer crew to another vehicle properly.....

### Files
[Customs - SirMegaV - Mechfiles.zip](https://github.com/MegaMek/mekhq/files/8152082/Customs.-.SirMegaV.-.Mechfiles.zip)
[NPE_When_Assigning_Crews_mekhq.log](https://github.com/MegaMek/mekhq/files/8152083/NPE_When_Assigning_Crews_mekhq.log)
[NPE_When_Assigning_Crews_SirMegaV25110413-6.cpnx.gz](https://github.com/MegaMek/mekhq/files/8152084/NPE_When_Assigning_Crews_SirMegaV25110413-6.cpnx.gz)

**Comment by Windchild292** [comment]
```
17:09:53,458 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$0(MekHQ.java:269) - Uncaught Exception Detected
java.lang.NullPointerException
	at mekhq.campaign.Campaign.getForceFor(Campaign.java:3763)
	at mekhq.campaign.unit.Unit.addPilotOrSoldier(Unit.java:4306)
	at mekhq.campaign.unit.Unit.addPilotOrSoldier(Unit.java:4289)
	at mekhq.gui.menus.AssignPersonToUnitMenu.lambda$initialize$15(AssignPersonToUnitMenu.java:253)
```
