### ISSUE TITLE
Unable To Open MegaMek, MegaMekLab, or MekHQ .exe files.

### ISSUE THREAD

**Issue by Energo17** [MegaMek/mekhq#3164]
### Environment
Version: 0.48.0
OS: Windows
Java: 1.8.0_321

### Description
Dowloaded the MekHQ files from https://megamek.org/downloads.html, and extracting them (I've done this twice before and the game worked fine).
Created shortcuts for MegaMek, MegaMekLab, and MekHQ, and put them on the desktop.
Clicked on the icons to run the programs and nothing happened. None of the 3 run from the shortcut or original .exe files, and don't run whether or not I use administrator privileges.

Note: I am running Bitdefender as my anti-virus.

### Files
No files are available for this issue I'm afraid. No logs have been created.

**Comment by Windchild292** [comment]
What directory are you trying to launch from? Would it happen to be either downloads or program files?

Also, did you use the broker Windows zipper or a working zipper like 7-zip to do the extraction?

**Comment by Windchild292** [comment]
This has been resolved. It was the antivirus making downloads into a protected folder.

**Comment by Energo17** [comment]
Thanks for the reply. I managed to figure it out.
