### ISSUE TITLE
[0.49.7] NPE when assigning pilot to a mech

### ISSUE THREAD

**Issue by mjbroekman** [MegaMek/mekhq#3169]
### Environment
	Release Date: 2022-02-18
	Today: 2022-03-13
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.13
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 8 GB

### Description
When assigning a pilot to a mech that is not in the TOE, a Null Pointer Exception is thrown.

In the provided campaign, for example, assigning Mechwarrior Ruth Klimkowski to another mek will throw an NPE.

### Files
[mekhq.log](https://github.com/MegaMek/mekhq/files/8240651/mekhq.log)
[Star League Reborn30140825.cpnx.gz](https://github.com/MegaMek/mekhq/files/8240652/Star.League.Reborn30140825.cpnx.gz)
[customs.zip](https://github.com/MegaMek/mekhq/files/8240654/customs.zip)

**Comment by Windchild292** [comment]
Duplicates #3146, resolved in #3148.
