### ISSUE TITLE
RFE: Hanger status improvement

### ISSUE THREAD

**Issue by mjbroekman** [MegaMek/mekhq#3173]
### Environment
	Release Date: 2022-02-18
	Today: 2022-03-14
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.13
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 8 GB

### Description
The 'Status' field in the Hanger is "severely" overloaded in the current use. It represents not only the condition of the unit (salvage, damaged, mothballed, undamaged) but also the crew state (a fully repaired unit with no crew will show up as crippled)

This RFE is aimed at updated the word status to better represent the state (in addition to the color coding):
* Separate condition from crew state:
  * Condition states:
    * Salvage
    * Undamaged
    * Light Damage
    * Moderate Damage
    * Heavy Damage (formerly Crippled)
    * Inoperable
  * Crew state
    * Mothballed
    * Uncrewed = no tech, no pilot/gunner
    * Unmaintained = no tech, 1+ pilot/gunner
    * Partial = tech, less than full pilot/gunner
    * Full = tech, full crew

The "Status" column should then be updated to show a condition/crew status:
* Examples:
  * Light Damage/Mothballed = A light damaged unit that is mothballed (and so not subject to maintenance checks) 
  * Salvage/Partial = A wrecked unit with a tech assigned
  * Inoperable/Full = A full staffed unit with some damage that makes it undeployable
  * Heavy Damage/Uncrewed = A heavily damaged unit with no personnel assigned

**Comment by Windchild292** [comment]
I'm going to be splitting it into three columns, Status (which gives you the same info as now), Condition, and Crew State.
