### ISSUE TITLE
RFE: Personnel state improvements

### ISSUE THREAD

**Issue by mjbroekman** [MegaMek/mekhq#3174]
### Environment
	Release Date: 2022-02-18
	Today: 2022-03-14
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.13
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 8 GB

### Description
While colors are currently used to indicate certain conditions of personnel (red == injured, green == pregnant, orange == permanent injury) and those colors _are_ configurable, it can be helpful to have textual indicators as well. Currently, the only textual indicator is the `*` attached to the "Prisoner" rank to represent a prisoner that is willing to defect.

The RFE is intended to add more text indicators and to change the column updated with the indicator.

* Column used: The `Role` column, rather than the `Rank` column should contain the indicators
* Prisoners should have their `Role` prepended with a `*` rather than their `Rank`
* Pregnant personnel should have a `+` prepended (they are adding to the roster, after all)
* Injured personnel should have a `-` prepended
  * Permanent injuries should be indicated by `--` instead

**Comment by Windchild292** [comment]
I'm closing this request as it is a confusing change that only helps very experienced user UX while harming new user UX.
