### ISSUE TITLE
RFE: improve minimap handling of vertically large maps

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#3179]
Related to the problem posted here: https://github.com/MegaMek/mekhq/issues/3178#issue-1174666468

There should be some means of handling playing areas where the minimap is excessively tall (and potentially wide).  When this happens, there is no way to access the part of the minimap that is hidden.  Generated maps should either be restricted to keep the minimap at a reasonable size; or scroll bars added.  I also request the -/collapse/+ minimap size controls be moved to the top of the window so that they are always visible (the window header is always on screen).

Edit: bugger, this was supposed to be in the MegaMek section, not HQ.  Please move when you can.

**Comment by Windchild292** [comment]
Duplicates https://github.com/MegaMek/megamek/issues/2304
