### ISSUE TITLE
MekHQ not printing record sheets

### ISSUE THREAD

**Issue by charred-faith** [MegaMek/mekhq#318]
I cannot print 'mech record sheets and can only print aero sheets intermittently. I have updated java and am running no custom files aside from portraits and logos. Attached is a link to my dropbox with the log and campaign file. Hopefully that's all you need. 

https://www.dropbox.com/sh/29mvsasmbwuv5k7/AACMlQYQ4MIr2it1JEPY5wOia?dl=0

**Comment by HammerGS** [comment]
NPE from log file

```
java.lang.NullPointerException
	at megameklab.com.ui.Mek.Printing.PrintMech.print(PrintMech.java:89)
	at sun.print.RasterPrinterJob.printPage(Unknown Source)
	at sun.print.RasterPrinterJob.print(Unknown Source)
	at megameklab.com.ui.Mek.Printing.PrintMech.print(PrintMech.java:612)
	at megameklab.com.util.UnitPrintManager.printAllUnits(UnitPrintManager.java:223)
	at mekhq.gui.CampaignGUI.printRecordSheets(CampaignGUI.java:6229)
	at mekhq.gui.CampaignGUI$15.actionPerformed(CampaignGUI.java:1067)
```

**Comment by charred-faith** [comment]
Yes, is that something I need to fix? I'm not java handy at all.

**Comment by HammerGS** [comment]
You could trying coping the lib folder and the images-recordsheets folder  MML install into the MekHQ folder.

But **BEFORE** doing that make sure you make a separate copy of our **WHOLE** MekHQ folder as a backup.  If the copying doesn't work you'll have to use the back up until a coder looks at was is happening.

**Comment by charred-faith** [comment]
This did work. It might be worth mentioning that there was NOT a images-recordsheets folder in the HQ data-images folder. I couldn't say which fixed the problem, the lib folder or the recordsheets folder. Also, the record sheets that print from MekHQ do not have the fluff cockpit picture that MML had. Not a big deal, though.

**Comment by HammerGS** [comment]
Sounds like we have packaging error with the releases.  You can copy the data-image-fluff folder (from MML) to the MekHQ folder to get those images

**Comment by charred-faith** [comment]
Right then. Turns out that hud.png was missing from the data-images-fluff-mech folder in HQ. Everything seems to be right as rain now. Thank you for the help!
