### ISSUE TITLE
0.49.7 NPE Prisoner Ransom

### ISSUE THREAD

**Issue by SnyderPhilip** [MegaMek/mekhq#3185]
Simple enough bug here.  When attempting to ransom a prisoner dependent, the game returns a NPE.  Obviously the reason for this is that there is no ransom value for a dependent.

Potential Solutions:
1) Assign dependents (and the unknown skill value) as 0.
2) Make children born to prisoners not prisoners
3) Don't allow prisoners to have children (although if more support is added for pirates, we'll still want slaves to be able to procreate)

[mekhq.log](https://github.com/MegaMek/mekhq/files/8336117/mekhq.log)

**Comment by Windchild292** [comment]
I've just added NONE to MekHQ's current handling, which will handle this until I spend the time to swap MekHQ's skills to using MegaMek's SkillLevel enum.
