### ISSUE TITLE
[0.48.8-711] folders missing again

### ISSUE THREAD

**Issue by kernhe** [MegaMek/mekhq#3190]
Downloaded latest snapshot, extracted mekhq-0.49.8-SNAPSHOT.zip from mhq-release-win-temurin-jdk11.zip and same files and folders are missing as in issue #3083 

Doh!

BTW, in the -windows archive all files are present, at least to what I can see now

Update: no, mm-starter still missing (my bad) removed that form the issue text above

**Comment by Windchild292** [comment]
Subsumed by #3243
