### ISSUE TITLE
NPE in MekHQ when assigning personnel

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/mekhq#3195]
### Environment
MekHQ 0.49.7
Java Vendor: Eclipse Adoptium
Java Version: 11.0.14.1
Win10 21h2

### Description
There are actually two Null Pointer Exceptions in the MekHQ log file. I don't know if they're related or not, but both occurred while assigning personnel to units. The first occurred when assigning a soldier FROM the Jump Platoon(ID:66) to the Motorized Platoon (Fieldworks ID:12). The second NPE occurred while assigning (mechwarrior) Thelma MacKail from their damaged Warhammer (ID:19) to a spare Marauder (id:4).

Both times, the NPE error popped up, but the game continued and nothing appeared to be visibly wrong.

I have been seeing this sort of NPE error when assigning units often lately. For this report, the Mechwarrior assignment NPE is the only one I can replicate on demand on the save files included. I closed MekHQ, opened it again, and tried assigning Thelma back to her Warhammer which got an NPE popup, and then back to the Marauder, which got another NPE popup.

### Files
Files attached. The zip file contains the same folder structure as MekHQ uses, so if you paste it onto an existing installation it should add everything to the correct folders. I included the logs, the MekHQ campaign, custom variants, and camo, as well as the mekHQ preferences and campaign preset files. A screenshot of the error is also included in the zip file, though it doesn't seem to say much of value.
Apparently my custom portraits folder makes the log zip too big to upload as an attachment so I have not included those, I hope they're not necessary for loading a game or related to the bug. Shouldn't be, as I've seen this occur with personnel who don't have a portrait at all.
[NPE 3-28-2022.zip](https://github.com/MegaMek/megamek/files/8366829/NPE.3-28-2022.zip)

**Comment by Windchild292** [comment]
Duplicates #3146, resolved in #3148.

**Comment by Windchild292** [comment]
Also... Props on the excellent report and data zip. Do you mind if I use this report as an example on the MegaMek wiki @PhoenixHeart512?

However... please try to open MekHQ issues on the MekHQ tracker in future.

**Comment by PhoenixHeart512** [comment]
Sure, go for it! And I apologize, I completely forgot that MekHQ had a separate tracker, which is probably why I didn't see any previous reports of this and thought it was an unreported issue, haha.

**Comment by PhoenixHeart512** [comment]
Also, dumb question that may not have a definitive answer - do you know if this NPE error is harmless, or if it is slowly corrupting my savegame behind the scenes each time it happens?

**Comment by Windchild292** [comment]
You're all good with this one, it just prevents a person service log message and a GUI refresh that'll be handled on new day instead.
