### ISSUE TITLE
3.25 : Starting a new campaign, campaign options, "load a preset" does nothing

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#32]
When starting a new campaign, i get the campaign options popup after choosing the start date. Trying to click "load a preset" at this point does nothing, and the log file shows no errors.

Log file attached.

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/182402/mekhqlog.txt)

Edit : The load a preset button still does nothing even after restarting mekhq.

**Comment by pheonixstorm** [comment]
Check the presets folder. It may be 0.3.25 is missing the presets. I know it was missing but has been fixed (possibly after that release).

It is possible this has already been fixed

**Comment by BLOODWOLF333** [comment]
Load preset doesnt work for me either I have to import campaign options which does work under the File drop-down menu.

**Comment by Question2** [comment]
I cant find a preset folder anywhere in the mekHQ folder.

**Comment by BLOODWOLF333** [comment]
Its under the mmconfig folder now with 0.3.25

**Comment by pheonixstorm** [comment]
This appears to be working as of 0.3.27
@Question2 are you still having this issue? If not please close the ticket

**Comment by Question2** [comment]
Seems to be working.
