### ISSUE TITLE
Feature Request: Navigation with arrow keys

### ISSUE THREAD

**Issue by plutonick** [MegaMek/mekhq#320]
I would like to be able to navigate the marketplace (purchase parts for instance) using arrow keys only. For some reason I am unable to do so in the marketplace screen. It works fine in 'roster' screen though.

**Comment by firefly2442** [comment]
I'm not able to replicate this.  The arrow keys work for me on the "purchase parts" screen.  What version are running?

**Comment by Windchild292** [comment]
Closing as missing information and still unable to recreate.
