### ISSUE TITLE
[49.8 Snapshot] All Units in a battle (even undestroyed) show up on kill claim Screen.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3202]
18:35:29,825 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:254) - Starting MekHQ v0.49.8-SNAPSHOT
	Build Date: 2022-04-03T01:39:41.469496400
	Release Date: 2022-02-18
	Today: 2022-04-04
	Origin Project: MekHQ
	Java Vendor: AdoptOpenJDK
	Java Version: 11.0.10
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 4 GB

### Description
All units in a battle show up on kill claim screen.  Even my units and even if they are undestroyed.  In the screen the only unit of mine to be destroyed was one of the Flea's.   The rest are undestroyed, but the Mauler, both Firestarters, Warhammer, Javelin and Wolverine are all mine.  The tank lance is an ally reinforcement lance and none of them were destroyed either.  And although it doesnt show MM in the background, this was the end of battle screen.  It was not loaded from a mul.  This happened on my first 3 battles this campaign. 

EDIT:  This is not loaded from a MUL.  Its normal end of mission screen.

Side note - the Quickdraw is mentioned in the other bug I posted yesterday.  #3201.  He didnt even appear in the battle but shows up here.

### Files
![Screenshot (355)](https://user-images.githubusercontent.com/23645569/161779727-45c35979-ec7b-436e-9800-4ab6ecab23fa.png)
[mekhq.log](https://github.com/MegaMek/mekhq/files/8419158/mekhq.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/8419160/megamek.log)
[The Bluecoats30600208B.cpnx.gz](https://github.com/MegaMek/mekhq/files/8419162/The.Bluecoats30600208B.cpnx.gz)

**Comment by Windchild292** [comment]
All enemy units should show for that dialog, for GM user specification. Anything allied to the player shouldn't appear, and the appearance is a bug.

**Comment by NickAragua** [comment]
Probably fixed by #3715
