### ISSUE TITLE
[49.8][Stratcon] No VPs being awarded/tracked during entire contract.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3203]
11:59:47,146 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:254) - Starting MekHQ v0.49.8-SNAPSHOT
	Build Date: 2022-04-03T01:39:41.469496400
	Release Date: 2022-02-18
	Today: 2022-04-06
	Origin Project: MekHQ
	Java Vendor: AdoptOpenJDK
	Java Version: 11.0.10
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 4 GB

EDIT:  Per the discussion below, victory points awarded by a scenario and VP awarded on the stratcon tab appear to be different things, so this may not be a bug.  I guess my suggestion would be to change the name of the ones awarded in scenarios to "mission points" or something similar.

### Description
I have won a number of battles.  It seems no VPs are being tracked by Stratcon even though I am earning them by winning missions.  I noticed it earlier but thought maybe I had been spending them, but I just won a new battle and it still shows zero and I have done nothing to potentially spend them.

### Files
![Screenshot 2022-04-06 133444](https://user-images.githubusercontent.com/23645569/162045581-2f8d024c-cf70-4cf3-b882-9d553bd7a90c.png)
![Screenshot 2022-04-06 133521](https://user-images.githubusercontent.com/23645569/162045595-f68f6310-419f-4a9f-8a14-9ac92f9ab61f.png)
[mekhq.log](https://github.com/MegaMek/mekhq/files/8429542/mekhq.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/8429545/megamek.log)
[The Bluecoats30600326B.cpnx.gz](https://github.com/MegaMek/mekhq/files/8429549/The.Bluecoats30600326B.cpnx.gz)

**Comment by JonhyBurner** [comment]
Did the scenarios state in red in their StratCon tab description that they would give VP?

**Comment by Thom293** [comment]
Hmm.  Not exactly sure what you mean by in read, but when doing the end screen it says what you get awarded/lose points for.  The last one was just a Battle, so it was simple, but here it shows that one should have been awarded.  Is that what you mean or do you mean something else?
![Screenshot 2022-04-06 153933](https://user-images.githubusercontent.com/23645569/162067047-dc409a8b-0cb4-4e60-a476-297abd4ff1c1.png)
.

**Comment by JonhyBurner** [comment]
This is what I mean

![image](https://user-images.githubusercontent.com/67933202/162068995-ea551328-18ce-4807-86ea-8b47bb4b021c.png)

Those "scenario victory points" are just a way for MekHQ to decide whether the scenario was won or lost. You can consider them "internal" victory points that only relate to the scenario itself.

**Comment by Thom293** [comment]
Ahh I have seen that before.  No this did not say that.  So, presumably, the orange entries above would have had that line in red when they popped up?

I honestly didnt know to look at that.  I suppose its possible I spent the VPs I earned, but I would assume it would ask me to confirm and I didnt spend any VP.  Although the contract did end in a rout so maybe I would have gotten them at the end.

**Comment by JonhyBurner** [comment]
Spending VP when reinforcing doesn't ask for confirmation, so it's easy to spend them all. I don't think there's a ticket for adding that confirmation dialog, but Nick mentioned a while back he was thinking about doing that.

**Comment by Thom293** [comment]
After playing further, I think these were being awarded but I spent them without knowing.  Will close.

**Comment by SirMegaV** [comment]
Would it be clearer if there's some sort of notification each time the VP
is being used/awarded?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Thom293** [comment]
@SirMegaV Yes very much so.  :)
