### ISSUE TITLE
[49.6] Purchase parts - Hide impossible target parts

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/mekhq#3208]
### Environment
MekHQ version: 49.6

### Description
If the tick box "Hide Impossible Target Parts" in the Purchase parts dialogue is clicked, the system hangs for about a minute with sigfnificant CPU usage befor the system recovers. The tick box remains unchecked and filtering is not done.

![Impossible parts](https://user-images.githubusercontent.com/28268113/162567295-e01c0597-3f78-4a32-ad0b-eb6684ed481a.png)

**Comment by Windchild292** [comment]
I cannot reproduce this behaviour in any of my test games nor on a clean game. I'll need campaign, customs, and logs to do anything else for this.

**Comment by mwberlindeu** [comment]
I looked up the error message in the log, it appears to be an issue with a custom unit:

> 19:12:50,705 ERROR [mekhq.campaign.unit.Unit] {AWT-EventQueue-0}
> mekhq.campaign.unit.Unit.getSparePartsCost(Unit.java:5118) - Foot Platoon (Hunting Hellhounds Frogmen) is not a generic CI. Movement mode is SCUBA

Campaign File
[Hunting Hellhounds30541123somemirothings.cpnx.gz](https://github.com/MegaMek/mekhq/files/8466342/Hunting.Hellhounds30541123somemirothings.cpnx.gz)

Custom Units
[Hunting Hellhounds.zip](https://github.com/MegaMek/mekhq/files/8466354/Hunting.Hellhounds.zip)

Logs
[Logs.zip](https://github.com/MegaMek/mekhq/files/8466359/Logs.zip)

I hope this helps.

**Comment by Windchild292** [comment]
The error code is unrelated, but I'll investigate it tonight as that reads odd.

The likely reason for this is that you are running Java 15, which is completely unsupported and will cause issues like this. Please immediately downgrade to Java 11 and try again.

The guide for our Java setup is located at https://github.com/MegaMek/megamek/wiki/Updating-to-Adoptium

**Comment by Windchild292** [comment]
(forgot to close as part of the above)
