### ISSUE TITLE
[49.6] Unit Assignment for Techs is mixing in maintenance assignments for multiple units

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/mekhq#3209]
**Environment**
MekHQ version: 49.6

**Description**
In the personal roster the following effect appears for Techs: 
Instead of the Unit Assignment the maintenance assignments for multiple units is shown. This is propably not the expected value.

![Unit Assignment Techs mixed up](https://user-images.githubusercontent.com/28268113/162567380-160f27e2-9c67-471b-8845-1b774e8adaba.png)

**Comment by Windchild292** [comment]
This is the expected and desired behaviour.
