### ISSUE TITLE
[feature request] ability to randomly assign portraits to personnel with out portraits

### ISSUE THREAD

**Issue by plutonick** [MegaMek/mekhq#321]
instead of having to assign portraits manually to all personnel that have no portraits, i would like to request an option to randomly "mass assign portraits" (from the portrait folder)

**Comment by Faolind** [comment]
Would an option for doing the same to OpFor/Ally personnel be too much to ask? (not as a right click, but as an automatic in the campaign options menu)

**Comment by Qwertronix** [comment]
Currently taking a shot at this, just adding a right-click context menu option to randomize portraits of all selected personnel in the Personnel tab. 

@Faolind That's doable too but should probably be its own separate request.

**Comment by NickAragua** [comment]
Implemented in PR #527
