### ISSUE TITLE
[49.8] Cannot repair missing limb.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3210]
10:06:11,423 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:254) - Starting MekHQ v0.49.8-SNAPSHOT
	Build Date: 2022-04-03T01:39:41.469496400
	Release Date: 2022-02-18
	Today: 2022-04-09
	Origin Project: MekHQ
	Java Vendor: AdoptOpenJDK
	Java Version: 11.0.10
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 4 GB

### Description
This Clint has been giving me issues for a long time.  I thought maybe I just didnt repair it correctly but I have now tried everything and I cannot scrap the arm and rebuild it.  It allows me to scrap it, but never will it fix.  Will also allow me to put armor on the ghost limb sometimes.  I THINK it started when it was mostly repaired but had to be deployed on a mission.  I have never been able to solve it since.  The AC5 is still on that arm in battle, even if I scrap the whole arm, armor and actuators.  Its been some months now since it started.

![Screenshot 2022-04-08 130302](https://user-images.githubusercontent.com/23645569/162580497-abe92574-a8bf-4f7e-8867-562a11f9a9e5.png)
[mekhq.log](https://github.com/MegaMek/mekhq/files/8457226/mekhq.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/8457227/megamek.log)
[The Bluecoats30600726.cpnx.gz](https://github.com/Meg
![Screenshot 2022-04-09 011941](https://user-images.githubusercontent.com/23645569/162580503-b51fdb85-639f-4d38-9a25-3d3f777c6317.png)
aMek/mekhq/files/8457228/The.Bluecoats30600726.cpnx.gz)

**Comment by kernhe** [comment]
It's a bit quirky, but it says what you have to do in the window next to the "Do Task" button: salvage pr scrap the AC/5

-> Right click Clint, select "Salvage"
-> now select "Right Arm" in the drop down under "Do Task" ... you will now only salvage the right arm
-> Do the salvage tasks
-> Right click Clint, select "Repair"
-> ... now you can replace your arm

this is my procedure. It becomes quite demanding, if you lost a complete torso.

**Comment by kernhe** [comment]
It's a bit quirky, but the system tells you, what to do in the text box right next to the "Do Task" button:

1. right click clint, select "Salvage"
2. select in the drop down under "Do Task" the right arm (we only want to salvage the arm, not the whole mech)
3. Do the task (scrap AC/5)
4. right click Clint, select "Repair"
5. Do the tasks ... but you'll need more Standard Armor :-)

It's quirky, but it works... and it's quite demanding if you have to replace a side torso.

2)

**Comment by Thom293** [comment]
Yes thank you.  Im 99% sure I did all of the above multiple times, but I guess its possible he ended up deployed every time before the repairs completed.  But I dont think so. Anyway - I think there is code now to auto-scrap bad limbs and actuators (its the orange text I think).  So if it isnt working for the clint for some reason, it may need looking at.

**Comment by swang300** [comment]
I downloaded your campaign and did the steps kernhe noted above, and everything worked.  Possible things you may have missed:

1) you need to salvage or scrap the AC/5 in the arm (step 3 above)
2) Your TNs are pretty bad. The Clint is in the field (+2) and it's A maintenance level (+3).  Moving it back to the Transport Bay gets the AC/5 scrap TN to 7
3) After you scrap the AC/5, and select repair (step 4), and the task "Replace Mech Right Arm" (step 5), the TN is 12 in the field, 10 in the Transport bay.  If you fail the TN, you lose your part and have to get it again.  Recommend you go to "extra time x4" mode to get your TN down.

After replacing the arm, installing the AC/5, and fixing the armor, the Clint is in pristine condition and out of the repair bay.

**Comment by Thom293** [comment]
Thank you.  In hindsight I should have gone back and tested this to see if I missed something when he posted the earlier answer. Looks like I just didn't scrap the AC5 even though the arm was gone.  

I will say that I think MHQ should treat all weapons on a destroyed limb as gone.  But that isn't the bug I reported. 

Like I said I should have retested myself.  Sorry for the false alarm.   Will close.
