### ISSUE TITLE
[49.8] NPE When trying to sell ASF Salvage from Hanger

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3211]
13:37:44,743 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:254) - Starting MekHQ v0.49.8-SNAPSHOT
	Build Date: 2022-04-03T01:39:41.469496400
	Release Date: 2022-02-18
	Today: 2022-04-10
	Origin Project: MekHQ
	Java Vendor: AdoptOpenJDK
	Java Version: 11.0.10
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 4 GB

Files attached.  The mechs and infantry I salvaged from that mission are right-clickable and sellable.  The ASF from that mission are not.  When right-click on them get a NPE.  Saving and loading did fix it.

[megamek.log](https://github.com/MegaMek/mekhq/files/8460245/megamek.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/8460247/mekhq.log)
![Screenshot (377)](https://user-images.githubusercontent.com/23645569/162646163-957984e0-0241-411e-95c1-623bd76aad5b.png)
[The Bluecoats30600809.cpnx.gz](https://github.com/MegaMek/mekhq/files/8460250/The.Bluecoats30600809.cpnx.gz)

**Comment by Windchild292** [comment]
This technically duplicates #1537, but I'll handle the NPE better with an error message instead and then close this.
