### ISSUE TITLE
[49.8][Stratcon] NPE when clicking on map - deleted scenario

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3225]
19:45:54,687 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:254) - Starting MekHQ v0.49.8-SNAPSHOT
	Build Date: 2022-04-03T01:39:41.469496400
	Release Date: 2022-02-18
	Today: 2022-04-14
	Origin Project: MekHQ
	Java Vendor: AdoptOpenJDK
	Java Version: 11.0.10
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 4 GB

There was a scenario I didnt want to do.  I think it was a heavy urban chase mission against some hovercraft and I had a heavy lance.  I had already deployed the lance on map.  Decided I didnt want to do mission.  Deleted in on Ops tab and it disappeared there. This happened some time ago.  Now I see that mission still shows on map and lance is perpetually deployed to that mission and if I right or left click on that mission on the map, I get a NPE.   I have tried undeploying lance on TOE screen but it just shows are redeployed next day.  And now i cant even undeploy it since the NPE started.

EDIT:  Tried Completing contract and advancing a few days.  Lance still shows as deployed.

[mekhq.log](https://github.com/MegaMek/mekhq/files/8493089/mekhq.log)
[The Bluecoats30610424.cpnx.gz](https://github.com/MegaMek/mekhq/files/8493144/The.Bluecoats30610424.cpnx.gz)
![Screenshot (396)](https://user-images.githubusercontent.com/23645569/163501226-e37c5a47-bd50-49b5-bb21-57b58eb7c360.png)
![Screenshot 2022-04-14 194729](https://user-images.githubusercontent.com/23645569/163501258-2cfd4908-a2b9-4de0-80ff-33dd15854750.png)

**Comment by SuperStucco** [comment]
For what it's worth, the last time this happened I saved the campaign file uncompressed and edited the scenario out of the XML content.  Then re-opened the campaign and switched back to GZ/compressed saves.  That undeployed the formation and allowed the campaign to continue.

**Comment by Thom293** [comment]
Hmm.  I will look at that and try it.  Thank you.

**Comment by Thom293** [comment]
@SuperStucco do you mind if I ask what file you edited?  I would not have a clue where to look.  :)

**Comment by SuperStucco** [comment]
Its an uncompressed save of the campaign file.  It's not an easy thing if you're not familiar with editing XML.  If you want, I might be able to try but I'm only running 49.7 so you would need to post a uncompressed version (wrap it in a ZIP if needed).  I would need to know the StratCon coordinates (looks like 4,4) and which mission this is in.

**Comment by Thom293** [comment]
Ok thanks.  I can edit xml.  I was able to fix the issue (not the one in this thread) by saving and reloading.  But I will look at this save later.  Thank you.

**Comment by SuperStucco** [comment]
Cool.  Inside each <mission> element is a set of StratCon data under <StratconCampaignState>.  Check for <assignedForceCoords> and <assignedForceReturnDatesForStorage> elements, like this:

`
<assignedForceCoords>
                <entry>
                    <key>1</key>
                    <value>
                        <x>8</x>
                        <y>3</y>
                        <hash>0</hash>
                    </value>
                </entry>
                <entry>
                    <key>10</key>
                    <value>
                        <x>3</x>
                        <y>3</y>
                        <hash>0</hash>
                    </value>
                </entry>
            </assignedForceCoords>
            <assignedForceReturnDatesForStorage>
                <entry>
                    <key>1</key>
                    <value>3056-06-24</value>
                </entry>
                <entry>
                    <key>10</key>
                    <value>3056-03-05</value>
                </entry>
            </assignedForceReturnDatesForStorage>
`

The offending formation should be at the coordinates.  You should be able to delete the associated elements, then reload the campaign file.

**Comment by Thom293** [comment]
That is so helpful.  Thank you.
