### ISSUE TITLE
Uncaught java.lang.NullPointerException detected 0.49.7 Windows adoptium 11.0.13

### ISSUE THREAD

**Issue by manstrokemole** [MegaMek/mekhq#3231]
0.49.7
Windows
adoptium 11.0.13

Uncaught java.lang.NullPointerException detected

### Files

**latest autosave**
[Autosave-1-Entropy** Inc.-30370115.cpnx.gz](https://github.com/MegaMek/mekhq/files/8522078/Autosave-1-Entropy.Inc.-30370115.cpnx.gz)

**Save immediately after error**
[Entropy Inc.30370117.cpnx.gz](https://github.com/MegaMek/mekhq/files/8522115/Entropy.Inc.30370117.cpnx.gz)

**Customs**
[Customs.zip](https://github.com/MegaMek/mekhq/files/8522111/Customs.zip)

**megameklog.txt and mekhqlog.txt**
[megamek.log](https://github.com/MegaMek/mekhq/files/8522091/megamek.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/8522093/mekhq.log)

**Comment by Windchild292** [comment]
Duplicates #3146, resolved in #3148
