### ISSUE TITLE
BUG: Personnel keep trying to fake their death

### ISSUE THREAD

**Issue by ThomasMarik** [MegaMek/mekhq#324]
when resolving a battle in mekHQ after doing the megamek match you have the opportunity to review and alter damage taken by your personnel. If someone has taken 6 points of damage ad you reduce it to 5 the game still considers him dead and sets him KIA. This is incorrect as a person with 5 hits is not dead unless a Lost head result is rolled.

**Comment by Dylan-M** [comment]
I cannot replicate this on the current code. I'm pretty sure this has been resolved.
