### ISSUE TITLE
[0.49.8-743 and -744] Non-Windows Snapshot broken

### ISSUE THREAD

**Issue by kernhe** [MegaMek/mekhq#3248]
Since 0.49.8-743 the MekHQ-0.49.8-SNAPSHOT.tar is <50 Megabytes compared to the normal >620 Megabytes. 

It only contains the folder lib and 2 files in bin. The rest is gone...

**Comment by Windchild292** [comment]
Duplicates #3243. If an issue has not been closed, it has not been fixed.

**Comment by kernhe** [comment]
Not really a duplicate, it is an extension... because more is missing.
