### ISSUE TITLE
MekHQ lockup when accessing Purchase Units issue (A couple of NullPointerException)

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#3249]
49.7
Windows 10
jdk-11.0.11.9-hotspot

### Description
Occasionally the MekHQ window locks up/can no longer refresh the display when accessing Purchase Units. My suspicion is this is after refit or after a certain amount of time has passed and a memory leak or similar has occurred. I end up having to force close through task manager, which seems to cause java to also have to be force closed.

### Files
[legacy.log](https://github.com/MegaMek/mekhq/files/8586954/legacy.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/8586955/megamek.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/8586957/mekhq.log)
[Helena's Valkyries30281027.cpnx.zip](https://github.com/MegaMek/mekhq/files/8586963/Helena.s.Valkyries30281027.cpnx.zip)
[Helena's Valkyries.zip](https://github.com/MegaMek/mekhq/files/8586964/Helena.s.Valkyries.zip)

**Comment by swang300** [comment]
When it locks up and you have to go to task manager, could you also  check if your CPU is pinned and how much memory is being used?
Also, from the given campaign, is there a reproducible way to get the lock up?  I don't see any issues in the logs.

**Comment by OrbMonky** [comment]
I'm not able to reproduce consistently, but it's happened twice this week. My best guess is it happens when A: the client is open for a long time (like overnight) or B: when you have created a new variant via the mekHQ meklab (ie; a making your own custom variant) and then once it's complete going to the Purchase Units window, as those are the only correlations I noticed.
It may not even be a lock up and just no longer correctly outputting updates to the screen, as I can minimize, resize, interact with the window etc. which tells me it isn't a complete crash. If it happens again I'll update w/new files and that requested info of I can grab it.

**Comment by OrbMonky** [comment]
Ok, I got a lead on it - when it occurs, once again after it's been open for a while and have been messing in the MekHQ meklab, then going to Purchase Unit, I click and it just freezes up at least visually. No CPU spike, but the 4 gb of ram I dedicated to it fills completely full and never 
![Capture](https://user-images.githubusercontent.com/59293682/166090995-34761d18-4e0f-4c7d-a876-7aceb3d7120c.JPG)
recovers. Looks like a memory leak to me.

**Comment by OrbMonky** [comment]
[legacy.log](https://github.com/MegaMek/mekhq/files/8596096/legacy.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/8596097/megamek.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/8596098/mekhq.log)
logs from latest event
[Autosave-2-Helena's Valkyries-30281122.cpnx.zip](https://github.com/MegaMek/mekhq/files/8596100/Autosave-2-Helena.s.Valkyries-30281122.cpnx.zip)
[Helena's Valkyries.zip](https://github.com/MegaMek/mekhq/files/8596101/Helena.s.Valkyries.zip)

**Comment by Windchild292** [comment]
The logs are partially corrupted, and thus this is user error. I'd guess you are running or have been running multiple programs from the same folder, which breaks most software including MM/MML/MHQ.

Given the above, I'm closing this.

Specifically, the whitespace issue below (scroll to the right to view) isn't possible with a non-corrupted logging setup.

```
16:43:07,307 INFO  [megamek.client.ui.swing.MegaMekGUI] {main}
megamek.client.ui.swing.MegaMekGUI.createGUI(MegaMekGUI.java:102) - Loaded Font: Battletech Oldstyle

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      16:44:07,657 INFO  [megamek.common.QuirksHandler] {SwingWorker-pool-2-thread-2}
megamek.common.QuirksHandler.loadQuirksFile(QuirksHandler.java:316) - Parsing C:\Users\User01\Desktop\Battle Tech Table Top\mekhq-windows-0.49.7\data\canonUnitQuirks.xml
...Parsing finished.
	Total number of unit tags: 1594
		Atlas~~Mech: duplicate entry added!
	Total number of quirk entries: 1593
```

**Comment by OrbMonky** [comment]
Hello,

I'm not sure what you mean? I'm only running one instance of MekHQ, do you mean when something like MegaMek launches? I am of course playing missions, but haven't had megamek or meklab open while any of these crashes has occurred.

**Comment by OrbMonky** [comment]
Just got the exact same lockup ensuring nothing but the normal megamek launches that MekHQ missions cause, this is NOT down to user error. There is a memory leak. I do not run multiple instances of MHQ, this is occurring during normal use.

[legacy.log](https://github.com/MegaMek/mekhq/files/8597442/legacy.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/8597443/megamek.log)
[megameklab.log](https://github.com/MegaMek/mekhq/files/8597444/megameklab.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/8597445/mekhq.log)
[Helena's Valkyries30290112.cpnx.zip](h
[Helena's Valkyries.zip](https://github.com/MegaMek/mekhq/files/8597449/Helena.s.Valkyries.zip)
ttps://github.com/MegaMek/mekhq/files/8597446/Helena.s.Valkyries30290112.cpnx.zip)

**Comment by HammerGS** [comment]
We have some errors in the MekHQ log.

This a couple of times. 
```
10:28:00,715 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$0(MekHQ.java:269) - Uncaught Exception Detected
java.lang.NullPointerException
	at mekhq.campaign.Campaign.getForceFor(Campaign.java:3763)
	at mekhq.campaign.unit.Unit.addPilotOrSoldier(Unit.java:4306)
	at mekhq.campaign.unit.Unit.addPilotOrSoldier(Unit.java:4289)
	at mekhq.gui.menus.AssignPersonToUnitMenu.lambda$initialize$15(AssignPersonToUnitMenu.java:253)
```
 also this 

```
mekhq.MekHQ.lambda$main$0(MekHQ.java:269) - Uncaught Exception Detected
java.lang.NullPointerException
	at megameklab.com.util.UnitUtil.replaceFieldGun(UnitUtil.java:4230)
	at megameklab.com.ui.convInfantry.CIFieldGunView.actionPerformed(CIFieldGunView.java:309)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
```

**Comment by swang300** [comment]
Just a note, neither of these NPEs have anything to do with accessing the Purchase Units screen

**Comment by Windchild292** [comment]
Both NPEs are resolved in latest.
