### ISSUE TITLE
Picked up pilots do not show up on resolution screen

### ISSUE THREAD

**Issue by ThomasMarik** [MegaMek/mekhq#325]
During a megamek battle you can physically pick up enemy mechwarriors with your mechs.   After the battle any enemy mechwarrior you pick up does not show up in the enemy personnel list.  Friendlies I pick up still populate just fine.   Reproduction steps would be to pick up an enemy mechwarrior during a battle then resolve the battle using /victory.

**Comment by pheonixstorm** [comment]
Known issue I believe. May already have an open ticket on SF.net

This is really a MM issue though as HQ just parses the information sent by MM.

In either case it would be nice to have a campaign save (with customs if any) along with the last MM save. It makes reproducing a lot faster.

**Comment by ThomasMarik** [comment]
I'll send it along next time it happens. To be clear you are needing the campaign save from the day of the battle and the mm autoaave?  Are you wanting the MULs as well?

**Comment by pheonixstorm** [comment]
No, just the campaign save and MM save. With that I can check the before and after in eclipse and see whats getting passed around (or not passed around).

**Comment by NickAragua** [comment]
This should have been fixed with PR #697

**Comment by AQGadget** [comment]
I've seen this one in both 0.44 and 0.46
![ammo expl](https://user-images.githubusercontent.com/17732457/70391293-816c2a00-19a1-11ea-8dd3-06093a432fc6.JPG)
![eject](https://user-images.githubusercontent.com/17732457/70391295-816c2a00-19a1-11ea-80fb-d3ad94d06762.JPG)
![picked up](https://user-images.githubusercontent.com/17732457/70391296-816c2a00-19a1-11ea-8a86-0aabcb4e2acb.JPG)
![captured pilots](https://user-images.githubusercontent.com/17732457/70391294-816c2a00-19a1-11ea-9680-937a8300d906.JPG)
