### ISSUE TITLE
[49.8 Testing Branch]  Tree Clubs become Mech Equipment

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3260]
16:34:37,112 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:254) - Starting MekHQ v0.49.8-SNAPSHOT
	Build Date: 2022-05-03T01:13:29.469020
	Release Date: 2022-02-18
	Today: 2022-05-03
	Origin Project: MekHQ
	Java Vendor: AdoptOpenJDK
	Java Version: 11.0.10
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 2 GB

Windchild asked me to post this, so I assume its unintended behavior.  Below mech is a salvaged Thunderbolt 7M.

In a MM battle, if a Mech Picks up a Tree Club and then gets killed before smashing it over someone's dome, the Tree Club becomes equipment for that Mech and is transferred back to MHQ if it is salvaged.  (Not sure if I could do it on my own mech).  I did not actually see him pick up the club here, but I have seen it in the past so I assume that is what happened.

![Screenshot 2022-05-03 191454](https://user-images.githubusercontent.com/23645569/166613548-bd541f6f-7387-4e01-80fa-9297d5d9a957.png)
[mekhq.log](https://github.com/MegaMek/mekhq/files/8617495/mekhq.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/8617496/megamek.log)
[The Bluecoats30621106C.cpnx.gz](https://github.com/MegaMek/mekhq/files/8617504/The.Bluecoats30621106C.cpnx.gz)

**Comment by Windchild292** [comment]
This needs to be cleared along with any transient flags upon return to MekHQ.
