### ISSUE TITLE
Error when Creating Campaign as Pirate Faction

### ISSUE THREAD

**Issue by Michaellaneous** [MegaMek/mekhq#3270]
### Environment
0.49.7 MekHQ
Windows 10
Java Version: 11.0.12

### Description
When creating a campaign, attempting to set faction to Pirates [PIR] it returns to the intro window and refuses to launch.
Steps: Trying to create a new game with pirates as faction consistently causes this.
https://puu.sh/IZBe7/c91520d62c.png

No saves.

### Files
[mekhq.log](https://github.com/MegaMek/megamek/files/8665119/mekhq.log)

**Comment by Windchild292** [comment]
Transferred to the MekHQ tracker. In future, please try to open MekHQ issues on MekHQ's GitHub instead of MegaMek's.
