### ISSUE TITLE
[49.8 Testing Branch] Damaged Unit does not appear in Repair Bay.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3272]
19:21:57,522 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:254) - Starting MekHQ v0.49.8-SNAPSHOT
	Build Date: 2022-05-10T23:31:57.263092
	Release Date: 2022-02-18
	Today: 2022-05-10
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.15
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 2 GB

As title.  Jenner Was on last combat mission.

[mekhq.log](https://github.com/MegaMek/mekhq/files/8666657/mekhq.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/8666658/megamek.log)

[The Bluecoats30631026.cpnx.gz](https://github.com/MegaMek/mekhq/files/8666660/The.Bluecoats30631026.cpnx.gz)
![Screenshot 2022-05-10 230037](https://user-images.githubusercontent.com/23645569/167767049-bac642b8-b871-438e-8e37-0466a8007b61.png)
![Screenshot 2022-05-10 230058](https://user-images.githubusercontent.com/23645569/167767058-d1aed36c-5ed2-493c-939d-1596700591da.png)

**Comment by finsterdexter** [comment]
I thought I was running into this, but I noticed that with StratCon active, a deployed force in the StratCon view won't show up in Repair Bay between missions. You have to undeploy them (right-click the hex in the hex view, click the force which should have a checkmark, this will undeploy them and send them back). Once I undeployed, everything showed up in repair bay. 

Maybe there needs to be a UI element somewhere to indicate deployed units can't be repaired? or if deployed units are intended to be repairable, may need to edit the `getServiceableUnits` function in Campaign.java to remove the `isUnitDeployedToStratCon` check.

**Comment by Thom293** [comment]
Old issue. Self closing as it looks like unit was still deployed.
