### ISSUE TITLE
RFE - Option in TO&E pane on right click menu to expand all below this node

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#3278]
49.7
Windows 10
jdk-11.0.11.9-hotspot

It would be a sizable QOL benefit for large units to have the ability to expand all or expand all from 'here' - 'here' being the specific node in the organization that is clicked on and thus opening everything under it automatically. When organizing a big enterprise (regiment-ish scale and above) the clicks become more and more just to be able to see what is actually in the TO&E right now. Yes, there are other ways to glean what is in there but the TO&E page is the final word, and could be made more usable in this way.

![image](https://user-images.githubusercontent.com/59293682/168307632-cbd1ed7c-76de-4db2-920e-138dbda52ad0.png)
To expand this unit to view all of its constituent parts requires 68 clicks (due to needing to double click) in order to represent individual lances - and that's after getting this far, and this has to be done every time the MekHQ suite is closed/crashes and needs to be reopened. Alternatively, retaining the expanded/minimized status in the latest save may be an acceptable upgrade to accomplish the same goal as well.

**Comment by Windchild292** [comment]
Duplicates #302 and #303
