### ISSUE TITLE
49.7--Campaign file could not be loaded, check log file for details

### ISSUE THREAD

**Issue by AfroSamurai34** [MegaMek/mekhq#3279]
### Environment
What version of MekHQ does your issue apply to? 49.7
What operating system are you using?  Windows
What java version are you using? 8

### Description
Cannot load most recent save of two different campaigns.  Recieve same error message

### Files
[mekhq.log](https://github.com/MegaMek/mekhq/files/8691774/mekhq.log)
[macks marauders30560516.cpnx.gz](https://github.com/MegaMek/mekhq/files/8691775/macks.marauders30560516.cpnx.gz)
[Kumar's Kommandoes30590725.cpnx.gz](https://github.com/MegaMek/mekhq/files/8691781/Kumar.s.Kommandoes30590725.cpnx.gz)

**Comment by Windchild292** [comment]
Duplicates #3139, workaround in issue.

**Comment by Windchild292** [comment]
Further, Java 18 is completrly unsupported. Immediately downgrade to Java 11
