### ISSUE TITLE
If you accept a contract on Taussen, the game teleports you back to Terra once you arrive

### ISSUE THREAD

**Issue by Tamren** [MegaMek/mekhq#328]
To replicate this generate and then pick a contract with a low travel time. Edit the contract so that Taussen is the location, then use the GM tools to move your troops there. Once you are on Taussen advance days until the first mission pops up, this should ensure that the contract is active. Then all you have to do is save and reload the game and you should be on Terra.

I discovered this bug when I took a security contract from Comstar on Taussen using MekHQ v42.0. I replicated it in other campaigns and other versions of mekhq.

**Comment by pheonixstorm** [comment]
If that's the case then this should be happening on any planet that gets renamed at some point. Of which there are several.

**Comment by Dylan-M** [comment]
I removed the AtB label since this isn't related to anything specific to AtB.

**Comment by jayof9s** [comment]
Responding since this was tagged to me; there's nothing I can do. This isn't a data problem, this appears to be a bug from the implementation of name changes for planets.

**Comment by Dylan-M** [comment]
So... planets have both an ID and a name. When AtB was added, the save file was made to use the name instead of the ID for the contract. I can fix it, but making it "backwards" compatible... would be unnecessarily difficult.

**Comment by Dylan-M** [comment]
Actually, this affects all contracts, not just AtB. Removing AtB flag.
