### ISSUE TITLE
[49.8 Testing Branch] NPE when trying to Remove contracts in Contract Market

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3281]
21:50:47,582 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:254) - Starting MekHQ v0.49.8-SNAPSHOT
	Build Date: 2022-05-12T01:18:20.834213
	Release Date: 2022-02-18
	Today: 2022-05-13
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.15
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 2 GB

If you have more than one contract in market, highlight first and hit "remove" that works fine.  But it does not auto-select the next contract in the list, so if you hit remove again, without manually selecting the next contract, throws an NPE.

I think I recall seeing this some time ago, and I meant to do a report, but I could not find a report on it.  Its probably in all versions.

[The Bluecoats30640817x.cpnx.gz](https://github.com/MegaMek/mekhq/files/8692023/The.Bluecoats30640817x.cpnx.gz)
![Screenshot 2022-05-13 131119](https://user-images.githubusercontent.com/23645569/168408164-de89be9e-3877-4b8c-a852-cd30afdb139a.png)
[mekhq.log](https://github.com/MegaMek/mekhq/files/8692036/mekhq.log)

**Comment by Windchild292** [comment]
We'll need the logs

**Comment by Thom293** [comment]
Sorry log attached.  But I did not do it recently.  Happened earlier.  Just got around to reporting.
