### ISSUE TITLE
RFE:  "Simple" Difficulty and Flavor Buffs - Pilot, OpFor, SPA and Edge Generation, and Edge triggers in Megamek.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3289]
And yes, I am using the term "Simple" loosely.  I know these are always more difficult than they appear.  But I what I mean is that I that this uses an already existing element that, if given a small tweak or two, could greatly increase Princess effectiveness in MM without having to actually change Princess.  It also adds a large amount of flavor to the game.  It makes real dangerous enemies that you can hate and fear.  So, a large benefit for a "small" (again used loosely) amount of effort.

This is long, and has been kicking around in my head for a while, but I _think_ if it is used, it could be done in phases, so it would not be too much to bite off all at once.

Yall have done an excellent job at adding flavor with marriages, births, deaths, origins, etc.  It adds so much to the game.  I think this would add to that, _but for the enemy_.

This is related to bugs #2643 and #3175

Summary:  1.  Fix the SPA generation/transmission for Opfor MHQ pilots to MM.  2. Have OpFor Pilots have an increased chance to roll Edge.  3. (optional and harder)  Then, when Opfor Mechs are generated, have it roll the Pilot and SPAs _after_ their mech, as I believe the game already takes "piloted mech" into account when generating SPA.  (I guess if that would require too much work, the SPA roll could take place in MM lobby when they are already sitting in their mech?)  4.  (optional and harder) Enable default Edge Triggers in MM for Opfor Pilots.  

With some or all of these changes, you will have enemy Opfor pilots that are more dangerous because their SPA will match their mech and they have the protection of Edge.  This results in having a much more dangerous Princess without having to do anything to change Princess.

_Why would you ask us to do all of this work?_  Two words:  Shojiro Yamamoto.  Just by random happenstance, Mr. Yamamoto rolled a useful SPA in a useful mech and then absolutely whupped my butt.  

![Screenshot 2022-05-14 104536](https://user-images.githubusercontent.com/23645569/168440628-a461cb7e-80a6-425d-9bfe-25161c54769f.png)

He was a whirling dervish of death and knocked down/critted me so many times 2 of my mechs became combat ineffective and the rest had no hope because I simply had no answer for him because I didnt have any fast movers of my own.  _By the end of the scenario, I hated him._  I was uncontrollably blurting out "Oh my god!"  An emotional response to a bad-ass enemy is a good thing.  Im no longer just facing Princess.  Im facing _Shojiro Yamamoto_, and I fear and hate him.  IMHO, this adds much to the game.  I literally could not win the scenario because of this guy.  This is a good thing.

As a test, after that, I had another scenario where I manually assigned SPAs in the lobby to enemy pilots.  I gave one Jumping Jack and one Melee Specialist and they proceeded turn what should have been a very easy battle into a war of attrition.  I did win that battle, but all of my mechs were slagged.  My Nightsky had to eject, and my Komodo and Vulcan were held together only by prayer and wires.  Again, I hated those particular two pilots.  The Phoenix Hawk especially.  She became my enemy.  If, say, I had lost some endo-steel arms and legs and I was on a contract with low parts availablity that would have a huge effect.  Again, this is a good thing.  Also, I ended up capturing the Phoenix Hawk pilot as a prisoner.  When I saw it I said "This @$%^!?"  She wants to defect.  I do not know if I will free her or execute her.  Honestly, _its not looking good for you_, Tomi Houd.

![Screenshot 2022-05-14 105419](https://user-images.githubusercontent.com/23645569/168441091-8d2e08b9-18d5-4f21-bc9e-d2f1db761dfe.png)

Note that Tomi Houd didnt even have all of the SPA she was supposed to have, and neither Pilot had Edge.  Which would have made them much harder.

So, it could be done in phases as posted above.  I will post some screens as an examples, because this has gotten too long already:

1.  My CO.  He is in a Bandersnatch and rolled Weapon Specialist - LRM5 after a level up.  So I think this means MHQ already takes piloted mechs into account when generating SPA.  He is a killing machine.

![Screenshot 2022-05-14 105024](https://user-images.githubusercontent.com/23645569/168441310-eb082600-a696-481a-8510-6db54b717ce9.png)

2.  A pilot I got off of the employment market.  He looks illegal because he has too many SPA, but honestly Im ok with a variance in favor of the opfor.  I bought him the Edge, but he generated with everything else.  He is super dangerous.  Imagine him in the hands of Princess?  

![Screenshot 2022-05-14 105221](https://user-images.githubusercontent.com/23645569/168441359-7c42d24a-22fc-4598-b7e2-7071a1c65128.png)

3.  This dashing guy is off of the market too, but rolled with too few SPA. 

![Screenshot 2022-05-14 105142](https://user-images.githubusercontent.com/23645569/168441423-a4cceb00-5941-46ab-88aa-fbf05cd9ba7f.png)

For Opfor generation, (or just all pilots in general) have perhaps an increased chance to roll Edge.  A chance at 0-1 for regular pilots, 1-2 for Vets, and 2 for Elites.  I just had a newborn roll with 2 Edge.  Enemy pilots should have a chance to get it too.

Thank you.

**Comment by NickAragua** [comment]
The SPA generation code for Opfors was already present, but only gave each opfor unit a 25% chance to generate SPAs (as recommended by CamOps). This is on top of the fact that green units can't get SPAs. I've added an AtB setting to let folks crank that 25% between 0 and 100 instead.

**Comment by NickAragua** [comment]
The "SPA upgrader" used by the AtB/Stratcon code does look a little bit at the unit being driven - it won't give it SPAs that are for specific weapons that the mech doesn't have, or for weapon types the mech doesn't have. I'm sure there's some tuning that can be done on specific SPAs, but a lot of it requires a lot of metadata about SPAs ("this is effective on units with jump jets", "this is effective on units with three legs under a full moon") that we don't really have and would take a significant amount of time to implement.

My suggestion is to crank up the SPA intensity in the AtB campaign options.

I don't have any plans for addressing the "illegal" market pilots - I feel that having *every* elite come with a fixed number of SPAs and *every* green come with no SPAs reduces variety, which I'm not in favor of.

You can put an issue in MM for assigning random SPAs to units, but, as usual, no timeframe guarantees.

**Comment by Thom293** [comment]
@NickAragua Perfect.  Thank you!
