### ISSUE TITLE
[49.8-Snapshot] Exception when Stratcon generates scenario/forces.

### ISSUE THREAD

**Issue by MalachiteKell** [MegaMek/mekhq#3291]
### Environment
48.9-Snapshot
Windows
Java Vendor: AdoptOpenJDK
Java Version: 11.0.11

### Description
After assigning a force to a task, and clicking the confirm button, MHQ throws an unhandled exception as shown in the screenshot. After hitting X on the force assignment dialog, the stratcon map update shows the unit assigned to the tile assigned, with a scenario generated in the briefing room with a 0x0 map and no opfor.
To recreate, load the attached zip, and begin assigning scout lances to any hex tiles on the Stratcon map. It does seem to work intermittently, about 2/3rds chance weighted toward failure.

### Files
[megamek.log](https://github.com/MegaMek/mekhq/files/8711916/megamek.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/8711917/mekhq.log)
[legacy.log](https://github.com/MegaMek/mekhq/files/8711918/legacy.log)
[Crystal Gorilla Brotherhood31050117.cpnx.gz](https://github.com/MegaMek/mekhq/files/8711919/Crystal.Gorilla.Brotherhood31050117.cpnx.gz)
[customs.zip](https://github.com/MegaMek/mekhq/files/8711922/customs.zip)
![Screenshot 2022-05-17 152347](https://user-images.githubusercontent.com/20194453/168922280-e342bcd8-9ba2-48fa-b74e-825720b0a182.png)
[Crystal Gorilla Brotherhood31050117 post error.cpnx.gz](https://github.com/MegaMek/mekhq/files/8711926/Crystal.Gorilla.Brotherhood31050117.post.error.cpnx.gz)

**Comment by NickAragua** [comment]
This appears to be an issue with Compute.randomInt(nameList.size() + (int) (nonExclusivesWeight + 0.5));

It seems that nonExclusivesWeight can be less than 0.

**Comment by PhoenixHeart512** [comment]
I'm getting this 100% of the time when I deploy to the known enemy location (checked using GM reveal on the track) as well as any hex that randomly generates a mission.
File structure inside the zip matches MHQ folder structure, so you should be able to paste it over a clean install and it will put everything in the right place
[MHQ Stratcon Scenario Gen Error.zip](https://github.com/MegaMek/mekhq/files/8995625/MHQ.Stratcon.Scenario.Gen.Error.zip)
.
Save file used is "Tempest Marauders.cpnx", other saves included for completeness

**Comment by Windchild292** [comment]
It happens with an empty name list and a non-exclusive weight less than 0.5.
