### ISSUE TITLE
Null pointer when changing assigned mech

### ISSUE THREAD

**Issue by Gmoth** [MegaMek/mekhq#3295]
### Environment
[mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:290) - Starting MekHQ v0.49.7
	Release Date: 2022-02-18
	Today: 2022-05-20
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.13
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 2 GB

### Description
When changing a pilots assigned mech through the right-click menu, under the personnel tab, MekHQ generates a null pointer exception. This only happens if the pilot is already assigned to a mech, and you change them into another mech. No issue unassigning the pilot from the mech. Assigning a pilot a mech when they have none assigned does not generate the error, only when assigning them a new mech while they already have one assigned, regardless of which mech you assign them from/to

The mech is assigned without problem however, can't detect any actual problems other than it generates the error. 

### Files
[mekhq.log](https://github.com/MegaMek/mekhq/files/8741130/mekhq.log)
[Red Death30541031.cpnx.gz](https://github.com/MegaMek/mekhq/files/8741133/Red.Death30541031.cpnx.gz)

**Comment by Windchild292** [comment]
Duplicates #3146, fixed in #3148
The only effect is it doesn't properly create the force assignment message in the personnel log.
