### ISSUE TITLE
3.25 : All allied units are marked as total loss after battle even if undamaged

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#33]
All allied units are marked as total loss after battle even if they are underdamaged. Happens in all battles.

Save attached including the last autosave before the battle ended.

[#battletech.zip](https://github.com/MegaMek/mekhq/files/183044/battletech.zip)
![mekhq](https://cloud.githubusercontent.com/assets/1191378/13932966/e187a4d0-effe-11e5-8656-dad585e31936.jpg)

**Comment by BLOODWOLF333** [comment]
I believe that is what is supposed to happen.  Or else those units would show up in your hangar afterwards and become part of your unit which they're not supposed to.  But, if any allied units are destroyed your supposed to receive a minor contract breach.

**Comment by Akjosch** [comment]
Yeah, allied units are supposed to be doing that. I guess it's a bit counter-intuitive, but there's little we can do with the current MegaMek framework.

**Comment by Question2** [comment]
Im pretty sure that allied units will not show up in your hangar even if they are not marked as total loss...the only one ive seen where they do show up in your hangar afterwards seem to be in civilian help (which i believe is intended, as you are rescueing those units).

It will take a while to test this though.

**Comment by Question2** [comment]
Yea i can confirm that even if you dont mark allied units as total loss, they wont show up in your hangar.

If you want to see it, play the mission, declare victory and set allied units to not total loss. They still wont show up in your hangar afterwards.

[#battletech.zip](https://github.com/MegaMek/mekhq/files/196916/battletech.zip)

**Comment by BLOODWOLF333** [comment]
Ok, thats working correctly then.  They're part of another allied unit and cannot be salvaged/join your unit.  Are you wanting to get those units at the end of the scenario?

**Comment by Question2** [comment]
No, I was just confirming that the total loss thing wasnt intended to prevent you from adding them to the hangar. Infact, im pretty sure the total loss bug wasn't present in an earlier version...
