### ISSUE TITLE
[49.8 Testing Branch] Out of Memory Error at end of Scenario Resolution.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3307]
11:43:01,787 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:254) - Starting MekHQ v0.49.8-SNAPSHOT
	Build Date: 2022-05-16T01:41:50.033873500
	Release Date: 2022-02-18
	Today: 2022-05-26
	Origin Project: MekHQ
	Java Vendor: AdoptOpenJDK
	Java Version: 11.0.10
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 2 GB

Not sure if its a MM or MHQ issue.  As title.  Happened at end of Scenario resolution, after the final "Choose Victory or Defeat" screen.  MM did not close and give me the "you have become disconnected from the server" message until after I dismissed the error message, but visually it had already swapped over to MHQ.  

If it matters, this pilot on screen died to a headshot.  And I lost scenario.

![Screenshot 2022-05-26 232731](https://user-images.githubusercontent.com/23645569/170629824-b63885c6-3079-44a5-b7db-a48118d4e6b6.png)
[mekhq.log](https://github.com/MegaMek/mekhq/files/8783934/mekhq.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/8783939/megamek.log)
[autosave.sav.gz](https://github.com/MegaMek/mekhq/files/8783944/autosave.sav.gz)
[The Bluecoats30660125B.cpnx.gz](https://github.com/MegaMek/mekhq/files/8783946/The.Bluecoats30660125B.cpnx.gz)

**Comment by Windchild292** [comment]
Resolved in latest (was almost certainly a connection-based leak)
