### ISSUE TITLE
[49.8 Testing Branch] Duplicate Pilot Issue.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3308]
20:00:34,808 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:115) - Starting MegaMek v0.49.8-SNAPSHOT
	Build Date: 2022-05-16T01:41:50.033873500
	Release Date: 2022-02-18
	Today: 2022-05-27
	Origin Project: MekHQ
	Java Vendor: AdoptOpenJDK
	Java Version: 11.0.10
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 2 GB

No idea what happened here.  Has persisted through save/reload.

Basically Hitman was damaged and I THINK pilot ejected but I am not 100% certain.  I could not replace limb due to parts availability.  I "unassigned all crew" and mothballed it.  Put pilot in new Mech (Razorback).  This happened a few battles ago.

Now, in TO&E can add duplicate pilot in old mech (he appears injured though).  He does not appear twice in personnel window, but does appear twice in Hanger as pilot.

![Screenshot 2022-05-27 195724](https://user-images.githubusercontent.com/23645569/170803888-31464513-c0ad-4555-a1d3-986e53cad617.png)
![Screenshot 2022-05-27 200929](https://user-images.githubusercontent.com/23645569/170803890-6ae65563-00a5-4a91-ab30-4c5d2cf4cf90.png)
![Screenshot (456)](https://user-images.githubusercontent.com/23645569/170803961-322c8847-9b4a-4938-9242-a0f7cc5b743f.png)

[megamek.log](https://github.com/MegaMek/mekhq/files/8790236/megamek.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/8790237/mekhq.log)
[The Bluecoats30660131.cpnx.gz](https://github.com/MegaMek/mekhq/files/8790239/The.Bluecoats30660131.cpnx.gz)

**Comment by JonhyBurner** [comment]
Something similar happened to me. If the duplicated pilot lived through the initial duplication of personnel bug, a duplicated "driver" would have appeared in the save on the mech entry. Removing the pilot only removes one instance, and so, when activating the mech again, a ghost pilot appears. Can you check if you have an earlier save with the mech mothballed, and see if there's a pilot attached to it?

**Comment by Thom293** [comment]
@JonhyBurner Thank you.  I GM deleted the Hitman, and it seems to have gotten rid of him.  But if he starts his haunting up again I will properly exorcise him.

Im curious what causes this?  I always thought the "remove all crew" dropdown removed both pilot and tech, but maybe it doesnt remove the invisible gunner?

**Comment by JonhyBurner** [comment]
It was related to the duplicated crew bug. It duplicated gunners left and right, and did so in the mechs too. If you removed a pilot, it removed from the mech just one instance of the duplicated gunner, leaving one behind. If you added a new pilot, the gunner part of the new one would get below the old one inside the save, so the game saw a mech piloted by half a mechwarrior and gunned by another half...

**Comment by Thom293** [comment]
Was looking for something else and am pretty sure this is solved as part of another issue.  Closing.
