### ISSUE TITLE
49.8 - Multiple RFE:  Running List of MHQ QOL Suggestions

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3310]
I feel as if I dont say this enough.  But thank you for the wonderful game.  

Here is just a running list of "minor" QOL things I noted.  Wanted to put it up since a new version is out and before list got too long.  

All of the information is there, so these are just QOL suggestions.  Mainly, the most constant "interrupt" in MHQ is tab switching to find some detail, then tab switching back.  Obviously, that is needed, and how the game is organized.  But in circumstances where there are already existing pop-up windows or sub-tabs to prevent tab switching, I think it would be helpful to have those be more universal.

1. In the TO&E, the pilot frame has a subtab where you can view unit.  Request is for this to be added to the Personnel Tab pilot frame too.  And perhaps in the Hanger window, have the Unit frame have a pilot sub-tab.
![Screenshot 2022-05-28 125303](https://user-images.githubusercontent.com/23645569/170837380-32986740-a0d4-4295-84cc-9e535a0170d9.png)
![Screenshot 2022-05-28 125353](https://user-images.githubusercontent.com/23645569/170837386-ce2742c3-c122-42d6-a473-415182e7307e.png)
![Screenshot 2022-05-28 125513](https://user-images.githubusercontent.com/23645569/170837391-46dc9942-b3b9-4aaa-835b-0572fdfa13ad.png)
2. In Briefing Tab, a right-click menu option to bring up TRO of Unit.  Rare units and different version numbers cause me to switch to "purchase unit" screen to look them up.  I suppose a hyperlink to the pop up anywhere a unit name is listed would be better, but that might require too much work.
![Screenshot 2022-05-28 124006](https://user-images.githubusercontent.com/23645569/170836840-c7dfbc95-f636-4af5-a20d-ec9e48e99729.png)
3. In infirmary, a medical chart pop-up button added to end of nameplate.  This already exists in Personnel tab.  Infirmary is only place you cant see medical details. 
![Screenshot 2022-05-28 124439](https://user-images.githubusercontent.com/23645569/170837008-44f8bb57-f0c0-4d99-80f8-38895fcab5c6.png)
4.  Allow Change repair location for mothballed units.  It is currently greyed-out.
![Screenshot 2022-05-28 124912](https://user-images.githubusercontent.com/23645569/170837136-94514200-d499-496c-909a-2ddeadaa9a31.png)
5.  In StratCon Tab, have "Total Ally BV" and "Total Enemy BV" listed in scenario setup wizard.  This is the most common cause of tab-switching from Strat-con.  Switching back to the briefing tab to check enemy BV, and then switching back to StratCon.
![Screenshot 2022-05-27 154256](https://user-images.githubusercontent.com/23645569/170837500-ee172b2b-235d-4d65-85ae-52f8b37ee7e5.png)
6.  A category dropdown list for the "Parts in Use" tab on the main screen.  (There is already an RFE for a search box too).
![Screenshot 2022-05-28 130143](https://user-images.githubusercontent.com/23645569/170837656-1b2504e2-2b09-4342-a7d3-2e035c7e1255.png)
![Screenshot 2022-05-28 130231](https://user-images.githubusercontent.com/23645569/170837672-c7d092e7-abde-4b90-92c1-f7aaafb8d6bd.png)

I have another list for MHQ and MM, but they are for additions, so I will do it later as I dont have time right now.

Thank you again for all of the hard work.

**Comment by Windchild292** [comment]
Please open these in individual issues instead of using a list in future.

For the above list (with some names):
1. Duplicates #2670
2. Open, `RFE: Add Briefing Room OpFor EntityReadoutDialog`
3. Duplicates #1159
4. IIRC that's implementing RAW
5. Check the StratCon issues, and if it's not open feel free to open a RFE
6. Open, `RFE: Add Command Center Procurement Information Part Type Filtering`

**Comment by Windchild292** [comment]
Closing given it's a list
