### ISSUE TITLE
RFE: Adding manual personnel payments that generate Finance debit

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/mekhq#3318]
Please can you take a look at adding an option, perhaps on a right-click menu, to enable user specified c-bill payment amounts on the current day to individual personnel that also generates a corresponding debit on the 'Finances 'balance sheet'.

(Come to think of it, the 'balance sheet' should also be listed as 'income statement' or 'P&L' :) )

**Comment by Windchild292** [comment]
P&L?

**Comment by Gribbly1** [comment]
Profit and loss.

**Comment by Rewstyr** [comment]
Can this ticket be closed now?
