### ISSUE TITLE
Infantry Customization bugs 42.1

### ISSUE THREAD

**Issue by ThomasMarik** [MegaMek/mekhq#332]
I have noted the following bugs while trying to add a field gun to a MG Motorized unit.

AC/5 - AC/10 - AC/20: Preview shows each of these guns having AC/2 ammo instead of the appropriate type.

AC/5p - AC/10p - AC/20p: Preview shows each of these guns having AC/2p ammo instead of the appropriate type.

Heavy Rifle - Medium Rifle:  Preview shows each of these guns having Light Rifle ammo instead of the appropriate type.

Ultra AC/5:  Preview shows this unit with Ultra AC/2 Ammo instead of the appropriate type.

Ultra AC/5 - Gauss Cannon: Show up on the list incorrectly.  The year is set to 3028.  these weapons do not enter common use until 3040 and 3045 respectively.

Arrow IV Artillery shows up on list incorrectly.  Weapon went extinct in 2830 and wasn't reintroduced until 3044

**Comment by neoancient** [comment]
The field gun ammo mismatch was fixed in megamek/megameklab@bb20112.
The dates are in the process of being brought into compliance with the master tech advancement table in Interstellar Operations.

**Comment by HammerGS** [comment]
Closing this as invalid.  One part fixed the other part in Progress
