### ISSUE TITLE
Missing mekhq.jar?

### ISSUE THREAD

**Issue by Kelson92** [MegaMek/mekhq#333]
Unsure if i am simply dumb or what. Probably so in this case. But when i go to download MekHQ, it lacks the jar to actually start mekhq. The ones to start both megamek and meklab are there. But not MekHQ. Dunno what i am missing since when i look into the download for the current mekhq on github here, it isn't there either.

**Comment by HammerGS** [comment]
Their should be a MekHQ.exe for the windows releases.

**Comment by HammerGS** [comment]
Appears resolved based on forum post here - http://megamek.info/forums/index.php?topic=668.msg17780#msg17780
