### ISSUE TITLE
Problems purchasing bombs

### ISSUE THREAD

**Issue by ThomasMarik** [MegaMek/mekhq#334]
In the purchase parts window Whenever I try to purchase HE, Laser Guided, TAGbomb, Inferno, or Torpedo bombs it adds Cluster Bombs to the procurement list instead.  Cluster bombs can of course be bought and are added correctly.  This happens both in Single Purchase and Bulk Purchase.  If I attempt to GM add the bombs it simply adds a cluster bomb to my inventory.

**Comment by neoancient** [comment]
It actually adds whatever type of bomb you already have, or the first one it comes to if you have more than one type because MekHQ fails to check bomb type when determining whether two types of ammo are equivalent.
