### ISSUE TITLE
[Feature Request] Loan Unit or "Owned By" flag

### ISSUE THREAD

**Issue by GraalOtonami** [MegaMek/mekhq#335]
Adding the ability to loan control of mechs to other players and have control returned at the end of the game would give the ability for a GM to have records of all mechs in play, and would allow them to use MekHQ to play Op4 while players use the mechs of the actual unit and still keep a unified list of parts/personnel available on one program.
(I did post this as a feature request on the MegaMek part, but I was told to put it here)

**Comment by purpledragon2** [comment]
I second this request.  It could then be expanded on later to allow units multiple contracts on different planets.

**Comment by NickAragua** [comment]
This will be in the next dev release.
