### ISSUE TITLE
[0.49.9-Snapshot] Skill level not based on role

### ISSUE THREAD

**Issue by kernhe** [MegaMek/mekhq#3351]
### Environment
V: 0.49.9-Snapshot
O: Linux 5.4.0-109-generic  x86_64 GNU/Linux
J: openjdk 11.0.15 2022-04-19

### Description
Because we are doing more RPG mechwarrior we started to train our mechwarriors to be able to also take a battle armor.

As shown in screenshot the elite mechwarrior Mitsumi Schmitt has a Battle Armor skill level of Green, but the column "Skill Level" mentions "Elite"

Suggestion: the Personal view should show the Skill Level according to the selected "Personnel Type" 

### Files
![Screenshot_2022-06-13_10-57-55](https://user-images.githubusercontent.com/1056746/173318323-c414bb8b-a7eb-4be6-bfd6-4b96cd007f3b.png)

**Comment by Windchild292** [comment]
This is working as designed, the skill level displayed is based on the primary role.
