### ISSUE TITLE
[Bug] [0.49.9 Nightly CI #791] Multiple Uncaught Exceptions When Exiting MM into MHQ

### ISSUE THREAD

**Issue by IllianiCBT** [MegaMek/mekhq#3357]
### Environment
Version: 0.49.9 Nightly Ci #791
OS: Mac Monterey 12.4
Java: 11.0.12

### Description
Issue: Multiple Java exceptions triggered when exiting a megamek mission into mekhq
Reproduction: Create campaign, generate AtB mission, enter mission. Exit Megamek.

### Files
[Crash Test Dummies30250222.cpnx.gz](https://github.com/MegaMek/mekhq/files/8904609/Crash.Test.Dummies30250222.cpnx.gz)
[megamek.log](https://github.com/MegaMek/mekhq/files/8904611/megamek.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/8904612/mekhq.log)

**Comment by Windchild292** [comment]
This is resolved.
