### ISSUE TITLE
non-essential issue: older image for units.  

### ISSUE THREAD

**Issue by purpledragon2** [MegaMek/mekhq#336]
![image](https://cloud.githubusercontent.com/assets/16508297/23610697/18cbc2bc-0239-11e7-821d-783968840cb3.png)

TDR-5S, FS9-H,... 
notice the unit is missing the "shadows" around the edges.  I actually like this better for unit display in the TO&E as it is crisper, but can see where it might be better to have the shadows in MegaMek for display when fighting battles. Using MHQ version 43.1 and associated files.

**Comment by wildj79** [comment]
This can be fixed without the devs having to do anything.  If you go to the folder that you have mekhq installed in, and then look in the `data/images/units` folder, there should be a file called `mechset.txt`.  There should also be a file called `localclient_mechset.txt`. All you have to do is map what images you want to be used by what units (use `mechset.txt` as an example) in the `localclient_mechset.txt` file and then at the bottom of the `mechset.txt` file add this line:

```
# Local Server/Client moved here to support overrides of existing images!
include localclient_mechset.txt
```

You'll be good to go.

_NOTE: If you are on a non-windows platform, like macOS or Linux, *make sure* that the image file name *matches exactly*, casing and all, or you'll have issues with unit images either not showing at all, or the default image being used._

**Comment by Dylan-M** [comment]
The inclusion should already exist, and you should match case regardless of platform because if you distribute it it'll need to be done.

**Comment by HammerGS** [comment]
As mentioned this can be done by editing the files.  The shaded sprites are the default main sprites.
