### ISSUE TITLE
MekHq 0.49.8 hangs when exiting MegaMek

### ISSUE THREAD

**Issue by ParsonBoyles** [MegaMek/mekhq#3360]
### Environment
MekHQ 0.49.8
Windows 64
Java 11

### Description

When I launch a game from the MekHQ, and then close the instance of MegaMek, MekHQ freezes and hangs, until I force quit it. There are no error messages.

In previous versions, this is where it would have said "You have been disconnected from the server" and bump you back to MekHQ.

I have reinstalled both the MekHQ files and Java. I'm not sure what else to do, or what log files might be helpful.

**Comment by ParsonBoyles** [comment]
Here's the MekHQ log file:

[mekhq.log](https://github.com/MegaMek/mekhq/files/8904965/mekhq.log)

Here's the MegaMek log file:
[megamek.log](https://github.com/MegaMek/mekhq/files/8904966/megamek.log)

I probably should have added to my original post that the campaign is from the previous version of MekHQ. I can upload the campaign file if it helps, but it includes many custom units, which I would have to upload as well.

**Comment by IllianiCBT** [comment]
Hang on, I'm a donkey and I brain farted over version numbers. This is the same issue as: https://github.com/MegaMek/mekhq/issues/3357
