### ISSUE TITLE
[Bug] [49.9 #793] Campaign Options Overflowing Input Fields on Personnel Tab

### ISSUE THREAD

**Issue by IllianiCBT** [MegaMek/mekhq#3362]
### Environment
Version: 0.49.9 #793
Mac: Monterey 12.4
What java version are you using?  Homebrew 11.0.12

### Description
A few entry fields in Campaign Options overflow preventing users from seeing their contents. This appears to be isolated to the Personnel tab and was first spotted in 0.49.8.

A workaround is to go into windowed mode and expand the window beyond your screen size, allowing access to the full length of the input fields. This makes me believe the tab has been set up assuming a larger screen size than I possess.

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/103902653/174212083-6f7189d4-88b9-47e5-aba1-5f813acae3d9.png">

Reproduction: access Campaign Options, either by starting a new campaign or by the menu in an ongoing campaign.

**Comment by Windchild292** [comment]
It originates in changes made between 0.49.6 and 0.49.7.

**Comment by Windchild292** [comment]
Originates in #3020.
