### ISSUE TITLE
Feature Request: Separate list item for Prisoners on the personnel tab and list filters for personnel and hangar tab.

### ISSUE THREAD

**Issue by Tamren** [MegaMek/mekhq#337]
I currently have prisoner capture turned on and it's not unusual for me to capture several hundred over the course of a year long campaign. Managing these prisoners gets annoying after a while because there is no way to sort them off of the list of "active" personnel. So what would help a lot is to add another tab to the personnel screen just for prisoners. Prisoners would only appear here and not in any of the other categories. This would also make it much easier at a glance to see who is willing to defect.

________________________________________________________________________
Below split into https://github.com/MegaMek/mekhq/issues/1493

Secondly it would be helpful if we could remove or hide categories from the dropdown list. For instance I'm playing a campaign in the 3rd SSW and I don't have protomechs or battle armour. And yet I have separate tabs on the dropdown for these units. A similar issue happens on the hangar screen, I don't have any Gun Emplacements, Naval ships, Warships, Space Stations etc. These options only bloat the list as 99.99% of mercenary companies wouldn't have any of these things. 

So my suggestion is to let players tick a box somewhere and hide these options on the dropdown list, this would make the list shorter and only display things you actually own. It could also do this automatically and only show relevant categories.

**Comment by pheonixstorm** [comment]
hmm.. simple, doesn't require some tick box either. Think I might get a new feature cranked out soonish and post a PR. Well, unless ralgith thinks it should be optional, but adding a new item like I did with dependents should be easy enough as well as adding a check to ignore prisoners in the active category (maybe).

Honestly though why do you keep them around that long anyway?? Plus, sort by rank if you don't want to see the prisoners.

Second item... not really sure on that one. It wouldn't be a bad feature but I will leave that one for the devs to decide on.

**Comment by Tamren** [comment]
I only calculate prisoner ransom payments once at the end of a contract because it's a bunch of paperwork when you have hundreds of them and MekHQ doesn't do that automatically (yet? I'm still using v42). This is also for thematic reasons, I keep them until the end so that they can't just pick up weapons and come at me again. I also treat all the wounded which keeps my doctors in good skills and (in theory) keeps the other prisoners in line.

I can sort it the list in various ways but it's still a pain in the ass most of the time. If you have any amount of prisoners and you sort by skill or job the list looks like this:

Elite
Elite Prisoner
Veteran
Veteran Prisoner

So it stripes the prisoners in with the regular personnel. If you sort by rank it will always do this:

Rank X to Y
Newly hired personnel who don't have a rank yet
Prisoners

So instead of being able to just zoom to the bottom of the list to see who doesn't have a rank/job yet, you have to manually search the list for the midway point to find these people. TLDR it's just way more awkward than it should be. But putting prisoners in their own category and removing them from the mechwarrior and vehicle crew tab would solve the problem.

**Comment by purpledragon2** [comment]
I think this could be fixed if it would maintain the ranks secondary to whatever the use chooses as a primary sorting.  For some reason, only with ranks, it no longer maintains the rank sort as a secondary, when you choose to sort with any other option.

**Comment by Dylan-M** [comment]
This is something I've meant to do for some time. However, in a drop down list they're not called tabs, they're called list items. Tabs are things like the TO&E, Hangar, etc... in MekHQ. Also, it's 0.42.0, not 42. There is no such thing as a major version 42. Damn that irks the piss out of me lol.

Anyway, yes, the correct solution is to have them only show under the list items for everyone and prisoners.

@purpledragon2 It already does use whatever you sorted as last as a secondary sort. So you can sort by rank, and then something else. This won't keep prisoners from mixing in with others.

**Comment by Tamren** [comment]
@Dylan-M Sorry! I'll try to remember to type the full version numbers. Speaking of version numbers though, I should also mention that on megamek.info it still lists the "latest stable release" of mekhq as 0.2.0, and the latest dev branch as 0.3.31. These releases are from way back in 2013 and only the MegaMek links have been updated over time.

@purpledragon2 
Yeah it already does that, and it's very handy in the hangar bay. I always sort vehicles by name and then by size so that units are listed in alphabetical order within each weight category. This also works on the unit market.

**Comment by Windchild292** [comment]
Hasn't this been implemented by PR #344?
As for the second part, we could open up a new issue for it?

**Comment by HammerGS** [comment]
First part implemented in #344
