### ISSUE TITLE
Feature Request: Sort refit technician list by type, skill and work hours

### ISSUE THREAD

**Issue by Tamren** [MegaMek/mekhq#338]
IIRC the refit system is being overhauled, but I figured I should mention this anyway.

When you select a refit kit or customize a vehicle the game pops up a menu that allows you to select which technician you want to perform the refit. However this list does not sort in any fashion so all of the techs from all three disciplines get jumbled together. If you pick a technician of the wrong type, such as an aero tech while refitting a mech (as I have done accidentally several times) it doesn't stop you from doing this and only tells you that the tech is the wrong type after the fact when the refit is complete.

So the optimal order to sort the list would be something like this, from High to Low.

1. The type of technician, with the proper type placed at the top.
2. The skill level of the technician.
3. The available work hours a tech has per day, minus the amount they spend on maintenance. So a tech with 0/480 minutes would be displayed higher than one with 180/180 minutes.

**Comment by dtsosie** [comment]
Bug
Ordered list of refit technicians is sorted regardless of target refit unit.

Steps to reproduce:
1. New campaign
2. Enable GM Mode
3. Marketplace->Hire->Mech Tech; click "Add (GM)"
4. Marketplace->Hire->Mechanic; click "Add (GM)"
5. Marketplace->Purchase Unit; Heavy Tracked APC (MG); Add (GM)
6. Click Hanger; Right Click Heavy Tracked APC (MG); Customize->Choose Refit Kit
7. Click LRM Kit
Note Technician List.

Expected Result: Mechanic, Mech Tech
Actual Result: Mech Tech, Mechanic

**Comment by Windchild292** [comment]
#2439 implements the first two. Sorting by available time has not been implemented as of yet.
