### ISSUE TITLE
[Feature Request][ATB] Prisoner ransom instead of bonus

### ISSUE THREAD

**Issue by plutonick** [MegaMek/mekhq#339]
Instead of receiving a 50k bonus when you CAPTURE a prisoner, give out the following according to the ATB prisoners table

![image](https://cloud.githubusercontent.com/assets/8420602/23798088/961c165c-05ab-11e7-9353-26b2145bca22.png)

when you RELEASE them.

(in short, a change of the amount given and the timing of reward]

**Comment by neilfw** [comment]
I like this option.  Perhaps even different values... Sell (or get rewarded) them to your employer for X-fee and trade them back to your opponent for y-fee, with the fees factored by skill (as above) and by that house/faction...

**Comment by plutonick** [comment]
The value are the ones found on the atb rules. 

Of course if you could assign custom value as well (perhaps through campaign options menu as is the case for custom ranks) , that would be great too!

**Comment by Tamren** [comment]
Was the 50k reward added in .43.0? I'm still using .42.0, I'm waiting on a bugfix or two. Nothing wrong with mercenaries double dipping I guess. It would be neat if you had custom prisoner "bounties" set by your employer as each person taken alive is one less soldier on the enemy side and a source of intel. The ransom you get from releasing them later could also be customized by faction.

In regards to this feature request I should add that it's currently impossible to mass-free prisoners. You can only free prisoners one at a time, it doesn't have the option if you drag select more than one. I just delete them using the GM tools.

**Comment by pheonixstorm** [comment]
the 50k bonus has been in since the beginning I believe.

**Comment by neoancient** [comment]
The prisoner code is based on v2.18, since the most recent rules when AtB was coded (2.29) did not have them and people had requested them. I have updated the code to 2.31, but this is one rule that was overlooked. There may well be others.

**Comment by Tamren** [comment]
@pheonixstorm Hmm that's odd. Does the 50k just show up in your bank account, or is there an entry on the finance ledger? Because I haven't seen either of those things, I'll do some digging and see if I can figure out why.

**Comment by plutonick** [comment]
![image](https://cloud.githubusercontent.com/assets/8420602/23832100/15329006-0737-11e7-9510-d39ac5f9fdd5.png)

**Comment by pheonixstorm** [comment]
@neoancient I can get this done if you want. Doesn't seem like it should be too difficult.

**Comment by plutonick** [comment]
@pheonixstorm  as long as it's enabled when someone choses 'atb' in the campaign options, and it's just an option, I don't see the problem. More option = good thing, plus it's another step closer to the atb compatibility

**Comment by trent1098s** [comment]
I'd like this feature as well. I currently "back out" the 50k "bonus" and then (later) calculate out a lump sum payment for ransom before the I complete the contract. 

(Not sure if prisoners count towards leadership penalties on retirement rolls, so I always dump them for ransom and any other non-essentials before I complete a contract).

**Comment by Tamren** [comment]
Okay I figured out why I wasn't getting the 50k prisoner bounty. I think I remember turning off the "randomize prisoner capture" option as a test, and then I never turned it back on because it didn't have a visible impact on the after-action report screen. The option seems to be mislabelled because with or without it the game will automatically roll to see what enemies escape and who gets captured based on dice rolls and how injured they are. 

What turning the option off DOES do however, is stop rolling for defections and applying the 50k cbill bounty for capturing each prisoner. Maybe the option should be renamed? It doesn't seem to have an effect on what it says it does. Alternately the random defection rolls and prisoner bounties could be split off into separate options so that the player can tweak them individually.

**Comment by trent1098s** [comment]
The bigger question (before anything is 'fixed') is .. really, what should it *be*? Merc handbook 3055 (FASA 1670 pg 111 has some guidance but no set #'s for ransom. It vaguely mentions that ransom can be anywhere between 100,000-1,000-000 c-bills for a captured "unit" (no mention of size), with some factions charging more or less, and some claiming compensation or allowance for units.  It also covers the concept of clan Bondsman. But there's no set figures. I haven't been able to find any other mention of prisoners or ransom in the books I own (all of the field manuals, merc books).

Where did AtB rules come up with the ransom amounts?

**Comment by trent1098s** [comment]
Perhaps, this should be soft coded (as mentioned above by neilfw).

Basically have a table for experience level (ultra green...elite) and faction (DC, LA, etc) with multipliers. That way players could tweak it. 

The same data could be used to add a right-click context menu to "ransom back" your MIA warriors from the "Missing in Action" status in personnel roster. So your elite Mechwarrior gets captured on a mission where you didn't control the battlefield at the end (e.g. chase), and the warriors now-one-legged mech was laying helplessly in a pile of  scrap somewhere back along the way.

Mission over your top guy is now MIA. Right click > Ransom Back > "The opposing force asks $330,000 for ransom" (elite * faction multiplier of 1.1)

**Comment by Tamren** [comment]
Yeah, 50k cbills for just any old schmuck is a bit much. Your employer paying you a flat rate per-head makes sense because prisoners provide intel but most of these people are only worth about 5-10k when their families post bail. It should vary by faction with great houses doing prisoner exchanges all the time whereas a periphery power is unlikely to pay much for pirate prisoners.

**Comment by molemanBT** [comment]
+1 for mass freeing of prisoners, I can never be bothered to release them 1 by 1 and so just delete them wholesale.

**Comment by arlith** [comment]
Closed, as this was fixed with PR #425.
