### ISSUE TITLE
[UI] Links Unreadable when using GTK theme in HQ

### ISSUE THREAD

**Issue by kernhe** [MegaMek/mekhq#3393]
### Environment
V: 0.49.9 Snapshot
O: linux (Ubuntu 20.04.4)
J: openjdk 11.0.15 2022-04-19
Window Manager: Xfwm4 4.14.1 (revision 44809c49) for Xfce 4.14
Desktop Environment: Xfce 4.14

### Description
When using a GTK+ theme, the color for links does not use the "link_color" provided by the theme. 

Attached is a screenshot with the very eye-friendly theme "pho-earth-adaptive". The links should be #7BBD89 and are around #565656. 

The proposed workaround by @pakfront (https://discord.com/channels/458705327911731231/458706493659807801/996889845731442689) does not work.

### Files
![bad_colors_hq](https://user-images.githubusercontent.com/1056746/178915642-c54ee911-49b2-4d64-ad89-a54e141a9078.png)

**Comment by kernhe** [comment]
related: https://github.com/MegaMek/megamek/issues/3783

**Comment by Windchild292** [comment]
It's unrelated, and what do you mean by GTK theme? This is a bug in the theme in question, not on our end.

**Comment by kernhe** [comment]
> It's unrelated, and what do you mean by GTK theme? This is a bug in the theme in question, not on our end.

More Background on the issue: 
when you select "File > Themes > GTK+" MekHQ uses the GTK2 theme you have selected for your desktop (in my case xfce4 on linux). 

In each gtk theme folder there is a gtk-2.0 folder where the file gtkrc is located. This file describes all colors, buttons, etc for that specific theme. The file also defines the link color for the theme in the variable "link_color:" which is completely ignored by MekHQ.

The overall concept is also show here: https://stackoverflow.com/questions/2806623/how-to-access-the-theming-fonts-and-colors-on-gtk-gnome

I would like to add here that the gtk_color_scheme is deprecated as GTK3/4 are now the norm.

**Comment by kernhe** [comment]
Quick and dirty solution is to add a color attribute to all "<a href=" in src/mekhq/gui/view/*

**Comment by kernhe** [comment]
I'll close this issue as there is an official solution available: take a theme provided with MegaMek.
