### ISSUE TITLE
RFE: Load OpFor from Random .mul, callable by AtB/Stratcon random scenarios.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3410]
As title.  I guess pointing to a folder where subfolders could be placed, and it could draw randomly from various forces folders containing .mul, placed within. On a random, or BV basis, or direct reference.

This would allow for pre-set OpFors.

Possible enhancements, but would require more coding:  Allow subfolders within particular force folder, that could include portraits, and custom mech files.

Thank you.

**Comment by pakfront** [comment]
I like this idea, but would it be more robust if, rather than relying on a folder structure, it used the Force organization within a single MUL file?

**Comment by Thom293** [comment]
Yeah, not certain the best way to mechanic it.  

I guess just generally the goal would be to be able for basically anyone to create a force in MHQ - say a mech company with an ASF flight - and assign portraits, custom mechs, a company name, and export the .mul and put it someplace where that force could be drawn as a random, but rare, OpFor.  Just add some "realism" to the random OpFors sometimes.

Honestly, what I thought would be a fun idea is for the regular discord users to submit a .mul and portraits and customs for their Merc Companies or sub-units thereof, and they could be saved as random OpFors for other people to fight on occasion as a random draw, depending on years of activity.  Kind of like random "Boss Fights" that you would occasionally draw.  Just a flavor idea I have been kicking around.  Maybe too much work.

But any ideas/improvements are welcome!  That was my initial thought on it, but I am sure it could be improved.

**Comment by NickAragua** [comment]
PR #3418 will allow scenario force templates to be defined so that they are generated from a fixed MUL file; the MUL must be located within data/scenariotemplates/fixedmuls. This will ignore most other generation parameters, except the deployment zone parameters, starting location, alignment and altitude.

**Comment by Thom293** [comment]
Heck yes!  Thank you.  

So, once it goes live, we can make a few and drop them in that folder and create a scenario with the editor that uses that parameter to test?  Will it pull the entire .mul force?  Or just part of it?  Are there any limitations to the units used in the mul force?

Thank you again.
