### ISSUE TITLE
[49.8] Refurbishing a unit to raise its quality is not working 

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/mekhq#3416]
Refurbishing a unit to raise its quality is not working. I tried the usual process as well as the GM option but in both cases the quality remained at the current level, although money was deducted for the refurbishment. The refurbshment items did not show up, in the command center as to be purchased or in the warehouse as "in transit". Thus I suspect some issue in that step.

I did not share any files as the issue appears easily reproducible.

**Comment by SuperStucco** [comment]
Does refurbishment actually replace any components/locations/etc.?  Rule-wise there's no specified part replacements, although maybe that changed with the move from Strategic Operations to Campaign Operations.

It should still be increasing the overall quality or individual part values, though.

**Comment by pheonixstorm** [comment]
Refurbishment was written to follow the rules. I don't know if there has been any changes to the code (or the rules) since I wrote it.

Attach a save and any custom units and I will look into it.

**Comment by pheonixstorm** [comment]
Looked over the rules again and it doesn't appear to be any changes. As for part replacements, no, nothing actually gets replaced in HQ. You don't replace an AC/5 just because it started shaking a lot more when running. You replace the mounting gear, lube, etc and tear down and rebuild the AC/5 replacing whatever parts are worn out.

**Comment by pheonixstorm** [comment]
@mwberlindeu I was not able to reproduce this. New mech, refurbished twice, both times increased the quality one level as it is supposed to. 

There are no parts ordered for a refurbishment, only during a refit. Without the campaign file and any customs I see no way to find and fix the problem unless someone else has this same issue.

**Comment by mwberlindeu** [comment]
I checked again in version 0.49.10 and the issue remains. I have attched the campaign files and the custom units for further analysis.
[Hunting Hellhounds30550830secsafeagain.cpnx.gz](https://github.com/MegaMek/mekhq/files/9619193/Hunting.Hellhounds305508
[Hunting Hellhounds.zip](https://github.com/MegaMek/mekhq/files/9619195/Hunting.Hellhounds.zip)
30secsafeagain.cpnx.gz)

**Comment by Gribbly1** [comment]
Refurbishment is working perfectly for me in 0.49.10 (and 0.49.7)

**Comment by HammerGS** [comment]
We would need specific steps and specific units to test.

**Comment by Gribbly1** [comment]
That Nightshade looks like it's quality 'A'. If you have the 'reverse quality names' option turned on it's already at the maximum quality.

**Comment by mwberlindeu** [comment]
Ah, sorry that I did not see this before. Issue can be closed. I have rechecked with several units and it appears to work
