### ISSUE TITLE
Multiple uncaught exceptions when closing MegaMek. Resolve dialogue does not auto-show either.

### ISSUE THREAD

**Issue by MaridaConnoisseur** [MegaMek/mekhq#3423]
Version: 0.49.8
OS: Windows 11 21H2
Java Vendor: Eclipse Adoptium
Java Version: 11.0.16

When closing MegaMek, MekHQ throws multiple uncaught errors.
2x java.lang.NullPointerException
1x java.util.ConcurrentModificationException
The resolve dialogue box also does not appear

Reproduction:
Click Start Game
Close MegaMek

[501st Autonomous Regiment.cpnx.gz](https://github.com/MegaMek/mekhq/files/9267495/501st.Autonomous.Regiment.cpnx.gz)
[legacy.log](https://github.com/MegaMek/mekhq/files/9267520/legacy.log)
[megameklab.log](https://github.com/MegaMek/mekhq/files/9267521/megameklab.log)
[entitystatus.txt](https://github.com/MegaMek/mekhq/files/9267522/entitystatus.txt)

**Comment by Windchild292** [comment]
Resolved in latest
