### ISSUE TITLE
Load Last Save produces error

### ISSUE THREAD

**Issue by MaridaConnoisseur** [MegaMek/mekhq#3424]
Version: 0.49.8
OS: Windows 11 21H2
Java Vendor: Eclipse Adoptium
Java Version: 11.0.16

When clicking 'Load Last Save', an error "Cannot parse the version from . This may lead to severe issues that cannot be otherwise explained." shows up, and instead loads a new, nameless mercenary campaign at Janurary 1, 3067 starting at Outreach.

Reproduction:
Click 'Load Last Save'

[501st Autonomous Regiment.cpnx.gz](https://github.com/MegaMek/mekhq/files/9267587/501st.Autonomous.Regiment.cpnx.gz)
[megameklab.log](https://github.com/MegaMek/mekhq/files/9267592/megameklab.log)
[legacy.log](https://github.com/MegaMek/mekhq/files/9267593/legacy.log)

**Comment by Windchild292** [comment]
That's not the last file that's being loaded, and loads fine. However, this does bring up some missing error case handling, which I'm looking at now.

**Comment by Windchild292** [comment]
This has been resolved.
