### ISSUE TITLE
[Nightly] - CME when closing MM before end of game.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3427]
19:57:12,351 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:259) - Starting MekHQ v0.49.9-SNAPSHOT
	Build Date: 2022-08-04T01:57:31.617508100
	Today: 2022-08-07
	Origin Project: MekHQ
	Java Vendor: AdoptOpenJDK
	Java Version: 11.0.10
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 2 GB

As title.  I have played quite a few games, and closed MM before end of game probably 20 times because I have been testing something.  This is the first CME I have seen, so its way better than before.

Some background - if it helps.  Did some MHQ/MM stuff in the morning, went to Sunday sports, etc, and came back hours later.  Did a bit more MHQ/MM testing.  Closed it once or twice, but this last time it was open for a couple of hours through a few closed games in MM with no problems, and then took another break and came back later - after an hour or so.  The MM match was open the entire time.  My monitor had gone to sleep and everything was resized and had to resize it when I got back.  Closed MM and got the CME.  

EDIT:  Ignore the comment about the unit window.  My mistake.

The MHQ save probably isnt relevant.  But I was testing a new scenario I made with the new load OpFor from fixed mul.  I am including the new scenario below, If it matters.  But I have opened and closed it many times today with no problems.

![Screenshot 2022-08-07 221111](https://user-images.githubusercontent.com/23645569/183333070-ed2d5654-175a-48bc-bfab-c91da7d740c8.png)

[megamek.log](https://github.com/MegaMek/mekhq/files/9278407/megamek.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/9278408/mekhq.log)
[Galloping Ghosts of Java30610818 TTT.cpnx.gz](https://github.com/MegaMek/mekhq/files/9278474/Galloping.Ghosts.of.Java30610818.TTT.cpnx.gz)
[autosave.sav.gz](https://github.com/MegaMek/mekhq/files/9278475/autosave.sav.gz)

[The Bluecoats - Live Fire Exercise (3066).zip](https://github.com/MegaMek/mekhq/files/9278491/The.Bluecoats.-.Live.Fire.Exercise.3066.zip)

**Comment by Windchild292** [comment]
I believe this is resolved in latest, given no further reports of it.
