### ISSUE TITLE
Graphics Issue: MMLab screen does not fit in its MHQ window 

### ISSUE THREAD

**Issue by Faolind** [MegaMek/mekhq#343]
Just what it says. Though I wonder if anyone else has reported the issue involving the MMLab not actually working in the first place, in terms of campaigns? (PS that's my last issue for now, thanks so much for all your work guys!)

**Comment by Tamren** [comment]
Yes I reported meklab not working in 0.43 about three weeks ago. It is now listed as fixed and it should be in the next stable release.

When you say that the screen doesn't fit, what you mean exactly? Did you try making the daily log smaller by dragging the window divider over?

**Comment by neoancient** [comment]
What was fixed is that it wouldn't load. The entire window should be accessible without having to move or detach the daily log. It needs scrollbars.

**Comment by Tamren** [comment]
Oh, that's considered a bug? I ran into a similar glitch with the personnel market a few days ago, I'll post a report as soon as I can replicate it again.
