### ISSUE TITLE
Feature Request: Add Stratcon Campaign Options Preset

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/mekhq#3436]
While we can make our own presets, I would appreciate it if there was a preset included with MekHQ that had Stratcon and its applicable options already enabled instead of manually having to make adjustments each time I want to make a Stratcon preset without one to copy from.

**Comment by pheonixstorm** [comment]
Do you start with the campaign operations preset or atb preset?

**Comment by BLR-IIC** [comment]
I've started with AtB a lot in the past.  I've also been playing around with the Campaign Ops rules.  My latest presets use Campaign Ops.

**Comment by Windchild292** [comment]
This has been added.
