### ISSUE TITLE
Skill XP progression and SPA costs mangled

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#3438]
In the attached 49.7 campaign files, I was advancing through days outside of a contract, handling what should be normal activity - refits, skill increases, promotions, the usual.  I just tried to advance the skill of one crew member and noted the XP costs were off; after checking the Campaign Options the entire XP progression had been off for several game-days.

Custom units:
[Harrison's Harriers customs.zip](https://github.com/MegaMek/mekhq/files/9410650/Harrison.s.Harriers.customs.zip)
[Infantry Pack.zip](https://github.com/MegaMek/mekhq/files/9410651/Infantry.Pack.zip)

Here's the 'good' campaign save:
[Autosave-1-Harrison's Harriers-30651210 - OK skills.cpnx.gz](https://github.com/MegaMek/mekhq/files/9410595/Autosave-1-Harrison.s.Harriers-30651210.-.OK.skills.cpnx.gz)

Go to the Campaign Options and the Experience tab should look like this:
![Skills 1](https://user-images.githubusercontent.com/70451747/186265436-81803a1d-c83e-4659-b1d4-12ecd9e839b8.png)
Note the SPA costs as well.

Here's the save from the next day:
[Harrison's Harriers30651211 - wrecked skills.cpnx.gz](https://github.com/MegaMek/mekhq/files/9410618/Harrison.s.Harriers30651211.-.wrecked.skills.cpnx.gz)

![Mangled skills](https://user-images.githubusercontent.com/70451747/186267065-a71edbf5-8295-4525-8bca-b38517dbb155.png)

The skill XP progressions are all 8's, 4's, and 16's.  Also see the difference in the SPA costs, which are completely changed.

This isn't the first time I've noted this, but at the time I was working through major changes in the custom rank structure and I couldn't discount something related.  This time there was no such special work.

**Comment by gsparks3** [comment]
Did you accidentally hit "New Campaign" at any point? There's a known and difficult-to-resolve bug where doing that and canceling out changes multiple campaign options, most notably the XP costs as seen here. If you save the campaign after doing so, the changes to campaign options are also saved and persist.

**Comment by SuperStucco** [comment]
> Did you accidentally hit "New Campaign" at any point?

Really?  Yes - my precision isn't that great at times, so while trying to pick "Save Campaign..." at critical points the mouse pointer sometimes moves just a few pixels and grabs the adjacent item.  Which just happens to be "New Campaign..." in this case.

If it's not easily fixed, and is going to be around for a while, then I would request **something** be done to provide better isolation for that menu item from the much more common Save item.  Put it inside a flyout (e.g. New Campaign > New Campaign...), move it to the bottom, put separators between it and the adjacent items.  **Anything** to better isolate a known problem until a suitable fix is found.

And now after spending an hour documenting previous settings (because this WILL happen again), I get to spend another hour updating the newer campaign file.  Joy.

**Comment by Windchild292** [comment]
Duplicates https://github.com/MegaMek/mekhq/issues/2335
