### ISSUE TITLE
Company Generator does not generate units properly when a custom faction with attendant force generator files is assigned in Campaign Options

### ISSUE THREAD

**Issue by sldfgunslinger2766** [MegaMek/mekhq#3448]
### Environment
        MekHQ v0.49.9-SNAPSHOT
	Build Date: 2022-08-29T01:09:49.410546700
	Today: 2022-09-05
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.16
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 2 GB

### Description

I have made changes to data/forcegenerator/2780.xml,  data/forcegenerator/factions.xml and data/unitroles.txt that allow for a custom faction with custom units available for use with the RAT/Formation/Force generator in Megamek. I have also made changes to data/universe/factions.xml within MehHQ to create a custom playable faction. When using Manage Campaign/GM Tools Dialogue/RAT Roller, I am able to see the included custom units. However, when attempting to use Manage Campaign/Company Generator, it appears that the Company Generator is not pulling units from the proper custom faction and is instead pulling from its parent faction. When attempting to generate said companies within the Company Generator, I am making no setting changes other than maxing out the number of Companies/Lances/Mechs per Lance in order to eliminate this potentially being an RNG issue. 

Included are all relevant files to duplicate my current test set up, including two save games: One being the base save and another after generating a sample maxed out unit and advancing one day in order to show the units generated (which in this instance appear to be from the Terran Hegemony parent faction). 

After discussion with Windchild and confirming that the current Company Generator code uses many elements of the RAT Roller and that this is unexpected behavior, I am opening this issue and posting these files at his request

<img width="622" alt="RAT Roller" src="https://user-images.githubusercontent.com/40328392/188493653-960f8181-9d8a-4fc0-a05a-f7fb8e1b086a.PNG">

<img width="376" alt="Company Generator 1" src="https://user-images.githubusercontent.com/40328392/188493673-d1609527-3723-4867-a6f7-0a473bc23a85.PNG">
<img width="815" alt="Company Generator 2" src="https://user-images.githubusercontent.com/40328392/188493688-b8262ae8-ce65-4c7e-b961-3ee30588312d.PNG">

**Comment by sldfgunslinger2766** [comment]
[Custom Faction Company Generator Test Files.zip](https://github.com/MegaMek/mekhq/files/9491410/Custom.Faction.Company.Generator.Test.Files.zip)

**Comment by sldfgunslinger2766** [comment]
Addendum: Disabling 'Randomize Origins and/or Randomize Dependents' in the company generator 'solves' this issue as the generator populates the custom units in the generated company.

**Comment by Windchild292** [comment]
After further investigation we discovered that this is working as intended. There will be a few new options added based on this idea, however.
