### ISSUE TITLE
[ATB] Selling unit rules compliance to ATB ruleset

### ISSUE THREAD

**Issue by plutonick** [MegaMek/mekhq#345]
Currently MekHQ (if you enable ATB options) still calculates selling price according to vanilla MekHQ rules. 

I am adding a summary to the rule changes that would be required to be made IF a switch to pure ATB selling rules is to be made. 

SUMMARY BEGINS

```
MARKET GENERATION						

You can sell mechs and vehicles at any time directly from MekHQ, but to buy new mechs and vehicles and to sell with the possibility of getting close to the stock price of a mech or vehicle, you need to use the various markets available on the Inner Sphere.						

A Price Roll must be made for each unit to be sold – each number above the						
Price Target increases the buying price by 5%, each number below decreases by 5%. 			
						
Open Market						
Price Target (2d6):		7				
Observations:		Cannot be used to sell damaged units.				
				
Employer Market						
Observations:		Cannot be used to sell units.				

Mercenary Auctions						
Auctions where merc companies sell excess salvage or liquidate their assets.						
Price Target (2d6):		5				
Observations:		If selling damaged units, each level of damage applies a -1 do the Price Target				
	(Light:-1 / Heavy:-2 / Crippled:-3 / Inoperable:-4). MUST SELL AT LEAST 3 UNITS AT A TIME (emphasis mine)				

Factory Line						
Cannot be used to sell units.				

Black Market						
Price Target (2d6):		6				
Mechs with the “Bad Reputation” quirk receive -1 to the price roll when selling.						
When selling SL mechs prior to 3040, add +4 to the price roll.						


```
SUMMARY ENDS
--

Full rules (taken from ATB excel follows for further documentation if needed)

_MARKET GENERATION						

You can sell mechs and vehicles at any time directly from MekHQ, but to buy new mechs and vehicles and to sell with the possibility of 						
getting close to the stock price of a mech or vehicle, you need to use the various markets available on the Inner Sphere.						

Each market type has its requisites, advantages and disvantages and all of them can be generated only once month, on the 1st day of						
the month. Each market uses different RATs to determine the units available and has a different number of possible units for sale in a given						
month.						

After finding the number and specific model of units available, a Price Roll must be made for each unit available – each number above the						
Price Target reduces the stock price in 5%, each number below increases in 5%. If using the market to sell units the % are inverted.						
						
Vehicle markets receive a +1 bonus on the number of units available.						
						
Open Market						
General official market of the inner sphere, always available for buying and selling mechs and vehicles. 						
Mech Table:		Random IS				
Number of Units:		1d6-2				
Price Target (2d6):		7				
Observations:		Cannot be used to sell damaged units.				
						
						
Employer Market						
Local employer market, where the employer sells surplus units to authorized buyers.						
Mech Table:		Employer 				
Number of Units:		1d6-3				
Price Target (2d6):		7				
Observations:		Cannot be used to sell units.				

Mercenary Auctions						
Auctions where merc companies sell excess salvage or liquidate their assets.						
Mech Table:		Periphery/Mercenary				
Number of Units:		(1d6-3) x 3				
Price Target (2d6):		5				
Observations:		If selling damaged units, each level of damage applies a -1 do the Price Target				
		(Light:-1 / Heavy:-2 / Crippled:-3 / Inoperable:-4). Must sell at least 3 units at a time.				

Factory Line						
Units bought straight from the factory.						
Mech Table:		Local planet owner.				
Number of Units:		1d6-3				
Price Target (2d6):		6				
Observations:		Only mercenaries with B+ rating can use this market.				
		Cannot be used to sell units.				

Black Market						
Unofficial (and illegal) market, where stolen units are normally bought and sold.						
Mech Table:		Random IS				
Number of Units:		(1d6-3) x 2				
Price Target (2d6):		6				
Observations:		For each unit bought roll a 1d6 – if 2 you did not received the unit and lost				
		half the value paid – if 1 the unit was not received and you lost all the value				
		paid. If selling, a roll of 2 receives only half the payment and a roll of 1 loses				
		the unit without receiving anything. Damaged units can be sold without proce				
		modifiers.				

Civilian Vehicles can be bought and sold at any time. Civilian Mechs have their own market that generates 1d6						
Civilian Mechs for sale every month for the stock price.						

Mechs with the “Bad Reputation” quirk receive +1 to the price roll when buying and -1 when selling.						

When selling SL mechs prior to 3040, add +4 to the price roll._

**Comment by purpledragon2** [comment]
I like and second these ideas.  It always seemed to me to be odd that you could always just sell a unit, 'mech or otherwise, right away with no delay; regardless of situation.

**Comment by molemanBT** [comment]
You still will be able to won't you?

I'd like to see a rarity multiplier added to the buying selling price too? As far as I'm aware the price of a mech currently doesn't take into account the rarity, so a Hatchetman that comes onto the market in the early years costs the same as it does 20 years later. Also, in 3025, a Catapult that comes onto the market should be many multiples (10/20x) the price of a Wasp.

Assault mechs being $10m compared to a $4-5m medium doesn't really sit right with me seeing as Assault mechs are supposed to be gold dust.

**Comment by IllianiCBT** [comment]
AtB is no longer being developed, as it has been replaced by StratCon so closing this as 'not going to be implemented'. If you feel this is a mistake feel free to request we reopen this issue with a short explanation of why. :)
