### ISSUE TITLE
No oppnant force in scenario

### ISSUE THREAD

**Issue by Dermenore** [MegaMek/mekhq#3451]
### Environment
I use the 0.48 stable version of MekHQ on Windows 10. I don't know my version of Java.

### Description
There are no units in the Opsforce scenario generated for my current contract.
![Capture](https://user-images.githubusercontent.com/113073300/189007384-ba460d8f-6ef3-415e-8549-7f99dd635093.PNG)

It applies to all missions. I tried to load a save the (ingame) day before the generation of the contracts. The new contract generated had also no Opsforce.
The precedent contracts haven't this issue.

### Files
[Les Lames Jurées30631221.cpnx.gz](https://github.com/MegaMek/mekhq/files/9522462/Les.Lames.Jurees30631221.cpnx.gz)
[customs.zip](https://github.com/MegaMek/mekhq/files/9522474/customs.zip)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/9522498/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/9522499/mekhqlog.txt)

**Comment by Windchild292** [comment]
Resolved in latest develop.
