### ISSUE TITLE
0.49.10 mission generate "Base Attack" only

### ISSUE THREAD

**Issue by wataru0042** [MegaMek/mekhq#3455]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
MekHQ 0.49.10 windows 10 home

### Description
Against bot campaign missions were generated only "Base Attack".

**Comment by Windchild292** [comment]
Does the OpFor have invincible morale? That will always lead to the generation of a Base Attack (Defender) battle.

There's also no files attached, nor a description of the issue beyond the basics, so I have no ability to investigate beyond that.

**Comment by wataru0042** [comment]
I see. Indeed, the enemy was the clan, and the morale was "invincible".

**Comment by Windchild292** [comment]
Working as intended
