### ISSUE TITLE
Piloting stats not updating from MekHQ to Megamek

### ISSUE THREAD

**Issue by Wargamer777** [MegaMek/mekhq#3458]
### Environment
What version of MekHQ does your issue apply to?  49.10
What operating system are you using?  Windows
Java: Adoptium v.11

### Description
Mechwarriors stats in MekHQ don't update when launching a scenario.  

### Files
Provide the .cpnx campaign file that this issue occurs in.
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the megamek.log and mekhq.log files for any NPEs or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual megamek.log and mekhq.log files
(Delete the above lines)
[The Blood Hound Marauders30430604.cpnx.gz](https://github.com/MegaMek/mekhq/files/9584507/The.Blood.Hound.Marauders30430604.cpnx.gz)
[Orion ON1-H Mk II.zip](https://github.com/MegaMek/mekhq/files/9584514/Orion.ON1-H.Mk.II.zip)
[mekhq.log](https://github.com/MegaMek/mekhq/files/9584523/mekhq.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/9584532/megamek.log)
![Pilot_bug1](https://user-images.githubusercontent.com/68032032/190653404-b61f39d5-80bc-4e96-a3aa-f0b13937ccb6.JPG)
![Pilot_bug2](https://user-images.githubusercontent.com/68032032/190653436-67cc61ca-ea1d-48e5-9ca6-3480d2d2c676.JPG)

**Comment by Windchild292** [comment]
MekHQ does not support the legacy split gunnery option.
