### ISSUE TITLE
49.10 Salary for LAM pilots is set to zero and needs to be manually set

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/mekhq#3460]
Salary for LAM pilots is set to zero and needs to be manually set. This is a little bit inconvenient.

**Comment by Windchild292** [comment]
This is incorrect. LAM Pilots have a default salary of 3000 C-Bills.

**Comment by mwberlindeu** [comment]
I tried again, hired a new LAM pilot. Salary was set to "0".

**Comment by mwberlindeu** [comment]
If I hire a new mechwarrior a sensible salary is shown.

![grafik](https://user-images.githubusercontent.com/28268113/191594312-139f6a9d-f349-493b-b662-2f525f70a41d.png)

**Comment by Windchild292** [comment]
It's a campaign option, personnel tab.

**Comment by mwberlindeu** [comment]
Thanks, apparently the default salary there was set to 0 for some reason. This solves the issue.
