### ISSUE TITLE
49.10 Convenience to select Techs with "Clan Tech Knowledge" trait

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/mekhq#3461]
Convenience / Usability improvement

I have a unit mixing Inner Sphere and Clan tech. I would like to assign only those Techs to the Clan units that have the "Clan Tech Knowledge" trait. However there is no convenient way to filter for those Techs (or I did not see it). Thus I have to go through the Personal tab through the Techs to identify those who have the desired trait.

The same goes for the repair bay.

**Comment by pheonixstorm** [comment]
Until this request can be dealt with I suggest using different ranks for such techs. I use Sgt for techs that have the maintainer SPA and Master Sgt for Engineers.

**Comment by repligator** [comment]
Closing as no longer relevant, since the SPA no longer exists.
