### ISSUE TITLE
[49.10 NPE] When battle created at the top of the week

### ISSUE THREAD

**Issue by Leafback** [MegaMek/mekhq#3473]
### Environment
MHQ vr. 49.10
OS Win 10 
Java vr. 11.0.16.1 Eclipse Adoptium

### Description
I received an NPE when a battle was created at the top of a week on March 3. This didn't happen on other weeks until the battle was created.

To reproduce, I loaded the previous save (the one provided) and advanced the day until a week with a battle popped up.

### Files
[legacy.log](https://github.com/MegaMek/mekhq/files/9690900/legacy.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/9690901/megamek.log)
[megameklab.log](https://github.com/MegaMek/mekhq/files/9690902/megameklab.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/9690903/mekhq.log)
[Death Crows, Ltd.30450209.cpnx.gz](https://github.com/MegaMek/mekhq/files/9690904/Death.Crows.Ltd.30450209.cpnx.gz)

**Comment by Leafback** [comment]
After multiple times reloading the save, I noticed that OPFOR wasn't generating on battle creation. Loading into MegaMek had no opposing units.

Additinally, one time reloading I received a Special Event: Civilian Help. The NPE didn't occur and OPFOR was created normally.

**Comment by Windchild292** [comment]
This is due to customizations you made in the atbconfig.xml file, which prevented it from loading properly. You'll need to ensure that file is properly setup (with the hiringHalls element closed by a matching tag) so that it will be loaded correctly.

```
10:16:23,777 ERROR [mekhq.campaign.againstTheBot.AtBConfiguration] {SwingWorker-pool-2-thread-1}
mekhq.campaign.againstTheBot.AtBConfiguration.loadFromXml(AtBConfiguration.java:397) - 
org.xml.sax.SAXParseException; lineNumber: 171; columnNumber: 4; The element type "hiringHalls" must be terminated by the matching end-tag "</hiringHalls>".
	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:261)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:122)
	at mekhq.campaign.againstTheBot.AtBConfiguration.loadFromXml(AtBConfiguration.java:391)
	at mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:501)
	at mekhq.campaign.CampaignFactory.createCampaign(CampaignFactory.java:83)
```
