### ISSUE TITLE
0.49.10 Unit rating off due to imaginary tech shortage caused by having large craft.

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/mekhq#3475]
Another odd bug, this one affects the unit rating when dealing with large craft and normal unit techs. In the case of the image below, mech techs. This appears to affect both FMMr and Cam Ops ratings. The image shows only 3 techs listed in the unit rating panel, but four are listed under the personnel tab. A Leopard dropship is also part of the unit. If the Leopard is mothballed or removed, the unit rating tech count returns to normal. The missing tech count happens with all tech types, mech, aero, or mechanic.

No errors in the log.
![tech_count](https://user-images.githubusercontent.com/1787879/194038629-faf780eb-eeec-40da-bd38-369a3df2993a.png)

[_transportbug2.zip](https://github.com/MegaMek/mekhq/files/9714834/_transportbug2.zip)

**Comment by IllianiCBT** [comment]
Closing as resolved
