### ISSUE TITLE
49.10 AtB RFE or Bug?   I can no longer assign techs and astechs to infantry squads to "group them for my own purposes".  

### ISSUE THREAD

**Issue by purpledragon2** [MegaMek/mekhq#3485]
Might be related to or a part of Feature Request: Astech/medics as green techs/docs vs separate entity #542 

### Environment
MekHQ 49.10 with associated MegaMek and MMLab
Windows 10
What java version are you using?  If unsure it will state your java version at the top of the mekhq.log file.
(Delete the above lines)

### Description
In previous versions of MekHQ, I could assign Techs and Mechanics to a customized infantry squad to group them for my own gaming and roleplay purposes.  I used the foot (medic) squad as the base and modified and renamed it for techs/mechanics:  
Buy a foot squad (medic)
GM add all from the procurement list
Go to hangar
Right click choose customize in lab
Go to specializations tab and unclick paramedics
Click on the anti-mek button to checkmark it
Go back to weapons and choose Rifle (TK Assault)
Click on Add primary
Drop down the list and choose archaic weapons
Choose Blade (Vibro-blade)
Click on add secondary
click on begin refit
After the refit, I then GM complete the refit (in the hangar) and purchase a couple of dozen squads.  
even after advancing a couple of days, I still can not add techs or astechs to the squad.  I know I could go change roles to soldier to force the add, but that seems a lot of extra work.  

### Files
[Autosave-1-Collins Caveliers-30210309.cpnx.gz](https://github.com/MegaMek/mekhq/files/9847643/Autosave-1-Collins.Caveliers-30210309.cpnx.gz)
[logs.zip](https://github.com/MegaMek/mekhq/files/9847644/logs.zip)
[customs.zip](https://github.com/MegaMek/mekhq/files/9847645/customs.zip)

I'm not sure the files are attaching, I will check to see.

**Comment by purpledragon2** [comment]
On my computer the attached files are taking me somewhere other than to these files.  I apologize in advance if they are not working for you.

**Comment by pheonixstorm** [comment]
As far as I can remember you have always had to have either primary or secondary role to assign personnel to a unit. I've done this in the past with squads for techs. Made sure they have small arms skill and maybe them secondary soldiers. Remember what version it was that allowed this w/o the secondary role?

**Comment by purpledragon2** [comment]
yes, all of my recruits have small arms as a skill.   some of the techs/astechs also have admin so they get that for a secondary.  is there another workaround?

**Comment by IllianiCBT** [comment]
Unfortunately, it's been so long since this issue was originally logged that the available save no longer functions so it cannot be investigated.

Based on the description, I believe this issue would have been resolved by setting the characters to the soldier secondary role. As that would allow them to be assigned to infantry units.

Closing as cannot investigate.
