### ISSUE TITLE
Custom Excalibur Dropship shows mech graphics.

### ISSUE THREAD

**Issue by trent1098s** [MegaMek/mekhq#349]
Created a custom Excalibur dropship and put it in the customs folder.

MekHQ shows the incorrect image for it in TOE. (Shows mech instead of dropship)

http://imgur.com/F3x5y85

ETA: Purchase Unit also shows the incorrect image (mech instead of dropship)

Need to check the unit type for customs. Looks like it's assuming any custom is a mech, and getting the image for the mech Excalibur.

**Comment by pheonixstorm** [comment]
Custom units, especially those that share a name with other unit types, need an entry in the localclient_mechset or localserver_mechset file to show the proper image.

Not sure if this is something the devs would support adding or not. Maybe one of them will chime in on it.

**Comment by trent1098s** [comment]
Right, but for clarity, this was a mod of an existing Excalibur dropship, and not a brand new unit. The original Excalibur dropship (in the dropships archive) shows the spheroid unit icon in the purchase unit and TOE screens. The Excalibur dropship I extracted, modifed, and put in my customs folder shows the Excalibur *mech* image, and not the Excalibur *dropship* image. 

Meanwhile my custom overlord dropships show the correct overlord spheroid dropship image; so it just appears the program is grabbing the first matching Mech image based on name, instead of checking for the unit type (dropship) and pulling the image for it.

**Comment by trent1098s** [comment]
Megamek also shows the incorrect unit icon in Add Unit and on the battlefield.

**Comment by trent1098s** [comment]
I rename it to "Excaliber A" for unit name, it correctly defaults back to spheroid dropship. So it appears to be pre-empting the spheroid dropship unit icon that it should be using, if there is a mech that matches the name. 

If the unit type isn't mech, it shouldn't be looking in the mech images. :)

**Comment by pheonixstorm** [comment]
It doesn't matter if it is a new unit or not. Any custom unit needs an entry into the local mechset file to show a valid image. If not it defaults to the first image it finds with a matching chassis name.

**Comment by Dylan-M** [comment]
Closing as invalid/user error:

@pheonixstorm is correct in that you _must_ create an entry for it because the parser that decides which icon to use is very "dumb" and limited.

**Comment by trent1098s** [comment]
Thanks guys!
