### ISSUE TITLE
49.10 pilot recycling?

### ISSUE THREAD

**Issue by AfroSamurai34** [MegaMek/mekhq#3490]
### Environment
What version of MekHQ does your issue apply to?
49.10
What operating system are you using?  Windows 10
What java version are you using?  11

### Description
Not sure if this is a bug.  Pilot that had been hired was KIA.  New pilot appeared in marketplace with the same mech that the deceased pilot had, in the condition that it was in when she was killed.  On another save a coupla months ago and under a different version (49.7?) and game save this occurred with 2 or 3 pilots that died in the same battle.

### Files
Provide the .cpnx campaign file that this issue occurs in.
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
[mekhq.log](https://github.com/MegaMek/mekhq/files/9894329/mekhq.log)
tomized in this campaign like the factions.xml for example.
![Screenshot (124)](https://user-images.githubusercontent.com/14045991/198847496-3de3abed-a5a0-43d9-9dc2-b49bdbef0ffe.png)
![Screenshot (122)](https://user-images.githubusercontent.com/14045991/198847498-18373654-bb43-4fe6-af51-491897ba8436.png)
![Screenshot (123)](https://user-images.githubusercontent.com/14045991/198847499-50eac1f8-a09c-4429-b7ec-b3153f7bb53d.png)
[The Dark Ones30530306.cpnx.gz](https://github.com/MegaMek/mekhq/files/9894354/The.Dark.Ones30530306.cpnx.gz)
[megamek.log](https://github.com/MegaMek/mekhq/files/9894353/megamek.log)

**Comment by Windchild292** [comment]
We will require your customs to load the save.
![image](https://user-images.githubusercontent.com/39067288/204104127-1d4eeedb-912d-4121-87e2-fef6ebc47014.png)

Further, please reload MHQ if you leave it on overnight, as that could potentially be the cause.

**Comment by IllianiCBT** [comment]
I suspect this was a bug with the old retirement system that shouldn't exist in the current version. As we've been unable to investigate this issue for a couple of years I'm going to close as resolved.
