### ISSUE TITLE
RFE: add a home base icon to the Interstellar map

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#3493]
The Interstellar Map has system markers to indicate the current position, but that's not always 'home base' where a unit is based from when off-mission.  That's easy enough to remember when you are using a well-established and memorable system such as Galatea, Arc Royal, or Outreach, but not so easy with out-of-the way systems like Nocktatunga, Adelson, or one of the many other lesser known worlds.  Even more difficult when a campaign is not played in frequently or has a 18-month plus garrison assignment elsewhere.

I think it would be helpful to have a simple flag to note a system as 'home base', shown as a square/diamond/other unique marker in the same way the current position is multiple concentric circles.

**Comment by Windchild292** [comment]
Duplicates #1099
