### ISSUE TITLE
Quality of life request: please re-order the default awards list

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#3495]
The default awards list is difficult to navigate, as less frequently applied awards are at the top (e.g. Medal of Honor) while more commonly awarded ones are buried somewhere in the middle (e.g. Purple Heart).  Additionally kill-count based awards tend to be in reverse order e.g. higher kill counts before lower ones.  There is an order element in the XML file however it is not being made use of.

It would be helpful if the order was changed to reflect how often they are assigned.  For example, like this:

![Altered awards order](https://user-images.githubusercontent.com/70451747/200404197-9993921a-14b5-4306-9090-50c360419854.png)

(txt extension added to allow attachment)
[standard.xml.txt](https://github.com/MegaMek/mekhq/files/9955059/standard.xml.txt)

**Comment by UrsKR** [comment]
Seconded. A reordered list would.be really useful, and the proposed order looks good.
Would you like a pull request with the file?

**Comment by JonhyBurner** [comment]
My modified award list looks like this:
![image](https://github.com/MegaMek/mekhq/assets/67933202/5cb8a6ac-e5de-406c-a251-e595e1445328)

I added a couple of "filler" awards with no rewards or graphics to use as separators. Would it be possible to add these without them being clickable for better presentation?

**Comment by UrsKR** [comment]
Looks like something where an (additional?) grouping attribute could serve the system better, so mekhq can derive the proper grouping on it's own.

**Comment by SuperStucco** [comment]
> Looks like something where an (additional?) grouping attribute could serve the system better, so mekhq can derive the proper grouping on it's own.

In the meantime I've put them into separate groups as part of my personal customization:

- Formation mission: lance/company/battalion awards, at end of contract/mission
- Personal combat: personal accomplishments, at end of scenario
- Personal mission: personal accomplishments, at end of contract/mission
- Personal service: various service achievements and miscellaneous
- Training: basic training, OCS, drop/parachute, and other qualifications
