### ISSUE TITLE
49.10 Error - Saving and Loading Games

### ISSUE THREAD

**Issue by drsmurf19** [MegaMek/mekhq#3496]
I am having an issue saving and loading games.  It worked correctly for a while, but just broke recently.  I can still load some older saves and they will let me play and will generate autosaves.  However, I cannot manually save, and those autosaves will not load.

### Environment
What version of MekHQ does your issue apply to?  MekHQ 0.49.10
What operating system are you using?  Windows
What java version are you using?  If unsure it will state your java version at the top of the mekhq.log file.  Java 16.0.1
(Delete the above lines)

### Description
I try to save the game and get the error that states: 

"Oh no!  The program was unable to correctly save you game... Please help us out and submit a bug witht he hekhq.log file from this game."

It will create autosaves, but if I try to load those, I get the Error: "The campaign file could not be loaded.  Please check the MekHQ.log file for details."

### Files
Save File provided.
Autosave File provided.
MekHQ.log file provided.
Custom mech folder provided. In my system, the custom mech folder is unzipped and in the data>mechfiles folder as "SamMechs".  I had to zip it to attach it.

[Autosave-1-Rimworld Renegades-30250911.cpnx.gz](https://github.com/MegaMek/mekhq/files/10004988/Autosave-1-Rimworld.Renegades-30250911.cpnx.gz)
[mekhq.log](https://github.com/MegaMek/mekhq/files/10004992/mekhq.log)
[SamMechs.zip](https://github.com/MegaMek/mekhq/files/10005008/SamMechs.zip)
[Rimworld Renegades30250901.cpnx.gz](https://github.com/MegaMek/mekhq/files/10005538/Rimworld.Renegades30250901.cpnx.gz)

**Comment by JonhyBurner** [comment]
From the log:
"Java Version: 16.0.1"

There's your problem. The only Java version known to work with no issues is Java 11. You need to downgrade your install.

**Comment by HammerGS** [comment]
> From the log: "Java Version: 16.0.1"
> 
> There's your problem. The only Java version known to work with no issues is Java 11. You need to downgrade your install.

Exactly this. Anything past Java 11 breaks the programs HARD. 

https://github.com/MegaMek/megamek/wiki/Updating-to-Adoptium

**Comment by drsmurf19** [comment]
Thanks!

**Comment by drsmurf19** [comment]
I downgraded my Java, but I still get that error.  Would that have permanently broken my save?  I tried earlier saves too.
[mekhq.log](https://github.com/MegaMek/mekhq/files/10006538/mekhq.log)

**Comment by HammerGS** [comment]
If the save was made with Java 16 it wouldn't have written correctly and won't work.

**Comment by drsmurf19** [comment]
Ok thanks!
