### ISSUE TITLE
[REQUEST] Copy/Pasting header row from tables

### ISSUE THREAD

**Issue by plutonick** [MegaMek/mekhq#350]
I frequently copy/paste stuff from various tables (personnel, hangar) in order to use them on my campaign log blog.

However, the header row is not copied (the one containing the actual name of the columns -- Rank, Name, Skill, Role etc. Is it possible to include this as well?

Example

**Comment by neoancient** [comment]
It is technically possible to customize a table to allow inclusion of column headers, but it is not a trivial undertaking that does not affect the functioning of MekHQ itself and is of no use to the vast majority of the user base.
