### ISSUE TITLE
Campaign Options: Improve Maximum Acquisition Per Day Text and Tool Tip Text

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/mekhq#3502]
**Environment**

MekHQ version: 49.10

**Description**
Recently I order a lot of parts (ammo, armor, etc.) and smaller units like trucks. Apparently only one Admin is earning all the XPs from the resulting purchasing rolls. After a little spending spree one and only one admin ended up with more than 400 XP. I think no one admin can do it all. There should possibly some randomization on who does a purchase (also altering target rolls), and consequently XPs should not end up at one person alone.

**Comment by pheonixstorm** [comment]
There is an option you can limit the numbers of orders per day. In the same tab you can also change WHO (by selected skill) does the ordering as well

**Comment by mwberlindeu** [comment]
If I change the skill just another admin gets all the XPs.

Limiting the number of acquisitions per day is a solution. Then the purchasing tasks are split among the administrators. However the entry in the menu should propably be:
"Maximum Acquisition Per Day **and Administrator** (0 for unlimited)

**Comment by Windchild292** [comment]
Resolved in #3660
