### ISSUE TITLE
Add breakdown of support personnel requirements in Personnel Report

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#3503]
The Personnel report only shows a count of how many combat and support personnel there are.  The Unit Rating Details report does a bit better for technical support requirements, but lacks detail for administrator requirements.  It's also a bit of a weird location, since it's primarily to break down the unit rating calculation.

I would like to see the Personnel report expanded a bit for the support personnel.  Add in the optimum/available technicians required part from the Unit Rating Details dialog; optionally provide a list of which units each technician is maintaining (not just a count).  Also include the administrator requirements, including a breakdown as to how that number is arrived at.

**Comment by Windchild292** [comment]
The personnel report is a list of personnel, their roles, and their combined salaries. This would change what it does into something entirely different, only useful for small campaign.

Further, administrator and technical staff requirements are part of the unit rating calculation, hence their location.

Closing this as based on the above.
