### ISSUE TITLE
Feature Request GM Mode Personnel Tab "Set Skill Level"

### ISSUE THREAD

**Issue by trent1098s** [MegaMek/mekhq#351]
Simple request; 

In GM Mode context menu on Personnel tab a context menu item for "Set Skill Level" (green, regular, veteran, elite)

This goes along with large force generation requests I made in other items. Currently if you build a force (e.g. an Opfor unit for a campaign), the most efficient way of populating the unit is to generate the forces for the unit in Megamek, Export the MUL, then import in to MekHQ. (It would take far too long to "buy" 200+ units for a regiment and hire mechwarriors, and assign all of the mechwarriors to the units). 

When you import a MUL generated in megamek, all troops start at "Regular." (Except vehicle crews, a lot of those are randomly generated as MekHQ adds in gunners, etc). 

While this is fine, it can become a tedious task to make leaders veteran or elite, or change some units to green. 

This would make it much simpler. Currently you have to edit the warrior and set piloting and gunnery skills by hand.

<a href="http://imgur.com/epy294w"><img src="http://i.imgur.com/epy294w.png" title="source: imgur.com" /></a>

Ideally it would be available when multiple individuals are selected, or for single individuals.

**Comment by Qwertronix** [comment]
There no longer seems to be a big need for this, considering we have the "Hire in bulk" option, mass assign options, add N XP option and mass training options. 

It could be a handy QoL add-on that should be fairly easy to add, though.

**Comment by IllianiCBT** [comment]
Closed as resolved
