### ISSUE TITLE
Custom refit of Corsair-v12 ASF changes unit card to a mech

### ISSUE THREAD

**Issue by BTSS88** [MegaMek/mekhq#3526]
MekHQ v49.10
Win 11
Java 11

Custom refit of Corsair-v12 ASF changes unit card to a mech, naturally or GMed. Refitting to an existing lore kit variant does not have this issue. 

[Azure Tempest30400721.cpnx.gz](https://github.com/MegaMek/mekhq/files/10224063/Azure.Tempest30400721.cpnx.gz)
![Screenshot (6)](https://user-images.githubusercontent.com/119979347/207499364-bacf129b-3336-41ea-92cd-f4f194fefad9.png)

**Comment by BTSS88** [comment]
Hmm, I've never had any issue with unit card changing when I edit other mechs. I've done the exact same thing - just changing SHS to DHS - on another ASF and its unit card didn't change to a mech.

**Comment by HammerGS** [comment]
If you refit a ASF (or any unit) that doesn't share a name with another unit (Corsair, Condor, Hercules, etc) the chassis only part of the mechset will work. As soon as you refit a unit with shared name the mechset defaults to the chassis name and matches to the first chassis. In this case the mech.
