### ISSUE TITLE
[RFE][StratCon] Add GM support to "Unreveal" the map.

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#3528]
From a Discord discussion:
![image](https://user-images.githubusercontent.com/67933202/207721088-4c17775d-ee55-4f20-b247-5d4f116793d8.png)

So this RFE calls for an added GM functionality to reset the fog-of-war of the map.

**Comment by NickAragua** [comment]
You *can* un-reveal it - just right click on the map again and click 'Hide Track'.

**Comment by JonhyBurner** [comment]
I've just tried it on the latest dev version (49.11). While the option is there, the map shows no visual change. Adding an enemy facility and hiding the track shows the facility anyway. And you need to reveal the track even if it's already revealed before the option to hide appears.

So it's definitevely not working as intended.
