### ISSUE TITLE
Mass repair only counting temporary AsTechs, ignoring personnel with AsTech role

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#3532]
In the attached 49.7 campaign, there are multiple repairs needed.  Using the Mass Repair/Salvage option stops with a warning dialog about insufficient AsTechs:

![Insufficient AsTechs](https://user-images.githubusercontent.com/70451747/208256396-917e29e7-7d46-4dd2-91fa-f0c1ba8be880.png)

Note the AsTech pool minutes showing the full complement, which is different from the temporary AsTechs because it includes personnel with the AsTech role.  The Mass Repair/Salvage tool should be referencing the full complement of AsTechs.

[Findlay's Rifles30420812.cpnx.gz](https://github.com/MegaMek/mekhq/files/10252439/Findlay.s.Rifles30420812.cpnx.gz)

Custom infantry are present:
[Infantry Pack.zip](https://github.com/MegaMek/mekhq/files/10252444/Infantry.Pack.zip)

**Comment by Windchild292** [comment]
Your tech teams are short by 12 Astechs.

**Comment by SuperStucco** [comment]
It's not short.  There's the temporary AsTechs as shown at the left, but under the Personnel tab there are enough named personnel in the AsTech role to make up the difference.  The Repair tab, as shown at the right in the image, is showing the total of temporary AsTechs and assigned personnel - 222 AsTechs.

The assigned personnel are not being counted for the mass repair/salvage, while they are being counted for AsTech minutes available for repairs and maintenance requirements.

**Comment by Windchild292** [comment]
You need 234 Astechs, not 222. The only issue is unit rating is not updating, which is #1135
