### ISSUE TITLE
Feature Request- Layered TOE Icon expansion

### ISSUE THREAD

**Issue by Faolind** [MegaMek/mekhq#354]
Specifically, could we have the options presented as canon in the ... I think it was CampOps?

The things missing are: left-side letters............ and a few things I'm forgetting. Maybe LAMs Mech+star and Battle Armor's shaded X. I don't remember seeign those. Unfortunately I have to run very soon, and I wanted this up before I forgot. :)

**Comment by wildfire142** [comment]
Battle Armour and the LAM icons should be in the files I submitted originally. By the left side icons do you mean the ones outside the fame area or something else?

**Comment by pheonixstorm** [comment]
The TOE icons were in StratOps

**Comment by Faolind** [comment]
Thankyou Phoenixstorm.

Wildfire, if you look at "Warfare Symbology" in StratOps, starting on page 336, you'll see what I was looking at. Specifically, the Upper/Lower Left corners being devoted to the (optional) status letterings of Tech type&level and Experience/Loyalty, respectively. 

There ARE outer numbers, for "echelon" but, I think that's really too much to ask.
