### ISSUE TITLE
Extra maintenance time should not apply to units that are not maintained

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#3541]
Pretty basic concept, 2/3/4 x nothing is still nothing.

![Extra-unmaintained units](https://user-images.githubusercontent.com/70451747/208497916-23eff6c5-d5a0-4566-9de4-7bb0b1109227.png)

Not sure how difficult it would be to disable the flyout on unmaintained units.

**Comment by pheonixstorm** [comment]
Not sure where in the code that menu is, but using the isMothballed() function should remove that from those units. In fact, if there is no reason to use most of those flyout menus then all but the reactivate unit option could be removed.

**Comment by Windchild292** [comment]
After discussion on Discord, this option has use in assigning techs to units and knowing how much time it will take. Thus, I'm going to amend this PR to just not show for mothballing, activating, and mothballed.
