### ISSUE TITLE
49.11 MekHQ Save Issue

### ISSUE THREAD

**Issue by Krrast** [MegaMek/mekhq#3542]
### Environment
What version of MekHQ does your issue apply to? 49.11
What operating system are you using?  Windows
What java version are you using?  JDK 17

Loaded a 49.10 MekHQ save into version 49.11 MekHQ. Didnt make any changes, just tried saving the file from 49.11 and it pops up an error. Played through a scenario of MegaMek for a drop I had ready to go in the hopes it would update the file, still the same issue after playing a scenario and updating the MekHQ game. Updated to JDK 17 in the hopes that would fix it, no change. Posting the 49.10 save file and 49.11 MekHQ log. Hopefully its just me being an idiot somewhere along the way!

[Heilraisers30730427.cpnx.gz](https://github.com/MegaMek/mekhq/files/10291027/Heilraisers30730427.cpnx.gz)
[mekhq.log](https://github.com/MegaMek/mekhq/files/10291028/mekhq.log)
![MekHQ Save Issue](https://user-images.githubusercontent.com/17100778/209247031-3e391c1c-0dc6-4dd1-9252-55907e031446.png)

**Comment by Windchild292** [comment]
```
16:04:51,434 ERROR [mekhq.gui.CampaignGUI] {AWT-EventQueue-0}
mekhq.gui.CampaignGUI.saveCampaign(CampaignGUI.java:1305) - 
java.lang.NullPointerException: Cannot invoke "megamek.common.MechSummary.getName()" because the return value of "mekhq.campaign.market.unitMarket.UnitMarketOffer.getUnit()" is null
	at mekhq.campaign.market.unitMarket.UnitMarketOffer.writeToXML(UnitMarketOffer.java:125)
	at mekhq.campaign.market.unitMarket.AbstractUnitMarket.writeBodyToXML(AbstractUnitMarket.java:243)
	at mekhq.campaign.market.unitMarket.AbstractUnitMarket.writeToXML(AbstractUnitMarket.java:231)
	at mekhq.campaign.Campaign.writeToXML(Campaign.java:4180)
	at mekhq.gui.CampaignGUI.saveCampaign(CampaignGUI.java:1296)
	at mekhq.gui.CampaignGUI.saveCampaign(CampaignGUI.java:1269)
```

This is because the unit market should log and then ignore on the unit load, instead of allowing a null unit to propogate from parsing.
