### ISSUE TITLE
Cleaned up medal images

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#3543]
Cleaned up some jaggies and excessive halos, and patched some alpha-holes in medals for

- Combat cross
- Expert marksmanship
- Medal of Honor
- POW
- Silver Star

[Cleaned up awards.zip](https://github.com/MegaMek/mekhq/files/10296478/Cleaned.up.awards.zip)

**Comment by Windchild292** [comment]
Thanks for the cleanup, implemented
