### ISSUE TITLE
Omnimech Refits Taking Too Long

### ISSUE THREAD

**Issue by aldiss2** [MegaMek/mekhq#355]
Omnimech refits that should be quick reshuffling of pods are taking time equivalent to traditional mech customization.  Quick test to add an omnimech to a new campaign and customize it in megamek lab within MekHQ.  Removing an er medium laser for example will take 240 minutes.

**Comment by HammerGS** [comment]
Known issue, and its currently being worked on.

Related to
https://github.com/MegaMek/mekhq/issues/209

**Comment by neoancient** [comment]
It's not just refits. Replacing or salvaging all the pod-mounted equipment in a single location should be a single 30-minute operation. The reason this has not been done before is that MM lacked a way to distinguish between fixed and pod-mounted equipment in the unit file. That change was finished yesterday along with the changes to MML to support it. I started making the changes to MHQ to use that data today.
