### ISSUE TITLE
[49.11] NPE in Mek Lab: Resetting changes leads to a null pointer exception.

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#3554]
MekHQ 49.11
Java 11
Windows 10

Loaded a unit to the Mek lab in MekHQ, made a couple of changes, and when I clicked "Reset changes", the game threw an NPE. I can ignore it by removing the unit from the lab and keep playing, although I don't know how healthy that is.

Logs:
[megamek.log](https://github.com/MegaMek/mekhq/files/10347588/megamek.log)
[megameklab.log](https://github.com/MegaMek/mekhq/files/10347589/megameklab.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/10347591/mekhq.log)

NPE is in mekhq.log

Can provide campaign save if needed, but this happened in a fresh new campaign as well.

**Comment by Windchild292** [comment]
I cannot recreate the null return and thus the issue in question, but I do see a place where additional null protection is required.
