### ISSUE TITLE
When activating a unit from mothballed state, do not assign it to the top-level/any formation

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#3562]
When a unit is activated from mothballs, it is almost always added to the top-level formation.  This can create problems with scenario generation as deployable formations are determined by those which have units directly under them; a scenario may generate based on the overall formation BV rather than an individual lance with corresponding (and absurd) numbers and BV.

Units activated from mothballs should not be assigned to any formation by default.

**Comment by pheonixstorm** [comment]
That feature has been in for awhile, best to unassign the unit before mothballing it or to make it an option. I' have no opinion on this either way as I never mothball units during transit, unless salvaged units.

**Comment by Windchild292** [comment]
This is a MHQ option that you have selected. Closing as invalid.
