### ISSUE TITLE
RFE: cap additional adult dependents based on current admin levels

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#3570]
Every January 1st my campaign gets 80-100+ adult dependents added (current campaign is somewhere north of 800, they have a small town living in their backyard).  Kind of nice as a renewing resource for when extra personnel are needed but quickly blows out any semblance of keeping pace with required numbers of administrators.

Rather than blindly adding more adult dependents every year, it would be nice to have some kind of upper limits of what the unit can support.  This may be raw numbers of administrator personnel, and/or numbers of admin/HR members.  Either way, when January 1st rolls around dependents are only added up to the capped number.

This would not include child dependents of current members, staff, or dependents.

**Comment by pheonixstorm** [comment]
This should actually be set in the AtB tab as this is an AtB issue. And at least in Cam Ops rules they shouldn't require additional admin support. Not sure about FMMr though, I know they are handled differently in those rules.

Realistically I think AtB just needs to chill on handing out random strangers to your unit. Better to marry them off and delete the rest, maybe keep the ones with high xp values though.

**Comment by SuperStucco** [comment]
Dependents don't get a specific mention in my first printing of Campaign Operations, although they may fall under the basic "1 admin per 10 non-administrative members" even though it goes on to list combat and technical personnel but nothing else.  FM:Mr and the Supplemental doesn't have any mentions of dependents, either way.

But I do know that admin requirements go up right when all those dependents are added.  Maybe the admin requirements are not being calculated properly?  Something to check, at least.

**Comment by pheonixstorm** [comment]
In FMMr dependents give extra astech hours iirc while in CO they can affect your unit rating if you don't have enough transport for them. Neither is coded into MM, though I think I did look into giving dependents the astech hours.

For CO check p30, not sure if the page is the same for the most recent printing
For FMMr it is Mercenaries Supplemental Update p131, starts at the very bottom right.

Dependents have more of an impact under FMMr that they do in CamOps. In either one, not everything is coded into HQ for these rules.

Or, AtB just gives out too many dependents for no reason. Maybe they should be called groupies instead, chasing after your best pilots like they were a rock star.

**Comment by Thom293** [comment]
I support limiting the number of dependents and hangers-on.

**Comment by IllianiCBT** [comment]
Is this still an issue and to what extent? :)

**Comment by SuperStucco** [comment]
Haven't done any long term campaigns past 49.12, but I haven't seen any changes that would mitigate the issue.  It's not immediately obvious because most campaigns start out fairly small, which also means smaller numbers of dependents added each year.  As the size of the players force goes up, so does the number of dependents generated.  Also not very obvious until you start hitting 10-15 years into a campaign, where procreation starts having a noticeable impact on numbers of personnel thanks to exponential growth.

Because of the differences in how support requirements are calculated between the old FM:M(r) and Campaign Operations methods, the selected rating method might need to be considered in calculating how many dependents are added.

**Comment by IllianiCBT** [comment]
Are there any official rules on acquiring Dependents, do you know?

**Comment by HammerGS** [comment]
> Are there any official rules on acquiring Dependents, do you know?

None that I've ever seen, pg 30 CO has the stuff. But this is something that is going to fit into the go our own way, as CGL isn't likely to want to get into this detail. If we did implement something I'd base it off public sector size. https://en.wikipedia.org/wiki/List_of_countries_by_public_sector_size

**Comment by IllianiCBT** [comment]
That would give us a rough cap of 18% (rounded to 20% for ease of math).

**Comment by IllianiCBT** [comment]
Right now I'm thinking this:

> Dependent Slots = 20% of total unit population, sans dependents
> 
> At the beginning of each month spent on a planet friendly or neutral to the Dependents' faction, roll a d10. On the roll of a 1 the dependent leaves. If the unit is over its Dependents Slot allowance, usually due to the AtB event that adds dependents, departure rolls a d6 instead.
> 
> Also at the beginning of each month spent on a friendly or neutral planet (compared to the campaign faction) roll a d6 if there are open Dependent slots, on the roll of a 6 add a dependent (up to the cap). On a friendly planet add d3 Dependents.
