### ISSUE TITLE
Jumpship fuel calculation is using the full 30 days of burn

### ISSUE THREAD

**Issue by nutritiousemployee** [MegaMek/mekhq#3594]
### Environment
Version: 49.11
OS: Windows
Java: 17.0.1

### Description
CO page 24 states regarding fuel costs:
"DropShips and WarShips are assumed to use 15 burn-days of fuel per month, while JumpShips and space stations are assumed to use 3 burndays per month for station-keeping." 
SO page 179 lists the Hydrogen cost as 15,000 per ton

The JS in the attached savefile has the following:
  - Monthly fuel cost in the cost report: 1,778,400 C-Bill
  - Tons per burn day 3.95

3.95 tons * 3 days = 11.85
11.85 * 15,000 = 177,750 C-Bill

It looks like the actual calculation for the cost is using 30 days of fuel, instead of 3
1,778,400/15,000 = 118.56
118.56/30 days = 3.952 tons per day

### Files
[save.zip](https://github.com/MegaMek/mekhq/files/10611404/save.zip)
[customs.zip](https://github.com/MegaMek/mekhq/files/10611405/customs.zip)

**Comment by pheonixstorm** [comment]
The calculations are correct. Something else has to be off. The only possible option I can think of the tons per burn day change or you have a really off JS.

**Comment by pheonixstorm** [comment]
Per TRO Primitives III The Liberty has a TBD of 39.52, so the fuel cost is correct: 39.52 x 3 x 10,000 = 1,778,400

The bug is with the display, it shows the TBD at 10% of what it should be, or 3.95 instead of 39.52

**Comment by nutritiousemployee** [comment]
The display bug appears to be with all the Jumpships. I had a look on Sarna and all the JS values reflect the numbers you're mentioning.

**Comment by pheonixstorm** [comment]
I will have to check the remaining large craft as well to see if this only affects JumpShips or if DropShips and WarShips are also affected by this

**Comment by nutritiousemployee** [comment]
WarShips values are looking good (although I've only performed a summary check between Sarna and the value displayed for TBD, they're all either 39.52 or 19.75. Only "Bug-Eye Surveillance Ship (Standard)" has 2.82 TBD)
I can't find DropShip TBD info, but the amount paid monthly looks consistent with the TBD displayed.

**Comment by HammerGS** [comment]
Sarna isn't considered a canon source. References should always be to the TRO's

**Comment by nutritiousemployee** [comment]
Sure, but whether or not the values on Sarna are correct, the displayed values for WS and DS appear to be consistent with the calculations results

**Comment by pheonixstorm** [comment]
The calculations for fuel is here https://github.com/MegaMek/mekhq/pull/441/commits/af8d355c672b0d88583ce5c5662ea9ed583e6676

That is the fuel section of the original PR so the current code is slightly different in some areas. This is based off the values from the construction rules.

**Comment by nutritiousemployee** [comment]
This is being calculataed "wrong" in Jumpship, line 656-658
The method getStrategicFuelUse gets the correct values based on weight, but then does fuelUse *= 0.1 if the JS has station keeping drives.
Removing that last part appears to solve the issue, but I'm not sure if there's other impacts.
