### ISSUE TITLE
MHQ-J17 - NPE at end of week when advance day to Monday.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3599]
This is from todays nightly.

23:12:16,963 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:260) - Starting MekHQ v0.49.12-SNAPSHOT
	Build Date: 2023-02-12T01:37:41.488322900
	Today: 2023-02-11
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 2 GB

Advancing to Monday causes an NPE.  Did have an Ace Duel special mission trigger same day.
![Screenshot 2023-02-12 024507](https://user-images.githubusercontent.com/23645569/218301561-341101ba-008d-402f-b542-5aab474a5c88.png)

[mekhq.log](https://github.com/MegaMek/mekhq/files/10715653/mekhq.log)

[Autosave-1-Hazard Control-30600708.cpnx.gz](https://github.com/MegaMek/mekhq/files/10715650/Autosave-1-Hazard.Control-30600708.cpnx.gz)

**Comment by Thom293** [comment]
Closed the NPE and hit advance day.  Still showed Sunday and triggered NPE twice more.  Then eventually display jumped to Thrusday and say I had a defeat because I didnt deploy for Ace Duel.
![Screenshot 2023-02-12 025547](https://user-images.githubusercontent.com/23645569/218301841-00ff4692-fca8-4e7a-8a5b-c4a1f11a7fc7.png)

[mekhq.log](https://github.com/MegaMek/mekhq/files/10715669/mekhq.log)

**Comment by Thom293** [comment]
Ok, - more on this.  Tried to advance day from last save again.  Got this daily log message.  Now 2 ace duels show up in daily log, with weird dates.  Two listed in briefing tab and both were generated with no enemy.  I clicked through the NPEs each time and went to TOE and tried to assign single unit, and got an NPE for the first one, but was able to assign units to both.  Went back to briefing tab to see if it generated an enemy but it gives me an NPE if I click on either and shows nothing in the details pane now.

I have no idea if its related, but I THINK Acamar has a planetary ownership change around this time.  I have started 3 campaigns on this exact date for testing and there is always eventually a Pirate Hunting Contract on Acamar. And then the ownership changes at some point.  Again may not be related...

![Screenshot 2023-02-12 104406](https://user-images.githubusercontent.com/23645569/218324802-b641ef53-0537-4ee0-b214-75e1dce7795e.png)
![Screenshot 2023-02-12 104243](https://user-images.githubusercontent.com/23645569/218324808-a8acb69c-7449-4bc2-8921-a8f12eae7b14.png)
![Screenshot 2023-02-12 104341](https://user-images.githubusercontent.com/23645569/218324815-f826dd86-ae8a-4d6b-90da-c400cc935a38.png)
[mekhq.log](https://github.com/MegaMek/mekhq/files/10716626/mekhq.log)

**Comment by Thom293** [comment]
Sorry last thing.  I clicked through 3 days and got a new Ace Duel and NPE each day.  I delted each in the Scenario tab.  Eventually on 4th day, I got no new Ace Duel and was able to continue game normally...

**Comment by Thom293** [comment]
New contract, new planet, turn to Monday and get Ace Duel and get exception again.
[mekhq.log](https://github.com/MegaMek/mekhq/files/10730168/mekhq.log)

**Comment by PhoenixHeart512** [comment]
Just got one of these as well, logs attached.

19:09:20,798 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:260) - Starting MekHQ v0.49.12-SNAPSHOT
	Build Date: 2023-02-13T01:29:59.396044400
	Today: 2023-02-15
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.14.1
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 8 GB

(Using the Java 11 49.12 nightly)

No events or planetary ownership changes that i'm aware of, this occurred on February 24th, 3152. I am using AtB, not stratcon in this save.
[New Week NPE.zip](https://github.com/MegaMek/mekhq/files/10751320/New.Week.NPE.zip)
