### ISSUE TITLE
J17-MHQ: OOM when clicking on Market Mech

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3602]
Title.  New month popped, opened Unit market, Clicked on the first Mercury, got OOM message.  There is a fluff image of the Unit and I checked it and it is a jpg that is a middle size compared to the rest. Doesnt look irregular.

Dissmissing message and clicking on second mercury or anything else does not repeat the OOM message.

For testing purposes I keep it on whatever the minimum memory is now.  But I can turn it up if necessary.

![Screenshot 2023-02-13 224910](https://user-images.githubusercontent.com/23645569/218642823-521823c3-0fc8-4fa9-8324-86b6e6611053.png)

[mekhq.log](https://github.com/MegaMek/mekhq/files/10728873/mekhq.log)
[Autosave-1-Hazard Control-30610929.cpnx.gz](https://github.com/MegaMek/mekhq/files/10728904/Autosave-1-Hazard.Control-30610929.cpnx.gz)

**Comment by Thom293** [comment]
Accepted a contract, landed on planet, tried to do first battle, got a large number of OOM errors upon going into MM lobby and froze game/crashed.  Let me know if you need a separate bug report.

[mekhq.log](https://github.com/MegaMek/mekhq/files/10729123/mekhq.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/10729124/megamek.log)
[Autosave-1-Hazard Control-30611222.cpnx.gz](https://github.com/MegaMek/mekhq/files/10729126/Autosave-1-Hazard.Control-30611222.cpnx.gz)

**Comment by Windchild292** [comment]
Resolved multiple issues originating from this, and it appears to be that you've got too much in terms of extra image data loading in the backend for the default RAM assignment. I'd recommend using above that given that is the case.
