### ISSUE TITLE
Contracts wont generate scenarios/missions 

### ISSUE THREAD

**Issue by ALECOS44** [MegaMek/mekhq#3630]
Hello, 

Im having issues with scenario generation in MegamekHQ. 
In either generated contracts or custom-made ones the GM generate scenario is grayed out, and if it is not the generation does not work. I have run with a contract for 3 in-game months without any scenarios generated for 3 separate contracts. 
I also tried to start a new game from scratch as my current campaign was brought over from version 48, but even running a new campaign contracts are not working 

I am running version 49

![image](https://user-images.githubusercontent.com/128741015/227316885-07940044-a663-492b-a7e7-4c30768d39d8.png)
### Files
[Atrean Hoplites30520210.cpnx.gz](https://github.com/MegaMek/mekhq/files/11054843/Atrean.Hoplites30520210.cpnx.gz)

[megam
[mekhq.log](https://github.com/MegaMek/mekhq/files/11054888/mekhq.log)
ek.log](https://github.com/MegaMek/mekhq/files/11054887/megamek.log)

**Comment by ALECOS44** [comment]
Customs
[Atrean Hoplites.zip](https://github.com/MegaMek/mekhq/files/11054902/Atrean.Hoplites.zip)

**Comment by Thom293** [comment]
It appears this contact starts in June 3052 and it's only Feb 3052. 

Have you traveled to the correct planet and advanced Day?

**Comment by ALECOS44** [comment]
> [Thom293](/Thom293)

So For the one in the save that is true, but I advanced the day and it did not work
However something that did pop up was when i decided to test creating a contract starting the day I was on I got this 
![image](https://user-images.githubusercontent.com/128741015/227327281-5bf9965d-6e6e-4bfe-b1af-b9dc676ae5c8.png)

**Comment by Thom293** [comment]
I am not at computer so can't open yhe files, but generally Garrison contracts have low combat chances, I think (I have never taken one).  

My suggestion would be to close all of those other contracts, go to the contract market, generate new contracts, accept one, and then advance day and it should work.  Just don't start it same day. Give it a week or two. I have never seen MHQ use a same-day contract and that might be why you get the error. 

I dont know if that will address all of the issues, but it should get you playing.

**Comment by ALECOS44** [comment]
Awesome, thank you so much! I appreciate you taking the time to assist me with this issue, I feel dumb, but I am happy you helped me determine it is not a file issue. 
However, I'm having issues with contracts on new campaigns. I'm guessing its a settings issue, but I'm not sure why I don't have the option of creating one or accessing the contract market.

**Comment by Thom293** [comment]
Have to run, but check docs/Atb folder. I think there is a step by step Primer on how to set up company and take first contract.

**Comment by ALECOS44** [comment]
Now im having issues with the MUL, If I customize OPFOR at all the MUL won't load enemy units and counts all my units as destroyed. This started after updating to the most recent version. 
[Atrean Hoplites MUL issue.zip](https://github.com/MegaMek/mekhq/files/11057359/Atrean.Hoplites.MUL.issue.zip)

**Comment by HammerGS** [comment]
When you installed the program what unzipper did you use?

**Comment by ALECOS44** [comment]
7zip

**Comment by HammerGS** [comment]
The log has errors that I’ve seen before from bad downloads or unzipping with Windows unzipper.

**Comment by ALECOS44** [comment]
> The log has errors that I’ve seen before from bad downloads or unzipping with Windows unzipper.

Should I try a clean install and just transfer over the saves?

**Comment by HammerGS** [comment]
Or would be worth a try.

**Comment by ALECOS44** [comment]
So that definitely fixed both problems, I did not realize how off the installation was. The menu looks much better and not weirdly enlarged, missions are generating as normal, and the MULs are loading thank you for helping me solve that, it must of been how it extracted.
