### ISSUE TITLE
[49.12] Mass Mothball nolonger works

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/mekhq#3634]
Selecting more than one unit and choosing Mass Mothball from the pop-up does nothing no. No error in the log either, just a disconnected menu item.

**Comment by mjbroekman** [comment]
Okay... so it wasn't just me thinking that there were no techs available / capable of it... it really is just disconnected. Glad I wasn't imagining something...

**Comment by cjdhein** [comment]
Created pull request #3645 to fix this.
