### ISSUE TITLE
RFE: StratCon: Industrial Facility

### ISSUE THREAD

**Issue by SnyderPhilip** [MegaMek/mekhq#3639]
Currently, Industrial Facilities have no effect on the campaign track except to serve as an objective.

Proposed effect:
Allied Industrial Facility increases Campaign Parts Availability by 1
Enemy Industrial Facility increases OpFor Equipment Rating by 1

**Comment by Thom293** [comment]
I have already changed the enemy one to + equip quality and + bv in the nightly version. But I didn't change the friendly one.  I can look at it but not sure how to do campaign parts.  He suggests copying Free trader event, which is a good idea.

**Comment by IllianiCBT** [comment]
> I have already changed the enemy one to + equip quality and + bv in the nightly version. But I didn't change the friendly one. I can look at it but not sure how to do campaign parts. He suggests copying Free trader event, which is a good idea.

Were you able to take a look at Free Trader, or were there other roadblocks?

**Comment by Thom293** [comment]
> > I have already changed the enemy one to + equip quality and + bv in the nightly version. But I didn't change the friendly one. I can look at it but not sure how to do campaign parts. He suggests copying Free trader event, which is a good idea.
> 
> Were you able to take a look at Free Trader, or were there other roadblocks?

I did not.  It's on my list of things gs to look at, but I suspect it will require a little "new" code.  And I try to avoid tthat.  I'm really only a xml hack or code tweaker on my best days, unless I just get a wild hair, or get lucky.  

I'll be away another few weeks before I'm able to do anything else anyway.  You are welcome to poke this.  I think its a great idea.  

I've got a work issue that is going to

**Comment by IllianiCBT** [comment]
Closing as resolved
