### ISSUE TITLE
MekHq Calculates Naval Vee Piloting skill using Ground Vee piloting skill

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#364]
We just noticed this bug because our GM bought a bunch of ships, and they were all skill 8. Adding the skill "piloting ground vehicle" fixed the problem. "piloting naval" appears to be non-functional or at least buggy.

**Comment by neoancient** [comment]
I found this at the relevant place in the code:
`//TODO: identify naval vessel`
