### ISSUE TITLE
NPE Error while performing maintenance (on refitted unit)

### ISSUE THREAD

**Issue by AlexOldenburger** [MegaMek/mekhq#3641]
### Environment
What version of MekHQ does your issue apply to? 0.48.0
What operating system are you using?  Windows, Mac, or Linux? Windows 10
What java version are you using?  If unsure it will state your java version at the top of the mekhq.log file. 1.8.0_361

### Description
NPE Error in the log while performing maintenance on unit. The unit was recently refitted, from a Wasp WSP-1D to this Wasp WSP-1K, but no idea if that matters. 

ERROR: An error occurred performing maintenance on Unknown for unit Wasp WSP-1K, check the log

### Files
Provide the .cpnx campaign file that this issue occurs in.
And provide the megamek.log and mekhq.log files for any NPEs or errors that MekHQ might be reporting.

[Dust Devils30471002.cpnx.gz](https://github.com/MegaMek/mekhq/files/11183083/Dust.Devils30471002.cpnx.gz)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/11183089/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/11183090/mekhqlog.txt)

**Comment by repligator** [comment]
When the save is loaded under the latest nightly, the Wasp will finish being refit, and can be maintained as normal without any NPE's. Closing.
