### ISSUE TITLE
(Duplicate Issue, can be closed) Armor points seem to go to omnipod armor upon delivery and removing armor from omnipods causes error popup

### ISSUE THREAD

**Issue by Duuvian** [MegaMek/mekhq#3653]
### Environment
mekhq-windows-0.49.13-SNAPSHOT MekHQ Nightly CI number 1078 
Windows 10
Java Vendor: Eclipse Adoptium
	Java Version: 11.0.16.1

### Description
This might be two different bugs, one involving taking armor off omnipods in the parts missing menu and another that sends armor points on delivery to omnipods instead of normal usage for repairs, or it could be the same bug. I don't usually play campaigns in post-invasion eras so I'm not familiar with how omnipod armor works so perhaps it's user error, if there is a way to switch it back and forth I don't know of. This campaign is in 3023 currently.

I added a scenario template and sent the entire ToE against 1.2x bv civilian unit force to complete a bad Riot Duty contract I took while travelling back to Canopus IV with a mothballed ToE, as it was on the planet I was going to anyways to wait for a new contract or switch to Mercenary from Canopis faction, not sure when I'll do that yet. I began repairing the salvage from the riot duty contract's scenario, and noticed after a while that while  I had been ordering standard armor from the parts acuquisition menu in the repair tab I still was lacking armor for repairs. It seems upon deliveries to be putting armor points into the omnipod pool instead of normal stockpile that can be used for repairs. 

In addition there is an error message when trying to remove armor points from omnipod within the parts acquisition menu. To recreate this, open the parts acquisition menu and try to use the Remove One from Pod button in the Armor (Standard) section. The mekhq log included is from directly after this error message appears.

See points in omnipod two lines under Armor (Standard)
![armor orders](https://user-images.githubusercontent.com/84265834/235106983-b7d4a16d-b2c5-402e-8a4a-b7bfa8f53d5e.png)

The warehouse in the campaign save file showed I have 3159 points of standard armor but I can't repair armor damage with it, so it's tied up in omnipod armor as displayed on the parts missing button menu, I'd guess.

I Gm removed the entire stockpile of roughly 200 tons of standard armor in the warehouse and then gm added 40 orders (200 tons) using the purchase parts menu, but that also went into omnipod armor and can't be used.

As I mentioned in the second paragraph, this appeared to begin after I salvaged and repaired a large variety of civilian units. I don't know if my new collection of civilian units is the cause or not but that's the major difference in the campaign right before the bug was noticed. I don't think any of the salvaged vehicles (including some SVs) use omnipods; I tried to only take as salvage units that would be timeline appropriate, however I may have missed some, or accidently taken units that are Clan as I only looked only at the introduction date when selecting salvage (the civilian units sometimes pull impossible units from the future or from Clans list when they aren't in the IS yet). Sometime during the repairs and before I noticed the armor bug, I bulk recruited some ultra-green pilots for the industrial mechs (but just now remembered as I was thinking about it for this post that  I might not want to put them on the ToE even as noncombat flagged as they'll get pulled for AtB battles when I intended them to be more of a long term training cadre using the industrial mechs. I guess I could put them in training lances when contract morale is Very Low but I think that's digressing from the bug) I don't think it has something to do with placing pilots in the salvaged civilian  mechs but I mentioned it just in case as that also happened shortly before I noticed the bug.

The Jabberwocky mech has an arm that can't be ordered in the repair tab's Part Acquisition; originally the location couldn't be manually scrapped with no visible components in it when it had a bad shoulder. The daily instant repair must have scrapped it, though now there seems to be no part for ordering in the parts acquisition menu for replacing the arm despite it still sitting in the repair tab unit list of damaged units. I don't know if this is related or not to the reported bug  but it seems possible. I gm removed the Jabberwocky and afterwards armor in transit  and also gm added armor still go to omnipod armor points so that has me think the omnipod armor bug is not related to that particular unit.

### Files
No customs
[mekhq.log](https://github.com/MegaMek/mekhq/files/11352018/mekhq.log)
[Pleasurebots30231001.cpnx.gz](https://github.com/MegaMek/mekhq/files/11352019/Pleasurebots30231001.cpnx.gz)

**Comment by Duuvian** [comment]
I've found the reason for this and it's not related to a specific unit. as I thought,. I failed to check if it was pulling from a different armor pool instead of simply adding the Armor (Standard) to the omnipod pool.

Instead this is a duplicate of  #2942 as the issue is the existence of BAR armor in the warehouse overwriting the use of Armor (Standard). in repairs GM deleting the BAR armor stockpiles completely fixes the issue. It should be able to be avoided by not salvaging units with BAR armor.

I'll see if I can find the way to close this as the original poster, if it hasn't been closed not please close it as a duplicate issue and thanks.

**Comment by repligator** [comment]
Closing as requested by original submitter
