### ISSUE TITLE
Move scenario map settings from code to data

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#3658]
While most scenarios will randomly select one of the map setting XML files from the ...\data\mapgen folder, some built-in scenarios such as base defense/attack still use hard-coded map settings provided here:

https://github.com/MegaMek/mekhq/blob/e1b628c98ebcaa2816ac6e6ebe87169e7bda5de0/MekHQ/src/mekhq/campaign/mission/AtBScenario.java#L433-L453

I would like to see this small section of hard-coded information moved out to data, so it can be more easily modified.  For example, being able to switch to another file with different settings without overwriting the OOTB one, and using different naming schemes.

The scenario template XMLs already have a couple of patterns that could be followed.  The first is to provide a manifest file with flags to indicate which map settings to use for which scenarios.  Another is the scenario templates directly storing the fixed scenario modifiers, so that could be extended to include a list of map settings (both in the XML file and the scenario editor dialog), although that does not address the built-in scenarios unless those are also pulled out into scenario templates.

**Comment by NickAragua** [comment]
This is for "classic AtB", which is only supported for maintenance/bugfixes. The new "Advanced Terrain" feature of StratCon does exactly what this RFE asks, however.
