### ISSUE TITLE
Scenario Crash on Load

### ISSUE THREAD

**Issue by Faolind** [MegaMek/mekhq#3659]
### Environment
Megamek 0.49.4
Windows 10
I think I am using JDK17

### Description
This error should be reproduce-able with the savegame below. When trying to load the next mission, the scenario loader crashes on startup (see picture). This has occurred perhaps 5 times in a row, with a further 3 attempts producing the same crash but not loading the widows in the reference image seen below until I clicked on the download MUL option in MekHQ, at which point the windows in below image showed up underneath the MUL dialog. In those three instances another error box (could not not reproduce when doing screencapture for this report) showed up referencing [unable to find] the additional file linked (Wreckset.txt)

![error 1](https://user-images.githubusercontent.com/26367110/236079289-ff30ce6c-f428-4add-b3ea-c50dfcda7c20.PNG)

### Files
[wreckset.txt](https://github.com/MegaMek/mekhq/files/11392137/wreckset.txt)

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/11392117/mekhqlog.txt)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/11392118/megameklog.txt)
[The Ghost Hammers30391219.cpnx.gz](https://github.com/MegaMek/mekhq/files/11392115/The.Ghost.Hammers30391219.cpnx.gz)

**Comment by Windchild292** [comment]
MekHQ 0.49.4 does not support Java 17. Further, it is a very out of date dev release. Please immediately update to latest dev release (or 0.49.12 if you need to print record sheets), as support for Java 17 has since been added.
