### ISSUE TITLE
Issue Loading Game - Narc Pods

### ISSUE THREAD

**Issue by bryligg** [MegaMek/mekhq#3673]
### Environment
MekHQ version 0.49.12
Windows 10
Java Version 11.0.18

### Description
![image](https://github.com/MegaMek/mekhq/assets/87534745/7708e85f-2917-4ff8-9bb6-7357752a6f8c)

I am unable to load a saved game.  This has not happened before to me in this version of MegaMek, and according to the logs there is an exception being thrown due to a Narc pod on one of the mechs on the field.  I am using custom mechs, but none of them have a Narc pod, so this issue is likely with a stock mech.  I want to say the Stormcrow D, but I don't have a list of the mechs on the field handy.

### Files
[legacy.log](https://github.com/MegaMek/mekhq/files/11508116/legacy.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/11508117/megamek.log)
[Freebirth Scum.zip](https://github.com/MegaMek/mekhq/files/11508131/Freebirth.Scum.zip)
[Save1.sav.gz](https://github.com/MegaMek/mekhq/files/11508185/Save1.sav.gz)
[autosave.sav.gz](https://github.com/MegaMek/mekhq/files/11508187/autosave.sav.gz)

**Comment by IllianiCBT** [comment]
Closing as resolved
