### ISSUE TITLE
49.13 Configure Bot right click option on MHQ Briefing Tab causes NPE

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3682]
This happens in MHQ briefing tab, but not sure if it is actually MM related...

On briefing tab, if you right click a non-player force, it will give you the "configure bot" option.  Selecting a new behavior and hitting OK causes an NPE.  Selecting any preset behavior causes the NPE.  You can click out of it and continue though.

In this save, it works on all 3 battles this week, but I tried it first on the Base Attack.

[mekhq.log](https://github.com/MegaMek/mekhq/files/11581073/mekhq.log)

[megamek.log](https://github.com/MegaMek/mekhq/files/11581074/megamek.log)

[Hazard Control30640104.cpnx.gz](https://github.com/MegaMek/mekhq/files/11581082/Hazard.Control30640104.cpnx.gz)

![image](https://github.com/MegaMek/mekhq/assets/23645569/b7545992-c422-4e2e-8195-5e64a0299de2)

**Comment by NickAragua** [comment]
Fixed by MM PR #4463
