### ISSUE TITLE
49.13 Can't load saved game

### ISSUE THREAD

**Issue by Ward-B** [MegaMek/mekhq#3683]
### Environment
What version of MekHQ does your issue apply to?: 
49.13

What operating system are you using?  Windows, Mac, or Linux?
Windows

What java version are you using?  If unsure it will state your java version at the top of the mekhq.log file.
11.0.19

### Files
[mekhq.log](https://github.com/MegaMek/mekhq/files/11581335/mekhq.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/11581336/megamek.log)
[Calladin Firehawks30620726.cpnx.gz](https://github.com/MegaMek/mekhq/files/11581338/Calladin.Firehawks30620726.cpnx.gz)
[Calladin Firehawks.zip](https://github.com/MegaMek/mekhq/files/11581356/Calladin.Firehawks.zip)

### Description
When trying to load my save file, it says there's a null pointer exception. The mekhq log states something about an omnipod, which I don't use. I did, however, accidentally buy an omnipod thing for a masc 85ton 340 rating (for my custom battlemaster).

**Comment by Thom293** [comment]
To upload the custom mtfs, you can zip them and it will take the zip.

**Comment by Ward-B** [comment]
> To upload the custom mtfs, you can zip them and it will take the zip.

Ah, yeah that worked fine.
