### ISSUE TITLE
Allow units not in the TO&E to be undeployed when used as auxiliary forces

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#3688]
Using either Leadership or Tactical skill bonuses, it's possible to deploy auxiliary forces such as infantry, support and combat vehicles, and aircraft through StratCon.  I keep most of mine out of the TO&E because infantry-only and support vehicle formations just get overrun, vehicle-only formations struggle just a little too much, and I'm not currently interested in air/space combat scenarios (this gets down to there being no workable "Non-combat"/"Logistics"/etc. role so they don't get picked for scenarios, but that's another issue).

Once selected as auxiliary forces for a scenario there is no way to correct a mistake - the only "Undeploy" option is through the TO&E tab.  There should be a way to remove units that are not in the TO&E which are assigned in error.

**Comment by IllianiCBT** [comment]
We are removing the ability to assign units to the StratCon AO unless those units are in the TO&E. Furthermore, it is no longer possible to undeploy units that have accidentally been deployed to the AO, this is to avoid a number of bugs that result from deploy-undeploy functionality (mainly the occasional duplication of units or entire forces).

The introduction of the new Auxiliary role covers the need to have forces in the TO&E that won't be assigned to scenarios.

Closing as resolved.
