### ISSUE TITLE
[49.14] MekHQ not showing refits that have no Model name in Refit Kit list

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/mekhq#3695]
### Environment
megamek.MegaMek.initializeLogging(MegaMek.java:116) - Starting MegaMek v0.49.14-SNAPSHOT
	Build Date: 2023-06-09T01:44:24.482644100
	Today: 2023-06-09
	Origin Project: MegaMekLab
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 4 GB

### Description
The right click -> Refit -> Choose Refit Kit menu in MekHQ is not displaying any refit kits that don't have a Model name (such as the Clan units that had (standard) removed from their name and now have a blank model name).

I also tested this by creating a variant with a blank model name, refreshed the unit cache, and it failed to show up as well.

Screenshot example, I am unable to refit this Icestorm back to the standard version, I can only refit it to the normal "2" version (it is 2 Mk II currently after a minor refit)

![RefitBug](https://github.com/MegaMek/mekhq/assets/101755917/880b043e-4687-4490-bd5e-2ea1254480aa)

### Files
This does not seem to be tied to a save and can be seen on literally any campaign save, but if a campaign save is needed I am happy to provide one.

**Comment by repligator** [comment]
I've tested this in 50.01, and it looks like it is solved. Please re-open if this is not the case. Closing.
