### ISSUE TITLE
Remove "Pirate" as a playable faction until more/better implementation

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#3700]
In 49.12 the player selection of faction includes the option of Pirate/PIR per the ...\data\universe\factions.xml file with the "playable" tag.  However, even with adding PIR in various forms in the ...\data\universe\factionhints.xml file to specify opponents and allies, contracts are not being generated.  Issue #380 indicates that the there are other factors that need to be addressed as well.

Might be an idea to remove that "playable" tag until there is more work done on improving the playability i.e. generating contracts/missions, and with appropriate parameters.

**Comment by Windchild292** [comment]
MekHQ is a campaign management tool, with AtB being one way to use it. They are supported outside of AtB, and as such this is invalid.
