### ISSUE TITLE
RFE: Unit lists and Salvage when using manual resolution 

### ISSUE THREAD

**Issue by Skoraks** [MegaMek/mekhq#3706]
### Description
When using the "Resolve Manually" feature, it would be nice to be able to optionally load two MUL files, one for the player and one for the OpFor, when using MekHQ to track tabletop games where the scenario isn't played out in MegaMek, or generated by AtB etc. , and the player held the field (i.e. is able to collect salvage).

After the player's units' damage is applied, if they held the field the OpFor MUL could be then used to allow a GM to edit the status of the opponent's units. They could be marked as totally destroyed, escaped or salvaged for example. Any units that are marked as salvage could then have their damage edited to reflect what is left of the mech, like how the salvage works currently for an actual MegaMek game result file that is resolved manually.

It would also be great if kills could be manually assigned using this approach too.

**Comment by pheonixstorm** [comment]
Instead of Resolve Manually, start a game and recreate the opfor. Start the game and /victory. You will want to make sure the option to skip other phases is checked. End game as usually and it will send everything to HQ. Once that is done you can edit away.

**Comment by NickAragua** [comment]
If you "Save MUL" at the end of a game, it will contain the results both for every unit that participated, including player and opfor; so this feature already exists.

**Comment by Skoraks** [comment]
Thanks @pheonixstorm - this is what I am doing currently, I was just raising this as it would be nice to be able to skip that step to save a little time. But the skip phases when declaring Victory is an option I have overlooked which will help.

However there is still no way to assign kills using this approach via the GUI AFAICT

**Comment by pheonixstorm** [comment]
You would probably need to edit the damage to each unit individually to have it show up as a kill credit. And also make sure they are marked as escaped.
