### ISSUE TITLE
Github Actions Issues. 

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/mekhq#3707]
I've reached out to Watford about our failing issues with the Github actions. He's going to have a look. 

For Watford this is a link to a recent fail.
https://github.com/MegaMek/mekhq/actions/runs/5439701587

We are wondering if it could be related to this
https://github.com/MegaMek/megamek/pull/4577

We are trying to building in some testing for units that have a name change.

**Comment by HammerGS** [comment]
See also 
https://github.com/MegaMek/megamek/issues/4594

**Comment by sixlettervariables** [comment]
Not 100% sure, as 1 of the 4 runs succeeded on the MekHQ action...which is bizarre as they should "all succeed" or "all fail".
