### ISSUE TITLE
RFE: Activity Log for Coming of Age

### ISSUE THREAD

**Issue by johnboyjjb** [MegaMek/mekhq#3709]
It would be nice to have an option where an age or perhaps 2 or 3 ages could be specified when a unit member hits that target age.

Most people want to not have child warriors, choosing to have an age of 14 to enter cadet training or an ROTC type scenario.
Or having a flag when a unit member hits 18 or 21, they could be available for combat or officer training.
Finally, one could set a flag for forced retirement for non-mercenary or clan units.

Others may have other uses or intentions.

**Comment by IllianiCBT** [comment]
I've marked this as due to be closed by #4135.However that does not address 'Finally, one could set a flag for forced retirement for non-mercenary or clan units.' which really should have been posted as a separate PR.
