### ISSUE TITLE
[0.49.13] MekHQ against the bot hangs on "Advance Day"

### ISSUE THREAD

**Issue by RealTabman** [MegaMek/mekhq#3725]
### Environment
Build Date: 2023-05-23T14:36:10.295482500
	Origin Project: MekHQ
	Java Vendor: AdoptOpenJDK
	Java Version: 11.0.11
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_GB
	Total memory available to MekHQ: 4 GB

### Description
When playing against the bot inevitable after a few days the MekHQ will hang when trying to advancing one or more days.
MekHQ then can only be closed from the Taskmanager. 
Sometimes the MekHQ task uses the whole 4GB in a few seconds, while at other times it hovers around 2.5GB.
This happens with the old AtB system or the new StratCon system.
Previously it happened a few times and I was able to advance a day by completing the mission manually with the "GM Mode".
I wasn't able to do this with the uploaded save game.

I should probably also mention that this is a really old campaign. IIRC I started it with the 43.3 release.

Looks like this when MekHQ hangs. Not very helpful, I know. Sorry.
![MekHQhangs](https://github.com/MegaMek/mekhq/assets/5718054/acbc0a6d-7b7c-463c-917b-bedbbcfdb635)

### Files
Campaign save just before advancing a day:
[Autosave-1-All Sales Are Final-28630127.cpnx.gz](https://github.com/MegaMek/mekhq/files/12061989/Autosave-1-All.Sales.Are.Final-28630127.cpnx.gz)

Log files:
[legacy.log](https://github.com/MegaMek/mekhq/files/12061950/legacy.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/12061951/megamek.log)
[megameklab.log](https://github.com/MegaMek/mekhq/files/12061952/megameklab.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/12061953/mekhq.log)

Custom Mechs:
[customs.tar.gz](https://github.com/MegaMek/mekhq/files/12061968/customs.tar.gz)

Lastly, and this probably absolutely not needed, my custom camo. Just in case.
![TB_std_mek](https://github.com/MegaMek/mekhq/assets/5718054/18daabff-c7d8-44ed-8f27-4d2517a195e9) ![TB_std_mek_com](https://github.com/MegaMek/mekhq/assets/5718054/d8dcc05c-58cd-4bba-bc03-7ef6b6e1a888) ![TB_std_vehiclesA](https://github.com/MegaMek/mekhq/assets/5718054/96cfe73e-dde5-4374-a334-7ef58f9d53c0) ![TB_std_vehiclesB](https://github.com/MegaMek/mekhq/assets/5718054/ec8493ac-2efc-444f-b84f-f5b16f8cf72d) ![TB_std-2_mek](https://github.com/MegaMek/mekhq/assets/5718054/44c84b8f-4092-46b5-886a-a088103cf2bd) ![TB_std-2_mek_com](https://github.com/MegaMek/mekhq/assets/5718054/7cc579f1-a442-453e-b80b-3aba36a7e6f5) ![TB_std-3_mek](https://github.com/MegaMek/mekhq/assets/5718054/86b7582f-2132-4ea3-b17f-69714fe3a9ab) ![TB_std-3_mek_com](https://github.com/MegaMek/mekhq/assets/5718054/feef9bc1-e780-49f3-942b-186f0bd35f95)

**Comment by NickAragua** [comment]
As a workaround, you should set your planetary acquisition radius to one or two jumps tops.

**Comment by RealTabman** [comment]
Much appreciated :)
