### ISSUE TITLE
unable to load atb campaign

### ISSUE THREAD

**Issue by squidsoda** [MegaMek/mekhq#373]
Firstly you are all doing an amazing job on mekhq, 

however I am having the following issues;

I think I am using the latest stable build 
<img width="195" alt="mekhq" src="https://cloud.githubusercontent.com/assets/26926660/24707731/1b8065bc-1a58-11e7-9cbf-722b334adc6c.PNG">

I can load the pre-made campaigns, save them, and reload them fine, if I edit the campaign to atb, mekhq freezes.

I can start a new campaign however after a save I am unable to load the atb campaign.
I have to stop mekhq in task manager, I have waited up to 6 hrs to load the campaign.
In the log file I get a never ending list of units unable to be found, see below.
I can play as long as I do not save.

the campaign.zip save file will not upload here.
I get the following message
"We don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP."
here it is as a .txt file
[My Campaign30670101 - Copy.txt](https://github.com/MegaMek/mekhq/files/896297/My.Campaign30670101.-.Copy.txt)

This is the log file for the initial start new campaign with just the default atb selected,
[mekhqlog A.txt](https://github.com/MegaMek/mekhq/files/896231/mekhqlog.A.txt)

Once I try to load the campaign filemekhq appears to hang I have to exit mekhq.  log file attached  
[mekhqlog B.txt](https://github.com/MegaMek/mekhq/files/896331/mekhqlog.B.txt)

I managed to get some of the initial units unable to be found to not appear in the log by changing the format in the rat file from this:

[3053 Clan Blood Spirit Mech - Assault.txt](https://github.com/MegaMek/mekhq/files/896317/3053.Clan.Blood.Spirit.Mech.-.Assault.txt)

to this format:
[3053 Clan Blood Spirit Mech - Assault.txt](https://github.com/MegaMek/mekhq/files/896340/3053.Clan.Blood.Spirit.Mech.-.Assault.txt)

Here is the log after the changed format of the rat file.
[mekhqlog C.txt](https://github.com/MegaMek/mekhq/files/896337/mekhqlog.C.txt)

notice the lines referring to the Assault RAT (3053 Clan Blood Spirit Mech - Assault.txt) are now no longer present in the new log (log C)

log file excerpt
-----------------------------------------------------------------------------------------------------------
Load of campaign file complete!
Starting load of faction hint data from XML...
The unit Turhan Urban Combat Vehicle (Standard Armor) could not be found in the WoB Medium Vehicles (Blake Docs) RAT (WoB Medium Tank.txt)
The unit Truck (AC Conversion) could not be found in the CivilianUnits RAT (CivilianUnits.txt)
The unit Truck (SRM Conversion) could not be found in the CivilianUnits RAT (CivilianUnits.txt)
The unit Truck (AC Conversion) could not be found in the CivilianUnits_CivVeh RAT (CivilianUnits_CivVeh.txt)
The unit Truck (SRM Conversion) could not be found in the CivilianUnits_CivVeh RAT (CivilianUnits_CivVeh.txt)
---------------------------------------------------------------------------------------------------------

**Comment by HammerGS** [comment]
When you've updated from older versions how are you copying the data directory? Are you copying old versions of data into new versions?

**Comment by squidsoda** [comment]
I just unzipped the mekhq file into the folder, was I supposed to delete the data folder and download it separately?

**Comment by HammerGS** [comment]
That might be part of the issue.  Each release of the program is designed to be a standalone version. When you copy the new version over an old version there are often files in the old versions that we've deleted or altered.

So when you unzip and overwrite those files get mixed in and can cause issues. I noticed that your log file had hundreds of references to units that have had name changes, that was why I asked.

Can you try something for us.  Redownload 0.42.0 of MekHQ unzip into its own folder and then just copy any custom units and campaigns to that folder and try loading your campaign.

I suspect some of those old RATs are what is causing the crash.

**Comment by squidsoda** [comment]
Wonderful

That worked perfectly.
I can start, save and reload new atb campaigns.
Obviously only tested the basics but it fixed my issue.

Thank you

**Comment by HammerGS** [comment]
Glad it worked.
