### ISSUE TITLE
RFE - Names of Victory Points (Stratcon)

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/mekhq#3730]
This from Discord. https://discord.com/channels/458705327911731231/829058749665771571/991941908538589264

There are often comments around the confusion of the Victory points. As an example

"Color me confused as to what victory points are"
![image](https://github.com/MegaMek/megamek/assets/13752452/35e12c9f-578c-491f-a047-26f9d5765191) 
![image](https://github.com/MegaMek/megamek/assets/13752452/b20d21b2-2b88-444e-bff2-907edefb6a4d)

Experience players have answered as:

"Scenario victory points i.e. your first image are what determines what level of victory in a single scenario e.g. decisive victory, defeat, etc. Contract victory points are different and are earned from the objectives listed on the right hand side for the track."

and

"Yes it's kinda confusing. VP in battle are only relevant to that battle to determine winner or loser. VPs earned from Winning a Battle (and only certain battles) count toward your contract score and can be used to purchase support points.  i.e. even if you earn 5 VP in a battle, winning the battle will usually only award you 1 contact VP."

The suggestion to rename them - Operational Victory Points (OVP) and Campaign Victory Points. (CVP)

**Comment by IllianiCBT** [comment]
<img width="484" alt="image" src="https://github.com/MegaMek/mekhq/assets/103902653/04e1b2c3-fbaa-4e88-a3bd-54502aeb6bf8">

**Comment by HammerGS** [comment]
My ego likes "Operational Victory Points (OVP) and Campaign Victory Points. (CVP)" more  :)
