### ISSUE TITLE
[49.13] Singleblind and teams share vision

### ISSUE THREAD

**Issue by casualjoker** [MegaMek/mekhq#3737]
Pardon the formatting as this is my first ever ticket!
I have a half suggestion and half bug ticket. If there is a better place to post these please let me know.

When using the "Teams share vision" Game Option and also having an allied bot on your team with the /singleblind command turned on while using double blind it allows you to see everything that the allied bot can see, which is everything. In turn this appears to make double blind moot. Is there a way to only give /singleblind to enemy bots? Or would this make the allied bot less likely to "hunt" for the enemy units?

Thank you all for the amazing work!

**Comment by Thom293** [comment]
I have played 2 games and my allied bot did not share vision in either.  Was there a VTOL or Turrent or something that might have had vision?

**Comment by IllianiCBT** [comment]
As it's been around a year without this issue being replicated, closing as resolved.
