### ISSUE TITLE
Consistent messaging in Daily Activity Log: ComStar bill vs. C-Bill

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#3740]
In 49.12, there is a difference in messaging between prisoner ransoms:

`25,000 ComStar bill has been credited to your account for prisoner ransoms following Assassinate.`

... and battle loss compensation:
`7,290 C-Bill in battle loss compensation (parts) for Shadow Hawk SHD-2H has been credited to your account.`

There may be other cases where this is different.  I recommend settling on "C-Bills" (1 C-Bill is going to be extremely uncommon, so plural will work in almost every case) as the single term, and a general review of Activity Log messages so that it is consistent across all uses.  Possibly switching to a constant or similar value in string building.

**Comment by nutritiousemployee** [comment]
in ResolveScenarioTracker, one message is using toAmountAndNameString - name being "ComStar bill", the other toAmountAndSymbolString - with the currency symbol being "C-Bill"
I can see toAmountAndNameString being used only in 3 places (unit ransoms, prisoner ransoms and exporting finances to CSV) while the other method is used everywhere else. Might be worth to use the symbol everywhere?
