### ISSUE TITLE
[49.13] NPE: Unable to configure bot from Briefing Room

### ISSUE THREAD

**Issue by AQGadget** [MegaMek/mekhq#3743]
### Environment
MekHQ 0.49.13 using StratCon
Java 8/351 and 11.0.13 are on the PC
Windows 10

### Description
I was unable to modify the evacuating forces to actually flee instead of charge face first into the enemy from the briefing room.

Attempting to select a different bot profile or customize any behavior sliders in the briefing room generates an NPE when clicking 'Okay'. Changes are not saved

![image](https://github.com/MegaMek/mekhq/assets/17732457/59787528-2c9c-4732-b531-f9a2b787cb4d)

Bot behavior is able to be modified from the Megamek lobby

### Files
[ConfigureBotException.zip](https://github.com/MegaMek/mekhq/files/12241612/ConfigureBotException.zip)

**Comment by Thom293** [comment]
I think this was fixed in 49.14.

**Comment by AQGadget** [comment]
ah. yep. #3682
