### ISSUE TITLE
[0.49.15] Unable to Assign Pilots to Tripod Mechs

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/mekhq#3747]
### Environment
megamek.MegaMek.initializeLogging(MegaMek.java:116) - Starting MegaMek v0.49.15-SNAPSHOT
	Build Date: 2023-08-17T01:03:44.122808900
	Today: 2023-08-21
	Origin Project: MegaMekLab
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 4 GB

### Description
Unable to assign pilots to a Triskelion tripod mech. By using "hire minimum complement", mekHQ adds 2 pilots to the unit, but if I unassign one of them I am unable to reassign that exact same pilot back into the mech. Screenshot attached.

Also tested with an Ares Superheavy tripod, and I am only able to assign a tactical officer to the unit, not a pilot or gunner. In the hangar, both the Triskelion and Ares show 0/1 crew complement, instead of 0/2 and 0/3 respectively. If I use Hire Minimum Complement, the crew count changes to 3/1 for the Ares and 2/1 for the Triskelion.

### Files
File structure matches a standard MekHQ installation. Unzipping the file on top of an existing fresh MekHQ installation will place all files in the correct place automatically. I have included the custom Scenariotemplates folder since I had several pending scenarios and two of them were custom definitions.

![Tripod Pilot Bug](https://github.com/MegaMek/mekhq/assets/101755917/c07b5b65-5203-4c86-9917-d2252de3164b)

![Tripod Pilot Bug 2](https://github.com/MegaMek/mekhq/assets/101755917/283739ab-71ee-4db6-bc6b-5021c2513800)

[Tripod_Pilot_Assignment_Bug.zip](https://github.com/MegaMek/mekhq/files/12409996/Tripod_Pilot_Assignment_Bug.zip)

**Comment by PhoenixHeart512** [comment]
@NickAragua Does not appear to be resolved with the nightly build from 8/28

**Comment by Sleet01** [comment]
> @NickAragua Does not appear to be resolved with the nightly build from 8/28

It looks like the Pull Request is up but it has not been merged into master yet.
I believe this issue will get closed when that happens, so you should get notified.

**Comment by PhoenixHeart512** [comment]
Did this ever get merged? If I'm reading github correctly it was approved but never finished merging

**Comment by PhoenixHeart512** [comment]
Just realized this issue is still present in the .49.15 nightly build from 10/2 and may not be fixed, can this be re-checked? I know it's not the latest nightly, but it's several weeks after it was merged.

megamek.MegaMek.initializeLogging(MegaMek.java:118) - Starting MegaMek v0.49.15-SNAPSHOT
	Build Date: 2023-10-02T01:08:23.012828800
