### ISSUE TITLE
IndexOutOfBoundsException on removing assets.

### ISSUE THREAD

**Issue by Nikarus2370** [MegaMek/mekhq#3750]
MekHQ version 49.14 (though issue is present in earlier versions as well with same behavior)
Windows 10
Java version 11.0.18

Finances Tab > Manage Assets (GM).
Removing the last (bottom) asset in the list throws an IndexOutOfBoundsException.
Assets removed with this error will still be part of a company's "Net Worth" in the window on the right of the Finances Tab until you add a new asset, when it seems that adding a new asset forces a refresh of that window. I haven't tested to the point of if "ghost assets" have any effect on company rating or anything else.

Not a major issue and decently easily worked around. Doesn't seem to have any long term negative effect on play.

[mekhq.log](https://github.com/MegaMek/mekhq/files/12447091/mekhq.log)
[My Campaign27500101.cpnx.gz](https://github.com/MegaMek/mekhq/files/12447094/My.Campaign27500101.cpnx.gz)
![indexoutofbounds](https://github.com/MegaMek/mekhq/assets/32275242/d702a4df-554e-4150-a0cd-f2a066d25fca)

**Comment by repligator** [comment]
See #4437 . Closing.

**Comment by IllianiCBT** [comment]
Ah, thanks @repligator! I hadn't spotted we had a duplicate issue.
