### ISSUE TITLE
Ship search target numbers excessively low with Campaign Operations rating system

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#3753]
Similar to #3729, doing a ship search with the Campaign Operations overall unit rating is blowing out the numbers with a long running campaign.  Due to the calculation using the uncapped Campaign Operations rating number, as opposed to the old Field Manual: Mercenaries fixed values, it ends up with vastly off-base target numbers:

https://github.com/MegaMek/mekhq/blob/48b14323b5c43a01ffcd1909c421116653b9e1b4/MekHQ/src/mekhq/campaign/market/PersonnelMarket.java#L401-L416

As with #3729 this could be handled with clamping the rating value to the Dragoon rating enums, or separate calculations for the two unit rating systems.

**Comment by pheonixstorm** [comment]
CO uses a different formula for calculating availability for Large Craft. CO p17

CO also does not care about Logistics, Command, etc admin or unit rating.

AtB was not designed for use with CO rules at all as it wasn't even released at the time AtB as a ruleset was written. The code for AtB was designed the same way for the most part. At some point Stratcon may change that but that is a question for @NickAragua
