### ISSUE TITLE
Add weight to spare 'Mech locations

### ISSUE THREAD

**Issue by Saklad5** [MegaMek/mekhq#3759]
### Environment
MegaMek Version: MekHQ v0.49.14 Development Snapshot
Operating System: Mac
Java Version: 20.0.1

### Description
'Mech locations (such as arms, legs, heads, center torsos, etcetera) currently have a weight of 0 in MekHQ. _Campaign Operations_ specifies the weight of each part on page 213 of the third printing:

> Each limb is considered to weigh 10 percent of the total internal structure weight. The center torso weighs 25 percent, the left and right torso weigh 15 percent each, and the head weighs 5 percent.

While provided in the context of FrankenMech construction, this would logically apply to spare parts as well.

**Comment by Saklad5** [comment]
These weights apply to all 'Mechs, including tripods: their internal structure simply has 10% more weight due to having a fifth limb.

**Comment by NickAragua** [comment]
Implemented with #3766
