### ISSUE TITLE
MekHQ unselects task in repair bay/won't autoselect next patient in sickbay

### ISSUE THREAD

**Issue by JenniferinaMAD** [MegaMek/mekhq#376]
In the latest dev version (0.43.1), I ran into a small interface annoyance, two very similar instances but in different sections.

1. In the repair bay, when selecting a missing part in the purchase tab and clicking 'Do task', the part/task in question gets unselected, making repeat purchases slightly more cumbersome (e.g. if multiple jump jets were destroyed, I can't order multiple replacements with multiple 'do task' clicks without reselecting the task). In the past, the task/part stayed selected.
2. Similarly, in the medical tab, if I have multiple patients, it used to be that after selecting a doctor and a first patient, I could keep clicking 'assign' to assign multiple patients to the same doctor quickly. Now I have to select each patient before I can assign them, slowing the process significantly.

It's a minor convenience issue, rather than a true bug (since it does still all work), but I thought I should mention it anyway.

**Comment by pheonixstorm** [comment]
The repair bay issue already has an open ticket.

**Comment by neoancient** [comment]
This is also true of the warehouse tab, which is fixed in 0ebfb65.
The repair tab is fixed in accf9f5. I haven't gotten to the infirmary yet, but the fix will be the same. All three bugs result from some internal reorganization of MekHQ that uses an event system to trigger refreshes in the data, and the refreshes are happening after the selections are checked and set.

**Comment by neoancient** [comment]
The infirmary was actually a simpler problem; just a failure to fire the event when assigning a patient without selecting one first. Note also that you can select multiple individual patients by holding down the ctrl key while clicking them or a range of patients by holding down the shift key and assign or unassign them with a single click.
