### ISSUE TITLE
[0.49.15] Nightly - NPE Trying To Load Campaign 

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/mekhq#3764]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
12:46:23,787 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:260) - Starting MekHQ v0.49.15-SNAPSHOT
	Build Date: 2023-10-02T01:08:23.012828800
	Today: 2023-10-03
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 8 GB

### Description
Unable to load my campaign from the previous nightly. Year is 3156. Player location is on Northwind, on planet (mid contract)

```
12:46:33,971 ERROR [mekhq.gui.dialog.DataLoadingDialog.Task] {AWT-EventQueue-0}
mekhq.gui.dialog.DataLoadingDialog$Task.done(DataLoadingDialog.java:364) - 
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "mekhq.campaign.universe.PlanetarySystem.getPrimaryPlanet()" because the return value of "mekhq.campaign.universe.Systems.getSystemById(String)" is null
```

### Files
Zip file is structured so that it can be unzipped on top of a new MekHQ installation and all files/logs will be placed in the default location automatically.

[NPE Star Map.zip](https://github.com/MegaMek/mekhq/files/12795462/NPE.Star.Map.zip)

**Comment by HammerGS** [comment]
Fixed with https://github.com/MegaMek/mekhq/commit/4da8c84d3aece26e6fada85641ae9f8c0729e96f
