### ISSUE TITLE
Mimetic Armor should have a Technology Rating of E  (tech rating set correctly in MegaMek)

### ISSUE THREAD

**Issue by Saklad5** [MegaMek/mekhq#3765]
### Environment
MegaMek Version: MekHQ v0.49.14 Development Snapshot
Operating System: Mac
Java Version: 20.0.1

### Description
According to page 281 of the sixth printing of _TechManual_, Mimetic Armor should have a Technology Rating of E. However, MegaMek seems to give it a Tech Rating of A. This can be seen in MekHQ:
<img width="1002" alt="image" src="https://github.com/MegaMek/megamek/assets/4258823/cc072ea1-80b4-49cf-b1ba-ada1eb2254e0">

**Comment by jackreichelt** [comment]
This one has been fixed in the armor rework and can be closed.

<img width="1385" alt="image" src="https://github.com/MegaMek/mekhq/assets/723717/8c45e8b9-b695-4c4f-891d-973e2791f659">
