### ISSUE TITLE
Skills for leadership reinforcements/tactical support not using ranks but not bonuses

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#3769]
In 49.12, when using StratCon a formation leader can assign additional units as reinforcements/tactical support using their Leadership skill.  This is using only the raw ranks in the skill and ignoring any bonuses.  In the attached campaign, Bravo Lance is deployed to an Airbase - Hostile - Prevent Evac scenario.  The lance leader has 0 ranks in Leadership but a +1 bonus to the skill.  They do not have the opportunity to use the Leadership skill despite having an effective value of +1 as displayed in the personnel info box:

![Leadership - total](https://github.com/MegaMek/mekhq/assets/70451747/834b7ddd-eb7f-487f-a52f-81115dea9ca0)

This appears to apply to be the same with other skill uses such as Tactics and Strategy, which are only looking at ranks rather than ranks + bonus.

[Houston's Cowboys30380129.cpnx.gz](https://github.com/MegaMek/mekhq/files/12995757/Houston.s.Cowboys30380129.cpnx.gz)

Custom units:
[Houston's Cowboys.zip](https://github.com/MegaMek/mekhq/files/12995749/Houston.s.Cowboys.zip)
[Infantry Pack - Conventional.zip](https://github.com/MegaMek/mekhq/files/12995752/Infantry.Pack.-.Conventional.zip)
[Engineering Pack.zip](https://github.com/MegaMek/mekhq/files/12995753/Engineering.Pack.zip)

**Comment by IllianiCBT** [comment]
Closing as resolved
