### ISSUE TITLE
[0.49.15] IllegalArgumentException when loading infantry onto transport

### ISSUE THREAD

**Issue by Kromkar** [MegaMek/mekhq#3773]
### Environment
49.15
Windows 11 10.0 (amd64)
Java Version: 11.0.21

### Description
When loading four infantry units (Highlighted in screenshot) of weight 4 into a transport vehicle (Ares in same screenshot) I receive an error that makes the MegaMek window for the scenario non-responsive. I have tried loading these same units in a standalone MegaMek game and did not receive the same issue. 

### Files

[Venture Green Regiment30530808.cpnx.gz](https://github.com/MegaMek/mekhq/files/13186800/Venture.Green.Regiment30530808.cpnx.gz)

[megamek.log](https://github.com/MegaMek/mekhq/files/13186794/megamek.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/13186795/mekhq.log)
![image](https://github.com/MegaMek/mekhq/assets/4566455/e734a6bf-178b-4726-b288-a10048681f5a)
[Custom Unit Files.zip](https://github.com/MegaMek/mekhq/files/13186810/Custom.Unit.Files.zip)

**Comment by nutritiousemployee** [comment]
This is caused by one of the infantry being 4.5 tons instead of 4. bringing the total of 16.5 over the unit's 16 max.
The code could be amended for a clearer message though.

**Comment by Kromkar** [comment]
Why would one of them be 4.5 tons at all? It's the same unit.

**Comment by Kromkar** [comment]
> This is caused by one of the infantry being 4.5 tons instead of 4. bringing the total of 16.5 over the unit's 16 max. The code could be amended for a clearer message though.

What would cause 1/4 of the same infantry unit to weigh 1/2 ton more?

**Comment by RaozSpaz** [comment]
The anti-mek skill. If enough of the troops have it they will end up weighing a half ton more. Though I have [rarely] seen it happen with troops that dont have the skill and I believe its attached to something else but I cant recall what it was.

**Comment by Kromkar** [comment]
Thanks for the tip! If this error does fire it also happens to brick
MegaMek in the process still.

**Comment by nutritiousemployee** [comment]
There will be a code fix to stop that from happening in the next version :)

**Comment by Kromkar** [comment]
Awesome, thanks!

**Comment by HammerGS** [comment]
Fix with https://github.com/MegaMek/megamek/pull/4853
