### ISSUE TITLE
Thruster Maintenance on Conventional/Aerospace Fighters

### ISSUE THREAD

**Issue by yukamichi** [MegaMek/mekhq#378]
MekHQ 0.43.1 tracks maintenance/damage for thrusters on conventional and aerospace fighters, but according to Total Warfare's aerospace critical hits table conventional fighters and aerospace fighters can't take thruster hits, and their record sheets have no way of tracking thruster damage. 99% certain that thrusters are not actual equipment on these types of units.

**Comment by pheonixstorm** [comment]
TechManual p283

> Attitude Thruster (All craft) Cost 25,000 Rating C Availability is C-C-C

The maintenance in HQ is based off the advanced maintenance rules in StratOps p174
Weather or not it _should_ break though...

**Comment by neoancient** [comment]
The latest errata (v3.0) splits the aerospace section into large craft and small units, with no thrusters listed in smaller units. The small units section includes small craft, but they have to have thrusters since they can take thruster hits.
