### ISSUE TITLE
[49.16 - J17] Testing Force Commander Build

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3781]
14:28:38,290 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:260) - Starting MekHQ v0.49.16-SNAPSHOT
	Build Date: 2023-10-25T20:04:16.037901081
	Today: 2023-11-10
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.7
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 2 GB

This is testing and a save requested by @NickAragua.  For testing I used the Belligerent and Danger lances in my TOE to test.

Observations:
1.  If you are trying to set a force commander in a lance with a single superior or multiple equal ranks, it will allow you to choose among the highest rank of the lance or of the equal ranks.  So that seems to be working.
2.  It starts breaking down if you move people around though.  If I set Sgt Trillo as force commander in Danger lance, and then move him to Belligerent lance and move Lt. Kudumu to the bottom lance, I cant select the leader among the 3 Sgts now in Belligerent Lance.  If I then move Lt. Kudumu back to Belligerent Lance, then I cant select the force commander for either lance.

So I think this means there is a flag that needs to be cleared from both the Lance an the moved unit?  Otherwise it remembers who it was before and wont let you set a new one.  I would also think it might be more helpful if you can choose who the force commander is, regardless of rank.  But maybe not.

![Screenshot (77)](https://github.com/MegaMek/mekhq/assets/23645569/c219284b-50f3-4442-8330-7cd57744aa4c)

I have attached 2 saves.  The default and the one where I have started moving pilots around.

[Warpath Inc.30380201LANCELEADER.cpnx.gz](https://github.com/MegaMek/mekhq/files/13323114/Warpath.Inc.30380201LANCELEADER.cpnx.gz)
[Warpath Inc.30380201DEFAULT.cpnx.gz](https://github.com/MegaMek/mekhq/files/13323115/Warpath.Inc.30380201DEFAULT.cpnx.gz)

**Comment by Thom293** [comment]
I just realized I didn't attach customs. Will do later when I am back at computer.

**Comment by Thom293** [comment]
Customs.
[Customs.zip](https://github.com/MegaMek/mekhq/files/13323998/Customs.zip)

**Comment by NickAragua** [comment]
Need "Fortress Outpost"

**Comment by NickAragua** [comment]
Never mind, I think I figured it out, latest update to the relevant pull request should have the logic fix.

**Comment by Thom293** [comment]
Doh.  Sorry.  My computer is down but I maybe can get a link.  One sec.

**Comment by Thom293** [comment]
The Dropship is in this zip for the Hardcore Ruleset. https://discord.com/channels/458705327911731231/1125118494699159562/1167660926791593997
