### ISSUE TITLE
QoL: Campaign year selection requires >100 clicks for dark age and ilClan campaigns [0.49.15]

### ISSUE THREAD

**Issue by TimberWolfD** [MegaMek/mekhq#3784]
QoL request
Could we add a +10 year button or direct input for years in the Campaign Settings>General>Date popup? Needing 100+ clicks for current era play seems unnecessary.
![Untitled](https://github.com/MegaMek/mekhq/assets/143316586/e2ff19e5-39c9-413c-85eb-d194ba9100d4)

**Comment by JonhyBurner** [comment]
You can click on the date below and edit it. Hitting enter locks the new date.
