### ISSUE TITLE
Bug report Game not resolving

### ISSUE THREAD

**Issue by 69chrisd69123** [MegaMek/mekhq#3793]
### Environment
What version of MekHQ does your issue apply to? Version 0.49.15
What operating system are you using?  Windows
What java version are you using?  Current version

### Description
Game doesn't load to resolve victory.  I get the save for the salvage but then nothing
![image](https://github.com/MegaMek/mekhq/assets/42626937/ee237a91-7509-4b0e-8008-ad434c7ce70b)

### Files
This is not allowing me to post the cpx file for the save? Can someone email me and I will send them the files?

**Comment by HammerGS** [comment]
Please check you gave this workaround in place. 

https://bg.battletech.com/forums/index.php/topic,82935.msg1969313.html#msg1969313

Files on GitHub need to be zipped.

**Comment by 69chrisd69123** [comment]
Thanks Dave. I resolved it manually but will fix it for the next game

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
