### ISSUE TITLE
NullPointerException on Advance Day blocks date progression and duplicates scenario

### ISSUE THREAD

**Issue by DynamicWorlds** [MegaMek/mekhq#3803]
### Environment
Version 0.49.15
Windows 10 x64 AMD
Java Vendor: Oracle Corporation
Java Version: 11.0.18

### Description
Game doesn't advance date past Sunday November 11, 2790 on clicking "Advance Day" (neither on window border nor in daily activity log), though the daily activity log updates with the next day's worth of activities (including  "New scenario "Special Scenario: Prison Break" will occur on 2790-11-14.")
Tried going back to an older save and working through several days again: same result on same day.
Tried rebooting program and then computer: same result
Clicking advance day again continues to update Daily Activity Log, but fails to update date.
After a few days of doing this  the bottom of said log shows:

> New scenario "Special Scenario: Prison Break" will occur on 2790-11-14.Tuesday, November 13, 2790
> New scenario "Special Scenario: Prison Break" will occur on 2790-11-14.Wednesday, November 14, 2790
> New scenario "Special Scenario: Prison Break" will occur on 2790-11-14.

and adds a corresponding scenario to the Briefing room for each.

Saving the game after the error and reloading that save will update the date, but will continue to produce the error on advance day including adding of duplicate scenario(s) to the Briefing Room.

If date is advanced past the scenario, game resumes working as normal.

Highly suspect the scenario is the cause.

To reproduce, just click Advance Day on provided save.

### Files
[Pirates27901111.cpnx.gz](https://github.com/MegaMek/mekhq/files/13783470/Pirates27901111.cpnx.gz)
[customs.zip](https://github.com/MegaMek/mekhq/files/13783473/customs.zip)
[megamek.log](https://github.com/MegaMek/mekhq/files/13783480/megamek.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/13783481/mekhq.log)

**Comment by Gadehos** [comment]
Environment

Version 0.49.18
Windows 10 x64 AMD
Java Vendor: Oracle Corporation
Java Version: 11.0.18

Description

Game doesn't advance date past Wensday 18.9, 3067 on clicking "Advance Day" (neither on window border nor in daily activity log), though the daily activity log updates with the next day's worth of activities (including "New scenario "Special Scenario: Civilian Help" will occur on 22.09.3067")
Tried going back to an older save and working through several days again: same result on same day.
Tried rebooting program and then computer: same result
Clicking advance day again continues to update Daily Activity Log, but fails to update date.
After a few days of doing this the bottom of said log shows:

New scenario "Special Scenario: Civilian Help" will occur on 22.09.3067.
New scenario "Special Scenario: Civilian Help" will occur on 22.09.3067.
New scenario "Special Scenario: Civilian Help" will occur on 22.09.3067.

and adds a corresponding scenario to the Briefing room for each.

Saving the game after the error and reloading that save will update the date, but will continue to produce the error on advance day including adding of duplicate scenario(s) to the Briefing Room.

If date is advanced past the scenario, game resumes working as normal.

Highly suspect the scenario is the cause.


To reproduce, just click Advance Day on provided save.
[Nightwish Katafracts30670920issue.zip](https://github.com/MegaMek/mekhq/files/14832651/Nightwish.Katafracts30670920issue.zip)
[mekhq.log](https://github.com/MegaMek/mekhq/files/14832652/mekhq.log)
[megameklab.log](https://github.com/MegaMek/mekhq/files/14832653/megameklab.log)
