### ISSUE TITLE
Cannot negotiate contract terms because the game selects the highest skilled admin and not the one with the negotiating skill

### ISSUE THREAD

**Issue by Tamren** [MegaMek/mekhq#384]
If your admin has the negotiate skill you can re-roll some of the terms on each contract. However the game doesn't always select the right admin to do the negotiating. The game will pick the one with the highest administration skill to do the roll. The problem I'm having is that I have multiple logistical admins and only one of them is trained in negotiation. Since she is spending xp on two skills instead of one she lags behind the others. If I train the other admins to have a higher administration skill than my negotiator, I can no longer reroll the logistics clause on contracts at all because the highest skilled admin is not the one trained in negotiation.

So what I need is some way to designate a specific administrator to handle contract negotiations for transport/logistics/command. The contract screen could have a dropdown list that lets you pick a specific admin of each type. Another way to do this would be to add another special flag like "Dependant" or "Commander". The designated negotiator would then handle all contract rerolls regardless of skill levels (and get the XP bonus for doing so). Alternately you could simply make the game select the administrator with the highest negotiation skill because admins are not trained in negotiate by default and the one with the highest skill is probably the only one trained in negotiation at all.

**Comment by wildj79** [comment]
This is similar to #212

**Comment by purpledragon2** [comment]
As a workaround to this, I only have one of each type of admin except HR.  If I hire a multiple of either Command, Logistics, or Transport; I immediately change their primary career to HR and put a note in their bio as to which type of admin they were originally hired as.

**Comment by bandildo** [comment]
I have fixed this by changing the search criteria for calculating the re-rolls. I'm having trouble pushing my branch in order to create a pull request. It's a bit off-topic over, but do I need any special permission to be able to push into to the remote? Can't find any information anywhere, and was really hoping to contribute.

**Comment by wildj79** [comment]
@bandildo First, you would need to fork the project. Then, on your local machine, clone your fork. Create a new branch, make your changes, then push those changes to your fork. Then, issue a pull request.

**Comment by bandildo** [comment]
@wildj79 Thank you very much for the help. Got the pull request over [here](https://github.com/MegaMek/mekhq/pull/781).
