### ISSUE TITLE
[0.49.18] Unable to assign Aerospace units to a transport in the TO&E

### ISSUE THREAD

**Issue by azhais** [MegaMek/mekhq#3848]
### Environment
What version of MekHQ does your issue apply to? 0.49.18
What operating system are you using?  Windows 11
What java version are you using?  Adoptium 17

### Description
I'm unable to assign any aerospace fighter to any transport ship.
Reproduction steps:
1) start a new campaign
2) add a vengeance and a corsair (or ships of your choosing)
3) put them in the TO&E
4) try to assign

This works in .17 and doesn't in .18.   I've attached a basic atb campaign save with the above steps taken.

### Files
[AerospaceIssue30250101.cpnx.gz](https://github.com/MegaMek/mekhq/files/14324160/AerospaceIssue30250101.cpnx.gz)

**Comment by Sleet01** [comment]
@azhais This is definitely a bug, and it looks like it's related to the other Aero / AerosSpaceFighter class changes.
Using your save and some GM-added units I was able to confirm that _Non_ASF transports are working just fine.
Same with loading Conventional Fighters onto the _Vengeance_.
Only ASFs fail to load.

**Comment by Sleet01** [comment]
Single-line fix, PR will be up soon.

**Comment by Sleet01** [comment]
<img width="497" alt="image" src="https://github.com/MegaMek/mekhq/assets/22018319/4470219a-2214-47e0-86aa-4aa332df3399">

PR up, working with your save, this should be fixed in the next release.
