### ISSUE TITLE
[0.49.19] New Clan mech names preventing refit kits from showing up in Choose Configuration menu

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/mekhq#3850]
### Environment
megamek.MegaMek.initializeLogging(MegaMek.java:118) - Starting MegaMek v0.49.19-SNAPSHOT
	Build Date: 2024-02-19T01:07:54.080017200
	Today: 2024-02-19
	Origin Project: MegaMekLab
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 8 GB

### Description
Issue: Canon refit kits are not available for Clan mechs that have a split Clan/IS name

When attempting to refit a Clan mech with a split name, none of the lore refit kits show up as options. This is only affecting mechs that were created after the name change.

In my game, I have an old Timber Wolf and it is only able to see the custom designs that I created prior to the change, probably because those custom designs still have "Mad Cat (Timber Wolf)" as the full name. The new timber wolf that I GM-added to test with cannot see ANY refit kits, not my old customs nor the canon variants.

MekHQ is probably searching refit kits based on the original naming scheme and not the updated one.

In the attached files, the Mad Cat Prime ID:84 was GM-added and has the new naming scheme. All of the other mechs (and units) in my campaign existed in my hangar prior to the change, and can ONLY see my custom refit kits.

I believe this is also related to another bug I posted: https://github.com/MegaMek/mekhq/issues/3695

### Files
[Clan Unit Name MekHQ Refit Bug.zip](https://github.com/MegaMek/mekhq/files/14335243/Clan.Unit.Name.MekHQ.Refit.Bug.zip)

Newly GM-added timber wolf:
![FreshTimber](https://github.com/MegaMek/mekhq/assets/101755917/dd2950a7-52c2-4521-b617-9601a7bd09e6)

Old Timber Wolf from a previous contract prior to the name change:
![OldTimber](https://github.com/MegaMek/mekhq/assets/101755917/7ffd43c9-420e-40a2-b0a5-9f45f1affd9c)

**Comment by Thom293** [comment]
I had the same issue last night with an IS Mech, the Sunder.  Made some customizations in MML.  They show up in MHQ market just fine, but they dont show up in customization menu as options for refit.

If its unrelated, I can do a separate bug report, but maybe its something to do with Pods since both IS and Clan are effected?

![image](https://github.com/MegaMek/mekhq/assets/23645569/1f7f2a12-57de-4e25-8ce7-38757db98900)


![image](https://github.com/MegaMek/mekhq/assets/23645569/5734bac0-fcdc-415d-a4b8-c801f3c17498)

**Comment by Thom293** [comment]
Here are the refits if it helps.

[Sunders.zip](https://github.com/MegaMek/mekhq/files/14628574/Sunders.zip)

**Comment by Thom293** [comment]
I had similar Issue. Made new bug report https://github.com/MegaMek/mekhq/issues/3886

**Comment by Sleet01** [comment]
Fixed by PR #3899
