### ISSUE TITLE
[0.49.18] Display bug in 'Basic Unit Information', doesn't show aerospace units

### ISSUE THREAD

**Issue by azhais** [MegaMek/mekhq#3856]
### Environment
What version of MekHQ does your issue apply to? 0.49.18
What operating system are you using?  Windows 11
What java version are you using?  Adoptium 17

### Description
In the 'Unit Composition' display in the Basic Unit Information, aero units are not displayed in the breakdown in 0.49.18

0.49.17:
![aerodisplaybug4917](https://github.com/MegaMek/mekhq/assets/46464401/1a8515db-c6cf-46d6-87c6-417cb9983e32)
0.49.18:
![aerodisplaybug4918](https://github.com/MegaMek/mekhq/assets/46464401/09db8c4a-292b-44da-9951-54b34f797ad1)

### Files
[aerodisplaybug4917.cpnx.gz](https://github.com/MegaMek/mekhq/files/14391864/aerodisplaybug4917.cpnx.gz)

**Comment by Sleet01** [comment]
@azhais Please add your custom King Crab "KGC-RVN-1" mtf or blk file, compressed, to this issue so that we can load your save game.

**Comment by azhais** [comment]
Sorry, I just grabbed the top mech in the list and wasn't paying attention.  Here's a save with a stock KGC-0000

[aerodisplaybug4917-nocustom.cpnx.gz](https://github.com/MegaMek/mekhq/files/14392182/aerodisplaybug4917-nocustom.cpnx.gz)
