### ISSUE TITLE
MekHQ v0.49.7 Unable to assign unit for Special Mission: Civilian Help

### ISSUE THREAD

**Issue by Mr-ZenoUK** [MegaMek/mekhq#3862]
Environment
MekHQ v0.49.7
Windows 10, 22H2
Eclipse Adoptium, 11.0.22.7

### Description
While doing a Pirate Hunting job I received a mission called "Special Mission: Civilian Help".  In the description for the mission I have to assign a single unit from the TO&E to the mission.  However, no matter on who I click on the only options are "Remove Unit from TO&E", "Go to Unit in Hanger" and "Go to Pilot/Commander in Personnel".

I spoke to Mishra in Discord who recommended I submit the bug.

Files
[entitystatus.txt](https://github.com/MegaMek/mekhq/files/14467164/entitystatus.txt)
[legacy.log](https://github.com/MegaMek/mekhq/files/14467166/legacy.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/14467167/megamek.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/14467168/mekhq.log)
![TO+E issue](https://github.com/MegaMek/mekhq/assets/161900868/444f06f6-dfbe-4c67-a1ce-6ac842226dd6)

**Comment by Mr-ZenoUK** [comment]
[Suffering Rolls30350512.cpnx.gz](https://github.com/MegaMek/mekhq/files/14467185/Suffering.Rolls30350512.cpnx.gz)

The last save game file.

**Comment by IllianiCBT** [comment]
Closing as resolved
