### ISSUE TITLE
TOE 

### ISSUE THREAD

**Issue by Stm316** [MegaMek/mekhq#3873]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
I'm running (recently switched to) 0.49.18
Windows 10 64-bit
Java 17.0.4 

### Description
C.O./ranker of a unit is not displayed correctly in TOE. The ability to assign as leader only applies at company level, in 0.49.17 it was automatic. Information is not passed up the TOE tree. For example, in a regiment-battalion-company TOE (where overall commander was O7 in the only company in 1st batt [also had 2 mech batt, plus v and air] ), attached a DS to regiment (with E6 commander), TOE info box (top right) listed E6 as ranker.
![x](https://github.com/MegaMek/mekhq/assets/156564469/d34f4a98-9a91-4264-9062-553c4cb9116d)

Even removing DS from TOE and advancing a day, the E6 still displayed as overall commander.

### Files
Save game file attached. I'm using custom camo, portraits and a modified DCMS rank system, but, I don't think they are relevant to the issue.
[The Red Dragons30330722.cpnx.gz](https://github.com/MegaMek/mekhq/files/14547863/The.Red.Dragons30330722.cpnx.gz)
[mekhq.log](https://github.com/MegaMek/mekhq/files/14547970/mekhq.log)

**Comment by IllianiCBT** [comment]
Closing as resolved
