### ISSUE TITLE
[49.19] IS Omni Mech Customs not showing in Refit menu.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3886]
I had the same issue last night with an IS Mech, the Sunder. Made some customizations in MML. They show up in MHQ market just fine, but they dont show up in customization menu as options for refit.  Just to be safe I also tried with an Avatar and it didnt work either.

I tried refreshing cache and deleting units.cache and neither helped.  

Could be related to #3850 .  Maybe its something to do with Pods since both IS and Clan have issues?

![313498465-1f7f2a12-57de-4e25-8ce7-38757db98900](https://github.com/MegaMek/mekhq/assets/23645569/664e76cd-b0a4-4ec6-9a06-63f72478e4c2)

![313498394-5734bac0-fcdc-415d-a4b8-c801f3c17498](https://github.com/MegaMek/mekhq/assets/23645569/d12a4bfc-1e5f-4db7-a9a2-a78aea1ede48)

The Sunder is mothballed in the save but you can activate and see.

[Crazed Profanity30691217.cpnx.gz](https://github.com/MegaMek/mekhq/files/14628642/Crazed.Profanity30691217.cpnx.gz)

[Customs.zip](https://github.com/MegaMek/mekhq/files/14628645/Customs.zip)

**Comment by PhoenixHeart512** [comment]
Those 2 designs are not valid omnipod refits, as yours removed the Double Heatsink fixed equipment from the right arm. That is why MekHQ is not showing them in the list.
