### ISSUE TITLE
RFE: add a 'light artillery support' scenario modifier

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#3894]
At times the standard artillery scenario modifiers can be a bit overwhelming in opposition or overkill in support.  It would be nice to have a slightly less overwhelming version in play, using field artillery infantry rather than vehicles.  The lower round count makes them a little easier to fight past in opposition and not quite as obstructive when used as allies.

**Comment by Thom293** [comment]
I don't think the standard random selection can be this granular, but I can do it easily enough with a .mul. do you have a squad suggestion?

**Comment by SuperStucco** [comment]
Should be worth checking to see if the scenario modifiers will work by selecting infantry unit type while keeping the 'artillery' and 'offboard deployment' flags from the standard modifier XMLs.  It does work using the Force Generator tabs inside MegaMek which is the same system used by MekHQ.

Short of that working, doing it by MUL would be a matter of setting three infantry platoons (fairly standard company/artillery battery size) of each of the standard tube artillery.  Trouble with that is that it cannot be fine tuned e.g. more big tubes for the Lyrans, increase of artillery cannons (switching to on-map deployment) in the Republic and later eras, and so on.

**Comment by Thom293** [comment]
As far as I know there is an arty category and an infantry category. But I don't think they can be set to select infantry arty. 

But I'll look at it this weekend.  Should be able to make something work.

**Comment by Thom293** [comment]
You mean a unit like this right?  Going to work on this this weekend.  

![image](https://github.com/MegaMek/mekhq/assets/23645569/04553e0e-4550-4b61-afee-466e889e62d8)

**Comment by SuperStucco** [comment]
Exactly.  I have a number of other custom infantry with artillery on top of the few official ones.

**Comment by Thom293** [comment]
I'll add 2 different modifiers. A lance with 2 sniper and 2 LTC.  One on board and one offboard.

**Comment by Thom293** [comment]
This is done and a few others.  will push them tomorrow.
