### ISSUE TITLE
Damaged and inactive don't prompt for day advancement

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/mekhq#391]
It would be nice if we could have an option that suppresses the 'are you sure you want to advance the day' confirmation if the only units that cause it are damaged and not piloted. After a big fight with a lot of salvage, it may take a week or so to get rid of it all and the dialog is simply annoying.

**Comment by Dylan-M** [comment]
Arguably, if they're marked in "Salvage" mode, they should be ignored. If they're being repaired, then they should be assigned a tech for maintenance. :P

**Comment by Dylan-M** [comment]
Also, no need for [RFE] in the title, just assign it the "enhancement" label.

**Comment by kipstafoo** [comment]
Well, following that line of thinking, how about instead a flag that can be put on a unit of 'Not Maintained'. If it falls into disrepair, so be it.

**Comment by Dylan-M** [comment]
And then what happens when you forget to turn that flag back off?

:P

**Comment by kipstafoo** [comment]
Sucks to be you? :) How about on the 'Status' column in the hangar we add an [UN-MAINTAINED] before the status and the same thing in the repair bay?

**Comment by Dylan-M** [comment]
Or just do it the right way like I suggested :P

If the unit is just salvage it makes sense that you wouldn't maintain it. If it's being repaired for use, it makes sense that you WOULD maintain it. And, if you're repairing it prior to mothballing or selling it, you'd do the maintenance as well.

Also, less frequent maintenance cycle helps here ;)

**Comment by Dylan-M** [comment]
Oh, but the best way is to just add an unofficial option to ignore units that are being repaired or salvaged from being counted for maintenance :D

**Comment by IllianiCBT** [comment]
This was indirectly resolved a little while ago. I must have missed this RFE when pushing the PR. Nag Dialogs have been dismissible (either through MekHQ Settings, or by clicking the "don't show ago" box in the dialog itself). My PR removed the nag for units set to Salvage.

Closing as resolved.
