### ISSUE TITLE
Prevent Advancing Day When Scenario is "Due"

### ISSUE THREAD

**Issue by AaronGullickson** [MegaMek/mekhq#3929]
To prevent users from advancing the day when they should be completing a scenario with a "due" date of today, I think we should disable advancing the day when scenarios are due. Instead of advancing the day, they would get a pop-up that indicates they need to complete scenarios before advancing.

This should not be implemented until we can add the ability to change dates in the CustomizeScenarioDialog so that users can correct mistakes. This should be done by #3927

**Comment by IllianiCBT** [comment]
Current implementation has the user presented with a dialog warning that scenarios are due and will be counted as a defeat if not attended to before advancing the day. The user can then decide to ignore the warning and advance anyways.

**Comment by AaronGullickson** [comment]
Yeah, I found that code for AtB. But I am not talking about AtB. I would take all the code for AtB, dump it in a big pile and burn it if I could. I am talking about vanilla scenarios. I will make sure it doesn't conflict with AtB. This one will not be ignorable, but users will be able to change dates.
