### ISSUE TITLE
RFE:  Infirmary Nag for Untreated Patients

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3932]
TItle.  Ran across this in story arcs. athough it is unrelated to that.

An Optional daily nag just like the "You have unmaintained units, are you sure you would like to advance the day?"  or the Pending Scenario Nag.  For when you have injured people but have not assigend them to a doctor yet.  I forget to do this all of the time.

So, something like:  "You have untreated patients in the infirmary.  Are you sure you would ike to advance the day?"

**Comment by AaronGullickson** [comment]
This is a good idea. I also forget about it all the time.

**Comment by IllianiCBT** [comment]
I’ll take a look at this later
