### ISSUE TITLE
0.49.18 - MekHQ Meklab "Could not customize unit"

### ISSUE THREAD

**Issue by ThatGingerBastard** [MegaMek/mekhq#3934]
### Environment
0.49.18
Windows 11 Pro
Java: 11.0.22

### Description
Playing a Clan Wolf campaign. Attempting to customize a Timber Wolf Prime. 

I go to the Hanger tab, right click on the Timber Wolf, pick customize/customize in Mek Lab in the drop down menu. I remove the two machine guns, the medium pulse laser, and the MG ammo and swap in a flamer and 3 more double heat sinks. I assign the criticals (flamer in CT, double heat sinks in LT, RT, and RA). I change the model bracket from 'Prime' to 'OR'. 

I press 'Begin Refit', choose the first tech from the dropdown list, press OK, pop-up asks me to rename the refit I press 'submit', get the 'Proceed?' pop-up, I press 'Yes'.
I recieve a Pop-up entitled 'Could not customize unit'
with the text: "For some reason, the unit you are trying to customize cannot be loaded and so the customization was cancelled. Please report the bug with a description of the unit being customized."

### Files
[Clan Wolf99thCAMPw-ships.cpnx.gz](https://github.com/MegaMek/mekhq/files/14812831/Clan.Wolf99thCAMPw-ships.cpnx.gz)
[mekhq.log](https://github.com/MegaMek/mekhq/files/14812832/mekhq.log)
![Meklab Error1](https://github.com/MegaMek/mekhq/assets/87938250/f735ca7d-3e60-4588-abb1-7be2be986b9a)

**Comment by HammerGS** [comment]
Related to https://github.com/MegaMek/mekhq/issues/3880

Fixed for next release.
