### ISSUE TITLE
RFE:  MHQ Toughness

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3939]
We discussed this recently in another PR. 

Right now, Toughness is unusuable unless manually assigned.

As far as I can tell, Characters cannot spawn with it, and it cannot be purchased with XP.  Sometimes characters will spawn with "Toughness 0" but never with any actual points in it.

I propose it that it become a "birth" stat that they can be generated with, and that they can spawn with 0-2 points.

Purchasing via XP would be ok too, but since I view this as a "natural" stat, I think it would be better if it wasnt purchaseable.  Some people are just tough, and some are not.  But either way would be fine.

I think its control should belong here, on this campaign options tab:

![image](https://github.com/MegaMek/mekhq/assets/23645569/6a9349fa-722e-4140-87b7-f81928256537)

**Comment by JonhyBurner** [comment]
I also agree on the no on XP purchase. Either inate, and/or tied to a class, to give it some granularity? I can't remember if the RPG book has any rules like that.

Thoughness could also be improved by surviving a serious wound, perhaps with a roll to give some randomization (Thinking about the possible future changes to injuries by @IllianiCBT).

**Comment by IllianiCBT** [comment]
This would likely want to be a part of #3913.

**Comment by IllianiCBT** [comment]
Closing as resolved (manually closing to make it easier to spot what issues still need actioning).
