### ISSUE TITLE
RFE:  Exclude Units with the "Salvage" status from the "Unassigned Techs" Nag

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3941]
Just as title.

Right now, if you collect a bunch of wrecked units that  you are just salvaging, it will tringger the unassigned techs nag, which is very annoying as it can take weeks.  I propose that units with the salvage status do not trigger the Assign Tech nag.

Thank you.

**Comment by IllianiCBT** [comment]
Identical to https://github.com/MegaMek/mekhq/issues/646

**Comment by Thom293** [comment]
Closing as duplicate. I shouldda searched first.
