### ISSUE TITLE
SPAs do not appear in Pilot Info in MHQ

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#395]
MHQ 0.43.2

![2017-05-04](https://cloud.githubusercontent.com/assets/16738384/25718409/f0aee2ae-30d3-11e7-98de-874b96e31cde.png)
As you can see from screen shot. The display of SPAs doesn't work.

The data does get transferred to MM so it still works in game.

**Comment by Dylan-M** [comment]
Is this with ATB turned on? I made some major changes to internal code for SPAs, and that includes around how they get displayed. I didn't test it with ATB on, but it shouldn't matter. Still...

Also, you know better: Where's the campaign file and such for testing?

**Comment by scJazz2** [comment]
AtB is on and yeah... thanks for the spank... I do know better. Kinda rushed gotta get the kid off the bus and get his snack ready. <<<< Major Derp
[The Corp30500528.zip](https://github.com/MegaMek/mekhq/files/977228/The.Corp30500528.zip)

**Comment by scJazz2** [comment]
Yeah I do know better... ATB is on... 2 customs and 1 campaign file attached.

Rushed... got to get nephew off Bus and make his snack <<<< MAJOR STUPID

[The Corp30500528.zip](https://github.com/MegaMek/mekhq/files/977235/The.Corp30500528.zip)
[EPIC.zip](https://github.com/MegaMek/mekhq/files/977237/EPIC.zip)
[_USMC.zip](https://github.com/MegaMek/mekhq/files/977236/_USMC.zip)

**Comment by RamiusFox** [comment]
I am having this same problem with SPAs not showing on either the TO&E screen or when you look at the pilot on Personnel tab.  I do not have AtB turned on.  Attached is a test campaign with one pilot that should list Sniper for SPA.  There are no custom mechs. I couldn't tell from above comments if AtB mattered or not so I wanted to report it. 
[test Campaign30281224.zip](https://github.com/MegaMek/mekhq/files/1059233/test.Campaign30281224.zip)

**Comment by Dylan-M** [comment]
Yes, this is a known issue and one I plan on looking into in the very near future as it's related to code changes that I made. I'm not sure if I missed committing part of the changes or what, because it _was_ working for me when I tested prior to commit. It hasn't been, but then I had fixed it. So, ugh.

**Comment by molemanBT** [comment]
I seem to be able to spend xp multiple times on the same special abilities, ie if I have hopping jack, it will still show up in the list to purchase, and jumping jack won't, same with laser specialists etc, are these issues linked or does it need a new issue on here?

**Comment by Dylan-M** [comment]
I'm not sure if they're linked or not. For now just leave the comment on this issue.

**Comment by neoancient** [comment]
The old `PilotOptions` and the new `spas` hash are both there and one is being used in some places and the other in other places, but they are not sharing data.

**Comment by Dylan-M** [comment]
For now Neo just ripped out all my changes, so I have to create myself a branch where I re-apply them.

I would note that they show just fine, until you save and reload. Then they're only hidden. Which suggests to me that it's somewhere in the loading code that the bug exists.

**Comment by NickAragua** [comment]
I believe SPAs properly show up for pilots now.
