### ISSUE TITLE
Urban guerrilla & foot cavalry (prerequisites)

### ISSUE THREAD

**Issue by DynamicWorlds** [MegaMek/mekhq#3952]
### Environment
MekHQ v 0.49.17
Win 10
Java Version: 11.0.18

### Description
The spa tab says they need "veteran leadership" (twice for some reason for Urban guerrilla, but with regular small arms as the other prerequisite skill for foot cavalry) and the skills tab lists veteran leadership at 6 and regular leadership at 3.
Pg 71 of atow companion lists the prerequisites as 
Foot Cavalry: [Attributes] BOD 5+; [Traits] Fit; [Skills] Navigation/Ground 3+, Leadership 4+, Running 3+
Urban Guerrilla: [Attributes] BOD 5+; [Traits] Fit; [Skills] Leadership 4+, Stealth 3+, Streetwise/Any 3+
(the XP costs are different to mekhq costs but in line with other skills of the same cost)

I'm unsure if this is intentional or not as it seems a prohibitively expensive increase for characters in as much danger as infantry personnel.

If intended, there is no bug besides the duplication of the leadership requirement (very low priority).

![Temp](https://github.com/MegaMek/mekhq/assets/155043132/e2eec003-4534-4fac-a1a8-66cb0e83a048)
![Temp2](https://github.com/MegaMek/mekhq/assets/155043132/6e395db3-1cb1-4170-842e-b0b2acd6de9d)
![Temp3](https://github.com/MegaMek/mekhq/assets/155043132/e3e12312-5c02-4434-a3a4-e39db2948e1e)

**Comment by IllianiCBT** [comment]
Closing as resolved
