### ISSUE TITLE
Unable to replace weapon, "part not available", despite stock available in warehouse

### ISSUE THREAD

**Issue by Borgoroth** [MegaMek/mekhq#396]
Hello!

I have noticed a bug in 43.1: I have noticed on several occasions being unable to replace a missing component.

Example shows the following: Crusader CRD-3L "114" with missing Machine Gun and Medium Laser, both listed with repair status "no replacement", the two items do also appear in the acquisitions tab. 
![repair screen](https://cloud.githubusercontent.com/assets/28832062/26279929/99a145e6-3d90-11e7-8d4a-89ab43425db6.PNG)

Next Picture is the warehouse, which displays that the items above are in stock:
35 Machine Gun
44 Medium Laser
![warehouse](https://cloud.githubusercontent.com/assets/28832062/26279928/99a0521c-3d90-11e7-9df2-e6db314e91d6.PNG)

I do not recall ever encountering this problem ever before (have been playing a since the versions in the .30s)

I've included the savefile for the campaign in question. Please let me know if I can provide any additional information. 
[Armored Metal Tactical30241111.zip](https://github.com/MegaMek/mekhq/files/1016561/Armored.Metal.Tactical30241111.zip)

**Comment by NickAragua** [comment]
I have attempted to reproduce this issue using 43.2 and have not been successful in doing so. Are you still seeing it?

**Comment by neoancient** [comment]
Cannot replicate in current version.
