### ISSUE TITLE
RFE:  When New Contract is Accepted, Randomly Roll & Assign Faction Appropriate or Random Camo

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3977]
Title. 

Right now you can manually select custom camo in the edit mission dialogue.  But I always forget.  It would be flavorful, I think, if the game randomly selected a camo from the faction appropriate folder.  e.g. DC would roll a camo from the DC folder that already exists in MM, etc.

If that is too difficult, just randomly rolling any camo for Enemy and Ally from the camo folder would be fine too.  

Thank you.

**Comment by IllianiCBT** [comment]
Closing as resolved
