### ISSUE TITLE
49.19 - Bug - Double Daily Skipped battle Nags.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3979]
I am playing SC. Testing new nags by skipping battles. I have a single battle on X day. Skip it, try to advance. Get a skipped battle nag with StratCon language. Dismiss that, then Get skipped battle Nag with AtB language. Seems like I should only get one.

Load save and hit advance day and should be able to repeat.

![image](https://github.com/MegaMek/mekhq/assets/23645569/277ffe1c-918b-41de-9f5d-35d3eadcc2d5)
![image](https://github.com/MegaMek/mekhq/assets/23645569/4bc3df33-9983-4cb1-b859-6db86659fac0)

[Customs.zip](https://github.com/MegaMek/megamek/files/14896035/Customs.zip)
[Crazed Profanity30700215NAG.cpnx.gz](https://github.com/MegaMek/megamek/files/14896039/Crazed.Profanity30700215NAG.cpnx.gz)
[mekhq.log](https://github.com/MegaMek/megamek/files/14896041/mekhq.log)

**Comment by IllianiCBT** [comment]
This appears to have been fixed in 50.0. I vaguely recall a fix being pushed in 49.19.1
