### ISSUE TITLE
Display A Unit's Part Availability

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/mekhq#399]
This is something behind the scenes that is not intuitive to players and would prob be helpful to have displayed along the bottom bar of the HQ screen along with the unit rating, C-bills, etc.  Just so that it is more obvious as to why a player may not be able to acquire whatever part they are needing on a contract which HQ gives no explanation of.

![github](https://user-images.githubusercontent.com/16950832/26886048-fff9ddd0-4b69-11e7-94d7-2b36520f1c5d.png)

**Comment by BLOODWOLF333** [comment]
But looks like we would have to put in all this levels junk into the purchase parts window as well which only displays the TN right now.  Maybe this is too much of a hassle.

![github0](https://user-images.githubusercontent.com/16950832/26886419-ea6c14dc-4b6a-11e7-820e-7e9b59a0db0f.png)

**Comment by pheonixstorm** [comment]
That is only for AtB though so would also have to take that into account as well. Those numbers are useless for non-AtB play.
