### ISSUE TITLE
[0.49.19 Nightly] RFE - Set MekHQ UI default to Flat Darcula to match MegaMek and MegaMekLab defaults

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/mekhq#3995]
### Environment
0.49.19 Nightly 4/15/2024

### Description
As it says in the title, can we set the mekHQ default to Flat Darcula so that it is consistent across all 3 programs in the suite?

**Comment by HammerGS** [comment]
For Reference this PR was used in MM and MML

https://github.com/MegaMek/megamek/pull/5209

**Comment by Sleet01** [comment]
Implementation has been merged.
