### ISSUE TITLE
RFE: 49.19 - Option for Untreated Person Nag to ignore ignore prisoners.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#4001]
The untreated person nag is very useful.  Thank you.  But perhaps it could use a tweak.  This would be very similar to the maintenance ignore units set to salvage setting.

If you fight one group of infantry, your infirmary quickly becomes filled with prisoners.  And usually your doctors cant treat them all.  Especially in a new unit.  So the nag, which is otherwise very useful, becomes spammy and will trigger every day.  

So, RFE:  Have the untreated persons nag ignore prisoners.  Then it will only trigger on your people.  Thank you.

![image](https://github.com/MegaMek/mekhq/assets/23645569/add8eb5d-1b80-437e-a93e-c70671941682)

**Comment by IllianiCBT** [comment]
I agree, it's annoying, I'll get this done tomorrow
