### ISSUE TITLE
49.19 Nightly - Soft Freeze upon advancing day.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#4002]
EDIT2: Ok - well - its not even the ghost pilot issue maybe.  What worked last night - deleting the pilot or mech - inexplicably does not work this morning with the exact same process.  Frustrated, I reloaded nightly from 4.14 and loaded same save and was able to advance to monday.  So I presume now, probably incorrectly, that this is something new that was introduced by the merges yesterday.  Regardless, Im going to let someone smarter than me figure it out. Im stumped.

EDIT:  Looks like this may be related to the infamous Ghost Pilot issue.  Normally it goes away upon reload, but I had mothballed the Warhammer that he died in so I guess that preserved whatever the bug is.  Illiani isolated it to a mech or Pilot and on a hunch I checked the recently departed and his mech.  Deleting either of them allowed it to advance to Monday.

Will close this and open a new issue.  Can re-open later if needed.

Title - was advancing day. Not sure if it was from a Saturday to Sunday or Sunday to Monday.  i would guess the latter, but not certain.

EDIT:  Looks like I got an autosave, so I guess it was advancing from Sunday to Monday when it froze.  So might be some weekly roll shenanigans.  I dont see anything in the log, but it is attached.  Will try to load that autosave after I post this.  

It did not give me a NPE or other Error pop up, it just became unresponsive.  I could move my mouse and switch to other windows outside of MHQ, but none of the menus or tabs or anything in MHQ could be clicked on.  Its almost as if there is an invisibile pop-up menu waiting to be clicked and rendering the rest unresponsive.  Alt tabbing and minimizing everything else to try to find a buried window did no good.  

Log and autosave and save before autosave and customs attached.

![image](https://github.com/MegaMek/mekhq/assets/23645569/984593ad-1b70-4a15-a9bf-f65ccdeb8f23)

[mekhq.log](https://github.com/MegaMek/mekhq/files/14986571/mekhq.log)

[Autosave-1-Crazed Profanity-30700220.cpnx.gz](https://github.com/MegaMek/mekhq/files/14986593/Autosave-1-Crazed.Profanity-30700220.cpnx.gz)

[Crazed Profanity30700218a.cpnx.gz](https://github.com/MegaMek/mekhq/files/14986595/Crazed.Profanity30700218a.cpnx.gz)

[Customs.zip](https://github.com/MegaMek/mekhq/files/14986600/Customs.zip)

**Comment by Thom293** [comment]
Update - window would not close normally, so had to close with Task Manager.  

Loaded autosave and it loaded fine and I could use the mouse.  Advancing day froze it again though.  And minimizing and restoring turned the whole screen grey.  Task manager close again. New log attached.  

Log looks a little different this time.  "New thread in lounge."

![image](https://github.com/MegaMek/mekhq/assets/23645569/b177402b-1353-4228-97aa-8572a7d88b5e)

[mekhq.log](https://github.com/MegaMek/mekhq/files/14986714/mekhq.log)

**Comment by Thom293** [comment]
Oh man.  Those are wrong logs.  Its loading old saves now.  Ignore those.  Will have a good one soon.

**Comment by Thom293** [comment]
Here is correct log.  Loading the autosave above and advancing day will freeze it.

[mekhq.log](https://github.com/MegaMek/mekhq/files/14986797/mekhq.log)

**Comment by Sleet01** [comment]
A hidden or initializing modal dialog would be my guess too, and explain the issues you're seeing.

Might need to turn on debug logging to get more info.

**Comment by Thom293** [comment]
new log at debug level.

[mekhq.log](https://github.com/MegaMek/mekhq/files/14986845/mekhq.log)

**Comment by Thom293** [comment]
Ok, this save on Woodstock works.  Im able to advance through multiple mondays with no issues.  A different contract on a different planet.  But any save from day 1 of contract on Mallory's world, freezes on a monday.

[Crazed Profanity30690808.cpnx.gz](https://github.com/MegaMek/mekhq/files/14987019/Crazed.Profanity30690808.cpnx.gz)

And here is a new log with a new warning related to a missing file.

[mekhq.log](https://github.com/MegaMek/mekhq/files/14987093/mekhq.log)

**Comment by Thom293** [comment]
Looks like this may be related to the infamous Ghost Pilot issue.  Normally it goes away upon reload, but I had mothballed the Warhammer that he died in so I guess that preserved whatever the bug is.  Illiani isolated it to a mech or Pilot and on a hunch I checked the recently departed and his mech.  Deleting either of them allowed it to advance to Monday.

Will close this and open a new issue.  Can re-open this one later if needed.

**Comment by Thom293** [comment]
Ok - well - its not even the ghost pilot issue maybe.  What worked last night - deleting the pilot or mech - inexplicably does not work this morning with the exact same process.  Frustrated, I reloaded nightly from 4.14 and loaded same save and was able to advance to monday.  So I presume now, probably incorrectly, that this is something new that was introduced by the merges yesterday.  Regardless, Im going to let someone smarter than me figure it out. Im stumped.

somehow related to #4004

**Comment by IllianiCBT** [comment]
I don't know the cause, but I was able to semi-reliably replicate the bug by moving from Sunday-Monday while in a contract with units in my TOE.

This can be recreated by following the below steps:

1. start new campaign
2. create company and add units to the TOE (company generator will do this for you, if you let it, so I recommend doing that)
3. accept a contract and travel to it
4. advance days until Sunday
5. if the bug triggers, mhq will lock up when moving from Sunday to Monday

With it consistently occurring on the transition from Sunday to Monday, I'd be wanting to check into what processes run at the end/beginning of a week and whether any were changed recently. To help narrow down the issue we can be certain that it occurs after the save step - as the end of day save appears to complete correctly.

**Comment by Thom293** [comment]
Thank you for looking into it.  A nasty one that needs killing for sure.  That it can happen on a new campaign is even worse.

**Comment by IllianiCBT** [comment]
I have since been able to isolate this bug. It appears to be caused by Invincible enemy morale triggering base attacks while StratCon is enabled.

To reproduce:
- start a new campaign with StratCon enabled
- generate a company (with units in the TOE) and accept a contract
- arrive at the contract
- manually change enemy morale to Invincible
- mhq will lock-up when moving from Sunday-Monday

**Comment by kuronekochomusuke** [comment]
this looks to be getting into an infinite loop in CrewSkillUpgrader.java addSingleSPA() the while loop never exits

![image](https://github.com/MegaMek/mekhq/assets/116095479/c1998324-6d5f-411a-a60f-841bb3cfc9de)

**Comment by Sleet01** [comment]
@kuronekochomusuke damn.  I'll take a look.

**Comment by Sleet01** [comment]
@kuronekochomusuke @IllianiCBT @Thom293 ^^^ fix for the infinite loop I introduced.
I doubt that this fixes the ghost pilot issue, however.
