### ISSUE TITLE
RFE / 49.18 : Stratcon Difficulty Controls / Situation

### ISSUE THREAD

**Issue by RaozSpaz** [MegaMek/mekhq#4011]
### Environment
49.18 [applies to all stratcon versions though technically]
Windows
Java 11

### Description
Ive heard a few players talk about the overall situation with BV and deployment in Stratcon [there are also problems with AtB but that is why we push for Stratcon no?] where players have issues dealing with the various situations/forces thrown at them. Lets break it down a little.
At a glance most if not all deployments start out utilizing 100% of the player's BV as the deciding factor for the forces that it deploys to any mission. This typically would create a mostly fair fight, but there are other situations that typically effect a battle.
1 - The chance that a force will be 'larger than normal'. Sure you will be given princess allies, but this typically doesn't help much to counteract the increased amount of forces on the enemy team.
2 - Facilities. The various facilities can impact the forces deployed either by straight adding more forces or creating modifiers that enhance their strength or BV. 
3 - Random other modifiers - These additional modifiers can further complicate things by adding even MORE forces, further padding BV, etc etc. 

All of this combined can create situations where there are multiple battles in a row that are forever against the player. If one arrives at a contract and there are multiple hidden enemy facilities, it can be a steep hill to climb if at all. Now there is an understanding to be losing a battle here and there. That is the natural course of things. But getting a mission and seeing TONs of stacking mods thrown against you makes things frustrating for several players.

**POSSIBLE PROPOSED SOLUTIONS**

These aren't super thoroughly thought out but are some simple things I thought of when discussing things with Thom and Illiani in regards to the issue.

Larger Than Normal Force: Im not certain exactly how to fix this. Im not 100% certain what it is but man there are times it feels like it always spawns. I know it doesnt but it is pretty common.
Facilities: Personally having facilities only effect combats near them would be a major changing point towards fixing them. Especially cause then it also wouldn't revert the contract to being overly simple should you take them all over.
Random Modifiers: Toning these down seems to be the easiest way to solve this problem. Whether it be through increasing positive mods, or just bringing the tone down for mods appearing at all. 
General BV: As discussed in the Stratcon section for discord, something along the lines of a BV slider would be useful for players who want a more toned down experience. It wouldn't create the optimum ups and downs that a lot of players look forward to, but it could help solve a lot of the issues players have with the current deployments.

Regardless, I would love further discussion and thought on this.

**Comment by Thom293** [comment]
A quick band aid would be to allow the maximum number of modifiers be configurable.  Right now the default maximum is 3. Allowing people to turn it up or down would help with a customized experience.

**Comment by Profugo-Barbatus** [comment]
> Facilities: Personally having facilities only effect combats near them would be a major changing point towards fixing them.
I really like this, as it'd also make scouting a lot more effective and enjoyable. Rather than blindly stumbling about until you find a facility, you'd know your close once it starts influencing the fights along the way.

**Comment by SuperStucco** [comment]
The facility distance bit is a decent idea; along with where reinforcements show up, it might also include such things like response/arrival turn time and how far from the board offboard artillery is located.

One point I think that is missing, is that there needs to be a large scale re-balancing to consider all of the modifiers now potentially present.  What was only a few potential scenario modifiers has now expanded greatly with more, different, and more difficult ones plus additional factors such as biomes/environmental challenges and facility modifiers which could be more difficult than intended.  This would involve generating several large samples of randomly generated potential situations and giving them a once over to see whether it is overall decent or could use some tweaking.  And a few deliberately constructed extreme situations to see just how bad it could get (both for and against the player) and whether there needs to be changes made to tone down or prevent such combinations.

**Comment by RaozSpaz** [comment]
Yeah. I mentioned the toning down of modifiers in my main post. They definitely are incredibly prevalent, and when the BV is always based on yours it means any negative modifier is a problem.

**Comment by AaronGullickson** [comment]
The reason for the Larger than Normal force has to do with how the generator works. It assigns units in the specified "lance" size and only checks to make sure it has not gone over the target number of points. So lets say you the player have a lance of medium mechs. It might generate a lance of light mechs and then see that it has not matched you, so it generates another lance but this time it gets a heavy lance. It looks and sees its over the target number and so it says "good enough." Now your medium lance is facing two lances and probably out-BVs you by a wide margin. 

I just put in PR #4037 which should fix this in the BotForceRandomizer. Basically, it will instead try to find an acceptable range around the target number of points and reject generated forces that are both too small *and* too large. So, it should fix that problem except for the minor problem that AtB doesn't actually use BotForceRandomizer yet. But we will get there hopefully soon.
