### ISSUE TITLE
Bug: owned/allied aerospace units in generated "Space - Blockade Run escort Mission" appear to behave as if on groundmap. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4017]
### Environment
MekHQ bundle 0.49.19.
Running Microsoft Windows 11 Home, version 10.0.22631 Build 22631
Eclipse Temurin (jdk-17.0.8.1+1)

### Description
MekHQ campaign save generated a Space - Blockade Run Escort event. 
Pulled a non-TOE dropship of mine to generate it, and I deployed a fighter lance to engage.
The mission was not otherwise altered.

![image](https://github.com/MegaMek/mekhq/assets/141160646/978e49d4-c50c-400d-8556-d230007f92c5)

Once engaged, I was puzzled by the following:

- Despite being marked as space terrain, the map seemed to be either a groundmap or a low-atmo map. The map specified is: "80x60 - Fulda Gap". I suspect this is not an appropriate space terrain map and is partially responsivle for the oddities. 

- The dropship deployed landed as if on a ground map. 

- My craft as well as that of allies behaved like they were on a groundmap. This included only being able to make 'ground attacks' on enemy aircraft, which were also only visible directly on the flight path, or directly adjacent to the flight path, which is the same sensor behaviour my craft have on groundmaps using double blind rules. They would even lose one altitude while attacking. I had minimum thrust expenditure requirements as I would on a ground map.

- Enemy craft behaved with aerospace rules as far as I could tell; they didn't or barely moved (e.g. only a few hexes, as is using aerospace thrust moves), and seemed able to shoot me while also using those rulesets.

- I have several advanced Aerospace rules from StartCon turned on. This may or may not matter.

### Files
[Campaign Save.zip](https://github.com/MegaMek/mekhq/files/15056051/Campaign.Save.zip)

File attached is a campaign save. Since this pertails only to non-custom aerospace units, I removed all my Mechs, many of which were customs. The mission is present and immediately playable in the save. 

[mekhq.log](https://github.com/MegaMek/mekhq/files/15056056/mekhq.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/15056057/megamek.log)

**Comment by kuronekochomusuke** [comment]
Was the "Space - Blockade Run Escort" scenario generated in a prior version?

A work around for this is to set the map to space once in megamek.
