### ISSUE TITLE
[0.43.2-git : Bug] mekhqlog.txt Size Causing Performance Issue

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#402]
Load campaign, mekhqlog.txt = 28,208 KB. 

Go to 'Repair Bay', make 1 armor repair with 'Rush Job (1/2)' to e.g. Moonsoon with, mekhqlog.txt = 129,842 KB.

No errors in the log file, just information for debugging(?) such as checking <crew name> and adding <unit name> to unit counts.

Make another armor repair with the same setting, mekhqlog.txt = 206,180 KB.

Basically almost everything that I do, I will have to wait for quite a few seconds before it will take effect.

Attached campaign and custom file for testing.

**Comment by SirMegaV** [comment]
[mekhqlog.txt Size Causing Performance Issue.7z.txt](https://github.com/MegaMek/mekhq/files/1083885/mekhqlog.txt.Size.Causing.Performance.Issue.7z.txt)

**Comment by NickAragua** [comment]
Missing a unit called "Command Van (Standard)".

**Comment by NickAragua** [comment]
That is an impressively large save game file, though. How many game years have you run this thing through?

**Comment by SirMegaV** [comment]
Command Van missing? Will check it out.

Starter at 2400 now 2505.. 105 years? :)

**Comment by SirMegaV** [comment]
@NickAragua, what do you mean by missing unit "Command Van (Standard)"? It can be found in the "purchase unit" window.

**Comment by HammerGS** [comment]
Might me a custom unit for you.

**Comment by NickAragua** [comment]
Correct, the Command Van (Standard) appears to be a custom unit.

**Comment by SirMegaV** [comment]
The blk file is located under unofficial.zip/vehicles/Others/Command Van.blk

**Comment by neoancient** [comment]
@NickAragua The MekHQ packaging utility builds the distribution using the data files from the MegaMek repository. While we occasionally update the HQ repository, it is usually several months behind MM, and changes in the unit files, RATs, unit sprites, etc. may not be available when you run it in Eclipse.

[Command Van.blk.zip](https://github.com/MegaMek/mekhq/files/1165848/Command.Van.blk.zip)

**Comment by NickAragua** [comment]
Ah, thanks. Did not know that.

**Comment by NickAragua** [comment]
Three months later, it's fixed! (in the upcoming nightly builds only)

**Comment by NickAragua** [comment]
Should be fixed with PR #415
