### ISSUE TITLE
RFE Awards Suggestions

### ISSUE THREAD

**Issue by rroby1** [MegaMek/mekhq#4024]
The awards change currently in process is some thing I have been waiting on for ever since awards were added. This RFE is also related to awards. 

Currently there are awards within the standard set which can be awarded to an individual multiple times. However nothing changes visually with the award ribbon or medal. The US military awards has devices which are added to the ribbon / medal for each subsequent award of the same medal. Depending on the medal this is either a gold star or bronze star, with 5 gold stars being replaced by a silver star. Numerals are also used for some awards. There are a pretty large number of different devices which can be used.  

This RFE asks that these devices be visually represented for subsequent awards of the same award. I've added an image as an example of some of the devices which could be used. 

![awards](https://github.com/MegaMek/mekhq/assets/61069665/e479c6c8-d517-4fae-8c84-2cd1d88b92ec)

**Comment by IllianiCBT** [comment]
This functionality will be added to autoAwards later today

**Comment by rroby1** [comment]
> This functionality will be added to autoAwards later today

Awesome!  I look forward to this!
