### ISSUE TITLE
RFE 49.19 / Stratcon : Possible Idea for Industrial Centers lack of benefits

### ISSUE THREAD

**Issue by RaozSpaz** [MegaMek/mekhq#4036]
### Environment
49.19+
Windows
Java 11

### Description
In the current standing for Industrial Centers, they provide no benefit to the player [and thus incentive to keep alive] which really feels very counterproductive to the whole point of 'doing your job' and defending them properly. Brought up in Joker's stream was an idea of making Industrial Centers increase Campaign Availability by +1 as long as they are held. Probably only a +1 as long as one is held and not +1 per. 

Another option that was brought up in the stream were increasing repair tier.

### Files
RFE. No files needed.

**Comment by HammerGS** [comment]
I think repair tier makes more sense. Availability is going to be driven but the quality of the world. A backwaters world isn't suddenly gonna have Clan Parts, but would have factories that could be adapted to repair.

**Comment by Thom293** [comment]
Related: https://github.com/MegaMek/mekhq/issues/3639

**Comment by RaozSpaz** [comment]
> Related: #3639

How in the world did I miss this XD Apologies. I wouldn't of posted this if I saw that.

**Comment by Thom293** [comment]
well, its a good idea.  i did look at it and its just a bit beyond my comfort zone so need to wait for someone else to take it.

**Comment by IllianiCBT** [comment]
Closing as resolved
