### ISSUE TITLE
Change pop ups for command rights

### ISSUE THREAD

**Issue by molemanBT** [MegaMek/mekhq#4042]
Suggestion to change pop up information on command rights in MHQ:

NB, I think VP has changed name now? Not sure what to EDIT These are all Campaign VPs, edited as such

Integrated - You are required to keep your Campaign VP count positive. Every time you win a scenario, you will gain +1 CVP. Every time you lose a scenario, -1 CVP. Your employer chooses and deploys your lance on missions. You cannot scout the map, or reinforce the lance that has been chosen. You must complete the entire duration of the contract.

House - You are required to keep your CVP count positive. Every time you win a scenario which you didn't initiate, you will gain +1 VP. Every time you lose a scenario you didn't initiate, -1 CVP. You choose which lance to deploy. You can scout the map and reinforce. You must complete the entire duration of the contract.

Liaison - You are required to keep your CVP count positive AND you are responsible for completing the given number of strategic objectives, CVPs are only affected by scenarios in which a liaison participates. You choose which lance to deploy. You must scout the map to find objectives. You may reinforce. If you complete the contracted objectives, you may finish the contract early, unless the mission type is Garrison or Cadre.

Independent - You are only responsible for completing strategic objectives. Where, when and who you deploy is up to you. Your final CVP score doesn't matter. You must scout the map to find objectives. You may reinforce. If you complete the contracted objectives, you may finish the contract early, unless the mission type is Garrison or Cadre.

**Comment by SuperStucco** [comment]
> Integrated - You are required to keep your Campaign VP count positive. Every time you win a scenario, you will gain +1 CVP. Every time you lose a scenario, -1 CVP. Your employer chooses and deploys your lance on missions. You cannot scout the map, or **reinforce the lance that has been chosen**. You must complete the entire duration of the contract.

Both reinforcements and leadership reinforcements/tactical support can be deployed with Integrated and House command rights, from the StratCon map (unless that's been changed in recent releases?).  There are times when scenarios are not placed on the StratCon map but that should be considered a bug.


> Liaison - You are required to keep your CVP count positive AND you are responsible for completing the given number of strategic objectives, CVPs are only affected by scenarios in which a liaison participates. You choose which lance to deploy. You must scout the map to find objectives. You may reinforce. **If you complete the contracted objectives, you may finish the contract early, unless the mission type is Garrison or Cadre.**

On defensive contracts/missions with less restrictive command rights, there are objectives that indicate the date it must be held until.  So the actual type doesn't matter as it's covered under meeting objectives.

**Comment by IllianiCBT** [comment]
If someone can provide me with an exact wording for how the tooltips should read, I'd be happy to push an update to close this RFE off.
