### ISSUE TITLE
49.19 Inf Unit in Personnel Market is causing Java Issue

### ISSUE THREAD

**Issue by demster42** [MegaMek/mekhq#4045]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
MHQ 49.19
Windows 11
11.0.17

### Description
Every time I try to advance the day I get the error.  It won't advance but adds another unit.

### Files

[mekhq.log](https://github.com/MegaMek/mekhq/files/15182037/mekhq.log)
[Tough Cluff's30901220.cpnx.gz](https://github.com/MegaMek/mekhq/files/15182038/Tough.Cluff.s30901220.cpnx.gz)

**Comment by IllianiCBT** [comment]
This appears resolved as of 50.0. I suspect it was fixed by one of the many fixes we pushed in 49.19.1. If you're still using 49.19.0, I strongly recommend updating to 49.19.1 (our latest milestone, at time of writing).
