### ISSUE TITLE
Temperature is incorrectly set in Scenario

### ISSUE THREAD

**Issue by AaronGullickson** [MegaMek/mekhq#4051]
The default temperature setting in `Scenario` is 25. However all scenarios are defaulting to a temperature of zero instead. This is because planetary conditions are actually being set from a variable called `modifiedTemperature` rather than `temperature`. This `modifiedTemperature` variable however is never set in Scenario and so it gets the default integer value of zero. I believe this code is part of @kuronekochomusuke's work on varying planetary conditions in AtB scenarios. It is a classic example of AtB logic interfering with generic classes.

This could be easily fixed by just adding `modifiedTemperature = 25` to the `Scenario` constructor. However, I would like to think more about why we need both a `temperature` and a `modifiedTemperature` variable at all and whether there might be a better way to fix this issue. I find it confusing and non-intuitive and I don't know how it all works together. If temperature is being modified somehow, why not just write the modified temperature back onto the `temperature` variable?

**Comment by kuronekochomusuke** [comment]
this should be in AtBScenario.  It is used to override the temperature when snow is used, the override temperature is set to a value valid for snow .  the original temperature is left along, so that if a reroll is used it uses it, weather is set based on the original instead of the overridden version.
