### ISSUE TITLE
[0.49.19] NPE, "Could not find a mech summary"

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4057]
Edited - Still present in latest nightly

### Environment
Nightly 2024-05-23T01:11:31.212783451, Linux, Java 17.0.10

### Description
I used the 'Purchase Unit' option to purchase a new unit. Got an NPE, logs show "Could not find a mech summary". Save file and logs are attached.
[mekhq.log](https://github.com/MegaMek/mekhq/files/15225825/mekhq.log)
[3151Bears31510511.cpnx.gz](https://github.com/MegaMek/mekhq/files/15225829/3151Bears31510511.cpnx.gz)
[Autosave-1-GBD3098-31020730.cpnx.gz](https://github.com/MegaMek/mekhq/files/15225854/Autosave-1-GBD3098-31020730.cpnx.gz)
[Autosave-2-GBD3098-31020729.cpnx.gz](https://github.com/MegaMek/mekhq/files/15225855/Autosave-2-GBD3098-31020729.cpnx.gz)

**Comment by repligator** [comment]
Woops, wrong save file.
[GBD309831020731.cpnx.gz](https://github.com/MegaMek/mekhq/files/15225868/GBD309831020731.cpnx.gz)

**Comment by HammerGS** [comment]
From log

```
15:54:03,457 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$0(MekHQ.java:242) - Uncaught Exception Detected
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:209)
	at mekhq.campaign.Quartermaster.buyUnit(Quartermaster.java:467)
	at mekhq.campaign.unit.UnitOrder.find(UnitOrder.java:184)
	at mekhq.campaign.Campaign.acquireEquipment(Campaign.java:2539)
	at mekhq.campaign.Campaign.goShoppingByPlanet(Campaign.java:2332)
	at mekhq.campaign.Campaign.goShopping(Campaign.java:2196)
	at mekhq.campaign.Campaign.newDay(Campaign.java:3511)
	at mekhq.campaign.CampaignController.advanceDay(CampaignController.java:82)
	at mekhq.gui.CampaignGUI.lambda$initTopButtons$59(CampaignGUI.java:1067)
```

**Comment by repligator** [comment]
New save/logs from nightly
[mekhq.log](https://github.com/MegaMek/mekhq/files/15416435/mekhq.log)
[Rho Galaxy30740319.cpnx.gz](https://github.com/MegaMek/mekhq/files/15416444/Rho.Galaxy30740319.cpnx.gz)
[Rho Galaxy30740320.cpnx.gz](https://github.com/MegaMek/mekhq/files/15416445/Rho.Galaxy30740320.cpnx.gz)
[Rho Galaxy30740321.cpnx.gz](https://github.com/MegaMek/mekhq/files/15416447/Rho.Galaxy30740321.cpnx.gz)

**Comment by repligator** [comment]
By deleting the order for a Ryoken (Stormcrow) G (editing the save file using a text editor) I've been able to create a good save file that I've used to test buying various mechs with mixed results.
[Rho Galaxy30740322 GOOD.cpnx.gz](https://github.com/MegaMek/mekhq/files/15416721/Rho.Galaxy30740322.GOOD.cpnx.gz)

Trying to purchase the following units throws an NPE
Ryoken (Stormcrow) Prime
Ryoken (Stormcrow) G
Ryoken (Stormcrow) Attwater
Gladiatior (Executioner) TC
Mad Cat (Timber Wolf) Prime

Trying to purchase the following units does **not** throw an NPE
Supernova 3
Urbanmech IIC
Urbanmech IIC 2
Turkina B
Annihilator C 'Gaussszilla'
Mad Cat Mk II

This leads me to believe that the issue is related to _sphere name (clan name)_ system some how.
