### ISSUE TITLE
Incorrect field naming in Customize Scenario Objective

### ISSUE THREAD

**Issue by sldfgunslinger2766** [MegaMek/mekhq#4079]
Build Date: 2024-05-13T22:23:40.539878300
Today: 2024-05-13
Origin Project: MekHQ
Java Vendor: Eclipse Adoptium
Java Version: 11.0.20
Platform: Windows 10 10.0 (amd64)
System Locale: en_US
Total memory available to MekHQ: 2 GB
Version: MekHQ 0.40.20-Snapshot

<img width="612" alt="Failure" src="https://github.com/MegaMek/mekhq/assets/40328392/62c5eeac-4360-46c7-a994-45cd6179b794">

The underlined text field should be changed to 'Effects on Failure'

**Comment by repligator** [comment]
Appears to be resolved as of the latest nightly.
