### ISSUE TITLE
RFE: Remove Child Marriage and Knocked Up Children Flags

### ISSUE THREAD

**Issue by johnboyjjb** [MegaMek/mekhq#4080]
Not sure it works this way, as I've not seen any pregnant and married 4 year olds, but it looks like they can be flagged for marriage and pregnancy by default. 
![Screenshot 2024-05-14 122538](https://github.com/MegaMek/mekhq/assets/75278541/e8559007-bb47-4265-9599-8500cc9d99a0)
I have not changed any settings on this person. There may be other calculations which prevent the marriage calculation and the pregnancy calculation from picking these up. It does look like I cannot force them to be pregnant until they turn 14, which I guess is good. 
Maybe mask the flag until target age or just don't care since it appears to be only a flag problem.

**Comment by IllianiCBT** [comment]
I already have a PR open to address child pregnancy. I'll take a look into this later tonight (writing documentation atm).

**Comment by johnboyjjb** [comment]
Apologies. I guess my searching abilities on github suck. Though I guess I did focus on the marriage part first.

**Comment by IllianiCBT** [comment]
> Apologies. I guess my searching abilities on github suck. Though I guess I did focus on the marriage part first.

No apology necessary, your suggestion here isn't a part of my PR, so it's a good addition

**Comment by IllianiCBT** [comment]
After thorough internal deliberation on this matter, we acknowledge your perspective, but presently, we've decided against concealing these flags.

While these flags remain inactive during a person's underage period, concealing them poses a challenge: users cannot deactivate the flag until _after_ the individual reaches the appropriate age. Something that would be difficult for users to track.

Our solution involves revising the tooltips associated with these flags, explicitly indicating the age at which personnel become eligible for marriage or reproduction.
