### ISSUE TITLE
[0.49.19] RFE: option to default show expanded log sections on Personnel tab

### ISSUE THREAD

**Issue by ObviousTech** [MegaMek/mekhq#4083]
### Environment
mekhq 0.49.19 and later

### Description
Recently the details section for the select person on the Personnel tab was changed to group log types.  This hides all of the details in sections which you must click the header of to expand.

It would be convenient to be able to have the option to have all (or some, selectively?) of these sections expanded by default in order to view the info without having to click several times per person.

The section as it loads currently:
![personnel hidden](https://github.com/MegaMek/mekhq/assets/1627342/1756990f-4414-4355-908c-019b7b0cad35)

### Files
any mekhq save file with any amount of history on the personnel would work

**Comment by IllianiCBT** [comment]
The hardest part of this would be figuring where to stick the campaign options. I'll see it done.
