### ISSUE TITLE
RFE: Continue Campaign button on MekHQ

### ISSUE THREAD

**Issue by BlueThing00** [MegaMek/mekhq#4089]
### Environment
All

### Description
I'd like to see a Continue Campaign button for MekHQ that simply loads the most recent campaign save in the save game folder.

I know it only saves a few clicks, but it would be a nice minor QOL improvement.  :)

**Comment by Sleet01** [comment]
I believe that is what this button does:

<img width="754" alt="image" src="https://github.com/MegaMek/mekhq/assets/22018319/db23e1e0-3f20-4d5d-8b90-23e9063a7a41">

It should be available in more recent releases; what version are you running?

**Comment by BlueThing00** [comment]
Somehow I missed that...

**Comment by Sleet01** [comment]
> Somehow I missed that...

I only knew because I had to fix something related to it -_-;

**Comment by BlueThing00** [comment]
This can just get closed.

I'm glad I just went to the eye doctor, because he can confirm that I'm not blind...  ;)
