### ISSUE TITLE
Add hyperlinks to personnel log entries and/or person panel

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/mekhq#41]
It would be nice to add the ability to hyperlink units, spouse names, or mission/scenario names.
It would also be nice to do the same in the person panel a spouse as well.

**Comment by donlindsay** [comment]
As far as I know, you can put hyperlink tags in the personnel logs.

**Comment by donlindsay** [comment]
It's possible that a context pane would be simpler to implement than a linking system and provide most of that info. 
![context-panel](https://cloud.githubusercontent.com/assets/156800/18484263/90310acc-799c-11e6-8190-16699c1884ff.png)

**Comment by donlindsay** [comment]
A context panel that provides a pre-set list of related records 
![context-panel2](https://cloud.githubusercontent.com/assets/156800/18484627/1dc2f80e-799e-11e6-88ab-888f6c71db66.png)
might do so of that, and possibly be more realistic to code.

**Comment by pheonixstorm** [comment]
It would still require the same amount of work if not more.

**Comment by donlindsay** [comment]
Ah, well. There it is then.

**Comment by Windchild292** [comment]
I've added the hyperlink in the person panel. Do we want to implement the rest of these?

**Comment by Windchild292** [comment]
Based on no further replies I'm closing this as implemented
