### ISSUE TITLE
Allied traitors scenario no longer working

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/mekhq#410]
With the redone scenario code, the Allied Traitors scenario is no longer working. It is not properly selecting the appropriate enemies for the assigned unit and is instead selecting all weight class enemies.

I would imagine that this applies to all 'special mission' type of scenarios.

**Comment by Bonepart** [comment]
https://github.com/MegaMek/mekhq/issues/437 I suspect these are related. I know at least one of the special missions works, as when I did my testing I let the system randomly pick one and selected for the unit deployed okay.

**Comment by HammerGS** [comment]
Closed as merged.
