### ISSUE TITLE
"Uncaught java util NoSuchElementException" when trying to advance a day in HQ

### ISSUE THREAD

**Issue by Kendaric-Imahso** [MegaMek/mekhq#4108]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
	Build Date: 2024-04-19T14:55:55.057542200
	Today: 2024-05-25
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.22
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 20 GB

### Description
Trying to advance a day in HQ.  Instantly hits me with this error message:
![2024-05-25 01_07_18-Uncaught java util NoSuchElementException](https://github.com/MegaMek/mekhq/assets/8572810/a61db81c-e0d0-4184-aa5d-0ca8d0095b32)

Upon inspection I noticed that my HQ window was showing 2 different dates for some reason:
![2024-05-25 01_04_39-Morgans Misfits (Mercenary) - Sunday, July 2, 3037 (Late Succession Wars - Renai](https://github.com/MegaMek/mekhq/assets/8572810/5c01e0f5-7ced-4609-804c-12e9b13a53d0)

No clue if related but seems wrong.

### Files
Campaign File: 
[Morgans Misfits.cpnx.gz](https://github.com/MegaMek/mekhq/files/15441949/Morgans.Misfits.cpnx.gz)

Custom Files:
[custom.zip](https://github.com/MegaMek/mekhq/files/15441950/custom.zip)

Logs:
[mekhq.log](https://github.com/MegaMek/mekhq/files/15441952/mekhq.log)

Please let me know if you need anything else.

**Comment by IllianiCBT** [comment]
Can you confirm whether you're on 49.19 or 49.19.1?

**Comment by Kendaric-Imahso** [comment]
Oh sorry.  49.19

**Comment by IllianiCBT** [comment]
I was able to advance day in 49.19.1. There were a number of advance bugs fixed in that version, and it looks like this issue was among them. Closing as resolved :)
