### ISSUE TITLE
MekHQ v0.49.20-SNAPSHOT, NullPointerException with Education module

### ISSUE THREAD

**Issue by jjgormley2** [MegaMek/mekhq#4123]
### Environment
What version of MekHQ does your issue apply to? _MekHQ v0.49.20-SNAPSHOT, Build Date: 2024-05-29T01:16:48.962688400_
What operating system are you using?  Windows, Mac, or Linux? _Windows 11_
What java version are you using?  Java Vendor: _Eclipse Adoptium, Java Version: 11.0.22_

### Description
Describe the issue and provide screenshots in game if able. _After enrolling personnel to any academy, allowing them to complete the enrollment, and allowing them to graduate and return, right-clicking on the graduating personnel throws a NullPointerException. This occurs on a new save and with any personnel sent to any academy. The error occurs whether you manually complete the enrollment or allow time to pass normally._

[My Campaign30350108.cpnx.gz](https://github.com/MegaMek/mekhq/files/15485632/My.Campaign30350108.cpnx.gz)
[mekhq.log](https://github.com/MegaMek/mekhq/files/15485634/mekhq.log)

**Comment by Sleet01** [comment]
This may be fixed in tonight's nightly build, but let me confirm with your campaign...

**Comment by Sleet01** [comment]
@jjgormley2 It looks like the bug fix patches that went in this morning have corrected the NPE.  This should be in the Nightly tonight.

**Comment by IllianiCBT** [comment]
@jjgormley2 (copied from Discord) Anyone using the nightlies: when updating to tonight’s nightly you will need to GM mode right-click Education/Complete Education any education enrolled personnel once (this can be done en masse).

Mentioning this here, as I know not everyone using the nightlies is signed up to be part of our QA team (if you use the nightlies a lot, definitely consider DMing Hammer to join the QA team).

**Comment by jjgormley2** [comment]
Issue resolved by 29 May 2024 Nightly build (MekHQ Nightly CI #1507).

**Comment by IllianiCBT** [comment]
Closing as resolved
