### ISSUE TITLE
[Nightly] Spheroid tech blocks clan techs from Mass/Repair Salvage

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4154]
### Environment
2024-06-03T01:14:09.813417422
Linux
17.0.10

### Description
Having an elite spheroid tech on staff will prevent elite clan techs from attempting repairs when using Mass Repair. The program is checking the first elite tech it finds, and if that tech can't do it on at a maximum target of 4, it assumes that none of the rest can (See line 705 of [MRMSService.java](https://github.com/MegaMek/mekhq/blob/master/MekHQ/src/mekhq/service/mrms/MRMSService.java)).

Because Spheroid techs have a +2 penalty, it is entirely possible for them to "block" a clan tech from attempting the repair when using Mass Repair. The attached save demonstrates this better than I can explain. Despite multiple available techs who can replace the right torso of the Shadow Cat II at 3 or 4, it will not be repaired.

### Files

[Spheroid_mech_tech_block.RD307031010728.cpnx.gz](https://github.com/user-attachments/files/15589812/Spheroid_mech_tech_block.RD307031010728.cpnx.gz)

**Comment by IllianiCBT** [comment]
Adding further information to this: the bug doesn't just affect Clan v. IS techs, rather any techs with the same experience level but different modifiers (from SPA, for example) are affected.

**Comment by repligator** [comment]
Closing as rendered 99% irrelevant by https://github.com/MegaMek/mekhq/pull/4863 . As Illiani pointed out above, it will still affect SPA's, but if I remember correctly those are all unofficial. If anyone is concerned, they can always open a new issue.
