### ISSUE TITLE
[43.2-git][AtB][bug] Base Attack scenarios fail to generate turrets

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/mekhq#416]
When using AtB and the game generates a Base Attack scenario while on contract, the slots that are supposed to be turrets instead say "no random assignment table found for faction". Saving and loading the game empties those slots out completely, so no save game can be provided. However, it's trivial to simulate in code by changing the MekHQ.Campaign.Force.Lance.checkForBattle() method to just return AtBScenarioFactory.createScenario(c, this, AtBScenario.BASEATTACK, true, getBattleDate(c.getCalendar()));, then cycling the day past sunday.

It appears that the calls to getEntityByName(randomGunEmplacement(), [snip]); fail to return a proper entity. 

I'm planning on working on this myself, but entered this issue to keep track of it.

**Comment by pheonixstorm** [comment]
I wonder when this issue started happening. Last I played AtB it worked, but that was before all the changes were made to the scenarios and maybe the rat tables

**Comment by NickAragua** [comment]
Fixed with PR #417
