### ISSUE TITLE
49.19.1  Every time I load my campaign one of my dropships has damaged thrusters.

### ISSUE THREAD

**Issue by Daishi-5** [MegaMek/mekhq#4163]
What version of MekHQ does your issue apply to?
49.19.1
What operating system are you using? Windows, Mac, or Linux?
Windows

What java version are you using? If unsure it will state your java version at the top of the mekhq.log file.
Java Vendor: Eclipse Adoptium
Java Version: 11.0.16.1

Short description:

Every time I load my campaign 1 dropship, name: "Union (2078)", has more damaged thrusters.  

The behavior is really weird.

At first, I noticed that it had 8 damaged thrusters, 4 on each side.  I repaired them all normally, thinking maybe it had been battle damage from a deployment.

Later I noticed 8 damaged thrusters again, and I repaired them again normally.  At this time, I still hadn't figure out it was related to loading the save.

Then, I reloaded to fix deployed auxiliary units, and I noticed the 8 damaged thrusters again.  This time I got screenshots to replicate the issue.  

Here are the damaged thrusters, and then I used GM mode to fix all the replacement thrusters I had, leaving 3 damaged. 
![image](https://github.com/MegaMek/mekhq/assets/168131032/049bb629-892a-48e6-90fa-7ea943629baa)
![image](https://github.com/MegaMek/mekhq/assets/168131032/cffc091a-1080-407c-b8f7-16d0058a9d4e)

Then, I reloaded to see if the thrusters were damaged again, and now I have 12 damaged thrusters.  (Note, in the screenshot, the unit card on the left says 4 left damaged, and 4 right damaged, but there are 12 thrusters available for repair in the center.)

![image](https://github.com/MegaMek/mekhq/assets/168131032/4b023f75-a0eb-45c3-99f1-99e8c0388277)

Just to check, I saved it again with the 12 damaged thrusters, and reloaded, now I have 14 damaged thrusters. The unit card still says 8.

[My Campaign30860517-4.cpnx.gz](https://github.com/user-attachments/files/15686279/My.Campaign30860517-4.cpnx.gz)
[My Campaign30860517-3.cpnx.gz](https://github.com/user-attachments/files/15686280/My.Campaign30860517-3.cpnx.gz)
[My Campaign30860517-2.cpnx.gz](https://github.com/user-attachments/files/15686281/My.Campaign30860517-2.cpnx.gz)
[customs.zip](https://github.com/user-attachments/files/15686282/customs.zip)

**Comment by repligator** [comment]
The issue seems to persist under 2024-06-03T01:14:09.813417422 (Java 17.0.10, Linux). I don't see anything in the logs that would indicate an issue either.
On the bright side, using GM mode to restore the unit from the hanger screen seems to have made the issue disappear.
 
[fixed.My Campaign30860517.cpnx.gz](https://github.com/user-attachments/files/15687084/fixed.My.Campaign30860517.cpnx.gz)

**Comment by TenkawaBC** [comment]
This may be related to bug #4849

**Comment by TenkawaBC** [comment]
Checking my.campaign30860517-4.cpnxM i can see this.
`		<part id="224396" type="mekhq.campaign.parts.MissingThrusters">
			<id>224396</id>
			<name>Thrusters</name>
			<unitTonnage>3600</unitTonnage>
			<mode>NORMAL</mode>
			<skillMin>1</skillMin>
			<unitId>1ec2f4a5-2387-4202-9bbd-0f62ba2dee40</unitId>
			<brandNew>false</brandNew>
			<quantity>1</quantity>
			<quality>3</quality>
			<isLeftThrusters>false</isLeftThrusters>
		</part>`

Parts 224396 through 224699. I'm seeing 10 entries in the campaign file.

Unit ID matches the dropship for all of them
`<unit id="1ec2f4a5-2387-4202-9bbd-0f62ba2dee40" type="mekhq.campaign.unit.Unit">
			<entity chassis="Union" model="(2708)" type="Spheroid" commander="false" externalId="1ec2f4a5-2387-4202-9bbd-0f62ba2dee40" altitude="5">`

**Comment by TenkawaBC** [comment]
Submitted a pull request for a fix on this, #5254 

The left thrusters were not getting created as missing parts correctly.
