### ISSUE TITLE
Transport Capacity Report issue

### ISSUE THREAD

**Issue by Desertdream2** [MegaMek/mekhq#4170]
### Environment
MekHQ version 49.19.1
Windows
Java 11.0.17

### Description
The Transport Capacity Report is treating all my units as needing a bay capacity, regardless of if they are mothballed or not. In Transport Capacity, it lists out my unit having Mech Bay Capacity of 93 (based on my Dropships, that is correct). However, it is saying I am using all of them plus have another 93 not transported. But when I analyze my unit overall, I can see (downloading Units and sorting them) that I have 186 (which matches 93+93), but 81 of them are Mothballed. Shouldn't my transport capacity report represent that? This is reflected when I go to the Unit Rating report, where under Transportation, I am listed as needing only 105 Mech Bays (with the same 93 available).

Screenshots:
![image](https://github.com/MegaMek/mekhq/assets/166620824/700cdb1e-a01c-4c1d-928a-fcd98083b621)
![image](https://github.com/MegaMek/mekhq/assets/166620824/12752ba1-0dab-471f-b0f3-75ace0943732)
![image](https://github.com/MegaMek/mekhq/assets/166620824/574717ae-05bb-468d-b7a5-3ff9a62d7761)

### Files
[5th ISR Bobcats30300901.cpnx.gz](https://github.com/user-attachments/files/15739022/5th.ISR.Bobcats30300901.cpnx.gz)
[5th ISR Bobcats.zip](https://github.com/user-attachments/files/15739069/5th.ISR.Bobcats.zip)

**Comment by IllianiCBT** [comment]
It looks like it's just a display bug, but I've not had a chance to investigate it (I won't till 50.0, at the earliest)

**Comment by IllianiCBT** [comment]
This has been resolved by the upcoming CamOps unit rating calculation rework. Closing as resolved.
