### ISSUE TITLE
[0.49.49.1] Contracts don't generate with (proper) pay

### ISSUE THREAD

**Issue by Jenbak5** [MegaMek/mekhq#4179]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
MegaMek Version 0.49.49.1
Windows 10 
Java 17.0.11

### Description
![bugreportcontract](https://github.com/MegaMek/megamek/assets/60224265/67adc3f5-5d39-4bdc-983b-43fb19dd6e40)
I created a new campaign using the StratCon Alpha as base with some modifications and then generated my company with a single lance.

New contracts don't generate with proper pay (they range from 1 200 to 18 240 C-bills).

### Files
Zip file containing:
[Bug report - Contract Pay.zip](https://github.com/user-attachments/files/15746591/Bug.report.-.Contract.Pay.zip)

- the log file
- campaign save
- company generation preset

**Comment by Jenbak5** [comment]
Coming back to the save much later I found out that my meks had no value attached to them and neither did the spare parts.
So unless the C-bills in the bank also counts for contract pay evaluation I think that might be the cause.
But how that happened; I'm not sure.
![image](https://github.com/MegaMek/mekhq/assets/60224265/d738b78f-95c5-4304-abde-c17cac04cee2)

![image](https://github.com/MegaMek/mekhq/assets/60224265/5fe0901c-f758-4cf2-ad4b-c87d00ebd1da)

**Comment by HammerGS** [comment]
Likely fixed with https://github.com/MegaMek/mekhq/pull/4141

**Comment by Jenbak5** [comment]
Yup, got it laid out to me in the discord. I did toggle the "Reverse quality name" during initiation
