### ISSUE TITLE
[RFE] - Add HQ Deployment Role for StratCon lances

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#4190]
Right now there is no way to put forces in your TOE without them being pulled as a primary force into battle.  

Not sure of the best way to do it, but an HQ Role for support forces that might occasionally be drawn into battle, but it would have a greatly reduced chance of being pulled as a combat force, but not be immune.  E.g. Traning Lances in AtB defaulted to a 10% encouter chance.  StratCon works differently, so I am not sure how it can work, but this is a common complaint.

So it would be in addition to a non-combat flag (which currently does not work) that would presumably be used for organizational purposes.  REMFs that never get picked for battle.  Like your recovery vehicles, or mobile kitchen lance, etc.  Some good ideas detailed here:  https://github.com/MegaMek/mekhq/issues/2749

And then you could have the HQ Role that can be picked for battle but at a greatly reduced chance.  Like traning lances, Arty Lances, etc.

Thank you.

**Comment by SuperStucco** [comment]
There needs to be a better name for this - we have the force generator roles, the Campaign Operations/official roles, and these roles.  Just like 'victory points', too many things using the same name.

I prefer a range of non-combat roles be available.  A 'transport' or 'logistics' role that gets deployed alongside/in place of the non-combat units in Convoy Escort scenarios.  A 'support' role that gets deployed when a friendly facility is under attack, and joins the fleeing civilian units.  Both, for the Base Attack (Defender) scenarios where you're really getting pushed.

**Comment by Thom293** [comment]
Agreed. Some heads  need to be put together on naming conventions.  Need to be clear and concise and non-similar to other things.

**Comment by Saklad5** [comment]
The fourth printing of *Campaign Operations* has three distinct types of non-combat force. I've pulled together the different roles each force is allowed to fill. Note that each force can only act as one type at a time, even though the relevant equipment may overlap.
| Name | Page | Purpose | Equipment |
|--------|--------|--------|--------|
| Repair and Refit | 197 | Maintains unit effectiveness | Mobile Field Base or Salvage Arm (for maintenance checks, repairs, and refits), MASH/Paramedic Equipment (for non-SAR wounded checks and/or healing), Liquid Cargo and possibly Refueling Drogue (for fuel and/or coolant), Bulk/Containerized Cargo and/or Lift Hoists (for spare parts, ammo, OmniPods, etcetera), Field Kitchen (for fatigue checks), Infantry Compartment/Bay (for Technical Teams, potentially in exoskeletons and such) |
| Salvage | 214 | Packs up and carries off units and/or components | Bulk/Containerized Cargo and/or Lift Hoists (for carrying off either entire units or salvaged components from them), Mobile Field Base or Salvage Arm (for salvaging components from units not being taken intact), Infantry Compartment/Bay (for Technical Teams, potentially in exoskeletons and such), Liquid Cargo and Fluid Suction System (for siphoning coolant and/or fuel) |
| Search and Rescue | 223 | Recovers personnel (including enemy) after unit destruction, abandonment, or ejection | MASH/Paramedic Equipment (for wounded checks of recovered personnel), Infantry Compartment/Bay (for holding recovered personnel), Active Probe or Improved Sensors (for locating personnel) |

Other types of non-combat force are possible or even already implied: prisoners need infantry squads to keep them in check; surveillance can be conducted with satellites, remote sensors, and/or aerospace; teams need to put out fires and disarm mines after combat; engineers set up fortifications and minefields before combat; the DropShips have to sit somewhere, and someone has to guard them… etcetera. But those types of force aren't as well-defined as the three types above.

**Comment by Thom293** [comment]
i like this.  if added, even partially or as an amalgamation, would add a lot of depth to merc units.

**Comment by Saklad5** [comment]
> i like this. if added, even partially or as an amalgamation, would add a lot of depth to merc units.

And crucially, none of that is homebrew: it's all official rules.

**Comment by IllianiCBT** [comment]
Closing as resolved
