### ISSUE TITLE
Error thrown when Clan sibkin reach age 10.

### ISSUE THREAD

**Issue by Stm316** [MegaMek/mekhq#4193]
### Environment
Mekhq 0.49.20 nightly 9th June 2024
Widows 10
Java 17.0.11 Adoptium (full re-install prior to logging issue, both JRE and JDK)
2GB RAM allocated, 12GB system

### Description
Upon reaching 10yo, Clan creche personnel throw an error. Daily report states personnel passed/failed trial of position with number of kills. Pass/fail for personnel, and error, is repeated daily until they are sent to academy or re-education (also repeated entry in personnel log). Changing status from student to active also avoids error message.
![error](https://github.com/MegaMek/mekhq/assets/156564469/88240a28-d117-40a4-bda5-aadd2a8b40a4)
(Composite image, personnel Personel in report, Zale, also finished creche on previous day)

### Files
[CSJ Sibko30360101.cpnx.gz](https://github.com/user-attachments/files/15754257/CSJ.Sibko30360101.cpnx.gz)
Error on my system will occur on next day advance.
Custom rank "Cadet" added at E1. Shouldn't matter? Not a new rank system or file, edited original ranks.xml
[mekhq.log](https://github.com/user-attachments/files/15754271/mekhq.log)
[megamek.log](https://github.com/user-attachments/files/15754273/megamek.log)

**Comment by IllianiCBT** [comment]
Closing as no longer relevant (clan education was removed from 49.20).
