### ISSUE TITLE
Show Unit ID in MM results in bad names in MHQ

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#42]
If you turn on the option to Show Unit IDs in MM Options...

All units in MHQ have the Unit ID appended to their name.

Like this one showing from Hangar...
Scorpion SCP-1N ID:179  Mek Medium  Mothballed  -   -

Perhaps Unit ID in MM should be separate column???

And MHQ should definitely ignore it!

![unitids in mhq](https://cloud.githubusercontent.com/assets/16738384/14287797/36b13e16-fb22-11e5-823e-5b67ca95c70b.jpg)

**Comment by arlith** [comment]
I'm not familiar with MHQ code, but I feel like this value shouldn't have any meaning.  In MM, it's used to identify an Entity, but it's just arbitrary, based on the order the unit was added to the game.  I think MHQ uses UUIDs to identify units.

**Comment by scJazz2** [comment]
The problem is turning the feature on in MM Client Options causes MHQ to display the same data. In doing so changing the name string of a unit in the CPNX. MHQ shouldn't show Unit IDs like MM does at all.

**Comment by arlith** [comment]
Yes, I'm corroborating your bug report...

**Comment by scJazz2** [comment]
Sorry Arlith, lil bit trigger happy cause you always give me well deserved flak :)

**Comment by BLOODWOLF333** [comment]
This is causing me issues in 0.3.30 bundle #119

**Comment by pheonixstorm** [comment]
Since issue #119 is now closed can someone confirm this is no longer an issue? If so this ticket can be closed as well.

**Comment by kipstafoo** [comment]
I am closing this issue. In 0.41.27, this appears to no longer be an issue. The MM unique IDs are not written out to the MUL and therefore don't find their way back to MHQ. There may be an edge case, but assuming MM is using the same code in all places to create the MUL, this issue has gone away.

**Comment by Dylan-M** [comment]
@kipstafoo You're assuming this was done via MUL. What if it was launched directly from MHQ?

**Comment by kipstafoo** [comment]
Because MM no longer saves the MM unique ID in the MUL, which is where the unique ID came from. These IDs aren't generated in MHQ.

**Comment by Dylan-M** [comment]
@kipstafoo Incorrect. They are present in MHQ. You have to turn them on.
