### ISSUE TITLE
49.20 Nightly - Contract Market seems broken and does not generate Contracts.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#4207]
So - I think the contract market is messed up too.  Brand new unit.  After the first month (where you get 2 contracts hard coded), I have had no contracts appear in the market.  With a 2 rating I should be getting some every month.  Im on Galetea (which I believe is still a Hiring Hall).

![image](https://github.com/MegaMek/mekhq/assets/23645569/5426e942-39e9-42d1-b78f-5a22c790a51a)

[Titanium Tide30700314BASE.cpnx.gz](https://github.com/user-attachments/files/15781920/Titanium.Tide30700314BASE.cpnx.gz)

[CustomsThom6.10.24b.zip](https://github.com/user-attachments/files/15781927/CustomsThom6.10.24b.zip)

**Comment by IllianiCBT** [comment]
I was able to get a contract by advancing one month. Potentially you just got unlucky.

![image](https://github.com/MegaMek/mekhq/assets/103902653/075e119f-10fb-4f2c-be8e-efc74e4c8028)

**Comment by Thom293** [comment]
well I ran though 6 months and got none.  Odd.  sorry.  closing.
