### ISSUE TITLE
[Nightly] EnemyMercSkyInfantry.xml reinforcements replaced by mechs

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4210]
### Environment
2024-06-10T01:16:09.281030903
Linux
Java 17.0.11

### Description
A scenario in Stratcon rolled with the EnemyMercSkyInfantry.xml. Normally, this adds a infantry riding flying beasts. However, on this occasion, 8 mechs got added instead. Regenerating enemy forces just adds mechs again. Note the following from the log.

`09:42:01,583 ERROR [mekhq.campaign.againstTheBot.AtBConfiguration] {AWT-EventQueue-0}
mekhq.campaign.againstTheBot.AtBConfiguration.selectBotLances(AtBConfiguration.java:224) - Bot force tables for organization "IS" don't have an entry for weight class 0, limiting to valid values`

### Files
[mekhq.log](https://github.com/user-attachments/files/15788793/mekhq.log)
[wingless_sky_cavalry.Bear Air Cavalry31520512.cpnx.gz](https://github.com/user-attachments/files/15788795/wingless_sky_cavalry.Bear.Air.Cavalry31520512.cpnx.gz)

**Comment by Thom293** [comment]
Ill look at this later today.  it worked before but maybe it got changed or does something strange with clans?
 Its a .mul file so maybe the reference got broken.

**Comment by Thom293** [comment]
Yep.  Something broke all of the infantry ones.  No idea what.  Will try to figure it out.

![image](https://github.com/MegaMek/mekhq/assets/23645569/67163e26-0bd2-463b-aa01-14a0645527da)

**Comment by Thom293** [comment]
Actually it broke ALL of the .mul modifiers it looks like.  Anyone know what could have changed this?

![image](https://github.com/MegaMek/mekhq/assets/23645569/733b6878-9598-4786-a560-da3d75824fff)
