### ISSUE TITLE
49.20 Nightly - MM No longer closes at end of MHQ Scenario

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#4212]
Title.  Previously, when the scenario resolution dialogue was finished, you would be spat out into MHQ and MM would be closed.

Now at the end of MHQ scenario resolution dialogue, you are spat out into an empty MM lobby, and not in MHQ. 

Just for convienance, the old way was better. But I think it may also be causing a priority struggle with the new Auto-Awards window which can cause it to disappear behind both the MM and MHQ windows, and the user will not know its there because there is no other visual indication it is open.

This is where you end up now at end of scenario resolution:

![image](https://github.com/MegaMek/mekhq/assets/23645569/fb807eb7-bcaf-4dd5-b1fc-703df83e9cec)

Should be able to load this save, launch battle, start battle, declare victory round 1, and get the behaviour.

[Titanium Tide30700606a.cpnx.gz](https://github.com/user-attachments/files/15798509/Titanium.Tide30700606a.cpnx.gz)

[CustomsThom6.10.24b.zip](https://github.com/user-attachments/files/15798514/CustomsThom6.10.24b.zip)

**Comment by IllianiCBT** [comment]
I pushed a fix earlier today (via #4208) that might have fixed this. At least, I've been unable to replicate while #4208 is enabled.

**Comment by IllianiCBT** [comment]
@Thom293 has this been an issue since 4208 got merged?

**Comment by Thom293** [comment]
Have not been able to play since. Was waiting on some merges and then got busy. Will try later this week.

**Comment by IllianiCBT** [comment]
I've not encountered this issue since I posted the fix a couple of weeks ago, so closing as resolved.

If the issue re-occurs lemme know and I'll investigate further.
