### ISSUE TITLE
Invalid Faction

### ISSUE THREAD

**Issue by DelaCruz-Sergeant** [MegaMek/mekhq#4222]
### Environment
     While in mekhq-windows-0.49.19.1
     Using Windows 10
     Java Vendor: Eclipse Adoptium
     Java Version: 11.0.22

### Description
     While playing MekHQ - Stratcon, I selected the year 3049 and the faction fed suns. For this reason, i was unable to get a contract because they are fedcom now.  Illiani, wrote, "I’ll try and get a ‘your faction no longer exists’ nag put in before 49.20 launches"

### Files
     N/A

**Comment by IllianiCBT** [comment]
The system works! I had forgotten about this, I’ll get it done in a couple minutes

**Comment by DelaCruz-Sergeant** [comment]
You rock!  Thanks
