### ISSUE TITLE
Personal Market - LRM Infantry available in 2950 campaign

### ISSUE THREAD

**Issue by Schugger** [MegaMek/mekhq#424]
MHQ offered me  a Jump LRM Infantry platoon for hire in my 2950 campaign. 
Longshot LRM launchers should not be available until about 100 years later.
Strangely enough, if you try to custimie an infantry unit in the Mek Lab and give them Longshot LRM launchers, the game will tell you that they are not available.

Eventually this is related to report #290

**Comment by pheonixstorm** [comment]
There are several infantry units like this and are usually included for one reason or another regardless of intro date of the unit and sometimes its weapons. Hammer would be able to explain it better.

**Comment by HammerGS** [comment]
I'll have to go back and look again, but I was sure I fixed those pesky infantry dates.

**Comment by HammerGS** [comment]
Dates fixed here - https://github.com/MegaMek/megamek/commit/7c6b301fad52b24ee3a030c99d836723ac69951b

One note from this Clan LRM infantry become unofficial as the Corean is a IS weapon system only (per IO).

Also LRM infantry have moved to a 3057 introdate but to get that date they have become a level 3 unit.
