### ISSUE TITLE
49.20 Nightly - Overwhelming Reinforcements modifier is broken.  Spawned roughly 150 units one time and 280 unit another...

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#4269]
Title. Normally this modifier spawns 2-3 lances of Enemies.  It is now spawning between 1-2+ Regiments.  

First time & Seed lance.
Spawned roughly 150 units. (this plus 2 pages).
![image](https://github.com/MegaMek/mekhq/assets/23645569/559c9641-9279-4936-b19d-90a9173dbb0f)
![image](https://github.com/MegaMek/mekhq/assets/23645569/1706b532-55ee-4864-9f04-549f33d958a1)

Second time & Seed lance
Spawned roughly 280 units. (this plus 5 pages).
![image](https://github.com/MegaMek/mekhq/assets/23645569/333cf133-deb2-420c-8542-64b4cfd80fc7)
![image](https://github.com/MegaMek/mekhq/assets/23645569/9b07556f-e6ae-438b-92ac-d224fb3af853)

 Save for both.  Log should contain both.

[Titanium Tide30700815OVER.cpnx.gz](https://github.com/user-attachments/files/15935072/Titanium.Tide30700815OVER.cpnx.gz)
[Titanium Tide30700926OVER2.cpnx.gz](https://github.com/user-attachments/files/15935073/Titanium.Tide30700926OVER2.cpnx.gz)
[mekhq.log](https://github.com/user-attachments/files/15935074/mekhq.log)
[CustomsThom6.10.24b.zip](https://github.com/user-attachments/files/15935075/CustomsThom6.10.24b.zip)

**Comment by NickAragua** [comment]
It's probably an instance of the "use your whole TO&E as the seed for opfor" bug.

**Comment by Thom293** [comment]
It could be, but I dont have any DS in it, and this is my whole unit.  This is a brand new unit on its first contract I built for testing.  
![image](https://github.com/MegaMek/mekhq/assets/23645569/9e75ed3f-abb3-4dfd-ab47-df6ed4f639eb)

**Comment by Thom293** [comment]
heh.  Card shows my unit is lead by a private...

**Comment by IllianiCBT** [comment]
No, this is definitely something else. I just got the bug, too, on a fresh campaign with only 3 lances in 3025:

![image](https://github.com/MegaMek/mekhq/assets/103902653/3ca4fe9f-a37c-4ed9-818f-fa51972002db)

**Comment by IllianiCBT** [comment]
It seems to be something specific with the `OverwhelmingEnemyGroundReinforcements.xml` modifier and, presumably, the ASF equivalent.

**Comment by IllianiCBT** [comment]
Reproduction: load the below save. Assign a lance to any of the three hostile bases. If you get the `OverwhelmingEnemyGroundReinforcements.xml` modifier (you'll get 10 modifiers, so chances are good) you will encounter this bug.

[overwhelmingBug.cpnx.gz](https://github.com/user-attachments/files/15937514/overwhelmingBug.cpnx.gz)

**Comment by Thom293** [comment]
It could be the modifier, but unless it was changed recently, it could be how it is handled in the code.

**Comment by IllianiCBT** [comment]
That would be my guess. I've finished with yard work, so getting a chance to look into it now. Off hand, do you know if there is any special handling for that modifier?

**Comment by Thom293** [comment]
it is a fixed modifier for some encounters.  Maybe guerrilla contracts, and perhaps the Irregulars scenario?

**Comment by IllianiCBT** [comment]
I've found the culprit. Pushing a fix shortly.
