### ISSUE TITLE
49.20  Nightly - Top Level of TO&E shows a Private as my CO.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#4270]
Super minor, but see below.  Can use save from #4269 if needed.

![image](https://github.com/MegaMek/mekhq/assets/23645569/8eb81024-c297-4a1a-b21b-9281291c2fa1)

**Comment by repligator** [comment]
It looks like if the top level is empty, it uses whoever the last person who was in it. If you move Captain Campion under the top level, and then move him back to his lance, he will show as the top level commander.
