### ISSUE TITLE
Dead bondsmen showing when filtered by prisoners

### ISSUE THREAD

**Issue by Stm316** [MegaMek/mekhq#4279]
### Environment
0.49.20 nightly from 15/6/24
Windows 10
Java 17.0.11 Adoptium

### Description
Playing as a Clanner, If you filter personnel by prisoner, deceased bondsmen are displayed.
Also wondering if it's possible to make recruiting bondsmen a thing (outside of those marked as recruitable post-scenario).

### Files
Campaign save file [Clan Fire Mandrill30561231.cpnx.gz](https://github.com/user-attachments/files/15942349/Clan.Fire.Mandrill30561231.cpnx.gz)
Custom unit files [Clan Fire Mandrill.zip](https://github.com/user-attachments/files/15942352/Clan.Fire.Mandrill.zip)

**Comment by IllianiCBT** [comment]
> Also wondering if it's possible to make recruiting bondsmen a thing (outside of those marked as recruitable post-scenario).

For this, bondsmen aren't recruited like prisoners. Instead, anyone who is a Bondsman can be assigned roles as if they were recruited.

**Comment by Stm316** [comment]
I know. That's why I've got one in a mech. 10 kills since assigning, but the only option is "free", can't adopt (recruit) him. Abtakha or however it's spelled.

**Comment by IllianiCBT** [comment]
Because of how Abtakha works, in that it's a decision by the Clan not a random roll, this is best handled by changing the person's status from Bondsman to 'Active'. We could add a 'Abtakha' option, but I'm wary of overly bloating the already quite long right-click menu.

**Comment by Stm316** [comment]
Cool. Ignore that request, then.
