### ISSUE TITLE
MHQ Allowing Multiple Concurrent Marriages

### ISSUE THREAD

**Issue by johnboyjjb** [MegaMek/mekhq#4283]
MekHQ v0.49.19.1
	Build Date: 2024-05-10T20:11:07.455725852
	Today: 2024-06-18
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.11
	Platform: Windows 11 10.0 (amd64)
	System Locale: en_US
	Total memory available to MekHQ: 4 GB

### Description
Pablo Stannard has two wives concurrently
(https://discord.com/channels/458705327911731231/458706545379639296/1254838121615331488)

### Files
My CPNX file exceeds the 25MB limit.
[PabloStannard.zip](https://github.com/user-attachments/files/15959350/PabloStannard.zip)

**Comment by johnboyjjb** [comment]
Another thing that could be fixed depending on how you fix this, step parents and blended families are not really represented nicely.

**Comment by IllianiCBT** [comment]
This should be resolved in 50.01, closing for now. However if it reoccurs once 50.01 is out, please log a fresh bug report. Or request this one get re-opened.
