### ISSUE TITLE
Switching ammo does not update the UI

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/mekhq#429]
This happens in both the hangar and repair tabs. There are no errors in the log and reloading the campaign will fix it.

![ammo](https://user-images.githubusercontent.com/1787879/29905210-399fb470-8ddb-11e7-9629-96b76dcbfa00.png)

**Comment by jslater89** [comment]
I poked at this and saw the following behavior:

1. Swap ammo generates a repair task.
2. Until the repair task is completed, the old ammo type displays with the full number of shots. 
3. If the game is reloaded, the new ammo type displays with zero shots.

So it's inconsistent, but I'm not sure in which direction to fix it.

**Comment by NickAragua** [comment]
Fixed with PR #448
