### ISSUE TITLE
RFE: Dynamic Loyalty with Turnover and Education modules

### ISSUE THREAD

**Issue by DeniedExistence31** [MegaMek/mekhq#4290]
Illiani requested I add this as an RFE so that they can remember to consider it.

With the coming new Turnover and Education systems, it would be nice if there was benefit for taking on and training up Green/Ultragreen recruits and educating children as opposed to simply hiring vets and elites for your company. Keeping the rolled loyalty (the 2-24 variable that is translated to the turnover loyalty modifier) would allow for dynamic increments to personnel loyalty, which is one way that this could be done.

For example, one of the breakpoints currently as I understand it is 16; say you had a dependant child who rolled a loyalty value of 15, known or unknown to you, and you sent them off for school, which in this example increments the rolled value by 1 upon graduation. This causes their loyalty value to break the 16 threshhold, thus granting them a better turnover loyalty modifier than before.

Various events/decisions could have such increments/decrements that they apply to personnel, changing the loyalty of your company personnel over time, rather than those that are loyal or disloyal always being effectively such if they stick around long enough. There may be additional unexpected value to retaining this xd6 roll in the future.

Alternatively/additionally Green/Ultra-green recruits could be given a unique loyalty roll like prisoners and re-educated personnel are. Furthermore, I think it would be more valuable to make these special rolls an xd6 drop yd6 method instead of the 2d6 vs 3d6 vs 4d6 rolls that are currently implemented. Having prisoners only roll 2d6 guarantees they will not generate as high loyalty. I agree that event should be unlikely, but not completely impossible. 

Having, for example, prisoners instead roll 4d6 and drop the highest value out of the d6 would give them an on average lower final loyalty value, while still retaining the possibility of generating with a high loyalty. This drop system is already in place for the Natural Aptitude SPAs in Megamek, which take the highest two dice of 3d6 for their respective roll types. This method can also be easily altered for however strongly you want to slant the probability for any particular character type. 20d6 drop highest 17d6 would make someone exceptionally unlikely to roll high, if you felt that was important for some reason.

Here's an article showing how things like this affect probability: https://anydice.com/articles/4d6-drop-lowest/

**Comment by IllianiCBT** [comment]
catlikecoding (where anywise is hosted) is a godsend. I've been using their site for well over a decade
