### ISSUE TITLE
[49.20] Duplicated Nag Dialogs

### ISSUE THREAD

**Issue by IllianiCBT** [MegaMek/mekhq#4297]
### Environment
Version: 49.20 (in dev)
OS: Mac
Java: Adoptium 11

### Description
Occasionally, a bug may cause all new day notifications to duplicate, including everything from missing commander alerts to turnover dialogs. Restarting the client resolves this issue. Due to its intermittent nature, tracking down the cause has been challenging.

This issue has been present since at least version 49.18. However, I could not confirm it affected others until earlier today, so I didn't file a report. I run the client through IDEA and had assumed it was a quirk related to that.

For testing purposes, I've attached a save file set to trigger the turnover and missing commander notifications on the next day. However, as restarting the client fixes this issue, it may be necessary to reload the file multiple times before the issue occurs.

## Files
[Autosave-1-Peach Garden-30321201.cpnx.gz](https://github.com/user-attachments/files/15993652/Autosave-1-Peach.Garden-30321201.cpnx.gz)

**Comment by repligator** [comment]
I've only personally experienced the bug with the turnover nag. The first time I experienced it was with version 2024-06-26T01:14:43.618455549 AKA MHQ nightly 1534.

**Comment by IllianiCBT** [comment]
I've not seen this since the switch to java 17, so closing as resolved.
