### ISSUE TITLE
[49.20] Missing Daily Log Messages & Empty MHQ Log

### ISSUE THREAD

**Issue by IllianiCBT** [MegaMek/mekhq#4298]
### Environment
Version: 49.20
OS: Mac
Java: Adoption 11

### Description
I’ve encountered a very rare bug where daily report messages fail to appear. When this happens, no daily report messages show up, regardless of their source. Restarting the client resolves the issue.

Potentially related: when this bug occurs, the mhq log also appears empty, suggesting that no messages are being pushed there either. When I say 'empty' I mean the entire file is completely wiped clean.

**Comment by repligator** [comment]
I've not had any truly empty logs, but I've had multiple log entries that should be there simply not appear. New 'Mechs, swindled by Black Market, new hires, repairs, etc.

**Comment by Thom293** [comment]
> I've not had any truly empty logs, but I've had multiple log entries that should be there simply not appear. New 'Mechs, swindled by Black Market, new hires, repairs, etc.

This is also how I have seen it.  Never seen a completely empty one.

**Comment by IllianiCBT** [comment]
Can I clarify, when you say 'log' are you referring to the mhq log or the daily report?

**Comment by Thom293** [comment]
I use them interchangeable. Maybe wrong. Daily report log where you get repair messages, market refresh messages, defections, etc.

**Comment by IllianiCBT** [comment]
I've not seen this since the move to java 17. Closing as resolved
