### ISSUE TITLE
RFE: Administrators are gaining too much XP

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#43]
Tried to find an old ticket in SF but couldn't.

MHQ > Campaign Options > Experience > XP Awarded to each administrator every Monday for the work of the previous week...

Currently, the value is an integer. Can it become a float, like 0.25? Or can the Option be renamed and have a 2nd Field or every N Mondays?

**Comment by pheonixstorm** [comment]
In my latest non-AtB test campaign none of my admins are getting any monday xp. Do you recall if this was an atb only option?

**Comment by scJazz2** [comment]
Campaign Options > Experience > Middle Left
N XP Awarded to each administrator every Monday for the work of the previous week.

Also it shouldn't be a float it should be "for the work of the previous" Y week(s).

**Comment by pheonixstorm** [comment]
Yes I know where it is. I tried to set it to 1, 2, 3.. and... nothing. No xp gain.

**Comment by Akjosch** [comment]
The weekly XP stuff is weird. The rules, as they currently are, deeply nested within a huge if-chain:

* If AtB is in use
* ... *and* for each AtB contract (but no other!) that is currently running
* ... *and* if the admin XP option is set to a value more than 0
* ... *and* for each person who's primary job is some kind of administrative one
* ... award the XP

Given that it's an experience option and not an AtB option, this is 100% wrong.

**Comment by pheonixstorm** [comment]
So it was designed as an atb only option then. That kinda fits considering the amount of xp required to raise a skill in atb.

**Comment by Akjosch** [comment]
Ok, so I added the `DayEndingEvent` and `NewDayEvent` events to the campaign (I wanted to do so anyway, so might as well). With them the *current* implementation would be easily amended by adding the following as an event handler and removing the corresponding code from the already way too big Campaign#newDay().

```
    @Subscribe
    public void processAdminXP(NewDayEvent event) {
        final Campaign campaign = event.getCampaign();
        final CampaignOptions opts = campaign.getCampaignOptions();
        if((opts.getAdminWeeklyXP() <= 0)
                || (campaign.getCalendar().get(Calendar.DAY_OF_WEEK) != Calendar.MONDAY)) {
            return;
        }
        for (Person person : campaign.getPersonnel()) {
            if (person.isAdminPrimary()) {
                person.awardXP(opts.getAdminWeeklyXP());
            }
        }
    }
```

The question remains: What if I want to add less than 1 XP per week? What do you think, should we leave that to chance (C% chance of X XP per week) or only the XP every-so-many-weeks? The chance one is easier to implement, frankly.

**Comment by pheonixstorm** [comment]
For work from a given week? No, I think making it x xp per x weeks would be better, though frankly having it set to 1xp per x weeks would be the best.

**Comment by scJazz2** [comment]
X per Y weeks please... it was added as an option to help AtB admins IIRC but it should be open to non-AtB as well.

**Comment by Akjosch** [comment]
Okay then, so I'll need to add a tiny bit of infrastructure to `Person` so that I can record how many Mondays ago they last got admin XP ...

**Comment by Akjosch** [comment]
There we go, PR to do so done. Looking at the required code changes, we need to make campaign loading/saving and campaign option additions less of a pain too.

**Comment by Akjosch** [comment]
PR #62 merged in.

**Comment by scJazz2** [comment]
TYVM!
