### ISSUE TITLE
When starting a scenario in MegaMek the camo for units seems to be the defaults

### ISSUE THREAD

**Issue by Bonepart** [MegaMek/mekhq#431]
I would think the intention of giving a Camo option in the Campaign options is to have your units in that color. It does not seem to be carrying over to MegaMek.

Also contracts, at least under AtB, have camo options for allies and the enemy and those do not seem to carry into MegaMek either.

**Comment by Bonepart** [comment]
Nevermind about the camo options for allies and enemies. Those seem to be working okay. It's just the player camo that doesn't seem to carry across.

**Comment by Bonepart** [comment]
Using a named camo seems to work just fine. If you pick a color under the 'no camo' listing those will default to blue in MegaMek.

**Comment by Bonepart** [comment]
Found the problem, submitted https://github.com/MegaMek/mekhq/pull/432 to fix it

**Comment by neoancient** [comment]
Fixed in c78065c
