### ISSUE TITLE
[49.20] Turnover and Retention: Management option, leadership has inverse effect.

### ISSUE THREAD

**Issue by DeniedExistence31** [MegaMek/mekhq#4315]
### Environment
Megamek/MekHQ Version: 0.49.20
OS: Windows 10
Java Version: Adoptium 11.0.23.9

### Description
With the new Turnover and Retention module, enabling the 'enable managment skill' campaign option has the inverse effect that it should on the turnover die roll. Ie, a commander leadership of +1 would result in a +1 to the TN, and a leadership of +4 would result in a +4 modifier to the TN, making personnel _more likely_ to leave a unit with better leadership.

**Comment by IllianiCBT** [comment]
I have lost count of how many times I fixed this…

**Comment by IllianiCBT** [comment]
Would you be able to provide a save file that displays this issue? Make sure to include your customs folder in the upload

**Comment by IllianiCBT** [comment]
To clarify, the reason I need the save is to verify there isn't something else going on, as I'm not able to replicate this issue locally:

![image](https://github.com/MegaMek/mekhq/assets/103902653/01859da4-b997-4b81-a698-da15b9e561e8)

**Comment by IllianiCBT** [comment]
Disregard last, it looks like this bug only exists when 'only use commander's leadership' is enabled, which is why I was struggling to replicate the problem.
