### ISSUE TITLE
[RFE] Language clarification on Campaign Options>Against the Bot>Scenarios section

### ISSUE THREAD

**Issue by Stackandslash** [MegaMek/mekhq#4316]
### Environment
Megamek/MekHQ Version: 0.49.20
OS: Windows
Java: Adoptium 11.0.23.9

### Description
The tooltip description for the Maximum Random Scenarios Modifier value could use some additional clarification to make the inclusion of Facility modifiers explicit, for rookies like myself.
![image](https://github.com/MegaMek/mekhq/assets/61757855/598602fc-b70e-499f-9b94-3ba5342327b3)

There may be some benefit in text directing the user to more detailed coverage of the Scenario Modifiers system, as well, but that might not fit in a tooltip

**Comment by IllianiCBT** [comment]
Thanks for the report. I’ll see about clarifying things when I get back from vacation and I’ll add a pointer that directs folks to the StratCon documentation :)

**Comment by IllianiCBT** [comment]
Closing as resolved (manually closing so I can more clearly see which of my tasks are still outstanding)
