### ISSUE TITLE
RFE: Education status added as a sortable column

### ISSUE THREAD

**Issue by johnboyjjb** [MegaMek/mekhq#4317]
49.20

The education level is only displayed in the side bar callout and does not appear in personnel table nor the exportable CSV.
This prevents somebody looking for either the least or most educated person without checking every person.

Loyalty has the same "problem" but given that loyalty can be masked and is pretty hard to enumerate in real life it doesn't seem as necessary.

**Comment by IllianiCBT** [comment]
Thanks for the RFE, I’ll do some thinking about the best way to display this information in the personnel table; as I want to avoid cluttering the existing filters.

There are a few more metrics coming it might mean adding a new filter. I think there is also value in adding a Fatigue column

**Comment by johnboyjjb** [comment]
I dump the CSV and integrate it with my Excel file pretty regularly so that works for me, but isn't the most elegant solution.

**Comment by IllianiCBT** [comment]
I opted not to include Loyalty, as (as you pointed out) Loyalty can be hidden and it would have been a bit of a pain to implement.

I also opted not to include Fatigue as that is a metric that only really affects combat personnel and is transitory so doesn't really warrant a column of its own.

**Comment by IllianiCBT** [comment]
Closing as resolved (manually closing so I can more clearly see which of my tasks are still outstanding)
