### ISSUE TITLE
[RFE] Allow any faction with the "merc" tag to get random contracts

### ISSUE THREAD

**Issue by azhais** [MegaMek/mekhq#4318]
### Description
I've added a custom faction to the game with the "merc" tag.   My expectation was it would function as a mercenary faction and get contracts from anyone, but it functions as a standard faction and only gets contracts from the faction itself.   Obviously an edge case, but it would be nice if the contract generation would switch from the current hardcoded "only if the faction is named MERC" code:

```
src/mekhq/campaign/market/ContractMarket.java#L283

        if (campaign.getFactionCode().equals("MERC")) {
```

to something that checks for the faction's "merc" tag in factions.xml.  I imagine a similar change would need to go into 
generateContractOffers

**Comment by IllianiCBT** [comment]
From what I’ve seen there is quite a lot of code that checks for the faction code being “MERC” rather than using the isMercenary method. 50.0 would be as good a time as any to start switching some of those uses across.
