### ISSUE TITLE
[49.20] Children are being born with a high school education

### ISSUE THREAD

**Issue by azhais** [MegaMek/mekhq#4319]
### Environment
What version of MekHQ does your issue apply to? 49.20
What operating system are you using?  Windows
What java version are you using?  17

### Description
While generating a company after starting a new campaign, dependents born during the simulation period are being given "High School" as their education level.   I'd expect this to be 'none' or some variation thereof.

Attached campaign is just starting with the 'stratcon alpha' preset + enable education module.

### Files
[overeducatedbabies30350101.cpnx.gz](https://github.com/user-attachments/files/16043495/overeducatedbabies30350101.cpnx.gz)
![Screenshot 2024-06-30 015646](https://github.com/MegaMek/mekhq/assets/46464401/f796640e-f263-41ea-952d-4af6f17502e9)

**Comment by IllianiCBT** [comment]
On vacation, but I’ll get this resolved once I’m back in a week

**Comment by IllianiCBT** [comment]
Closing as resolved (manually closing so I can more clearly see which of my tasks are still outstanding)
