### ISSUE TITLE
RFE: Add facility description to AtB Campaign State tab

### ISSUE THREAD

**Issue by BlueThing00** [MegaMek/mekhq#4321]
### Environment
MegaMek v0.49.19.1
Java Vendor: Eclipse Adoptium
Java Version: 17.0.11
Platform: Windows 11 10.0 (amd64)

### Description
As seen here, facilities do not have descriptions:
![image](https://github.com/MegaMek/mekhq/assets/21363819/4010f6ec-9e03-42db-bd5e-1c41926b83e0)

A description and information on the game effects of each facility would impact my decisions on which to go after first.
### Files
n/a

**Comment by IllianiCBT** [comment]
Fixed in 49.20. Closing as resolved
