### ISSUE TITLE
RFE: Apply death notice to all family

### ISSUE THREAD

**Issue by johnboyjjb** [MegaMek/mekhq#4323]
49.20

When somebody kicks the bucket, the spouse will get a message, "Spouse, Deborah Keitel, was killed in action"
Deborah had a spouse and two kids but only the spouse gets the message. 

This request is to push that personnel log message into all members of the genealogy.

**Comment by IllianiCBT** [comment]
Closing as resolved (manually closing to make it easier for me to see what issues still need actioning).
