### ISSUE TITLE
[0.49.20] Admin Skill Levels not functioning as intended

### ISSUE THREAD

**Issue by SVNaas** [MegaMek/mekhq#4325]
### Environment
0.49.20 (All)

### Description
With Admin skill links active, Scrounge and/or Negotiation personnel who don't have Scrounge and/or Negotiation return a Skill Level of None, rather than counting as a -1 to match someone with the skill at level 0.

**Comment by IllianiCBT** [comment]
While I agree the interaction isn’t ideal, it’s technically working as intended. As per discord conversation, though, I see the points raised and will review this once I’m back from vacation
