### ISSUE TITLE
Field Kitchens should not need to service support personnel

### ISSUE THREAD

**Issue by Saklad5** [MegaMek/mekhq#4329]
### Environment
MegaMek Version: MekHQ v0.49.20 Development Snapshot
Operating System: Mac
Java Version: 20.0.1

### Description

MekHQ 0.49.20 adds a rough implementation of Field Kitchens, diverging from _Campaign Operations_ primarily in not tracking actual deployment. The current approach instead compares the number of Field Kitchens on fully-crewed units against the total number of personnel in the force, providing the Fatigue bonus to everyone if there's enough capacity.

Putting aside the Field Kitchen-equivalents included with quarters on Small/Large Craft, this approach shouldn't be counting support personnel at all. Page 219 of the fourth printing of _Campaign Operations_ describes Field Kitchens thusly:

> **Field Kitchen**: Forces that have access to field kitchen reduce fatigue by 1 extra point. One field kitchen can supply 150 combat troops (and their support personnel) per Morale/ Fatigue Cycle. When determining which forces have access to the available field kitchen resources, do not split any units; that is, all 28 ground-pounders in that platoon are counted or none are.

While the logic of this is debatable, the meaning is not: players should only need one Field Kitchen for every 150 *combat* personnel, and the requirement should ignore support personnel entirely due to being included in the former.

---

This issue was opened at [the request](https://discord.com/channels/458705327911731231/458706545379639296/1256445791451484263) of @IllianiCBT.

**Comment by IllianiCBT** [comment]
Closing as resolved (manually closing so I can more clearly see which of my tasks are still outstanding)
