### ISSUE TITLE
[49.20] gamelog lacks formatting

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4331]
### Environment
MekHQ bundle 0.49.20.
Microsoft Windows 11 Home - 10.0.22631 Build 22631
Eclipse Adoptium 17.0.8.1

### Description
After starting a new campaign and fighting an engagement set, opened the gamelog.html file in order to assign certain kills. 
File opened in browser (Google Chrome default) and seemed to lack formatting that rendered it readable. 
Opening the log in Microsoft Edge, or an HTML reader resulted in the same lack of format. 
In previous version use (0.49.19 and prior) gamelog file behaved normally.

![image](https://github.com/MegaMek/mekhq/assets/141160646/26de428c-6fec-4161-aac9-dc755beced51)

### Files
[megamek.log](https://github.com/user-attachments/files/16072573/megamek.log)
[mekhq.log](https://github.com/user-attachments/files/16072574/mekhq.log)
[Compressed gamelog for upload.zip](https://github.com/user-attachments/files/16072577/Compressed.gamelog.for.upload.zip)
[Autosave-3-Coalition Heavy Lancers-30300308.cpnx.gz](https://github.com/user-attachments/files/16072582/Autosave-3-Coalition.Heavy.Lancers-30300308.cpnx.gz)

**Comment by IllianiCBT** [comment]
Closing as resolved. Please see #5687 for more information.
