### ISSUE TITLE
paid recruitment doesnt turn off

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#4335]
### Environment
win 11
java 17
mmhq 49.20

### Description
did a paid recruitment for a few weeks.  got the person i was looking for, turned paid recruitment off.  continue to be charged for paid recruitment weekly, even though radio selector is still off.

### Files
[Galatia Mecenary Coalition27621203.cpnx.gz](https://github.com/user-attachments/files/16099027/Galatia.Mecenary.Coalition27621203.cpnx.gz)

**Comment by repligator** [comment]
Did you close the recruitment window after deselecting paid recruitment? As far as I know, changes to paid recruitment don't take affect until you close the recruitment window.

**Comment by bczretribution** [comment]
Yes window was closed, a month has been progressed, it charged every week.  Window has been opened a giant to confirm radio button is off, and closed again.  Charges still made

**Comment by IllianiCBT** [comment]
This seems to be connected to whether you click the button labeled ‘close’ or whether you just terminate the window.

**Comment by IllianiCBT** [comment]
Closing as resolved (manually closing to make it easier for me to see what issues still need actioning).
