### ISSUE TITLE
RFE: ability too use multiple QTY with the tier system in <awards>

### ISSUE THREAD

**Issue by Wunsche** [MegaMek/mekhq#4337]
This post ties into that my previous RFE for rank and would effectively make rank images a thing in mhq IMO. Perhaps I should of put both together I guess but they are separate improvements too me and this one will probably be harder too implement than just <range>implicit</range>, so i decided it best too make 2 separate post
==
Add the ability too use multiple quantities with the excellent tier system , for award. It would probably be useful too have this trigger automatically after the rank is changed though

Now, this might prove useful for other awards as well, but im mainly thinking of the <item>ranks</ranks>. 

Not sure how too put this in words, so an example
![2024-07-04_082200](https://github.com/MegaMek/megamek/assets/80139243/292a9a57-932a-4bf3-838f-722c89eb1fa5)

    KG_BRANDENBURG

**Comment by IllianiCBT** [comment]
Multiple qty would require rebuilding how qty functions for every award and would be no small amount of work. It’s not something I’m considering at this time.

Adding a trigger to rank change is definitely something I can take a look at. That shouldn’t be too much extra work, I’d just need to add a unique trigger handler. That’s something I’m already looking into for your other RFE. So that should be done for 50.0’s release.

**Comment by Wunsche** [comment]
well,.. that for looking at the rank trigger idea.. that's the more important of the 2. w/o the qty rfe, this just means ill have too delete the old rank after the new one. which is no big deal. i understand its alot of work, with such a niche benefit. i hated asking because i felt it would be alot of work, but i thought id try any way.

**Comment by IllianiCBT** [comment]
So the plan is to have autoAwards optionally remove the lesser award when promoting. However, right now I’m on vacation, so haven’t investigated feasibility.

**Comment by Wunsche** [comment]
ohh dude.. that idea will definitely work 

i thought of that idea then it got lost sometime between 1st thinking of it and posting and then the  qty idea took over. probably because i was thinking of another idea


thx again for looking into my request

**Comment by IllianiCBT** [comment]
Closing as no intentions to implement
