### ISSUE TITLE
Employee Turnover: Management Skill effect inverted

### ISSUE THREAD

**Issue by SirChaos1** [MegaMek/mekhq#4341]
In the Employee Turnover module, the list of factors influencing the target number shows that Management Skill (i.e. the Leadership skill of the commander) *increases* the target number for employee retention, rather than decreasing it.

Everything else appears to be working as intended.

**Comment by IllianiCBT** [comment]
Thanks for the report. This is a known issue with the ‘use commanders leadership only’ option and will be fixed in the next version.
