### ISSUE TITLE
Right click on Clan freeborn throws illegal state error

### ISSUE THREAD

**Issue by Stm316** [MegaMek/mekhq#4347]
### Environment
MekHQ nightly 0.50 #1537
Windows 10 22h2
Java 17.0.11

### Description
![error](https://github.com/MegaMek/mekhq/assets/156564469/df8289d0-e0ca-40d4-98e5-1143947ee8f3)
Clan personnel, freeborn, from trueborn elemental mother.  I'm raising clan personnel from 0 yo (bulk gm hired age range 0-0 yo, different phenotypes) to age 20. I have a copy of your "clan academies xml" from .49.2, renamed for play purposes. Attaching all sets below. 160 other generated personnel are fine. Failures are manually assigned to a new caste. I say it's because the mother's on government benefits.

### Files
[CSJ Sibko30381029.cpnx.gz](https://github.com/user-attachments/files/16114229/CSJ.Sibko30381029.cpnx.gz)
Custom awards
[Clan_SJ.zip](https://github.com/user-attachments/files/16114233/Clan_SJ.zip)
[Clan_SJ_XML.zip](https://github.com/user-attachments/files/16114235/Clan_SJ_XML.zip)
modified ranks xml (no clan mechwarrior "point1-5"), not provided
[Academies.zip](https://github.com/user-attachments/files/16114275/Academies.zip)
[mekhq.log](https://github.com/user-attachments/files/16114266/mekhq.log)

**Comment by IllianiCBT** [comment]
I strongly suspect using the clan academies file is what’s breaking things. There have been a lot of format changes since Clan education was removed, so those academies won’t work

**Comment by Stm316** [comment]
Everyone else is happy. I'll remove the <isclan> and report back.

**Comment by IllianiCBT** [comment]
It's not just the `isClan` tag, I moved to using enums instead of magic numbers, plus a number of other things that were removed. The old academies (even the IS ones from that period) are incompatible with the release version.

Looking through the log, all the errors I'm seeing look like they're coming from a malformed academy set.

**Comment by Stm316** [comment]
I guess that solves it then. Will sort out what i've got wrong. Thank you.

**Comment by IllianiCBT** [comment]
Is all good. I understand wanting to have Clan education, but I'd recommend waiting for it to be implemented properly. :)

Closing as invalid.
