### ISSUE TITLE
Fenrir BA causing NPEs due to missing images

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#435]
Using 43.3, it seems the mechset.txt file is pointing to fenrir image files that do not come with the download.

Mechset.txt : 

exact "Fenrir Battle Armor [ERML]" "battle armor/fenrir_ml.png"
exact "Fenrir Battle Armor [MG]" "battle armor/fenrir_mg.png"
exact "Fenrir Battle Armor [Mortar]" "battle armor/fenrir_ml.png"
exact "Fenrir Battle Armor [MPL]" "battle armor/fenrir_ml.png"
exact "Fenrir Battle Armor [SL]" "battle armor/fenrir_mg.png"
exact "Fenrir Battle Armor [SPL]" "battle armor/fenrir_mg.png"
exact "Fenrir Battle Armor [SRM]" "battle armor/fenrir_srm.png"
exact "Fenrir Battle Armor [VSP]" "battle armor/fenrir_vsp.png"

But my image folder only has fenrir.png and fenrir(6).png.

When attempting to select a fenrir BA in the hangar, it leads to a NPE due to the missing images.

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1283523/mekhqlog.txt)

**Comment by HammerGS** [comment]
This is actually a MegaMek Issue. For future reference issues with unit sprite issues should be posted on that tracker.

Fixed here - https://github.com/MegaMek/megamek/commit/6fe0e05b369bf850b61b310b7cc8f94cd3202864
