### ISSUE TITLE
[NPE/RFE] Null pointer exception advancing the day when custom academies are missing

### ISSUE THREAD

**Issue by azhais** [MegaMek/mekhq#4352]
### Environment
What version of MekHQ does your issue apply to? 0.49.20
What operating system are you using?  Windows
What java version are you using? 17

### Description
I switched to a new nightly (this is reproducible in 0.49.20 and that's what the attached save is from) and got a null pointer exception when advancing the day.  Looking at the logs, it's because I forgot to copy my custom academies over.

Additionally, if you save the campaign after advancing the day and getting the NPE, put the missing files in place, then reload, the next time you advance the day it will send all students home because their academy was destroyed, even tho they do exist and you can send the students straight back.

It would be nice if MekHQ would check for missing academies the same way it checks for missing custom mechs upon loading the game.

### Files
[ghost academies30250103.cpnx.gz](https://github.com/user-attachments/files/16134170/ghost.academies30250103.cpnx.gz)
[mekhq.log](https://github.com/user-attachments/files/16134171/mekhq.log)
[Ghost Academies.zip](https://github.com/user-attachments/files/16134176/Ghost.Academies.zip)

**Comment by IllianiCBT** [comment]
This was a fantastic RFE.

I'm going to go ahead and manually close it, rather than waiting for GitHub to do it automatically, as that makes it easier for me to see what still needs to be done.
