### ISSUE TITLE
Education Module: Bonus XP generation rate seems off.

### ISSUE THREAD

**Issue by SirChaos1** [MegaMek/mekhq#4357]
Playing the July 3rd Nightly...

I´ve been doing a bit of a test run of the Education Module. Bonus XP are enabled and set to 1 XP. After one year (signed up 200-ish personnel on January 1st and ran until the January 1st the next year) all students (generated with 0 XP) sit at either 0, 1 or 2 XP. 

Faculty skill is 7+, so in 12 monthly rolls, an average 7 bonus XP would be expected, with plenty of variation either way.

The observed generation rate is consistent with bonus XP being rolled for every 6 months; with 200-ish test subjects, any more frequent rolls would have resulted in at least a few personnel with 3+ XP. Alternatively, the success chance of bonux XP checks might be way lower than documented, but even then with more than 2 checks I would expect at least a few personnel to have 3+ XP.

**Comment by IllianiCBT** [comment]
Thanks for the big report. I’ll make sure to investigate this some time before the end of the week and get back to you :)

**Comment by IllianiCBT** [comment]
Closing as resolved (manually closing so I can more clearly see which of my tasks are still outstanding)
