### ISSUE TITLE
RFE: Education Module Tweaks

### ISSUE THREAD

**Issue by SirChaos1** [MegaMek/mekhq#4359]
I would like to have the ability to manually drop someone out of their current education module - the same way that manually completing an education stage works right now, except they always fail to graduate, rather than rolling for graduation.

Also, right now (if bonus XP generation worked as documented), childhood education generates a ridiculous amount of XP, on account of how long it takes - a character spending all their life from birth to 16th birthday in an education with faculty skill 7+ can expect to gain 112 XP from monthly bonuses alone. That is probably too much and should be reduced - such as by changing faculty skill in all childhood education to 11+ or 12+.

Regarding the proposed change to bonus XP in general... if you end up going with bonus XP being granted at conclusion, perhaps the amount should be in a XdY format, where X is determined by course length and faculty skill (from 0 for boot camp and reeducation camp to maybe 10 or 12 for 1200 day courses in elite academies like Sun Zhang or the Nagelring) and Y can be set in the options so that people can adjust the volume of XP gain to their liking.

**Comment by IllianiCBT** [comment]
Closing as resolved (manually closing so I can more clearly see which of my tasks are still outstanding)
