### ISSUE TITLE
BA in MekHQ's mechlab has incorrect tonnage

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#436]
A unit of fenrir BA should be 2 tons each and have a total squad tonnage of 8 tons, but the mekhq mechlab shows 4.26/4 tonnage for some reason. This problem is not present when loading the BA outside of mekhq via MML.

![mekhq](https://user-images.githubusercontent.com/1191378/30147553-5a84eb76-93e2-11e7-9d33-7cc7e0068a7a.jpg)

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1283545/mekhqlog.txt)

**Comment by HammerGS** [comment]
If using the Battle Armor Weights rules from TO pg 187 the units will be 2 tons each.

We do a list of issues with MML in MekHQ and I suspect the weight issue is coming from inside MekHQ

**Comment by neoancient** [comment]
There were a total of three things wrong here:
1. The calculation for the total construction weight of the squad was leaving out one of the suits.
2. The maximum weight was taken from the weight used in MegaMek, which is a flat 1 ton/trooper unless you have the TacOps rule for varying BA weight by weight class.
3. MegaMek does not yet account for the weight of the turret mount, so these suits will still be showing 80 kg under weight until that is implemented.
