### ISSUE TITLE
RFE: Education module notes

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4361]
After playing for ten in-game years, some notes to consider: 

## 1. Better visibility for academies extant, and their courses. 
- Allow option to increase jumprange, at the cost of allowing really long transit times. 
- Separate the show inegligble and show out-of-range options, so users can toggle off academies they don't qualify for, but still show those who are simply out of range. 
- Generate an academy report that pulls from the database and provides an overview of acadamies and classes they offer. 

## 2. Primary & Boarding schools.
- Minimum age should likely be implemented for boarding schools, either 3 or 6. Sending children to boarding school as newborns is weird, but supported. This might also cut down on XP bloat, since it gives them less years to gorge on XP. 
- Alternatively, implement an age 3-6 local daycare / creche, though mechanical benefits here might be minimal. 
- Implementing homeschooling and/or local primary schools should be considered as alternative options; right now it feels like boarding school is the 'only' option, since the alternative is to leave them out of education, which feels weird. 

## 3. Non-specific civilian degree. 
- Because a lot of educations have a college-level requirement, having access to a non-specific higher civilian education is something I miss, especially because it feels off or wasteful to send them back to an academy where they gain nothing, or a skill that doesn't seem entirely suitable to them. Having an alternative that provides them with a few XP points might be nice instead.

**Comment by IllianiCBT** [comment]
> Allow option to increase jumprange, at the cost of allowing really long transit times.
In campaign options, under the education module options, there is the option to increase maximum jump radius. This increases the distance you can search for prestigious academies.

**Comment by SirChaos1** [comment]
Definitely agree with (3), and I think I agree with (2) as well.

The non-specific degree should be easy enough to implement: Add a class to the local University and/or Technical College that has "XP" as the only skill it teaches.

**Comment by IllianiCBT** [comment]
> Implementing homeschooling and/or local primary schools should be considered as alternative options; right now it feels like boarding school is the 'only' option, since the alternative is to leave them out of education, which feels weird.

So, the way things are set up, the presumption was that if personnel are not in education they are being educated by the unit. However, I can absolutely see why that hasn't been communicated very well.

**Comment by IllianiCBT** [comment]
> Generate an academy report that pulls from the database and provides an overview of acadamies and classes they offer.

I missed this, when I made the above message. I won't be doing this, but I am looking into having academies visible from as an interstellar map filter.

**Comment by IllianiCBT** [comment]
![image](https://github.com/MegaMek/mekhq/assets/103902653/66416963-3e37-4391-96ae-433d017f7b3c)

This will be available in 50.0

**Comment by IllianiCBT** [comment]
I've marked #4367 as closing this PR. #4367 covers everything in .2 and .3. The requests in .1 are not something I intend to take action on at this time. If you feel strongly about them, please create a separate PR with just those requests, so someone else can pick them up in the future. :)

**Comment by IllianiCBT** [comment]
Closing as resolved (manually closing so I can more clearly see which of my tasks are still outstanding)
