### ISSUE TITLE
ini files for windows are missing in the nightly

### ISSUE THREAD

**Issue by kuronekochomusuke** [MegaMek/mekhq#4368]
MekHQ-0.50.0-SNAPSHOT

ini files for windows are missing in the nightly

![image](https://github.com/MegaMek/mekhq/assets/116095479/24f9324e-71f2-4c64-8b5a-fc697cb56643)

**Comment by IllianiCBT** [comment]
This is currently working as intended and will be resolved as we continue to work towards the switch to j17 and the various upgrades coming as a part of that. For now, feel free to move over the .ini from 49.19.1 :)

Closing as working as intended.
