### ISSUE TITLE
ATB ambush mission generates the incorrect amount of enemy units

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#437]
By it's description, its supposed to generate 3 enemy units (and used to) but it just generated 11 enemy units for me.

[#battletech.zip](https://github.com/MegaMek/mekhq/files/1283682/battletech.zip)

**Comment by Bonepart** [comment]
I ran into this myself, I just forgot what the scenario type was, so when I did some testing I didn't see any problems. I'll look at the Ambush scenario when I get home tonight.

**Comment by Bonepart** [comment]
A quick look at the obvious trouble spots doesn't present any problems. The Ambush scenario is flagged as a special mission and generates special mission forces, so the refresh should change the opFor to match the unit deployed. I'll have to actually run it in debug when I get home to try to see where it goes wrong. I'll try to test the other special mission scenarios as well to make sure none of the others have issues.

**Comment by HammerGS** [comment]
Closed as merges.
