### ISSUE TITLE
RFE: reeducation camp documentation clarifications

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4374]
Personnel Module documenation referencing reeducation camps: 

- Turnover & Retention Module document refers to the Education Module for more information regarding reeducation camps (pg. 11). 

- Education Module document does not actually have a single heading explaining what a reeducation camp does. It refers piecemeal to seperate parts of the reeducation camp functionality, but does not provide a single overview of what this does, or how it is meant to interact. 

-> Create a single entry in Education Module that covers all these loose elements and explains interaction with Turnover & Retention module under one heading.

**Comment by IllianiCBT** [comment]
Your timing with this was perfect. I was just about to click 'push' on updated documentation. :D

**Comment by IllianiCBT** [comment]
Closing as resolved (manually closing so I can more clearly see which of my tasks are still outstanding)
