### ISSUE TITLE
[50.0] Personnel Report Counting Injured Prisoners as Support Personnel

### ISSUE THREAD

**Issue by DynamicWorlds** [MegaMek/mekhq#4386]
### Environment
0.50.0 Snapshot  (2024-7-10)
Windows 10
Java Version: 17.0.11

### Description
Personnel report seems to be counting injured prisoners as injured support personnel.
My count is 81 injured prisoners.

### Files
[Trond's Dragoons30250215C.cpnx.gz](https://github.com/user-attachments/files/16199790/Trond.s.Dragoons30250215C.cpnx.gz)
![Temp3](https://github.com/user-attachments/assets/866b6e2e-d5e5-4cf9-b8a0-b719fdb4c9b8)
[customs.zip](https://github.com/user-attachments/files/16199796/customs.zip)
[mekhq.log](https://github.com/user-attachments/files/16199805/mekhq.log)
[megamek.log](https://github.com/user-attachments/files/16199811/megamek.log)

**Comment by IllianiCBT** [comment]
Closing as resolved (manually closing to make it easier for us to see what issues still need actioning).
