### ISSUE TITLE
RFE: Prisoner defection

### ISSUE THREAD

**Issue by SirChaos1** [MegaMek/mekhq#4397]
Currently, MHQ only randomly determines if a prisoner is willing to defect as part of the AtB ruleset.

I would like to have those mechanics, or a version adjusted for the lack of AtB rules (such as those concerning enemy unit rating) available independently of AtB, so they can be used in non-AtB campaigns.

**Comment by IllianiCBT** [comment]
Closing as resolved (manually closing so I can more clearly see which of my tasks are still outstanding)
