### ISSUE TITLE
RFE: Education. Provide oppertunity to re-enroll without having to travel from and back. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4399]
In cases where students drop-out, or qualify for subsequent education from the same location, it sometimes makes sense to have the option to re-enroll immediately, without having to travel back to the company's current location, and then back again. This can otherwise take multiple months.

**Comment by IllianiCBT** [comment]
Closing as resolved (manually closing to make it easier for me to see what issues still need actioning).
