### ISSUE TITLE
Complete Mission will screw up Kill Record

### ISSUE THREAD

**Issue by kernhe** [MegaMek/mekhq#4408]
### Environment
V: MekHQ-0.50.0-SNAPSHOT
O: GNU/Linux (ubuntu 20.04.6)
J: openjdk-17-jdk (17.0.11+9-1~20.04.2)

### Description
Sorry for coming up again with a bug in the Kill count:

* Mission ended, dialog reminds me to resolve the mission
* after the retention dialog and all the awards I can only see the kills done in the last mission, every kill before this mission is gone.
  The Personal Log and Mission Log are still complete!

Before Mission Complete:
![Before](https://github.com/user-attachments/assets/ae39aa71-273d-4b3e-a178-61adf28533fd)

After Mission Complete:
![After](https://github.com/user-attachments/assets/4b96bbf2-5924-4772-87cc-35b2d0c71a59)

### Files
I will provide a clean campaign save ASAP (currently not at home), the current campaign I used for the screenshots uses too many FrankenMechs...

**Comment by repligator** [comment]
I could of sworn we had this one fixed already. See #4211

**Comment by kernhe** [comment]
> I could of sworn we had this one fixed already. See #4211

This last ticket was also from me and was related to forgetting Kills after a battle. This was fixed, so all kills accumulated correctly after each battle only to be screwed up after the mission.

This here is something different.

Problem: After ending mission multiple actions on personnel will be triggered: Retention and Awards. And one of em is buggy.
(My personal guess again: Awards)

**Comment by IllianiCBT** [comment]
Can I verify something:

When you say ‘mission’ do you mean Mission, Contract, or AtB Contract? Our language isn’t clear here, I’m aware, but it’d be helpful to know if this was an issue specific with mission-missions, as opposed to mission-contracts.

**Comment by kernhe** [comment]
I'm talking about an AtB Contract that is shown in Briefing Room as "Current Mission" with plenty of Scenarios.

Once the End Date is reached, you'll need to hit the "Complete Mission" button to select the "Outcome". And here starts the description from above.

**Comment by IllianiCBT** [comment]
Perfect, thank you. I just didn't want to be chasing situation A, if it turned out to have B or C

**Comment by IllianiCBT** [comment]
Closing as resolved (manually closing so I can more clearly see which of my tasks are still outstanding)
