### ISSUE TITLE
Darcula Flat UI Scaling Broken

### ISSUE THREAD

**Issue by Algebro7** [MegaMek/mekhq#4412]
### Environment
0.49.20
Linux (KDE Plasma DE)
OpenJDK Runtime Environment (build 17.0.11+9)

### Description
UI Scaling for the Darcula Flat theme is broken on my 3440x1440 monitor. Global scaling is set to the default 100% and other apps scale correctly, but elements in MekHQ Darcula are scaled way too big, making text unreadable in a number of instances. MekHQ Metal theme scales correctly.

Example in Darcula:

![darcula](https://github.com/user-attachments/assets/0055534e-3515-42d1-9510-4202b5e03559)

Same screen in Metal:

![metal](https://github.com/user-attachments/assets/32ff5ad8-dbe0-414c-ab1b-a212394dae9b)

**Comment by Algebro7** [comment]
I did some more digging into this today and turns out this is being caused by FlatLAF's built on HiDPI scaling. As a workaround for now I can patch the MekHQ launcher script to add `-Dflatlaf.uiScale=1` to the java command, but as a more long term solution I will probably make it configurable in the MekHQ options. I did some testing and confirmed you can switch it at runtime.

**Comment by IllianiCBT** [comment]
I _believe_ this has been fixed now. If you find time can you double-check and get back to us?

Closing for now, we can re-open if necessary.
