### ISSUE TITLE
[0.43.2-git : Feature Request] "Mass Repair/Salvage" to Ignore Units in 'Salvage' Status

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#442]
At "Mass Repair/Salvage", another option to ignore all units in 'salvage' status except those required for repairs after salvaging.

**Comment by kipstafoo** [comment]
Can you explain "except those required for repairs after salvaging", please?

**Comment by Dylan-M** [comment]
@kipstafoo He means don't salvage anything unless you need the part to fix something else.

**Comment by SirMegaV** [comment]
Actually I mean don't salvage at all. But Dylan's idea is another great
addition.

**Comment by kipstafoo** [comment]
Well, you can do this now by opening the MRMS dialog and not selecting the 'salvage' units.

I'll look at adding a flag to suppress it on 'instant mrms'

**Comment by SirMegaV** [comment]
Yup. Already doing that. I was thinking a check box option so that I don't
have to manually select every time. Just being lazy here.
