### ISSUE TITLE
RFE: Create Parts Crates to add to mission rewards and adjustment existing tables

### ISSUE THREAD

**Issue by SVNaas** [MegaMek/mekhq#4421]
This RFE follows on from conversation on the Discord.
Possible extension for mission/monthly rewards, supply crates. These would serve as an addition similar to Bonus Parts but would allow for the addition of somewhat more controlled rewards. I suggest having it use the tech availability/level dates as the basis for its list generation, as this could account for extinct/LosTech without needing as many new lists.

Inner Sphere (Random Reward)
1-10: Standard Supply Crate (1-10 Standard Tech Parts)
11-15: Advanced Supply Crate (1-8 Advanced Tech Parts)
16-19: Experimental Supply Crate (1-6 Experimental Tech Parts or if Clan Invasion era+ 10% chance of being a Clan Supply Crate)
20: Star League Supply Cache (1-4 Extinct Tech Parts)

Clan (Random Reward)
1-10: Solahma Supply Crate (1-10 Standard IS Parts)
11-15: Secondline Supply Crate (1-8 Standard Clan Parts)
16-18: Frontline Supply Crate (1-6 Advanced Clan Parts)
19: Experimental Supply Crate (1-4 Experimental Clan Parts)
20: Star League Supply Cache (1-4 Extinct Tech Parts)

Some suggested implementations of this would be to adjust the following:

Star League Cache battles:
1-6: Star League Supply Cache (no allied pilot)
7-9: Star League Mech
10: Star League Royal Mech

Monthly Rewards:
1-2: 1d6 Dependents
3-4: Recruit
5: Standard Supply Crate (1d4 on a 4 this is upgraded to an Advanced Supply Crate)
6-7: Civilian Vehicle
7: APC
8-9: Civilian Mech
10: 1d6 Bonus Parts

**Comment by IllianiCBT** [comment]
This has been implemented via the Resupply Convoys system. Closing as resolved.
