### ISSUE TITLE
RFE: Turnover & Retention - Retirement Dialogue nag on Advance Day should not actually Advance Day automatically.

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4424]
When running the Retirement Dialogue using the Advance Day nag reminder, the resolution is printed on the day it is run, and then advances to the next day immediately. This means that you need to refer to the Historical Daily Log Report if you wish to refer back to the results once the dialogue is closed. 

-> If the dialogue is run through this nag, do not automatically advance the day at resolution. 
OR
-> Results need to be posted on the following day, rather than the previous.

Use-case: 
After dialogue is run, I will frequently want to take some time to go over the retirees, and look at potential replacement personnel. In the current instance, this requires the extra step of having to refer to the Historical report that could easily be ommitted by implementing the above.

**Comment by IllianiCBT** [comment]
> -> If the dialogue is run through this nag, do not automatically advance the day at resolution.

This option isn't possible, as otherwise (without extra code support) it would trigger each time someone clicked 'advance day', even if users run the dialogue. This is actually similar to how it worked during development, which is how I know.

> -> Results need to be posted on the following day, rather than the previous.

This will require a little work, but I'll see what I can do.

**Comment by IllianiCBT** [comment]
Closing as resolved (manually closing to make it easier for me to see what issues still need actioning).
