### ISSUE TITLE
Enemy Force Generation, Transport(?) NPE.

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4429]
### Environment
Developmental
Java 17
Linux

### Description
Hit advance day in MHQ, got hit with NPE. The scenario in question was a base defense mission. After deleting the mission, I got hit with another defense mission the next week, which triggered the NPE again.
`17:49:24,733 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$1(MekHQ.java:280) - Uncaught Exception Detected
java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because "requiredRoles" is null
	at mekhq.campaign.mission.AtBDynamicScenarioFactory.fillTransports(AtBDynamicScenarioFactory.java:1436)`

### Files
[mekhq.log](https://github.com/user-attachments/files/16275100/mekhq.log)
[Autosave-1-Fronc Marshals-30710430.cpnx.gz](https://github.com/user-attachments/files/16275102/Autosave-1-Fronc.Marshals-30710430.cpnx.gz)
[NPE-Fronc Marshals30710501.cpnx.gz](https://github.com/user-attachments/files/16275103/NPE-Fronc.Marshals30710501.cpnx.gz)

**Comment by IllianiCBT** [comment]
@SuperStucco this looks like it might be related to your recent force generation changes
