### ISSUE TITLE
StratCon - Right clicking the location of a hidden enemy base during integrated command throws NPE

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4430]
### Environment
Master (Latest PR https://github.com/MegaMek/mekhq/pull/4478)
Java 17
Linux

### Description
Load the attached save and right click hex 0301 on the StratCon map.

`18:01:35,165 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$1(MekHQ.java:280) - Uncaught Exception Detected
java.lang.NullPointerException: Cannot invoke "mekhq.campaign.mission.AtBDynamicScenario.isCloaked()" because the return value of "mekhq.campaign.stratcon.StratconScenario.getBackingScenario()" is null`

### Files
[Stratcon-right-click-npe-Fronc Marshals30710523.cpnx.gz](https://github.com/user-attachments/files/16275151/Stratcon-right-click-npe-Fronc.Marshals30710523.cpnx.gz)
[mekhq.log](https://github.com/user-attachments/files/16275150/mekhq.log)

**Comment by IllianiCBT** [comment]
Closing as resolved
