### ISSUE TITLE
Custom award set not displaying medals

### ISSUE THREAD

**Issue by Stm316** [MegaMek/mekhq#4448]
### Environment
MekHq Nightly build 1558
19:50:30,130 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:303) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-07-20T01:15:24.980782824
    Today: 2024-07-21
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.11
    Platform: Windows 10 10.0 (amd64)
    System Locale: en_AU
    Total memory available to MekHQ: 4 GB
    MM Code Revision: Unknown
    MML Code Revision: Unknown
    MHQ Code Revision: Unknown

### Description
Award sets now require the presence of the "Ribbon" tag. Previous builds up to 1554  would show the medal without the tag being present. Adding said tag to each section of the xml made it show the medal. If the tag is not present, it's image is not shown despite the log entry being there. The tag does not need to contain data, as shown below.
Describe the issue and provide screenshots ingame if able.
![1x](https://github.com/user-attachments/assets/4938c55c-dcdd-4262-8ac7-d361888ff0c8)

In the image above, line 32 "Warrior" will be displayed in-game, line 43 "Point Commander" will not.
![2x](https://github.com/user-attachments/assets/4aae52e0-1cff-4604-b4dd-3b1dae7f5a99)

### Files
Zip archive containing custom award xml file, award art, and campaign save.
[Files.zip](https://github.com/user-attachments/files/16323878/Files.zip)
A new campaign, for minimal file size.

**Comment by IllianiCBT** [comment]
Closing as resolved (manually closing to make it easier for me to see what issues still need actioning).
