### ISSUE TITLE
RFE: Education Module - format certain text in report log to provide better at-a-glance clarity.

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4449]
When managing reports, some messages lack visual distinction which could be improved for at-a-glance clarity. 
This is specifically important for unusual outcomes that are not the 'expected' message, such as failures, drop outs, and so on. 
When processing multiple of these, being able to at-a-glance see which one of these messages is out-of-the-ordinary helps; this is the same logic that is used in the maintenance report logs, where good/bad results are colour-coded. 

_Some specific examples:_ 
John Doe considered dropping out, but was convinced [...]
Jane Example ***has dropped out***, and [...]
Mike Random graduated from [...]
Josh Lastname ***failed to graduate*** [...]
Cherry Picking graduated ***with honors*** [...]

Formatting here just for clarity; recommend using only bold, or negative/positive colour-coding.

**Comment by IllianiCBT** [comment]
Great idea!

**Comment by IllianiCBT** [comment]
Closing as resolved (manually closing to make it easier for me to see what issues still need actioning).
