### ISSUE TITLE
RFE: Disambiguate salvage, salvage, salvage, salvage, and salavage.

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4450]
There are currently 4+ meanings (some of which overlap) of the word salvage in MHQ. This makes things really confusing. This RFE proposes changing and/or clarifying some of the salvages, without contradicting BT:CO. Strip/stripping/stripped and destroyed are both terms within BT:CO that apply in the following circumstances. Other ideas are very much welcome.

- [ ] Under **Repair Status** change **Salvage** to **Salvage (Strip for Parts)**
- [ ] Under the post-battle screen change the **Salvage** status to **Destroyed (Salvage for Parts Only)**

**Comment by SirChaos1** [comment]
The act of salvaging destroyed/abandoned/knocked-out enemy units could be renamed to "Recover".

I prefer "Wrecked" to "Destroyed" for the unit state, since MM already uses "destroyed" for when a unit is taken out of play.

The repair status could be just "Strip for Parts", to minimize appearances of the word "Salvage".

**Comment by repligator** [comment]
> I prefer "Wrecked" to "Destroyed" for the unit state, since MM already uses "destroyed" for when a unit is taken out of play.

Unfortunately 'wreck' is already used in a contradictory fashion in CO. "_A wreck can be removed from
the field to be repaired or stripped down later..._" (Page 214, 4th Printing). Interestingly, CO also acknowledges the two different meanings of destroyed under the section _Destroyed vs. Truly Destroyed_ on page 197.

**Comment by gsparks3** [comment]
"Unrepairable" could be used for the unit status in the hangar corresponding to Truly Destroyed in CO. Gets the meaning across clearly and concisely.

**Comment by IllianiCBT** [comment]
Closing as resolved (manually closing to make it easier for me to see what issues still need actioning).
