### ISSUE TITLE
BA Advanced Armor (IS) is missing from the purchase parts screen

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#446]
With the tech level set to unofficial, BA advanced armor (IS) is missing from the purchase parts screen and the repair bay claims it is extinct. I tried turning "disallow extinct units/parts" off and setting the campaign year to 3145, and it made no difference, the part is still missing and cannot be purchased. It should not be "extinct" at this point, and it seems mekhq thinks that it is permanently extinct regardless of the tech level or year.

[#battletech.zip](https://github.com/MegaMek/mekhq/files/1291486/battletech.zip)

**Comment by neoancient** [comment]
This is working now. Most likely fixed in MegaMek/megamek@cc1f030
