### ISSUE TITLE
Significant amount of company mysteriously vanished

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4481]
### Environment
Master (last PR https://github.com/MegaMek/mekhq/pull/4478)
Java 17
Linux

### Description
Something like 1/3rd of my company has vanished into thin air.  Tons of log entries along the lines of

`08:59:50,875 WARN  [mekhq.io.idReferenceClasses.PersonIdReference] {SwingWorker-pool-2-thread-2}
mekhq.io.idReferenceClasses.PersonIdReference.fixGenealogyReferences(PersonIdReference.java:57) - Failed to find the spouse for Deputy Heather Shurpali with id e0815b6d-294b-49b4-9780-038dabc0785c`

`08:59:50,890 ERROR [mekhq.campaign.unit.Unit] {SwingWorker-pool-2-thread-2}
mekhq.campaign.unit.Unit.fixReferences(Unit.java:5624) - Unit 7f091ffe-2ee1-44f5-b4a1-6aeeaaa21920 ('Warhammer WHM-9D') references missing gunner 5f67fb38-f210-47b2-8553-74a9af3ee3bd`

When manually examining the save file, they still seem to be present though...
![Screenshot_20240724_090620](https://github.com/user-attachments/assets/b199bfa6-43ad-456d-b0bf-bc713587e97c)

### Files
(last save with everyone accounted for)
[Fronc Marshals30761214.cpnx.gz](https://github.com/user-attachments/files/16362456/Fronc.Marshals30761214.cpnx.gz)

[mekhq.log](https://github.com/user-attachments/files/16362427/mekhq.log)
[Fronc Marshals30770101.cpnx.gz](https://github.com/user-attachments/files/16362455/Fronc.Marshals30770101.cpnx.gz)

**Comment by IllianiCBT** [comment]
This means the missing characters are failing to load for some reason. Most likely they have a stored variable that is failing to unmarshel. I won’t have time to look into this today, so if someone else can that would be amazing. If not, I’ll investigate first thing tomorrow.
