### ISSUE TITLE
RFE: Enable Copy/Paste Functionality in XP Table and Rank Table Campaign Settings Dialogues

### ISSUE THREAD

**Issue by UlyssesSockdrawer** [MegaMek/mekhq#4483]
### Description

User story:

As a: MekHQ campaign player,

I want: the ability to copy/paste text in tables when setting up a new campaign,

So that: my new campaign setup experience is streamlined and I get to the action more quickly.

---

When setting up a new campaign in MekHQ, the XP table and Rank table dialogues do not currently support copy/paste.

This means that when configuring XP requirements or setting up complex custom rank structures, each new field must be hand typed. This slows down the user's campaign set up and increases the chance of errors creeping in and the need to redo settings later.

Supporting copy/paste in these fields would improve UX when creating a new campaign.

---

ACs:

GIVEN: I am setting up a new MHQ campaign,

WHEN: I am editing the XP table,

THEN: I am able to copy/paste values from external programmes or from field to field inside the MHQ dialogue

GIVEN: I am setting up a new MHQ campaign,

WHEN: I am editing the Rank table for custom ranks,

THEN:  I am able to copy/paste values from external programmes or from field to field inside the MHQ dialogue

**Comment by IllianiCBT** [comment]
Can you explain what you mean by 'copy/paste', because I just went to check some functionality and I was able to copy & paste data into the various XP cost cells.

**Comment by UlyssesSockdrawer** [comment]
Interesting - last time I tried to copy/paste into, or from say Cell A to Cell B it didn't work using Ctrl+C / Ctrl+V.

I'll give it a test tomorrow morning in MHQ with a new campaign and see if somebody fixed it in a more recent version than I've set a campaign up on.

**Comment by IllianiCBT** [comment]
It's worth noting I am testing this on 50.0, but I don't remember any changes having been done (at least not since the launch of 49.19.0, maybe even 49.18)

**Comment by IllianiCBT** [comment]
Actually, my memory is making a liar of me: I made changes to how the table was displayed in 49.20. I wonder if that had an unintended knock-on effect of allowing values to be copy-pasted in?

**Comment by UlyssesSockdrawer** [comment]
Maybe - I'm not set up with the branches to try out at the minute. Does the inadvertent change also let you copy/paste between cells in the table?

**Comment by IllianiCBT** [comment]
I can double-click the contents of the cell, select the text, copy it; enter another cell and paste that data. If that's what you mean. :)

**Comment by UlyssesSockdrawer** [comment]
Perfect, sounds like this can be closed with 0.5/whatever milestone comes from 49.20.whatever :D

**Comment by IllianiCBT** [comment]
Closing as (accidentally) resolved
