### ISSUE TITLE
Mekhq meklab : location boxes dissapear

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#449]
With 43.3, after allocating a component to a location (e.g. flamer to front), the location boxes all dissapear until you switch tabs in the meklab. This happens even on a fresh campaign file.

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1299104/mekhqlog.txt)

![mekhq](https://user-images.githubusercontent.com/1191378/30372743-1b38a9c8-98c2-11e7-9599-68768e652b3e.jpg)

**Comment by neoancient** [comment]
Cannot duplicate. There has been some work on the MML integration after the gui rework in MML and I'm going to presume this resolved.
