### ISSUE TITLE
Use the Exclude Large Craft from Share Value to Exclude LCs from IO% payment

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#45]
Currently, you can exclude LCs from Share Values. There is no way to exclude the value of LCs using IO % payment rules.

**Comment by pheonixstorm** [comment]
Thats the case in non AtB games as well so this isn't an atb issue but more of an IO payments issue and one I want to eventually fix if ralgith doesn't get to it first.

**Comment by pheonixstorm** [comment]
I have a fix for this in my Peacetime Operating Costs branch but still testing all of it. If it continues to perform properly I will see if I can break it out to its own branch and post a PR

**Comment by pheonixstorm** [comment]
@hammer this can be closed now that peacetime cost PR has been merged

**Comment by HammerGS** [comment]
Closed.
