### ISSUE TITLE
Mekhq meklab : Unit statistics panel no longer updates

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#450]
In 43.3, the unit statistics panel no longer updates until you switch tabs in the meklab. This happens even on a fresh campaign file.

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1299113/mekhqlog.txt)

![mekhq2](https://user-images.githubusercontent.com/1191378/30372900-c7a81bee-98c2-11e7-8346-b9e196e61978.jpg)

**Comment by neoancient** [comment]
This is no longer an issue.
