### ISSUE TITLE
[RFE] - End of Contract Prisoner Nag and Defectors

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#4505]
This very helpful End of Contract Nag reminds you to ransom or free them.  

But I believe it should exclude people willing to defect (the *Prisoners).  

Or perhaps some other handling?  A pop up before the Nag "the following people are willing to defect, would you like to hire them?"  Simiar to the Awards screen. 
 But that's gui work and might be a pain.  

But at the least excluding them from the ransom/free dialog would be helpful. Thank you.

**Comment by IllianiCBT** [comment]
I think what I'll do is fire a dialog that warns there are prisoners willing to defect and ask for confirmation from the user to continue.

I don't think a blanket 'recruit all' is valuable, especially if using Loyalty and Personalities (more so once random events are online).

**Comment by gsparks3** [comment]
Personally I would want a "Ransom/free all prisoners unwilling to defect" button in the nag; don't know how difficult that would be to arrange.

**Comment by IllianiCBT** [comment]
Closing as resolved
