### ISSUE TITLE
[0.50.0-SNAPSHOT] AutoAward misinterprets TOE for formation kills

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4514]
### Environment
15:48:19,393 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:143) - Starting MegaMek v0.50.0-SNAPSHOT
    Build Date: 2024-07-27T01:16:03.359732465
    Today: 2024-07-29
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MegaMek: 4 GB
    MM Code Revision: e86f08fde087d229498e46e9697a41466897653e
    MML Code Revision: bea7884b61319d3b2c803a0fa65988008638e6ef
    MHQ Code Revision: 12c84d7d4a3a993ac643cdf58ba9b621a907170c
    
### Description
When running AutoAwards, formation kill awards are given out to units that do not qualify as being part of the formation. 
This includes units qualifying for lance kills outside their lance, company kills outside their company, etc. 

This can easily be observed when looking at infantry and aerospace support units that are getting kill qualifiers despite being two - three forces separated, even when observing strict individual unit < lance < company < battalion < regiment force containers across the TOE. 

![image](https://github.com/user-attachments/assets/56616a5e-e4ff-41a7-814a-d34739c9cf7d)

### Files
[CampaignSave.zip](https://github.com/user-attachments/files/16414852/CampaignSave.zip)
[custom mechfiles.zip](https://github.com/user-attachments/files/16414872/custom.mechfiles.zip)

**Comment by Tzahr** [comment]
Unfortunately not. I noticed it only when I was looking through my TO&E much later, and unfortunately it's a slightly difficult bug to replicate. If I play more today and get another end-of-contract reward prompt, I'll provide saves before and after, with logs. 

It's also visible on the BA and dropships.

**Comment by IllianiCBT** [comment]
To be able to easily investigate this I could do with the following:

- a save prior to the scenario
- the scenario results file (the one you stick into mhq when manually resolving a scenario)

That will allow me to throw together tests substantially faster than if I had to manually play through the scenario. Especially as you can't save a results file if you have Princess playing against herself.

If you can provide those two things I should be able to get this fixed relatively easily. It's like just a parsing error given how little programming experience I had when I wrote that.

**Comment by IllianiCBT** [comment]
I should also add an option to tell autoAwards to treat the Force furthest from the Origin as a `x` rather than always assuming it's a Lance.

**Comment by IllianiCBT** [comment]
Actually, ignore the above. So long as your save is mid-contract I should be able to replicate the issue pretty reliably even without scenario logs.

I do want to verify though: are the kill credits that are being incorrectly applied relating to scenario kills (kills across a single scenario) or mission kills (kills across a single mission)?

**Comment by IllianiCBT** [comment]
Commenting here because I'm in bed and I will forget this by tomorrow:

To reliably resolve this bug (and remove future weirdness) the smartest thing to do is to see whether it's possible at add a new stored variable to Forces that designates then as a Lance, Company, whatever. Then give the user the ability to assign this information to the Force, along with having some gui element (probably the force information pane) to show what it's classed as.

Then, on advance day, nag the user if there are nodes that haven't been assigned a TO&E level.

The feasibility of this comes down to how we store Force characteristics. If I'm lucky it'll just be a case of adding a couple of lines to Force.java, but somehow I doubt I'm that lucky.

**Comment by IllianiCBT** [comment]
I got curious and clambered out to bed to check, but this does actually look very feasible.

Actions I will need to do tomorrow:
- create formation enum (including support for IS, Clan, & CS factions)
- add force level value to `Force.java` including an array of getters and setters
- modify the force pane to display force level, if force level isn't `null`
- add right-click actions (restricted to origin node - the one that normally is named after the campaign) that allows you to specify what formation level the origin node is. 
- add method to assign formation levels (company, lance, etc) to all nodes below the origin node. i.e. if the player has set the origin node as 'Battalion' then the next layer gets assigned as 'Company', then the next layer gets assigned as 'Lance'.
- add an advance day nag to inform the player that they need to specify the force level of the origin node if the force level of the origin node is unassigned when advance day is prompted.
- add a new day action that re-assigns force levels across the TO&E (based on force level of origin node), to catch instances where the TO&E is modified.

Optional
If we can do the below it removes the need to have a On New Day action.
- add 'assign force level' action when adding new force (based on distance from origin node)
- add 're-evaluate force levels' action when moving forces around the TO&E
- add 're-evaluate force levels' action when removing forces from the TO&E

**Comment by Tzahr** [comment]
I finished a contract with plenty of kills. 
Here is a save pre- and post contract end. 
You can see loads of BA and Dropship crews qualifying for Lance kills. 
Custom folder linked above still required. 

[mekhq.log](https://github.com/user-attachments/files/16433513/mekhq.log)
[Pre&post contract saves.zip](https://github.com/user-attachments/files/16433517/Pre.post.contract.saves.zip)

**Comment by IllianiCBT** [comment]
I’m currently in the process of (accidentally) overhauling relationships, but once that’s finished I’m planning to go with the plan outlined above. I think that’s the best move atm, and opens the gate for a lot more intuitive programming when it comes to handling formation levels

**Comment by IllianiCBT** [comment]
> I finished a contract with plenty of kills. Here is a save pre- and post contract end. You can see loads of BA and Dropship crews qualifying for Lance kills. Custom folder linked above still required.
> 
> [mekhq.log](https://github.com/user-attachments/files/16433513/mekhq.log) [Pre&post contract saves.zip](https://github.com/user-attachments/files/16433517/Pre.post.contract.saves.zip)

![image](https://github.com/user-attachments/assets/7d69a4d1-f691-49e6-ad88-7568c4153bba)
 getting this error when I try to extract that archive

**Comment by Tzahr** [comment]
[Pre&post_saves.zip](https://github.com/user-attachments/files/16462795/Pre.post_saves.zip)

This should be more functional.

**Comment by Tzahr** [comment]
I ran a test on a specific build for @IllianiCBT - going to load the files up here. I ran an entire contract to the end, played all the fights, and scored kills across multiple lances. Should give a decent spread for AutoAwards to hook into.
Unfortunately, on the test build I ran, once I ended contract and waited for AutoAwards to start, the application froze up.

14:43:59,025 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:303) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-08-02T00:00:00.884215158
    Today: 2024-08-04
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MekHQ: 8 GB
    MM Code Revision: f21a917389c702d8d08f06d91bc464860d17b985
    MML Code Revision: 4dae110a07fec0db6ca297a829c6f7ea08a97533
    MHQ Code Revision: 34f09adaf8927663302d65e077f41c3750a7578a

[1st Rimward Hussars_PreContractEnd.zip](https://github.com/user-attachments/files/16487890/1st.Rimward.Hussars_PreContractEnd.zip)
[customs.zip](https://github.com/user-attachments/files/16487899/customs.zip)
[mekhq.log](https://github.com/user-attachments/files/16487894/mekhq.log)

**Comment by repligator** [comment]
> I ran a test on a specific build for @IllianiCBT - going to load the files up here. I ran an entire contract to the end, played all the fights, and scored kills across multiple lances. Should give a decent spread for AutoAwards to hook into. Unfortunately, on the test build I ran, once I ended contract and waited for AutoAwards to start, the application froze up.
> 
> [1st Rimward Hussars_PreContractEnd.zip](https://github.com/user-attachments/files/16487890/1st.Rimward.Hussars_PreContractEnd.zip) [customs.zip](https://github.com/user-attachments/files/16487899/customs.zip) [mekhq.log](https://github.com/user-attachments/files/16487894/mekhq.log)

I'll look into this when I get a chance, but I think that the odds are pretty good that it's looping over the commanding officer endlessly, see https://github.com/MegaMek/mekhq/pull/4539#issuecomment-2266744203

**Comment by repligator** [comment]
Well, I was partially right. It's stuck on one person, but it's not stuck on the overall commander. It's stuck on Jia "Citizen" Shen. Looks like it will get stuck on whoever is the first pilot in the first lance of the first company of the first battalion.

**Comment by IllianiCBT** [comment]
Which is odd, because in testing that wasn’t an issue. Which means something unforeseen is going on.

**Comment by IllianiCBT** [comment]
Closing as resolved
