### ISSUE TITLE
AtB contract search radius doesn't do much

### ISSUE THREAD

**Issue by jslater89** [MegaMek/mekhq#452]
Looking at the code, it appears that it's only used to limit employers—any faction with a controlled world within contract-search-radius light-years is included in the possible employers list, and any border planet controlled by an employer is a possible contract destination.

It seems reasonable to also limit destination worlds by the search radius.

**Comment by purpledragon2** [comment]
I would say, if possible, have the destination worlds on a separate search radius.  Maybe have the search radius be from the employer's "hiring" planet.

**Comment by NickAragua** [comment]
Fixed with PR #465
