### ISSUE TITLE
[RFE] Education: Children born to parents at school should stay with the parent until they return

### ISSUE THREAD

**Issue by azhais** [MegaMek/mekhq#4522]
### Description
Per request in Discord: Currently babies just magically teleport back to your company if their mother is at school when they give birth.   It would be nice if children stayed with their parent until they return from school/had the option of being sent straight to boarding school or something.

**Comment by IllianiCBT** [comment]
This is going to be a thorny problem to solve, so I'm open to suggestions

**Comment by HammerGS** [comment]
Could you just drop the mother out when the pregnancy happens and have them return to the unit.

**Comment by IllianiCBT** [comment]
The isn't isn't with them getting pregnant while at an academy - that I can resolve easily - it's the issue of what to do with the kid when they give birth while away from the unit. As currently, the kid just magically teleports from their parent back to the unit. Any method I can think of, to have the kid stay with the parent, requires some really hacky code that I'm not comfortable implementing.
