### ISSUE TITLE
[0.50.0-SNAPSHOT] Recurring semi-random NPE when selecting multiple personnel and opening context menu. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4532]
### Environment
02:10:46,326 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:303) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-07-27T01:16:03.359732465
    Today: 2024-08-01
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MekHQ: 4 GB
    MM Code Revision: e86f08fde087d229498e46e9697a41466897653e
    MML Code Revision: bea7884b61319d3b2c803a0fa65988008638e6ef
    MHQ Code Revision: 12c84d7d4a3a993ac643cdf58ba9b621a907170c

### Description
When selecting multiple personnel and opening the context / right-click menu, occasionally an NPE error occurs.
This happens with high frequency, but also seems inconsistent, as sometimes the same personnel groups do not produce errors, and sometimes they does. 

The log attached notes several of these errors at the bottom, which concurred with my testing: 
->  java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "faction" is null

I have also provided the campaign save, since I suspect this might be related to a specific time period. 

### Files
[mekhq.log](https://github.com/user-attachments/files/16448256/mekhq.log)
[Savegame.zip](https://github.com/user-attachments/files/16448258/Savegame.zip)
[custom mechfiles.zip](https://github.com/user-attachments/files/16414872/custom.mechfiles.zip)

**Comment by IllianiCBT** [comment]
This is an education module bug. It's trying to parse what academy options are available for the selected personnel, but is running into a `null` faction.

**Comment by IllianiCBT** [comment]
Closing as resolved
