### ISSUE TITLE
[0.50.0-SNAPSHOT] Specific lance consistently has buggy deployments using StratCon. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4533]
### Environment
02:10:46,326 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:303) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-07-27T01:16:03.359732465
    Today: 2024-08-01
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MekHQ: 4 GB
    MM Code Revision: e86f08fde087d229498e46e9697a41466897653e
    MML Code Revision: bea7884b61319d3b2c803a0fa65988008638e6ef
    MHQ Code Revision: 12c84d7d4a3a993ac643cdf58ba9b621a907170c

### Description
This specific formation consistently fails to deploy using the StratCon menu.
When the unit is assigned to a deployment, it will show as deployed, but fail to actually load into the lobby. 
When the campaign is subsequently reloaded, they appear as below in the Briefing Room outliner:
![image](https://github.com/user-attachments/assets/2033a299-9b85-494e-a83d-b5837111bc2c)

However, when loading into the lobby, they do not actually duplicate, but also fail to reinforce as a single unit.
Commonly the Nightstar (3/5) with have a different round deployment as the other three machines, which leads me to observe the unit is being treated as individuals, instead of as a reinforcing lance.

I am flagging this one specifically because it has occured with this lance repeatedly, leading me to believe it might be an useful in tracking down whatever causes this sort of behaviour for StratCon deployments in general. I am uncertain if this also happens when they are the only unit deploying, and I will append an observation if I have the oppertunity to test it. 

### Files
[mekhq.log](https://github.com/user-attachments/files/16448256/mekhq.log)
[Savegame.zip](https://github.com/user-attachments/files/16448258/Savegame.zip)
[custom mechfiles.zip](https://github.com/user-attachments/files/16414872/custom.mechfiles.zip)

**Comment by Tzahr** [comment]
Deployed the lance alone through StratCon, and now I don't have the option to start the game, even though it is the due date for the contract.

![image](https://github.com/user-attachments/assets/2c2456b5-05a0-4b94-8e5e-677e8bcd63b9)

When reloading the save, I get the same behaviour as before.

![image](https://github.com/user-attachments/assets/5166e9d2-0903-42e4-8c75-61fc7bdc0f10)

When actually loading in the lobby, the unit seems to load as an auxiliary or reinforcement lance, and not a main force. Note the different deployment times per unit (instead of deploying as a single lance). 
![image](https://github.com/user-attachments/assets/524332ec-0a5e-4eb9-b7e1-693fe6a9184e)


Save for replication purposes:
[WeirdLance.zip](https://github.com/user-attachments/files/16464047/WeirdLance.zip)
[mekhq.log](https://github.com/user-attachments/files/16464050/mekhq.log)

**Comment by Thom293** [comment]
Longshot, but did one of your mechs have a pilot die in it at any point?  

Here is an option to test:  remove all of those mechs and GMReplace them and put back in lance and they again.  If you had a death, try just that one first.

**Comment by Tzahr** [comment]
All units in this lance were brand new, and they've been having deployment issues since the start.
I removed all of them, and GM re-added them, but encounter the same issue. I have also re-made their formation, but the same problem persists.

**Comment by Thom293** [comment]
You could also try swapping pilots completely and see what happens.  Switch this lance pilots for another. 

I can't look right now but I think there is another BR about settings persisting between games.  I thought it was fixed.  But maybe this is something else.

**Comment by Tzahr** [comment]
Alright, good idea!
I swapped the pilots for an entirely different set of pilots.
Then I tried to assign the force to a mission. It first threw me an NPE, and then I still had the same issues as described above. Force wouldn't deploy, and on a reload, they'd show double on the Mission Briefing panel, and then deploy as if they were loose units again. It's been truly baffling.

**Comment by RaozSpaz** [comment]
Stupid question and I assume the answer is no
Do you have the rule that limits lances based on weight turned on?

**Comment by Tzahr** [comment]
I do not, but that's good thinking. 
I'm going to try and load up a new campaign later and replicate the lance, and see if the same issue happens there.

**Comment by Thom293** [comment]
Are they custom units?  This one is truly odd.

**Comment by Tzahr** [comment]
Only the Flashman is a custom variant, the others are canon. 

I tried rolling the same lance in a different campaign and experienced no issues there. 
I'm wonder if perhaps it may be a force-related bug.

**Comment by Tzahr** [comment]
I ended up tearing down my entire TOE and rebuilding it from scratch, which does seem to have resolved this issue. 
This is odd, since I had disbanded and reformed the specific lance in question before, and continued having the same issue. 

As it stands, tabula rasa seems to have worked as a resolution.
