### ISSUE TITLE
[0.50.0-SNAPSHOT] Recent Nightly causes certain fonts to be much smaller using flat themes.

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4537]
### Environment
01:20:27,289 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:303) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-08-01T01:24:10.210831282
    Today: 2024-08-02
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MekHQ: 4 GB
    MM Code Revision: f21a917389c702d8d08f06d91bc464860d17b985
    MML Code Revision: 4dae110a07fec0db6ca297a829c6f7ea08a97533
    MHQ Code Revision: 95426bd9cbf247afa83ce51ca723c3a49173f5d6

### Description
Flat themes cause certain fonts to scale smaller than in previous versions, causing reading difficulties. 
This is especially visible in the Repair Bay where Tasks and Techs text is much smaller than expected. 
This issue was not present previously, and is compounded by my ultrawide monitor. 

![image](https://github.com/user-attachments/assets/5cf31a7a-9258-405b-b301-c26799e21b0d)
![image](https://github.com/user-attachments/assets/10e8753e-d6a9-4556-8912-22ed6a13b5c2)

### Files
[mekhq.log](https://github.com/user-attachments/files/16462748/mekhq.log)

**Comment by IllianiCBT** [comment]
Closed as resolved
