### ISSUE TITLE
RFE: Personnel tab display mode "Personality"

### ISSUE THREAD

**Issue by SirChaos1** [MegaMek/mekhq#4543]
I would like to see an additional display mode in the personnel tab that shows characters´ personality traits, their intelligence and their loyalty; right now it is impossible to sort for any of these, or get an overview without looking at each person individually. With intelligence and loyalty in particular, there are times when it would be useful to sort for them, such as to find good education candidates.

**Comment by IllianiCBT** [comment]
Adding a note for future Illiani: it would be helpful to have Intelligence shown as an int somewhere, to aid sortability. As right now, with it being an adjective the only sorting available would be alphabetically.

**Comment by IllianiCBT** [comment]
Closing as resolved
