### ISSUE TITLE
50.00 - Nightly OID Version - Right Click on Multi-selected dependants NPE

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#4546]
Title.  

Go to personnel tab, select child, highlight all 3, right click, got an NPE.  Repeatable.

Screen:
![image](https://github.com/user-attachments/assets/ac236b75-616b-4fee-bf62-5bfbf4a37c29)

Log  & Save.

[mekhq.log](https://github.com/user-attachments/files/16486690/mekhq.log)
[No ID30750104.cpnx.gz](https://github.com/user-attachments/files/16486693/No.ID30750104.cpnx.gz)

**Comment by IllianiCBT** [comment]
There should be a fix ready for this, when I get a chance I’ll double-check the fix resolves your instance too :)

**Comment by IllianiCBT** [comment]
Confirmed fixed by #4542, closing as resolved
