### ISSUE TITLE
[0.50.0-SNAPSHOT] - Education: doctorate graduates appearing with 'finished Master degree' announcements, not receiving Dr title prefix. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4548]
### Environment
23:27:46,531 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:303) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-08-04T01:23:25.882857488
    Today: 2024-08-04
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MekHQ: 8 GB
    MM Code Revision: 0f0d10d35f6bbc190c42be24563140865de228c5
    MML Code Revision: 35aa5ce66ca59272c0d1e05c3d174cd4c0335b3c
    MHQ Code Revision: 76e9cea125956ab9a9d8af389ee60c2bb2eca81d

### Description
Students graduating a doctorate-level education graduate with an announcement declaring they're earned their Master degree, while also not getting the titular Dr prefix. 
In addition, the Master degree announcement is colour-coded red instead of the expected green. 

Will append a screenshot if I spot it happening a second time.

**Comment by Tzahr** [comment]
The bug in the flesh: 

![image](https://github.com/user-attachments/assets/70486fc1-5bc9-4c76-9b73-0b4a749d924d)
![image](https://github.com/user-attachments/assets/39a37193-7d68-4d99-9481-d89327e27702)

**Comment by IllianiCBT** [comment]
Fixed as resolved. Fix will be in tomorrow's nightly.
