### ISSUE TITLE
[0.50.0-SNAPSHOT] TOE Formation Types does not detect lowest formation containers as Lances. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4549]
### Environment
03:00:27,851 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:303) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-08-04T01:23:25.882857488
    Today: 2024-08-05
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MekHQ: 8 GB
    MM Code Revision: 0f0d10d35f6bbc190c42be24563140865de228c5
    MML Code Revision: 35aa5ce66ca59272c0d1e05c3d174cd4c0335b3c
    MHQ Code Revision: 76e9cea125956ab9a9d8af389ee60c2bb2eca81d

### Description
The TOE correctly notes Formationn Type based on container hierarchy, but seems to lose track of what lances are in a formation of sufficient size, even if the formation is set-up entirely correctly. In my case, my unit is composed of a combat battalion and an aerospace battalion. It marks every containter correctly: regiment -> battalion -> company, but notes forces lower than this as 'Formation Type: None'. 

Potential relation to #4514. 

### Files
[1st Rimward Hussars.zip](https://github.com/user-attachments/files/16489632/1st.Rimward.Hussars.zip)
[customs.zip](https://github.com/user-attachments/files/16489634/customs.zip)
[mekhq.log](https://github.com/user-attachments/files/16489638/mekhq.log)

**Comment by IllianiCBT** [comment]
Closed as resolved. The fix will be in tomorrow's nightly.
