### ISSUE TITLE
50.00 - RFE: Remove/Recolor "Current Objectives" Pane, or use it to display weekly battles

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#4552]
The current objectives pane is used and needed for Story Arcs.  It has no purpose in MHQ.  And because it doesnt seem to take a theme color, its this glaring white (unnecessary) block in the middle of the home screen.

Suggestions:
1.  Remove it as Unnecessary;
2. Make it take the theme color so its less annoying;
3. Have it display the current weekly battles from the Briefing Tab, updated weekly, so it serves an actual purpose. (and if it remains, take the theme color).

Thank you.

![image](https://github.com/user-attachments/assets/afc3aef6-e4ac-4a6e-9da6-ed2f6de4cd1b)
 
Could display this part from the briefing tab, for just the current week:

![image](https://github.com/user-attachments/assets/5ba37c01-c32e-4b83-83bc-4053bfd09820)

**Comment by IllianiCBT** [comment]
Closing as resolved
