### ISSUE TITLE
RFE: Education - Prevent injured personnel from being sent on educations.

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4555]
Currently it is possible to send injured personnel to educations, during which the injuries will freeze without progressing.
On their return, their treatment continues normally. 
This anomaly can be prevented by stopping injured personnel from being sent on educations.

**Comment by johnboyjjb** [comment]
I don't know if the problem of healing stopping while shipped out to education is the best solution here.

**Comment by Tzahr** [comment]
It's not suggested as a solution. It's what's currently happening.

**Comment by johnboyjjb** [comment]
My writing was an incomplete thought. 

I was meaning - There are instances where healing and education would be a preferred option and there are instances where they should be incompatible. 
Minor cuts, sprains, bruising - sure.
Probably not a lot of learning during spine surgery.

**Comment by IllianiCBT** [comment]
Don't forget that Advanced Medical isn't something everyone uses, and as an unofficial system will eventually be superseded by CamOps Medical. So any changes need to keep that in mind. A blanket 'injured? no school for you' approach is the best approach here, imo.

**Comment by SirChaos1** [comment]
FWIW, healing is also frozen without Advanced Medical.

I agree that "no education while injured" is the best approach. We might want to consider barring pregnant characters from at least military education, too.

**Comment by IllianiCBT** [comment]
Yeah, barring pregnant personnel is something I’m considering, as a resolution to (or more accurately, a papering over) #4522.

**Comment by johnboyjjb** [comment]
It would be funny if pregnant people didn't progress in their pregnancy while at school - unless that is also what you are saying. Again, if I have a person on staff who is medically unable, because they are pregnant, a 10 week education course seems like a great way to multitask them.

**Comment by IllianiCBT** [comment]
I am definitely not suggesting that, though the thought (briefly) did occur to me.

While I agree that sending someone on an education course is a great way to multi-task them, we have the measure the benefits against the capabilities of the system. I am strongly veering towards blocking pregnant personnel from attending non-unit education, simply due to the limitations of mhq (unless I want to write reels of special handlers for this, which I something I want to avoid).

**Comment by IllianiCBT** [comment]
Closing as resolved
