### ISSUE TITLE
[0.50.0-SNAPSHOT] Education  - Re-enroll options shows 'nothing more to learn' on drop-outs from military academies

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4557]
### Environment
22:22:36,069 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:303) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-08-04T01:23:25.882857488
    Today: 2024-08-05
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MekHQ: 8 GB
    MM Code Revision: 0f0d10d35f6bbc190c42be24563140865de228c5
    MML Code Revision: 35aa5ce66ca59272c0d1e05c3d174cd4c0335b3c
    MHQ Code Revision: 76e9cea125956ab9a9d8af389ee60c2bb2eca81d
    
### Description
Students dropping out of military educations cannot use the re-enroll functionality built-into the system. Trying to do so shows the "Nothing more to learn" message, despite students in question not having gained any skills, and normally qualifying for re-enrollment. 

I have seen it happen reliably on prestigious military academy drop-outs, though local civilian educations appear unaffected at a glance. If I note any other occurances, will update. 

### Files
[mekhq.log](https://github.com/user-attachments/files/16503976/mekhq.log)

**Comment by IllianiCBT** [comment]
I think this is going to likely come down to faulty logic that checks whether the character has anything to learn. We check whether they have anything to learn skill-wise, but also if they have anything to learn Education Level-wise. I suspect that’s an OR check, rather than a AND check, which would produce this behavior.

**Comment by IllianiCBT** [comment]
I think I have a fix for this, but I really need a save to be able to properly test the issue.

**Comment by IllianiCBT** [comment]
If you can please test your issue with the fix added by https://github.com/MegaMek/mekhq/pull/4562 and lemme know if the issue has been resolved.

**Comment by Tzahr** [comment]
Can confirm it is now fixed.

**Comment by IllianiCBT** [comment]
Closing as resolved :)
