### ISSUE TITLE
RFE: ATB Garrison Contract Changes

### ISSUE THREAD

**Issue by SnyderPhilip** [MegaMek/mekhq#4565]
I would like the propose a change to the way ATB generates Garrison class contracts.  Every Contract on creation states a planet, ally rating, ally skill, enemy, enemy rating, enemy skill.  But logically, a Garrison class contract wouldn't know who is going to be attacking the planet that you would be garrisoning.  Plus, a garrison class contract should not be just a constant battleground, even when you defeat the first enemy, in a couple of months a new enemy shows up.

I propose that the Garrison class contracts (Garrison, Cadre, Security) drop all the enemy information, and for the first calendar month of the contract there is no enemy.  Then on the 1st of every month the game rolls 2d6.  On a 6-8 there is no enemy for the month. On a 5 or a 9 randomly check 1d6 enemy planets within 1 jump of the planet.  Add 1 for each modifier, enemy that owns planet is at war with planet owner. Industrial Output is B or better.  Agriculture Output is B or better.  On a 6+ that is the enemy that attacks, determine skill and rating normally.  On a 4 or 10, extend the radius to 2 jumps and check 2d6 enemy planets, add 1 to the 1d6 roll to any planets within 1 jump.  On a 3 or 11, extended the radius to 3 jumps, check 3d6 planets, add 1 to the 1d6 roll to any planets within 2 jumps, and another 1 to any planet within 1 jump (for a total of +2).  On a 2 or 12 extend the radius to 4 jumps, check 4d6 planets.  Add 1 to the 1d6 roll to any planets within 3 jumps, another 1 for planets within 2 jumps (+2 total), and another 1 for planets within 1 jump (for a total of +3).  Set the enemy morale to High.

Additionally, if possible, if the planet that is being garrisoned changes hands historically during the garrison contract, the month the planet is captured, change the enemy to the new owner, and set the enemy morale to invincible.

What that should do, is make it where the garrison contracts are more calm, as they should be in universe, but punctuated by brief but intense periods of combat.  And adding the last bit should make it where you wont remain on a planet that is overrun historically, unless you manage to defeat the enemy, and then I think you deserve to keep the planet under your control.

**Comment by IllianiCBT** [comment]
Closing as resolved
