### ISSUE TITLE
Unable to customize ASF in MekLab

### ISSUE THREAD

**Issue by Bonepart** [MegaMek/mekhq#457]
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1309416/mekhqlog.txt)

[The Dragon's Claw.zip](https://github.com/MegaMek/mekhq/files/1309418/The.Dragon.s.Claw.zip)

From HQ in hanger choose one of the ASF's and select customize in MekLab. Does nothing and MekLab shows a blank tab. Has error in log.

Using nightly build made on 9/15/17

**Comment by Bonepart** [comment]
Just tried with latest HQ build, 267. Same result, different error

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1309442/mekhqlog.txt)

**Comment by pheonixstorm** [comment]
I just tried with the last daily build and could not reproduce using the blake and wolf campaign

**Comment by pheonixstorm** [comment]
Tried with your campaign and was not able to reproduce

**Comment by Bonepart** [comment]
Seems I was just using a bad build.
