### ISSUE TITLE
RFE: Implement Planet Modifers to Repairs

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/mekhq#4575]
Campaign Ops has rules for planet types impacting repairs. Pg 193 

![image](https://github.com/user-attachments/assets/ece6c47c-1b4f-4ddc-b1c9-ce166232edb4)

With all the planets having details on this would be a fun option for hardcore players.

**Comment by IllianiCBT** [comment]
The first 6-7 should be relatively easy to implement. We'd just have to ensure that we're able to fetch that information from the planetary data without too much refactoring. Assuming we can, the biggest challenge would be ensuring that the modifiers are appropriately fed back to the player in _all_ the instances where they could appear.

I've grabbed this out the pile and will take a look tomorrow. If people thought Era Mods were rough, wait until they're trying to rebuild their broken ass 'Mechs in the middle of a frozen wasteland, with no atmosphere, and high Gs... in the 3rd Succession War. :D

**Comment by IllianiCBT** [comment]
Closing as resolved
