### ISSUE TITLE
(Nightly) Freeze when bulk-hiring at invalid skill level

### ISSUE THREAD

**Issue by SirChaos1** [MegaMek/mekhq#4579]
If you set Green level of a skill to rank 0 in the Skills tab, then bulk-hire personnel for a role using that skill while forcing Ultra-Green skill level, MHQ freezes. presumably because it cannot find a skill level below the rank set for Green.

I´m not even sure if this is a bug, as such, or more of a case of Error Code ID-10-T, but I figured I´d put it here anyway.

**Comment by IllianiCBT** [comment]
To be honest, the code I used to handle this is ugly as heck. I might just used this issue as an excuse to refactor it, closing this bug in the process.

**Comment by IllianiCBT** [comment]
Closing as resolved
