### ISSUE TITLE
Formatting issues with Fatigue.properties

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4585]
### Environment
Linux
Java 17
Master (latest PR https://github.com/MegaMek/mekhq/commit/a45a5251c44f7ab1cc47069bbc66e66f61ecd4c4)

### Description
See picture. I think the intention was for it to be _Person is no longer fatigued_ but its formatted as _is Person no longer fatigued_.

![Screenshot_20240808_130332](https://github.com/user-attachments/assets/2cd12a54-6882-4bc8-90ee-f2f4043710be)

**Comment by IllianiCBT** [comment]
Wups

**Comment by IllianiCBT** [comment]
Closing as 'resolved'
