### ISSUE TITLE
Battle Armor Education

### ISSUE THREAD

**Issue by SirChaos1** [MegaMek/mekhq#4606]
The battle armor related qualifications for both prestigious and local academies "unlock" in 3058, even though both IS Standard and Gray Death Standard suits become available in 3052.

I propose changing the start date for prestigious academies to the year their parent nation introduced their first BA design - 3050 for DC (Raiden Original) and FC (Sloth/Infiltrator), 3057 for FWL (Achileus/Longinus), 3062 for CC (Fa Shih), 3066 for MoC and TC (Trinity). The Dragoons´ academy should offer the classes from its inception. Local academies could start offering the classes in 3052 (the year the IS Standard and Gray Death Standard are introduced), and in-unit training could start then as well.

**Comment by Saklad5** [comment]
Keep in mind that industrial exoskeletons predate power armor and battle armor considerably. The skill field includes Piloting/Battlesuit, but (understandably) not Gunnery/Battlesuit.

I imagine early education programs drew extensively from technical schools to begin with.

**Comment by IllianiCBT** [comment]
This should be 3052 and was due to a flaw in how I fetched the 'standard' date for these units.

**Comment by HammerGS** [comment]
In a perfect world we'd align with this. 

<img width="768" alt="image" src="https://github.com/user-attachments/assets/04d3309e-ee28-43ec-82d8-af8ec94fcae7">

**Comment by Saklad5** [comment]
Yeah, just use that.

**Comment by IllianiCBT** [comment]
What's this column?

![image](https://github.com/user-attachments/assets/2af0964f-fcc6-4ae4-bc06-8ba234ae8cf5)

**Comment by Saklad5** [comment]
Common year.

**Comment by IllianiCBT** [comment]
Cool. We're going with 3052 as that's when the bulk of IS BA becomes available at Standard, at which point presumably publicly available education qualifications would be established. Though in-unit should be 3050.

**Comment by IllianiCBT** [comment]
Closing as resolved

**Comment by IllianiCBT** [comment]
Edit to last comment:

After discussion these are going to be the availability dates for BA-related qualifications:

Prestigious Academies from Major Factions: 3052
Other Academies: 3065 (to represent tech restrictions outside of non-major players)
Unit Education: 3050
