### ISSUE TITLE
RFE: Display Commanding Officer of Formation when Formation is selected for Formation Larger than Lance

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4607]
### Environment
Java 17
Linux
Master (latest PR https://github.com/MegaMek/mekhq/commit/a16a4fbdef2ed9c113f8eb1f3c8955af8a4bdb96)

### Description
Currently, when a Lance (or equivalent) is selected on the TOE, the commanding officer is displayed in the upper right. In this case, Major General Brita Mellem.
![Screenshot_20240811_101836](https://github.com/user-attachments/assets/915fcf45-6a0f-4b8c-ab75-e1408edd73d8)

However, when I travel up a level on the TOE, the Company commander is not shown. The Lance Commanders are show below, but not the Company Commander.
![Screenshot_20240811_101910](https://github.com/user-attachments/assets/e129bcdb-7bdf-4a78-a463-5df670468060)

When I travel up another level in the TOE, the Battalion Commander is not shown, _but_ the Company Commanders are shown below, with Major General Brita Mellem being accurately depicted as the Company Commander.
![Screenshot_20240811_101942](https://github.com/user-attachments/assets/aafd9a7d-90e1-4e99-9ab9-d0a6ea28dd27)

When I travel up another level in the TOE, the Regimental Commander is shown (because they use the commander flag), and the Battalion Commanders are shown below, with Major General Brita Mellem being accurately depicted as the Battalion Commander.
![Screenshot_20240811_102020](https://github.com/user-attachments/assets/7a379d14-6dd1-475e-8916-77fc3e60334e)

It would be nice if the formation commander would be displayed when the formation they are commanding was selected, instead of needing to travel up a level. In this case, when selecting the Company or Battalion, it would display Commander: Major General Brita Mellem, just like the Lance does. I believe this would also finish the already partially completed RFE #3873

### Files
[My HUGE Campaign31510104.cpnx.gz](https://github.com/user-attachments/files/16574017/My.HUGE.Campaign31510104.cpnx.gz)

**Comment by IllianiCBT** [comment]
Closing as resolved.
