### ISSUE TITLE
50.00 CamOps Rating Artifact - Generate Company - NPE - People generated, but no mechs.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#4612]
This one I think...  https://github.com/MegaMek/mekhq/actions/runs/10343673758

Title.  Load this save, Generate Company.  Save is from a previous version of 50.00, if it matters.

![image](https://github.com/user-attachments/assets/e8f9fc0c-a94f-4567-86c5-c2a026857e0b)

[Tsunami30700101.cpnx.gz](https://github.com/user-attachments/files/16577599/Tsunami30700101.cpnx.gz)
[mekhq.log](https://github.com/user-attachments/files/16577616/mekhq.log)

**Comment by Thom293** [comment]
Its repeatable.  Did it again. Got this force.  

With these people and no mechs and no one in my TOE I have a legendary reputation...

![image](https://github.com/user-attachments/assets/862469e5-6fa5-4670-8acf-b4abe9dc6b03)
![image](https://github.com/user-attachments/assets/cb11f12c-22d0-4a03-8692-7e3e3c67697b)

**Comment by IllianiCBT** [comment]
Known issue a fix is in the queue to be merged, just waiting on approval :)

**Comment by IllianiCBT** [comment]
Closing as resolved.

the work around is to turn off procreation until the fix gets merged :)
