### ISSUE TITLE
RFE: Effects of intelligence on XP cost

### ISSUE THREAD

**Issue by SirChaos1** [MegaMek/mekhq#4613]
Since a major component of intelligence is the ability to process new information, and thus to learn, a character´s intelligence level should affect the XP cost of new and improved skills as well as of SPA.

For example, a 5% modifier per intelligence level would vary costs between 40% and 160%.

(Note: this modifier and the general XP cost multiplier should probably be multiplicative - i.e. at 50% general cost, a Genius should pay 20% of base cost.)

**Comment by Saklad5** [comment]
This is not affected by INT in AToW rules. It is instead affected by a pair of traits, Fast Learner and Slow Learner.

MekHQ is already implementing a few traits as SPAs (like Natural Aptitude), though it would be best to separate them eventually.

**Comment by IllianiCBT** [comment]
Closing as resolved
