### ISSUE TITLE
[v0.50.0-SNAPSHOT] "Admin XP per _ week" campaign options resets to 1 on reload.

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4619]
### Environment
18:40:17,456 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:315) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-08-13T01:20:20.322515318
    Today: 2024-08-13
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MekHQ: 8 GB
    MM Code Revision: 8b0a9892f4419b03d76a29ecbfcf22233e2a8fd7
    MML Code Revision: fc321e451b068ba6292e43ecc1f6ce80345d79cb
    MHQ Code Revision: 156e2f11ee630330d7917873ee2ad73127985576

### Description
Under Campaign Options:
-> Experience. 
The entry: "XP awarded to each administrator every Monday for the work of the previous [number] weeks(s)".
The value entered as [number] here resets to 1 on reloading a campaign save. This can be replicated on a new campaign easy be changing the value to any number, saving the campaign, and reloading it. The value will be reset to 1. 

### Files
[mekhq.log](https://github.com/user-attachments/files/16602741/mekhq.log)

**Comment by IllianiCBT** [comment]
Closing as resolved
