### ISSUE TITLE
[v0.50.0-SNAPSHOT] Education - formatting error in tuition fee note in finances.

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4620]
### Environment
18:46:34,563 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:315) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-08-13T01:20:20.322515318
    Today: 2024-08-13
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MekHQ: 8 GB
    MM Code Revision: 8b0a9892f4419b03d76a29ecbfcf22233e2a8fd7
    MML Code Revision: fc321e451b068ba6292e43ecc1f6ce80345d79cb
    MHQ Code Revision: 156e2f11ee630330d7917873ee2ad73127985576

### Description
![image](https://github.com/user-attachments/assets/5a49dd8c-3685-4dd7-afd4-a54791b74f00)

Finances note r for tuition fees are not formatted correctly. 
Can be replicated easy by sending personnel on an education and referring to the finances ledger. 

### Files
[mekhq.log](https://github.com/user-attachments/files/16602814/mekhq.log)

**Comment by IllianiCBT** [comment]
Closing as resolved
