### ISSUE TITLE
[v0.50.0-SNAPSHOT] All Edge triggers toggle on whenever campaign is reloaded. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4621]
### Environment
19:00:19,305 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:315) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-08-13T01:20:20.322515318
    Today: 2024-08-13
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MekHQ: 8 GB
    MM Code Revision: 8b0a9892f4419b03d76a29ecbfcf22233e2a8fd7
    MML Code Revision: fc321e451b068ba6292e43ecc1f6ce80345d79cb
    MHQ Code Revision: 156e2f11ee630330d7917873ee2ad73127985576

### Description
All Edge triggers reset to ON whenever the campaign is reloaded, regardless of previous settings. 
Can be replicated by toggling off some triggers, saving and reloading, and observing triggers again; they will all be on. 

### Files
[mekhq.log](https://github.com/user-attachments/files/16602967/mekhq.log)

**Comment by IllianiCBT** [comment]
While technically Edge triggers are handled by mm, I'm going to leave this among mhq's reports as it's an issue that only affects mhq.

**Comment by IllianiCBT** [comment]
Closing as resolved
