### ISSUE TITLE
[0.50.0-SNAPSHOT] NPE when assigning a force to a Stratcon track

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/mekhq#4623]
### Environment
mekhq.MekHQ.initializeLogging(MekHQ.java:315) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-08-13T01:20:20.322515318
    Today: 2024-08-13
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.6
    Platform: Windows 10 10.0 (amd64)
    System Locale: en_US
    Total memory available to MekHQ: 8 GB
    MM Code Revision: 8b0a9892f4419b03d76a29ecbfcf22233e2a8fd7
    MML Code Revision: fc321e451b068ba6292e43ecc1f6ce80345d79cb
    MHQ Code Revision: 156e2f11ee630330d7917873ee2ad73127985576

### Description
I assigned my "Command" TO&E force to stratcon track 0 hex 0402 (badlands hex) and received an NPE. The lance is now showing on the stratcon track, but no mission was generated.

"java.lang.NullPointerException: Cannot read field "name" because "template" is null"

### Files
The folder structure of this zip file is aligned with the default MHQ folder structure, so that if it is unzipped on top of a clean install, all files will be placed in the appropriate folders.

[StratconTrackAssignment.zip](https://github.com/user-attachments/files/16604062/StratconTrackAssignment.zip)

**Comment by repligator** [comment]
> wait, I think this one is my fault and user error

> while making a backup of the scenario_manifest (by renaming it to _old) I apparently forgot to actually put the new one in, so my install is missing a scenario_manifest.xml file entirely

Closing as requested by submitter
