### ISSUE TITLE
[0.50.0-SNAPSHOT] Auto-Awards appears to be counting months instead of years for Longevity award

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/mekhq#4624]
### Environment
mekhq.MekHQ.initializeLogging(MekHQ.java:315) - Starting MekHQ v0.50.0-SNAPSHOT
Build Date: 2024-08-13T01:20:20.322515318
Today: 2024-08-13
Origin Project: MekHQ
Java Vendor: Eclipse Adoptium
Java Version: 17.0.6
Platform: Windows 10 10.0 (amd64)
System Locale: en_US
Total memory available to MekHQ: 8 GB
MM Code Revision: 8b0a9892f4419b03d76a29ecbfcf22233e2a8fd7
MML Code Revision: fc321e451b068ba6292e43ecc1f6ce80345d79cb
MHQ Code Revision: https://github.com/MegaMek/mekhq/commit/156e2f11ee630330d7917873ee2ad73127985576

### Description
Auto-Awards gave my people the 4-year Longevity award at 4 months instead of 4 years. Latest example is a Mechanic that was not part of my initial company generation (and therefore wouldn't have been part of the pre-game simulations) and was awarded Longevity when they hit their 4th month.

Mechanic name: Alpi Jalkanen
![image](https://github.com/user-attachments/assets/323dd4a2-f52d-438a-8d8c-3750f0a9a437)

### Files

[LongevityAward.zip](https://github.com/user-attachments/files/16604799/LongevityAward.zip)

**Comment by IllianiCBT** [comment]
Closing as resolved
