### ISSUE TITLE
[0.50.0-SNAPSHOT] Weekly Loyalty changes still occurring even with turnover module disabled

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/mekhq#4625]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
mekhq.MekHQ.initializeLogging(MekHQ.java:315) - Starting MekHQ v0.50.0-SNAPSHOT
Build Date: 2024-08-13T01:20:20.322515318
Today: 2024-08-13
Origin Project: MekHQ
Java Vendor: Eclipse Adoptium
Java Version: 17.0.6
Platform: Windows 10 10.0 (amd64)
System Locale: en_US
Total memory available to MekHQ: 8 GB
MM Code Revision: 8b0a9892f4419b03d76a29ecbfcf22233e2a8fd7
MML Code Revision: fc321e451b068ba6292e43ecc1f6ce80345d79cb
MHQ Code Revision: https://github.com/MegaMek/mekhq/commit/156e2f11ee630330d7917873ee2ad73127985576

### Description
As it says on the tin, I am still seeing Monday reports of my personnel changing loyalty even though I have the loyalty & turnover module disabled in my campaign options.

### Files
[LoyaltyChanges.zip](https://github.com/user-attachments/files/16604940/LoyaltyChanges.zip)

**Comment by IllianiCBT** [comment]
Closing as resolved
