### ISSUE TITLE
MekHQ only remembers MGs set to rapid fire for up to two MGs

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#463]
I have noticed that after setting MGs to rapid fire in the lobby, MekHQ will remember it for the same unit in future scenarios, but only for up to two MGs.

E.G. Fenrir assault BA has three MGs, if you set all MGs to rapid fire, play a scenario, and use the same BA in future scenarios, only the first two MGs will be set to rapid fire and you have to manually set the third MG to rapid fire.

![mekhq](https://user-images.githubusercontent.com/1191378/30661564-c4dd64e4-9e87-11e7-8581-e1ad075021a9.jpg)

[#battletech.zip](https://github.com/MegaMek/mekhq/files/1318859/battletech.zip)

First campaign file is before setting all MGs to rapid fire for the Fenrir BA, second is after finishing one scenario, if you go into the lobby for the next scenario, only the first two MGs are set to rapid fire.

**Comment by neoancient** [comment]
Megamek was not reserving enough space for the critical slots. Though the equipment was loaded, the third MG went beyond the limit of the slots. The unit status written by the campaign file goes by slots, and since the third MG was never assigned a slot on loading the status was not preserved.
