### ISSUE TITLE
[0.50.0-SNAPSHOT] Plugin example code no longer works. 

### ISSUE THREAD

**Issue by cam-smith** [MegaMek/mekhq#4642]
### Environment
MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-08-15T20:55:51.855085900
    Today: 2024-08-15
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.11
    Platform: Windows 11 10.0 (amd64)

### Description
Plugin example code no longer works, as detailed in [/docs/plugins.txt](https://github.com/MegaMek/mekhq/blob/master/MekHQ/docs/plugins.txt)
Apparently the JS and other language support used by the plugin framework has been depreciated in Java  11 and removed in Java 15.  [https://stackoverflow.com/a/71481633](https://stackoverflow.com/a/71481633)
Seems like we would need to investigate GraalVM to get the multi language parsing to work again.

**Comment by IllianiCBT** [comment]
To my knowledge we no longer support plugins. The only system that _did_ support plugins was refactored in 50.01 to no longer use them.

Closing as no longer an issue, however let us know if you think this is mistaken and we can reopen.
