### ISSUE TITLE
Prisoner Ransom/Defection Nag clarification

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4643]
### Environment
Linux
Java 17
Master (latest PR https://github.com/MegaMek/mekhq/commit/fbb0a02e62541aa66b146055a847e38bad50f86e)

### Description
Let us assume that I have 10 prisoners, 5 of whom are willing to defect.

`ransomDefectorsQ.format=You have %d prisoners willing to defect, ransom them for %s?`
`%d` uses the value for total number of prisoners. The nag currently reads "You have 10 prisoners willing to defect...", which isn't true.

Either the text should be changed to "You have 10 prisoners, some of whom are willing to defect,..." or `%d` should be changed to reflect the number of defectors "You have 5 prisoners willing to defect...".

**Comment by IllianiCBT** [comment]
Closing as resolved
