### ISSUE TITLE
v0.50.0 aerospace pilots in conventional aircraft

### ISSUE THREAD

**Issue by DynamicWorlds** [MegaMek/mekhq#4649]
### Environment
v0.50.0-SNAPSHOT (2024-08-12 evening's nightly) 
Win 10
Java Vendor: Eclipse Adoptium
Java Version: 17.0.11

### Description
The game allows assigning aerospace pilots to conventional aircraft, but seems to show the wrong skills when deployed to the briefing room.  I currently have a 4/5 aerospace pilot who is registering as a 7/8 pilot in a conventional aircraft.
I'm not sure if that should be 4/5 or 8/8 or if he should not be able to be assigned as the pilot at all, but it seems that something is off.
![Temp](https://github.com/user-attachments/assets/a56b0627-96d0-43bf-bd89-5ee4ec8318d5)
![Temp2](https://github.com/user-attachments/assets/4cbaa25e-fd8c-4329-8308-b979d607445f)

### Files
[Trond's Dragoons30250224A2.cpnx.gz](https://github.com/user-attachments/files/16631479/Trond.s.Dragoons30250224A2.cpnx.gz)
[customs.zip](https://github.com/user-attachments/files/16631483/customs.zip)
[megamek.log](https://github.com/user-attachments/files/16631488/megamek.log)
[mekhq.log](https://github.com/user-attachments/files/16631489/mekhq.log)

**Comment by IllianiCBT** [comment]
From discussion on Discord we've concluded the ability for Aero pilots to fly conventional was likely a legacy decision with no basis on current rules. So we're going to take a look at bringing it in line with RAW though that won't be in 50.0 due to the likelihood any fix will have unforeseen knock-on effects.

**Comment by IllianiCBT** [comment]
Closing as resolved
