### ISSUE TITLE
[v0.50.0-SNAPSHOT] Intelligence XP Modifiers prevent levelling or cause decimated skill costs. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4653]
### Environment
03:39:33,323 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:315) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-08-16T01:18:37.610518301
    Today: 2024-08-16
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MekHQ: 8 GB
    MM Code Revision: f33d7a95b57ec014dd816d02534eb018aca13256
    MML Code Revision: fc321e451b068ba6292e43ecc1f6ce80345d79cb
    MHQ Code Revision: de5b32500bbe5a7b5b179a9e9ce75a224d2f00a0

### Description
Turning on the Intelligence XP Modifier option under Life Paths in the Campaign Options appears to decimate XP costs, often rounded down to 0 XP, or to an anomalous value that prevents the skill from being levelled at all. Likely a calcuation error, or an incompatbility with the XP curve I employ. 
Turning off the option appears to restore XP costs to normal. 

@IllianiCBT - tagged on request. 

### Files
Log, savegame, and custom units provided:
[mekhq.log](https://github.com/user-attachments/files/16632860/mekhq.log)
[1st Rimward Hussars.zip](https://github.com/user-attachments/files/16632501/1st.Rimward.Hussars.zip)
[customs.zip](https://github.com/user-attachments/files/16632507/customs.zip)

**Comment by IllianiCBT** [comment]
Closing as resolved
