### ISSUE TITLE
Contract hover over text issue

### ISSUE THREAD

**Issue by molemanBT** [MegaMek/mekhq#4660]
the hover over for the different types of contract, one of them the text doesn't wrap and is full of % characters, I don't know if it's been fixed or noticed. I think it's the contract market, don't know if it's independent, liaison etc but it was one of them

**Comment by molemanBT** [comment]
@IllianiCBT

**Comment by IllianiCBT** [comment]
I'm away for the weekend, but will get this checked out once I return.

**Comment by IllianiCBT** [comment]
Closing as resolved
