### ISSUE TITLE
Documentation: Logistics and Parts Procurement: A ComStar Field Manual for Mercenary Commanders

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4661]
### Description
I realize things are still in a state of flux leading up to the big five oh release, apologies if I'm just noting things that are deliberately being held off until the last minute. There is also the question of which preset(s) the documentation should reflect, since some of them use different values.

**Your Unit's Reputation (between contracts)**
Alphabet ratings from FM:M, should probably be changed to CamOps since it's the default.

**Wheeling and Dealing: Acquisition Protocols**
Default acquisition skill is either Tech or Negotiation, not Administration.
The formula for delivery time and the penalty for clan tech are not accurate to any of the presets.

### Files
[Logistics and Parts Procurement.pdf](https://github.com/user-attachments/files/16642356/Logistics.and.Parts.Procurement.pdf)

**Comment by IllianiCBT** [comment]
@HammerGS I’ll send you edit permissions so you can make edits directly to the pdf on Google docs

**Comment by HammerGS** [comment]
I wonder if you can generate FDF files for these.

**Comment by IllianiCBT** [comment]
I can take a look into it when I'm back Sunday PM

**Comment by HammerGS** [comment]
Can someone give me specific corrections or wordings. I can then fluff that up.

**Comment by IllianiCBT** [comment]
Closing as resolved (not sure if the fixed documentation was included in 50.0, but if it wasn't it will be in 50.01)
