### ISSUE TITLE
RFE: Include era-bookmarks with the calendar when starting a new campaign. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4662]
When starting a new campaign, there is a step when the user specifies the campaign starting date.

This can be enhanced by providing era-specific bookmarks that will automatically set the date to the specific era, which will allow new and returning users to quickly play in the period of their choosing. These eras are already tracked by date in MekHQ, usually displayed at the top of the window along with the date. 

These bookmarks should only set the date, not automatically confirm it (to allow users to browse). Optionally, a textsnippet can provide a contextual overview of the era selected. 

@IllianiCBT - Tagged on request.

**Comment by IllianiCBT** [comment]
Closing as resolved
