### ISSUE TITLE
[v0.50.0-SNAPSHOT] Unable to sell most parts through the Parts In Use Report.

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4663]
### Environment
04:50:26,741 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:315) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-08-17T01:16:16.522116870
    Today: 2024-08-17
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MekHQ: 8 GB
    MM Code Revision: 5d74b455d1bfe3c55797e4e3daac3bd0168ca828
    MML Code Revision: fc321e451b068ba6292e43ecc1f6ce80345d79cb
    MHQ Code Revision: b3e0e4457a766489e5545398116ef0d341862003

### Description
The Parts in Use Report (found in the Command Center tab) now has buttons that are meant to allow selling parts directly from this report. This only seems to function sporadically, and will often fail to sell any parts. 

### Files
[customs.zip](https://github.com/user-attachments/files/16643208/customs.zip)
[1st Rimward Hussars.zip](https://github.com/user-attachments/files/16643209/1st.Rimward.Hussars.zip)
[mekhq.log](https://github.com/user-attachments/files/16643210/mekhq.log)

**Comment by Algebro7** [comment]
This one's mine, will look into it shortly. Thanks for the report.
