### ISSUE TITLE
NPE - Contracts only generate with Independent OpFor

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4664]
### Environment
Java 17
Linux
Master (latest PR https://github.com/MegaMek/mekhq/commit/b3e0e4457a766489e5545398116ef0d341862003)

### Description
I accepted a generated contract from the contract window, with an OpFor of Independent on the planet of Cartago. I then traveled from Galdeon to Cartago. Upon arrival on Cartago, the first day of the contract occurred, and an NPE was thrown. An NPE was also thrown on the second and third day. 
If I go to Edit Mission FedCom is shown as the OpFor. If I hit cancel, an NPE is thrown. If I hit okay, an NPE is thrown. If I change the OpFor to independent, an NPE is thrown.

### Files
[mekhq.log](https://github.com/user-attachments/files/16645038/mekhq.log)
[fedcomNPEYakuza3830400808.cpnx.gz](https://github.com/user-attachments/files/16645040/fedcomNPEYakuza3830400808.cpnx.gz)

**Comment by repligator** [comment]
Having continued the save (GM generated a ton of contracts) it seems that contracts are erroneously generating exclusively with an Independent OpFor. Even Pirate Hunting is generating with an Indenpendent OpFor.

**Comment by repligator** [comment]
Example from a different campaign. This one did manage to generate a scenario somehow.

[Angry Monkey30000512.cpnx.gz](https://github.com/user-attachments/files/16646488/Angry.Monkey30000512.cpnx.gz)
[mekhq.log](https://github.com/user-attachments/files/16646489/mekhq.log)

**Comment by Tzahr** [comment]
Can confirm this happened independently on my end also.

**Comment by IllianiCBT** [comment]
Confirming Nick's PR appears to have resolved this issue. Closing as resolved.
