### ISSUE TITLE
[0.50.0-SNAPSHOT] Education - academy names in failed entry exams are "null" in personal log entries. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4675]
### Environment
10:37:20,476 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:315) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-08-19T01:20:04.014314212
    Today: 2024-08-19
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MekHQ: 8 GB
    MM Code Revision: 4c3690d64ffd1b6c730dc4be6ccdd0487095b4c7
    MML Code Revision: fc321e451b068ba6292e43ecc1f6ce80345d79cb
    MHQ Code Revision: f5277de44aead75414629af998e9e205fd69254a

### Description
When a student fails an entry exam, a notation of this is made in the personal log. This entry currently mislabels the academy name as 'null'. 

![image](https://github.com/user-attachments/assets/0c0a807c-7216-401d-bf44-7664acafb5e8)

@IllianiCBT - Tagging since this is going to be your code.

**Comment by IllianiCBT** [comment]
Closing as resolved
