### ISSUE TITLE
RFE: Wolf Empire/Republic of Sphere Faction colors hard to differentiate

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4676]
### Description
RotS
`<colorRGB>207,119,57</colorRGB>`
Wolf Empire
`<colorRGB>207,114,58</colorRGB>`
![Screenshot_20240819_091324](https://github.com/user-attachments/assets/de6a892d-7a21-417c-81ce-f6d4c3dfbf9c)
The Wolf Empire and Republic of Sphere Faction colors hard to differentiate between, especially on a black background. The Wolf Empire color does seem to be 'canon' as it's used in the maps from several of the rulebooks for Clan Wolf and/or CWiE. Is there an alternative color that could be used for the RotS?

**Comment by IllianiCBT** [comment]
@HammerGS do you have a color preference here, or do I have carte blanche?

**Comment by HammerGS** [comment]
Let me see if I can find canon codes.

**Comment by IllianiCBT** [comment]
Closing as resolved
