### ISSUE TITLE
Generating personalities on older saves gives incorrect names

### ISSUE THREAD

**Issue by Stm316** [MegaMek/mekhq#4681]
### Environment
16:53:20,669 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:315) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-08-17T01:16:16.522116870
    Today: 2024-08-20
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.11
    Platform: Windows 10 10.0 (amd64)
    System Locale: en_AU
    Total memory available to MekHQ: 4 GB
    MM Code Revision: 5d74b455d1bfe3c55797e4e3daac3bd0168ca828
    MML Code Revision: fc321e451b068ba6292e43ecc1f6ce80345d79cb
    MHQ Code Revision: b3e0e4457a766489e5545398116ef0d341862003
Nightly 1586

### Description
I have been continuing campaigns from older saves (some older than .49.2), wondering what will break the save.  Enabling the new personality mod saw older characters all with "none" attributes, that also had "average" IQ.  I selected them, and regenerated personalities. Scrolling through, I found a mismatch in some characters names, and what was displayed in their "about".
![nope](https://github.com/user-attachments/assets/e8a3fd0e-5cc0-472e-a60a-68b67f9d3040)

This issue did not appear in a new game.
As a funny side note, I've got a mech pilot callsign "Squid" whose profile says "hugs others". That works.

### Files
Save file:
[The Red Dragons30360723.cpnx.gz](https://github.com/user-attachments/files/16685536/The.Red.Dragons30360723.cpnx.gz)
Custom files:
[The Red Dragons.zip](https://github.com/user-attachments/files/16685542/The.Red.Dragons.zip)
[ranks.zip](https://github.com/user-attachments/files/16685551/ranks.zip)

**Comment by IllianiCBT** [comment]
Closing as resolved

**Comment by IllianiCBT** [comment]
To resolve the issue in your save, right click on any affected personnel (while in GM mode) and select edit. You can close the edit dialog without making changes which will cause the description to regenerate.
