### ISSUE TITLE
Auto Awards not issuing, throws exception on run

### ISSUE THREAD

**Issue by Stm316** [MegaMek/mekhq#4683]
### Environment
14:40:15,385 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:315) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-08-20T01:18:23.558375041
    Today: 2024-08-21
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.11
    Platform: Windows 10 10.0 (amd64)
    System Locale: en_AU
    Total memory available to MekHQ: 4 GB
    MM Code Revision: 7682f165c2d7664f113e743b5da452811d433f5c
    MML Code Revision: fc321e451b068ba6292e43ecc1f6ce80345d79cb
    MHQ Code Revision: f5277de44aead75414629af998e9e205fd69254a
Nightly 1589

### Description
When I try to run auto awards, I get an exception. Faction specific custom award set and ranks in use. I'm trying to tune my award sets to run, but can't get the promotion function to trigger.

### Files
Save:
[153rd Striker Cluster30310717.cpnx.gz](https://github.com/user-attachments/files/16686259/153rd.Striker.Cluster30310717.cpnx.gz)
Ranks:
[ranks.zip](https://github.com/user-attachments/files/16686260/ranks.zip)
Logs:
[mekhq.log](https://github.com/user-attachments/files/16686265/mekhq.log)
Awards:
[Awards.zip](https://github.com/user-attachments/files/16686274/Awards.zip)
Award images:
[Clan_JF.zip](https://github.com/user-attachments/files/16686279/Clan_JF.zip)

**Comment by IllianiCBT** [comment]
When are you trying to run autoAwards? At the end of the month, manually, after a scenario?

**Comment by Stm316** [comment]
Manually, attempting to give rank insignia, so far I've only been able to do it manually.

**Comment by IllianiCBT** [comment]
Closing as resolved
