### ISSUE TITLE
[rfe] Add current edge total to the tech selection screen in the repair bay/warehouse

### ISSUE THREAD

**Issue by azhais** [MegaMek/mekhq#4695]
While doing a high cost repair task, I wanted to use a tech with edge to add some cover for a "destroyed part" failure. It would be helpful if you could see how much edge a tech has from the repair bay rather than having to scroll over the in the personnel tab, find someone with edge, then go back to the bay and find the tech by name.

(I will be implementing this myself, I just don't have permissions to set the assignee)

**Comment by IllianiCBT** [comment]
Closing as resolved
