### ISSUE TITLE
NPE when adjusting Salary

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4697]
### Environment
Linux
Java 17
MHQ Code Revision: ab52c2e15ffce1aecdf583da820223f7d7c1ca4a

### Description
Right clicked on a person, selected 'Set Salary'. Received NPE.

```
21:33:23,210 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$1(MekHQ.java:294) - Uncaught Exception Detected
java.lang.IllegalArgumentException: (minimum <= value <= maximum) is false
```

### Files
[mekhq.log](https://github.com/user-attachments/files/16734808/mekhq.log)
[Salary-NPE-Comstar27880101.cpnx.gz](https://github.com/user-attachments/files/16734813/Salary-NPE-Comstar27880101.cpnx.gz)

**Comment by IllianiCBT** [comment]
I’ll try and take a look at this whenever I get a few minutes

**Comment by IllianiCBT** [comment]
Closing as resolved
