### ISSUE TITLE
Experience for XP for each 2 rolled on an unsuccessful task can not be negative

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#47]
I don't know exactly when it happened but it used to be a value that could be negative. Now it can not be negative.

**Comment by Dylan-M** [comment]
I'm not even sure why you'd want it to be negative. Even in real life you learn more from failure than you do from success.

**Comment by scJazz2** [comment]
I don't know either since I set that value to ZERO 2 years ago. However, it used to be able to be a signed integer.

**Comment by Akjosch** [comment]
Well, the "easy" fix breaks a few things (a few places in code expect the total XP to never go below 0). Though that particular bug seems to have been in there forever, it's just that nobody realised it's there ...

**Comment by Dylan-M** [comment]
I'm going to close this as invalid, as people shouldn't lose experience just for failing at a task.

**Comment by scJazz2** [comment]
I agree... it was a bad suggestion.
