### ISSUE TITLE
RFE:  Include current rank as a filter in Mass Training 

### ISSUE THREAD

**Issue by Kendricke** [MegaMek/mekhq#470]
Within Mass Training, I can filter by role or experience level.  For skills such as Strategy which only apply benefits to my officers in an ATB campaign, I would prefer to filter only by rank.

**Comment by Kendricke** [comment]
Noting that this was originally added to the 0.45 milestone, but never implemented. Any way to reintroduce this to a future release backlog?

**Comment by Windchild292** [comment]
@Kendricke 
It is still in the backlog, just nobody has gotten to it.

**Comment by Kendricke** [comment]
Ran into this issue again and went to add the RFE, before realizing I had requested this a couple years ago already.  Hoping to get this eventually pulled in to a new release.
