### ISSUE TITLE
RFE:  Portrait system should avoid using duplicate portraits if possible

### ISSUE THREAD

**Issue by Kendricke** [MegaMek/mekhq#471]
As a gamemaster/player, I would like the portrait system to automatically check to see if a given portrait file is already in use within a unit before assigning that same portrait again.  

Example:  Portrait file mw762.jpg is in use by Mechwarrior Joe Smith within the unit Mercs Inc.  A new mechwarrior recruit is hired and MekHQ will assign a new portrait to the new recruit.  The system should recognize that mw762.jpg is already in use (even if Joe Smith is now MIA or KIA) and will skip that possibility when assigning a new portrait file.

**Comment by Kendricke** [comment]
Ok, thanks for clarification.  I guess it's because I keep assigning my portraits by role that I find myself frequently having to double check which images are in place already.  Having discrete portrait folders would then alleviate this problem outright, I'd reckon.

**Comment by Dylan-M** [comment]
Well, it should only do it for auto-assigned portraits. And this would be by design. I'll leave this open until someone can validate that my memory is correct since I'm currently at work.

**Comment by Bonepart** [comment]
On the plus side you opening this brought the open RFE to my attention and I think it's a neat idea, so I implemented it.
https://github.com/MegaMek/mekhq/pull/481
