### ISSUE TITLE
MekHQ-0.50.0-SNAPSHOT: CamOps Transport Calculation Does Not Properly Factor in Transport Bays

### ISSUE THREAD

**Issue by UlyssesSockdrawer** [MegaMek/mekhq#4711]
### Environment
Version: MekHQ-0.50.0-SNAPSHOT
OS: Win11
Java: 17

### Description
To test the new CamOps unit rating approach, I added an Overlord dropship to my force.

The Transport Capacity report shows that 36 bays are available, and 9 occupied. The unit reputation report shows a penalty for lack of transported meks.

![image](https://github.com/user-attachments/assets/dae9d20d-b90e-4861-955f-a2b340e050d3)

![image](https://github.com/user-attachments/assets/c4a984e0-cdce-4035-9383-661beede48ec)

### Files
[The Ramshackle Renegades30620207.cpnx.gz](https://github.com/user-attachments/files/16741975/The.Ramshackle.Renegades30620207.cpnx.gz)

@IllianiCBT

**Comment by IllianiCBT** [comment]
So there haven't been any changes made to the transport report, so I can't comment to that, however my immediate question is whether your Union is fully crewed, as if not you won't get the benefits of its bays.

**Comment by IllianiCBT** [comment]
It's also worth noting that Reputation only updates on Mondays, so any changes made won't be reflected until the following Monday.

**Comment by UlyssesSockdrawer** [comment]
![image](https://github.com/user-attachments/assets/7e5c06d6-d05d-43d5-bc0e-20f986f02a47) - fully crewed, used the Hire Minimum Complement action when I added it to the campaign.

I didn't know about the Monday thing - let me try flipping forwards a week quickly.

**Comment by UlyssesSockdrawer** [comment]
![image](https://github.com/user-attachments/assets/6285a0df-d67f-4323-91d3-de1e061625ec)

@IllianiCBT - yep, flipping forward to the next Monday updated the report.

Maybe some text in the report at the top to say it updates Mondays might help to avoid any future issue reports? I assumed it was dynamic like the Transport Capacity one.

**Comment by IllianiCBT** [comment]
It used to by dynamic, but that wasn't RAW and it wasn't remotely efficient in terms of processing.

Closing as not an issue
