### ISSUE TITLE
MekHQ-0.50.0-SNAPSHOT: Formation Type not Auto Set for Lance Level Formations

### ISSUE THREAD

**Issue by UlyssesSockdrawer** [MegaMek/mekhq#4713]
### Environment
Version: MekHQ-0.50.0-SNAPSHOT
OS: Win11
Java: 17

### Description
When creating a detailed TO&E for a campaign, formation levels auto-assign at Regiment, Battalion, and Company level.

However, lance level formations do not auto-assign.

This may want to be a separate RFE, but the default top-level has an override, whilst lower levels don't. Personally I'd find it super useful to be able to override the formation level for any TO&E force.

![image](https://github.com/user-attachments/assets/bb97499d-115d-4a01-9607-32db75388164)
![image](https://github.com/user-attachments/assets/df488b67-d21c-4c11-b064-f31e743d6da6) - I'd like this feature for all forces. Let me know if it needs a separate RFE.
![image](https://github.com/user-attachments/assets/69b04234-1d17-4931-80df-4cf73baad660)
![image](https://github.com/user-attachments/assets/1807a3b4-363d-44cd-8342-62debdd27504)
![image](https://github.com/user-attachments/assets/eb05aa67-245e-45f8-be9d-b410b64137ae)

### Files
[The Ramshackle Renegades30620207.cpnx.gz](https://github.com/user-attachments/files/16742008/The.Ramshackle.Renegades30620207.cpnx.gz)

@IllianiCBT

**Comment by IllianiCBT** [comment]
Closing as resolved

**Comment by UlyssesSockdrawer** [comment]
Let me know when this is in the nightly @IllianiCBT  and I'll re-test

**Comment by IllianiCBT** [comment]
Oh and can you open your RFE regarding the ability to override all toe layers. I have no interest in implementing that, but someone else might pick it up in future.

Why I chose not to implement it:
First and foremost it's very difficult to communicate to users which force has been overridden, furthermore a mid-TOE override only works if the TOE is static, if users are frequently changing their TOE the need to constantly remove the override for random forces will get annoying very quickly. Especially if there is no easy way to see whether a force has been overridden.

The next is a code complexity issue. Right now the code for this system is relatively simple. If we introduce mid-TOE overrides that will very quickly stop being the case.
