### ISSUE TITLE
Units continue to show damaged status despite being restored/fully repaired

### ISSUE THREAD

**Issue by Flibjib** [MegaMek/mekhq#472]
<img width="1369" alt="screen shot 2017-09-27 at 5 31 18 pm" src="https://user-images.githubusercontent.com/32344358/30938907-b973cc0c-a3a9-11e7-8396-e721c09794de.png">

This happens across any units and I can't seem to resolve it or work out the logic, looks like a bug to me

**Comment by HammerGS** [comment]
We would need a campaign file, and all customs to look into this.

**Comment by Flibjib** [comment]
[Minnesota Tribe28260118.cpnx.zip](https://github.com/MegaMek/mekhq/files/1341014/Minnesota.Tribe28260118.cpnx.zip)

**Comment by Flibjib** [comment]
I have no custom units added to my campaign

**Comment by pheonixstorm** [comment]
Injured Pilots, unfinished repairs...
