### ISSUE TITLE
RFE Player Reinforcement easy stopgap improvement

### ISSUE THREAD

**Issue by DynamicWorlds** [MegaMek/mekhq#4721]
When deploying reinforcements, have the system only able to draw from Support Points and not automatically convert a Victory Point to a Support Point when SP is 0.  This would enable some degree of manual control over deploying via reinforcement rolls by leaving it up to the player to choose to manually convert VP to SP to make them available for reinforcements and allow reinforcements while still keeping VP above 0 as is specified by some missions.

It would also be easy to code and require minimal, if any, UI changes, making it a minimalist way of taking a full step toward full manual control of reinforcements

**Comment by Thom293** [comment]
I may not be understanding this - but I think what you are suggesting is already possible.   Go to the map tab and top right there should be a "Manage VP/SP" button.  Should have this and other option there.

**Comment by DynamicWorlds** [comment]
> I may not be understanding this - but I think what you are suggesting is already possible. Go to the map tab and top right there should be a "Manage VP/SP" button. Should have this and other option there.

what I'm suggesting is that when you reinforce, if you have no SP it does a reinforcement roll rather than automatically using a VP instead of the usual SP

**Comment by Thom293** [comment]
ohh.  it automatically eats a VP if you have no SP?  

Yeah.  Then this is a good idea.

**Comment by IllianiCBT** [comment]
Closing as resolved
