### ISSUE TITLE
[0.50.0-SNAPSHOT] Selling items from Parts In Use Menu with "Name (Tonnage)" name format causes wrong items to sell

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4723]
### Environment
00:49:38,142 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:315) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-08-25T01:25:18.350793281
    Today: 2024-08-26
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MekHQ: 8 GB
    MM Code Revision: 38c5c63334f27ef2c0e2cf39b9b634883a948f14
    MML Code Revision: b1b0bee27fee84bfe1af4375aba9a5423258cea7
    MHQ Code Revision: d9a07a3c8f79c902c2c188a1590b53ee786de3bd

### Description
Trying to sell an item that has Name (tonnage) format from the Parts In Use Menu results in a different, similar item being sold instead. This follows specific behaviour outlined below:

Example: selling 20t foot actuators will sell a 65t foot actuator instead. It will continue selling all 65t foot actuators, before moving on to a different weight of foot actuator again, selling all of these, etc.  In some instances, the item fails to sell at all. 

This behaviour appears reliably with items that follow this naming convention, e.g.: actuators, limb parts, Mech sensors, Jump Jets, and so on.

The sell function also does not distinguish between: 
LB 10-X AC
or
LB 10-X AC (Omni Pod)
In this example, trying to sell the former will result in it selling parts of the latter.

**Comment by Algebro7** [comment]
Just a note for everyone else--this functionality was removed for the 0.50 release due to this bug but I'm working on a better fix for it in the next dev cycle.
