### ISSUE TITLE
[0.50.0-SNAPSHOT] Stratcon - Unable to deploy multiple lances to attack facility discovered by scouting an adjacent hex

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/mekhq#4726]
### Environment
mekhq.MekHQ.initializeLogging(MekHQ.java:315) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-08-27T01:20:39.316782284
    Today: 2024-08-27
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.6
    Platform: Windows 10 10.0 (amd64)
    System Locale: en_US
    Total memory available to MekHQ: 8 GB
    MM Code Revision: 1aaf2125d43a24d3eaf6c276af06757b16dc2acf
    MML Code Revision: b1b0bee27fee84bfe1af4375aba9a5423258cea7
    MHQ Code Revision: 10c3f1e358f14b5cb04865826be84669c9e4bf66

### Description
The facility on hex 0405 was discovered by a scouting lance deployed to an adjacent hex. Since the facility was discovered but not created as a mission in the briefing tab, I am unable to deploy multiple lances to attack it unlike with scenarios generated by scouting adjacent hexes.

Ctrl-clicking multiple lances just moves the selection and does not select multiple forces.

Stratcon seems to treat it as a deployment to a non-scenario hex until the base attack scenario is actually generated.

End result is that I have to either move all forces into a single lance in TOE when deploying, or deploy the second lance as reinforcements and manually set the units to arrive on turn 0 with the main force, and GM-refund the SP used for the deployment of reinforcements.

In the attached save, I am attempting to deploy Blizzard and Tracked - I to attack this artillery base.

### Files

[StratconMultipleLances.zip](https://github.com/user-attachments/files/16765813/StratconMultipleLances.zip)

**Comment by IllianiCBT** [comment]
This looks like it's working normally in 50.02. Closing as resolved
