### ISSUE TITLE
MekHQ-0.50.0-SNAPSHOT-CI1597: Name mismatch when generating prisoner backgrounds

### ISSUE THREAD

**Issue by UlyssesSockdrawer** [MegaMek/mekhq#4736]
### Environment
Version: MekHQ-0.50.0-SNAPSHOT-CI1597
OS: Win11
Java: 17

### Description
![image](https://github.com/user-attachments/assets/d8403863-d10f-4795-897e-e03a63ac5d80)

When taking prisoners in a scenario, their backgrounds auto-generate, but the names mismatch.

@IllianiCBT suggested the following: "From what I can gather, prisoners get their names regenerated at some point, so what you see in their description is their original name. But I’ll be damned if I can find where it’s happening."

### Files
Pre-battle save: 
[The Nova Dragoons30000630.cpnx.gz](https://github.com/user-attachments/files/16786836/The.Nova.Dragoons30000630.cpnx.gz)

Post-battle save:
[The Nova Dragoons30000630-BackgroundNameMismatch.cpnx.gz](https://github.com/user-attachments/files/16786837/The.Nova.Dragoons30000630-BackgroundNameMismatch.cpnx.gz)

@IllianiCBT

**Comment by IllianiCBT** [comment]
I’ll take another look at this when I get a chance. My current theory is that prisoner names get changed at some point, leading to this behavior.

the problem can be resolved by entering the character’s edit person view (while in GM mode) and immediately leaving. This will cause the description to regenerate.

**Comment by IllianiCBT** [comment]
Closing as resolved
