### ISSUE TITLE
MekHQ-0.50.0-SNAPSHOT: Commander loading failure with existing save - error message mentions academies

### ISSUE THREAD

**Issue by UlyssesSockdrawer** [MegaMek/mekhq#4738]
### Environment
Version: MekHQ-0.50.0-SNAPSHOT - CI1597 Nightly - Megamek launched via MekHQ
OS: Win11
Java: 17

### Description
![image](https://github.com/user-attachments/assets/1f9c1ed1-673c-4456-91db-6d1a7f83e52c)

When loading a save created on the 0.50.0 CI-1597 nightly, the above error message appears. This is a blocker and prevents MHQ from loading the save at all.

Some possible conditions?:

- A unit commander flag has been set
- All meks are loaded onto dropships in the TO&E

Split from: https://github.com/MegaMek/mekhq/issues/4728

### Files
[The Nova Dragoons30000826.cpnx.gz](https://github.com/user-attachments/files/16787898/The.Nova.Dragoons30000826.cpnx.gz)

**Comment by IllianiCBT** [comment]
Closing as resolved
