### ISSUE TITLE
[0.50.0 Nightly CI #1598] Rapid unplanned disassembly of entire force when loading save files created in #1598

### ISSUE THREAD

**Issue by LadyAdia** [MegaMek/mekhq#4742]
### Environment
What version of MekHQ does your issue apply to? 0.50.0 Nightly CI 1598
What operating system are you using?  MacOS 14.6.1
What java version are you using?  17.0.2

### Description
Issue: When loading save files created in the current nightly build, nearly all units in the force are disassembled.
First three screenshots shows the status of things when loading a save created in Nightly CI 1596.

<img width="1440" alt="Command Center Before" src="https://github.com/user-attachments/assets/5a3c352b-d18d-4f16-b5cc-c70607a3fc5a">

<img width="1440" alt="Hangar Before" src="https://github.com/user-attachments/assets/68143938-d8a1-47c3-8159-df115a7fd138">

<img width="1440" alt="Warehouse Before" src="https://github.com/user-attachments/assets/22c3bd74-9d79-4902-99ac-dd97ef14efa4">

Upon loading and taking these screenshots, I immediately saved the game and reloaded from the new save. The following shows the result

<img width="1440" alt="Command Center After" src="https://github.com/user-attachments/assets/7c32987b-c9a4-4edd-8064-ea319bfd40d2">

<img width="1440" alt="Hangar After" src="https://github.com/user-attachments/assets/3011f269-4f34-4b7a-b1a5-3060405094af">

<img width="1440" alt="Warehouse After" src="https://github.com/user-attachments/assets/283bfa90-c658-4d8d-b689-821ee7b28e06">

The .zip file attached below contains both the before and after save files, the above screenshots, the log file, and all my userdata

### Files
[MekHQ Save Error 24-08-28 V2.zip](https://github.com/user-attachments/files/16791210/MekHQ.Save.Error.24-08-28.V2.zip)

**Comment by LadyAdia** [comment]
Quick note: the save names "House KaruCRASH" is the before file. I forgot to rename the file before compressing it

**Comment by UlyssesSockdrawer** [comment]
I can replicate this with my Nova Dragoons campaign that migrated from nightly 1597 to 1598.

As an interesting point, my mothballed unit is NOT disassembled, so still gets read properly when loading the save.

![image](https://github.com/user-attachments/assets/99fcbf24-490c-462c-90cc-60e84240333c)

![image](https://github.com/user-attachments/assets/8dd2e8ef-fb77-4c09-a043-bab5694c54b1)

Save file attached with the mothballed hunchie in storage.

[The Nova Dragoons30000826.cpnx.gz](https://github.com/user-attachments/files/16795686/The.Nova.Dragoons30000826.cpnx.gz)

**Comment by Tzahr** [comment]
Also confiming replication here. Saves made in the current Nightly corrupt and cause mass disassembly. I did notice that I had one-two units that did *not* fall apart. Specifically - those that had maintenance done today.  

On a whim, I compared the XMLs for my old save versus a re-saved copy of the same one done in the current build, in case I happened to notice anything clearly different. There are some 33.000 points of divergence, so I did not go over all of them; the majority just seems data that is stored in a different order. I did specifically noticed that the following data was consistently different. Under units, the following is taken from the initial save (which loads fine): 

```
<daysSinceMaintenance>29</daysSinceMaintenance>
<daysActivelyMaintained>29</daysActivelyMaintained>
<astechDaysMaintained>174</astechDaysMaintained>
```

This is the same entry in the save that corrupts: 

```
<daysSinceMaintenance>29.0</daysSinceMaintenance>
<daysActivelyMaintained>29.0</daysActivelyMaintained>
<astechDaysMaintained>174.0</astechDaysMaintained>
```

This extra decimal point is consitently recorded in each maintenance entry for each unit. 
Notably, and this is important: the units that did not disassemble (because they were maintained on the day the save was made) did not have any of these three entries! 

I am therefore fairly positive that this extra decimal is the root cause of this issue.

**Comment by repligator** [comment]
@Tzahr 
Which Nightly is the current Nightly (4 digit 15xx code)? 

Latest master (https://github.com/MegaMek/mekhq/commit/198ce0e0ce16af53c487caafdc4f4f75aba2e482)
appears to be affected as well. Compare screenshot from old save with new save.
![Screenshot_20240829_085026](https://github.com/user-attachments/assets/0ee80b74-ea24-407a-996d-3e42213d1565)
![Screenshot_20240829_084906](https://github.com/user-attachments/assets/484ee59c-04e1-4d51-974f-463c2be220d0)

Log file of nothing but loading an affected save
[mekhq.log](https://github.com/user-attachments/files/16799403/mekhq.log)

Save files:
[new-Yakuza3830420101.cpnx.gz](https://github.com/user-attachments/files/16799434/new-Yakuza3830420101.cpnx.gz)
[Yakuza3830420101.cpnx.gz](https://github.com/user-attachments/files/16799462/Yakuza3830420101.cpnx.gz)

**Comment by Tzahr** [comment]
This: 
    MHQ Code Revision: 198ce0e0ce16af53c487caafdc4f4f75aba2e482

**Comment by repligator** [comment]
> I am therefore fairly positive that this extra decimal is the root cause of this issue.

I'm inclined to agree.

From the log I posted:
```
08:53:44,153 ERROR [mekhq.campaign.unit.Unit] {SwingWorker-pool-2-thread-1}
mekhq.campaign.unit.Unit.generateInstanceFromXML(Unit.java:2036) - Could not parse unit 67b56816-c746-41f2-b957-e899d17fb291
java.lang.NumberFormatException: For input string: "6.0"
```

**Comment by repligator** [comment]
Still a couple of doubles that need to be parsed. See https://github.com/MegaMek/mekhq/pull/4749 .
