### ISSUE TITLE
NPE When trying to re-enroll a dropout who was forced to take the entry exam a second time(?) and failed.

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4744]
### Environment
Java 17
Linux
PR (https://github.com/MegaMek/mekhq/pull/4743), which is functionally identical to latest master for the purposes of this issue (https://github.com/MegaMek/mekhq/pull/4741)

### Description
I received a message that Stanley Morris had dropped out. I right clicked him, and selected re-enroll. I then received a message indicating that he had failed his entrance exam. I'm not sure if being required to retake the entry exam is a bug or not. After right clicking him again, and selecting reenroll again, I received the following NPE.

`10:28:25,266 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$1(MekHQ.java:294) - Uncaught Exception Detected
java.util.MissingFormatArgumentException: Format specifier '%s'`

### Files
[mekhq.log](https://github.com/user-attachments/files/16800753/mekhq.log)
[Freddie's Field Guns31511119.cpnx.gz](https://github.com/user-attachments/files/16800755/Freddie.s.Field.Guns31511119.cpnx.gz)

**Comment by IllianiCBT** [comment]
Closing as resolved
