### ISSUE TITLE
POW award is being issued once per month instead of once per internment

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4745]
### Environment
Java 17
Linux
PR (https://github.com/MegaMek/mekhq/pull/4743), which is functionally identical to latest master for the purposes of this issue (https://github.com/MegaMek/mekhq/pull/4741)

### Description
The POW award is being issued once per month instead of once per internment. Thus a soldier who is captured in the first month of a 12 month campaign will be given the award 12 times, instead of once.

### Files
[Freddie's Field Guns31520714.cpnx.gz](https://github.com/user-attachments/files/16802193/Freddie.s.Field.Guns31520714.cpnx.gz)
[mekhq.log](https://github.com/user-attachments/files/16802194/mekhq.log)

**Comment by IllianiCBT** [comment]
The fix here is move the POW check to post-scenario only.

**Comment by IllianiCBT** [comment]
Closing as resolved
