### ISSUE TITLE
Award dimensions not scaling at 87px square

### ISSUE THREAD

**Issue by Stm316** [MegaMek/mekhq#4748]
### Environment
06:12:55,615 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:315) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-08-25T01:25:18.350793281
    Today: 2024-08-30
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.11
    Platform: Windows 10 10.0 (amd64)
    System Locale: en_AU
    Total memory available to MekHQ: 4 GB
    MM Code Revision: 38c5c63334f27ef2c0e2cf39b9b634883a948f14
    MML Code Revision: b1b0bee27fee84bfe1af4375aba9a5423258cea7
    MHQ Code Revision: d9a07a3c8f79c902c2c188a1590b53ee786de3bd
Nightly 1594

### Description
Images set at 87px square seem much larger than rectangular images either 87px wide or high. For reference, 2nd image is 87px high, 3rd image is 87px square. Scaling seems much closer if square images are 57px (by my testing).
![Untitled-1](https://github.com/user-attachments/assets/0dcfabff-d8b7-46d2-b4ca-e35adea47c83)

### Files
**Campaign save**
[The Red Dragons30360808.cpnx.gz.zip](https://github.com/user-attachments/files/16805790/The.Red.Dragons30360808.cpnx.gz.zip)
**Award XML**
[Award_XML_DC_Kurita.zip](https://github.com/user-attachments/files/16805792/Award_XML_DC_Kurita.zip)
**Award images**
[Images_Awards_DC_Kurita.zip](https://github.com/user-attachments/files/16805787/Images_Awards_DC_Kurita.zip)
**Custom unit files**
[MechFiles.zip](https://github.com/user-attachments/files/16805836/MechFiles.zip)

**Comment by IllianiCBT** [comment]
Closing as resolved
