### ISSUE TITLE
Sort Personnel by Name in Choose Spouse (Mate) list

### ISSUE THREAD

**Issue by MattDroz** [MegaMek/mekhq#475]
Currently, the list to choose a spouse/mate is coming up unsorted, which makes it harder to choose a match when trying to play matchmaker between two characters.

**Comment by pheonixstorm** [comment]
Sorting by name doesn't really help all that much. I think sorting by age would be better. That is how I would want it. Someone else may want it another way completely.

**Comment by HammerGS** [comment]
Age and Name.
