### ISSUE TITLE
[0.50.0 Nightly CI #1599] NPE upon loading a save

### ISSUE THREAD

**Issue by LadyAdia** [MegaMek/mekhq#4750]
### Environment
What version of MekHQ does your issue apply to? 0.50.0 Nightly CI 1599
What operating system are you using?  MacOS 14.6.1
What java version are you using?  17.0.12

### Description
While loading a save file from a fresh campaign, Java threw a NPE as shown on the screenshot below. This was an attempt to reproduce the error noted in #4742 with a fresh force created in the new nightly build. I have been unable to reproduce this NPE on my end.

<img width="1440" alt="NPE 24-08-29" src="https://github.com/user-attachments/assets/db9c4023-6338-4f66-8292-190f9c520689">

### Files
[MekHQ NPE Report 24-08-29.zip](https://github.com/user-attachments/files/16811288/MekHQ.NPE.Report.24-08-29.zip)

**Comment by IllianiCBT** [comment]
Unable to replicate in 50.01, closing as resolved. I suspect this issue was resolved by work done prior to the launch of 50.0
