### ISSUE TITLE
RFE: Allow user to set skill level when GM adding minimum complement to units in the hangar

### ISSUE THREAD

**Issue by UlyssesSockdrawer** [MegaMek/mekhq#4752]
### Environment
N/A

### Description
When setting up a campaign file, especially to match published sourcebooks, users currently have to manually tweak the skill level for all crew after adding them via the 'Hire/Add(GM) Minimum Complement' right-click actions.

This RFE is to add a dialogue to the Add Minimum Complement GM action to let the user specify the desired skill level of the crew.

![image](https://github.com/user-attachments/assets/63779bf3-2024-46ec-b2d0-09711bab7875)

Possible dialogue format, if not taken from somewhere else:
![image](https://github.com/user-attachments/assets/360f2854-0717-4751-8753-0d6a90064648)

### Files
N/A

@IllianiCBT

**Comment by IllianiCBT** [comment]
I’ve added this to my 50.01 pile, but anyone should feel empowered to pick it up if they get there before me.

My current line of thinking is to have the GM action ‘add minimum compliment’ to trigger a similar dialog as Mass Hire, so users can specify experience level. Another option would be to have that option be a sub menu in the right click menu where users can specify experience level or random. I prefer the first option as it will be cleaner from a GUI perspective.

I would also like to see us add the ability to right-click Edit Person multiple selected people. This would trigger consecutive Edit Person dialogs.

**Comment by UlyssesSockdrawer** [comment]
I can do 'Mass edit persons' as a separate RFE if you'd like.

**Comment by IllianiCBT** [comment]
Closed as resolved
