### ISSUE TITLE
On nightly, new campaign lost all non-mothballed mechs and vehicles despite them being there at campaign start. No saves retained any non-mothballed units.

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#4754]
### Environment
Nightly from 08/28
Windows 10
Java 17

### Description
MechHQ deleted all of my active mechs and they're not present in any of the saves except the one I made at the start of the campaign. Even the manual save I made doesn't have them - but they where still interactable until MekHQ crashed several months into a contract.
![image](https://github.com/user-attachments/assets/c298ff60-4975-4bd6-9b55-afa411de68ca)
screen shot of only my mothballed units remaining. only one lance was ever deployed so far. I should have four entire lances of active mechs fully assigned and staffed.

Below is a screenshot of the campaign start to reflect this;
![image](https://github.com/user-attachments/assets/4757e0c7-c11f-4ff1-bfb1-46f3c9a14751)

About 4 months of in game events came and went including a battle, and somehow the mechs are all gone in all of the saves since the start...

### Files
[MekHQ-0.50.0-SNAPSHOT.zip](https://github.com/user-attachments/files/16824147/MekHQ-0.50.0-SNAPSHOT.zip)

[Logs and XML and Customs.zip](https://github.com/user-attachments/files/16824157/Logs.and.XML.and.Customs.zip)

**Comment by Tzahr** [comment]
Is this an instance of #4742 ?
This caused Mechs to disassemble into their component parts if the save was made in specific Nightly branch affected by a maintenance value issue. This should no longer be occurring in the latest Nightly, though I'm uncertain if an affected save is automatically fixed. If not, I can likely tell you how to manually try and restore your save.

**Comment by Tzahr** [comment]
I was able to load the CKPT 1 save on the latest build, and it looks fine to me at a glance with 4 mech lances and 4 vee lances.
I would recommend updating build, loading your save, and seeing if everything is where it should be!

**Comment by LadyAdia** [comment]
This is a repeat of #4742 and is resolved as of the 8/30 nightly build (CI1600).

**Comment by IllianiCBT** [comment]
Yeah, my bad. This was caused by adding “just one last simple change” to 50.0 while fatigued.
