### ISSUE TITLE
RFE: Add new log entry for Personnel moved in/out of a ToE Force

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#476]
If a person is moved out of a given ToE Force please add an entry to the Personnel Log. Often this occurs when that person's mech/asf/vehicle is destroyed but other things could cause it.

This would make managing large forces easier by easily identifying which "Force" a person came from after after having their "unit" blown to hell after a battle.

Example
"01/01/3025 Removed from Command Lance"

**Comment by SirMegaV** [comment]
I think even if you have a log file, it will be quite difficult to
reorganize especially when you are dealing with units which require more
than 1 crew such as assault tanks and large crafts. I have an old feature
request, leaving the lost unit in ToE with crews intact using a dummy unit.

**Comment by pheonixstorm** [comment]
So you want something like what I did for the lance tech log?

**Comment by scJazz2** [comment]
@pheonixstorm sure... I leave it to you to sort out the details but you definitely understand what I mean.

**Comment by pheonixstorm** [comment]
ok, so something like Removed from My Lance, My Campaign or Removed from My Lance

Having the fully formation might be more useful but you could end up with... Removed from My Lance, My Company, My Battalion, My Campaign.

**Comment by scJazz2** [comment]
Just removed from "My Lance"... no full path required. If you are running a Large Force you have gotten used to giving the smallest "Force" names something descriptive. That way sorting in Personnel isn't all screwed up.
