### ISSUE TITLE
NPE on interstellar map

### ISSUE THREAD

**Issue by Sir-Payback** [MegaMek/mekhq#4765]
What version of MekHQ does your issue apply to?  0.50.0
What operating system are you using?  Windows, Mac, or Linux?  Windows 11
What java version are you using?  17.

The interstellar map will display a Null Pointer Exception in May of 3150 when you pan the map towards the Free Worlds League.  To re-create the issue just Start a New Game and set the date to May 1, 3150.  Pan the map down and to the left towards the Free Worlds League should be and it'll pop up.  MekHq log file is attached.

[mekhq.log](https://github.com/user-attachments/files/16839973/mekhq.log)

**Comment by HammerGS** [comment]
Lots of these.

```
mekhq.MekHQ.lambda$main$1(MekHQ.java:294) - Uncaught Exception Detected
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "java.util.Map.get(Object)" is null
	at mekhq.gui.InterstellarMapPanel$6.paintComponent(InterstellarMapPanel.java:689)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
```

**Comment by repligator** [comment]
I did some panning around while zoomed in. Looks like Zara (FWL) is causing the issue.
[mekhq.log](https://github.com/user-attachments/files/16842533/mekhq.log)
