### ISSUE TITLE
Personnel Clean Up 

### ISSUE THREAD

**Issue by Tempest-56** [MegaMek/mekhq#4771]
After transferring an existing campaign from 49.18 to 50.0 (Windows version, Java 17), I turned on the Personnel Clean Up option. When reaching the last day of the month, MekHQ pops an error of `Uncaught java.until.ConcurrentModificationException detected.` and no personnel are cleaned up. I tested and was able to replicate the behavior with a fresh campaign/save as well. Log and save for the fresh campaign attached.
[mekhq.log](https://github.com/user-attachments/files/16842167/mekhq.log)
[Autosave-1-The Wraith Jägers-31510128.cpnx.gz](https://github.com/user-attachments/files/16842172/Autosave-1-The.Wraith.Jagers-31510128.cpnx.gz)

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by IllianiCBT** [comment]
Deleted spam bot message
