### ISSUE TITLE
RFE: Maintenance/Supply tab in Hangar, and maybe ammo too.

### ISSUE THREAD

**Issue by Nikarus2370** [MegaMek/mekhq#4773]
Given the recent update, there's a lot more the average player needs to know about keeping their mechs in fighting shape. Currently you can see an average "Quality" rating for a unit in the Hangar, but there's not really a quick way to see an itemized list of it's parts and their respective quality ratings. You can move to the next maintenance cycle and look at the previous report, but this is a text heavy window that is clunky to read.

So my suggestion. In the Hangar, on the right where there is typically a Technical Readout for the currently selected machine... add an extra tab to that window that could be labeled Maintenance/Supply (or something else more fitting). 

Near the top of this tab, could have a button "Buy Parts", this would open a Parts In Use window listing parts of the currently selected unit, including currently equipped ammos, as well as other ammos that could be equipped to the current unit. 

Next a few lines dictate the unit's current Monthly Supply Costs. Then a list of all parts installed in the unit that the game tracks quality for. Splash of red/orange on A/B rated parts that are liable to break, black background white text on parts that are destroyed maybe.

Finally down the bottom (or maybe a 3rd tab) could put the currently equipped ammo, with dropdowns for selecting other ammos a-la swapping them in the MegaMek lobby.

**Comment by Nikarus2370** [comment]
***

Addendum. Another minor suggestion that could be whipped up quickly to help with monitoring operating costs would be to add Ammo and Fuel columns to the existing Status view in the hangar (currently includes maintenance costs, but not ammo/fuel.)

**Comment by IllianiCBT** [comment]
Taking a look at this now.

For future issue reports please ensure you're logging only one issue per report (i.e. in this case the quality report and ammo/fuel columns should be separate PRs. It helps keeps things neat and avoids situations where half of a PR has been addressed but it's not obvious which.

**Comment by IllianiCBT** [comment]
I'm going to close this as 'resolved'. Please open a separate case including the ammo/fuel cost request as it's a more involved task than I want to do right now, but I don't want it missed.
