### ISSUE TITLE
RFE MHQ v50.00  - Reset Preset Reset - "Extra Randomness" & Company Generator

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#4774]
for MHQ v 50+.  Discussed in QA in discord.  It has been learned that extra randomness can generate worse pilots on average.  It is now enabled in all of the new presets.  This can result in a high percentage of a Generated Company being green or worse skill level, including possibly more than 50% of MWs.

Determined that best course of action would be disabling this option in the new presets, and adding a popup explaining it can result in worse pilots on average.  

This was requested by Illiani.

Not directly related, but relevant - We learned that The Prior StratCon Alpha preset was/is bugged and cannot generate a by the book green pilot. The 50.00 presets can.  But Prior StratCon presets cannot. Therefore, when discussing pilot issues with people, it needs to be determined if they are on milestone, or using a preset based on the old presets, because if they are, it is probably bugged too (Like mine).

**Comment by UlyssesSockdrawer** [comment]
As an aside, it would be nice to add one more preset if it gets turned off in the others - essentially Preset 2: Everything, including extra randomness.

I've been enjoying having more Green and Ultra Greens across the board as it more closely matches to some of the campaign books.

**Comment by IllianiCBT** [comment]
Both issues have been (hopefully) resolved by #4817, extra randomness was disabled in the new player preset but retained in complete experience. Once the new campaign options dialog is online we can include information about extra randomness causing lower than average personnel skills. Though I think a pop-up will be a tad overkill, I'm assuming you mean a tooltip, if so I agree.

Closing as resolved.
