### ISSUE TITLE
Remove ClanTech penalties for Technician Skill Rolls

### ISSUE THREAD

**Issue by Saklad5** [MegaMek/mekhq#4782]
[Recent errata](https://bg.battletech.com/wp-content/uploads/2024/08/Campaign-Operations-2024-08-22-v5.0.pdf) for Campaign Operations has removed the +2 target modifier applied to Inner Sphere Technical Teams working with ClanTech.

The unofficial SPA "Clan Tech Knowledge" should also be marked as Legacy and removed insofar as it is possible to do so without breaking backwards compatibility with older saves.

**Comment by IllianiCBT** [comment]
Closing as resolved
