### ISSUE TITLE
Purple Heart not auto awarded

### ISSUE THREAD

**Issue by Desertdream2** [MegaMek/mekhq#4785]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
v0.50.0
Windows 10 10.0 (amd64)
17.0.12

### Description
After my first two missions, I received 1 injury (each) on two separate pilots. Neither time was a Purple Heart automatically awarded.
![image](https://github.com/user-attachments/assets/bd54cc79-9d1f-47d9-bc18-7c79fb8b2a36)
![image](https://github.com/user-attachments/assets/6330d995-0baf-484f-9f29-4770fa156b75)
![image](https://github.com/user-attachments/assets/2bd1473c-9091-44c1-a5b8-02abca2b8e17)
![image](https://github.com/user-attachments/assets/1119b084-6130-4948-a4bf-05265e61ca28)

One note, since the screenshots were taken, I went ahead and manually gave the MechWarrior a Purple Heart.

### Files
[5th ISR Bobcats30250228.cpnx.gz](https://github.com/user-attachments/files/16881476/5th.ISR.Bobcats30250228.cpnx.gz)
[Round-11-autosave_2024-09-04_15-57-45.sav.gz](https://github.com/user-attachments/files/16881479/Round-11-autosave_2024-09-04
[megamek.log](https://github.com/user-attachments/files/16881482/megamek.log)
[mekhq.log](https://github.com/user-attachments/files/16881483/mekhq.log)
_15-57-45.sav.gz)
[entitystatus.txt](https://github.com/user-attachments/files/16881495/entitystatus.txt)
[gamelog.html.pdf](https://github.com/user-attachments/files/16881498/gamelog.html.pdf)

**Comment by Desertdream2** [comment]
Updated Files/screenshots.
![image](https://github.com/user-attachments/assets/e546353c-7571-4366-9926-43da994ace0f)
![image](https://github.com/user-attachments/assets/77133c18-bbf4-40a7-aec6-66293281203b)
![image](https://github.com/user-attachments/assets/05ff17f9-2585-4151-b02d-d713096770e7)


[5th ISR Bobcats30250310.cpnx.gz](https://github.com/user-attachments/files/17036634/5th.ISR.Bobcats30250310.cpnx.gz)

**Comment by IllianiCBT** [comment]
Closing as resolved
