### ISSUE TITLE
50.00 - StratCon Prisoner Defection is happening too often.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#4787]
14:43:03,097 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:315) - Starting MekHQ v0.50.0
    Build Date: 2024-09-01T14:30:44.398779200
    Today: 2024-09-04
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.12
    Platform: Windows 10 10.0 (amd64)
    System Locale: en_US
    Total memory available to MekHQ: 8 GB
    MM Code Revision: ce95ba3d3c12c0e4e116cb713e47493316831daa
    MML Code Revision: 19b12fa9a622458ed00b0dc94ef1d0f2b19bbb66
    MHQ Code Revision: eaa1134aa318d26121a879c24651e16e84252b39

Title.  Finished scenario.  14/19 enemy prisoners defected.  They ARE from a green unit, but even so, that seems excessive.  Ballpark under old system with unit rating like mine I would get roughly 1/10 defect.

![image](https://github.com/user-attachments/assets/60fa0d3b-4bd7-40bb-a707-378e838c6e7d)

[ThomCustoms9.4.24.zip](https://github.com/user-attachments/files/16883261/ThomCustoms9.4.24.zip)
[Celcius 23330710321a.zip](https://github.com/user-attachments/files/16883264/Celcius.23330710321a.zip)
[mekhq.log](https://github.com/user-attachments/files/16883306/mekhq.log)

**Comment by Thom293** [comment]
This is the end of the above contract.  17/26 Prisoners defected.  

![image](https://github.com/user-attachments/assets/d4cc1658-36a8-42a4-80fb-2c795fa278d1)

**Comment by IllianiCBT** [comment]
You can read more about the prisoner defection system in docs, but to summarize, the algorithm for prisoner defection is....

> 8 + Enemy Dragoon Rating - Campaign Unit Rating + Individual’s Loyalty Modifier

For you that equates to `8 + 3 - 3 + loyalty`. So, assuming average loyalty, you'd be looking at a TN of 8 per person. Which matches your experience. I do think, now I have live data, that this is too low and definitely could do with adjustment. I'm thinking a base TN of 10 would present more reasonable results.

Also the aforementioned documentation should be updated now we have revised CamOps Reputation, I'll get that done.

**Comment by IllianiCBT** [comment]
Marking this case as closed, however this is with awareness that the final value may need to be further adjusted. In the event the new TN still doesn't yield suitable results this case can be re-opened.
