### ISSUE TITLE
50.00 - Untreated Personnel Nag is counting untreated Defectors.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#4789]
Screen below shows it popping with only prisoners untreated.  If you treat the defector, the nag stops.

![image](https://github.com/user-attachments/assets/229c903e-62a3-42a0-83a4-4905f51f098a)

[Celcius 23330710321a.zip](https://github.com/user-attachments/files/16883580/Celcius.23330710321a.zip)

**Comment by Thom293** [comment]
[ThomCustoms9.4.24.zip](https://github.com/user-attachments/files/16883603/ThomCustoms9.4.24.zip)

**Comment by IllianiCBT** [comment]
The nag just needs to be adjusted to exclude personnel that are current prisoners, but not bondsmen. When I wrote this I’d only been in the project for about a month so clearly didnt know that ‘prisoners’ didn’t include ‘prisoner-defectors’ I believe adjusting the loop to use `person.getPrisonerStatus.isCurrentPrisoner()` will give us the result we need (though it should be checked that this will exclude Bondsmen as we want the nag to run for them).
