### ISSUE TITLE
units.cache gaining extra duplicates of refits and sometimes the entire unit database

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#4791]
### Environment
Windows 10 / Java 17 / 0.50.00 release

### Description
units.cache is receiving duplicates of refits when they are made. If units.cache is deleted to attempt resolution, units.cache recieves a duplicat of all BattleTech units (not just customs), doubling the file size the first time and increasing by the same amount each successive time, resulting in multiple duplicates of everything.
![image](https://github.com/user-attachments/assets/c5e25ee4-93ab-4b6d-bd6c-e34bdf46ef58)
![image](https://github.com/user-attachments/assets/c5f52fdc-de97-46f5-8ecc-b2e58efbb0a9)
![image](https://github.com/user-attachments/assets/e3a3373d-60f4-4703-815a-94df1d8cdefb)
The 'Firebird' was a refit made before moving to 0.50.00, the (Food Truck) was made after, both are duplicated. Removing the units.cache and the mechfiles and even replacing the units.cache with one from another verified 'clean' installation seems ineffective.
### Files
[FOODIES.zip](https://github.com/user-attachments/files/16885492/FOODIES.zip)
[customs.zip](https://github.com/user-attachments/files/16885494/customs.zip)
[units.zip](https://github.com/user-attachments/files/16885498/units.zip)
The Units.cache file attached has duplicates of custom refits.

**Comment by OrbMonky** [comment]
![image](https://github.com/user-attachments/assets/f8966e1f-cb4c-4e04-b5e2-636e54445318)
Here is a screenshot of a 'doubled' units.cache, if it is deleted while mekhq is running and refresh cache is ran than this is what seems to occur.

**Comment by Thom293** [comment]
We were talking about this on Discord.  A few days ago I had 3 copies of everything and now I have 5 copies of everything.  Other than deleting the cache once, I have done nothing out of the ordinary. So, for whatever reason this this will incrementally grow and and eventually become huge.

**Comment by UlyssesSockdrawer** [comment]
I wonder if this is also playing into what happens with the freezing on customisation performance issue? https://github.com/MegaMek/mekhq/issues/4554
