### ISSUE TITLE
Unit Rating - DropShip crews not accounted for correctly in Average Unit Experience calculations. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4803]
### Environment
21:21:52,454 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:315) - Starting MekHQ v0.50.1-SNAPSHOT
    Build Date: 2024-09-06T01:22:33.618875471
    Today: 2024-09-07
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MekHQ: 8 GB
    MM Code Revision: 089e4490c50b7bbf1b80ff9e39c239f0d60ad0ff
    MML Code Revision: 0581ab356323b936a71aca60af9b01fc4d9135d8
    MHQ Code Revision: 1348549171cc252f673c8856fef775e5e2b96a91

### Description
Average Unit Experience calculation for Unit Rating is meant to account for DropShip crews, which may only have Tech/Vessel and not gunner or piloting as relevant. This likely skews the totals calulcation of the skill sum and divisor, leading to lowered Average Experience Ratings.

This will likely also apply to WarShips, ref. Navigators. 
JumpShips are correctly excluded as per CamOps. 

### Files
Dataset with dropships if testing is required. 

[1st Rimward Hussars.zip](https://github.com/user-attachments/files/16919487/1st.Rimward.Hussars.zip)
[customs.zip](https://github.com/user-attachments/files/16919486/customs.zip)

**Comment by IllianiCBT** [comment]
So, my inclination here, to save a lot of math is to just not count crew at all. As we're only told to sum the gunnery/piloting skills (or unit appropriate equivalent) and the crew are support personnel which wouldn't normally be counted. So I think the play is to discount them entirely. This has the added benefit of being the easiest to code.

**Comment by IllianiCBT** [comment]
Closing as resolved
