### ISSUE TITLE
Uncaught Java.lang.NullPointException

### ISSUE THREAD

**Issue by Gobser21** [MegaMek/mekhq#4805]
### Environment
MekHQ 0.50
Windows
Java 17.0.9

### Description
On company generation and after this on every "advance day" button press, an error message pops up 
![image](https://github.com/user-attachments/assets/6753d350-83f7-4568-b7b4-60ee4309d5a9)

Standard New Pilot ruleset. Default company generation settings, nothing altered.

[mekhq.log](https://github.com/user-attachments/files/16919971/mekhq.log)

[The 30th Safety Switch Savages31540122.cpnx.gz](https://github.com/user-attachments/files/16919972/The.30th.Safety.Switch.Savages31540122.cpnx.gz)

[megamek.log](https://github.com/user-attachments/files/16919974/megamek.log)

**Comment by IllianiCBT** [comment]
Looks like it’s trying to display or redraw your TOE but is running into a null person issue.

**Comment by repligator** [comment]
Using the latest master, (https://github.com/MegaMek/mekhq/commit/62e881f1605f59f6323256a7b88a42da84c11233) I can't replicate the NPE, but I do get some confusing output from breakpoints on lines 557 and 558 of `ForceViewPanel.java`
```
campaign = {Campaign@8669} 
this = {ForceViewPanel@8899} 
force = {Force@8867} "Able Lance"
battleValue = 9570
cost = {Money@8927} "CSB 40692700.0"
tonnage = 320.0
number = 4
commander = "No personnel found"
campaign = {Campaign@8669} 
```
"No personnel found" despite the fact the GUI shows the commander correctly.
![Screenshot_20240907_203130](https://github.com/user-attachments/assets/cbaafd3b-799b-4d5e-b724-9d6b079cdf42)

**Comment by IllianiCBT** [comment]
Closing as resolved
