### ISSUE TITLE
[RFE] Display unit ownership

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/mekhq#4807]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

In MekHQ, personnel can be flagged as owning a specific unit, which matters for compensation on leaving the force. Currently this is displayed in the Edit Person menu, which requires having GM mode active, and manually opening a new window for each person. Displaying this somewhere more easily visible, such as the Person View pane or a column entry in the Personnel tab, would be more efficient for quickly determining which personnel own which units (if any). 

### MekHQ Suite Version *

0.50

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
