### ISSUE TITLE
Spouse Status is listed twice for deceased spouse

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4808]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

A deceased spouse has their marital status displayed twice. Once as "Spouse" and the other as "Former Spouse". See Attached screenshot.

![Screenshot_20240908_151450](https://github.com/user-attachments/assets/9227b8bc-4e38-49e2-b77a-39faa76128f9)

### Steps to Reproduce

1. Marry two people.
2. Have one of them die.
3. Observe the deceased.

### Operating System *

Linux

### Java Version *

17

### MegaMek Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Latest Master (https://github.com/MegaMek/mekhq/commit/62e881f1605f59f6323256a7b88a42da84c11233)

### Attach Files

[The Blacksmiths31510101.cpnx.gz](https://github.com/user-attachments/files/16923392/The.Blacksmiths31510101.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
I suspect when a character dies we clear the marriage on the surviving partner, but not the deceased. Should be an easy fix, I’ll tackle it as part of my relationship overhaul once I’m back from vacation

**Comment by IllianiCBT** [comment]
This should be resolved as of yesterday's nightly. Closing as resolved. If you opt to test it note that the fix does not work retroactively.
