### ISSUE TITLE
[0.50.0] Error when editing support vehicle crew

### ISSUE THREAD

**Issue by EvilAtlas** [MegaMek/mekhq#4814]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

![Screenshot 2024-09-10 112525](https://github.com/user-attachments/assets/13e975d3-fb19-41e1-b7c1-b1337e03cfb9)

I get an error when I try to GM edit the crew assigned to a J-37 Ordnance Transport. It doesn't happen with the other support vehicles in my roster; it may be linked to the presence of a "crewmember" personnel slot. The game doesn't crash and no long-term issues appear, but this error popup comes up instead of the edit window. Other personnel menu options like changing ranks still work. The error recurs every time I try to edit one of the personnel assigned to either of the transports.

### Steps to Reproduce

1. GM add unit to campaign (along with all other units)
2. Hire minimum complement (along with all other units)
3. Select one of the personnel assigned to a J-37 Ordnance Transport
4. Right click to bring up the context menu
5. In the GM Mode section at the bottom of the context menu, select Edit

### Operating System *

Windows 11

### Java Version *

17.0.12

### MekHQ Suite Version *

v0.50.0

### Attach Files

[transportpersonnelbug.zip](https://github.com/user-attachments/files/16948234/transportpersonnelbug.zip)
![image](https://github.com/user-attachments/assets/63b01281-d068-4a4a-999b-4909063718ba)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
This appears to be fixed as of yesterday's nightly. Closing as resolved.
