### ISSUE TITLE
[RFE] Crew breakdown display on Hangar page

### ISSUE THREAD

**Issue by Tempest-56** [MegaMek/mekhq#4824]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

It's a mild annoyance when handling units with multiple crew members is determining/tracking what roles are needed and what's missing. Currently the Hangar tab (under the Status view) shows the raw number of crew a unit needs but not the breakdown - IE how many drivers/gunners/crewmembers - nor does a unit's status card in the Hangar or either of the stores. (Dropship cards show a vague Officer/Enlisted/Gunner/Bay Personnel breakdown, but that's both inaccurate to actual crew needs and doesn't show roles.) It would be a useful streamlining feature to be able to find that information quickly - possibly a tooltip while hovering over the mentioned raw crew number in the Hangar tab?

### MekHQ Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by SuperStucco** [comment]
While somewhat cryptic, changing the crew column to show something like 1D(1)/2G(3) to show that it has 1 driver (1 required), and 2 gunners (3 required) might work.  Similarly using 'P' for pilots and 'C' for crew (both support vehicle crewmembers and vessel crew).  Might use 'A' (for 'Actual', typical callsign for a formation commander) with Mechs that have a command console e.g. 1P(1)/0A(1) shows the backseat is empty.

**Comment by IllianiCBT** [comment]
Closing as resolved
