### ISSUE TITLE
[0.50.01-SNAPSHOT] Campaigns from prior versions will fail to load if any students are enrolled in named prestigious institution affected by the trademark compliance pass. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4827]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

![image](https://github.com/user-attachments/assets/2689d82d-4f1b-41c0-88d7-7b28104f0d80)

When loading a campaign save from a version predating the trademark pass, the savegame will fail to load if any student is currently enrolled in a prestigious academy whose name is affected by the change in terms.
This specific example occurred because _Allison MechWarrior Institute_ was changed to _Allison MekWarrior Institute_.

The tooltip provides a workaround. 

### Steps to Reproduce

1. In a previous version, send a student to a prestigious academy whose name will be affected by then change. 
2. Enroll. 
3. On the current version, load the campaign. Observe failure to load.

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0,50,01 - 55fbc3f32d79c96eb230d6cb38607aababc788e6

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/16992946/mekhq.log)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
