### ISSUE TITLE
Table headers that sort values formatted as "X C-Bills" sort as text instead of sorting as numbers. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4829]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

Any tab in the personnel or hangar views that lists its value in the _X C-Bills_ format sorts as text instead of as numbers. This is likely because the value _is_ text. For sorting and filter purposes, it is however intended these sort as numbers instead. 
If possible the table behaviour should be adjusted so that it respects hierarchy of numbers on sorting. 

Sorting as text (current situation): 
1, 11, 110, 2, 20, 3, 3.060,000, 4, etc... 

![image](https://github.com/user-attachments/assets/84c451c1-b697-4e1b-99c3-fc1ee00b0690)

Sorting as numbers (desired): 
1, 2, 3, 4, 11, 20, 110, 3.060,000, etc...

### Steps to Reproduce

Not required. 

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0,50,01 - 55fbc3f32d79c96eb230d6cb38607aababc788e6

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
