### ISSUE TITLE
Bug: BAR 0 Armor (Refit to 'Standard' in the 'Meklab) on Buffel causing 999 difficulty maintenance rolls and other errors

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#4832]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

I refit a custom Buffel Engineering Vehicle (it's spelled with a non-english u with dots above it so it is harder to search for), I selected Standard as the armor option. It seems to think the vehicle has 'BAR 0 armor (X)' and this is causing it to roll 999 difficulty checks for maintenance. Other issues that seem related are that when attempting to refit a Buffel to this variant, it creates an error on launching the refit selection window and fails to load. Something is going wrong with this vehicle's customization which seems to be setting the wrong armor type, an issue that hasn't presented on other vehicles being set to 'standard' armor.

![image](https://github.com/user-attachments/assets/7a0728da-2853-45cc-99b2-bf7b68975ae0)
![image](https://github.com/user-attachments/assets/b297ea70-b45f-4f93-9779-8b2e29015949)

Focus: Issue with what appears to be an incorrect armor type getting assigned during megamek's meklab refit process (these were refit from mekhq). This appears to affect maintenance and refit kits as well as repairs.

### Steps to Reproduce

Create Buffel with 'Standard' armor option. Set a tech to maintain, advance to Maintenance Day.
Secondary issue: Create Buffel with 'Standard' armor option, acquire second Buffel, attempt to refit second Buffel to the variant with 'standard' armor.

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Attach Files

[Helena's Valkyries30250706.cpnx.gz](https://github.com/user-attachments/files/17002196/Helena.s.Valkyries30250706.cpnx.gz)
[customs.zip](https://github.com/user-attachments/files/17002205/customs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by OrbMonky** [comment]
After testing and reconfiguring the armor in Meklab proper, it seems like it was 'a grade' vs 'f grade' standard armor. To my knowledge, limited though it is, F grade (or whatever is the best grade if you're running the reversed order on quality names option) should be the only option that has standard armor. It was able to be set to standard armor for a grade that didn't have that as an option, seemingly. Saving it with a different armor type then changing to F grade and re-selecting standard armor fixed it.

**Comment by IllianiCBT** [comment]
This specific issue has now been closed. Though in testing this we ended up finding a secondary issue which Monky has agreed to open in a separate report.

Closing as resolved.
