### ISSUE TITLE
Unable to afford expenses nag appears when current funds are below loan collateral.

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4834]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

When taking out a loan and having total funds below the collateral of the loan causes a nag message to appear at the end of the month. This nag message claims the inability to cover all expenses, even if this is strictly speaking not true. 
E.g. one can be below a 10mil collateral, and still be quite capable of paying expenses, while this nag suggests imminent bankrupcy instead. 

![image](https://github.com/user-attachments/assets/55cb2bda-5eeb-4219-8aa5-c1a9c6e916b3)

This is possibly functioning as intended, but I was requested to bring this up just for a sanity check. 

### Steps to Reproduce

1. Take out a loan through the finances tab. 
2. Take note of agreed collateral.
3. Ensure current funds are below the agreed collateral (GM adding a negative amount worked fine on my end). 
4. Proceed to end of month, observe nag message. 

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0.50.01-SNAPSHOT - Revision: e0a790a6a4cfccb36f50625799b23898e0e8bd1a

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
