### ISSUE TITLE
[RFE] Clarify 'maintenance cycle in days' campaign option to reference longer peacetime cycles.

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4835]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

The CamOps maintenance rules presume a 7 day cycle, multiplied x4 when not on contract. 
This is currently implemented using the "Maintenance cycle length in days" Campaign option under Repair and Maintenance. This value is used as the on-contract cycle, and then multiplied x4 when off contract. 
![image](https://github.com/user-attachments/assets/9ee64228-269e-4529-97bc-fb9d818ff974)
This can cause confusion for users using/importing the previous standard 30 day cycle, in which off-contract maintenance will only happen every 120 days. 

This can be clarified by updating the tooltip and label to reference the multiplier. 
E.g.: _Maintenance cycle length in days (x4 if off-contract)_
OR
_Wartime maintenance cycle in days_ 
With tooltip like: _Interval between unit maintenance. The peacetime value is automatically mulitpied by four if there is no active contract, or if the contract is of the "Garrison Duty" type._

### MekHQ Suite Version *

v0.50.01-SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
