### ISSUE TITLE
[0.50.01-SNAPSHOT] Importing a campaign save does not correctly import skill costs for skills affected by namechange.  

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4836]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

When importing a campaign save using custom skill cost values found in Campaign options -> Experience, values for skills whose name has been altered because of the change in terminology are not updated correctly, and will instead resort to default skill cost values. 

![image](https://github.com/user-attachments/assets/0c4d9162-3a95-4dda-90f0-b3f8630a7633)
Example. The skill costs for the Mek and Aerospace skills are meant to be identical. 

Affected skills: 
- Piloting/Mek
- Gunnery/Mek
- Gunnery/BattleArmor
- Gunnery/ProtoMek
- Anti-Mek
- Tech/Mek
- Tech/BattleArmor

Potentially MedTech as well, but this was unclear on my end. 

### Steps to Reproduce

1. Customise affected skills in a preceding version, and save campaign.
2. Load in current Nightly. 
3. Observe value discrepancy. 

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0,50,01 - 55fbc3f32d79c96eb230d6cb38607aababc788e6

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
