### ISSUE TITLE
Vehicle Crews are always Mechanics.  I would make sense to have astechs for some vehicles with kitchens.  It would also make sense to have Mech Techs as Crew for some vehicles with ability to repair mechs

### ISSUE THREAD

**Issue by demster42** [MegaMek/mekhq#4839]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is a new feature

### Brief Description *

I would like to have Mechanics, Mech Techs, and Astechs as crewmembers for vehicles that require them.

### MekHQ Suite Version *

v50.0

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
We can easily check to see if the personnel is any variety of tech (including Astech and Medtech). I think that makes a lot of sense, and just let users decide which type personnel is most appropriate for their vehicle of choice.

**Comment by OrbMonky** [comment]
If there is no dedicated 'tech type in the books I would prefer these just be Astech honestly. Everyone else is usually far more valuable in the maintenance bay and usually paid according to that value. Gives a reason to hire them beyond 'hey what do these do' as well.

**Comment by RaozSpaz** [comment]
> If there is no dedicated 'tech type in the books I would prefer these just be Astech honestly. Everyone else is usually far more valuable in the maintenance bay and usually paid according to that value. Gives a reason to hire them beyond 'hey what do these do' and then filling with temps as well.

Vehicles are repaired by Mechanics. Which require their full group of AStechs to do their job right. What are you actually wanting done with this request as I dont fully understand it. You can already technically do this by just paying the EXP for the skill on the crew. Though I dont think they can do anything day of their mission.

**Comment by OrbMonky** [comment]
So let's address this from the top.

Mechanics where arbitrarily decided to be 'the crewman'.
Mechanics are more valuable for their role than being a ride-along.
Mechanics in BT are technicians capable of up to factory level repair of extremely high tech, closer to engineers than real life 'mechanics' that we think of.
Astechs are grease monkeys, wrench turners, people who show up and do the job even if it's mind numbing/trivial and just needs someone to do it.
Vehicles who require crewmen outside drivers and gunners don't pack room for a Mechanic and six Astechs, meaning it is A: not a repair/maintenance situation and B: not something that requires a fully fledged Mechanic.

Unless these assumptions are wrong, it doesn't seem a Mechanic, in the sense that Battletech portrays a Mechanic, is the fit for this, and as it was arbitrarily chosen, a hired Astech seems like a better fit. This issue could be solved easily by simply changing the 'generic crew' type to Astech, essentially.

**Comment by Saklad5** [comment]
I don't see what this issue wants changed, personally.

For what it's worth, AToW includes "Technician/Mechanics" in the skill field for tankers, meaning they may have some of it. To put that in context, however, MechWarriors also get "Technician/Any". And AToW's Technician subskills are more nuanced than CamOp's, which is what MekHQ is currently using: that one subskill wouldn't allow you to fix *everything*. Based on what I've seen in the fiction and in the rules, I think combat personnel are mainly expected to pitch in as AsTechs if there's a shortage, or maybe patch up motive systems between fights in the case of vehicle crew.

**Comment by SuperStucco** [comment]
The Vehicle Crewmember role requires just a single rank of Tech/Mechanic - that's most definitely not personnel who are one step short of being classified an engineer.  It's far closer to an AsTek than a Mechanic who has to be better than ultra-green to be practically functional.

But I wouldn't mind seeing a range of skills being qualified for assuming the Vehicle Crewmember role, from Astek to Medic to Tech/Mechanic.  I would like to retain the specific role as separate from the others as it is distinct from someone making repairs (Mechanic) or assisting (AsTek).

**Comment by demster42** [comment]
When I click Hire Minimum Complement in MekHQ, I want the crewmen to be Astechs, but I want to be able to assign any tech to that role on my own. If the vehicle is a MASH unit, I want to be able to assign med techs. If the unit is a Field Kitchen, I want Astech to be filled in. If the vehicle is a Mobile Base, I might want to assign both Mech Techs and Mechanics to represent the staffing to do the maintenance of units in the field.   I like IllianiCBT's initial response.

**Comment by Saklad5** [comment]
AsTechs really have nothing do with Field Kitchens. You could reasonably assume that the required crew should have the Art/Cooking skill, but that's not specified in the rules. No Culinary Teams to speak of.

As for MASH Equipment, that *is* supposed to be staffed by a Medical Team, and I believe there's an RFE for that already.

I'm actually not sure Mobile Field Bases are supposed to require extra crew. That only shows up in the rules for advanced buildings, and since Technical Teams aren't the right size I have no idea what the added personnel would represent. I've asked about it on the rules forum.

**Comment by demster42** [comment]
Thanks.  What is your recommendation?  I can't find it in either of your responses.  I see Astechs as general helpers so having them assigned feels right compared to the available occupations in  MEKHQ.

**Comment by repligator** [comment]
See also https://github.com/MegaMek/mekhq/issues/4488

**Comment by IllianiCBT** [comment]
Closing as resolved
