### ISSUE TITLE
Repairable crippled dropship on ground map shows in salvage/sell screen with bounty enabled

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#4845]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

When crippling a dropship on the ground map rather than destroying it, it shows up in the salvage window. Bounty is at 10% but it does not process the bounty and it seems to treat it as any other salvageable unit. This also happened with an air battle and a crippled dropship earlier in this contract.

Discussion on discord expects this to be an oversight of the expected behavior of not seeing the dropship on the salvage/sell screen and getting the bounty instead.

### Steps to Reproduce

1. Launched into 'destroy grounded dropship' mission
2. Reduced dropship to 'crippled' status without destroying it
3. Upon resolving scenario it showed up in the salvage/sell screen and did not process the bounty

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Attach Files

[salvage.zip](https://github.com/user-attachments/files/17019296/salvage.zip)
[customs.zip](https://github.com/user-attachments/files/17019305/customs.zip)
[DSLOOT.zip](https://github.com/user-attachments/files/17019308/DSLOOT.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by RaozSpaz** [comment]
At Illiani's request

Page 215 of CO: Dropships cannot be recovered on the ground.

So any situation that results in a DropShip being salvageable on a ground map should probably proc the bounty. As there just isn't the time required to recover said unit.

Its possible that intention was still in place for DropShips to be repairable should you actually control the planet its crippled on, and it just can't be moved from where its at. But this is just conjecture based on assumptions.

**Comment by IllianiCBT** [comment]
Closing as resolved
