### ISSUE TITLE
When I customized an Overlord Dropship by removing some bay doors it shows up damaged

### ISSUE THREAD

**Issue by honestaly** [MegaMek/mekhq#4849]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

So I customized an Overlord Dropship in 50.0 and when I did... every time I open the save file it's Vehicle bays are damaged.. I've repalced them quite a few times, but each time I do they show up damaged when I reload the saved file.

I was told to reference this closed bug as it apparently is not fixed.
https://github.com/MegaMek/mekhq/issues/2878

### Steps to Reproduce

1. open campaign file
2. look at the history for today to see that all the damaged parts were repaired
3. go to the repair bay and see those same parts are damage still, even though they've been repaired.

![2024-09-17_16-18-15](https://github.com/user-attachments/assets/b78c767d-940e-43fd-bbd7-ab69d7992724)
![2024-09-17_16-20-18](https://github.com/user-attachments/assets/9677f939-bc32-4f04-b5ec-a52d19846a08)
. 

### Operating System *

Windows 11

### Java Version *

17.0.11

### MegaMek Suite Version *

v0.50.0

### Attach Files

[Diplomatic Solutions30480302.cpnx.gz](https://github.com/user-attachments/files/17035314/Diplomatic.Solutions30480302.cpnx.gz)
[Unit Files.zip](https://github.com/user-attachments/files/17036017/Unit.Files.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
I can't work out the cause, but a work around does exist: if you go into GM Mode and restore the unit that permanently resolves the issue.

**Comment by TenkawaBC** [comment]
I think I had a bug which is the same as this one, but it presented differently.

My leopard failed a maintenance roll, resulting in some thruster damage. No matter how many I repaired, the next load of my save, they were all damaged again.

So either it is not saving correctly, or the repair is not marked correctly.

**Comment by TenkawaBC** [comment]
In the .cpnx file, I found the following: 
		<part id="4860" type="mekhq.campaign.parts.MissingCubicle">
			<id>4860</id>
			<name>Heavy Vehicle Cubicle</name>
			<unitTonnage>9700</unitTonnage>
			<mode>NORMAL</mode>
			<skillMin>1</skillMin>
			<unitId>f9c55f8a-daf3-42d4-972a-bb5e35911437</unitId>
			<brandNew>false</brandNew>
			<quantity>1</quantity>
			<quality>3</quality>
			<parentPartId>1893</parentPartId>
			<bayType>VEHICLE_HEAVY</bayType>
		</part>

Part IDs 4845 through 4860.  This is why, when loading it says that it is damaged. So the question is why the missingCubicle entries were written to the .cpnx file. This also explains why a GM restore will "fix" it, because it voids all the missing and damaged components.

**Comment by TenkawaBC** [comment]
Testing done with 0.50.1.

-Current save file has 16 damaged cubicles.
-Load, 16 cubicles damaged in megamek and 2 damaged doors (8 cubicles each).
-Saved, still 16/2
-repaired bay doors, saved, still 16 cubicles.
-aquired part for cubicle, fixced 1 cubicle, saved, 15.

Using GM mode, Fixed all 8 light vehicle cubicles, leave the 8 heavy cubicles alone.
Edit dropship, damage bay door 7 (light vehicle bay), save, load, 16 damaged cubicles. All 8 light cubicles were marked destroyed if the door was damaged.
