### ISSUE TITLE
MekHQ Contract Bug

### ISSUE THREAD

**Issue by BigBebberino** [MegaMek/mekhq#485]
So far, after multiple tries, all base amounts for a contract have no starting value for compensation, ie a 0

This is for 0.43.4

**Comment by Bonepart** [comment]
I would need to look at the code, but I think compensation is based on your TO&E. Do you have your units assigned to the TO&E?

A campaign file would be handy.

**Comment by jslater89** [comment]
If this is 0.43.4, it includes the Campaign Ops rules for base payment when using the CamOps percent-of-TO&E rules. The base payment is based on peacetime operating costs, and is only calculated when peacetime operating costs are enabled.

That's my reading of the code, at least. @pheonixstorm would know better.
