### ISSUE TITLE
[RFE] Engage scenarios & complete enemy destruction

### ISSUE THREAD

**Issue by Tempest-56** [MegaMek/mekhq#4850]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

The Engage scenario type (and Engage - Heavy) has two or three objectives: 'Engage the following enemy unit(s) and force(s)', 'Preserve X% of the following unit(s) and force(s)', and possibly a liaison protection objectives. However it is possible to fail the scenario if you kill the opposition too fast - if you're to engage them for at least 10 turns but kill them all by turn 8, that's a failure despite that it should be an obvious success. This should probably be reflected in the objectives with a 'Destroy or rout X% of the following unit(s) and force(s)' that appear in other similar scenarios. 

### MekHQ Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by SuperStucco** [comment]
Perhaps a minor change in verbiage would work.  Instead of "... engage for at least X turns...", it may be better to indicate "... force the enemy to withdraw from the map, or engage them with weapon or physical attacks for at least X total rounds before retreating...".

**Comment by UlyssesSockdrawer** [comment]
Why would this be a scenario fail? If the enemy is totally destroyed before the minimum time, that's overperformance vs. the objective.

**Comment by Tempest-56** [comment]
> Why would this be a scenario fail?

Because you didn't engage for the specified number of turns. It's a technicality, but it's still a valid statement that if they're all dead before the minimum time you didn't complete the objective. 

> Perhaps a minor change in verbiage would work.

That would probably satisfy just fine. It's a minor issue but no harm in closing the loophole.

**Comment by IllianiCBT** [comment]
Closing as resolved
