### ISSUE TITLE
[0.50.1 Nightly - #CI1618] - Opening Reputation Report gives NPE

### ISSUE THREAD

**Issue by UlyssesSockdrawer** [MegaMek/mekhq#4851]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

Opening up the Reputation Report on the CI-1618 nightly with a save from 0.50 causes an NPE and the report does not open.

![image](https://github.com/user-attachments/assets/a308d189-6c65-4df8-9aa2-58e159021621)

I have not tried this with a freshly created campaign just in 0.50.01. This may be for @IllianiCBT 

### Steps to Reproduce

1. Import a save-game from 0.50.
2. Open up the save-game in the 0.50.1 nightly.
3. Navigate to the Command Centre
4. Click to open the Reputation Report
5. NPE occurs, report window does not open

### Operating System *

Windows 11

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

50.01 CI1618 Nightly

### Attach Files

[customs.zip](https://github.com/user-attachments/files/17041583/customs.zip)

[The Nova Dragoons30050716.cpnx.gz](https://github.com/user-attachments/files/17041586/The.Nova.Dragoons30050716.cpnx.gz)

Save file provided is from 0.50 to test importing. Don't worry about missing camos, logos, and portraits.

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by UlyssesSockdrawer** [comment]
Forgot to attach the log, whoops:

[mekhq.log](https://github.com/user-attachments/files/17044190/mekhq.log)

**Comment by IllianiCBT** [comment]
Closing as resolved
