### ISSUE TITLE
[0.50.01 #CI1618]: Importing campaign from 0.50 removes all awards from personnel

### ISSUE THREAD

**Issue by UlyssesSockdrawer** [MegaMek/mekhq#4852]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Importing a campaign from 0.50 into the 0.50.01 nightly removes all awards from personnel. The awards are still shown in the pilot's personal log. I suspect this may somehow be linked to the mekkening of names. May be one for @IllianiCBT 

Auto-awards continues to assign correctly after scenarios to mekwarriors.

0.50.01 screenshot:

![image](https://github.com/user-attachments/assets/0066f57e-4f0e-468a-83e2-df3a82021c10)

0.50 screenshot of same pilot:

![image](https://github.com/user-attachments/assets/691c1098-b739-4983-bcb9-e27964080230)

### Steps to Reproduce

1. Load provided save-game in 0.50 - check that awards are present.
2. Load provided save-game in 0.50.01 #CI1618 nightly
3. View personnel records - awards show in personal log but are missing from personnel

### Operating System *

Windows 11

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

50.01 CI1618 Nightly

### Attach Files

0.50 save with medals: [The Nova Dragoons30050716.cpnx.gz](https://github.com/user-attachments/files/17041758/The.Nova.Dragoons30050716.cpnx.gz)

[customs.zip](https://github.com/user-attachments/files/17041768/customs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by Tzahr** [comment]
This issue is not isolated to imported campaign saves. 
Rewards do not load at all from any savegame made in this build. 

This can very easily be tested by creating a new campaign, and using the default company generator, which will normally generate you with personnel that qualify for the Marksman award, and automatically promt you to do so. 
Confirm this, and make note of which personnel received the reward. Save the game, and reload it: the reward is no longer there, and running the eglibility dialogue re-awards it. 

So: rewards are failing to load correctly in general.

**Comment by IllianiCBT** [comment]
Closing as resolved
