### ISSUE TITLE
[RFE] Update AtB Excel to note it's lack of updates compared to the code

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#4855]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

Implementation of the AtB/Against the Bot rules has been modified, improved upon, and otherwise changed over the years while the original Excel document has not changed.  This leads to increasing numbers of questions about why MekHQ does this or that, while the document says otherwise.

It would help answer these questions right away if the AtB Excel document was modified to include some big, bold words (similar to the note for the Noble ruleset) that the contents are not being actively maintained, the current implementation may differ, and that the contents are retained for legacy purposes.

### MekHQ Suite Version *

v.050.0

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
I don't have easy access to excel, but if someone wants to do this and just send me the file I'll be happy to put in the PR so whomever doesn't have to set up a dev environment just for this

**Comment by UlyssesSockdrawer** [comment]
Is there a list of what is no longer current in the doc? I can go in and update this tomorrow after some in-office meetings & PR it in.

**Comment by IllianiCBT** [comment]
There isn't a list, but anything covered by the new documentation (in either docs/personnel modules or docs/AtB and StratCon) are definitely not longer working as written.

I'll be honest, as I've gone through this stuff, finding an AtB system that works as written has proven rarer than not.

**Comment by UlyssesSockdrawer** [comment]
This can probably be closed now if folks are happy with my annotated version of the doc.
