### ISSUE TITLE
[RFE] Enable ASF only (or mostly) campaigns

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4860]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

This request proposes the addition of an ASF only (or mostly) checkbox to campaign options. As complicated as this initially sounds, most of the features are already present, and most of the work would be turning certain things off if the checkbox is checked. Although there are many changes/additions that could be made to make ASF only/mostly campaigns more complete, in the interest of keeping the RFE narrow, it will focus exclusively on small tweaks that would take ASF campaigns from "Sort of possible, but you need to use GM mode every single day" to "possible".

If the checkbox is checked then...

- Allow formations of ASF to be assigned Scout/Defend/Fight/Train roles
- Disable certain scenarios from spawning. Notably, Duel, Capture, and the Legacy ATB scenarios
- Decrease the odds of the remaining ground scenarios spawning and/or increase the chance of the six already present space/low-atmo scenarios spawning.
- Allow meks to assigned as support forces using leadership the same way vees/ASF can currently.

To the best of my knowledge, everything else needed is already present. 

### MekHQ Suite Version *

50.00

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by RaozSpaz** [comment]
Ive pulled this off with a bit of messing with scenarios, but having it just be an option would be great.

**Comment by IllianiCBT** [comment]
The upcoming 50.02 introduces the concept of Combat Teams and removes the limitations previously placed on ASF forces. While StratCon is not designed with pure ASF campaigns, they can now be done.

Closing
