### ISSUE TITLE
Mech unable to be customized, will not load according to MekHQ's Meklab

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#4868]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Mech unable to be customized as it will not load

### Steps to Reproduce

Take the Lumberjack LM4/P into the 'meklab in mekhq and attempt to customize it

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Attach Files

![image](https://github.com/user-attachments/assets/1c9f3d7d-ed30-47b8-af87-19a94ac71af9)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by repligator** [comment]
Could you post the MHQ and MML logs? It might be helpful with trying to pin down the cause of the issue.

**Comment by repligator** [comment]
I was able to replicate the issue with a recent nightly.

`java.io.FileNotFoundException: data/mekfiles/customs/Shock Jock's Iron Shadows/Lumberjack LM4/P Mk II.mtf (No such file or directory)`

Looks likes the `/` in LM4/P isn't being escaped properly. It's looking for a Lumberjack LM4 directory to place the file P MK II.mtf inside. If such a directory exists it will actually write the mtf file to it as well.

[megamek.log](https://github.com/user-attachments/files/17091859/megamek.log)
[megameklab.log](https://github.com/user-attachments/files/17091860/megameklab.log)
[mekhq.log](https://github.com/user-attachments/files/17091861/mekhq.log)
[Shock Jock's Iron Shadows30260101.cpnx.gz](https://github.com/user-attachments/files/17091864/Shock.Jock.s.Iron.Shadows30260101.cpnx.gz)
