### ISSUE TITLE
[43.4] Used bombs don't get properly subtracted when resolving a scenario manually

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/mekhq#487]
I've been taking advantage of @Bonepart 's bomb loading change (thumbs up, works super, btw). However, it looks like you missed a spot, as illustrated here.

I've got a scenario that I needed to "Resolve Manually", and my fighters expended all their bombs in the process. However, when I do so, the bombs don't actually get subtracted from inventory.

[BombBug.zip](https://github.com/MegaMek/mekhq/files/1357249/BombBug.zip)

**Comment by Bonepart** [comment]
I can take a look at it when I get home from work.

Are you saying the bombs are not subtracted from the fighters inventory or the warehouse when you manually resolve?

**Comment by NickAragua** [comment]
The bombs stay in the fighter's inventory.

**Comment by Bonepart** [comment]
Gotcha. I'll look into it. Thanks for reporting it.

**Comment by Bonepart** [comment]
I don't think your mul file was generated correctly, or at least something did something odd with your fighters. When I remove the extra <bomb> tag that has the total bombs it processes just fine and removes the bombs from the fighters.


[SC2 - Finish - Goldenrod Menace B.zip](https://github.com/MegaMek/mekhq/files/1357659/SC2.-.Finish.-.Goldenrod.Menace.B.zip)

We might need to look into how you got that mul file. Do you resolve manually often? Is this the first time this has happened?

**Comment by Bonepart** [comment]
As an additional test I marked 2 bombs on each ASF as not having been dropped and HQ correctly showed them with 2 bombs left.

Whether you resolve manually or automatically it handles the bombs in the same place, when it calls clearGameData() for the entity as part of the resolveScenario() method of ResolveScenarioTracker.

**Comment by NickAragua** [comment]
This issue seems to have been fixed.
