### ISSUE TITLE
Getting Personnel Reports while away from Hiring Hall/Capital

### ISSUE THREAD

**Issue by Insert25c** [MegaMek/mekhq#4871]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

![image](https://github.com/user-attachments/assets/54e9fbe3-6d05-4ed1-8435-d27cfcebda3a)
![image](https://github.com/user-attachments/assets/4105cbd7-3e7d-49ec-8752-82df7ab94dd2)
![image](https://github.com/user-attachments/assets/cbd8727f-709e-4fbd-bf4a-0f8fce84b3dd)

When I arrived on Styk for a Cadre Contract, I started getting Personnel Market updates. This is in spite of the fact that my campaign options limit such things to hiring halls or capitals.

*included logs, save, and screenshots*

### Operating System *

Windows 10

### Java Version *

17.0.11

### MekHQ Suite Version *

v0.50.0

### Attach Files

![image](https://github.com/user-attachments/assets/befc4148-1a1e-479c-8ff1-b1b0cd2ab14f)
[logs.zip](https://github.com/user-attachments/files/17082470/logs.zip)
[Magnificent Bastards30520602.cpnx.gz.zip](https://github.com/user-attachments/files/17082497/Magnificent.Bastards30520602.cpnx.gz.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by Algebro7** [comment]
So Styk is being considered a faction capital in 3052, but shouldn't be until 3058. Currently looking into why the date filtering isn't working.

**Comment by IllianiCBT** [comment]
Closing as resolved
