### ISSUE TITLE
[RFE] Add Campaign Option to Disable ATB 'Special Scenarios'

### ISSUE THREAD

**Issue by UlyssesSockdrawer** [MegaMek/mekhq#4873]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

With StratCon now out of alpha and the recommended way to play a campaign in MHQ, the legacy ATB special scenarios can break the flow of play and feel out of place with the map-driven campaign.

This RFE is to implement a new campaign option on the ATB/StratCon page to enable or disable the ATB special scenarios from generating.

As some players may still enjoy these or prefer classic ATB, this should be an option rather than fully disabling them unless there's a big community push for them to go away.

### MekHQ Suite Version *

MHQ 0.50 -> Future

### Attach Files

N/A

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by cmpederson** [comment]
Those scenarios are the reason I started using the Atb campaign back before it was a part of megamek and while I understand not everyone likes them or uses them anymore, I do hope that they are still kept as an option.

**Comment by SuperStucco** [comment]
The special scenarios are hard coded, so along with the toggle it would be nice to have the generation system consolidated to the same XML templates as the standard scenario generation.  This would allow tweaking not just to generation parameters but selectively removing the least desired types while retaining the rest on a player-by-player basis.

Thought I had an RFE for that, but it's not jumping out in searches.

**Comment by IllianiCBT** [comment]
The current plan is to phase these scenarios out, as the opportunity arises.

Closing this request, but know that we hear you and we're actively working on a solution. :)
