### ISSUE TITLE
[RFE] Add Entrance Exam roll and TN to daily log or popup

### ISSUE THREAD

**Issue by KaiserFalk** [MegaMek/mekhq#4874]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

Add Entrance Exam roll and TN to daily log or popup

Currently when an entrance exam is successful there is no feed back. When it is failed a popup box informing about the failure is shown. I would like there to be text somewhere showing the exam's TN and the actual roll

### MekHQ Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
