### ISSUE TITLE
Harass scenario VPs & VIPs

### ISSUE THREAD

**Issue by Tempest-56** [MegaMek/mekhq#4877]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

In a Harass scenario (as generated by Stratcon), the primary objective ('Destroy x% of the following force(s)') is worth +1/-1 Scenario VPs and the secondary ('Preserve x% of the following force(s)') is a similar +1/-1. When a VIP protect is added into the mix ('Preserve 100% of the following force(s)') at +1/-1, it is no longer required to participate in the scenario. As the opfor will flee at top speed towards the far map edge, as long as you keep the VIP and at least half your units alive you are guaranteed positive scenario victory points without ever engaging the opfor or making any effort to complete the primary objective. (This is fairly unique to Harass, since in almost all other scenarios the opfor engages you.)

Upping the primary objective to a +2/-2 would resolve this. 

### Operating System *

Windows 11

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
