### ISSUE TITLE
[0.50.01 Nightly] Loading existing campaign causes clan_tech_knowledge error. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4890]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

When loading an older, existing campaign, it will display the following message directly prior to loading:

![image](https://github.com/user-attachments/assets/ac352a48-d9b5-4c96-baaa-6437618c0494)

The log shows variations of the following error: 

> 04:11:35,329 ERROR [mekhq.campaign.personnel.Person] {SwingWorker-pool-2-thread-1}
> mekhq.campaign.personnel.Person.generateInstanceFromXML(Person.java:2605) - Error restoring advantage: {}

This message will appear multiple times.
Clicking 'OK' through each of them will proceed with the campaign file loading fine. The affected Techs do not seem impacted.

This is highly like related to the removal of the Clan Tech Specialist SPA. 

### Steps to Reproduce

Load a campaign with Techs that have the Clan Tech SPA. 

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Nightly 0.50.01 - 621775698d20e6bb8b6ef8d55600a79af7d4593a

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17141791/mekhq.log)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Can you upload a campaign file that includes a character with the removed SPA. Will make testing easier.

**Comment by IllianiCBT** [comment]
Closing as resolved
