### ISSUE TITLE
[0.50.01 Nightly] Log error ref. campaign.parts.VeeStabiliser - Campaign import error

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4892]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

When loading in the campaign save, log shows variations of the following error: 

> 04:11:38,946 ERROR [mekhq.campaign.parts.Part] {SwingWorker-pool-2-thread-1}
> mekhq.campaign.parts.Part.generateInstanceFromXML(Part.java:769) - 
> java.lang.ClassNotFoundException: mekhq.campaign.parts.VeeStabiliser
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
> 	at java.base/java.lang.Class.forName0(Native Method)
> 	at java.base/java.lang.Class.forName(Class.java:421)
> 	at java.base/java.lang.Class.forName(Class.java:412)
> 	at mekhq.campaign.parts.Part.generateInstanceFromXML(Part.java:694)
> 	at mekhq.campaign.io.CampaignXmlParser.processPartNodes(CampaignXmlParser.java:1238)
> 	at mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:240)
> 	at mekhq.campaign.CampaignFactory.createCampaign(CampaignFactory.java:83)
> 	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:381)
> 	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:216)
> 	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:305)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
> 	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:342)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
> 	at java.base/java.lang.Thread.run(Thread.java:1583)

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Nightly 0.50.01 - 621775698d20e6bb8b6ef8d55600a79af7d4593a

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17141845/mekhq.log)
[1st Rimward Hussars.zip](https://github.com/user-attachments/files/17141849/1st.Rimward.Hussars.zip)
[customs.zip](https://github.com/user-attachments/files/17141851/customs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
From what I can tell `VeeStabiliser` is now `VeeStabilizer

**Comment by IllianiCBT** [comment]
Closing as resolved
