### ISSUE TITLE
[0.50.01 Nightly] New contract has no camo or placeholder colour for Allies or Enemies

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4895]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

When accepting a new contract on a new playthrough, enemy and allied forces generate without camouflage.
Before these would default to basic red/green colour. 
 
![image](https://github.com/user-attachments/assets/35ff4338-db0a-4ec4-af93-a5d2e1566bc8)

Attached "camo" folder is a custom camo folder used in an external custom unit folder, provided in case it was related.

### Steps to Reproduce

Can be reproduced easily by creating a new game, and accepting any contracy. 
Edit Mission under the Briefing Tab will show both camouflages as missing.

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Nightly 0.50.01 - 621775698d20e6bb8b6ef8d55600a79af7d4593a

### Attach Files

[camo.zip](https://github.com/user-attachments/files/17142394/camo.zip)
[mekhq.log](https://github.com/user-attachments/files/17142411/mekhq.log)
[Yakima Test Pilots.zip](https://github.com/user-attachments/files/17142413/Yakima.Test.Pilots.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
