### ISSUE TITLE
NPE with CO Contract Market - java.lang.NullPointerException: Cannot read field "employersMod" because "this.contractMods" is null

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/mekhq#4897]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

java.lang.NullPointerException: Cannot read field "employersMod" because "this.contractMods" is null
	at mekhq.campaign.market.contractMarket.CamOpsContractMarket.determineEmployer(CamOpsContractMarket.java:186)
	at mekhq.campaign.market.contractMarket.CamOpsContractMarket.generateContract(CamOpsContractMarket.java:141)
	at mekhq.campaign.market.contractMarket.CamOpsContractMarket.addAtBContract(CamOpsContractMarket.java:39)
	at mekhq.gui.dialog.ContractMarketDialog.lambda$initComponents$7(ContractMarketDialog.java:389)

### Steps to Reproduce

Flip on GM mode, head to the contract market and try to GM generate a contract. 

### Operating System *

Windows 11

### Java Version *

Java 17

### MekHQ Suite Version *

None

### Custom MekHQ Version

50.01 NIghtly -     MHQ Code Revision: bd9535fc6f3db9b6f7e95b85f6f80412cb21553b

### Attach Files

[megamek.log](https://github.com/user-attachments/files/17148332/megamek.log)
[megameklab.log](https://github.com/user-attachments/files/17148333/megameklab.log)
[mekhq.log](https://github.com/user-attachments/files/17148334/mekhq.log)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
