### ISSUE TITLE
[0.50.01 Nightly] MekTechs generate without portaits. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4898]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

When generating a new company, Mek Techs fail to generate with portaits. 
Log gives variations of the following error: 

> 16:19:11,319 WARN  [mekhq.campaign.personnel.generator.RandomPortraitGenerator] {AWT-EventQueue-0}
> mekhq.campaign.personnel.generator.RandomPortraitGenerator.generate(RandomPortraitGenerator.java:106) - Failed to generate portrait for Kupaalani McEachin. No possible portraits found.

Techs hired through personnel markets also fail to generate a portrait. 

### Steps to Reproduce

Can be reproduced on any save - start a new campaign, use the company generator.
Mek Techs will generate without portaits. 

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Nightly 0.50.01 - 621775698d20e6bb8b6ef8d55600a79af7d4593a

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17150151/mekhq.log)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
I'm fairly confident I know what's causing this, but I'll not likely get in a fix till tomorrow.

**Comment by IllianiCBT** [comment]
Closing as resolved
