### ISSUE TITLE
[0.50.01 Nightly] Repairs randomly stall and fail to progress until team is manually told to complete task. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4899]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

When conducting repairs on damaged components, an assigned team will at some points cease their assigned repair task. 
The damaged part will show the part as having an assigned team, but also show all unassigned teams.
![image](https://github.com/user-attachments/assets/eeaf16ae-6cdb-4e49-b8d1-9e32ad8da550)

Advancing day does not continue the repair, as expected, and the time scheduled does not decrease, leaving the team locked in limbo unless noticed.

Selecting a different team than the assigned one will show the following:
![image](https://github.com/user-attachments/assets/903b718b-a48a-4d25-ad1c-a568bc62685d)

The task can still be completed manually by finding the assigned team in the list, and manually telling them to Do Task, allowing for a workaround. 

### Steps to Reproduce

This can be semi-reliably reproduced by generating a lot of repair tasks. 
One way to do this is to generate a brand new game, and letting your maintenance cycles fail.
Tasking the repairs, you should eventually notice certain tasks that never get completed without manual input. 

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Nightly 0.50.01 - 621775698d20e6bb8b6ef8d55600a79af7d4593a

### Attach Files

[The Fragile Fighters30670209.cpnx.gz](https://github.com/user-attachments/files/17150797/The.Fragile.Fighters30670209.cpnx.gz)
[mekhq.log](https://github.com/user-attachments/files/17150803/mekhq.log)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
I've been unable to replicate this on the nightly. My gut is telling me this is related to the name change, so it is possible my other work to resolve those issues may have fixed this by accident.

Tentatively closing as resolved, but we should keep an eye out for this moving forward.
