### ISSUE TITLE
[0.50.01 Nightly] Large Vessel & Vehicle Crew personnel filters incorrectly omits pilots, gunners, and navigators.

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4900]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

When using the personnel filter to set Personnel Type to 'Large Vessel Crews', the filter shows only Vessel Crewmembers, incorrectly removing pilots, gunners, and navigators from the list. 

This is the crew complement of my Overlord: 
![image](https://github.com/user-attachments/assets/1c66983c-44a7-446d-b6d5-5c06ef13a83a)

And this is the personnel shown when filtering Large Vessel Crews: 
![image](https://github.com/user-attachments/assets/fb9ec69b-b955-41ca-abaa-b7e893ac7947)

This can be reproduced on a clean save as well. 

### Steps to Reproduce

Add a dropship to any campaign, and add minimum complement. 
Filter for Large Vessel Crews, and observe only Vessel Crewmembers listed. 

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Nightly 0.50.01 - 621775698d20e6bb8b6ef8d55600a79af7d4593a

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by PhoenixHeart512** [comment]
This also affects regular "vehicle Crews". I can only view my tank crews in "Combat Personnel" (or "all"), if I select "vehicle crews" in the dropdown the whole thing is blank.

Save file from my game can be found on issue https://github.com/MegaMek/mekhq/issues/4912

**Comment by IllianiCBT** [comment]
Closing as resolved

**Comment by PhoenixHeart512** [comment]
Was this change included in the mekHQ build from 9/30? I am on that build and this issue is still occurring, my "Vehicle Crews" window is still empty, and the "Large Vessel Crews" window only shows the ones listed as "crewmembers" and not pilots/gunners.

**Comment by IllianiCBT** [comment]
This has not yet been mergedSent from my iPhoneOn Sep 30, 2024, at 11:12 AM, Tzahr ***@***.***> wrote:﻿
It is still waiting to be merged as of current, didn't make it into yesterday's Nightly.
