### ISSUE TITLE
[0.50.01-SNAPSHOT] Non-Mek Techs Generate NPE When Right-Clicked

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/mekhq#4901]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

When moving a campaign from 0.50.0 to the 0.50.01 snapshot, I am unable to right-click on any non-mek techs, it generates an NPE.

Hiring new mechanics on the broken save DOES exhibit this issue.
Creating a new campaign and hiring new Mechanics does NOT exhibit this issue.

The attached zip file matches a standard mekHQ installation folder structure, so it can be unzipped on top of the root mekHQ folder and it SHOULD put everything where it needs to go automatically.

### Steps to Reproduce

Go to personnel tab and right-click on any Mechanic/AeroTech/BA tech, etc

### Operating System *

Windows 11

### Java Version *

Java Version: 17.0.6

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

mekhq.MekHQ.initializeLogging(MekHQ.java:306) - Starting MekHQ v0.50.1-SNAPSHOT     Build Date: 2024-09-26T01:26:30.916388034     Today: 2024-09-26     Origin Project: MekHQ     Java Vendor: Eclipse Adoptium     Java Version: 17.0.6     Platform: Windows 10 10.0 (amd64)     System Locale: en_US     Total memory available to MekHQ: 8 GB     MM Code Revision: d41eb83a27e1d0a31c430bb1749e242394c71d01     MML Code Revision: 1b955537a117a5f05d20287d29a2d4f13117b01d     MHQ Code Revision: 621775698d20e6bb8b6ef8d55600a79af7d4593a

### Attach Files

[CampaignTechNPE.zip](https://github.com/user-attachments/files/17151494/CampaignTechNPE.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by Tzahr** [comment]
Can confirm, NPE when right-clicking: 
- AeroTechs
- Mechanics
- Vessel Crewmembers
NOT AFFECTED: BA Techs and Mek Techs. 
Ref. attached save. 

Errors in log give: 

> 17:37:44,336 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
> mekhq.MekHQ.lambda$main$1(MekHQ.java:290) - Uncaught java.lang.NullPointerException detected. Please open up an issue containing all logs, the game save file, and customs at https://github.com/MegaMek/megamek/issues . If Sentry is enabled, the error has also been logged.
> java.lang.NullPointerException: Cannot invoke "megamek.common.options.IOption.getType()" because the return value of "mekhq.campaign.personnel.PersonnelOptions.getOption(String)" is null
> 	at mekhq.gui.adapter.PersonnelTableMouseAdapter.createPopupMenu(PersonnelTableMouseAdapter.java:2197)
> 	at mekhq.gui.adapter.JPopupMenuAdapter.maybeShowPopup(JPopupMenuAdapter.java:74)
> 	at mekhq.gui.adapter.JPopupMenuAdapter.mouseReleased(JPopupMenuAdapter.java:69)
> 	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
> 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
> 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
> 	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
> 	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
> 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
> 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
> 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
> 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
> 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

[mekhq.log](https://github.com/user-attachments/files/17151695/mekhq.log)
[1st Rimward Hussars.zip](https://github.com/user-attachments/files/17141849/1st.Rimward.Hussars.zip)
[customs.zip](https://github.com/user-attachments/files/17141851/customs.zip)

**Comment by IllianiCBT** [comment]
Closing as resolved
