### ISSUE TITLE
MHQ appears to be writing data to MMLog and MHQLog

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#491]
MHQ 0.43.4 version

The following appears in MMLog.txt
11:47:31,741 INFO [mekhq.campaign.universe.Faction] {SwingWorker-pool-2-thread-1} 
Starting load of faction data from XML...

See attached files...
[Logs.zip](https://github.com/MegaMek/mekhq/files/1366240/Logs.zip)

**Comment by scJazz2** [comment]
bumping appears to be related to other Packaging issues

**Comment by sixlettervariables** [comment]
I don't see this in 0.45.X.
