### ISSUE TITLE
[0.50.01-SNAPSHOT] SPA's with Mechwarrior skill requirements no longer have Mechwarrior skills as valid prereq's after mech/mek change

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/mekhq#4912]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

MekHQ appears to have lost all of it's Mechwarrior skill prereq's for SPA's (such as Veteran Mek/Piloting) after the Mech/Mek change. When viewing the SPA in the Campaign Options it shows the "Mek/Piloting" in the preview, but when you click Edit to actually adjust the prereq's, Mek/Piloting is unchecked and not selected.

Screenshots attached, along with a campaign save that can be used as well as the preset I am using.

![1](https://github.com/user-attachments/assets/0e0935bd-61f6-44c4-a281-28384601b830)
![2](https://github.com/user-attachments/assets/9925214c-95b4-44c5-a333-e941460cae12)
![3](https://github.com/user-attachments/assets/9de2ef5e-29b8-4a2a-9132-70b0db44fd5a)

### Steps to Reproduce

1. Open campaign settings
2. View SPA list
3. Observe issue

### Operating System *

Windows 11

### Java Version *

Java Version: 17.0.6

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

10:25:14,651 INFO  [mekhq.MekHQ] {main} mekhq.MekHQ.initializeLogging(MekHQ.java:306) - Starting MekHQ v0.50.1-SNAPSHOT     Build Date: 2024-09-26T01:26:30.916388034     Today: 2024-09-26     Origin Project: MekHQ     Java Vendor: Eclipse Adoptium     Java Version: 17.0.6     Platform: Windows 10 10.0 (amd64)     System Locale: en_US     Total memory available to MekHQ: 8 GB     MM Code Revision: d41eb83a27e1d0a31c430bb1749e242394c71d01     MML Code Revision: 1b955537a117a5f05d20287d29a2d4f13117b01d     MHQ Code Revision: 621775698d20e6bb8b6ef8d55600a79af7d4593a

### Attach Files

[SPAskillRequirements.zip](https://github.com/user-attachments/files/17155696/SPAskillRequirements.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by PhoenixHeart512** [comment]
Just checked and this also applies to Tech/Mek SPA's too.

**Comment by IllianiCBT** [comment]
Closing as resolved
