### ISSUE TITLE
[0.50.01-SNAPSHOT] Opfor still generating with abnormal skill spread

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/mekhq#4918]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

This clan opfor with contract skill level "Regular" generated a 1/4 pilot. Posting an issue so it can be looked into, in case this is not intended behavior per my discussion with @IllianiCBT.

### Steps to Reproduce

Load save and observe issue

### Operating System *

Windows 11

### Java Version *

Java Version: 17.0.6

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

megamek.MegaMek.initializeLogging(MegaMek.java:146) - Starting MegaMek v0.50.1-SNAPSHOT     Build Date: 2024-09-26T01:26:30.505226736     Today: 2024-09-26     Origin Project: MegaMekLab     Java Vendor: Eclipse Adoptium     Java Version: 17.0.6     Platform: Windows 10 10.0 (amd64)     System Locale: en_US     Total memory available to MegaMek: 8 GB     MM Code Revision: d41eb83a27e1d0a31c430bb1749e242394c71d01     MML Code Revision: 1b955537a117a5f05d20287d29a2d4f13117b01d     MHQ Code Revision: 621775698d20e6bb8b6ef8d55600a79af7d4593a

### Attach Files

[OpforSkillLevels.zip](https://github.com/user-attachments/files/17156890/OpforSkillLevels.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
