### ISSUE TITLE
[50.01 Nightly - CI1627] Importing Campaign from Pre-Mek Loses TO&E Icons - Conversion Needed

### ISSUE THREAD

**Issue by UlyssesSockdrawer** [MegaMek/mekhq#4920]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

Very minor conversion issue.

When importing a campaign from 0.50 to 0.50.01 with the mek changes, TO&E icons formerly with 'mech' in the name no longer load as their names are now mek. A converter should be added for these .png names to ensure backwards compatibility.

0.50:
![image](https://github.com/user-attachments/assets/d728f25c-b698-4c6c-860c-0f127641abb3)

0.50.01:
![image](https://github.com/user-attachments/assets/9ec4262a-71a5-42b3-938d-177651c08477)

N.B: when opening the campaign save, do not worry about missing portraits. My campaign uses custom portrait packs for some personnel.

### Steps to Reproduce

1. Load the attached save in 0.50 release - see that the TO&E has full icons.
2. Load the attached save in 0.50.01 latest nightly
3. View the TO&E - any mek related icons do not show on the TO&E elements

### Operating System *

Windows 11

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

50.01 CI1627 Nightly

### Attach Files

[The Nova Dragoons30060529.cpnx.gz](https://github.com/user-attachments/files/17166434/The.Nova.Dragoons30060529.cpnx.gz)

[customs.zip](https://github.com/user-attachments/files/17166436/customs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
