### ISSUE TITLE
MHQ doesn't respect \n in SPA hover-overs

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4921]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

In the code, the description for the forest ranger SPA is as follows
`Movement in woods or jungle costs 1 less MP.\nUsing walk/cruise MP while in woods/jungle gives +1 BTH when being attacked.\nAdditionally, you gain -1 to PSR checks in Jungle terrain.`

In MM it renders as follows:
Movement in woods or jungle costs 1 less MP.
Using walk/cruise MP while in woods/jungle gives +1 BTH when being attacked.
Additionally, you gain -1 to PSR checks in Jungle terrain.

Three separate lines.

In MHQ it renders as follows:
Movement in woods or jungle costs 1 less MP.Using walk/cruise MP while in woods/jungle gives +1 BTH when being attacked.Additionally, you gain -1 to PSR checks in Jungle terrain.

One single line, note the lack of space between the period and the next sentence.

### Steps to Reproduce

1. Hover over an SPA (for example Forest Ranger) in MM.
2. Hover over the same SPA in MHQ.

### Operating System *

Linux

### Java Version *

17

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

https://github.com/MegaMek/mekhq/commit/7779b817d1b00ec50c9dd1912913caed20774cd2

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
