### ISSUE TITLE
[RFE] Option to display multiple tracks in Stratcon

### ISSUE THREAD

**Issue by BlueThing00** [MegaMek/mekhq#4926]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

I have an ultrawide monitor.  This is the Stractcon campaign state window:
![image](https://github.com/user-attachments/assets/5f70902e-4e22-408a-b185-2ccef8a4374d)

Stratcon could easily display multiple tracks simultaneously, and that would be a better UX for me.  I'd either like the game to display multiple tracks next to each other, or to combine them into one large track (not sure which would be better/easier).

### MekHQ Suite Version *

0.50.0

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
While I understand the appeal this would require _substantial_ rebuilding of the StratCon tab and would obstruct some future plans we have, that we cannot currently discuss.

Closing, but keep an eye out for a future announcement some time next year. :)
