### ISSUE TITLE
Recon scenario - scan ASFs

### ISSUE THREAD

**Issue by Tempest-56** [MegaMek/mekhq#4927]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

When running a Recon scenario, it can roll an air support modifier. (In the attached save, it's Recon - Heavy with a BadIntelAir.xml modifier.) This includes the planes in the list of units that need to be scanned. This is probably an unintended interaction because it's very silly and likely impossible for a ground-based force to accomplish. 

### Operating System *

Windows 11

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Attach Files

[Alley Cats30121112.cpnx.gz](https://github.com/user-attachments/files/17172078/Alley.Cats30121112.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
