### ISSUE TITLE
[OPFOR GEN 3?] BA deploying into tornado

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4929]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Part of OPFOR Gen3 involves clan reinforcing with BA. They will still be used to reinforce even if they can not survive the battlefield conditions (for example Tornadoes). This or may not be related to OPFOR Gen 3, since their are existing issues with units deploying into conditions they can't survive.

### Operating System *

Linux

### Java Version *

Java 17

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

https://github.com/MegaMek/mekhq/commit/7779b817d1b00ec50c9dd1912913caed20774cd2

### Attach Files

[CBS302530250629.cpnx.gz](https://github.com/user-attachments/files/17175645/CBS302530250629.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
