### ISSUE TITLE
Personality module generating incorrect names

### ISSUE THREAD

**Issue by Tempest-56** [MegaMek/mekhq#4933]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

The bug shown [here](https://github.com/MegaMek/mekhq/issues/4681) is still in effect and applies to campaigns generated post 50.0. 

Opfor characters have consistent names in the briefing screen, in MegaMek, and in the Personnel screen after being taken prisoner. However, they are named incorrectly 100% of the time in the About section of the character card. Oddly, this does not apply to characters who were not named in the briefing screen/MegaMek, such as additional vehicle crew members or soldiers in an infantry platoon. Those generate with the correct name 100% of the time.

### Operating System *

Windows 11

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Attach Files

[Alley Cats30121117.cpnx.gz](https://github.com/user-attachments/files/17176027/Alley.Cats30121117.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
This should already be fixed in 50.01. Closing as resolved.
