### ISSUE TITLE
Duplicate portrait directories

### ISSUE THREAD

**Issue by Tempest-56** [MegaMek/mekhq#4942]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

Under the 50.01 snapshot for 9/27, there are several duplicate portrait directories.

Under the Female set, you've got Aerospace Tech, Aerospace Tek, and AeroTek, as well as duplicates with Mek Tek and MekTech. 
Under Male, there's Aerospace Tech and Aerospace Tek, as well as MekTek and MekTech. 

The three female aero directories do _NOT_ have identical contents, but the other three pairings do.

### Operating System *

Windows 11

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
