### ISSUE TITLE
[RFE] Promotion Factors for Retention & Turnover/Mutiny

### ISSUE THREAD

**Issue by SVNaas** [MegaMek/mekhq#4946]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

This suggestion proposes hooking up the existing promotion mechanics into the personnel systems Turnover & Retention mechanics, including the mutiny system. It feels beneficial to add a check on the turnover/retention and mutiny rolls that checks time in rank to apply an additional modifier to the rolls that determine if someone leaves the unit or is on the rebel side respectively.

The suggested modifiers are:
| Time in Rank | Roll Modifier |
| ------------- | ------------- |
| Under 3 Months | -2 |
| Under 6 Months | -1 |

Optional as would require extra work:
| Time in Rank | Roll Modifier |
| ------------- | ------------- |
| Prisoner with single promotion | +2 |

This would reflect their recruitment and feeling of being neglected.

### MekHQ Suite Version *

v 0.50.00

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
I have no interest in returning to the turnover system at this time, but this would make a great first PR for a new dev.

my only uncertainty is why we’re checking whether prisoners have been promoted. Is that a typo, or am I missing something?

**Comment by SVNaas** [comment]
Not a typo, it was an additional consideration I'd planned to mention and feeds into older plans from when AtB development was still community-supported via the BattleTech forum. It's marked optional due to the fact it'd need new system work with wider scope compared to the additions of time in rank to the rolls.

**Comment by IllianiCBT** [comment]
Yeah, I don’t think we should be tracking whether prisoners have been given promotions. They’re prisoners, after all. Bondsmen being an exception.

**Comment by SVNaas** [comment]
Fair but to clarify it was specifically for ex-prisoners, though that degree of micromanagement definitely isn't for everyone.

**Comment by IllianiCBT** [comment]
Ah, I didn’t spot that part. Yeah, then my vote (for what it’s worth) is against that implementation. If for no other reason than we’d have to add a bunch of extra tracking. And while I’m fine with bonuses being added for recent promotions I am firmly against any penalty that requires micromanage. Especially as the first time the player sees they’ve been hit with the malus is after it’s had an effect. We don’t have any way to communicate the issue to the player in a way that would not be awful for anyone with over a thousand personnel.

**Comment by UlyssesSockdrawer** [comment]
Closed by #5021
