### ISSUE TITLE
MASH Equipment not loading for some units

### ISSUE THREAD

**Issue by Tempest-56** [MegaMek/mekhq#4947]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Some units with MASH Equipment are not loading them properly: I noticed initially with the Carter MERV, but it also applies to most of the ground units (like the various MASH Trucks) but not any of the airborne (dropship/jumpship) units. Precise text is that at the bottom of the unit card it states:
`The following equipment slots failed to load: 
MASH Operation Theater`
And the equipment section of the card displays 
`MASH Equipment (0 theater)`

### Operating System *

Windows 11

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Attach Files

[Alley Cats30130511.cpnx.gz](https://github.com/user-attachments/files/17182475/Alley.Cats30130511.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by Tzahr** [comment]
Can confirm, still present in v0.50.1-SNAPSHOT - rev. a53044ee0763666eba74cdeaf511e150d291b1f0

**Comment by IllianiCBT** [comment]
I'm unable to replicate with the current nightly. Tentatively closing as resolved.
