### ISSUE TITLE
CamOPs Not identifying Techs properly

### ISSUE THREAD

**Issue by LaserEye32** [MegaMek/mekhq#495]
I have set up 4 techs, Aero&Mech&Mechanic&BA.
I have also Mass Trained all four techs to be masters of each of the Tech Fields.
CamOps now says that all 4 are MechTechs instead of identifying the job they are assigned and/or identifying the vehicle they are working on. Thus giving me a -5 Support.

This was set up on mekhq 0.43.4

[Bug Test- techs error30000101.zip](https://github.com/MegaMek/mekhq/files/1366930/Bug.Test-.techs.error30000101.zip)

**Comment by jslater89** [comment]
Thanks for the test case. PR497 fixes it.

**Comment by NickAragua** [comment]
Should be fixed with #497
