### ISSUE TITLE
[0.50.01-SNAPSHOT] Maternal leave ending as soon as it began. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4950]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

Personnel went on maternal leave (but did not give birth) and also returned on the same. 
Implies maternal leave is not working as intended. 

This report will be updated with other findings as they happen. 

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Nightly v0.50.1 - Rev. b5a4f6a63622f97b768c9dcb2124f544cc986ce8

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17183526/mekhq.log)
[1st Rimward Hussars MOTHER IS BACK.zip](https://github.com/user-attachments/files/17183529/1st.Rimward.Hussars.MOTHER.IS.BACK.zip)
[customs.zip](https://github.com/user-attachments/files/17183227/customs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
This _should_ be closed, as I did some work on this earlier in the dev cycle.

Closing as resolved.
