### ISSUE TITLE
[0.50.01-SNAPSHOT] AtB contract market generates contracts with very high base pay values. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4952]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

When generating contracts through the AtB Contract Marker, contracts generate with very high base pay values. This is more visible on more mature mercenary companies where the expected values are clearly inflated on the higher end. When comparing payouts of contracts generated in previous versions compared to contracts generated on current, we notice up to ten times increase in payout value. 

The base pay range seems quite broad, suggesting a faulty multiplier somewhere. 
It is hard to reliably detect in new companies, though batch creating contracts will result in some contracts generating with a much higher base pay that is expected (up to 20 - 40 million range). 

The workaround is to manually lower the base pay values (suggested divide by 10). 

### Steps to Reproduce

Generate new contracts with GM mode using the AtB contract markets, and monitor the expected profits and base pay values. 
If possible, compare newly generated contracts from a previous version with one from a current version. 

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Nightly v0.50.1 - Rev. b5a4f6a63622f97b768c9dcb2124f544cc986ce8

### Attach Files

[1st Rimward Hussars_NEW.zip](https://github.com/user-attachments/files/17195491/1st.Rimward.Hussars_NEW.zip)
[customs.zip](https://github.com/user-attachments/files/17195495/customs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by Thom293** [comment]
Screen from 50.00
![image](https://github.com/user-attachments/assets/08b6e20d-0637-4b93-97ec-7d09f61fe8e9)

Same Save, screen from 50.01
![image](https://github.com/user-attachments/assets/2e8b15e6-abc5-421d-85ef-3f40133665d9)


[ThomCustoms9.30.24.zip](https://github.com/user-attachments/files/17195622/ThomCustoms9.30.24.zip)
[Celcius 23330720728.cpnx.gz](https://github.com/user-attachments/files/17195624/Celcius.23330720728.cpnx.gz)

**Comment by UlyssesSockdrawer** [comment]
[The Nova Dragoons30060529.cpnx.gz](https://github.com/user-attachments/files/17195848/The.Nova.Dragoons30060529.cpnx.gz)
[customs.zip](https://github.com/user-attachments/files/17195851/customs.zip)

Save and customs are from the 0.50 release version.
