### ISSUE TITLE
[0.50.0 and on] Null Pointer Exception in TO&E when GM Removing COs

### ISSUE THREAD

**Issue by WeaverThree** [MegaMek/mekhq#4953]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

Removing a lance CO via GM Mode Remove Person and then clicking on its company's entry in the TO&E causes a null pointer exception.

This occurs on 0.50.0 and today's nightly. It does not occur on 0.49.19.1. 

Exception Text:

```12:39:34,320 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$1(MekHQ.java:294) - Uncaught Exception Detected
java.lang.NullPointerException: Cannot invoke "mekhq.campaign.personnel.Person.getFullTitle()" because the return value of "mekhq.campaign.Campaign.getPerson(java.util.UUID)" is null
```

### Steps to Reproduce

1. Create a new campaign. I used the full experience preset.
2. Run the company generator, default settings.
3. Look at the TO&E to see the CO of Baker Lance
4. Go to the personnel tab
5. GM Mode -> Remove the CO of Baker Lance
6. Go back to TO&E and click on Able Company

### Operating System *

Linux

### Java Version *

17.0.12

### MekHQ Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Ignore me, I can't read. Re-opening.

**Comment by IllianiCBT** [comment]
Unable to replicate on current nightly. Some work was done in this area, earlier in the dev-cycle, so I'm guessing we fixed it then.

Closing as resolved.
