### ISSUE TITLE
[0.50.0 and on] Kiddos can drop out of Daycare

### ISSUE THREAD

**Issue by WeaverThree** [MegaMek/mekhq#4955]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

Young children can drop out of Daycare-type education. This seems unrealistic.

They probably shouldn't be able to drop out of anything before age 10 or something, especially if homeschooled.

Found in 0.50.0 and tested in today's 0.50.1-nightly. Tried to replicate in MILESTONE but education doesn't seem to be a thing there?

### Steps to Reproduce

1. Start a new campaign
2. Bulk-hire personel in GM mode. Select 100+ dependents of age 0-1
3. Go to personnel and send them all to daycare
4. (Optional: run Company Generator so it doesn't complain as you advance time)
5. Advance time for several months until at least one of the brats drops out

### Operating System *

Linux

### Java Version *

17.0.12

### MekHQ Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by Thom293** [comment]
Yeah, I dropped out of Kindergarten.

Why?  

Because I dont play.

**Comment by WeaverThree** [comment]
They probably also shouldn't "barely graduate" from daycare. Graduation from daycare should possibly be handled differently in the text in general.

**Comment by RaozSpaz** [comment]
I mean I have seen some children that DayCares refuse to take care of XD If you use that logic then they 100% should be a possibility XD

**Comment by IllianiCBT** [comment]
Closing as resolved
