### ISSUE TITLE
[RFE] Award Ceremony UI does not include details of the award being granted

### ISSUE THREAD

**Issue by BlueThing00** [MegaMek/mekhq#4957]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

As seen here:
![image](https://github.com/user-attachments/assets/89069b63-567f-401f-a100-05fda5714cfb)

The award ceremony doesn't include the details of the award being granted.  I'd suggest two improvements:

1) A brief description of the award (perhaps even a short speech ala the Batchall work that is being done).

2) Details of the game mechanics of the award.  This could be either a tooltip over the name when hovered or (since there seems to be a separate ceremony for each award being given) a description in the area currently labeled "Instructions"

### MekHQ Suite Version *

0.50.0

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
I’m a little confused, so I assume I’m missing your point, but your screenshot shows that the award was issued for scoring 5 pilot kills in a mission. Was there something specific you were looking for other than that?

**Comment by WeaverThree** [comment]
Point 2 seems to be asking for a way to see the gameplay effects of the award (+2 edge or whatever) from this screen so you don't have to chase down a person and hover over the award in their info panel to find out. This is something I've wished for as well.

**Comment by BlueThing00** [comment]
Yeah, for point 1 I'm meaning that it would be nice to see some fluff text describing the award.  It's definitely a lower priority request.

For point 2, @WeaverThree is correct.  I'm asking to have a way to see the gameplay effects when it's being awarded.

**Comment by IllianiCBT** [comment]
I've addressed point 2 in: #5099

There are no plans to address point 1 at this time, though if you'd like you can open a separate RFE for that specific functionality.

Closing as resolved.
