### ISSUE TITLE
Possible Packaging issue for releases with MekHQ

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/mekhq#496]
See here - 

http://bg.battletech.com/forums/index.php?topic=58956.msg1355855#msg1355855

and

http://bg.battletech.com/forums/index.php?topic=58956.msg1357203#msg1357203

I've downloaded and test the releases and not had any issues, I also tested the windows release prior to uploading and it worked.

**Comment by scJazz2** [comment]
Just to add info to the issue.

Computer was rebooted, Java reinstalled, clean install tested. Nothing worked until overlaying the MM and MML packages. The only difference I could see was the major jump in the size of the .EXEs.

**Comment by dericpage** [comment]
What was the Java exception that occurred when running MegaMek.exe?  Was there anything in any of the log files?

**Comment by dericpage** [comment]
If you try launching from the command line, what do you get?

**Comment by scJazz2** [comment]
same

**Comment by BRDiger** [comment]
Just to confirm scJazz2: same problem here

**Comment by neoancient** [comment]
What version of Windows? What version of Java?

**Comment by BRDiger** [comment]
I was able to test it on 2 versions of Windows Pro(dualboot) 
Win 7 with Java 8 v. 144
Win 10 (1607) with Java 8 v. 131

**Comment by Question2** [comment]
The megameklab.exe in mekhq 43.4 is unusable, i tried launching it and it just kept saying "file not found". The .exe was extremely small compared to the one in the MML stand alone release.
