### ISSUE TITLE
[0.50.0] Infantry Created in Enviroments They Can't Survive

### ISSUE THREAD

**Issue by WeaverThree** [MegaMek/mekhq#4968]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Sometimes MekHQ generates infantry that cannot survive the weather condition on the map will be played on in MegaMek, and when you load into MegaMek they all have environment warnings on them.

I've included a save with a mission ready to launch that is in this condition. As far as I can recall I didn't reroll anything about the mission.

### Steps to Reproduce

1. Load provided save file
2. Navigate to briefing room and select pending scenario
3. Note force composition including infantry
4. Launch megamek with start game button
5. Note infantry with environment warnings

### Operating System *

Linux

### Java Version *

17.0.12

### MekHQ Suite Version *

v0.50.0

### Attach Files

mekhq.MekHQ.initializeLogging(MekHQ.java:315) - Starting MekHQ v0.50.0
    Build Date: 2024-09-01T14:30:44.398779200
    Today: 2024-10-02
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.12
    Platform: Linux 6.11.1-200.fsync.fc40.x86_64 (amd64)
    System Locale: en_US
    Total memory available to MekHQ: 8 GB
    MM Code Revision: ce95ba3d3c12c0e4e116cb713e47493316831daa
    MML Code Revision: 19b12fa9a622458ed00b0dc94ef1d0f2b19bbb66
    MHQ Code Revision: eaa1134aa318d26121a879c24651e16e84252b39

I don't have any other relevant logs but here is the save game and associated customs directory.

[0.50.0 Infantry Danger.zip](https://github.com/user-attachments/files/17236397/0.50.0.Infantry.Danger.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
I've been unable to replicate this using the new scenario templates. Closing as resolved.
