### ISSUE TITLE
[0.50.01 Nightly] Spouses/children joining generated personnel are inverted in Log report announcing their relation.

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4972]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

When new personnel is generated, they have a chance to be joined by a spouse and/or children. When this occurs, the activity log message displays them the wrong way around. 

![image](https://github.com/user-attachments/assets/0804a084-0d63-4a41-b691-880282eac588)
![image](https://github.com/user-attachments/assets/0bf294ab-8d62-44d8-9bfa-000028b55149)

### Steps to Reproduce

Create new save, generate new company.
Monitor personnel log for children or spouses. Note that message inverts relatives.

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Nightly v0.50.1-SNAPSHOT - Rev. 7eb17ed577293cf4fe52daeba4b0e9bf3223f902

### Attach Files

[ExampleCampaign.zip](https://github.com/user-attachments/files/17247024/ExampleCampaign.zip)
[mekhq.log](https://github.com/user-attachments/files/17247029/mekhq.log)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
This is my favorite bug of this dev cycle

**Comment by IllianiCBT** [comment]
Closing as resolved
