### ISSUE TITLE
[0.50.01 Nightly] Allison MekWarrior Institute causes Null Exception on campaign load due to name change. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4973]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

When loading a campaign that includes personnel currently attending the Allison MechWarrior Institute, the campaign will fail to load because the academy in question has been re-named to the Allison MekWarrior Institute. 

This can be worked-around by editing either the Prestigious Academies.xml, or save-editing the campaign save and manually renaming the institute on the relevant personnel entries.  

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Nightly v0.50.1-SNAPSHOT - Rev. 7eb17ed577293cf4fe52daeba4b0e9bf3223f902

### Attach Files

[1st Rimward HussarsPostTest.zip](https://github.com/user-attachments/files/17247367/1st.Rimward.HussarsPostTest.zip)
[mekhq.log](https://github.com/user-attachments/files/17247369/mekhq.log)
[customs.zip](https://github.com/user-attachments/files/17247375/customs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
