### ISSUE TITLE
[0.50.01 Nightly] FG3 generated OPFOR matched to my entire force. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4976]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

A randomly occuring Low-Atmohsphere Air Intercept mission generated with an OPFOR of 109555 BV, matched to my entire force. 

![image](https://github.com/user-attachments/assets/8a697184-37d1-4197-a9a4-345100c936ac)
![image](https://github.com/user-attachments/assets/5551e693-20c7-4d24-bb12-3d43ce7100db)
![image](https://github.com/user-attachments/assets/c7a50032-64aa-483d-bca4-b00d8275f823)

Log gave the following at the time.

> 03:38:22,481 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
> mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForce(AtBDynamicScenarioFactory.java:749) - Generated a force with 135974 / 122954  Generic BV
> 
> 03:38:22,482 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
> mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForce(AtBDynamicScenarioFactory.java:772) - Final force 135974 / 153692  Generic BV

It appears ForceGen actually worked entirely correctly, though we may wish for it not to pick the top-most level force to match itself to. 

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Nightly v0.50.1-SNAPSHOT - Rev. 7eb17ed577293cf4fe52daeba4b0e9bf3223f902

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17252124/mekhq.log)
[1st Rimward Hussars_AirSuperiorty.zip](https://github.com/user-attachments/files/17252125/1st.Rimward.Hussars_AirSuperiorty.zip)
[customs.zip](https://github.com/user-attachments/files/17247375/customs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by Tzahr** [comment]
I have found a likely culprit for this anomaly. 
During a mission directly prior, one of my pilots crashed his Lightning. I replace the Lightning, which was automatically added to the top-level force, resulting in my TOE looking like this at the moment the mission was generated: 

![image](https://github.com/user-attachments/assets/066e2320-c355-4bc5-b781-f420e5face88)

It likely matched itself to the PO Bereket's Lightning, assuming the regimental container was at unit-level, and incoporated every child force contained within. 

This could potentially be prevented by limiting the matching logic from picking out forces with massive amount of nested units, but this might easily be chalked up to what is essentially a confluence of events conspring to set-up circumstances that allowed this to happen, including my own forgetfulness at not immediately reassigning the hapless pilot (who seems to have called down the wrath of the Blakist airforce all on his own).

**Comment by IllianiCBT** [comment]
So, right now, it’s working the same as in 50.0 - when reading the TOE. I have everything set up to fix this to start using the new TOE Reader, but that’s locked behind the Campaign Options IIC roadblock

**Comment by IllianiCBT** [comment]
Closing as resolved
