### ISSUE TITLE
[RFE] Standardize Challange Estimate To Use Half To Five Scale

### ISSUE THREAD

**Issue by WeaverThree** [MegaMek/mekhq#4979]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

Replace the red-star/green-star two-way grading system with one that goes <half icon> <whole icon> <one and a half icons> and so on up to <five icons>.

This solves several problems:

- It will look basically like how other battletech-related games all do it (though they use skulls generally)
- Because it looks how MANY other systems work in the world, people won't have to learn the system nor will instructions have to be provided for reading it
- It won't cause problems for red/green colorblind people

It may be better to use a symmetrical icon for this purpose, but I'm not sure what that should be.

If we still want to use color, we could

- Have each star progressively go from green to red in the line

or

- Have the line of stars be a color from green to red depending on the total value

(Posted on behalf of Atma at request of Illiani

### MekHQ Suite Version *

v0.50.1-SNAPSHOT: 2024-10-02

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
