### ISSUE TITLE
[0.50.01 Nightly] Newborn origins mismatching reality, issued foreign citizenship. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4980]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

When a new child is born, their origins mismatch expected reality, seemingly receiving random origins appropriate to the settings. 

In given example, little Seira is born on New Hope to a Mercenary faction. She is however promptly issued a Marik-Stewart Commonwealth passport that claims she was born a world away on Stewart. 

This replicates with other newborns, all receiving origins that seems to match my Random Origin settings. 

![image](https://github.com/user-attachments/assets/732f8c82-46cc-458d-93ff-5bc6031a972f)
![image](https://github.com/user-attachments/assets/8cbc3cc1-bb01-4df1-a618-03a7d943400a)
![image](https://github.com/user-attachments/assets/c08097ab-5895-4218-8d22-3f801f991a8c)

This replicates with other newborns, all receiving origins that seems to match my Random Origin settings. 

![image](https://github.com/user-attachments/assets/97505879-8051-4cb6-bfec-42ae6d2737c6)

Note: I actually think the idea of being issued citizenship on a given planet is pretty interesting, but that might best be tackled elsewhere. 

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Nightly v0.50.1-SNAPSHOT - Rev. 7eb17ed577293cf4fe52daeba4b0e9bf3223f902

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17253322/mekhq.log)
[1st Rimward HussarsOddKidOut.zip](https://github.com/user-attachments/files/17253326/1st.Rimward.HussarsOddKidOut.zip)
[customs.zip](https://github.com/user-attachments/files/17247375/customs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Can I verify whether this issue occurs if Randomize Origin for Dependents is disabled?

**Comment by Tzahr** [comment]
It does not occur when it is disabled.

**Comment by IllianiCBT** [comment]
Perfect. That gives me all the lead I needed to track this down.

**Comment by IllianiCBT** [comment]
Closed as resolved
