### ISSUE TITLE
[0.50.01 Nightly] NPE on selecting contract in Contract Market. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4983]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Simple enough: when selecting a contract in the contract market, an NPE occurs.

Note however that this campaign in forced into a very artifical state. It is 2445, I have no active forces, and the majority of my personnel is in education. This is likely an edge case, which is why I have lowered the the severity. 

Log throws this error: 

> 09:01:10,858 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
> mekhq.MekHQ.lambda$main$1(MekHQ.java:290) - Uncaught java.lang.ArithmeticException detected. Please open up an issue containing all logs, the game save file, and customs at https://github.com/MegaMek/megamek/issues . If Sentry is enabled, the error has also been logged.
> java.lang.ArithmeticException: / by zero
> 	at mekhq.campaign.mission.AtBContract.getAverageBattleValue(AtBContract.java:1921)
> 	at mekhq.campaign.mission.AtBContract.calculateContractDifficulty(AtBContract.java:1770)
> 	at mekhq.campaign.mission.AtBContract.getContractDifficultyStars(AtBContract.java:1723)
> 	at mekhq.gui.view.ContractSummaryPanel.fillStats(ContractSummaryPanel.java:168)
> 	at mekhq.gui.view.ContractSummaryPanel.initComponents(ContractSummaryPanel.java:103)
> 	at mekhq.gui.view.ContractSummaryPanel.<init>(ContractSummaryPanel.java:91)
> 	at mekhq.gui.dialog.ContractMarketDialog.refreshContractView(ContractMarketDialog.java:613)
> 	at mekhq.gui.dialog.ContractMarketDialog.contractChanged(ContractMarketDialog.java:600)
> 	at mekhq.gui.dialog.ContractMarketDialog.lambda$initComponents$4(ContractMarketDialog.java:282)
> 	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:231)
> 	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:193)
> 	at java.desktop/javax.swing.DefaultListSelectionModel.setValueIsAdjusting(DefaultListSelectionModel.java:771)
> 	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.setValueIsAdjusting(BasicTableUI.java:983)
> 	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleased(BasicTableUI.java:1196)
> 	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
> 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
> 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
> 	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
> 	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
> 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
> 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
> 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
> 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
> 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
> 	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
> 	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
> 	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
> 	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
> 	at java.desktop/java.awt.Dialog.show(Dialog.java:1079)
> 	at java.desktop/java.awt.Component.show(Component.java:1728)
> 	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
> 	at java.desktop/java.awt.Window.setVisible(Window.java:1036)
> 	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1015)
> 	at mekhq.gui.CampaignGUI.showContractMarket(CampaignGUI.java:1329)
> 	at mekhq.gui.CampaignGUI.lambda$initMenu$30(CampaignGUI.java:715)
> 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
> 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
> 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
> 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
> 	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
> 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1029)
> 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1073)
> 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
> 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
> 	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
> 	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
> 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
> 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
> 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
> 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
> 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
> 

### Steps to Reproduce

Open the attached savefile, navigate to the contract market, and select the contracts. It should give an NPE on 2/3 contracts already generated. 

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Nightly v0.50.1-SNAPSHOT - Rev. 7eb17ed577293cf4fe52daeba4b0e9bf3223f902

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17254601/mekhq.log)
[Yakima Test Pilots_BrokenContracts.zip](https://github.com/user-attachments/files/17254613/Yakima.Test.Pilots_BrokenContracts.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
This is an error from the challenge estimate code, I suspect I didn't tell it what to do if the player's force has an estimated power of 0. I have another RFE related to challenge estimates, so I'll tackle this when I get to that.

**Comment by Tzahr** [comment]
Another incident of this, this time on my main save. 
It's the Stone's Coaltion vs. Marik-Stewart Commonwealth one.


Log error gives: 
> 06:11:05,804 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
> mekhq.MekHQ.lambda$main$1(MekHQ.java:290) - Uncaught java.lang.ArithmeticException detected. Please open up an issue containing all logs, the game save file, and customs at https://github.com/MegaMek/megamek/issues . If Sentry is enabled, the error has also been logged.
> java.lang.ArithmeticException: / by zero
> 	at mekhq.campaign.mission.AtBContract.getAverageBattleValue(AtBContract.java:1921)
> 	at mekhq.campaign.mission.AtBContract.calculateContractDifficulty(AtBContract.java:1770)
> 	at mekhq.campaign.mission.AtBContract.getContractDifficultyStars(AtBContract.java:1723)
> 	at mekhq.gui.view.ContractSummaryPanel.fillStats(ContractSummaryPanel.java:168)
> 	at mekhq.gui.view.ContractSummaryPanel.initComponents(ContractSummaryPanel.java:103)
> 	at mekhq.gui.view.ContractSummaryPanel.<init>(ContractSummaryPanel.java:91)
> 	at mekhq.gui.dialog.ContractMarketDialog.refreshContractView(ContractMarketDialog.java:613)
> 	at mekhq.gui.dialog.ContractMarketDialog.contractChanged(ContractMarketDialog.java:600)
> 	at mekhq.gui.dialog.ContractMarketDialog.lambda$initComponents$4(ContractMarketDialog.java:282)
> 	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:231)
> 	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:193)
> 	at java.desktop/javax.swing.DefaultListSelectionModel.setValueIsAdjusting(DefaultListSelectionModel.java:771)
> 	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.setValueIsAdjusting(BasicTableUI.java:983)
> 	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleased(BasicTableUI.java:1196)
> 	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
> 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
> 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
> 	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
> 	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
> 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
> 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
> 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
> 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
> 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
> 	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
> 	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
> 	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
> 	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
> 	at java.desktop/java.awt.Dialog.show(Dialog.java:1079)
> 	at java.desktop/java.awt.Component.show(Component.java:1728)
> 	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
> 	at java.desktop/java.awt.Window.setVisible(Window.java:1036)
> 	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1015)
> 	at mekhq.gui.CampaignGUI.showContractMarket(CampaignGUI.java:1329)
> 	at mekhq.gui.ReportHyperlinkListener.hyperlinkUpdate(ReportHyperlinkListener.java:105)
> 	at java.desktop/javax.swing.JEditorPane.fireHyperlinkUpdate(JEditorPane.java:402)
> 	at java.desktop/javax.swing.text.html.HTMLEditorKit$LinkController.activateLink(HTMLEditorKit.java:955)
> 	at java.desktop/javax.swing.text.html.HTMLEditorKit$LinkController.mouseClicked(HTMLEditorKit.java:756)
> 	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
> 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6624)
> 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
> 	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
> 	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
> 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
> 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
> 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4584)
> 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
> 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)


[1st Rimward HussarsCont.zip](https://github.com/user-attachments/files/17265124/1st.Rimward.HussarsCont.zip)
[customs.zip](https://github.com/user-attachments/files/17265126/customs.zip)
[mekhq.log](https://github.com/user-attachments/files/17265120/mekhq.log)

**Comment by Tzahr** [comment]
I accidentally closed this with my fat fingers while writing the above.

**Comment by IllianiCBT** [comment]
Tentatively closing this as resolved
