### ISSUE TITLE
[RFE] Personnel Market Report Message Should Mention When More Than One Available

### ISSUE THREAD

**Issue by WeaverThree** [MegaMek/mekhq#4986]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

If there are more than one people available on the personnel market, currently they go hidden by this feature. Ideally it would show:

Personnel market updated:
**5 people** are available.

Or similar when there is more than one.

### MekHQ Suite Version *

v0.50.1-SNAPSHOT: 2024-10-04

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by WeaverThree** [comment]
It turns out the issue here is actually that paid recruitment is available when camops markets are selected, it shouldn't be.

**Comment by IllianiCBT** [comment]
Closing: non-issue
