### ISSUE TITLE
NPE when trying to select show all factions in GM contract creation

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4987]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

While testing another issue, I tried to create a garrison contract on Misery, the employers being the DC, with the intended OPFOR being MERC.WD. When trying to select Show All Factions, an NPE was triggered.

### Steps to Reproduce

1. Add Mission
2. New Contract
3. Check Show All Factions

### Operating System *

Linux

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Custom MekHQ Version

50.1 Snapshot (custom version due to trying to triage a different bug, but it's fairly recent, has the red star contract difficutly ratings merge)

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17266583/mekhq.log)
[Tiny Tom's Tiny Pies30280101.cpnx.gz](https://github.com/user-attachments/files/17266584/Tiny.Tom.s.Tiny.Pies30280101.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
