### ISSUE TITLE
Erroneous lack-of-funds-for-next-jump nag

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4988]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

While stationed on a planet, I received a message that I lacked funds for the next jump. I don't have any jumps planned. I'm one year into a two year contract.
Note that I used a good deal of GM tools both to create the contract and to teleport to the planet, this may be part of the cause of the issue.

### Steps to Reproduce

1. Load save.
2. Hit advance day.

### Operating System *

Linux

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Custom MekHQ Version

50.1 Snapshot (custom version due to trying to triage a different bug, but it's fairly recent, has the red star contract difficutly ratings merge)

### Attach Files

[Tiny Tom's Tiny Pies30290302.cpnx.gz](https://github.com/user-attachments/files/17266638/Tiny.Tom.s.Tiny.Pies30290302.cpnx.gz)
[mekhq.log](https://github.com/user-attachments/files/17266640/mekhq.log)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by WeaverThree** [comment]
This also happens if you are low enough on money when transiting into the final system of a jump path but not yet on the planet. Probably the exact same thing causing the problem.
