### ISSUE TITLE
[0.50.01-SNAPSHOT] Daily activity report occasionally generates again after processing awards, omitting some information. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4998]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

Occasionally, when a new month is started, the AutoAward system will prompt issuing a set of new reports. Doing so will cause the daily activity log to regenerate, while moving the original entry to the historic log. The new entry will not display all the information provided in the first. 

![image](https://github.com/user-attachments/assets/62386ce8-a6a1-4662-933c-027a137b6fcf)

I have attached two savegames - ones is the day on which this occurred, and the other is an autosave directly prior. 
This can be duplicated by loading the autosave, advancing a day, and processing the AutoAwards that pop up. 

### Steps to Reproduce

1. Load provided autosave.
2. Advance day. 
3. Process AutoAward prompt. 
4. Compare current Daily Activity Log to the historic one. One should appear with an identitical date. 

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Nightly v0.50.1-SNAPSHOT - Rev. 036d7bea06aa05b4e65424baa02bf8b67d5c78f3

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17272064/mekhq.log)
[1st Rimward HussarsCont.zip](https://github.com/user-attachments/files/17272073/1st.Rimward.HussarsCont.zip)
[Autosave-1-1st Rimward Hussars-30801130.cpnx.gz](https://github.com/user-attachments/files/17272074/Autosave-1-1st.Rimward.Hussars-30801130.cpnx.gz)
[customs.zip](https://github.com/user-attachments/files/17272079/customs.zip)

NOTE: the Allison MekWarrior Academy error might appear when attempting to load file. This can be avoided by renaming the Allison MekWarrior Academy in the Prestigious Academy XML to Allison MechWarrior Academy, or editing the saves to do the inverse for the students attending it under the personnel headings. 

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
