### ISSUE TITLE
Fatigue in list view does not agree with fatigue on pilot UI

### ISSUE THREAD

**Issue by BlueThing00** [MegaMek/mekhq#4999]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

![image](https://github.com/user-attachments/assets/3be1dadf-dd9c-408d-b325-641da7f1197a)

The fatigue in the list view is 5.

The fatigue in the pilot UI is 2.

This appears to be one displaying base fatigue and the other displaying effective fatigue.

### Steps to Reproduce

Play a campaign with fatigue enabled.

Look at the UI after one or more Scenarios have been completed.

### Operating System *

Windows 11

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by BlueThing00** [comment]
If those are meant to be different, they should have different names (e.g. "Fatigue" and "Effective Fatigue").  

Plus, Since the effective fatigue seems to be the one that really matters (if I'm understanding the fatigue rules properly), it should be available in a list view somewhere.

**Comment by IllianiCBT** [comment]
Yeah, I must have just called fatigue instead of effective fatigue when writing the code for that part of the table. Easily fixed.

**Comment by IllianiCBT** [comment]
Closing as resolved
