### ISSUE TITLE
No new line between dates when using Advance Multiple Days

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/mekhq#50]
Instead of having dates on a new line they are jumbled together.

> Tuesday, April 26 3025Wednesday, April 27 3025Thursday, April 28 3025Friday, April 29 3025Saturday, April 30 3025

**Comment by pheonixstorm** [comment]
Here is a full 7 day log with most days having something.

![advday](https://cloud.githubusercontent.com/assets/1787879/14515168/232cdd24-01c5-11e6-815c-f81725976400.png)

**Comment by Akjosch** [comment]
And done. :)
