### ISSUE TITLE
[0.50.01-SNAPSHOT] Whitespace issues in About section for personnel. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#5003]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

The 'About' section for personnel has whitespace issues. Most notably what appears like a full line at the start, and then occasionally also midway through the text body.

![image](https://github.com/user-attachments/assets/1ad96d5c-027c-478f-ae64-2a69ef9f25b5)

### Steps to Reproduce

This should reproduce on a new campaign. 

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Nightly v0.50.1-SNAPSHOT - Rev. 976204bfa54b995b2d45159b080d13dba8a16ee5

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17286136/mekhq.log)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
