### ISSUE TITLE
[0.50.01-SNAPSHOT] DropShip Raid scenario generates fleet of DropShips instead of single target. 

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#5005]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

The naturally ocurring DropShip Raid scenario type seems to generate with an excess amount of enemy DropShips, rather than the expected single craft. 

![image](https://github.com/user-attachments/assets/207ed11b-32d7-4768-a0d1-cd4f69f15d9f)
This was matched to a single Lance of mine, the full scenario layout available in the save below. 

Regenerating the bot forces did not fix the issue, but merely generated another set of about a half-dozen DropShips. 

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Nightly v0.50.1-SNAPSHOT - Rev. 976204bfa54b995b2d45159b080d13dba8a16ee5

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17286488/mekhq.log)
[1st Rimward HussarsDropShipBoogaloo.zip](https://github.com/user-attachments/files/17286489/1st.Rimward.HussarsDropShipBoogaloo.zip)
[customs.zip](https://github.com/user-attachments/files/17286490/customs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
I suspect it’s using the wrong generation method. It should be using fixed unit count, not FG3

**Comment by IllianiCBT** [comment]
Closing as resolved
