### ISSUE TITLE
[0.50.01-2024-10-05] Paid Recruitment option not saving/loading properly

### ISSUE THREAD

**Issue by WeaverThree** [MegaMek/mekhq#5006]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

When loading a save file on a fresh MekHQ, paid recruitment is ~~never turned on.~~ **set to whatever it was set to last time you were running MekHQ.**
When loading a save file on a running MekHQ, paid recruitment is not changed at all.

I've provided two files, WITH RECRUIT.cpnx that contains
```
		<paidRecruitment>true</paidRecruitment>
		<paidRecruitType>MEKWARRIOR</paidRecruitType>
```

And WITHOUT RECRUIT.cpnx which only contains

```
		<paidRecruitType>MEKWARRIOR</paidRecruitType>
```

In the same place.

This is a small, brand new save that has no dependencies, but I found the same issue on larger, active game saves.

### Steps to Reproduce

1. Start MekHQ and load WITHOUT RECRUIT.
2. Open personnel market and observe that paid recruitment is turned off.
3. Close MekHQ.
4. Start MekHQ and load WITH RECRUIT.
5. Open personnel market and observe that paid recrutiment is turned off here too.
6. Close MekHQ.
7. Start MekHQ and load WITH RECRUIT again.
8. Open personel market and turn paid recruitment ON.
9. Open WITHOUT RECRUIT without closing MekHQ.
10. Open personnel market and observe that paid recruitment is still on.

It looks like the above will only work if Paid Recruitment was already off in your install, because.

1. Start MekHQ and load WITHOUT RECRUIT.
2. Open personnel market and observe status of paid recruitment.
3. Turn it off if its on.
4. Close MekHQ.
5. Start MekHQ and load WITHOUT RECRUIT.
6. Open personnel market and observe that paid recruitment is now off.
7. Turn it on.
8. Close MekHQ.
9. Start MekHQ and load WITHOUT RECRUIT.
10. Open personnel markte and observe that paid recruitment is now on.

### Operating System *

Linux

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

v0.50.01-SNAPSHOT 2024-10-05

### Attach Files

mekhq.MekHQ.initializeLogging(MekHQ.java:306) - Starting MekHQ v0.50.1-SNAPSHOT
    Build Date: 2024-10-06T03:25:24.214306127
    Today: 2024-10-08
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.12
    Platform: Linux 6.11.2-202.fsync.fc40.x86_64 (amd64)
    System Locale: en_US
    Total memory available to MekHQ: 8 GB
    MM Code Revision: 82fc89ceba5bfdb40670ba90bdc3e3ca1027a07b
    MML Code Revision: 446bd8d9c7e28bfdf49d35f312d838c44e16941a
    MHQ Code Revision: 976204bfa54b995b2d45159b080d13dba8a16ee5

Save Files: [Paid Recruitment Test.zip](https://github.com/user-attachments/files/17296521/Paid.Recruitment.Test.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by WeaverThree** [comment]
After posting I discovered that the option seems to be getting saved in the install environment somewhere, because it's sensitive to what it was set to last time you were running the program. Post updated.

**Comment by IllianiCBT** [comment]
Closing as resolved

In case you weren't aware: if you include `Closes #prNumber` somewhere in your PR description it will automatically close the linked issue report when the PR gets merged.

**Comment by WeaverThree** [comment]
Oh that's the magic word. Thank you!
