### ISSUE TITLE
[0.50.01-SNAPSHOT] PrimaryAlliesGround.xml modifier occurring even after opfor bids down to match player BV

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/mekhq#5008]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

The stratcon modifier "PrimaryAlliesGround.xml: To compensate for the presence of a large opposing force, allied units will be working alongside us on this operation." is occurring even after the clan opfor bid down (or BV-matched) the player's force, resulting in extra allies that are no longer needed.

Issue observed in both of the pending scenarios in the attached save.

Unfortunately, mekHQ was closed and reloaded several times after the scenarios were generated so the mekHQ log is empty and will not be included.

### Steps to Reproduce

Issue occurs as part of scenario generation in stratcon

### Operating System *

Windows 11

### Java Version *

Java Version: 17.0.6

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

mekhq.MekHQ.initializeLogging(MekHQ.java:306) - Starting MekHQ v0.50.1-SNAPSHOT     Build Date: 2024-10-04T03:22:42.858455457     Today: 2024-10-08     Origin Project: MekHQ     Java Vendor: Eclipse Adoptium     Java Version: 17.0.6     Platform: Windows 10 10.0 (amd64)     System Locale: en_US     Total memory available to MekHQ: 8 GB     MM Code Revision: e1d2728d2a51e221c92f9f8d1855e899303a4386     MML Code Revision: 446bd8d9c7e28bfdf49d35f312d838c44e16941a     MHQ Code Revision: 036d7bea06aa05b4e65424baa02bf8b67d5c78f3

### Attach Files

[PrimaryAlliesModifier.zip](https://github.com/user-attachments/files/17298478/PrimaryAlliesModifier.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
