### ISSUE TITLE
[RFE] Add logging in MekHQ showing the target BV during opfor generation

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/mekhq#5009]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

Per discussions with Illiani, we would like to add logging to mekHQ to have it show what the target BV is when generating an opfor, so that we can see if the resulting forces are within expected values.

### MekHQ Suite Version *

0.50.01-SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
