### ISSUE TITLE
[0.50.01 - Latest Dev Pull] java.lang.ArithmeticException - divide by zero when clicking on contracts

### ISSUE THREAD

**Issue by UlyssesSockdrawer** [MegaMek/mekhq#5011]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

I've only seen this issue occur on the latest pull from my fork of MekHQ.

This issue can occur with both the CamOps and ATB Monthly markets selected.

When clicking on a contract in the contract market window, a pop-up mentioning a divide by zero error appears and the contract window on the right hand side of the market sometimes does not show. This prevents the user from reviewing the contract, but if the error is dismissed the contract can be accepted.

Log screenshot:

![image](https://github.com/user-attachments/assets/b744de0b-abf7-4e09-88bf-0d91651b3105)

### Steps to Reproduce

1. Open an MHQ campaign
2. View the contract market
3. Click on a contract in the list, including GM-generated contracts and naturally generated ones
4. Divide by zero error occurs

### Operating System *

Windows 11

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

50.01 Latest Dev Pull

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17298903/mekhq.log)

Log file.

Basic campaign setup save.

[NonCombatTestUnit-Base.cpnx.gz](https://github.com/user-attachments/files/17298905/NonCombatTestUnit-Base.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
I’ve already got some changes planned to the challenge estimate code so will take a look when I tackle that. Shouldn’t be a difficult fix.

**Comment by IllianiCBT** [comment]
Closing as resolved
