### ISSUE TITLE
[0.50.01-SNAPSHOT] Scenario Opfor Generation Audit and general weirdness

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/mekhq#5012]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

The scenario appears to have generated a force within what I would consider acceptable bounds. Posting file for Illiani to review per his request due to the large number of factors that this scenario generated to make sure everything is hunky dory.

### Steps to Reproduce

N/A

### Operating System *

Windows 11

### Java Version *

Java Version: 17.0.6

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

mekhq.MekHQ.initializeLogging(MekHQ.java:306) - Starting MekHQ v0.50.1-SNAPSHOT     Build Date: 2024-10-04T03:22:42.858455457     Today: 2024-10-08     Origin Project: MekHQ     Java Vendor: Eclipse Adoptium     Java Version: 17.0.6     Platform: Windows 10 10.0 (amd64)     System Locale: en_US     Total memory available to MekHQ: 8 GB     MM Code Revision: e1d2728d2a51e221c92f9f8d1855e899303a4386     MML Code Revision: 446bd8d9c7e28bfdf49d35f312d838c44e16941a     MHQ Code Revision: 036d7bea06aa05b4e65424baa02bf8b67d5c78f3

### Attach Files

[Opfor Generation Weirdness.zip](https://github.com/user-attachments/files/17299827/Opfor.Generation.Weirdness.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Everything _appears_ to be working as intended, when using #5042, so I think this can be closed.
