### ISSUE TITLE
[RFE] Highlight Force Commanders in TO&E Tree View

### ISSUE THREAD

**Issue by WeaverThree** [MegaMek/mekhq#5019]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

Bold or otherwise highlight the commander of each force in the treeview of the TO&E:

![2024-10-09_184705](https://github.com/user-attachments/assets/3ae9aa0c-14c1-4cca-ac46-36e50b4fece8)

Looks like it would involve this bit of code but I have no idea how to determine if the person is the group's commander.

https://github.com/WeaverThree/mekhq/blob/0e47eecb5c8b06f6e3e9b743832d29df155b8073/MekHQ/src/mekhq/gui/ForceRenderer.java#L61

### MekHQ Suite Version *

v0.50.1-SNAPSHOT: 2024-10-04

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Has this been resolved by your other TO&E work?

**Comment by IllianiCBT** [comment]
Would campaign.getForce(forceId).getCommander() work?

It might be getForceCommander - I’m writing from memory

**Comment by WeaverThree** [comment]
Got it, thanks
