### ISSUE TITLE
Hover over SPA descriptions remove first line

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#5020]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Hover over SPA descriptions don't show the first line. It's hard to capture via screenshot, but take Weapon Specialist for example.

This is what should be displayed
`A pilot who specializes in a particular weapon receives a -2 to hit modifier on all attacks with that weapon.`

This is what is displayed
`
 weapon.`

### Steps to Reproduce

1. Hover over an SPA.

### Operating System *

Linux

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Custom MekHQ Version

https://github.com/MegaMek/mekhq/commit/2a8f5f5ba6b8453be4ada8fb25943122cbdba6bf

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by WeaverThree** [comment]
I reported this in #4995 with screenshots but a little less specificity.

**Comment by IllianiCBT** [comment]
Closing as resolved
