### ISSUE TITLE
Division by 0 in Loan window

### ISSUE THREAD

**Issue by SJuliez** [MegaMek/mekhq#5023]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

In the loan window, sliding the Annual Interest slider all the way to 0 results in an ArithmeticException

![image](https://github.com/user-attachments/assets/2b6ed66f-76fb-4b95-887c-d27cdb032e42)

### Steps to Reproduce

Start a new Campaign, "New Pilot" setting; go to the Finances tab; Get Loan; slide the Annual Interest slider all the way to the left

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

50.01 Snapshot

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
