### ISSUE TITLE
[RFE] Option to ignore mothballed meks on Parts In Use report

### ISSUE THREAD

**Issue by WeaverThree** [MegaMek/mekhq#5026]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

I don't really want to buy spare parts for mothballed meks. But removing them always might be bad. I know the interface is already busy there, but is there somewhere we could wedge a checkbox for this?

### MekHQ Suite Version *

v0.50.1-SNAPSHOT: 2024-10-05

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by WeaverThree** [comment]
Implemented by #5055

**Comment by IllianiCBT** [comment]
Closing as resolved
