### ISSUE TITLE
[RFE] Refine Clan bidding report in FG3

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#5027]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

The current Clan bidding report reads as follows: 
![image](https://github.com/user-attachments/assets/c94a1c82-24ed-4541-9530-f76d72d159d7)

The use of whitespaces and lack of cohesion makes it difficult to visually group the lines to one given scenario. 
Suggest whitespaces for paragraphs are kept to a minimum. Also mentioned in Discord was to use bullet points for the units being bid away, and potentially omitting the scenario name from the bidding message, since it follows directly after the announcement of the scenario it relates to. 
Optionally also remove the _Bargained Well and Done_ message if consdered overly obtrusive to visual clarity. 

### MekHQ Suite Version *

v0.50.01-SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
So some notes, because I won't remember them by the time this swings around:

We should change the dialog to read similar to this:

> Clan Emerald Chicken OpFor has bid away the following forces:
> - Hot Dog Cart IIC
> - Banana Car
> - Steve

This removes a lot of the duplicated information (scenario and contract) and condenses everything, organizing it with bullet points will aid readability.

**Comment by IllianiCBT** [comment]
Closing as resolved
