### ISSUE TITLE
Characters with <ancestors> tag can only marry characters with the same ancestor ID

### ISSUE THREAD

**Issue by MattDroz** [MegaMek/mekhq#503]
Was playing around and wanted to make two characters siblings. Added an ancestor tag to both (used ID = "ba301501-0000-0005-0002-000000000000"). At first I didn't add any parent IDs since they weren't the children of a personnel record. When I opened in MekHQ, I right-clicked to Choose Spouse, but it wouldn't load any list.

So, I went back an added a mother id="ba301501-0001-0005-0002-000000000000" to the Ancestor tag. Now when I open up MekHQ and right-click to choose spouse, the ONLY choice is the sibling. I'm thinking there's a NOT missing somewhere. (Unless my bogus IDs are the cause...)

**Comment by pheonixstorm** [comment]
Attach a campaign file. This is an issue of user error rather than an issue with the code as this has been working correctly for a rather long time. 

Having an option to create sibling pairs could be a nice new feature though.

**Comment by MattDroz** [comment]
Here ya go. I thought it might be, but I couldn't think of why it broke.
[Temp.zip](https://github.com/MegaMek/mekhq/files/1389055/Temp.zip)

**Comment by MattDroz** [comment]
Actually, looking at another campaign (where I didn't fiddle with Ancestor IDs), it looks like it's doing the same thing if I jump the date forward to where the kids are old enough to marry.

**Comment by MattDroz** [comment]
Yeah, here's a test campaign. Created two mechwarriors, married them, spawned a few kids, jumped forward 20 years and added some new mechwarriors. The kids can only marry their siblings.
[Test-Ancestors.zip](https://github.com/MegaMek/mekhq/files/1391094/Test-Ancestors.zip)

**Comment by jslater89** [comment]
Looks to be the case, going by around line 1087 in Person.java:

`	public boolean safeSpouse(Person p) {
		// Huge convoluted return statement
		return (
				!this.equals(p)
				&& (getAncestorsID() == null
				|| campaign.getAncestors(getAncestorsID()).checkMutualAncestors(campaign.getAncestors(p.getAncestorsID())))
				&& p.getSpouseID() == null
				&& getGender() != p.getGender()
				&& p.getAge(campaign.getCalendar()) > 13
		);
	}`

It appears to only allow marriage if the two persons have mutual ancestors, rather than not having mutual ancestors.

**Comment by MattDroz** [comment]
So... Is this going to be added as bug?

**Comment by jslater89** [comment]
I submitted a pull request earlier, and @NickAragua merged it, so it should be fixed for the next release.

**Comment by NickAragua** [comment]
Fixed with PR #511
