### ISSUE TITLE
Tactics can be Negative

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#504]
Check out "Jeff Seraka" in Marketplace > Personnel Market

His Tactics Level is -1

[The_Rolling_HoundsNegTac.zip](https://github.com/MegaMek/mekhq/files/1399790/The_Rolling_HoundsNegTac.zip)

**Comment by VampireSeraphin** [comment]
I'm not sure what setting allowed this to happen, but jazz has already uploaded a copy of the CPNX with the bug.

**Comment by VampireSeraphin** [comment]
Loaded this up in a game, MM treats the negative tactics score as a score of 0, providing neither bonus nor penalty.

**Comment by pheonixstorm** [comment]
What file/line did you find that? Will need to change that eventually and would be nice to know ahead of time so I can make note of it. Some SCAs and other rules items may cause tactics to be negative in HQ and passed to MM.

**Comment by scJazz2** [comment]
Open the CPNX in MHQ and Check out "Jeff Seraka" in Marketplace > Personnel Market
