### ISSUE TITLE
MekHQ NI #1641 - Tank spawns not respecting player settings

### ISSUE THREAD

**Issue by RaozSpaz** [MegaMek/mekhq#5041]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

![mission4](https://github.com/user-attachments/assets/675b0811-090e-4b02-938a-ed5bc3ee24a5)
[mission 4 - 6.log](https://github.com/user-attachments/files/17351769/mission.4.-.6.log)

This image is from the first mission in this log. I have my game settings to not generate anything more than light conditions; however, Im assuming that MekHQ is still registering the hostile enviroment of the planet when trying to determine whether it can or cannot spawn units.

![image](https://github.com/user-attachments/assets/6c1adf72-bd57-4ba6-bca3-50eaba508d5e)

Because of this tank units fail to spawn [though for some reason infantry still spawn . . .]

### Operating System *

Windows 10

### Java Version *

Java 17

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

NI #1641

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
