### ISSUE TITLE
[RFE] Add GBV (Generic BV) to MUL content on export

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#5045]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

Forces can be exported as MUL files.  It would be beneficial for the new GBV (Generic BV) value to be included in these exports, either as a full XML element or as an attribute value on an appropriate element.  This would enable GBV to be inspected without pulling log entries and/or resorting to operations which would force the GBV to appear in the log.

### MekHQ Suite Version *

v.050.0

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Where can I find the Export to MUL option?

**Comment by IllianiCBT** [comment]
Closing as resolved
