### ISSUE TITLE
Feature Request: Expand Batch Purchasing

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#505]
Can we expand the new batch purchasing system to the parts purchase window, and the parts in use overview. It would be very helpful in both of these places. Can we also update it to allow purchasing more than a single unit of each item in a batch. That would also be very helpful for bulk goods like ammunition.

**Comment by firefly2442** [comment]
Related issue: https://github.com/MegaMek/mekhq/issues/121

**Comment by HammerGS** [comment]
Closing  per request.
