### ISSUE TITLE
[NIGHTLY 1647] Trying to start a campaign in 3039 kicks me to the main menu

### ISSUE THREAD

**Issue by ussdefiant60** [MegaMek/mekhq#5056]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

I was attempting to start a new campaign in 3039, and recieved a Campaing File Could Not Be Loaded error, and was kicked back to the MekHQ start menu.

### Steps to Reproduce

Start A New Campaign ---> Select Complete Experience ---> Hit Customize ---> Late Succession War ---> War Of 3039 ---> Confirm Date ---> Confirm

### Operating System *

Windows 11

### Java Version *

Java 20

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

50.01 NIGHTLY 1647

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17422016/mekhq.log)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by repligator** [comment]
`12:54:50,840 ERROR [mekhq.gui.dialog.DataLoadingDialog] {AWT-EventQueue-0}
mekhq.gui.dialog.DataLoadingDialog$Task.done(DataLoadingDialog.java:429) - 
java.util.concurrent.ExecutionException: java.lang.NumberFormatException: For input string: "6CSJ"`

**Comment by ussdefiant60** [comment]
Further update: Data\forcegenerator\3039.xml has this in it:

```
        <chassis name='Koshi (Mist Lynx)' unitType='Mek' omni='Clan'>
            <availability>CIH:8,CLAN:7,CCO:5,BAN:7,CSA:5,CW:6CSJ:9,CJF:5,CB:8</availability>
```

Inserting a comma into that 6CSJ fixes the issue, though i don't have the software on this machine to do a proper PR for it.

**Comment by repligator** [comment]
Gosh darn it github, I didn't want to close the issue until it gets merged.
