### ISSUE TITLE
[RFE] Unit Turnover: Show a message when no rolls are needed

### ISSUE THREAD

**Issue by WeaverThree** [MegaMek/mekhq#5059]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

The unit turnover screen can be confusing when there's nobody listed on it, and that's usually true the first few times you see it. Having a message like "no rolls are required at this time" would probably help with that.

### MekHQ Suite Version *

v0.50.1-SNAPSHOT: 2024-10-15 or thereabouts

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
