### ISSUE TITLE
Star League generated as enemy in contract during 3025+ AtB campaign

### ISSUE THREAD

**Issue by RexPearce** [MegaMek/mekhq#506]
Hello,

I got a contract against the enemy "Star League" in my late SW AtB campaign.

(This would be a cool bug, if not for the fact that no RAT exists for SL in that era, so no units were able to generate.)

I dug around the code, and it looks like the problem is a broken faction change in planets.xml for the planet Adherlwin:

**First issue:**
```xml
        <planet>
                <name>Adherlwin</name>
                <xcood>-134.304</xcood>
                <ycood>-418.682</ycood>
                <faction>UND</faction>
                <factionChange>
                        <date>2571-07-09</date>
                        <faction>MOC</faction>
                </factionChange>
                <factionChange> date listed as last week in April so picked East
er to occupy :)
                        <date>2583-04-27</date>
                        <faction>SL</faction>
                </factionChange>
                <factionChange> date noncanon
                        <date>2897-01-01</date>
                        <factionChange>MOC</factionChange> # <<< BROKEN
                </factionChange>
        </planet>
```
Note that the last faction change reverting the planet back to MOC is broken (See BROKEN marker), so the planet remains under SL control from 2583 onwards.

**Second issue:**

While looking for the above, I noticed that the planet Huntress is changing to the SL faction in 3061-01-01 and 3061-04-01. I think those should be "CSL" (Clan Stone Lion)?

**Third (possible) issue:**

The SL faction seems to only appear legitimately twice in planets.xml: for Adherlwin and Tancredi IV - is this the correct faction to be using in these cases - the SL only directly controlled two planets ever? (Or should TH or one of the states be used instead here?)

**Comment by pheonixstorm** [comment]
Terran Hegemony.

Most dates will fall on the first of the year if there is/was no canon information available at the time the entry was changed. There are some worlds that only give a month that a world fell so in those cases entries would be listed on the first of the month. As the list of planets and the information on them is ever changing, even if there is new information available it can and does get missed sometimes.

The MM team is always open for canon planet information. Just make sure it is from an official source and you can provide the book and page number it came from.

**Comment by RexPearce** [comment]
Just to clarify, the minor canon issue I mentioned is distant afterthought to the first two issues.

To summarize:

**First issue:** Typo in XML tag name **results in broken contracts being generated for all eras**. (Broken in that no units can be generate because of non-existent RAT faction)

**Second issue:** Typo in XML tag content **results in broken contracts being generated during 3061**. (Broken in that no units can be generate because of non-existent RAT faction)

Third issue: Minor note of canon about which faction should actually own a planet. I thought I'd mention it, but I don't want it to distract from the first two issues.

**Comment by HammerGS** [comment]
Regarding the first issue, I've fixed the typo and corrected the date.

Second issue - Huntress was held by the Second SL during that time.
http://www.sarna.net/wiki/Huntress#3059
The RAT issue might be one that @neoancient can clear up he coded the RAT Generator.

Third issue, is planets can and do have multiple factions on them. They could be shared planets in eras like the First Star League, planets involved in long term campaigns or battles.

**Comment by RexPearce** [comment]
re: Second issue, right, I forgot about the second Star League. So this isn't a typo at all then.

re: First issue, thanks for fixing the typo. That should prevent the broken contract that I saw from being generated.

Given that the first issue was the only real issue, this issue can probably be closed. Do the devs prefer do the closing themselves, or have the original opener do the closing?

**Comment by pheonixstorm** [comment]
Once an issue is fixed and pushed to the repo the devs will close it unless the commit is tagged such as Fixes # 506 or I think Closes works as well.

For other issues that are user error, an error outside the software, or something that ends up NOT being an error you would normally close your own ticket.
