### ISSUE TITLE
[0.50.01-2024-10-15] Part Quality Report shouldn't show ammo bins

### ISSUE THREAD

**Issue by WeaverThree** [MegaMek/mekhq#5079]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

Ammo bins are not maintenence items and only have a quality by default, it never changes. Therefore they should be filtered out of the quality report.

Possibly items on infantry or other unit types need to be filtered too? Unsure.

### Steps to Reproduce

Use the quality report on any unit with ammo.

### Operating System *

Linux

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

v0.50.01-SNAPSHOT 2024-10-15

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Can armor have a quality and if not, do we display that too?

**Comment by WeaverThree** [comment]
Yep, armor has a quality and is maintained and it goes up and down and stuff.

**Comment by IllianiCBT** [comment]
Closing as resolved
