### ISSUE TITLE
[0.50.01-2024-10-15] TO&E drag and drop messses with StratCon deployments. 

### ISSUE THREAD

**Issue by WeaverThree** [MegaMek/mekhq#5084]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

When units are deployed via StratCon, drag and drop involving them in the TO&E gets strange (see below).

Drag & Drop for involving deployed forces should probably be disabled. I would suggest it remain possible to adjust what units are in the forces, at least in GM mode, though.

### Steps to Reproduce

1. Get a standard company into the position of being able to deploy on the stratcon map
2. Stratcon Map: Deploy one lance
3. Briefing Room: 4 units are deployed
4. TO&E: Drag deployed lance into another lance. Note its deployed color goes away
5. Briefing Room: 4 units still deployed
6. TO&E: Drag another lance into deployed lance. Nothing is marked deployed
7. Briefing Room: 8 units are deployed
8. TO&E: Drag everything back into original position. Nothing is marked deployed
9. Briefing Room: 4 units are deployed.

And so on

### Operating System *

Linux

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

v0.50.01-SNAPSHOT 2024-10-15

### Attach Files

13:29:59,690 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:307) - Starting MekHQ v0.50.1-SNAPSHOT
    Build Date: 2024-10-16T03:25:30.725189744
    Today: 2024-10-20
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.12
    Platform: Linux 6.11.3-200.fsync.fc40.x86_64 (amd64)
    System Locale: en_US
    Total memory available to MekHQ: 8 GB
    MM Code Revision: dbecc3ee1390114dc4e1ab995c953f22c743b2ce
    MML Code Revision: bad56a653b7db9f4ba51fe399940b05c716d60fc
    MHQ Code Revision: 3ab76d07dec80d9c7278dcf24791b9472d0ce1ce

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
