### ISSUE TITLE
[0.43.4] Individual soldier skill affects infantry unit weight

### ISSUE THREAD

**Issue by RexPearce** [MegaMek/mekhq#509]
I noticed two identical motorized infantry units showed different weights in the MekHQ hanger 5.5t vs 6.25t. This difference was passed on to MM meaning I couldn't mount the 6.25t unit in my Karnov, whereas the 5.5t unit mounted fine.

It seems this is related to the AntiMech skill: when a certain threshold of soldiers with AntiMech skills is reached, the platoon increases from 5.5t to 6.25t. I realize this is probably to account for the extra weight of the antimech equipment, however, shouldn't the existence of that equipment depend on the unit configuration, not the skill of the crew members?

(This also seems to work the other way: If create an infantry unit with antimech unchecked, it seems to gain weight if the threshold of soldiers with AntiMech skills is met.)

**Comment by HammerGS** [comment]
Part of this has been fixed here - https://github.com/MegaMek/megamek/commit/269b8b6452f124e8cae3338be63ecdd89b73597b#diff-4f6cb769e0fa04e5e6f8411242e2fe36

Part of the solution is to have Anti-Mek trained unit files.

**Comment by RexPearce** [comment]
So with that change, infantry units will still be affected by individual soldiers' antiMech skill, but range of weight change will be smaller (i.e. 5.5t -> 6t, instead of 5.5t -> 6.25t) - am I understanding that correctly?  If so, while it doesn't actually address the underlying issue, it certainly reduces the main inconvenience caused by it.

**Comment by HammerGS** [comment]
The foot units are done, 
![image](https://user-images.githubusercontent.com/13752452/31854512-ca126f80-b657-11e7-9356-04e92d1e414d.png)

But I still need to make Anti-mek and non anti-mek trained motorized units. Ultimately it's going to need to be AM trained and non-AM trained units.

Also I suspect some code changes for when the skill is changed in customized unit.

**Comment by RexPearce** [comment]
Sounds good, thanks.

**Comment by sixlettervariables** [comment]
@RexPearce is this still an issue? I recall you worked on some of the data bits for this.

**Comment by RexPearce** [comment]
I haven't seen this issue come up in years. I just checked the weights of the generic infantry types in the latest dev, and both the Foot platoons and Motorized platoons seem to match the TW numbers.
