### ISSUE TITLE
Personnel Log does not display full injury report

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/mekhq#51]
Prior to the change in the way the personnel log is displayed the injury report would show on multiple lines, now it (and presumably everything else) only shows on a single line. This makes reading the log difficult as the only way to pull up a full entry to to edit the log.

**Comment by Akjosch** [comment]
Did you try it in the newest build or release?

**Comment by pheonixstorm** [comment]
The bugged one 0.3.26

Looks like this works properly in 0.3.27 so I am going to go ahead and close this.
