### ISSUE TITLE
Dragoons rating: Medical support includes KIA/MIA/Retired Personnel

### ISSUE THREAD

**Issue by MattDroz** [MegaMek/mekhq#510]
I'm working on recreating Team Banzai to run through MekHQ through the Clan Invasion and Civil War. As I'm building the "history" of the Merc Unit before I begin, I've got a lot of data to get the Dragoon's Rating up. I've built it so they have 576 Active Combat Personnel, 193 Support, 73 Dependents, 1 prisoner, 113 MIA, 170 KIA, and 11 Retired. Going by the FM:Mercs formula, that means the Medical Support hours should be:

840/7 = 120 * 4 = 480 
3 + 3/5 = 3.6
484 Man-Hours.

But the Dragoons Rating is showing I need 652 man-hours, which is what it would be if the doctors are maintaining non-active personnel:

1134/7 = 162 * 4 = 648
3 + 3/5 = 3.6
652  Man-hours

[Team Banzai30250101.zip](https://github.com/MegaMek/mekhq/files/1412064/Team.Banzai30250101.zip)

**Comment by NickAragua** [comment]
Fixed with PR #538
