### ISSUE TITLE
Daily Log is empty on each new day until a save is loaded

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#5108]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

The Daily Log is empty on each new day until a save is loaded.

### Steps to Reproduce

1. Start a new MHQ campaign.
2. Advance Day.
3. Note that the daily log is empty.
4. Save and load the campaign.
5. The Daily Log will now show a Personnel Market Update.
6. Hit Advance day.
7. Note that the daily log is empty.
8. Save and load the campaign.
9. The Daily Log will now show a Personnel Market Update.
10. Repeat ad infinitum.

### Operating System *

Linux

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Custom MekHQ Version

https://github.com/MegaMek/mekhq/commit/035ff6c725a948b98d811bdaac45d7375ea67074

### Attach Files

[CGB306230630104.cpnx.gz](https://github.com/user-attachments/files/17476950/CGB306230630104.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Can I confirm that this is 50.0 and not the nightly?

**Comment by IllianiCBT** [comment]
This does appear to be affecting the nightly.

**Comment by IllianiCBT** [comment]
It also only seems to occur when using the `Advance Days(s) Dialog`

**Comment by IllianiCBT** [comment]
Some entries also seem to be duplicated in the `Advance Day(s) Dialog`

**Comment by repligator** [comment]
Sorry for the late reply. My testing was done via IDEA, the most recent pull being https://github.com/MegaMek/mekhq/commit/035ff6c725a948b98d811bdaac45d7375ea67074 .

**Comment by IllianiCBT** [comment]
Closing as resolved
