### ISSUE TITLE
[0.50 NIGHTLY 1652] Botched reinforcement roll produces 4 grounded dropships for enemy

### ISSUE THREAD

**Issue by ussdefiant60** [MegaMek/mekhq#5109]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

woke up this morning, decided to do the scenarios that rolled up last night. Tossed a reinforcement lance at the Assassinate An Atlas scenario, reinforcement roll fails, grabs GroundedEnemyDropship.xml for the negative event, and apparently 1 enemy dropship down turns into 2 Leopards and 2 Unions

### Operating System *

Windows 11

### Java Version *

Java 17 Adoptium

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

50.01 NIGHTLY 1652

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17479716/mekhq.log)
[The 5th Cipher Infrastructure30401222.cpnx.gz](https://github.com/user-attachments/files/17479723/The.5th.Cipher.Infrastructure30401222.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
