### ISSUE TITLE
[RFE] Contract Automation

### ISSUE THREAD

**Issue by IllianiCBT** [MegaMek/mekhq#5116]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is a new feature

### Brief Description *

Current maintenance rules, while RAW, are very rough on the player and create unfun experiences where the user arrives at their contract and half their force is in ruins before they even leave the DropShip.

Furthermore, accepting a contract requires a number of repetitive actions: accept the contract, navigate to the Briefing Room, click on the Location, Calculate Jump Path, Begin Transit.

I propose we add a couple of points of automation to when contracts are accepted:
- Ask the user if they want to mothball their TO&E -- storing the details of what units are mothballed in this fashion, for use later. Ideally we'd tell the user how much extra this will add to their journey costs, but that choosing to not mothball units will result in their needing to be maintained while en route.
- Ask the user if they would like to chart a course to the destination. If confirmed, we should then ask the user whether they would like to begin transit.
- When the user enters the target system, ask them if they would like to begin unmothballing their TO&E. At which point we fetch the list stored previously and begin unmothballing those units.

Mothballing and unmothballing in this manner should be done instantly. This can be logic'd as the campaign receiving assistance from DropShip crewed, etc, but removes the need for us to dynamically assign (and potentially invent) techs. It also removes any chance of the user being mid-unmothballing when they arrive on planet. While it does break the rules, I do think this is an overall improvement to player experience.

All of this allows the users' contract acceptance journey to be reduced to a handful of dialog confirmations, removing much of the repetitive busywork that just creates a barrier of entry to new players.

### MekHQ Suite Version *

50.01

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved

**Comment by BullseyeSmith** [comment]
Hey @IllianiCBT ! Has this been implemented? I ask because I'm running a campaign with the snapshot to test things out. When I accepted a contract, I was not asked about mothballing or setting a course. When I go to Interstellar Map and click Begin Transit, nothing happens. If I advance the day, I see that the DropShip has started transit to jump point, but there was no indication that it accepted my command the day prior.

**Comment by IllianiCBT** [comment]
It's been implemented, when you click 'accept' it should trigger the dialog. I'm not aware of any way to skip that dialog short of canceling the 'accept' action if you get the 'this contract is too hard/easy' dialog.

**Comment by IllianiCBT** [comment]
When you say 'snapshot' what do you mean? We launched 50.01 earlier in the week/late last week and this was included.

**Comment by BullseyeSmith** [comment]
Meaning I'm using nightly artifact link https://github.com/MegaMek/mekhq/actions/runs/11622017545/artifacts/2131272913 listed on the "[StratCon and Logistics: The Future of MegaMek Campaigns](https://megamek.org/development/stratcon/2024/10/31/StratCon-and-Logistics-The-Supply-Chain-Ahead.html)" post. I only time to play on the weekends so I grab the new file and use it until I hit a problem, then I start the reporting process. :)

**Comment by BullseyeSmith** [comment]
I've reloaded a save file from before accepting a contract and all the happens is the contract disappears from the list and I have to close the contract market window. I'll test it on the 50.0.1 release and then submit a ticket if it doesn't work on that.

**Comment by BullseyeSmith** [comment]
Okay, it works fine on 0.50.01. I thought the above links was for the nightly, but it was just a shot in time from before this was implemented. Thanks for your time.
