### ISSUE TITLE
Very high turnover check base number and incorrect insolvency warning

### ISSUE THREAD

**Issue by Olin011** [MegaMek/mekhq#5129]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

I generated new company on nightly build 0.50 and I think something is wrong with the finances and turnover numbers. Firstly, at the end of the month I get a message that I'm unable to afford the expenses that are 340k and I'm sitting on 8.8m cash. Secondly, I get very high base numbers in turnover dialog for some reason. Not sure if these two are somehow related so I am reporting it as one issue.
![Turnover](https://github.com/user-attachments/assets/84347d9e-d4a5-4b31-a651-4822fd76a034)

![Finances](https://github.com/user-attachments/assets/51abf302-8be4-4f29-aa9d-043d22c7414f)

### Steps to Reproduce

1. Generated new company. Changed some options like: merc company size limits, use % based maintenance costs, tracking mechs. The last option - track mechs - for some reason did not register. I re-checked it a few times but it was not saved. 
2. Edited some pilots and hired new ones while advancing days.
3. Ordered some parts, and started repairs on mechs that failed maintenance checks.
4. Took a loan.
5. Waited till the end of the month for new contracts.
6. Got hit with the (incorrect) message that I could not afford expenses and with the bugged turnover check. 

### Operating System *

Windows 10

### Java Version *

17.0.12

### MekHQ Suite Version *

v0.50.0

### Attach Files

![log](https://github.com/user-attachments/assets/87657405-d53e-46d3-ae46-50c5c081aa99)

[logs.zip](https://github.com/user-attachments/files/17513841/logs.zip)
[Free Lancers Company30270131.cpnx.gz](https://github.com/user-attachments/files/17513851/Free.Lancers.Company30270131.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
For future reference, please keep issue reports to one issue per report.

**Comment by IllianiCBT** [comment]
Both issues already resolved in 50.01, closing as resolved
