### ISSUE TITLE
[RFE] Do not expel enemy factions at war from Reeducation Camps

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#5131]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

I had a DC vessel pilot join my unit. I sent him to a reeducation camp. He was expelled when the Combine/Dominion war started. Given that the whole point of a reeducation camp is to switch factions, would it be possible to exempt enemy personnel from expulsion?

### MekHQ Suite Version *

.50.1

### Attach Files

[War-expulsion-CGB306230630223.cpnx.gz](https://github.com/user-attachments/files/17525745/War-expulsion-CGB306230630223.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
