### ISSUE TITLE
[0.50.01-SNAPSHOT] Formatting issue with end-of-scenario resolution objectives window

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/mekhq#5132]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

The objectives checklist window of the scenario resolution window has an unusually large amount of blank space at the top, so much that I had to scroll down to even begin seeing the checkboxes with the default window size.

![Screenshot 2024-10-25 141313](https://github.com/user-attachments/assets/18f19527-087a-4484-880c-308b122ac3dc)

Campaign attached.
the "Campaign salvage" can be used to Manually Resolve the scenario.
If that doesn't work, I've included the final autosave from the megamek scenario that can beloaded to prompt the end-of-scenario popup window to appear.

Tested and confirmed that issue is present regardless of what method is used to resolve the scenario, including on a fresh close and re-open of mekHQ.

### Steps to Reproduce

1. Load ResolutionWindowFormatting.cpnx
2. Briefings tab -> Manually resolve -> Use Tempest Winds.mul
3. Observe issue on the scenario objectives checklist screen

### Operating System *

Windows 10

### Java Version *

Java Version: 17.0.6

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

mekhq.MekHQ.initializeLogging(MekHQ.java:307) - Starting MekHQ v0.50.1-SNAPSHOT     Build Date: 2024-10-23T03:23:14.592586070     Today: 2024-10-24     Origin Project: MekHQ     Java Vendor: Eclipse Adoptium     Java Version: 17.0.6     Platform: Windows 10 10.0 (amd64)     System Locale: en_US     Total memory available to MekHQ: 8 GB     MM Code Revision: 8bea36f57e240eb47fc127f6a2fe2a0f48c568e6     MML Code Revision: 384380362038ce744734c3a05836fd5d511d1df0     MHQ Code Revision: 52412bf1b23e9227e0528c642ba52062027c2cd2

### Attach Files

[ScenarioResolutionFormatting.zip](https://github.com/user-attachments/files/17526645/ScenarioResolutionFormatting.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
I'm guessing this is related to @WeaverThree's recent changes

**Comment by WeaverThree** [comment]
So far, what I've discovered.

- Loading my own save and doing 'resolve manually' without a MUL, no space at the top of the objective list
- Loding OP's save and doing 'resolve manually' without a MUL, some space at the top of the objective list
- Loading OP's save and doing 'resolve manually' with provided MUL, hugs space at the top of the objectives list.

@.@

**Comment by WeaverThree** [comment]
Well I've discoverd that the code inside `ResolveScenarioWizardDialog.generateObjectiveStatusPanel()` isn't at fault, because if I switch its axis to generate along X it's tightly butted up against the left edge but there's still a huge gap above and below:

![2024-10-26_210327](https://github.com/user-attachments/assets/dc0efdbc-d031-4af0-8cbe-5435370dcbd4)

So it's not just blarting out extra spaces as it generates the objective list or anything like that.

I've poked at a few things outside of the function but nothing so far has helped.
