### ISSUE TITLE
Field Kitchens counting all personnel even when "Ignore Noncombatants" is flagged .50.0

### ISSUE THREAD

**Issue by Insert25c** [MegaMek/mekhq#5139]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

Field Kitchen is counting all personnel (combat, support, dependents, and prisoners) despite chosen options

![image](https://github.com/user-attachments/assets/6ab09b0b-9672-4805-998f-8cf39f4bca30)

### Operating System *

Windows 10

### Java Version *

17.0.11

### MekHQ Suite Version *

v0.50.0

### Attach Files

[Magnificent Bastards31300701.cpnx.gz](https://github.com/user-attachments/files/17535624/Magnificent.Bastards31300701.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
We need a copy of your Customs folder to be able to load your save :)

<img width="582" alt="image" src="https://github.com/user-attachments/assets/1b7e8416-f090-4e92-b8d3-944492dbb78b">

**Comment by Insert25c** [comment]
sorry about that. this should help. If not, its the kitchen truck UlyssesSockdrawer posted in the discord (https://discord.com/channels/458705327911731231/1125117349029236777/1280495714807447676)

[customs.zip](https://github.com/user-attachments/files/17535884/customs.zip)

**Comment by IllianiCBT** [comment]
Closing as resolved
