### ISSUE TITLE
Feature Request: Building Conventional Fighters

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/mekhq#514]
I would like to create the other (Marik, Kurita, etc.) spotter plane versions from the Davion Boomerang (http://www.sarna.net/wiki/Boomerang). However MekHQ does only allow the creation of arespace fighters (not conventional ones). Maybe this functionality can be added easily.

**Comment by HammerGS** [comment]
MegamekLabs current releases has this. 

![image](https://user-images.githubusercontent.com/13752452/32406350-67282258-c13c-11e7-80aa-c62a78c5fd2a.png)

You can build the units in the lab and add them to a customs folder in mechfiles.  You would then be able to refit, or purchase the units.

**Comment by neoancient** [comment]
It still needs to be enabled as an option in MekHQ.
