### ISSUE TITLE
RFE: Add Export Finances Command as CSV, TD text file

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#515]
Please add the ability to export the data in Finances Tab as a CSV or TD text file or both.

The command could be under the File > Export or a button in Finances tab.

Enabling Select All/Copy/Paste in the Finances Tab might also be useful.

Perhaps an option also to remind on December 31st/Last Day of Year.

**Comment by NickAragua** [comment]
Has been addressed with PR #762
