### ISSUE TITLE
Higher than expected opfor with FG3

### ISSUE THREAD

**Issue by Makaze2048** [MegaMek/mekhq#5153]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Log of FG3 generation as requested by Illiani.

Log file attached, the relevant section when I originally generated is below. I regenerated and messed around with it after that though. Save file is from AFTER I altered the mission manually, don't have one from after it exists and before I made changes.

17:55:41,222 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForces(AtBDynamicScenarioFactory.java:245) - GENERATING FORCES FOR: FRONTLINE DISRUPTION

17:55:41,222 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForces(AtBDynamicScenarioFactory.java:274) - Target Percentage: 120

17:55:41,222 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForces(AtBDynamicScenarioFactory.java:275) - Difficulty Multiplier: 1.0

17:55:41,222 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.calculateEffectiveBV(AtBDynamicScenarioFactory.java:2719) - Total Seed Force Generic BV: 7159

17:55:41,222 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.calculateEffectiveBV(AtBDynamicScenarioFactory.java:2740) - Total Base Generic BV Budget: 7159 (adjusted for campaign difficulty)

17:55:41,222 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForces(AtBDynamicScenarioFactory.java:287) - ++ GENERATING A FORCE FOR THE PLAYER TEMPLATE ++

17:55:41,223 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForces(AtBDynamicScenarioFactory.java:287) - ++ GENERATING A FORCE FOR THE ADDITIONAL FORCE TEMPLATE ++

17:55:41,229 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForces(AtBDynamicScenarioFactory.java:287) - ++ GENERATING A FORCE FOR THE REINFORCEMENTS TEMPLATE ++

17:55:41,229 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForces(AtBDynamicScenarioFactory.java:287) - ++ GENERATING A FORCE FOR THE FORWARD OBSERVER TEMPLATE ++

17:55:41,237 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.calculateEffectiveBV(AtBDynamicScenarioFactory.java:2719) - Total Seed Force Generic BV: 7159

17:55:41,239 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.calculateEffectiveBV(AtBDynamicScenarioFactory.java:2736) - Free Worlds League Additional Force Generic BV: 3799

17:55:41,240 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.calculateEffectiveBV(AtBDynamicScenarioFactory.java:2736) - Unknown Hostiles Generic BV: 1049

17:55:41,240 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.calculateEffectiveBV(AtBDynamicScenarioFactory.java:2740) - Total Base Generic BV Budget: 12007 (adjusted for campaign difficulty)

17:55:41,240 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForces(AtBDynamicScenarioFactory.java:287) - ++ GENERATING A FORCE FOR THE OPFOR TEMPLATE ++

17:55:41,240 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForce(AtBDynamicScenarioFactory.java:453) - Force BV Multiplier: 1.5 (from scenario template)

17:55:41,246 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForce(AtBDynamicScenarioFactory.java:662) - Force Weights: H (HHHH)

17:55:41,253 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForce(AtBDynamicScenarioFactory.java:662) - Force Weights: M (MMMH)

17:55:41,259 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForce(AtBDynamicScenarioFactory.java:662) - Force Weights: H (HHHH)

17:55:41,332 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForce(AtBDynamicScenarioFactory.java:662) - Force Weights: A (HAAA)

17:55:41,333 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForce(AtBDynamicScenarioFactory.java:790) - OpFor generated a force with 21537 / 18010  Generic BV

17:55:41,333 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForce(AtBDynamicScenarioFactory.java:813) - Final force 21537 / 18010  Generic BV (may exceed by *1.25)

17:55:41,333 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.calculateEffectiveBV(AtBDynamicScenarioFactory.java:2719) - Total Seed Force Generic BV: 7159

17:55:41,336 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.calculateEffectiveBV(AtBDynamicScenarioFactory.java:2736) - Free Worlds League Additional Force Generic BV: 3799

17:55:41,336 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.calculateEffectiveBV(AtBDynamicScenarioFactory.java:2736) - Unknown Hostiles Generic BV: 1049

17:55:41,337 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.calculateEffectiveBV(AtBDynamicScenarioFactory.java:2740) - Total Base Generic BV Budget: 12007 (adjusted for campaign difficulty)

17:55:41,344 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.calculateEffectiveBV(AtBDynamicScenarioFactory.java:2719) - Total Seed Force Generic BV: 7159

17:55:41,347 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.calculateEffectiveBV(AtBDynamicScenarioFactory.java:2736) - Free Worlds League Additional Force Generic BV: 3799

17:55:41,347 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.calculateEffectiveBV(AtBDynamicScenarioFactory.java:2736) - Unknown Hostiles Generic BV: 1049

17:55:41,348 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.calculateEffectiveBV(AtBDynamicScenarioFactory.java:2740) - Total Base Generic BV Budget: 12007 (adjusted for campaign difficulty)

17:55:41,355 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForce(AtBDynamicScenarioFactory.java:662) - Force Weights: M (MMHH)

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

10/28 nightly

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17564554/mekhq.log)
[FG3.cpnx.gz](https://github.com/user-attachments/files/17564557/FG3.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by RaozSpaz** [comment]
![image](https://github.com/user-attachments/assets/3f1d2d0b-3983-4650-a1fe-bb5ed8b82c84)

The OpFor generator seems to be grabbing Unknown Hostiles when determining its GBV pool.

**Comment by IllianiCBT** [comment]
Thanks for the report, I’ll get this fixed tomorrow. :)

**Comment by IllianiCBT** [comment]
When uploading a save you also need to include a copy of your customs folder, as otherwise the save cannot be loaded:

<img width="577" alt="image" src="https://github.com/user-attachments/assets/f09ee645-8c99-40d4-9ae3-7846875ab710">

**Comment by IllianiCBT** [comment]
I've checked over the code and I've been unable to replicate this issue. I'll require your customs before I can investigate further.
