### ISSUE TITLE
Opfor generating a large number of low value units in scenarios

### ISSUE THREAD

**Issue by TheThinKing0** [MegaMek/mekhq#5160]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [x] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

(Playing on the Artifact build)

All scenarios generated on my current contract consist entirely of large numbers of low value units. This seems to persist even if I change the contract settings and regenerate the opfor (they just make even more units to raise the BV, not stronger ones).

<img width="313" alt="Screenshot 2024-11-01 185502" src="https://github.com/user-attachments/assets/5282c4ec-244f-43f4-9881-5e0676abb055">

### Operating System *

Windows 11

### Java Version *

Eclipse Adoptium 17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

MekHQ v0.50.1-SNAPSHOT

### Attach Files

[mekhq.zip](https://github.com/user-attachments/files/17604923/mekhq.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
I need your save, your customs folder (if you have any customs) and your log file so I can investigate

**Comment by TheThinKing0** [comment]
[SNAFU-Gardeners of Eden30600313.cpnx.gz](https://github.com/user-attachments/files/17604927/SNAFU-Gardeners.of.Eden30600313.cpnx.gz)
[customs.zip](https://github.com/user-attachments/files/17604930/customs.zip)

Here's the saved game and customs folder (very few), the log is attached in the original ticket

**Comment by IllianiCBT** [comment]
Perfect, thanks. Sorry must have missed the log

**Comment by TheThinKing0** [comment]
I tried ending that cursed contract and taking a totally different one instead, which resulted in normal looking opfors:

![Screenshot 2024-11-01 193441](https://github.com/user-attachments/assets/7dce337f-1449-4f4e-ad58-c62eb9eedd62)

**Comment by TheThinKing0** [comment]
I thought maybe it was a problem with skulls, my bugged mission was 0.5 skulls and the above was 2.5 skulls, so I took another 0.5 skull mission and opfor was normal. It seems like a contract-specific problem??

**Comment by IllianiCBT** [comment]
Closing as resolved
