### ISSUE TITLE
Stratcon - VIP Defense scenario does not generate objective to protect VIP; Cadre Duty allies + VIPs; multiple modifiers generating

### ISSUE THREAD

**Issue by Tempest-56** [MegaMek/mekhq#5162]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Running a Cadre Duty mission and pulled a VIP Defense scenario. Issues that resulted: 
- Scenario generated with the three cadre rookies as part of the Attached Allies group, as well as the VIP. This made it difficult to tell who the VIP actually was to defend them.
- Scenario did not generate an objective to actually protect the VIP. One to protect the cadre rookies but no VIP.
- The AlliedTraineesGround.xml modifier generated twice

### Operating System *

Windows 11

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Custom MekHQ Version

Snapshot as of 11/1

### Attach Files

[Autosave-1-Alley Cats-30151219.cpnx.gz](https://github.com/user-attachments/files/17608896/Autosave-1-Alley.Cats-30151219.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
