### ISSUE TITLE
Salaries shown in "Personnel Report" window and in the Personnel tab are different from the total value in Finances tab

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#5169]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

The salaries in the Personnel tab and in the Personnel report correctly show the base values and the skill multipliers applied, but the Finance tab value shows a larger number.

![image](https://github.com/user-attachments/assets/9a622fc5-6357-4bba-b24b-ac23a0f72bdb)

A new campaign has the same issue.

Further investigation with others on the Discord revealed that the difference is the total salaries of astechs and medics combined.

There is still 700 c-bills unaccounted for in the campaign attached, which might be explained by the dependents modifier being applied on the personnel tab (and consequently on the report), but not on the finance tab, which is apparently how it should be.

### Operating System *

Windows 10

### Java Version *

Java Version: 17.0.13

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Resupply artifact from 2024-11-04 with hotfix

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17625865/mekhq.log)
[megamek.log](https://github.com/user-attachments/files/17625866/megamek.log)
[megameklab.log](https://github.com/user-attachments/files/17625867/megameklab.log)
[5th Circle Furies - NoContract.cpnx.gz](https://github.com/user-attachments/files/17625912/5th.Circle.Furies.-.NoContract.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
I know this was discussed at length in Discord, what was the conclusion reached?

**Comment by JonhyBurner** [comment]
The larger number is the correct one, the one on the personnel report is missing the astechs/medics salaries.

Also, the dependents salaries are being affected by the skill modifiers. Unsure on how it's supposed to be, but that creates a difference as well.
