### ISSUE TITLE
RFE: [ATB] Display BV for Each Force in Briefing Room

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#517]
In the Briefing Room... assigned units for the battle... display the BV for each "force"

At the bottom display Friendly/Enemy BV totals.

**Comment by Qwertronix** [comment]
As a separate line, or as a mouse-over tooltip? Maybe a bit of both by having the Friendly / Enemy BV totals listed in the scenario details, and BV/tonnage data shown as a mouse-over tooltip for each of the forces?

**Comment by scJazz2** [comment]
![bv](https://user-images.githubusercontent.com/16738384/33906923-5defa476-df51-11e7-9fbf-d7723215f8c9.jpg)

**Comment by Qwertronix** [comment]
Hmm I think that, as this mockup actually demonstrates, this particular way of displaying it would overload this view. 

A better approach would probably be to display only the Total BV values on their own lines like there, but hide the per-force values until that force is expanded, and then display its BV value on a subtitle line right under the force name.

**Comment by scJazz2** [comment]
I would agree. It was a Hack... and my screen and yours are different but if that is the way you want to do it, go right ahead.

**Comment by NickAragua** [comment]
Done for bot forces.
