### ISSUE TITLE
[RFE] Improvement to how available tracks are displayed in Stratcon panel

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5170]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

After discussion in discord, a general consensus was reached that it would be simpler and more clear to users if the list of available tracks was displayed in a one-column list view instead of a drop down, with a number of tracks visible by default to illustrate that there can be more than one track for new and unfamiliar users. The column can have a scroll bar to accommodate as many tracks as needed that will appear when the default amount that would be displayed is exceeded, providing a visual indicator of a change.

The right half of the stratcon screen is fairly compact, between 5 to even possibly 10 displayed track selections could be displayed by default.

![image](https://github.com/user-attachments/assets/32ffd0e1-9e09-4eb6-803d-45ea058d63f2)

For reference, the drop down display could simply be converted to display these items in a column making it much clearer 'at a glance' and more intuitive to learn/interact with.

![image](https://github.com/user-attachments/assets/86d95c58-9b29-4fa9-a269-66c98ed72c9e)

Screen space available seems to be workable, and possibly repositioning to the right of the Strategic Objectives panel would be a convenient way to do it provided it isn't earmarked for something else already.

### MekHQ Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved.
