### ISSUE TITLE
Uncaught java.util.ConcurrentModificationException message

### ISSUE THREAD

**Issue by BTSS88** [MegaMek/mekhq#5171]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

The error message pops up when trying to advance a day.
![Screenshot 2024-11-06 003059](https://github.com/user-attachments/assets/ba863075-cf72-40b3-a27a-85ae325b7a3c)

### Steps to Reproduce

Load saved file and advance day. 

### Operating System *

Windows 11

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Attach Files

[Musket's Emergency Contractors30610429.cpnx.gz](https://github.com/user-attachments/files/17633508/Musket.s.Emergency.Contractors30610429.cpnx.gz)
[logs.zip](https://github.com/user-attachments/files/17633549/logs.zip)
[customs.zip](https://github.com/user-attachments/files/17633554/customs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
This has been resolved in the 50.01 dev version. For now, go into campaign options, personnel, and disable personnel removal.

Closing as resolved.
