### ISSUE TITLE
Dead prisoners triggering POW nag

### ISSUE THREAD

**Issue by Tempest-56** [MegaMek/mekhq#5182]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

During a mission, I had a prisoner die of natural causes. At the end of said mission I released/ransomed everyone listed as prisoners but continued to get the Prisoner of War nag. I discovered several in-game months later that the dead solider still counted as a prisoner of the purposes of the nag despite not appearing in the Prisoners tab. (After testing, this also applies to anything else that moves them to an inactive tab - being sacked, going AWOL, being a student, maternity leave, etc. Death is simply the most common/likely.) 

This probably shouldn't happen as it can be (and was!) very confusing for the user when they're told they still have prisoners but the Prisoners tab is empty.

### Steps to Reproduce

1. Have a prisoner
2. Make them die
3. Deal with the Prisoner of War nag

### Operating System *

Windows 11

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Custom MekHQ Version

Snapshot as of 11/1

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
