### ISSUE TITLE
Extreme weather maintenance debuffs are being applied to units in a Facility - Basic location

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#5184]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

My campaign is currently in Galatea, with an equatorial temperature of 55º C. This is enough to trigger the extreme weather modifiers on maintenance. But I also currently have Facility - Basic as a repair location for my units, so the maintenance checks should not be modified by the temperature (or any other planetary weather condition), since it's a closed environment, according with Cam Ops (I checked the latest errata).

![image](https://github.com/user-attachments/assets/59640c40-008c-4c55-b87d-eaef5c19ea47)

### Steps to Reproduce

1. Set up a company in Galatea
2. The game will select Facility - Basic automatically for the units
3. Advance to next maintenance check. A "+ 1 (Extreme Temperature)" will be on the maintenance report

### Operating System *

Windows 10

### Java Version *

Java Version: 17.0.13

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

MekHQ resupply artifact from 2024-11-04

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
