### ISSUE TITLE
[RFE] Logistics Overhaul - Allow the player to check the required convoy size during a contract.

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#5189]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

When accepting a contract, the game shows a pop-up indicating the required size of the convoy, in tons.

Since this is now dynamic and depending on ToE size, a place where a player can check that is needed.

Illiani suggested putting it in the Briefing Tab, and I agree.

### MekHQ Suite Version *

MekHQ Logistics Overhaul artifact from 2024-11-04 with hotfix

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
