### ISSUE TITLE
Automatic Mothballing of Dropships when starting contracts

### ISSUE THREAD

**Issue by MrHiDie** [MegaMek/mekhq#5190]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

When starting a new contract, you are prompted to automatically mothball all units in your TOE until you arrive planetside to save money. However, clicking yes will also mothball any dropships you have in your TOE which is what is supposed to be transporting the units.

### Steps to Reproduce

1. Have a dropship in your TOE
2. Accept a contract that requires you to travel
3. When it asks you mothball all your TOE units click accept
4. Your Dropship will be mothballed and unable to be unmothballed until you arrive planetside

### Operating System *

Windows 11

### Java Version *

Adoptium 17.0.13

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

v0.50.02

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
We should explicitly exclude all large vessels and (maybe) small craft. This was an oversight in my part.

**Comment by IllianiCBT** [comment]
Closing as resolved
