### ISSUE TITLE
[RFE] Auxiliary formations

### ISSUE THREAD

**Issue by Tempest-56** [MegaMek/mekhq#5192]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

The implementation of combat versus non-combat forces in the TOE is good but could be refined further. I propose a third designation: auxiliary units. 

The intended use is for forces that are combat facing but not intended to be primary units such as an artillery lance. Right now such lances are given the same weight as any other lance for the purposes of scenario generation. This can create weird, unfun, or suboptimal scenarios. Under AtB you could affect that by assigning different roles (or leaving them Unassigned) but the move to Stratcon has gotten rid of that.

An auxiliary unit would have a significantly reduced weight when generating scenarios, allowing for the occasional 'your artillery unit got ambushed' while making that a rare surprise while making it so the majority of your combat scenarios use actual combat-oriented forces. 

### MekHQ Suite Version *

v0.50.01

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
So, I'm not going to implement this tonight, but I wanted to jot down my thoughts:

`Auxiliary` role doesn't allow the force to be assigned as the primary force for a scenario, so they're always going to end up as reinforcements; however they won't be grabbed by StratCon on Integrated commands.

Thoughts?

**Comment by OrbMonky** [comment]
Personally I like this, sometimes I want to have an extra mech deploy to a scenario but they will be grabbed by Stratcon if left in the TOE so I have to ad-hoc new formations in TOE as needed which is tedious.

**Comment by Tempest-56** [comment]
That would accomplish the objective, I think.

**Comment by IllianiCBT** [comment]
Closing as resolved
