### ISSUE TITLE
Unit Reputation window is failling to show the total on the Support Rating section (Visual Bug)

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#5194]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

![image](https://github.com/user-attachments/assets/016e0099-249e-42da-9ea4-0d126bacf2a5)

As shown in the image, the total reputation score is correct, but the bolded section total only add up to -6, because the Support Rating penalty, although being applied, is not shown on the section's title.

### Operating System *

Windows 10

### Java Version *

Java Version: 17.0.13

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

MekHQ Logistics Overhaul artifact from 2024-11-04 with hotfix

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
