### ISSUE TITLE
Remaining time for repairs is showing wrong days left (visual bug)

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#5195]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

When repairing, the message stating the time left has the time left in minutes correctly stated, but not the days.

![image](https://github.com/user-attachments/assets/88bb9000-e899-41b0-af02-b8efae35c3d7)

The mektech working on the part has 120 free minutes, so it should (and it does) finish the next day, but the message in the daily log shows this:

![image](https://github.com/user-attachments/assets/7a98dc6d-f8f3-4a36-aa6f-1b2683ca84fa)

The repair does finish the next day, so it's working correctly.

### Operating System *

Windows 10

### Java Version *

Java Version: 17.0.13

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

MekHQ Logistics Overhaul artifact from 2024-11-04 with hotfix

### Attach Files

[logs.zip](https://github.com/user-attachments/files/17727077/logs.zip)
[5th Circle Furies29900902.cpnx.gz](https://github.com/user-attachments/files/17727079/5th.Circle.Furies29900902.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by SirChaos1** [comment]
Can confirm that this happens. If the tech would finish the repair with 0 minutes left on the day it´s finished, completion time is stated as 1 day longer than it should be - but it still completes exactly when it should.
