### ISSUE TITLE
Personnel leave unit on divorce

### ISSUE THREAD

**Issue by SirChaos1** [MegaMek/mekhq#5196]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

If a unit member (combat or support personnel) who is married to someone in the Dependant role, upon random divorce, the unit member leaves the unit and the dependant remains behind - the exact opposite of what is supposed to happen.

### Steps to Reproduce

1. Generate personnel with the Simulate Relationship History setting on
2. Run campaign until a random divorce occurs

### Operating System *

Windows 10

### Java Version *

Java 17

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0.50.01

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
