### ISSUE TITLE
MekHQ not letting create custom settings

### ISSUE THREAD

**Issue by demster42** [MegaMek/mekhq#5198]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

Created a new campaign in 50.01 and the game crashed when I set it up. 

### Steps to Reproduce

1. Set a modified date, adjust, and save the preset. Included the presents in the zipped file with the logs.

### Operating System *

Windows 11

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

50.01

### Attach Files

[logs.zip](https://github.com/user-attachments/files/17739983/logs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by repligator** [comment]
```
15:10:17,591 ERROR [mekhq.gui.dialog.DataLoadingDialog] {AWT-EventQueue-0}
mekhq.gui.dialog.DataLoadingDialog$Task.done(DataLoadingDialog.java:436) - 
java.util.concurrent.ExecutionException: java.lang.NumberFormatException: For input string: "7LA"
```

**Comment by repligator** [comment]
Closing as fixed.
