### ISSUE TITLE
Stratcon allows deployment but not use of non-combat forces

### ISSUE THREAD

**Issue by Tempest-56** [MegaMek/mekhq#5200]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

In Stratcon, when you deploy forces it gives you the option to deploy forces that are marked as non-combat on your TOE. Should the enter a combat scenario (such as an encounter when revealing an unreconned hex), the scenario will generate with the force as the seed and assigned to it. However as a non-combat force you cannot actually start the scenario as it doesn't count them as deployed. Similarly, you cannot assign a different unit to it without consuming a support point for them as reinforcements, nor can you advance the day as the incomplete scenario nag pops up.

### Operating System *

Windows 11

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Custom MekHQ Version

Snapshot as of 11/1

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
For anyone picking this up: we should be filtering out non-combat forces from this dialog.

**Comment by Tempest-56** [comment]
Oops. Apologies, I thought I _had_ attached a save. Corrected and attached.
[Alley Cats30161229.cpnx.gz](https://github.com/user-attachments/files/17807609/Alley.Cats30161229.cpnx.gz)

**Comment by IllianiCBT** [comment]
Closing as resolved
