### ISSUE TITLE
[MEKHQ 50.01] Issue with clicking Area of Operations after completing the first scenario

### ISSUE THREAD

**Issue by BiggestBoss1** [MegaMek/mekhq#5203]
### Prerequisites and Pre-Issue Checklist

- [x] I'm reporting the issue to the correct repository:
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [x] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

After the completion of the first scenario i am unable to click on Area of operations as it shows a java error or only showing the victory point conditions.

### Steps to Reproduce

Loading the save and clicking on the Area of operations tab should cause the error to trigger

### Operating System *

Windows 11

### Java Version *

Java Version: 17.0.11

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

50.01

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17790328/mekhq.log)
[problematic save.cpnx.gz](https://github.com/user-attachments/files/17790330/problematic.save.cpnx.gz)

![Capture](https://github.com/user-attachments/assets/70fc2f40-8528-4326-aec7-df69c793c3ac)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
It seems to be trying to fetch an invalid force. Did you make any changes to your TO&E after the scenario?

**Comment by BiggestBoss1** [comment]
I dont think i have,even then when i do change the force after loading the campgain save and having the TO&E lance organised again it still shows that issue,even after completing a scenario and moving on a new one that error still persists,i havent completed the mission so im unsure if it fixes itself on a new one.

**Comment by IllianiCBT** [comment]
Closing as resolved
