### ISSUE TITLE
[MEKHQ v50.01] Unit Reputation: Command Rating doesn't update Tactics.

### ISSUE THREAD

**Issue by CrushU** [MegaMek/mekhq#5205]
### Prerequisites and Pre-Issue Checklist

- [x] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

![image](https://github.com/user-attachments/assets/829d1aeb-f5d9-4d67-a3b5-fcb0fd4403cc)
This MekWarrior is flagged as Commander in the Personnel tab.
However, if I go to Reputation Report, I see the following:
![image](https://github.com/user-attachments/assets/f6b5be35-315f-4d24-a96c-406195c14186)
Leadership and Strategy are accurate, but Tactics is 2 instead of the 3 listed for the commander.
I have waited for Monday to roll around, and it did update the Leadership value.
Spoke in Discord about it, and Illiani told me to open an issue report.

### Steps to Reproduce

I have included two savefiles.
If you load the first one you can see the Unit Reputation shows a 0 for Leadership, however that is because the commander's Leadership was improved this same day.
If you load the second savefile, it's the same as the first, but time advanced until Monday, where you can see a 1 for Leadership now, but still 2 for Tactics.

First: [Holland's Berserkers30410111.cpnx.gz](https://github.com/user-attachments/files/17791823/Holland.s.Berserkers30410111.cpnx.gz)
Second: [Holland's Berserkers30410118.cpnx.gz](https://github.com/user-attachments/files/17791824/Holland.s.Berserkers30410118.cpnx.gz)

### Operating System *

Windows 10

### Java Version *

Eclipse Adoptium 17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

50.01

### Attach Files

[logs.zip](https://github.com/user-attachments/files/17791835/logs.zip)
![image](https://github.com/user-attachments/assets/c01c64ce-1209-4345-bde6-3dea7efb0cea)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Does your commander have a bonus to tactics?

**Comment by CrushU** [comment]
Yes.
As shown in the screenshot, the bonus is +3

**Comment by IllianiCBT** [comment]
Not entirely what I meant: skills can have skill levels and skill bonuses. I'll load up the save tomorrow and take a look.

**Comment by CrushU** [comment]
Costs 40XP to give more Tactics, so that should be actually 3 skill levels of Tactics. 5, 10, 20 for the three levels?

**Comment by IllianiCBT** [comment]
Note, while working on the revamp of the Reputation reported I discovered my earlier response was inaccurate. This has since been corrected in our code, so I won't be reopening this case.
