### ISSUE TITLE
Mass Repair/Salvage Window doesn't respect Monitor Size

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#521]
The Window should appear with a maximum height of whatever display it is being shown on.

0.43.5 Beta Nov11

![massrepair window](https://user-images.githubusercontent.com/16738384/32736305-1c3d49aa-c865-11e7-98d1-fcd226a5cb9b.jpg)

**Comment by sixlettervariables** [comment]
@Windchild292 while you're working on MRMS could you take a look at perhaps a scrollbar for the options area?

**Comment by Windchild292** [comment]
Already in my plan.

**Comment by Windchild292** [comment]
The baseline on this is not a bug but rather considered a standard in Java. However, I will be adding a scrollbar.

**Comment by Windchild292** [comment]
The dialog already has a scrollbar and works fine on tiny screens, closing as this is just a standard for Java.
