### ISSUE TITLE
50.01 Pirateopfor BV in large excess of my own

### ISSUE THREAD

**Issue by MrKadoodle** [MegaMek/mekhq#5219]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

Irregular force assault opfor generated with a combined BV of 17122 against my BV of 5462.

### Steps to Reproduce

Just generated a mission with the Irregular Force Assault scenario with pirates as the enemy.

### Operating System *

Windows 10

### Java Version *

20.0.1

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0.50.01

### Attach Files

[mekhq.zip](https://github.com/user-attachments/files/17808192/mekhq.zip)
![image](https://github.com/user-attachments/assets/e24452b1-eff0-406e-b1ba-c8e498e8334a)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by MrKadoodle** [comment]
Adding the latest save file since I forgot to in the post
[uhoh.zip](https://github.com/user-attachments/files/17808355/uhoh.zip)

**Comment by IllianiCBT** [comment]
Closing as resolved
