### ISSUE TITLE
[RFE] Equalizing mission VPs

### ISSUE THREAD

**Issue by Tempest-56** [MegaMek/mekhq#5221]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

Currently certain mission types - like Relief Duty or Garrison - have significantly fewer VP-critical scenarios than others and it's possible to go an entire mission with few or even zero VPs being able to be awarded. Meanwhile other types will award VPs like candy.

As the new XP defaults specifically award significant bonuses for completing a mission with 3+ VPs, this makes certain mission types undesirable while others much more rewarding. (More so, the difference is invisible to the average player as there's no indication which ones are superior.) There should probably be some form of check to ensure that any given mission at least provides the player the _opportunity_ to reach the 3 VP threshold. 

### MekHQ Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
This has potentially been resolved by #5230, but we'll need to wait until QA gets their hands on it to be sure.

**Comment by IllianiCBT** [comment]
Closing as resolved
