### ISSUE TITLE
My mechwarrior won't stop having babies :D

### ISSUE THREAD

**Issue by molemanBT** [MegaMek/mekhq#5236]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

I hired 1 mechwarrior, made her commander, made her pregnant, then sent her on an NCO course, now she keeps having a baby every week, sounds uncomfortable

### Steps to Reproduce

Just advance a week on the save

no customs
[The Matrix Investments30341215.cpnx.gz](https://github.com/user-attachments/files/17875775/The.Matrix.Investments30341215.cpnx.gz)

### Operating System *

Windows 11

### Java Version *

17

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0.50.01 (although the log, and the help > about ribbon at the top say 0.50.1)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by repligator** [comment]
[mekhq.log](https://github.com/user-attachments/files/17893730/mekhq.log)
Ran the attached campaign for another few weeks. One child per week, every week. Campaign settings show relationship-less conception at 1/2000 odds, so this almost certainly a bug. Not sure if the error in the log is related, or just a side effect.

```
10:01:04,169 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$1(MekHQ.java:291) - Uncaught java.lang.NullPointerException detected. Please open up an issue containing all logs, the game save file, and customs at https://github.com/MegaMek/megamek/issues . If Sentry is enabled, the error has also been logged.
java.lang.NullPointerException: Cannot invoke "mekhq.campaign.personnel.education.Academy.isHomeSchool()" because the return value of "mekhq.campaign.personnel.education.EducationController.getAcademy(String, String)" is null
	at mekhq.campaign.personnel.procreation.AbstractProcreation.birth(AbstractProcreation.java:370)
	at mekhq.campaign.personnel.procreation.AbstractProcreation.processNewWeek(AbstractProcreation.java:541)
	at mekhq.campaign.Campaign.processWeeklyRelationshipEvents(Campaign.java:3942)
	at mekhq.campaign.Campaign.processNewDayPersonnel(Campaign.java:3859)
	at mekhq.campaign.Campaign.newDay(Campaign.java:4262)
```
