### ISSUE TITLE
[RFE] Include commander's name in Reputation Report

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#5237]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

Something that comes up from time to time on Discord is "How do I know who my commander is", and "I don't have anyone with those listed skills" (although they likely do) when dealing with the Reputation Report.

This can be handled by listing the overall commander's name in the Reputation Report.

### MekHQ Suite Version *

v.050.0

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
