### ISSUE TITLE
50.01 Company Experience broken(?)/showing as None

### ISSUE THREAD

**Issue by poiu18894012** [MegaMek/mekhq#5238]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

![image](https://github.com/user-attachments/assets/84926631-fabe-464a-8e74-1859da0c6ac8)
Company Experience shows up as None.  Not sure why its happening.

### Operating System *

Windows 11

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

50.01

### Attach Files

[Interstellar Defense Force27780201.cpnx.gz](https://github.com/user-attachments/files/17878414/Interstellar.Defense.Force27780201.cpnx.gz)
[mekhq.log](https://github.com/user-attachments/files/17878415/mekhq.log)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
You need to include your customs folder, otherwise we are unable to investigate your issue.

**Comment by poiu18894012** [comment]
[customs.zip](https://github.com/user-attachments/files/17895693/customs.zip)
Sorry about that, customs folder added with this message.

**Comment by IllianiCBT** [comment]
Can I verify whether all your personnel are _meant_ to be 0/0? Wanting to verify whether that's a loading error or intentional.

**Comment by poiu18894012** [comment]
Yes, I used the mass training + exp to get everyone who wasnt 0/0 to 0/0

**Comment by IllianiCBT** [comment]
Closing as resolved

**Comment by IllianiCBT** [comment]
The current workaround is to not have characters with negative skill target numbers.
