### ISSUE TITLE
Can't load Campaign Save, Parsing Error

### ISSUE THREAD

**Issue by aherrera305** [MegaMek/mekhq#5249]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

Go to load save file that worked in 0.49.14 to continue in latest milestone version, 0.49.19.1, and get a failure to load/parsing error. See attached screenshots and log. Even trying to load the game in 0.49.14 is creating the same error.
0.49.19.1 Log > [mekhq.log](https://github.com/user-attachments/files/17909375/mekhq.log)
![image](https://github.com/user-attachments/assets/7f944591-ff07-4da6-9a4b-02af21301b2c)
![image](https://github.com/user-attachments/assets/0253de26-16d2-4ab5-ac5e-ce6812bb7425)

### Steps to Reproduce

1. Launch Megamek 0.49.19.1
2. Load campaign
3. Errors above

### Operating System *

Windows 11

### Java Version *

11.0.19

### MekHQ Suite Version *

v0.49.19.1

### Attach Files

[logs.zip](https://github.com/user-attachments/files/17909436/logs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by repligator** [comment]
Could you please post the save file for the campaign in question, thanks.

**Comment by IllianiCBT** [comment]
So the issue seems to be that MekHQ is failing to parse the save's version number, because it's blank - presumably because it predates us storing that information.

Without a copy of your save, though, this is going to be impossible to investigate.

**Comment by IllianiCBT** [comment]
It's been a couple of weeks and no save has been provided. Without a save it is impossible to investigate this issue or to provide a workaround.

Closing: unable to investigate.
