### ISSUE TITLE
Available Time for Mothball Not Calculating Correctly

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#525]
0.43.5

If a Tech has a Secondary Role such as Mechanic/Mech Tech time available for Mothballing a unit is calculated as base 240 minutes.

CPNX, Customs, and Screen Shots attached
[Mothball Bug.zip](https://github.com/MegaMek/mekhq/files/1478946/Mothball.Bug.zip)

**Comment by neoancient** [comment]
The tech was still performing maintenance tasks. In addition to suspending maintenance tasks during mothballing/activation I added a confirmation dialog for any tech that has assigned units to inform the user that they will be unmaintained until mothballing or activation is complete.
