### ISSUE TITLE
Dead pilot automatically replaced by live pilot upon scenario resolution in MekHQ, and live pilot is already assigned to mech. Pilot now assigned to two mechs and unassigning doesn't stick.

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5256]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

I lost a pilot to death by skin of teeth optional rule ejection after a fatal medium laser hit to the cockpit. Upon resolving the scenario, the mech assigned to the dead pilot now is assigned to another pilot of the same mech type/refit, in this case the Wolverine 'Breaker B'. I name them to help keep track of their service, and the dead pilot was from the one named 'C' and the now double-assigned pilot is from the one named 'B'.

I cannot remove the alive pilot from the mech that they are erroneously assigned to easily, I had to restart, remove the mech from TO&E, remove pilot from all units in personnel, and remove pilot from both mechs in hangar, and restarted again to ensure it stuck. Before resolving, even mothballing showed the weird erroneous assignment which shouldn't be possible, and they showed on the TO&E in both Support Company > Lead Lance and Support Company > Support Lance under my Lead Battalion entry.

### Steps to Reproduce

Lose pilot in megamek due to skin of teeth ejection from head damage while having a non deployed pilot in a matching mech, resolve scenario, new pilot showed up in both 'mechs and was hard to remove.

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Attach Files

[files.zip](https://github.com/user-attachments/files/17942178/files.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by OrbMonky** [comment]
The pilot in question is Ilona "M8" Shilling, pilot of the wolverine 'Breaker B' #3 - C
She also shows for 'Breaker B' #2 - B
![image](https://github.com/user-attachments/assets/4e94566b-dd9e-4435-9b7f-85958f2667ea)
Here is a screenshot of the save before the battle;
![image](https://github.com/user-attachments/assets/44d339b0-520f-4d25-8a71-690b8fbc60fe)
Here is the save prior to the battle and the mul
[files2.zip](https://github.com/user-attachments/files/17942232/files2.zip)

**Comment by DM0000** [comment]
Can you post the log?

**Comment by OrbMonky** [comment]
They should be in the files.zip or files2.zip, is there a specific one I'm missing?

**Comment by HammerGS** [comment]
> They should be in the files.zip or files2.zip, is there a specific one I'm missing?

Just checked both and between them they have everything but the logs.

**Comment by OrbMonky** [comment]
Ok, I see what happened. It didn't include the log files because the program was open so they were 'in use' it seems... ugh. Looking at their contents it seems to just be maintenance rolls from last night well after the time when this occurs.

**Comment by psikomonkie** [comment]
Interesting, In the save file, the Wolverine having this issue has two gunners. Looking at the autosave in files2.zip from Jan. 26, the Wolverine has Ilona M8 Schilling as the 2nd gunner for the wolverine. Even after manually resolving the scenario and assigning a new pilot, that new save still has Ilona M8 Schilling listed as the 2nd gunner for the Wolverine.

**Comment by OrbMonky** [comment]
I have no idea what could even cause that, I'm fairly sure I reassigned both of these pilots after fully unassigning them from their previous rides this contract. Bizarre.

**Comment by IllianiCBT** [comment]
Is it possible that we're not clearing the old pilot/gunnery data somewhere?

**Comment by psikomonkie** [comment]
Hey @OrbMonky , would you be able to provide a save from before March 29 3030 (30300329)? That's the date Ilona was reassigned from the Mek showing this bug to their current Mek. I'm curious when this bug was first introduced to your save. Thanks!

**Comment by OrbMonky** [comment]
Unfortunately my campaign also has another bug that is apparently a divide by zero attempt based on an invalid armor type for support vehicles that somehow got assigned. I can only go back as early as May 4 3030. Bit of a perfect storm :(
