### ISSUE TITLE
[50.02-Nightly 1691] FG3 issues

### ISSUE THREAD

**Issue by ussdefiant60** [MegaMek/mekhq#5262]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

i have a save and log here for two scenarios that have some screwed up force generation going on.

1)
a) For the Engagement Scenario, i have 3 Medium/Heavy Meks + Allies going up against a single Manitcore. Eyeballing the log suggets that 2 lances were generated as the Opfor, all but the Manticore were culled out of the second lance, but the first lance never actually got added to the mission.

b) Looking at this bit in the log suggests that the Force BV Multiplier is not adjusting the Seed Force BV properly:
`mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForce(AtBDynamicScenarioFactory.java:449) - Force BV Multiplier: 0.5 (from scenario template)

12:05:49,863 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.generateForce(AtBDynamicScenarioFactory.java:459) - BV Budget was 4988, now 2494 (includes Modifier settings and Multiplier)

12:05:49,892 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.calculateEffectiveBV(AtBDynamicScenarioFactory.java:2855) - Total Seed Force Generic BV: 4988

12:05:49,892 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.calculateEffectiveBV(AtBDynamicScenarioFactory.java:2872) - Capellan Confederation Integrated Allies Generic BV: 1729

12:05:49,892 INFO  [mekhq.campaign.mission.AtBDynamicScenarioFactory] {AWT-EventQueue-0}
mekhq.campaign.mission.AtBDynamicScenarioFactory.calculateEffectiveBV(AtBDynamicScenarioFactory.java:2876) - Total Base Generic BV Budget: 6717 (adjusted for campaign difficulty)`

c) I'm not sure the BadEvent/ArmedNArmored modifiers are actually doing anything here.

2) The Frontline Engagement scenario is also screwed up, with precisely none of the 2 lances apparently generated actually making it into the Opfor. Also, should those Tank Reinforcements have 3 full platoons of infantry? Only see one vehicle i could call an APC.

### Operating System *

Windows 11

### Java Version *

Java 17 Adoptium

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

50.02 Nightly 1691

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17966624/mekhq.log)
[The 5th Cipher Infrastructure30420207.cpnx.gz](https://github.com/user-attachments/files/17966625/The.5th.Cipher.Infrastructure30420207.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Marking this as resolved; however once the above PR is merged we'll want to keep an eye on this to ensure this bug doesn't re-appear.
