### ISSUE TITLE
Valid lances being flagged as overweight/not detected as StratFors

### ISSUE THREAD

**Issue by jslater89** [MegaMek/mekhq#5265]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

The lances in the attached save file are relatively ordinary 4-mech forces between about 200 and 300 tons, but aren't available as strategic forces if the 'limit lance deployments by weight' option is checked. (If that option is checked, they are detected as strategic forces, but all have the 'super heavy' weight class in the 'current assignments' table on the briefing room tab.

### Operating System *

Linux

### Java Version *

17.0.13

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

v0.50.02-SNAPSHOT (11/30 nightly)

### Attach Files

[logs.zip](https://github.com/user-attachments/files/17967287/logs.zip)
[customs.zip](https://github.com/user-attachments/files/17967289/customs.zip)
[The Opinionated Bastards30540206.cpnx.gz](https://github.com/user-attachments/files/17967290/The.Opinionated.Bastards30540206.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Already resolved in #5263.

Closing: resolved
