### ISSUE TITLE
[RFE] Instant Mass Repair for damaged components in warehouse

### ISSUE THREAD

**Issue by LadyAdia** [MegaMek/mekhq#5267]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

An option to use instant mass repair for components in the warehouse would be very helpful after a large batch of stripping salvaged components from units.

### MekHQ Suite Version *

v0.50.01

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by repligator** [comment]
If I understand the request correctly, this feature is actually already implemented. If you right click on a damaged part in the warehouse, you can select Mass Repair.

**Comment by LadyAdia** [comment]
I had never seen that option before now. Thank you for the feedback. I'll close this RFE.
