### ISSUE TITLE
[v0.50.01] Incorrect lances being pulled into scenarios in subcontract

### ISSUE THREAD

**Issue by LadyAdia** [MegaMek/mekhq#5269]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

 I'm in a garrison contract and I took up a short relief subcontract with integrated command that only needed one lance. I assigned one of my assault lances to it and left the rest on the garrison duty, but it seems to be really common for lances not assigned to the subcontract to be deployed on scenarios despite how I have my assignments set.
Example: Lance assigned to Contract A is pulled into a scenario in Subcontract B. 

Included in the attached .zip file is my user files, custom builds, MekHQ log, current save file with the notification of the deployment, and my previous autosaves from the days leading up to the point the scenario generated.

[MHQ Contract Bug 2024-12-01.zip](https://github.com/user-attachments/files/17970633/MHQ.Contract.Bug.2024-12-01.zip)

### Steps to Reproduce

1. Accept garrison contract
2. Accept subcontract with integrated command
3. allow a scenario to generate. Deployed lance bat be one not assigned to the subcontract.

### Operating System *

Mac

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0.50.01

### Attach Files

[MHQ Contract Bug 2024-12-01.zip](https://github.com/user-attachments/files/17970636/MHQ.Contract.Bug.2024-12-01.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
