### ISSUE TITLE
[RFE] Expand upon the 'Maximum Lances' requirement of HQ

### ISSUE THREAD

**Issue by RaozSpaz** [MegaMek/mekhq#5275]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

This RFE is being posted by @IllianiCBT request

Thanks to discussion in the MekHQ section of the discord between Kaatapholt, Illiani, and myself in relation to a prior posted PR about reinforcement times. The topic came up that not all contracts should require all of the players lances. Representing that not every battlefield is of an intensity requiring the entirety of the mercenary's forces. Primarily this would allow players opportunities to take less intense engagements [at an equally less pay cut]. 

### MekHQ Suite Version *

Mek HQ V 50.01

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
This has already been resolved. I must have missed closing this PR.

Closing as resolved
