### ISSUE TITLE
[RFE] Add Primitive Rocket Launchers for external ordinance

### ISSUE THREAD

**Issue by LadyAdia** [MegaMek/mekhq#5278]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

Per conversation on Discord this morning: [Discord](https://discord.com/channels/458705327911731231/458706545379639296/1313150508332220440)

It was suggested that adding Primitive Rocket Pods as external ordinance may help alleviate the long-standing complaint about Princess using excessive rocket pods in ASF battles without players having the same option available.

### MekHQ Suite Version *

v0.50.01

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
@Sleet01 was this resolved by your recent rocket launcher changes? Can it be closed, or is it still a concern? :)

**Comment by LadyAdia** [comment]
It's fixed now. Closing as resolved.
