### ISSUE TITLE
MHQ suddenly unable to load saves dated after 11/12, these saves were able to be loaded over the last two weeks and suddenly cannot be loaded

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5285]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

I have encountered an issue where every save from 11/13 onward is unable to load, however 11/12 and prior are able to load without issue. I was able to use saves from the 13th and onward without issue until yesterday, nothing changed on my PC to cause any apparent problem. I have since uninstalled and reinstalled Java in accordance with recommended guidelines and set up a second install of MekHQ to see if something had become corrupted but neither resolved it. I am attaching a working and several non-working saves as well as my customs and other files to help isolate/resolve this issue.

I have also noticed that it is causing strange behavior of Java, not terminating properly. The issue does not resolve after closing these redundant instances of java nor after reboot, and this behavior was observed prior to and after the reinstall of Java when triggering this failure to load.
![image](https://github.com/user-attachments/assets/44b81016-9f68-41d3-a4e0-d87d44082f11)

When attempting to load any of the affected saves, this is what is received
![image](https://github.com/user-attachments/assets/595b3218-7ffc-464b-845c-2485becba1ab)

I have included saves from 11/12 and 12/3, the 11/12 works on my machine but it is the last one that works.
This loss of progress represents ~12 months of in game progress. I have included the other affected saves if more examples are needed in additional zips due to the 25 mb limit. As long as the latest save can be recovered that is enough to salvage my campaign, but this is a very odd issue that seems to have retroactively broken previously working saves so I am throwing in the kitchen sink. Let me know if anything else is needed.

The MekHQ log, customs, and 'working' and latest 'broken' save files are in the gamebreaker.zip file.

[gamebreaker.zip](https://github.com/user-attachments/files/17995847/gamebreaker.zip)
[brokensaves.zip](https://github.com/user-attachments/files/17995886/brokensaves.zip)
[brokensaves2.zip](https://github.com/user-attachments/files/17995915/brokensaves2.zip)
[brokensaves3.zip](https://github.com/user-attachments/files/17995942/brokensaves3.zip)
[brokensaves4.zip](https://github.com/user-attachments/files/17995961/brokensaves4.zip)

### Steps to Reproduce

I have no idea how to reproduce it, only that it is present. I've never seen an issue retroactively break previously working saves before.

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by DM0000** [comment]
Can you post the logs?

**Comment by IllianiCBT** [comment]
I've tracked down the issue. Will work to see what I can do to fix it.

**Comment by IllianiCBT** [comment]
I'll try and get the above PR merged into tonight's nightly. This case will be closed automatically when that happens, so keep an eye on your email inbox.

**Comment by OrbMonky** [comment]
Is it possible to move to the new nightly mid-contract? I'm on a long garrison + now two subcontracted security contracts. Should I just close those out and say 'mission successful' ?

**Comment by IllianiCBT** [comment]
I would recommend so, if you're updating from 50.0 -- a lot has changed in 50.01 and 50.02 is still mid-development, so it's not worth the risk.
