### ISSUE TITLE
Supply Convoy assigned as a force needing to be preserved during a Frontline Engagement despite not being in the battle

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#5288]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

An enemy contact appeared on the AoE map. I assigned my one and only combat lance. After completing the battle, I was puzzled. The preserve allies objective (showing just a single friendly mek) was colored red, and would not switch to green even if checked and unchecked.

I didn't figure out why until I was writing up the issue. My Supply Convoy was listed under the Preserve 50% objective, even though they weren't partaking in the mission. The Supply Convoy did not appear in the actual MM game, nor do they appear in the gamelog nor entitystatus.

![Screenshot_20241203_152528](https://github.com/user-attachments/assets/81762e36-cdc2-44ed-9b83-ff61be16d349)

### Steps to Reproduce

I don't know. I'm going to continue with this campaign and see if it happens again. I've attached MM as well as MHQ saves/logs in case it matters.

### Operating System *

Linux

### Java Version *

17

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

https://github.com/MegaMek/mekhq/commit/b0dc5e1f60817e2f84996e554fb4f5ba75a3a222

### Attach Files

[megamek.log](https://github.com/user-attachments/files/17998671/megamek.log)
[mekhq.log](https://github.com/user-attachments/files/17998677/mekhq.log)
[entitystatus.txt](https://github.com/user-attachments/files/17998680/entitystatus.txt)
[Autosave-1-IS Logistics-30690110.cpnx.gz](https://github.com/user-attachments/files/17998688/Autosave-1-IS.Logistics-30690110.cpnx.gz)
[IS Logistics30690114.cpnx.gz](https://github.com/user-attachments/files/17998689/IS.Logistics30690114.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Unfortunately, with the scenario resolved it's not possible to fetch information from it that would be needed for this investigation. Potentially the upcoming scenario generation changes may fix this, inadvertently, so once they're merged we should keep an eye out to see if this happens again. If it does, make a save prior to undertaking the scenario so I can take a look at the scenario's internals.

**Comment by repligator** [comment]
Loaded/Reloaded a Sunday save until I got another erroneous battle. Same as last time the supply convoy is needs to be preserved despite not being a part of the mission.
[IS Logistics30690111.cpnx.gz](https://github.com/user-attachments/files/17999164/IS.Logistics30690111.cpnx.gz)

**Comment by IllianiCBT** [comment]
Perplexing. I'll take a look

**Comment by IllianiCBT** [comment]
Ok, I see what's happening here. When we generate a scenario we pick a seed force, that force isn't assigned to the scenario but we use it to determine scenario objectives. In these instances it appears that 'Supply Convoy' is the seed force, hence it appearing in the objectives. If you were playing an Integrated contract 'Supply Convoy' would have been the force assigned to the scenario.

This isn't so much a bug as an implementation we should probably review. I'll have a think and see if I can come up with a reasonable solution.

**Comment by IllianiCBT** [comment]
Closing as resolved
