### ISSUE TITLE
Missing map tile

### ISSUE THREAD

**Issue by BTSS88** [MegaMek/mekhq#5299]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

Missing map tile in the Area of Operation
![Screenshot 2024-12-05 104308](https://github.com/user-attachments/assets/e7484479-0367-4786-a728-876bbc1e98cb)

### Steps to Reproduce

Load save. 

### Operating System *

Windows 11

### Java Version *

17

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

50.01

### Attach Files

[logs.zip](https://github.com/user-attachments/files/18015426/logs.zip)
[Musket's Emergency Contractors30611107.cpnx.gz](https://github.com/user-attachments/files/18015428/Musket.s.Emergency.Contractors30611107.cpnx.gz)
[customs (2).zip](https://github.com/user-attachments/files/18015429/customs.2.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
The save you uploaded is from after the contract concluded

**Comment by BTSS88** [comment]
Oh my bad, I picked the top save file without realizing it was sorted in reverse order. Here's the current one. 

[Musket's Emergency Contractors30630213.cpnx.gz](https://github.com/user-attachments/files/18030829/Musket.s.Emergency.Contractors30630213.cpnx.gz)

**Comment by IllianiCBT** [comment]
I'm really sorry I'm only just getting back to this, but your customs folder appears to be missing a bunch of units:

<img width="570" alt="image" src="https://github.com/user-attachments/assets/9089697e-2c21-4996-b305-f2060332f939" />

I don't suppose you can upload an updated archive?

**Comment by IllianiCBT** [comment]
Closing as resolved
