### ISSUE TITLE
Convoy bot forces contain all/too many military units

### ISSUE THREAD

**Issue by BTSS88** [MegaMek/mekhq#5302]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

Convoy intercept missions keeps generate full military assets for the convoy bot force. It's either full on mech/tank or one type of recovery truck. I'm no longer seeing civilian mechs/trucks like in 50.00. Regenerating forces doesn't help either. 

### Steps to Reproduce

Load save. 

### Operating System *

Windows 11

### Java Version *

17

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

50.01

### Attach Files

[logs.zip](https://github.com/user-attachments/files/18016350/logs.zip)
[Musket's Emergency Contractors30630209.cpnx.gz](https://github.com/user-attachments/files/18016365/Musket.s.Emergency.Contractors30630209.cpnx.gz)
[customs.zip](https://github.com/user-attachments/files/18016371/customs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by RaozSpaz** [comment]
I have also encountered this happening in personal games. My last convoy mission was a Hunchback and a Firestarter. I havent seen an SV or IM in a long time.

**Comment by IllianiCBT** [comment]
Closing as resolved
