### ISSUE TITLE
[50.02-LOGI] NPE on month turnover, apparently related to logistics/convoy.

### ISSUE THREAD

**Issue by ussdefiant60** [MegaMek/mekhq#5303]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Advanced Day from June 31st to July 1st in the first month of a new contract. Had a message box pop up about a NPE. No convoy/logistics messages came up. Log file shows resupplyAndCaches in the trace. Log/Save attached

### Operating System *

Windows 11

### Java Version *

Java 17 Adoptium

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Logistics Artifact 4497

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/18017847/mekhq.log)
[The 5th Cipher Infrastructure30420701.cpnx.gz](https://github.com/user-attachments/files/18017854/The.5th.Cipher.Infrastructure30420701.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
