### ISSUE TITLE
[LOGISTICS] Campaign tries to summon cthulhu (or maybe it's a swing error when displaying shares in the briefing tab)

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#5308]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

The contract description in the briefing tab looks like this:

![image](https://github.com/user-attachments/assets/df4e59bf-7fa1-46fc-b801-e8cfb1f647b6)

...and it probably should not.

### Operating System *

Windows 10

### Java Version *

Java Version: 17.0.13

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

MekHQ Logistics Overhaul artifact from 2024-12-04

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Please remember to always include a save illustrating the issue. It means we don't have to create the issue manually, which takes time better spent on fixing the issues.

**Comment by IllianiCBT** [comment]
Closing as resolved
