### ISSUE TITLE
Ranks that include a comma yeet the part following the comma into the next column, knocking the rank that is there a column over as well.

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5312]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

When setting up a new campaign, I decided on some ranks that included commas.

The format I set up was Chosen, Nth Rank, ie; Chosen, 1st Rank, Chosen, 2nd Rank - etc.

After saving and creating my shiny new company, this is what the rank structure looked like;

![image](https://github.com/user-attachments/assets/169977dd-cbc7-482d-b16d-fb5d08a0653c)

It seems there is an issue where it is not treating separators like commas *within* the rank structure as separate from the commas it uses AS separators to keep the ranks sorted appropriately.

[ranks.zip](https://github.com/user-attachments/files/18032213/ranks.zip)

### Steps to Reproduce

1. Create a rank schema where a rank has a comma in the rank's title (ie: This, Rank).
1. Save the rank structure.
3. Start a campaign with the rank structure.
4. Generate personnel of the appropriate type.
5. Try to assign the rank.
6. Review ranks in campaign options.

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
So this is a format requirement, rather than a bug. When setting up a custom rank you are required to break with a `,`, which unfortunately means you cannot then use `,` in your rank names.

Closing, but I do appreciate the frustration.
