### ISSUE TITLE
Implemented Resupply Module #4497 - Mass Training becomes unavailable due to being able to lower Target skill level to 0, becomes unrecoverable without loading an earlier save.

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5317]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

I can no longer adjust the target skill level above 0 after having accidentally clicked one time too many, changing things in the drop downs, closing the drop down and reopening, closing and reopening the mekhq client do not resolve. I could not find anything in the campaign file pointing in an obvious way to where this variable is stored either.

![image](https://github.com/user-attachments/assets/a95f4390-d79a-49d7-9560-170555dc806c)

While it's amusing to imagine my admins on strike, it's hopefully an easy fix.

### Steps to Reproduce

1. Open Mass Training dialogue
2. Press down arrow on target skill level until it reads 0

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

Implemented Resupply Module #4497

### Attach Files

There are no customs in this install
[Hel's Vanguard30221223.cpnx.gz.zip](https://github.com/user-attachments/files/18049663/Hel.s.Vanguard30221223.cpnx.gz.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by OrbMonky** [comment]
Correction: Even loading an earlier save doesn't restore functionality. I had mistakenly assumed that it would. Wherever this variable is stored it appears to be global. I loaded an earlier save, gave a green soldier 100 xp to ensure it had someone to pull from, and it is still not adjustable.
![image](https://github.com/user-attachments/assets/6867b6b2-b087-49a9-92b0-5c2469a63fb5)

**Comment by IllianiCBT** [comment]
Closing as resolved
