### ISSUE TITLE
[RFE] Unit's quality decline message should have the bad event colour

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#5322]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

The quality decline message in the Daily Log has the same colour as the quality improvement message.

![image](https://github.com/user-attachments/assets/b0a146e9-6e79-42c1-90d9-2c6de1272869)

Logic would assume this to be a bad event, and so, should appear with the corresponding colour.

### MekHQ Suite Version *

MekHQ Logistics Overhaul artifact from 2024-12-06

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
