### ISSUE TITLE
Implemented Resupply Module #4497 - VIP Defense doesn't add the defended unit to the resolution objectives upon completing the mission, and does not list an objective to defend the VIP in the after-action report

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5323]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

![image](https://github.com/user-attachments/assets/ee3a43f4-39f6-425c-ad29-7b4547bc45a2)

VIP Defense doesn't add the defended unit to the resolution objectives upon completing the mission, and does not list an objective to defend the VIP in the after-action report. I don't have a save where this was recorded, but it should be reproducible or visible on evaluation of the mission structure.

### Steps to Reproduce

1. Be on a contract that can generate a VIP defense
2. Observe mission objectives
3. Complete VIP defense
4. Observe resulting scenario completion dialogue/after action report

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

Implemented Resupply Module #4497

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
