### ISSUE TITLE
 Implemented Resupply Module #4518  - MissingFormatArgumentException detected upon mission auto-resolve due to morale becoming Routed on Pirate Hunting mission

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5325]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

![image](https://github.com/user-attachments/assets/34c70d31-e345-4da3-9911-94554877be8d)
Appears to have not correctly closed out the mission/contract
![image](https://github.com/user-attachments/assets/7dc7fdb4-5220-47d6-8511-954835886b5c)
[logs.zip](https://github.com/user-attachments/files/18056481/logs.zip)
[Hel's Vanguard30240301.cpnx.gz.zip](https://github.com/user-attachments/files/18056492/Hel.s.Vanguard30240301.cpnx.gz.zip)

### Steps to Reproduce

1. Pirate Hunting mission in progress
2. Opfor Morale crumbles to Routed
3. Error immediately encountered

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

Implemented Resupply Module #4518

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by OrbMonky** [comment]
Received another one, this one on a new year
![image](https://github.com/user-attachments/assets/dfc2d396-1726-4e15-8390-462983dd5a58)

**Comment by IllianiCBT** [comment]
It’s almost certainly the same cause. Will be fixed tomorrow

**Comment by OrbMonky** [comment]
The interesting part is the failure to move to Jan 1st - it processed the new years events like planets being renamed but kept it displayed as dec 31st, only shows correctly upon reloading. Maybe not worth investigating because it only happens due to something that's changing, but thought it was worth a note

**Comment by IllianiCBT** [comment]
Closing as resolved
