### ISSUE TITLE
Implemented Resupply Module #4518 - Null Pointer error when reinforcing an embattled supply convoy with a single Aero unit

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5330]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Received the attached NPE the second I committed the AeroForce, unable to discern its impact but it seemed to succeed in the reinforcement roll.

Included both post-event and pre-even file, day probably needs to be re-advanced until the convoy battle rolls again to reproduce.

### Steps to Reproduce

1. Have an embattled convoy
2. Attempt to reinforce with a single Aero unit in a formation that is set to always be a strategic force, reinforce from Stratcon AO panel.
3. NPE presents instantly.

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

Implemented Resupply Module #4518

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Missing logs, campaign file, customs folder

**Comment by OrbMonky** [comment]
Arg, here you go. No customs folder. Contains the campaign files as well as logs.

[logs.zip](https://github.com/user-attachments/files/18068085/logs.zip)

**Comment by OrbMonky** [comment]
I also note this appears at the bottom;
![image](https://github.com/user-attachments/assets/44c0b6a0-5761-403b-ada8-ecbef364f3da)

**Comment by OrbMonky** [comment]
Issue also occurred when reinforcing an additional 'mech lance with no special strategic force designation, just a default setup for the formation.
[logs.zip](https://github.com/user-attachments/files/18068128/logs.zip)

**Comment by IllianiCBT** [comment]
So after a lot of digging, I've discovered this is a bad interaction between Supply Convoys and Combat Teams. Looking into a fix now.

**Comment by IllianiCBT** [comment]
Closing as resolved
