### ISSUE TITLE
[RFE] Reduce Identity Fraud; Have personnel fully generate before placement in hiring hall/personnel market as they sometimes change name due to marriage/divorce

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5333]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

This recruit showed up and I said welcome aboard;
![image](https://github.com/user-attachments/assets/2196cebe-096d-4a9b-95c3-fdca4d788b7d)

Everything checked out during processing;
![image](https://github.com/user-attachments/assets/e39bde4f-52d0-46d6-9f4a-10724091c3ad)

Clicking on their name in the daily log to go assign them their rank however;
![image](https://github.com/user-attachments/assets/deb3ddf8-f288-4763-90da-41a7d84fd58b)

![image](https://github.com/user-attachments/assets/1aa65ea3-a5e1-40ca-bea3-75509c4dea8d)

Seems like it generates AFTER adding to campaign, rather than before, minor issue/confusion point, but probably better to go ahead and do it before for better clarity for the end user.

### MekHQ Suite Version *

Implemented Resupply Module #4518

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
I’m not sure we *can* do it before, as I don’t think the character exists prior to hiring

**Comment by JonhyBurner** [comment]
How about having them keep their surnames when marrying? It would remove this confusion, regardless of marriage situation.

**Comment by psikomonkie** [comment]
Hey! I proposed a PR that'll change the display in the activity log to 
`"[First Name] [New Last Name] (Formerly [Old Last Name]) has been added to the personnel log."`
This should make it more clear that the personnel's name changed when simulating their history and provide a connection between the name the user saw in the hiring window and the name the personnel now has.
