### ISSUE TITLE
Implemented Resupply Module #4518 - Admins stopped procuring indefinitely even in high parts availability zones, don't seem to make checks

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5334]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

Uncertain of the cause, but my admins have stopped procuring. Targets are not impossible and admins are available, at best I can guestimate it happened when I started using a supply convoy. Procurement doesn't happen in or out of contract now, and even with Campaign Parts Availability 4 nothing happens. I have gone to the lengths of removing all requested procurements, saving, closing, restarting, and requesting them again and still nothing.

![image](https://github.com/user-attachments/assets/2c93b3cf-d7ca-4528-a4e2-5ab9ce015b58)
![image](https://github.com/user-attachments/assets/bd1e413e-f249-4a78-ac9a-13f918dc05f0)

### Steps to Reproduce

Uncertain, but suspect;
1. Assign/use supply convoy
2. Have/make an acquisition request from the parts market
3. Watch as the admins sit on SpaceBook and post MekToks.

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

Implemented Resupply Module #4518

### Attach Files

[logs.zip](https://github.com/user-attachments/files/18083497/logs.zip)
Campaign File and MekHQ log included, no campaign customs

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by OrbMonky** [comment]
Ok, this seems to have been due to allied procurement only with a merc faction setup, but I had no reason to set allied procurement only... not sure how THAT happened but this did resolve it.

**Comment by repligator** [comment]
I'm going to close this as resolved for now, please feel free to reopen this issue, or make a new one if you feel it has been closed erroneously.
