### ISSUE TITLE
[RFE] Improve assignment selector box for force assignments in stratcon

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5344]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

![image](https://github.com/user-attachments/assets/107f4c60-f2dd-44dd-a27d-28f6da9d8d13)
We could really use more information here such as; units in the selected item, condition of the units in the selected item (pilot/vehicle damage etc), a generally larger box default size to accommodate this, and scaling larger by default vertically to minimize unnecessary scrolling. If possible, removing it as a pop up and making it a box or tab on the rightward pane would be preferable as the pop ups usually show up at a weird scale/have other odd issues in MekHQ.

### MekHQ Suite Version *

12/6 logistics artifact

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
