### ISSUE TITLE
12/6 logistics artifact: Two assignment windows popped up for Stratcon force assignment

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5345]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

![image](https://github.com/user-attachments/assets/bce0d384-2404-4036-ad33-7e7227e7b0c4)
Never seen this before, when I try to activate the assignment window, both of these pop up. This may be handleable in the RFE I filed by removing pop ups altogether and having a dedicated area. The one on the left works for assignment but the one on the right is uninteractable in this scenario.

[logs.zip](https://github.com/user-attachments/files/18116429/logs.zip)

Campaign save, mekhq log, customs included

### Steps to Reproduce

Issue presented when right clicking to assign forces to the mission

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/6 logistics artifact

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by OrbMonky** [comment]
Upon reloading, this was no longer present, but only the smaller low-info version of the window came up when assigning the forces.

**Comment by IllianiCBT** [comment]
OK! Another weird setup. This will occur if you following these steps:
- right-click on any hex containing a facility or nothing, select 'Manage Force Assignment'
- Don't close the force assignment dialog. Instead, right-click on any hex containing a scenario and then select 'Manage Scenario'. You will now have two dialogs open.

This occurs because Manage Force Assignment and Manage Scenario are different dialogs, so they don't automatically replace each other.

**Comment by IllianiCBT** [comment]
Closing as resolved
