### ISSUE TITLE
12/6 logistics artifact - 'Engage any hostile units for the specified number of turns' objected populated 'null' turns

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5348]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

"Engage targets for x turns" did not populate an amount of turns
![image](https://github.com/user-attachments/assets/c9019725-e5fb-4193-8bc2-217aa3149865)
![image](https://github.com/user-attachments/assets/f58fd6e8-2557-4cb3-86c0-541b80ea26cf)
[logs.zip](https://github.com/user-attachments/files/18117836/logs.zip)

### Steps to Reproduce

1. Receive specified modifier on scenario
2. Check if it has a value or null for number of turns.

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/6 logistics artifact

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
I’m guessing this is an error in the x turns algorithm so that it’s not counting Turrets as units when counting. I am curious where that random ‘1%’ has come from.

**Comment by OrbMonky** [comment]
I think 1% is visible even in 50.00, it seems to work like 'engage at least one unit' because that would in most cases be 1% (obviously if you have 101 enemy units or more in the objective this wouldn't work, but hopefully that doesn't happen?)

**Comment by IllianiCBT** [comment]
I’ll need to take a look and see what the root issue is. The way this objective should work is that you just need to do the scenario for x turns, not specifically engage y% for x turns. So my money is on something being wonky under the hood.

**Comment by IllianiCBT** [comment]
Do you have a save with the effected scenario? On the provided save the only available scenario is `Frontline Engagement` which doesn't have this objective.

**Comment by IllianiCBT** [comment]
Or, at a minimum, the name of the affected scenario

**Comment by OrbMonky** [comment]
It was the Data Center - Hostile - Engage from 09-14, I only have after resolution and the autosave before it was generated, I'll try to reload it to generate

**Comment by IllianiCBT** [comment]
I'm adding in some safeguards to hopefully prevent this from happening again.

**Comment by OrbMonky** [comment]
Took about 50 tries to generate another 'engage', but it had the amount of turns specified. May be a transient error.

**Comment by IllianiCBT** [comment]
Closing as resolved
