### ISSUE TITLE
12/6 Logistics Artifact - Dropship Engage mission populates with no dropship in the objective

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5349]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

![image](https://github.com/user-attachments/assets/46ce616e-6c04-4480-8944-a3c11fb72b4f)
[logs.zip](https://github.com/user-attachments/files/18118269/logs.zip)
![image](https://github.com/user-attachments/assets/7d217ddf-e8af-478f-9df9-5dac9931d4bb)

Missing the hook-in of the dropship to the briefing screen which typically means it also doesn't register as an objective on the mission debrief

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/6 logistics artifact

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
I’ll need to investigate, but there is a good chance this has already been fixed, just waiting on a merge

**Comment by IllianiCBT** [comment]
This should be fixed by #5338. Closing as resolved
