### ISSUE TITLE
12/6 Logistics artifact - OutOfBounds error when checking mechs with battle damage pre-generated condition

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5350]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

Was able to push past it, but may indicate a deeper problem or just be trivial;
![image](https://github.com/user-attachments/assets/0804ff28-97a2-48fd-b3c7-dcdb9e653fbd)
![image](https://github.com/user-attachments/assets/2d243715-c777-40bf-9b9f-84a45bb66beb)
[logs.zip](https://github.com/user-attachments/files/18118314/logs.zip)

### Steps to Reproduce

1. Generate mission with battle damaged forces modifier
2. Right click on an expanded force list and click edit unit
3. OOB error presents

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/6 logistics artifact

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
So, I'm not entirely sure _how_ but you managed to access index -1 -- which understandably threw an error as this should only happen if nothing has been selected. Unfortunately, an error I'm unable to replicate. Do you remember there being anything odd happening around the time of the error?

Given the sheer volume of weird one-off errors you've been getting recently, though, I do think you'd be wise to reinstall the suite at this point. While I don't doubt the veracity of your reports, your mhq install does seem to be collapsing around you at a rate of knots. Do you have it installed to a protected folder, or a cloud-sync'd folder by chance?

**Comment by OrbMonky** [comment]
I was thinking the same re: reinstalling, but I've already reinstalled once. I've also cleared out and reinstalled Java prior to that reinstall. This contract is concluding so I'll do it then. I don't have any odd system/setup stuff, it's on a bog standard folder in my d drive

**Comment by IllianiCBT** [comment]
I've figured it out: If you expand the unit list, right-click on a unit - before selecting a unit - it will throw an error because it recognizes that you have the category title selected and _not_ a unit.

**Comment by OrbMonky** [comment]
Ah! Nice! I knew I wasn't crazy, hehehehahaha

**Comment by IllianiCBT** [comment]
Closing as resolved
