### ISSUE TITLE
12/13 Logistics Overhaul '0.50.02-SNAPSHOT' - Character dying from old age was resurrected automatically and left unit automatically

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5369]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

![image](https://github.com/user-attachments/assets/e61eef10-4c71-4264-ac0a-58dce1e0df8b)
![image](https://github.com/user-attachments/assets/f97d48dc-97de-4d80-b54d-1172b363afab)

I don't know what to make of it. A miracle? A bug? Who's to say.

### Steps to Reproduce

1. Character who is likely to die from old age in campaign
2. Advance days until they perish from old age
3. Personnel dies, resurrects, refuses to elaborate, and leaves.

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/13 Logistics Overhaul '0.50.02-SNAPSHOT'

### Attach Files

[logs.zip](https://github.com/user-attachments/files/18134100/logs.zip)
Campaign, Customs, logs included. Autosave before even included for reproduction purposes as well as a campaign save on the day it occurred.

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
