### ISSUE TITLE
[v0.50.02 Nightly] Vehicles and vessels are ignoring their personnel assignments

### ISSUE THREAD

**Issue by LadyAdia** [MegaMek/mekhq#5373]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

08:09:11,286 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:309) - Starting MekHQ v0.50.02-SNAPSHOT
    Build Date: 2024-12-13T03:35:44.686398237
    Today: 2024-12-14
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.12
    Platform: Mac OS X 15.1.1 (x86_64)
    System Locale: en_US
    Total memory available to MekHQ: 2 GB
    MM Code Revision: b049c9a13fdd9cd53e2e94aa279446656259f913
    MML Code Revision: 97444ab86cff224d0ac82377932d42eb472b447b
    MHQ Code Revision: ec5f60783439c6f52ff4fb8a4f66f3453fd9b119

While in hanger tab, vehicles, vessels, and similar units are showing understaffed, often with only their commander assigned. 

![Image 12-14-24 at 8 16 AM](https://github.com/user-attachments/assets/0cf39251-bbdb-4ce0-9366-89a69daf8d06)

TOE tab also shows the unit as in critical condition. Note the Schrek at the top of the above screenshot. Switching to the personnel tab shows that all assigned personnel are still in their vehicles.

![Image 12-14-24 at 8 17 AM](https://github.com/user-attachments/assets/c42fde39-8595-4baa-bc83-a45342ae89fc)

Two gunners are assigned to the Schrek in question. Chesking the rest of the personnel shows all gunners and drivers are assigned correctly.

The bug seems to effect tanks, VTOL, support vehicles, and vessels. Meks are unaffected, as well as units requiring only a single crew. Infantry are also unaffected, but they have a separate bug already noted (#5372 ).

Included in archive are the screenshot, all required customs and user files, the save, and the MHQ log.

### Steps to Reproduce

Load the save

### Operating System *

Mac

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0.50.02 Nightly

### Attach Files

[MHQ Crewe Vehicle Bug 24-12-14.zip](https://github.com/user-attachments/files/18136276/MHQ.Crewe.Vehicle.Bug.24-12-14.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by LadyAdia** [comment]
On further digging, it seems to only be Gunners that are effected by this bug. Pilots and "crewmembers" are unaffected.

**Comment by psikomonkie** [comment]
This is an issue in Megamek, can this please be moved? Thanks!

**Comment by psikomonkie** [comment]
I'm sorry, this is a MekHQ issue, please don't move it.
