### ISSUE TITLE
12/13 0.50.02 logistics snapshot - Gunnery reported at 7 across the board for units assigned to missions, gets ported into megamek with 7 gunnery

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5375]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

Forming for my first missions on my new contract, I noticed what seemed to be a display bug, pilots had their correct skills on the personnel sheet, but forces assigned to scenarios showed 7 gunnery. Unfortunately, it ports the force to megamek with 7 gunnery across the board as well.
![image](https://github.com/user-attachments/assets/628a2494-135a-49f9-8b3f-e9ac2e7a1c1f)
![image](https://github.com/user-attachments/assets/36c36628-8fa6-40fb-9e6c-3ba3f5558245)
![image](https://github.com/user-attachments/assets/5fce4e1f-acca-44dd-bd51-172cddd35038)
![image](https://github.com/user-attachments/assets/7e5a1b86-608f-42ac-9932-d369d2dc40eb)

### Steps to Reproduce

1. Start contract, get scenario, assign troops
2. observe scenario panel
3. observe results in megamek on day of scenario

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/13 Logistics Overhaul '0.50.02-SNAPSHOT'

### Attach Files

[logs.zip](https://github.com/user-attachments/files/18138020/logs.zip)
Includes prior day autosave, day-of manual save, suite logs, customs folder, and megamek autosaves

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by OrbMonky** [comment]
I can confirm personnel seem to not be affected by returning from mekhq, their gunner stays the way it should be after a mission even without editing it to the correct value in megamek

**Comment by IllianiCBT** [comment]
@psikomonkie is this possibly in relation to your recent crew changes?

**Comment by psikomonkie** [comment]
> @psikomonkie is this possibly in relation to your recent crew changes?

Yep. Save was made with after loading with the nightly, the Meks are missing their gunners: 
![image](https://github.com/user-attachments/assets/84bfb6a2-156c-40ca-9f52-234619b85549)

The stat on the TO&E is the unit's gunnery and piloting. To fix this on a save made with the nightly, you need to unassign and reassign the Mekwarrior. I would suggest you do not load saves until #5374 is included in the nightly.
