### ISSUE TITLE
Under the Education module, not all instances of 'mech' have been converted to 'mek'

### ISSUE THREAD

**Issue by Tempest-56** [MegaMek/mekhq#5379]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

Pretty much as stated. Instances like Unit Education-Military-Apprenticeship-Mechwarrior Apprenticeship. Some instances have been changed but others have not. 

### Operating System *

Windows 11

### Java Version *

17

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

v0.50.01

### Attach Files

[Autosave-1-The Stratos Tracers-31611015.cpnx.gz](https://github.com/user-attachments/files/18141170/Autosave-1-The.Stratos.Tracers-31611015.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
The education module sits in a weird position: canon information such as academy names and descriptions should use MechWarrior, course names and skills, etc, should use MekWarrior

**Comment by IllianiCBT** [comment]
I went through the very tedious process of checking mek vs. mech in the academy xmls and I'm happy to confirm we're in compliance.
