### ISSUE TITLE
Education modules provide far too little xp versus feral children

### ISSUE THREAD

**Issue by Tempest-56** [MegaMek/mekhq#5380]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Alright, so I did some experimenting because I was curious about something. 

I was trying to decide what paths to take children on using the education module in my main campaign and noticed some oddities.

**Methodology**: Started new unit, generated 12 children and removed all the adults. Set all XP of children to 0 and gave them the same birthday. I used the 50.00 experience curve since it was lower (so 1xp per month on a roll of 7 or better; 50.01 is 5xp per month.)

Sent four of the kids through a low end education (Unit Creche:Daycare -> Home Schooling:Basic Education -> High School:High School Education -> In-House Basic Training:Basic Mekwarrior Training); four through high end (Military Creche:Daycare -> Boarding School:Private Education -> Prepatory School:General Education -> Tri-M Mercenary Academy:Mekwarrior Graduate); and four were left to run feral with no education at all.

**Results**:
At the end of stage 1 (age 3), the low end cadre had 1xp; the high end cadre had 4xp; the feral cadre had 16-21xp.
At the end of stage 2 (age 10), the low end cadre had 5xp; the high end cadre had 8xp; the feral cadre had 66-74xp.
At the end of stage 3 (age 16), the low end cadre had 9xp; the high end cadre had 14xp and +1 Leadership (so the equivalent of 44xp); the feral cadre had 109-121xp.
And at the end of stage 4 (age 17 with graduation), the low end cadre had 12xp and were 8/7 pilots (equivalent to 52xp); the high end cadre had 15xp with slightly varied skills (one 6/5, one 6/4, two 5/5) plus the Leadership (equivalent to 175xp); the feral cadre had 115-128xp with no skills.
Now, again that's with the default 50.00 experience curve. Under the 50.01 defaults the feral cadre would be sporting 575-640xp.

I expect this is not the intended experience, because it seems like under the current rules set educating the unit's children will massively handicap them at every stage of development.

### Operating System *

Windows 11

### Java Version *

17

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

v0.50.01

### Attach Files

[Education Test.zip](https://github.com/user-attachments/files/18141593/Education.Test.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Children probably shouldn’t be getting idle xp at all

**Comment by Tempest-56** [comment]
Probably not - after a bit of quick math under the 50.01 awards system your average feral child will be have enough idle XP to able to become an Elite skilled mech pilot by age 10.

**Comment by IllianiCBT** [comment]
Closing as resolved
