### ISSUE TITLE
12-15 0.50.02 snapshot - unable to save

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5383]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

![image](https://github.com/user-attachments/assets/f59cb588-a5e8-4261-8a11-8309ccb038f1)
I was able to advance a day and generate an autosave, but cannot manually save. No current mission in progress, just idling on a planet reassigning my crew.
[logs.zip](https://github.com/user-attachments/files/18143526/logs.zip)

The named save is the one I was working off of when reassigning crew, it appears I am unable to progress in this version as neither manual nor autosaves are usable.

### Steps to Reproduce

1. load save from prior version
2. attempt to save in new version

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/15 Logistics Overhaul '0.50.02-SNAPSHOT'

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by OrbMonky** [comment]
The log captured there was for the autosave creation, here is one from attempting to save manually from the functional save
[mekhq.log](https://github.com/user-attachments/files/18143576/mekhq.log)

**Comment by OrbMonky** [comment]
The bottom of the autosave is 

> </combatTeams>
	<shipSearchType>0</shipSearchType>
	<shipSearchResult></shipSearchResult>
	<autoResolveBehaviorSettings>DEFAULT</autoResolveBehaviorSettings>
	<retirementDefectionTracker>
		<rollRequired>1,2,3,4</rollRequired>
		<unresolvedPersonnel>
		</unresolvedPersonnel>
		<payouts>
		</payouts>
		<lastRetirementRoll>3026-09-04</lastRetirementRoll>
	</retirementDefectionTracker>
	<automatedMothballUnits>
	</automatedMothballUnits>
	<customPlanetaryEvents>
	</customPlanetaryEvents>
		<partsInUse>
		<ignoreMothBalled>false</ignoreMothBalled>
		<topUpWeekly>false</topUpWeekly>

**Comment by IllianiCBT** [comment]
Just to confirm, this is the save aborting early. I'm looking into it now.

**Comment by OrbMonky** [comment]
The snippet I posted is from the autosave which the game made,
The autosave was able to be made on day advancement but won't load.
The actual campaign save is imported from the 12/13 logistics nightly

**Comment by IllianiCBT** [comment]
Closing as resolved
