### ISSUE TITLE
[12-15 Logistics Artifact] Gunners/Soldiers not assigning to units

### ISSUE THREAD

**Issue by LadyAdia** [MegaMek/mekhq#5385]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

A soldier and a gunner were killed in my last scenario (along with losing a VTOL unit). Upon activating a replacement VTOL, the pilot and mechanic were able to assign with no issue, but upon assigning the gunner, the unit still showed the purple border for understaffed. Upon checking the personnel tab, the gunner was showing successfully assigned. The same thing happened when assigning a new soldier to the jump infantry unit that was short.

Screenshots showing the two units as understaffed

<img width="1440" alt="Screenshot 2024-12-15 at 8 26 33 PM" src="https://github.com/user-attachments/assets/d88d6a88-dc29-404b-bee4-5f604c44bb7c" />

<img width="1440" alt="Screenshot 2024-12-15 at 8 26 43 PM" src="https://github.com/user-attachments/assets/4345ecaf-03c4-43e9-ad9b-e4c58cf14a40" />

Screenshot showing the gunner as assigned in Personnel tab

<img width="1440" alt="Screenshot 2024-12-15 at 8 27 16 PM" src="https://github.com/user-attachments/assets/3381faf5-e46f-4b90-a105-9c4dc6ead1b9" />

### Steps to Reproduce

Assign gunner or soldier to understaffed unit

### Operating System *

Mac

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0.50.02 Nightly Logistics Artifact

### Attach Files

[MHQ Gunner:Soldier Issue 24-12-15.zip](https://github.com/user-attachments/files/18143742/MHQ.Gunner.Soldier.Issue.24-12-15.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
@psikomonkie another one of yours I suspect. Sorry buddy, you seem to have fallen victim to the curse of 'one simple change'

**Comment by psikomonkie** [comment]
> @psikomonkie another one of yours I suspect. Sorry buddy, you seem to have fallen victim to the curse of 'one simple change'
I don't think it is, actually. 

If you go to the Karnov and unassign the gunner, the crew becomes 0/2. If you reload the save, unassign the pilot, and assign a different pilot, the Karnov is fully manned. 

Similarly, the Jump Platoon has two units with the "red" medical background in Personnel.

**Comment by LadyAdia** [comment]
Closing as resolved. User error.
