### ISSUE TITLE
[RFE] [50.02 Nightly] Dependents Cap Feels Too Stringent/No Dependents Outside Spouses/Children

### ISSUE THREAD

**Issue by ussdefiant60** [MegaMek/mekhq#5390]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

So, #4463 provided a bunch of changes with regards to how Dependents work, in particular putting a cap on the number of them the campaign can have before more stop showing up. My experience from about 7 years worth of campaign play, however, is that i'm not seeing any random dependents show up at all besides spouses/kids attached to new recruits to the unit. I'm getting the feeling that even just the random families for new arrivals is already completely filling the 5% cap, leaving no room for actual random hangerons to show up/potentially be training fodder. Is it possible to raise the cap from 5% of active personell to something in the area of 25%?

### MekHQ Suite Version *

50.02 Nightly

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
