### ISSUE TITLE
[12-15 Logistics Artifact] Reinforcement screen not formatted well in some occasions

### ISSUE THREAD

**Issue by LadyAdia** [MegaMek/mekhq#5391]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

When attempting to reinforce in a scenario, the dialog window occasionally shows unreadable data, making selecting desired reinforcement nearly impossible.

<img width="1680" alt="Screenshot 2024-12-16 at 8 03 14 AM" src="https://github.com/user-attachments/assets/22a8b396-a52c-4825-9674-e599ce8f487d" />

Display resolution set to 1680 x 1050 pixels.

### Steps to Reproduce

1. Load save file included in archive
2. On Area of Operations tab, select Manage Scenario on tile 0006 of Sector 0

### Operating System *

Mac

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0.50.02 Nightly Logistics Artifact

### Attach Files

[MHQ Reinforcement Bug 24-12-16.zip](https://github.com/user-attachments/files/18151320/MHQ.Reinforcement.Bug.24-12-16.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
This save was made during the tiny window in the tiny window where we updated a loading method. This is unrelated to the bug at hand, but to fix do a find-replace in your save file (it can be opened with any text editor) replace `>f<` with `>QUALITY_F>` (or `>QUALITY_A>` if you have reverse quality names enabled).

**Comment by IllianiCBT** [comment]
I'm really struggling to replicate this bug. Whenever you get time, can you have a play around on the latest nightly (or logistics artifact) and lemme know if you can narrow down a set of replication steps.

**Comment by LadyAdia** [comment]
Got it. I'll update tonight when I get home and see what I can figure out

**Comment by LadyAdia** [comment]
I managed to get it replicated. This archive has my current campaign with two scenarios. To reproduce, manage scenario "Heavy Recon Evasion" on Sector 2, Tile 0303 with a defense lance, then try to reinforce.

[MHQ Reinforce Bug Suppliment.zip](https://github.com/user-attachments/files/18158753/MHQ.Reinforce.Bug.Suppliment.zip)

**Comment by LadyAdia** [comment]
I use the 8th Grenadiers as the assigned force.

**Comment by IllianiCBT** [comment]
Closing as resolved
