### ISSUE TITLE
12/15 Logistics Overhaul '0.50.02-SNAPSHOT' - scouting seems to assign forces to any fight detected even if they did not land on that hex.

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5392]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Scouts are just having a rough time out there this version.
![image](https://github.com/user-attachments/assets/c1d96bc9-3564-468f-8dfd-ce86f1de6190)
All revealed fights embroiled a scout in it even if the scout didn't land in a hex with the opfor in it, as long as they 'scouted' it they got pulled in. This breaks the sustainability of scout groups and prohibits the addition of other groups to the scenario barring available SP, which isn't in abundance anymore, meaning these missions become do or die very rapidly.
[logs.zip](https://github.com/user-attachments/files/18155516/logs.zip)
File should contain autosave before and save after assignment - advance day from auto save, deploy scouts to the stratcon map to reproduce.

### Steps to Reproduce

1. load autosave
2. advance day
3. deploy scouts
4. note assignments on revealed opfors

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/15 Logistics Overhaul '0.50.02-SNAPSHOT'

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved

**Comment by OrbMonky** [comment]
... Somehow, the bug returned.... (kinda)

![image](https://github.com/user-attachments/assets/40241a48-047d-4694-bbfc-1b501d63d357)

It didn't hard-assign it to the task but it did assign the scouting force as the seed force (which is kinda worse since they're deployed a hex away).

**Comment by IllianiCBT** [comment]
That’s not actually a problem as, unless you’re on an Integrated contract (which is handled differently) we just pick one of your forces to act as the seed lance.

The force used as the seed lance does not need to be the force you actually send to the scenario — I fixed all the bugs relating to that earlier in the dev cycle.

However, if I’m missing something lemme know and we can get this reopened :)

**Comment by OrbMonky** [comment]
My understanding is the seed lance would pull from available lances so that lance could be assigned to the issue, or is the seed lance basically irrelevant? It feels as a player like I'm supposed to send that lance to that fight, if it isn't relevant it may be able to be clarified.

**Comment by IllianiCBT** [comment]
It’s basically irrelevant. I *might* be able to set it so that it doesn’t display the seed force at all, however the last time I looked it was more effort than the benefit warranted.Sent from my iPhoneOn Dec 19, 2024, at 8:13 PM, OrbMonky ***@***.***> wrote:﻿
My understanding is the seed lance would pull from available lances so that lance could be assigned to the issue, or is the seed lance basically irrelevant? It feels as a player like I'm supposed to send that lance to that fight, if it isn't relevant it may be able to be clarified.
