### ISSUE TITLE
Unable to Purchase Infantry

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#540]
0.43.5

AtB on, although I'm fairly certain it doesn't matter.

Click Marketplace > Purchase Unit > Change Filter to "Infantry"
Nothing shows so either something has broken the filter or something has disabled the ability to purchase infantry.
Logs show no errors.
[NoInfantry.zip](https://github.com/MegaMek/mekhq/files/1492101/NoInfantry.zip)

**Comment by neoancient** [comment]
This dialog? I don't see a problem. Do you have the weight class set to something other than light or all?
![image](https://user-images.githubusercontent.com/16927464/33089896-b3536024-ceb7-11e7-9e4c-9e59c48856d6.png)

**Comment by NickAragua** [comment]
Tech level introductory doesn't feature infantry, generally.

**Comment by scJazz2** [comment]
haha set Introductory while checking for another bug.
