### ISSUE TITLE
[12-16 Logistics Artifact] Saves not loading

### ISSUE THREAD

**Issue by LadyAdia** [MegaMek/mekhq#5402]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

My save file is failing to load in the new artifact. Ive tried both my main save file and my autosaves with no success. I've included all of the saves within the archive, along with required files.

### Steps to Reproduce

Attempt to load save file

### Operating System *

Mac

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0.50.02 Nightly Logistics Artifact

### Attach Files

[MHQ Save Load Error 24-12-16.zip](https://github.com/user-attachments/files/18158344/MHQ.Save.Load.Error.24-12-16.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Did you do the find-replace thing I mentioned in your other issue report?

**Comment by LadyAdia** [comment]
I forgot about that. Let me see if that helps

**Comment by LadyAdia** [comment]
That fixed it. Marking as closed.

**Comment by IllianiCBT** [comment]
Yeah, there was a window of less than an hour before we found and addressed that issue, and you got really unlucky.
