### ISSUE TITLE
[RFE] Add passenger capacity to the total noncombatant capacity in the reputation report

### ISSUE THREAD

**Issue by LadyAdia** [MegaMek/mekhq#5408]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an implementation of a missing official rule

### Brief Description *

Per CO pg.35, transportation rating first fills bay personnel capacity with support personnel, then any overflow is filled into passenger cabins. I noticed a discrepancy in how MHQ counts transport capacity, and upon testing, found that the reputation report is currently only counting bay personnel capacity in its total available noncombatant capacity. (Or, at the very least, passenger capacity is being skipped over in calculation.) 

This RFE would bring this calculation into line with the RAW as well as simplifying the process of housing noncombatants, particularly dependents.

### MekHQ Suite Version *

v0.50.02 SNAPSHOT Logistics Artifact

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
