### ISSUE TITLE
12/16 Logistics Artifact / 0.50.02 SNAPSHOT - Using Support Points to get a Resupply works but the CVP/SP management window becomes undismissable, mekhq cannot be closed or interacted with except through task manager

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5409]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

![image](https://github.com/user-attachments/assets/04a9c87e-b6cf-4031-9a13-2aa4de70bbdc)
Using this, I was able to get a supply convoy, hunky dory, but then it refused to go away and wouldn't allow interaction with anything in mekhq, couldn't even alt-f4. I was able to click the buttons on the menu but they did nothing except indicate they had been clicked visually.
[logs.zip](https://github.com/user-attachments/files/18169473/logs.zip)

### Steps to Reproduce

1. Have/add CVP in active contract
2. Convert CVP to SP
3. Request and succeed at supply convoy request
4. process supply convoy request
5. process does not end fully, CVP/SP management window becomes uninterruptible and hard locks the program effectively

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/16 Logistics Artifact / 0.50.02 SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
