### ISSUE TITLE
12/16 Logistics Artifact / 0.50.02 SNAPSHOT - Mekhq's inbuilt meklab does not utilize the A = Best F = worst alternative ordering at all when customizing, also allows illegal armor in excess of chassis rating

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5426]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

When this feature is enabled, it would be expected that the Armor Tech Rating would also abide by A = Best, F = Worst for consistency on support vehicles and units that mount various BAR armor.
Here is F rating selected in Meklab and its options
![image](https://github.com/user-attachments/assets/162b2d75-dfb2-4baa-91eb-279b25b5f626)
![image](https://github.com/user-attachments/assets/9bd17972-4e4f-445c-8ec9-c2ac9d1689cb)

Here is A rating selected in Meklab and its options
![image](https://github.com/user-attachments/assets/370697a0-79a1-43b0-91dc-bbd7815ab285)
![image](https://github.com/user-attachments/assets/d1a3ae4a-37b8-4159-b6ea-8df8683fb061)

The current build can get the right armor onto the unit, but it will still flag it as 'A' for worst, even if it is sporting Standard Armor which isn't available under its A rating dropdown which should only allow BAR 8 at max according to Tech Manual page 134. The chassis and engine ratings also do not account for the inverted ordering system.

Further, the armor tech rating may not exceed the vehicle chassis' tech rating, the Paramour MFB variant has a D chassis rating, and Megamek's Meklab allows refitting to any armor tech rating, exacerbating the initially reported issue.
![image](https://github.com/user-attachments/assets/f3cb433e-db77-4526-a703-c263f3ed7f86)
![image](https://github.com/user-attachments/assets/44a7a1d7-5d10-45d9-95a0-150acbf67fac)

### Steps to Reproduce

1. Enable reversed quality ordering.
2.  Grab a support vehicle in any campaign, I used Paramour, the MFB variant
3. Observe the quality names do not correspond to inverted best/worst ordering if enabled
4. Attempt to reset to an impossible armor (F rating, Standard)
5. Complete the refit once the weight is accounted for and note that it allows an impossible armor type.

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/16 Logistics Artifact / 0.50.02 SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
_To my best knowledge_ it shouldn't be using the reverse quality names because these aren't quality names.

**Comment by gsparks3** [comment]
Yeah, the letter grades here are _tech rating_ grades ("How high tech is this"), not item/unit quality grades ("How well maintained is this"). The fact that the letter-grade system is reused in something like six places (several of which have similar names and related meanings) is one of several issues originating in the tabletop rules themselves. 

The second half of the issue, the armor Tech Rating exceeding the chassis Tech Rating, appears to not actually be an issue due to errata. Early versions of TechManual had this limit, but as of the third printing and up, the limit was removed. See errata document snippet below.
![image](https://github.com/user-attachments/assets/81f28e01-075c-4f20-a32f-dde78b6e44db)

Closing as invalid, although I have to agree that the various sorts of letter codes can be confusing.

**Comment by IllianiCBT** [comment]
As Battletech players, letter grades are the bane of our existence
