### ISSUE TITLE
(ACARS) NPE : "this.game" is null

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#5432]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

There is no NPE pop up message, and everything appears to be functioning fine, but the log gets smashed with the following message.

```
14:23:35,281 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.calculateNumberOfVictories(MekHQ.java:803) - Error in parallel execution
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "megamek.common.Game.getOptions()" because "this.game" is null
```

### Steps to Reproduce

Resolve a battle via ACARS, observe log.

### Operating System *

Linux

### Java Version *

17

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

https://github.com/MegaMek/mekhq/commit/c8b3364a938a8f4599c02ffaa4c03519af91da1b

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/18188118/mekhq.log)
[Aces of ACARs30281205.cpnx.gz](https://github.com/user-attachments/files/18188126/Aces.of.ACARs30281205.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by Scoppio** [comment]
Fixed by: [Megamek #6284](https://github.com/MegaMek/megamek/pull/6284)
