### ISSUE TITLE
[RFE] [ACAR] Move option to select between Princess and ACAR auto resolve to briefing room

### ISSUE THREAD

**Issue by LadyAdia** [MegaMek/mekhq#5439]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

Given the strengths and weaknesses of both auto resolve options, it feels like the option of whish function to use could best be served moving from the campaign options dialogue to the briefing room tab. One option would be for a dialogue to appear when auto resolve is selected, prompting the player to decide at that time. Another could be to move the drop-down option itself into the briefing room directly to allow selection before clicking auto resolve.

### MekHQ Suite Version *

v0.50.02 SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by LadyAdia** [comment]
@Scoppio

**Comment by Scoppio** [comment]
#5454 implements this RFE
