### ISSUE TITLE
[RFE] Transparency/player agency improvements to StratCon reinforcements

### ISSUE THREAD

**Issue by jslater89** [MegaMek/mekhq#5442]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

The new reinforcement system doesn't feel great from a player perspective: you hit a button with a warning that you may fail, and then you get a message in the log. I think this is largely a perception problem rather than a design problem, though, so I propose the following two improvements:

* The reinforce dialog should show the TN and the factors going into it, so that players can decide ahead of time if reinforcing is worth the potential cost of SP (and learn the circumstances/character skills that make reinforcing easier or harder).
* It should perhaps be possible to commit additional SP to a reinforcement attempt as a player agency/risk-reward mechanic—do you burn extra SP to help out a lance that really needs it, at the risk of having no support left later in the cycle, or let that lance stand on its own to keep your powder dry?

### MekHQ Suite Version *

nightly

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Unfortunately, I ran out of dev time today, so this won’t be addressed in tonight’s nightly. I should have a PR ready to go before EOD tomorrow, though.

**Comment by IllianiCBT** [comment]
Closing as resolved
