### ISSUE TITLE
12/16 Logistics Artifact / 0.50.02 SNAPSHOT - Sometimes convoy processing crashes MHQ

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5448]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

Has only happened once, but MHQ completely froze after processing convoy, this was a new year/dec-31st-jan 1st convoy event if that matters.

[logs.zip](https://github.com/user-attachments/files/18202854/logs.zip)

### Steps to Reproduce

1. Retry advancing to new year from autosave or from slightly backdated campaign save
2. Sometimes it freezes, forcing task manager exit

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/16 Logistics Artifact / 0.50.02 SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by OrbMonky** [comment]
[logs.zip](https://github.com/user-attachments/files/18202927/logs.zip)
Attached is n additional a repro-capable save if it helps

**Comment by IllianiCBT** [comment]
Based on the description in Discord this sounds like an infinite loop

**Comment by OrbMonky** [comment]
Well, it seems to have some funky behavior around new years when on contract. Sometimes it freezes, sometimes it tells me both the convoy made it and the convoy is under attack, sometimes I get a second itenerary but I have only been able to produce the freeze more than once. May be related to the same issue since it's unpredictable, sometimes it goes off fine.

**Comment by IllianiCBT** [comment]
Closing as resolved
