### ISSUE TITLE
[RFE] Add more force clarity and situational clarity to ++INCOMING TRANSMISSION++ dialogues regarding convoys, particularly ones regarding the outcome/fate of convoys 

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5451]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

![image](https://github.com/user-attachments/assets/2a8fb00c-29c3-4ad9-802d-63b23b5ec906)
This doesn't tell me much except that whatever unit Tammy Morrison is with may or may not be in trouble. I have three convoys, they seem to operate 'together' for the sake of the convoy logic, utilizing a lump sum of cargo, but this at a glance doesn't provide meaningful information - though I do appreciate the flavor.

Please add information such as the title of the node above it/the grouping the unit is in for clarity, and a clarifying statement about what action is necessary or if any action is necessary at all in the text, preferable at the bottom in bold. Color code it red if severe, green if ideal for bonus points.

### MekHQ Suite Version *

12/17 logistics artifact / 0.50.02 SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Regarding your last request, events that require action should specifically state such already. I’ll double-check that’s working correctly.

**Comment by OrbMonky** [comment]
It may just need emphasis, I am not sure I have caught anything except the 'scenario created' bit'.

**Comment by IllianiCBT** [comment]
I can take a look at the wording for sure :)

**Comment by IllianiCBT** [comment]
Closing as resolved
