### ISSUE TITLE
ATB: Princess - Turret Deployment

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#546]
For Base Attack (Attacker) mission
Turrets should be moved to their own "Princess Player".
Turrets should be set to Deploy Center

Right now they are a part of the "Civilian" Player which deploys North edge. Unless the map is Full Urban type Turrets can not be deployed as there are no buildings. Moving them to a separate player also avoids any Herding issues with other mobile units. Deploying Center also means that they can actually get into the fight instead of being stuck on the far edge.

**Comment by NickAragua** [comment]
I wound up going a bit further with this one. Turrets always spawn under a separate bot in the center. Civilians will now spawn in the center as well, as per written AtB rules, and flee in the same direction as their allied bot forces. Also, there's a good chance that the "secondary" attacker force (whether the second bot lance roll or the allied bot lances) will show up on the "next over" edge from the primary force.

Let's keep this open and keep an eye out on whether this set of changes plays well in practice or not.

**Comment by scJazz2** [comment]
OCD insists I close a ticket that has had a fix applied. :)
