### ISSUE TITLE
12/16 Logistics Artifact / 0.50.02 SNAPSHOT - Logistics convoys seem to get copy/pasta scenario modifiers and extreme BV spreads in opfors, often resulting in light unit spam

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5464]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Hit the new year/next month, convoys went out, and wouldn't you know it all three got bogged down by enemy forces. Hey, it happens.

What probably shouldn't happen is some ~60 Warrior vtols splitting between the three groups of simple transports, in addition to main forces. It seems the Air Cavalry modifier got an extreme BV chunk (maybe from allied reinforcements, which may be resolved in later iterations), and filled up with a prodigious amount of Warrior VTOL craft.
![image](https://github.com/user-attachments/assets/83cc0f60-542d-4e66-8158-b32a2b42e25c)
![image](https://github.com/user-attachments/assets/6ce56d11-f2cd-442b-982a-f63251f6faa7)
![image](https://github.com/user-attachments/assets/9f2480f3-461b-4148-956f-3b36b84d4360)
![image](https://github.com/user-attachments/assets/0736a68e-9cb1-4a2e-8cb8-d0f2d1d5fa9b)

[logs.zip](https://github.com/user-attachments/files/18216608/logs.zip)

Day after and day before included

### Steps to Reproduce

1. Advance to a new month with multiple convoys and get dunked on by opfor force assignment modifiers

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/16 Logistics Artifact / 0.50.02 SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
