### ISSUE TITLE
[RFE] 12/16 Logistics Artifact / 0.50.02 SNAPSHOT - Convoy missions all look the same, with multiple ones all spawning on the same day it can be hard to distinguish which one you want to send forces to since StratCon's page doesn't list much info.

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5465]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

These all appeared on the same day - some of my convoys are more survivable than others, but I can't easily tell which one is which, so I can send the best relief force to them. Additional clarity/information would be great here.

![image](https://github.com/user-attachments/assets/6347c589-0b26-4250-9576-b924b345f702)
![image](https://github.com/user-attachments/assets/3987e78f-0bc1-4d42-aa2c-1d4b365056fe)
![image](https://github.com/user-attachments/assets/5b85e223-1e12-459b-813c-10b4ee01798f)

[logs.zip](https://github.com/user-attachments/files/18216688/logs.zip)

### MekHQ Suite Version *

12/16 Logistics Artifact / 0.50.02 SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
