### ISSUE TITLE
Feature Request: Awards for personnel

### ISSUE THREAD

**Issue by hell-fish** [MegaMek/mekhq#547]
Hi

This may sound pretty minor, but I'm playing a non-mercenary campaign at the moment, and I wish I had the ability to grant the characters in my unit medals and awards. Doesn't have to be terribly complex, just go into the personnel tab menu and do something like right-click to grant an award to a character from a list. Sorta like how you change their rank.

On right click:

Award:

Award 1
Award 2
Award 3
...

And maybe somewhere in the campaign options menu we can chose a pre-made list of awards (Davion, Kurita, etc.) or customize them with images (like portrait pics). Thus, when my unit deploys to Carver V for a 3-month mission, when it's all said and done, I can give them all a Carver V campaign medal, and then other medals for the characters who did important stuff, like held off a Blakist assault in a half-destroyed Locust or rescued the civilians in one of those special missions.

Like I said, minor, but it could go a way to helping me humanize my little puppet soldiers.

**Comment by BLOODWOLF333** [comment]
@Dylan-M what ever happened with that?

**Comment by pheonixstorm** [comment]
He said there were issues that still needed to be worked out iirc.

**Comment by BLOODWOLF333** [comment]
[Awards.zip](https://github.com/MegaMek/mekhq/files/1679192/Awards.zip)

My images for ranks, service stripes, and campaign ribbons.  Along with just the rank portion of my scenario generator spreadsheet since this keeps getting brought up now and then.

**Comment by bandildo** [comment]
I got a working version going on, with some work still need to be done. Here's how it looks:

![awards1](https://user-images.githubusercontent.com/12190053/42338757-ca8301b4-8082-11e8-90d2-b7c3497448a2.png)
![awards2](https://user-images.githubusercontent.com/12190053/42338759-cab227c8-8082-11e8-8ea5-7ccda4887422.png)

So, a couple of questions I'd like to debate:

- Where would be the best place to put the ribbons? I was thinking vertically, on a column to the right side of the person panel view, shown in the attached files. But maybe it will be too cluttered of medals and ribbons?

- I currently have each award to be defined by:

```
	combatCommendation.description=Company Kills 72
	combatCommendation.medal=CombatCommendationM.png
	combatCommendation.ribbon=CombatCommendation.png
	combatCommendation.text=Combat Commendation
	combatCommendation.xp=2
```
I wonder if I ought to put instead in a xml, so it would be easier to add and edit new awards. The user could select which award set to use in the campaign options, just like @hell-fish suggested. However, this wouldn't allow us to enforce the award conditions (e.g. disabling the button to award something that requires X kills if the person has less than that), since that would need to be hard-coded.

**Comment by Dylan-M** [comment]
I started the work needed to do this as an overlay on the portrait because I also needed the same code for doing layered TO&E images. There should be 2 images for each award: Full award like you've got, and also the small ribbon that would normally be worn on the left breast of most uniforms. It is that smaller ribbon that would be used as part of the overlay on the portrait.

**Comment by bandildo** [comment]
You mean something like this? (quickly done in mspaint)

![image](https://user-images.githubusercontent.com/12190053/42339699-a8a16dda-8085-11e8-9349-ee1674024488.png)

If so, seems like a neat discrete way of showing the ribbons. It's just a shame they are so small, because they are really beautiful.

**Comment by hell-fish** [comment]
Having them on the portraits doesn't seem optimal to me - you might have an
elite 20 year veteran with a fruit salad as a portrait. I think bandildo
(bandildo??) has the right idea with the full medals under the portrait and
stat box. Using .xml too, I think, would be best as it would better allow
the player to make/edit his own medals. Your merc company might use current
American medals for their graphics, but mine might use imperial
Austro-Hungarian medals and we might have different ideas in criteria for
our medals. If I want to give a Victoria Cross or Medal of Honor equivalent
to a guy piloting the light mech that killed an assault mech, I should have
the freedom to do so. Someone else may just want to let him get to 5 total
kills before a medal is automatically rewarded.

Great work on the first go!

**Comment by HammerGS** [comment]
Also looking forwarding to seeing this.  Personally I prefer the option in screen shot two.  Also I think everything needs to be as player configurable as possible.

**Comment by pheonixstorm** [comment]
For the final image shown... No. They would need to be below the portrait as well. Either above or below the medals.

**Comment by hell-fish** [comment]
Will this feature allow non standard medals too? Some of the canon awards
are things like big stars and sashes and stuff

**Comment by BLOODWOLF333** [comment]
Chappy also has a bunch of awards image and some faction specific ones and has posted them on the Megamek slack.

**Comment by pheonixstorm** [comment]
The initial idea I had that I shared with ralgith was to base the campaign ribbons on the contract followed by an upgrade for each scenario after the first.

ie First mission gives you a ribbon of x color or x x x colors. The next mission you get a single bronze star, next followup 2 bronze stars. Each series (bronze, silver, gold) would be no stars, 1 star, 2 stars, 3 stars, one large star, and maybe a border change to allow for 5 missions before bumping to the next color. Each contract ribbon could be designed in the contract the same as the toe images for the background. The scenarios decide the ribbons value (and number of scenarios fought for each individual.

**Comment by bandildo** [comment]
So something like this seems the best way to go?
![awards_mock](https://user-images.githubusercontent.com/12190053/42354677-58be2f84-80c0-11e8-957c-613658430ad0.png)

It looks nice, though the details of the ribbons are lost in resolution. But we have to choose either taking up space or not noticing the details. Can't have both.

I will then change it so we can add them via .xml

I was thinking about creating a sub-category in the menu, something like: 
Award > Award-Set-1 > Award 1.1 / Award 1.2 / etc
Award > Award-Set-2 > Award 2.1 / Award 2.2 / etc
This way we can leave the campaign options out of this. You are free to select awards from any set and mix them up, organize them as you wish. Award-Set-1 could be the current american medals, Award-Set-2 the Austro-Hungarian set, etc. However, this could be confusing for new users, as they will feel overwhelmed by the amount of medals. Did I just talk myself out of this idea? Would it be better to select an award set in the campaign options?

I will have to agree with @NickAragua about the prevention/allowance of medal awarding: it's not like it is difficult to "cheat" when playing AtB, anyways. We could have in the future some default awards, like the ones @pheonixstorm mentioned. That could use this framework, but then the awards would be hard-coded and automatically awarded. Seems something to do afterwards (I enjoy the idea of auto-awarding some awards, it is always rewarding for a player to get something automatically).

@hell-fish each award will have the possibility to have a ribbon image and a medal image. Both, only one or none at all. Medals will be displayed like shown in the first screenshots, ribbons will be under the portrait or somewhere else. You will be free to put whatever you wish as an image. Even a pin-up mech if you wish to have the kill-count in there :)

I will also add the "stackable" property for each award. This way you could award your pilot 3x the Purple Heart, or limit it to a single War of 3039. I was thinking of showing multiple instances of the medals, but only a single ribbon, even if it is stackable. Does this make sense?

**Comment by NickAragua** [comment]
That makes sense for the 20-year veteran whose got more medals than space on the chest. I'm somewhat concerned about the scope creep of it, as adding an extra "medal case" tab would mean extra coding. I'll leave it up to the coder. As long as the medal-rendering code is pretty modular it shouldn't be hard to move it around later if we feel a need to.

**Comment by Patriot1776** [comment]
It was an idea. :)

**Comment by BLOODWOLF333** [comment]
So they way I have been doing it is I use the colored ink portraits that can be downloaded off the megamek.org site.  (I use Gimp as my image editor its similar to photoshop I hear)
1. Resize the image to 150x150 after MekHQ randomly pics what image to use for the person.
2.  Add 8 pixels of transparency to the bottom of the portrait for the first row of ribbons (I use the medals as unit awards to be added to the force icons in the TO&E)
3.  Shrink my ribbons down to 9x30 pixels so five will fit in a row (centered).
4.  Add another 8 pixels to the bottom of the portrait if they gain more than 5 different ribbons and need another row, always keeping the highest ribbon on top then going according to the order of precedence to the right, with the lowest ribbon at the bottom right.
5.  And the ranks and service stripe images yeah those would be a different thing apart from this @bandildo (I imagine a new column in the rank section of the campaign options allowing the user to define the images for each rank and it writing the filepath of the image into the xml).
6.  All the medals in my zip have a corresponding ribbon (we only wore our medals when wearing dress blues in the USMC, the other dress uniforms it was just ribbons only along with our shooting medals) so, displaying the medals version somewhere else would save space restricting the portrait to ribbons only just as a suggestion.

**Comment by bandildo** [comment]
@BLOODWOLF333 that looks great, will aim to do it like so. Which is the real-world order? I could also add a "importance" property to each award. You also seem to have found a quite nice place to put the insignias. I would then use @Dylan-M code for layered images.

@Patriot1776 in my opinion it looks best to decorate the rather-bland panel, it gives more life and personality to the personnel.

**Comment by BLOODWOLF333** [comment]
Order of precedence chart for sorting high to low.
https://www.medalsofamerica.com/content--name-army-medals-and-ribbons-chart

**Comment by NickAragua** [comment]
@bandildo There's some offline discussion happening, and the consensus seems that the medal ribbons should go below the portrait, to avoid the fruit salad problem. Bloodwolf's renders seem to solve the problem pretty well, so I endorse going with that kind of approach.

**Comment by BLOODWOLF333** [comment]
Yeah I used to have the ribbons display over the portrait and a 20 yr SgtMaj mechwarrior's face would end up getting covered by the ribbon stack so had to start arraying them below the portrait.  HQ would always scale the image just fine with no problems.  And where ever you put the medals (idk how hard this would be to code) but, can have the upper row overlap the lower row of medals to compact it and save space as well just like on our uniforms.

![image](https://user-images.githubusercontent.com/16950832/42356199-c34d12f4-8096-11e8-9d42-728edb3526a2.png)

**Comment by pheonixstorm** [comment]
Just put the ribbons in the same way as the medals from the second pic, right above the personnel log. Best spot for them and reusable whenever unit citations become a thing (planned).

**Comment by hell-fish** [comment]
I’m not a big fan of the overlap idea, if only because I think of the
biography page as more like a DD-214 type of personnel record rather than
an official portrait. I’d rather have a full record with full medals and
awards that takes up the extra space than anything too small or compact to
fully appreciate. I mean, our characters practically get a full,
illustrated medical record already anyways, why not go all in on something
so very meta and so very involving for a player commanding a unit?

**Comment by Patriot1776** [comment]
I'm for the separate tab to put the awards. Maybe include a field where a person can input what the character did to receive the award. Under the portrait will make it hard to see for some of us that are visually challenged and can lead to overlap problems if said character does a lot of missions. Why hide that beautiful artwork in such a way?

**Comment by mchapman1970** [comment]
yes i have medals for all five factions  and how they obtain them.  I took what lorehad. and then added more.   i also went and look at foreign armys to get ribbons color and also names for specialized medals.

**Comment by Dylan-M** [comment]
@hell-fish You wouldn't actually overlap them. You would row them along the bottom. The original discussion for doing this involved having the standard campaign ribbons along the bottom edge of the portrait, new rows going down, and then also having a separate place for the full awards and honors. I still believe it should be done this way. Also, the sample image @bandildo did had the ribbons far larger than was done in the original concepts also. In the original concepts, you could fit a row of 5 ribbons across the bottom of the portrait.

At any rate, good luck and have fun.

**Comment by mchapman1970** [comment]
![amir](https://user-images.githubusercontent.com/22855199/42402426-4d266e4a-8140-11e8-9d32-6ebef3a3054e.jpg)


something like this???

**Comment by Patriot1776** [comment]
I do like that a lot better then the other way that was shown.

**Comment by pheonixstorm** [comment]
I think the dates and descriptions should go in the personnel log instead of adding an extra log like that though.

**Comment by mchapman1970** [comment]
![leftenant general valeria skidmore](https://user-images.githubusercontent.com/22855199/42404175-aab4a2f0-814c-11e8-99d2-9ec7d97f91d0.jpg)


I was tinkering with this a few months ago  not sure if anyone would want this or if it is going to deep

**Comment by NickAragua** [comment]
It looks like people have all kinds of opinions on this matter. My suggestion is to go with https://user-images.githubusercontent.com/12190053/42338759-cab227c8-8082-11e8-8ea5-7ccda4887422.png and https://user-images.githubusercontent.com/12190053/42354677-58be2f84-80c0-11e8-957c-613658430ad0.png as originally planned. 

My other main recommendation is to use good encapsulation on the medal/ribbon rendering code so that you can easily find and change it later, or invoke it from somewhere else without too much trouble.

**Comment by hell-fish** [comment]
I think I like the LTG Connor Amir graphic the best. Not sure about the
programming, but it looks the most flexible of all the options - ribbons,
skill badges, etc. The one with the uniform just seems too tricky - how
would the player chose what to put where?

**Comment by mchapman1970** [comment]
yeah the second pic with the uniform i was trying  something out.   the badges on the right were just showing how many campaigns she was in and of course her commander badge.  idk how u would code it. it was bitch doing it in gimp she is the only one i did that for.  i am excited about this feature so like i said whatever the coder does i will be happy. and if we could maniulate the names and such in xml i would be in heaven. lol.

**Comment by bandildo** [comment]
So I guess this will be the "final" version on how it will look:

![awards3](https://user-images.githubusercontent.com/12190053/42415211-03e38fe2-823f-11e8-8cae-539696bc1b80.png)

What do you guys think?

I will then implement everything using .xml. If anyone doesn't suggest otherwise, I think I'll leave the award sets out of the campaign options, and let the player choose on the fly via an intermediate menu.

Any more suggestions or feedback?

There is still a lot of cleanup to do and bug cracking until this becomes a pull request.

**Comment by BLOODWOLF333** [comment]
Super sweet!  Is it going to be too difficult to make the medals layer over each other with the top row offset from the one below it?

![image](https://user-images.githubusercontent.com/16950832/42415275-70343f1a-820e-11e8-9d15-41f72c9f4829.png)

**Comment by mchapman1970** [comment]
looks good.  cannot wait to test it.

**Comment by bandildo** [comment]
@BLOODWOLF333 to be honest, I have absolutely no idea how the overlapping can be done. I'll investigate in the next opportunity,  since it certainly looks neater.

Thanks for all the positive feedback :)

**Comment by firefly2442** [comment]
Here's the [awards page on Sarna](http://www.sarna.net/wiki/Awards).  Not sure if we can use the images (copyright?) but maybe the text of the award names?

**Comment by mchapman1970** [comment]
by using xml I will be able to create more medals or ribbons. and set the criteria? is that correct?

**Comment by pheonixstorm** [comment]
The campaign ribbons look like a mess that way... Too small and looks like a rainbow smashed together.

The medals look fine, though should be centered and inside the same type of ui element that the description/personal log uses to match the rest of the pane.

**Comment by mchapman1970** [comment]
I like the ribbons and the medals  the way he shows it...I am happy that we are getting these

**Comment by bandildo** [comment]
Okay, so I think I'm very close to wrapping this up.

Here's how it is looking:

![awards](https://user-images.githubusercontent.com/12190053/42524932-d0bdf5ee-8469-11e8-8628-52553c219ebd.png)

And the .xml is as follows:

![awards2](https://user-images.githubusercontent.com/12190053/42524940-dcc92cb4-8469-11e8-80a4-17a390a62006.png)

As for the parameters:

- Name and Description: self-explanatory;
- Medal: medal file name;
- Ribbon: ribbon file name;
- XP: experience awarded to the person who gets the award. Also, the importance of the award is evaluated by the amount of XP given (e.g. to decide in which order they appear in the UI);
- Stackable: by default/omission it is set as false. In case it is set as true, the award can be awarded multiple times to the same person.

As you can see in the first screen capture, we now can have multiple sets. To get everything working, to create a set named DEFAULT_SET, one should:

- Name the .xml as DEFAULT_SET.xml
- Create the folder /image/awards/DEFAULT_SET
- Inside the previous folder there should be a /medals and a /ribbons folder, where the respective files should be placed.

If anyone wishes to make the default set that will be included in every release, that would be extremely helpful. Just remember that the ribbons will be re-sized to 25x8 and the medals to 28x61 (let me know if you wish to change these values).

I will just take a look into overlapping the medals, which I believe it is the only thing missing before pull requesting this feature. Any tips on that?

**Comment by hell-fish** [comment]
Great work, but I foresee a bit of a problem. Namely, very few canon
medals, ribbons and awards would fit well into a 25x8 or 28x61 pixel
format. Just a quick scan, it looks like much fewer than half the canon
awards would fit well into this format, and many are not even medals or
awards as we know them in the 21st century. http://www.sarna.net/wiki/Awards
Some of them are badges or sashes or draped around the neck. The friggin'
Steiners even have an award made out of an old propeller that could never
look right with the current options.

I think we (er, you - sorry I can't do more than critique) should make some
provision for these now as long as we're setting up the baseline for the
capability. Maybe it could be as simple as adding a 150x150 pixel
option/line or something? I think most of those weird awards could fit into
something like that and still be recognizable, though in some cases we
might just have some extra white space.

Thanks for the excellent work!

**Comment by bandildo** [comment]
@hell-fish thank you for the feedback.

What if we created a third category next to the medals and ribbons, that would accommodate these awards? We could add them in a row above/below the current medal's one. We could also set a maximum size of 150x150, for example, therefore it could accommodate without stretching/resizing anything below those values. It won't be OCD-friendly by allowing to have things of different sizes, however.

This way, anyone who doesn't like the small ribbons, could add the real-size ribbons to this new category and they will appear above the medals in a bigger size.

**Comment by hell-fish** [comment]
Sounds like a great idea. I think below the medals might work best, as you
have a natural progression from small ribbons to average medals to big-ass
weird awards (and 150x150 would also suit things like skill or command
badges and other large odds and ends players may wish to incorporate (like
unit patches, cap badges, regimental crests, morale patches, etc.)

**Comment by NickAragua** [comment]
I still don't get the point of overlapping. I get that that's how people may wear medals on their uniforms, but the personnel info tab is more akin to a medal case than a uniform.

**Comment by mchapman1970** [comment]
sigh. its a wonder how we get anything accomplish with all this going back an forth   in my personal medal program which is like 97% like bloodwolf i give xp and edge points out for certain medals. not becauze of the medal but for the achievement that person had to accomplish to get that medal...and with it being in an xml. guess what u can go in there and change it to ur liking

**Comment by bandildo** [comment]
@pheonixstorm 

> At a minimum you should be able to build the campaign ribbons the way you want, not choose from a list of predefined ribbons that might not even apply to the game setting.

I believe this is addressed by being able to create your awards via the .xml file, or am I misunderstanding your point?

> And why the xp award for getting medals??

When I first started implementing this feature, the only resource someone provided was what @BLOODWOLF333 kindly provided in a zip file, which included XP for each medal. You can easily change the xp awarded in the .xml to zero, so no one is stuck with having to give XP for medals. If you have any other resources, you are still in time to provide them. I can only work with what I'm given. If you don't give me any resources, I can't build anything. Anyway, in case the XP = 0, I will remove the redundant information from the pop-up menu. That will accommodate anyone who doesn't want to award XP with the awards.

> As with ribbons the medals should be create your own. It really limits the feature.

Probably you didn't notice, but having both medals and ribbons is not imperative. In the .xml example I posted here, some awards only have ribbons, others have only medals. Nothing prevents you to create one award per medal.

I'm sorry if my work and time has angered you in any way. It is true that I landed out of nowhere into the development community. I have invested time and effort in this feature, but by any means I don't feel entitled to have it merged into the main branch. I like to program. I like to create. I like games. That's why I am here. Feel free to implement your vision and interpretation of the Award system. I have no issues if mine is not the "chosen one". I'm extremely open to constructive suggestions, as you might have seen by my participation in this thread. Feel free to add constructive suggestions, my ears aren't deaf.

@mchapman1970 would it be useful to include edge points like I've done with the XP? I could look into it, shouldn't be a problem (first I'll need to investigate what are edge points).

**Comment by mchapman1970** [comment]
yeah  but you don't have to I can  add it manually  I could send you some stuff I guess I should of from the beginning  will you have different medal tracks for the different factions?

**Comment by hell-fish** [comment]
I support Bandildo 100%. He's been nothing but cooperative, creative and
open to fair and honest critique. Not sure what crawled up some people's
butts and died, but it's pretty evident to me that the system he made is
very flexible and customizable. I can't wait to use this.

**Comment by NickAragua** [comment]
The fact that the medals/ribbons are defined in XML should be enough for most people, I think. We can put out a relatively small default set, and then others can make or distribute their own sets to their heart content. 

The proposed feature seems to accommodate different sets of medals for different factions. From what it looks like, a user can define a MEDALS_KURITA.xml, then add the images/awards/MEDALS_KURITA folder.  Then it'll show up in its own medal sub-menu. I imagine if someone goes nuts and defines a hundred different medals and medal sets, there may be some issues with usability, but that's not a deal breaker in this case.

Anyway, keep plugging away, still looking forward to the PR.

**Comment by mchapman1970** [comment]
yes I support Bandildo all the way  I am excited to use this  I made medal for all the main factions 
took the medals from BT lore and some of the medal names from real world

**Comment by HammerGS** [comment]
@bandildo A big vote of support for me on this.  I think this is a great start and looks good.  I'm looking forward to seeing the PR, and the coder review of it.  It's something long requested and going to be well received.

I very much look forward to seeing what you have in next, or what tweaks to this you'll do.

**Comment by pheonixstorm** [comment]
By build your own I am talking about doing it in the same manner the force images are created. The same can be done with the medals. Who here has played EVE Online and created medals for their own corp? That is partially what we should strive for in this and what has been discussed off and on for the past year or so.

Its great you are trying to work on this, but a lot of what BW has done is done due to limitations of the program not having a system for campaign ribbons and medals. Such as ribbon, rank, and service placement details which he had to place in the portrait.

**Comment by hell-fish** [comment]
That sounds great, but it’s only been talked about. This is being done. Now.

**Comment by HammerGS** [comment]
@phoenixstorm So create them in GIMP, find modern military sites to steal pictures from, use the images from CGL. 

I for would NOT want to play around with a add this base to this shape, add this color, find a tiny image to add. I’d say the majority of the players want canned canon medals and ribbons.

**Comment by pheonixstorm** [comment]
The design for the feature was not that difficult and was based on per contract/mission rather than randomly setting ribbons or medals per person. Which is more annoying. Applying ribbons to 3 dozen personnel or building one ribbon per contract and letting the software handle the assignment?

I know there are canon medals, but I don't recall seeing any canon ribbons. They may well be out there but I don't remember any...

**Comment by pheonixstorm** [comment]
More like the assignment from Mechcommander rather than simulating real world military

**Comment by mchapman1970** [comment]
@bandildo  are you on slack also??

**Comment by bandildo** [comment]
Thanks everyone for the support. Really appreciate it :)

> From what it looks like, a user can define a MEDALS_KURITA.xml, then add the images/awards/MEDALS_KURITA folder. 

Exactly. Or just KURITA.xml and have ribbons and medals. Or KURITA_RETRO.xml and have some retro looking awards, while having some modern looking version in KURITA_MODERN.xml. You are, however, not forbidden to award the corresponding award of a different set. In other words, if you award a person with "Destroyed 10 Mechs" in the KURITA_MODERN, it's up to you to not give it again using the KURITA_RETRO.

> By build your own I am talking about doing it in the same manner the force images are created. The same can be done with the medals.

I understand your idea. However, personally, I'm not the biggest fan of that system's concept. It is a bit too much of the reinvention the wheel, a simplified implementation of GIMP or Photoshop (which HAS it's value!). I have nothing against that being used for the medals, but I will not personally implement it. It would become a task, and not hobby.

> program not having a system for campaign ribbons and medals.

If I understand right, this is what we discussed before in regard of awarding automatically medals/ribbons after mission/campaign completion. What I'm implementing right now it is not that. This can be re-used for such a system, but it is not substituting that system. Feel free to open a ticket request for automated award awarding. Quoting myself from 5 days ago: "I really enjoy the idea of auto-awarding some awards, it is always rewarding for a player to get something automatically. Also some "loyalty" awards would be interesting, for every X contracts completed for faction Y." So, I would say, without a single drop of promise and/or commitment, that I could be a candidate to implement such a system.

> In that case, loading all the medals at once may wind up using a lot of unnecessary memory, which may become a problem for lower-end systems. I would suggest implementing a mechanism for loading medal images on the fly and caching them (perhaps discarding the least recently used ones).

If I'm not mistaken, this has been taken care of. The awards just store the filename, and only when the personal panel is drawn it will get the image. Basically, when you open the pop-up menu by right-clicking, you only have in memory a list of Awards with the strings/integers presented in the .xml. Any coders are welcome to review this once it gets PR.

@mchapman1970 I am not, but I will.

**Comment by VampireSeraphin** [comment]
This looks like some amazing work from a quick skim. I didn't see though, will this system support selecting multiple personnel at once and giving them all the same award? That could be super handy if you deploy infantry and vees with large crews.
