### ISSUE TITLE
[RFE] New convoy scenarios have unclear resolution screen - Costs & Payouts

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5478]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

This is what is provided on the 'costs and payouts' screen, it is unclear what 'none' is and what the 8 parts are.
![image](https://github.com/user-attachments/assets/88fadede-5c6b-4164-bbec-46daac3f59f8)
Ideally it would provide a list of parts and not have unnecessary verbiage for clarity. Discussed with Illiani who requested the RFE.

### MekHQ Suite Version *

12/16 Logistics Artifact / 0.50.02 SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
