### ISSUE TITLE
[Nightly 12-20-24] AutoLogistics orders reset values

### ISSUE THREAD

**Issue by LadyAdia** [MegaMek/mekhq#5479]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

While in Parts In Use, I attempt to set some parts to 0% to avoid ordering (due to weight, cost, etc.) and others to higher levels of desired in-stock (ammo, armor). When I change the list order, click to manually buy or sell, or when the automatic orders are placed, all requested in-stock resets to the default 10% and places the orders at that level. This leads to large backlogs of undesired equipment and suboptimal levels on others.

### Steps to Reproduce

1. In Parts In Use, set items to 0% requested stock (or any value)
2. change the listing sort
3. check the requested stock on the items changed

### Operating System *

Mac

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0.50.02 Nightly

### Attach Files

[MHQ AutoLogistics Bug 24-12-21.zip](https://github.com/user-attachments/files/18217782/MHQ.AutoLogistics.Bug.24-12-21.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved.

@Lapras if you include a line in your PR description that says something like `Closes #1234` or `Fixes #1234` GitHub will automatically close the cited PR when your PR is merged. :)

**Comment by UlyssesSockdrawer** [comment]
This one looks to be merged and intended to be closed, so marking it as fully closed.
