### ISSUE TITLE
BTH ignored during Mass Repair

### ISSUE THREAD

**Issue by servo01** [MegaMek/mekhq#548]
43.4 mass repair/salvage - min BTH numbers ignored, regardless of settings. 

Techs keep destroying parts by attempting repairs that need BTH > 12.

**Comment by Nightstalker17** [comment]
I happen to have the same issue with 0.43.4. Tested different kinds of settings (pod-mounted equipment etc) in several combinations, all with the same result.

**Comment by scJazz2** [comment]
same problem in 0.43.5?

**Comment by Nightstalker17** [comment]
Excuse the stupid question... but how do I get 0.43.5? I can only find a 0.43.4 release to download

**Comment by scJazz2** [comment]
Not a stupid question actually... http://bg.battletech.com/forums/index.php?topic=59401.0

**Comment by Nightstalker17** [comment]
Thanx for the hint. Tested it with 0.43.5, the problem is still occuring.

**Comment by neoancient** [comment]
Fixed in 4dd94b7.
