### ISSUE TITLE
[Nightly 12-20-24] AutoLogistics requesting incorrect parts when variants of the same part exist in some cases

### ISSUE THREAD

**Issue by LadyAdia** [MegaMek/mekhq#5480]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

In this specific instance, I have four different aerospace sensors in my parts in use list. When autoLogistics attemprs to place an order for spares of these components, instead of requesting one of each type, autoLogistics orders multiples of a single type. When the week advances into the new week, regardless of the parts received in that week, autoLogistics will continue to order multiple of that same part until it is turned off, potentially leading to massive overstock over time. So far, I have only loticed this on aerospace sensors, but I have a small campaign and thus there may be more that I'm not seeing.

### Steps to Reproduce

1. Have multiple aerospace sensors of different weights in parts in use
2. allow autoLogistics to run
3. check the actual ordered parts

### Operating System *

Mac

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0.50.02 Nightly

### Attach Files

[MHQ AutoLogistics Bug 24-12-21.zip](https://github.com/user-attachments/files/18217799/MHQ.AutoLogistics.Bug.24-12-21.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
