### ISSUE TITLE
[RFE] Add game world tech internships to Education module

### ISSUE THREAD

**Issue by HobbitDerrick** [MegaMek/mekhq#5483]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

The most famous game world, Solaris VII, has Character Creation paths in the RPGs for internship (warriors, techs, admin personnel). The brutal games on Galatea are noted as a place used for "testing" potential recruits to mercenary units. Hardcore (in the MoC) and Westerhand also had long-running Mek arenas that served as proving grounds for warriors and technicians alike.

Adding abstract participation in the games themselves may not be desirable when concrete participation is doable in MekHQ, but technician internships seem promising. It would be nice to have Solaris VII, Galatea, Hardcore, and Westerhand internships as Education options, following the same style as Prestigious Academies. If there's a concern that these options would not be distinctive, I suggest making them cheap or free but applying a loyalty check at the end of the internship to determine whether the intern returns to the unit or accepts a job offer at the arena.

**Summary**

I'm requesting four new Prestigious Academies in the Civilian Category:

Solaris VII Internship
Galatea Games Internship
Hardcore Games Internship
Westerhand Games Internship

Each should have a "course" that provides Mek Tech (Regular) and Scrounge (Green) skills.

### MekHQ Suite Version *

V0.50.02 Nightly

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by LadyAdia** [comment]
I can probably fold this into the academy project I'm working on. I'll add it to my list

**Comment by IllianiCBT** [comment]
Is this not covered by the Local Academy 'academies' `Tech Apprenticeship`?

**Comment by LadyAdia** [comment]
Arguably it is, unless we want to consider Solaris a prestigious academy. An argument could be made for it

**Comment by IllianiCBT** [comment]
Prestigious Academies are academies that are specifically named in canon, Local Academies are used to account for academies we can assume exist but are explicitly named in canon sources.

**Comment by IllianiCBT** [comment]
Closing as already implemented. If you think this has been closed in error, let us know and we can reopen it.
