### ISSUE TITLE
[v.0.50.02 Nightly 12-20-24] Previously rejected person from prestigious academy able to reapply after graduating from another academy

### ISSUE THREAD

**Issue by LadyAdia** [MegaMek/mekhq#5498]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

See [https://discord.com/channels/458705327911731231/458706545379639296/1320216433510187059](url)

Testing process: Take personnel who has previously been rejected by a prestigious academy. Send them to another academy (local or prestigious) of the same education level that will advance the highest education level. Upon return, the academy that had previously given rejection was available to apply. In both cases I have seen this, the applicant was accepted.

This bug seems inconsistent and does not happen every time.

### Steps to Reproduce

See description

### Operating System *

Mac

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0.50.02 Nightly

### Attach Files

[MHQ Academy maybe bug maybe feature 24-12-21.zip](https://github.com/user-attachments/files/18220639/MHQ.Academy.maybe.bug.maybe.feature.24-12-21.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
