### ISSUE TITLE
[v.0.50.02 Nightly 12-21] NPE upon contract acceptance 

### ISSUE THREAD

**Issue by LadyAdia** [MegaMek/mekhq#5500]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

Upon accepting a new contract, I was informed about the logistics requirements. After that, an NPE was thrown, and the mothballing and begin transit prompts were skipped. Autosave is the most recent from the day before.

### Steps to Reproduce

Accept contract from market

### Operating System *

Mac

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0.50.02 Nightly

### Attach Files

[MHQ New Contract NPE 24-12-21.zip](https://github.com/user-attachments/files/18220789/MHQ.New.Contract.NPE.24-12-21.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
