### ISSUE TITLE
[v.0.50.02 Nightly 12-20]

### ISSUE THREAD

**Issue by LadyAdia** [MegaMek/mekhq#5505]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

NPE thrown when attempting to start a scenario. Current only means of resolving scenarios is through ACAR. Save file included in archive is just before beginning scenario.

### Steps to Reproduce

Click "Start Game" in Briefing Room tab

### Operating System *

Mac

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0.50.02 Nightly

### Attach Files

[MHQ Scenario NPE 24-12-22.zip](https://github.com/user-attachments/files/18222715/MHQ.Scenario.NPE.24-12-22.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Based on the discussion on Discord, this should be already fixed as of last night's nightly. Closing as resolved, but we can re-open if needed.
