### ISSUE TITLE
[RFE] Logistics Module: Enhance Convoy Intercept Scenario Outcomes

### ISSUE THREAD

**Issue by UlyssesSockdrawer** [MegaMek/mekhq#5508]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

Per discussion in Discord, outcomes from convoy intercept scenarios can be enhanced further.

Comment/suggestion verbatim from chat:

"My assumption on how it would work for an intercept scenario would be something like this:

Best outcome: I defeat the enemy, and extract X% of convoy vehicles from the opposite map edge. I receive supplies up to surviving % of convoy vehicles capacity plus any salvage.

Moderate outcome: X% of convoy escapes from opposite board edge without me destroying the enemy/controlling the board - I receive % of surviving vehicles supplies but no salvage. Anything on the field (knocked out vees, meks, etc.) is lost as salvage to OpFor.

Flee outcome: X% of the convoy escapes from their starting board edge. Resupply is lost, but convoy vehicles and crews survive. Anything lost on the field is fully lost. OpFor receives a supply/morale boost.

Worst outcome: I lose. OpFor receives a supply/morale boost."

Per Illiani - this will likely require a special handler.

### MekHQ Suite Version *

0.50.02 -> Future

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
