### ISSUE TITLE
[0.43.5-git] Menu image size issue

### ISSUE THREAD

**Issue by Qwertronix** [MegaMek/mekhq#551]
Discussed in Slack but putting it here for tracking: 

At 1920x1080 resolution, MekHQ fills up the screen at launch, with the bottom of the screen (including the buttons) ending up "under" the task bar until the MekHQ window is maximized via double-click on the title bar or drag-n-drop to the top of the screen. 

Looks like this: 
![image](https://user-images.githubusercontent.com/360217/33260032-b2c7403e-d32c-11e7-9a28-754d6618f021.png)

**Comment by Dylan-M** [comment]
We should be checking both max width and max height in any fix for this issue. Since we should never make assumptions about monitor resolutions. We can have a minimum defined, but aspect ratios can vary widely, especially with the newer ultrawide monitors.

**Comment by sixlettervariables** [comment]
This is fixed in 0.45.X.
