### ISSUE TITLE
[RFE] Distinguish between scenario defeat and scenario non-engagement

### ISSUE THREAD

**Issue by HobbitDerrick** [MegaMek/mekhq#5515]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

**Summary of Requested Enhancement**

- Add a new category of Scenario outcome, "Refused Engagement", to use when the player decides not to deploy forces to a scenario. This should be displayed in the Command Center's Daily Activity Log and Current Objectives boxes, and in the Briefing Room's mission summary.
- Amend the reminder ("nagging") text for advancing to a new day without engaging scenarios to ask if the player wants to refuse engagement.

It may be desirable to explain the VP cost for Refused Engagement as _spending_ a CVP (implying a choice) rather than taking a penalty (which suggests doing something wrong).

**Discussion**

The current setup flags scenarios that go without player participation as "Defeat". This isn't entirely accurate and has an undesirable "feels bad" factor. Combined with the reminders, this could lead to players feeling that they have to engage will all scenarios (even though this isn't intent) and suffering from negative play experiences.

### MekHQ Suite Version *

V0.50.02 Nightly

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved

**Comment by IllianiCBT** [comment]
Closing as resolved... again...
