### ISSUE TITLE
12/16 Logistic Artifact / 0.50.02 SNAPSHOT - Kitchens still allow prisoners to come get hot meals meant to raise morale of fighting personnel

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5517]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

![image](https://github.com/user-attachments/assets/05be3822-dc87-4dbc-b046-35e0fc07c986)
![image](https://github.com/user-attachments/assets/4a438995-aa25-4bbc-be5d-0971e58720e5)
Gaining prisoners took my capacity to feed my crew out. Releasing my prisoners freed it up, it seems to be letting them go to the food trucks rather than having them on efficient rations.

### Steps to Reproduce

1. Have field kitchens
2. Acquire prisoners
3. Notice how capacity gets eaten up by prisoners

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/16 Logistics Artifact / 0.50.02 SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
I need a save for this, please :)

**Comment by OrbMonky** [comment]
[logs.zip](https://github.com/user-attachments/files/18232480/logs.zip)
As requested!

**Comment by IllianiCBT** [comment]
Closing as resolved
