### ISSUE TITLE
12/16 Logistics Artifact / 0.50.02 SNAPSHOT - Unit deployed to scouting assigned to 'pivotal engagement' on sector 0, no such engagement seems to exist

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5519]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

![image](https://github.com/user-attachments/assets/5edbb1e2-aa74-4f6f-9392-80c0766c5a76)
![image](https://github.com/user-attachments/assets/fdba86f5-1273-4518-9d31-ec82422135ec)
Gamma Lance - AC - Mek Medium, Alpha Company seems to have stumbled upon an invisible mission (I knew ghost missions were real!)

I cannot reinforce them and they will surely die or fail in this 'critical' mission. This may be due to scout lances being assigned to adjacent missions in 12/16's build, but it seems it place a critical mission off the map perhaps? there is an adjactent hex grid off-map, that is my only lead.

[logs.zip](https://github.com/user-attachments/files/18233030/logs.zip)

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/16 Logistics Artifact / 0.50.02 SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by OrbMonky** [comment]
[Hel's Vanguard30270108.cpnx.gz.zip](https://github.com/user-attachments/files/18233152/Hel.s.Vanguard30270108.cpnx.gz.zip)
Here is a save from that day before the scouts were assigned, this seems to be reproducible by deploying the scouts alongside the edge of the map. The following is what occurred during the test I ran off of this save.
![image](https://github.com/user-attachments/assets/dca02300-ea7b-431d-b8e4-a092cca9df11)
![image](https://github.com/user-attachments/assets/dc6afc54-27a6-4a5d-8f2a-a3a63bbf534e)
![image](https://github.com/user-attachments/assets/b0774450-42db-46b1-9e72-f83152532eba)

**Comment by IllianiCBT** [comment]
Closing as resolved
