### ISSUE TITLE
Uncaught Exception Accepting Contract - Clan Faction - 0.50.02 Nightly 12.21.2024

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/mekhq#5520]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

I set up my unit as a Clan Smoke Jaguar cluster in 2991.  I generated two contracts and accepted one.  After clicking the first pop-up saying that the opfor was beneath my capabilities, I got the logistics notice.  After clicking through that, I got the Uncaught Exception pop-up.

I didn't see anything immediately after the Uncaught Exception pop-up indicating that something was going to crash, but I classified this as "High" since these shouldn't be coming up anyway.

I included the logs and the saved campaign files.

### Steps to Reproduce

See above

### Operating System *

Windows 11

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0.50.02-SNAPSHOT Build Date 2024-12-21T03:20:06.256755481

### Attach Files

[UncaughtException 12.23.2024-1logs.zip](https://github.com/user-
[4th Jaguar Dragoons29901220.cpnx.gz](https://github.com/user-attachments/files/18233410/4th.Jaguar.Dragoons29901220.cpnx.gz)
attachments/files/18233405/UncaughtException.12.23.2024-1logs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by BLR-IIC** [comment]
It looks like the logs never uploaded:
[UncaughtException 12.23.2024-1logs.zip](https://github.com/user-attachments/files/18233423/UncaughtException.12.23.2024-1logs.zip)

**Comment by IllianiCBT** [comment]
This has already been fixed in the current nightly. Closing as resolved.

**Comment by BLR-IIC** [comment]
Sorry about that - I forgot to search the closed issues and searched only the open ones.

**Comment by IllianiCBT** [comment]
No blood, no foul. I'd rather have the odd case that is unnecessary than have issues missed because they weren't reported. :)
