### ISSUE TITLE
Uncaught Exception on Advance Day (likely for Training Combat Teams)

### ISSUE THREAD

**Issue by HobbitDerrick** [MegaMek/mekhq#5530]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

On attempt to advance to a new Monday, the date did not change, though the target new date was appended to the Activity Log for the Sunday I was leaving. No other activity was added to the in-game Log.

MekHQ log seemed to indicate an error relating to Combat Teams Training, which makes sense as I had Training teams deployed.

### Steps to Reproduce

I'm not 100% sure how to reproduce, but likely:

1. Deploy Training Combat team(s?)
2. Advance days through to the Monday after next

It may be necessary to load a saved game to reproduce this issue.

### Operating System *

Windows 10

### Java Version *

17.0.13

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0.50.02-SNAPSHOT     Build Date: 2024-12-23T03:23:45.514569973

### Attach Files

[logs.zip](https://github.com/user-attachments/files/18242436/logs.zip)
![mekhqlogheader](https://github.com/user-attachments/assets/abb36ba1-3928-474c-a792-b8591ad61752)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by HobbitDerrick** [comment]
Oh, OK. Here's the save at point of error.

[Task Force Shelob27840604.cpnx.gz](https://github.com/user-attachments/files/18247602/Task.Force.Shelob27840604.cpnx.gz)

**Comment by IllianiCBT** [comment]
Looks like this _was_ resolved by the first I pushed the other day. Closing as resolved.
