### ISSUE TITLE
[RFE] Improvements to "Scenario Setup Wizard"

### ISSUE THREAD

**Issue by BlueThing00** [MegaMek/mekhq#5533]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

When I get to the Scenario Setup Wizard by doing Manage Scenario in the Area of Operations, I've run into a couple of UI impediments that I'd like to see improved.
![image](https://github.com/user-attachments/assets/43aa3836-da83-4840-80f4-01fa56732904)

1) The force selection UI does not scale with the window size, and starts out quite small.  Particularly for the Auxiliary Unit selection, that can be annoying because I like to have a fair number of support units to provide flexible reinforcements.

2) The Auxiliary Unit selection UI has no way to filter out non-combat forces.  I really don't plan to use my Field Kitchens or similar units to reinforce.  I'd like them hidden by default, with a "show non-combat forces" checkbox to override that behavior.

### MekHQ Suite Version *

v50.1

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
This should already be mostly resolved in 50.02.

**Comment by BlueThing00** [comment]
Sounds good.  If this is done and/or tracked elsewhere, no need to keep this issue open.  :)
