### ISSUE TITLE
Typo in specific convoy transmission

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5534]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

![image](https://github.com/user-attachments/assets/3b82058d-ac1f-46a9-b43a-fa3649e58f13)
On this particular transmission, there appears to be an omission of a word at the end of the second sentence;

"Artillery impact has been primarily concentrated on rear positions, with limited effectiveness against."

In this case, it doesn't specify what the effectiveness is 'against'.

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/16 Logistics Artifact / 0.50.02 SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
