### ISSUE TITLE
Mass Repair/Salvage Button Broken during active campaign

### ISSUE THREAD

**Issue by Flibjib** [MegaMek/mekhq#554]
My Mass Reapir/Salvage function has spontaneously broken over the course of my campaign. Hitting it does nothing, regardless of what settings I have. The buttons maintain the "pushed" color for a few seconds, and then nothing happens.

Looks like an NPE in the logs
[Wolven Winter30290125.cpnx copy.zip](https://github.com/MegaMek/mekhq/files/1525080/Wolven.Winter30290125.cpnx.copy.zip)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1525081/mekhqlog.txt)

**Comment by neoancient** [comment]
The method that selects which tech to use based on experience and time remaining was not correctly handling situations where all criteria are equal.
