### ISSUE TITLE
12/26 Nightly / 0.50.02 SNAPSHOT - Mass Training dialogue won't allow adjustment of Target Skill Level field.

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5542]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Seems there is possible regression in the Mass Training again, now it is usable but has a hard-locked default of 10 for the target skill level;
![image](https://github.com/user-attachments/assets/5ed33645-5cdc-4038-96f3-5909baac501d)
[logs.zip](https://github.com/user-attachments/files/18264422/logs.zip)

### Steps to Reproduce

1. Attempt to use Mass Training
2. Attempt to set Target Skill Level

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/26 Nightly / 0.50.02 SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
Closing as resolved
