### ISSUE TITLE
12/26 Nightly / 0.50.02 SNAPSHOT - Unable to get contracts from some periphery factions in mid 3020's

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5544]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

Cant get contracts to generate on the northern group of mini-factions in the latest versions, was able to do son in 0.50.00 and wonder if there may have been a regression or misapplication of odds/data?

I used to be able to run missions for Morgraine's Valkyrate, Chainelane Isle, Oberon Confederation, Elysian Fields, and even GM moving into their territory I am seeing nothing but Lyran Commonwealth/Draconis Combine missions. Genning ~200 contracts on Gotterdamerung, Elissa, Placida etc created all Draconis Combine and Lyran Commonwealth contracts with only 6 Chainelane Isles contracts, and I wasn't able to gen any other faction in my test, though the low odds suggest it could be down to absolute luck.

This is in stark contrast to prior versions which often had contracts from minor periphery states, so I am filing this to ensure something isn't broken. I asked on discord but it didn't seem to get any notable input. It would be good to be able to generate contracts for periphery states again.

![image](https://github.com/user-attachments/assets/f20af389-d20e-43cb-98b2-49be26daa01d)
![image](https://github.com/user-attachments/assets/f37dbd42-2da1-4115-b4c0-ee433ccbb0e8)
[logs.zip](https://github.com/user-attachments/files/18264633/logs.zip)

### Steps to Reproduce

1. While not on contract, locate to a periphery state
2. Spam that generate contract GM button
3. Note the amount of contracts, relocate, repeat

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/26 Nightly / 0.50.02 SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
@HammerGS has anything changed data-wise for these factions?
