### ISSUE TITLE
entity.crew not being reset after scenario resolution

### ISSUE THREAD

**Issue by Qwertronix** [MegaMek/mekhq#555]
This leads to the crew properties of a unit (e.g. a Mech's commander stats) to not be reset inbetween battles. Among other possible issues, this seems to be the root cause of #553 .

**Comment by pheonixstorm** [comment]
easy enough to fix.

**Comment by Qwertronix** [comment]
...after looking into this some more, this may also be the root cause for https://github.com/Qwertronix/mekhq/issues/3 which I thought was the same as #464 and #324, but it turns out the latter are probably just the "forced death" problem I discuss in PR #552, while the issue I was running across comes from this entity.crew being carried over.

**Comment by neoancient** [comment]
What do you mean by "a Mech's commander stats"?

**Comment by Qwertronix** [comment]
The `entity.crew.unitcommander`'s pilot/gunnery/fatigue/injuries/etc... basically the MM data structures that store information about the primary pilot of a unit for any unit not using an average. That was as one example of data that is pulled back after battle resolution but wasn't really being cleaned up. 

AFAIK that's been fixed now?

**Comment by neoancient** [comment]
The crew stats are recalculated with every call to `Unit.resetPilotAndEntity()`, which includes piloting, gunnery, and hits, command/init bonuses, SPAs, and as of this morning now resets the fatigue counter as well. Without a specific example of something not being recalculated I don't know what I'm supposed to be looking at.

**Comment by Qwertronix** [comment]
`The crew stats are recalculated with every call to Unit.resetPilotAndEntity(),` <-- this wasn't the case when this issue was filed. I believe it should be resolved now as I haven't seen related issues crop up in 0.43.6+
