### ISSUE TITLE
[RFE] Improve Combat Team Role language for clarity

### ISSUE THREAD

**Issue by HobbitDerrick** [MegaMek/mekhq#5556]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

**Summary**

I am proposing changes to three Role names for Combat Teams:

- Frontline becomes **Maneuver**
- Garrison _preferably_ becomes **Frontline** (see discussion)
- Recon becomes **Patrol**

I am also requesting minor amendment to the "Combat Teams, Roles, Training
& Reinforcements" documentation to respect these changes.

**Discussion**

It was pointed out in the MegaMek Discord that the "Frontline" term potentially misleads players. While the term suggests the main force, the label is used for a flexible role well-suited to reinforcing the main body in scenarios. I still think that the advice to use this role effect as default is correct, regardless of name. Having the documentation tell players that more Maneuver teams are almost always good in the fluid campaigns of BattleTech should go down well.

The label "Garrison" adds to this problem, as that role is currently the best-suited to slower combat elements earmarked for the initial engagement. This is true even when the player seems to be on the tactical offensive, as the mines or infantry can help protect the flank of attacking elements. This is likely to match best with player intuition for the term "Frontline". (However, if it's felt that swapping the term "Frontline" from one role to another is too confusing for those testing the Nightlies, language like "Center", "Static", or even figurative terms like "Anchor" might work instead.)

Finally, while the term "Recon" is excellent and Patrol would normally be a 2nd-best option, "Recon" repeats language used in _Campaign Operations_ for a Formation type. Even if the Formation types are never implemented, it's still better to use distinct language to reduce misconceptions.

### MekHQ Suite Version *

V0.50.02 Nightly

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment]
I really wish you put this in yesterday. I'll see what I can do.

**Comment by IllianiCBT** [comment]
Closing as resolved.
