### ISSUE TITLE
Splash Screen Edges

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/mekhq#563]
0.43.5 MekHQ release (the real one)
The HQ start up screen has the right and bottom edges of the image chopped off.

![github](https://user-images.githubusercontent.com/16950832/34136656-9c6b450e-e42c-11e7-87f0-ccdd8ae95541.png)

And the HQ loading screen has the top and maybe the bottom edge is supposed to be chopped off?

![github0](https://user-images.githubusercontent.com/16950832/34136681-b639877a-e42c-11e7-822d-657b9b4f3810.png)

**Comment by wildj79** [comment]
To be honest with you, I'd rather see the beveled edges removed or cutoff completely.

**Comment by Dylan-M** [comment]
I think this must be related to some resolution/scaling issues since I don't have this happen on my large screens.

**Comment by sixlettervariables** [comment]
I believe I fixed this in 0.45.3.
