### ISSUE TITLE
Repair Bay Tech Portrait Scaling

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/mekhq#564]
However HQ 0.43.5 is scaling the portraits down is also chopping off the edges....and it just looks bad.
[TechPortrait.zip](https://github.com/MegaMek/mekhq/files/1570042/TechPortrait.zip)

![github1](https://user-images.githubusercontent.com/16950832/34136733-02b24c90-e42d-11e7-8cc4-60c804082c8f.png)

Whole portrait

![grass](https://user-images.githubusercontent.com/16950832/34136741-0c6edc44-e42d-11e7-92ad-2eef27c3b128.png)

**Comment by Windchild292** [comment]
This is still an issue, but a fix is in progress.
