### ISSUE TITLE
BA standard armor cannot be repaired

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#567]
BA units (clan elementals) with damaged BA standard (basic) armor claim no valid armor is available for repairs even when there is.  Acquiring the right armor via the part acquisition button in the repair tab still does not resolve the issue.  It appears that the armor in the elemental listing is not recognized as the same armor pointed to in the parts listings.  
![ba armor glitch 1](https://user-images.githubusercontent.com/34722287/34238860-015b9792-e5d2-11e7-9a27-e58757670937.png)
![ba armor glitch 2](https://user-images.githubusercontent.com/34722287/34238861-01695328-e5d2-11e7-8753-e6c5004cab86.png)

**Comment by neoancient** [comment]
Please provide campaign file.

**Comment by bczretribution** [comment]
https://drive.google.com/file/d/1tc1mcfPwtaYUIZNquYRmY0Z0ViYkWmXH/view?usp=sharing

Here's the campaign file
