### ISSUE TITLE
error loading old campaign files

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#568]
trying to load an old campaign file after updating to 0.43.5 fails to load any units from the data cache
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1578260/mekhqlog.txt)

campain file
https://drive.google.com/file/d/1mNap4edvP2b67ZCKQEM5Aa7RzyhMdTN5/view?usp=sharing

**Comment by NickAragua** [comment]
There are two custom units, the ST Basilisk BSK-STG, and ST Cockatrice Scout Armor SCA-ST that are missing. Could you supply those?

**Comment by bczretribution** [comment]
https://drive.google.com/file/d/1F2tGw-ZKCDNylaRmOYl0kBRAEDeYGQ4E/view?usp=sharing
https://drive.google.com/file/d/12BVUiS41oGWy7GJStJc7bo13AzbgP1nm/view?usp=sharing

That should be them.

**Comment by NickAragua** [comment]
This should be fixed with PR #821
