### ISSUE TITLE
Dropship capacity Inconsistancy

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#574]
Dropship infantry bays inconsistent between transport breakdown and unit rating/hangar tabs.

![dropship](https://user-images.githubusercontent.com/34722287/34324364-b31a20ca-e83e-11e7-8f27-e2e9139725f9.png)
![dropshiperror](https://user-images.githubusercontent.com/34722287/34324365-b324d010-e83e-11e7-844b-c7c352a97189.png)
![dropshiperror2](https://user-images.githubusercontent.com/34722287/34324366-b32f2632-e83e-11e7-8b13-1e31f4f896ae.png)

campain file:
https://drive.google.com/file/d/1GkGwYa0LI5-nxnpqbKz_nOUlMy3sc4--/view?usp=sharing

**Comment by neoancient** [comment]
The overview tab was showing the capacity by tonnage rather than number of platoons.
