### ISSUE TITLE
Mechs remain damaged after repair

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#584]
Mechs sometimes are defined as having damage in the hangar screen (heavy damage, inoperable, etc. ) after having been fully repaired.  inaccurate damage listing prevents their deployment in megamek.  The occurrence is uncommon (3rd time so far out of several dozen salvages).  Warhammer WHM-6R # 2 reserve in the attached file.
![repair glitch](https://user-images.githubusercontent.com/34722287/34431461-70ae181a-ec3d-11e7-8828-53240f4fa867.png)

[glitch.zip](https://github.com/MegaMek/mekhq/files/1592700/glitch.zip)

**Comment by Flibjib** [comment]
Have you tried saving, and restarting MekHQ? More often than not this will solve the issue. Also make sure the pilot is not injured.

**Comment by bczretribution** [comment]
I hadn't.  I'll try that at the next occurrence and report back

**Comment by scJazz2** [comment]
What version are you using? CPNX? Logs? Customs if needed?

**Comment by bczretribution** [comment]
scJazz, 0.43.6, all the needed files are in the zip that was attached to the original post

**Comment by neoancient** [comment]
The very nature of this type of issue makes it very difficult to track down. Since saving a reloading the campaign clears the error there is nothing in the campaign file that will help us, and it is very difficult to reproduce reliably. I have added some debugging code to MegaMek, which is where the status determination is made, to log the reason for the damaged status in hopes that knowing the reason it was flagged will help us track down the cause.

**Comment by Dylan-M** [comment]
This is almost certainly some transient state that doesn't get reset after a scenario is completed, which is why save/reload clears it.

**Comment by mkraemer67** [comment]
Just FYI this also occurs pretty frequently for me, but I am unsure what actually triggers it. It's far from uncommon though.

**Comment by HammerGS** [comment]
@mkraemer67 What version are you using?

**Comment by mkraemer67** [comment]
v0.43.10 Development Snapshot (0.44 RC4)

**Comment by mkraemer67** [comment]
Actually if a mech shuts down due to heat in the last round of combat for me it is 100% reproducible that the mech stays shutdown in the first round of combat in the next battle. I'd guess that this could be related to the same issue?

**Comment by sixlettervariables** [comment]
It seems like this issue has not been encountered in some time, please reopen this issue if it happens again on a more recent built of MHQ.
