### ISSUE TITLE
[43.6] Cannot set mass edge triggers

### ISSUE THREAD

**Issue by Kendricke** [MegaMek/mekhq#590]
I'm not able to set edge triggers for multiple personnel.  I can ONLY set the "off" status, but not the "on" status.  I can't recall if this was ever actually implemented, but based on https://github.com/MegaMek/mekhq/commit/04ba4ee7141af79833850d87c80b5b6c55766fd3, this seemed to be the case.

**Comment by mkerensky** [comment]
Most likely, this will not work because Edge triggers are now broken up by personnel type.  Currently, only Mechwarriors, Admins, Doctors and Techs can have edge triggers.   Try mass-selecting only those personnel types and see if it works.

**Comment by Kendricke** [comment]
I've attempted this with only Mechwarriors.  I've even confirmed that I've attempted this with just two  Mechwarriors who both already have edge.

**Comment by Kendricke** [comment]
![image](https://user-images.githubusercontent.com/24977517/34489883-c6db71e4-ef92-11e7-9a79-73479121bec2.png)

**Comment by Kendricke** [comment]
Using the command currently will only result in turning OFF triggers that I have already selected.  

![image](https://user-images.githubusercontent.com/24977517/34489951-facb49f2-ef92-11e7-8bfc-1be64d5cbe2c.png)

![image](https://user-images.githubusercontent.com/24977517/34489976-1a1e7d9c-ef93-11e7-8c52-4eed07758396.png)

![image](https://user-images.githubusercontent.com/24977517/34490004-354dca46-ef93-11e7-85c2-c5fbe82d2761.png)

**Comment by Kendricke** [comment]
Campaign file attached:

[Kendricke's Templars30260316.zip](https://github.com/MegaMek/mekhq/files/1597991/Kendricke.s.Templars30260316.zip)

**Comment by Qwertronix** [comment]
I've had the idea of adding an "ON" section to mass set triggers (just like the OFF one) on my todo list for a while, but haven't gotten around to it yet. It'd be just a couple copy pastes and minor edits though. 

Great first issue / first PR too if anyone is new to contributing to Megamek or looking to start helping.

**Comment by scJazz2** [comment]
In the interest of simplicity and QoL... if Edge is added perhaps all triggers should be set automatically, and then allow the user to turn some off. The way the triggers are setup this probably makes sense in the number of clicks required.
