### ISSUE TITLE
Special Abilities can be selected multiple times

### ISSUE THREAD

**Issue by Legendslayer84** [MegaMek/mekhq#591]
When adding special abilities to a pilot in MekHQ, I am able to select sthe same special ability over and over again, and when I do, each time experience is deducted. 
Is it possible to change it in a way, so that either xp will not be deducted when selecting an already active special ability, or that you can not select an active special ability?

**Comment by pheonixstorm** [comment]
The thing with this is that the ability to select the SPA multiple times is the bug so changing the XP deduction isn't what needs to be fixed.
