### ISSUE TITLE
[43.6][ATB] - Can't change camo in ATB created Megamek scenarios; locks up client

### ISSUE THREAD

**Issue by Kendricke** [MegaMek/mekhq#598]
When starting a new scenarior from an Against the Bot mission, I cannot change the camouflage for any team (i.e. civilians; reinforcements).  

Attempting to do so locks up the client and prevents mission start. 

![image](https://user-images.githubusercontent.com/24977517/34652982-5b6f2958-f39a-11e7-93ca-471e7ee1390c.png)
![image](https://user-images.githubusercontent.com/24977517/34652992-7a75dd88-f39a-11e7-8c56-b26b83a39263.png)
![image](https://user-images.githubusercontent.com/24977517/34652999-8cc2b42a-f39a-11e7-8dd0-2c77db83eacb.png)
![image](https://user-images.githubusercontent.com/24977517/34653014-a86bed54-f39a-11e7-8fd6-13384c297568.png)

**Comment by Kendricke** [comment]
[Kendricke's Templars30260404.zip](https://github.com/MegaMek/mekhq/files/1610101/Kendricke.s.Templars30260404.zip)

**Comment by BLOODWOLF333** [comment]
This is a megamek-specific issue and has already been fixed.

https://github.com/MegaMek/megamek/issues/834
