### ISSUE TITLE
After eject will not deploy unit in Megamek

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/mekhq#6]
I believe this is a MekHQ issue.  Shadow Hawk took a large laser to the face and reduce internal structure to 1 so, ejected pilot.  Completed the scenario, repaired the mech, deployed the SH with the lance on the next scenario.  Mech shows up in the megamek lobby with no "invalid unit" or anything to indicate something is wrong.  But once in the game during the deployment phase the Shadow Hawk is missing and am able to deploy only five out of six units.  Remove pilot from the mech then reassigned him to it again, removed the unit from the lance and reassigned, changed pilot status to MIA then back to active, deleted the salvage file in the logs folder, and deleted the entity status file all with the same concern still present.  Finally allowed me to deploy the SH after deleting the unit.cache and mekhq log (to the recycle bin). Almost was a campaign breaker for me.
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/109267/mekhqlog.txt)
[entitystatus.txt](https://github.com/MegaMek/mekhq/files/109268/entitystatus.txt)

*Does not allow attachment of the campaign file or unit cache
"Unfortunately, we don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP."

**Comment by BLOODWOLF333** [comment]
https://sourceforge.net/p/mekhq/bugs/962/

**Comment by pheonixstorm** [comment]
There was another bug sort of like this that was actually an issue with either MM or HQ not clearing some flag properly. Don't recall the details but will go for a quick look and see if I can't find it. It could be related but I don't know.

**Comment by Dylan-M** [comment]
Yes, we'll have to come up with a new official policy regarding how users provide files to us... such as zipping them first ;)

**Comment by BLOODWOLF333** [comment]
[AFFS-FSACRCT-2REG-2BN-ECO30250127.zip](https://github.com/MegaMek/mekhq/files/110564/AFFS-FSACRCT-2REG-2BN-ECO30250127.zip)

**Comment by BLOODWOLF333** [comment]
When I run into this again I will provide the savegame file.  I see I should have done that when it was acting up.

**Comment by BLOODWOLF333** [comment]
I'd say close this, I started over from a template campaign file and have had a few ejects and the pilots have redeployed the next scenario fine(in different replacement mechs).  I cant duplicate this anymore.

**Comment by Saberuneko** [comment]
Hello, I am experiencing a similar issue, but with the Archer mech listed in the roster (see attachment)
This was a micro-campaign thing for mere testing of things and passing time, so it does not have many items (only 3 mechs in hangar) and may make tracking this issue easier:
[Eclipse Warlords.zip](https://github.com/MegaMek/mekhq/files/1690346/Eclipse.Warlords.zip)

Additional information in case it is useful: This happened while playing with Stable: 0.42.2 on ArchLinux

**Comment by BLOODWOLF333** [comment]
Every time I have hit this intermittent impossible to reproduce bug reloading the campaign has always fixed it.  And when a developer would load my campaign the issue would be gone.  Can you exit and reload and see if it disappears for you as well?

**Comment by Saberuneko** [comment]
You are correct, after shutting down the system and booting again, MekHQ behaves as expected.
What a peculiar bug!

Thanks

**Comment by Dylan-M** [comment]
I'm 98% sure this is simply a flag on either the MW or the Mech that we're not clearing properly. I have a better idea now, so I'm going to reopen it.
