### ISSUE TITLE
IS prisoners taken as Bondsmen by Clan are Trueborn MWs

### ISSUE THREAD

**Issue by hell-fish** [MegaMek/mekhq#600]
In MHQ 43.6, Inner Sphere mechwarrior prisoners taken by a Clan player become bondsmen and are converted into Trueborn Mechwarriors as their role. I'd think at the very best they'd be Freeborn Mechwarriors (like vehicle crews taken as bondsmen are considered Freeborn).

**Comment by pheonixstorm** [comment]
I would have to look at the code but it is possible that the flag for bondsmen sets the isClan flag to true. Will try to look into it tonight and see.
