### ISSUE TITLE
Campaign Options Personnel Window

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/mekhq#607]
### Environment
MekHQ 0.43.7-betaJan14
Win 8.1
Java 1.8

### Description
![image](https://user-images.githubusercontent.com/16950832/35185060-87fd07d2-fdc3-11e7-973d-281aa5e186f8.png)

We should probably assume the user has a 800 x 600 resolution for window sizing.  I think that is the "use log saver" rule but I cant click it anymore (bottom left).  Using a 1366 x 768 resolution, it needs a scroller or something just too much stuff packed in there.

### Files
Does not apply

**Comment by Qwertronix** [comment]
In support of this point, while I don't think the software should _assume_ the user has 800x600 (having to constantly resize all windows upwards can be a pain for users at or above 1080p), some effort should go towards better UI support for the 700-900 vertical range, which seems the most common in general when not restricting the dataset to gamers: http://gs.statcounter.com/screen-resolution-stats/desktop/north-america

**Comment by scJazz2** [comment]
All windows should assume a size of NxN. And display scrolls. And Center on the main monitor.

**Comment by BLOODWOLF333** [comment]
Yeah 800x600 probably isnt ideal.  And I would ask that all windows remember how the user sized them previously like some are but, I know thats a ton of stuff to recode so, maybe some day later.

**Comment by pheonixstorm** [comment]
800x600 should be the minimum window size. If anyone is still using it as a resolution I highly doubt they are playing games since most people are using at least 1440 res these days or at worst 1024

**Comment by VicenteCartas** [comment]
There is a PR that should make it to 0.45.4 which will allow MekHQ to remember the size a user resizes any dialog in the app and the position of the screen of the dialog between sessions.

So you can start MekHQ, resize and position the dialog, close MekHQ, and in the next MekHQ launch it will remember your previous settings.

**Comment by Windchild292** [comment]
I have added a scrollbar to this page as part of #1438 , and as such this has been fixed.
