### ISSUE TITLE
background.png appears to have moved in the most recent release

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/mekhq#613]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.

### Environment
What version of MekHQ does your issue apply to? 0.43.7
What operating system are you using?  Windows, Mac, or Linux? Linux
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file. 
Starting MegaMek v0.43.7-RC1 ...
    Compiled on Sun Jan 21 17:51:03 CST 2018
    Today is Sun Jan 21 19:39:18 CST 2018
    Java vendor Oracle Corporation
    Java version 1.8.0_151
    Platform Linux 4.14.14-300.fc27.x86_64 (amd64)
    Total memory available to MegaMek: 932,352 kB

### Description
Describe the issue and provide screenshots ingame if able.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the campaign file if applicable.
This error appears in the log:
MainMenu Error: background icon doesn't exist: /home/mjackson/megamek/mekhq-0.43.7-RC1/data/images/widgets/Bloodwolf/Parts/title/background.png

### Files
Provide the .cpnx campaign file that this issue occurs in.
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the mekhqlog.txt file for any NPE's or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual mekhqlog.txt file

The error occurs on load (before campaign settings are relevant)

**Comment by BLOODWOLF333** [comment]
Did you copy an older release's skin files over into this new version?

The title screen background is the same used for the board background so I got rid of the duplicate image in /Parts/title.

The new skin files have the correct path in them.

> 	<UI_Element>
		<name>MainMenuBorder</name>
		<no_border>true</no_border>
        <background_image>../misc/megamek_splash_spooky_fhd.png</background_image>
        <background_image>Bloodwolf/Parts/boardview/background.png</background_image>
        <background_image>../misc/megamek_splash_spooky_uhd.png</background_image>
        <background_image>../misc/megamek_splash_spooky_hd.png</background_image>
		<tile_background>true</tile_background>
		<font_color>#ffffff</font_color>
		<show_scroll_bars>false</show_scroll_bars>
		<should_bold_mouseover>false</should_bold_mouseover>
	</UI_Element>

>

**Comment by Dylan-M** [comment]
BW, do you need assistance in getting these into the repo properly?

**Comment by BLOODWOLF333** [comment]
Fixed in PR#877.  Suspect copying and pasting over an old release folder.  Lack of communication to assume otherwise. Megamek-specific issue on HQ tracker.

**Comment by Dylan-M** [comment]
Fixed via MegaMek/megamek#877
(Comment added just to properly link to the issue)
