### ISSUE TITLE
[0.43.7-RC1] The planet Adherlwin is owned by 'Star League' in all years/eras after 2583

### ISSUE THREAD

**Issue by RexPearce** [MegaMek/mekhq#615]
To reproduce:
  1) start a campaign in 3025 (Or any date after 2583-04-27)
  2) Go to the Interstellar map
  3) Find Adherlwin
  4) See that it is owned by 'Star League'

While minor, this error can result in broken contracts being generated against the Star League faction. They are broken because the faction doesn't exist in most time periods and thus (correctly) RAT data doesn't exist to generate the SL opposing forces.

Patch to fix error:
```
--- planets.xml-0.43.7-RC1	2018-01-21 18:51:02.000000000 -0500
+++ planets.xml	2018-01-22 00:19:38.049350071 -0500
@@ -1359,10 +1359,6 @@
             <faction>MOC</faction>
         </event>
         <event>
-            <date>2583-04-27</date>
-            <faction>SL</faction>
-        </event>
-        <event>
             <date>2750-01-01</date>
             <hpg>B</hpg>
         </event>
```

Note: I recommend just deleting the event altogether. It looks like the event was added to reflect a brief SL occupation during the Reunification War, except that none of the other SL occupations appear elsewhere in planets.xml, so I'm not sure why this was one singled out for inclusion.

**Comment by HammerGS** [comment]
Often work is started on Planets and not finished which creates issues.  Rather than delete the old entry it would be better to add the missing entries.

**Comment by Dylan-M** [comment]
@BLOODWOLF333 We cannot, for legal reasons and data integrity reasons, pull data from an online source. Ever.

We cannot take anything directly from Sarna, ever. Just like we can't take things word for word from the sourcebooks.

As for pulling in data for planets, there is no single source. Anything you do like this will completely wreck the _thousands_ of manhours that have gone into doing planets correctly from multiple sources.
