### ISSUE TITLE
[0.43.7-RC1] Unused bombs are not recovered for VTOLs after battle

### ISSUE THREAD

**Issue by RexPearce** [MegaMek/mekhq#620]
To reproduce:
 1) Load the attached campaign which has a battle queued up
 2) Note that "MegaMek Options->Advanced Combat->TacOps VTOL Special Attacks" is enabled
 3) Note in the hanger that the VTOL has 5 bombs loaded (and the fighter has 4)
 4) Launch the mission, deploy all units, then end it after the first turn with "/victory" (without using any bombs)
 5) After the mission, in the hanger note that fighter still has its bombs, but the VTOL does not.

**A related bug:** After the mission, in the hanger view, the VTOL's bombs are actually shown as integrated weapons on unit. However, saving the game and reloading it restores the unit back normal, but still without the unused bombs.

[My Campaign30250202-vtol-bombs.zip](https://github.com/MegaMek/mekhq/files/1653701/My.Campaign30250202-vtol-bombs.zip)

**Comment by NickAragua** [comment]
This was a two-pronged issue:
1) MekHQ wasn't actually saving the bomb selection for the VTOL in the saved game. 
2) There was an issue preventing the bombs from displaying properly on the "unit summary" when clicking "view unit".

**Comment by NickAragua** [comment]
It just occurred to me that there might still be an issue when resolving a battle directly from Megamek as opposed to "Resolve Manually" by supplying a MUL file. I'll take a look sometime tonight.

**Comment by RexPearce** [comment]
A minor related bug: looks like the bomb text is truncated in the Hanger view. i.e. it says "HE Bomb (4" instead of "HE Bombs (4)".

**Comment by NickAragua** [comment]
Bombs should properly clear for VTOLs and LAMs as well as aeros through all possible scenario resolution paths. Fixed the parens as well. One minor issue is that, in the initial screen where you review units, the VTOLs will still show up as having "light damage", and the View Unit screen will show the list of individual bombs, as opposed to the HE Bomb (5) text. However, in the interest of minimizing changes prior to stable, I'm going to leave that for now.
