### ISSUE TITLE
[0.43.7-RC1] Clanner flag not being set on captured Clan personnel

### ISSUE THREAD

**Issue by RexPearce** [MegaMek/mekhq#621]
To reproduce:

1. Load the attached campaign which has a battle against the Clan queued up
2. Launch the mission, deploy all units, then end it after the first turn with "/victory", with your side controlling the battlefield.
3. In salvage resolution, uncheck 'escapes' on all enemy units, then check 'captured' all on enemy personnel.
4. After the mission, in Personnel->Prisoners, note that none of the prisoners have the 'clanner' flag set.

[My Campaign30500306-clan-battle.zip](https://github.com/MegaMek/mekhq/files/1654081/My.Campaign30500306-clan-battle.zip)

**Comment by RexPearce** [comment]
This might be related to issue #600. Maybe captured personnel are always set to be the same faction as the player.

**Comment by pheonixstorm** [comment]
It is more likely that there is no clan flag passed from MM to HQ after a fight. This could be the same type of issue as not having a male/female flag passed between MM and HQ.

**Comment by NickAragua** [comment]
Fixed by PR #726
