### ISSUE TITLE
Random Date Generation Groups Events

### ISSUE THREAD

**Issue by JWest82** [MegaMek/mekhq#626]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.

### Environment
What version of MekHQ does your issue apply to?
*0.43.3*
What operating system are you using?  Windows, Mac, or Linux?
*Windows*
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.
*8 u161*
### Description
Describe the issue and provide screenshots ingame if able.
*Random date generation per the notes in the news.xml works but generates all events as a single group. For example, 10 events with only 3046 will all generate on the same date, randomly in 3046. 10 events with the date of 3046-01 will generate on the same day, randomly, in January 3046.*

![image](https://user-images.githubusercontent.com/33674850/35291548-99c8931c-003b-11e8-8cb5-d724c717a674.png)

![image](https://user-images.githubusercontent.com/33674850/35291567-ae3de388-003b-11e8-82b4-ec82078cbc19.png)

Provide the rulebook, page number, and text if you feel like this is a rules issue.
*N/A*
And provide the steps you have taken to reproduce the issue in the campaign file if applicable.
*Tested against year only entries and year and month entries. Reproducible.*

### Files
Provide the .cpnx campaign file that this issue occurs in.
*N/A*
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
*N/A*
Provide any other files that you have customized in this campaign like the factions.xml for example.
*N/A*
And provide the mekhqlog.txt file for any NPE's or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual mekhqlog.txt file

**Comment by wildj79** [comment]
I think I've found the culprit, `NewsItem.finalizeDate(long)` creates a new `Random` object with the same seed for every news item, instead of sharing a common `Random` object. Since it's the same object with the same seed for each news item, it will produce the same sequence of numbers every time.
