### ISSUE TITLE
Heat sinks not tracked correctly by Mek Lab and Warehouse

### ISSUE THREAD

**Issue by RexPearce** [MegaMek/mekhq#630]
To reproduce:

1. Load the attached campaign which has two mechs ready to be customized
2. Note in Warehouse that 12 single heat sinks are available
3. In Hanger, select the Night Hawk NTK-2Q to be customized in Mek Lab
4. In Mek Lab, change the heat sink type from double to single and assign the critical locations
5. **Bug:** Auto Fill will not assign the heat sinks at this point - need to assign manually
6. **Bug:** Note that Mek Labs list 8 single heat sinks required for the refit instead of none (i.e the warehouse is not being checked for the engine-free ones)
7. begin the refit
8. **Bug:** Note in Warehouse that only 4 heat sinks are reserved for the refit instead of 12 (and the remainder have not been ordered)
9. Advance the day until refit is complete
10. **Bug:** Note that Warehouse shows 8 single heat sinks available instead of none.

Upgrading from single to double heat sinks has the same result:

1. Note in Warehouse that 12 double heat sinks are available (and 8 single)
2. In Hanger, select the Warhammer WHM-6R to be customized in Mek Lab
3. In Mek Lab, change the Tech Level to advanced
4. Change the heat sink type from single to double and reduce the count to 12
5. Add 4 jump jets and 2 tons of armor to add weight
6. Assign the critical locations
7. **Bug:** Auto Fill will not assign the heat sinks at this point - need to assign manually
8. **Bug:** Note that Mek Labs shows 11 heats required for the refit instead of none (12 are available in warehouse)
9. begin the refit
10. **Bug:** Note in Warehouse that only 1 heat sink is reserved for the refit instead of 12 (and the remainder have not been ordered)
11. Advance the day until refit is complete
12. **Bug:** Note that Warehouse shows 11 double heat sinks available instead of none.

[My Campaign30250101-heatsinks.zip](https://github.com/MegaMek/mekhq/files/1660687/My.Campaign30250101-heatsinks.zip)

**Comment by RexPearce** [comment]
I looked into this, and the problem is basically that integrated heat sinks can be added or changed without requiring any parts. (Removing integrated heat sinks works fine though, they will be added to the warehouse.)

Eclipse keeps freezing on me when I set any breakpoints in the refit code, so I've been struggling with this one, but here's what I've found:

This is the main block that tracks changes to integrated heatsinks:

https://github.com/MegaMek/mekhq/blob/ae86420592ca244d37340bf8859dfd4b33b1f89c/MekHQ/src/mekhq/campaign/parts/Refit.java#L770-L823

^ I think the first problem is the warehouse is not checked for spare parts here, instead any required integrated heat sinks are just added to the shopping list.

----

The shopping list is later processed here:

https://github.com/MegaMek/mekhq/blob/ae86420592ca244d37340bf8859dfd4b33b1f89c/MekHQ/src/mekhq/campaign/parts/Refit.java#L1056-L1078

Looks like an attempt is made to find a replacement for each part that is an instance of IAcquisitionWork, however, the HeatSink objects added at L823 are not instances of IAcquisitionWork. So instead the HeatSinks objects are not copied over to the newShoppingList and are lost.

@neoancient @sixlettervariables  I'm not sure how to fix this one - maybe use MissingHeatSink for the integrated heats sinks instead? Any chance either of you could look at a fix for this?

**Comment by sixlettervariables** [comment]
I've been working on new refit logic that handles this situation gracefully, but I'm not close enough to putting it up as a pull request.

**Comment by RexPearce** [comment]
@Windchild292 this was fixed by the merge of #2018. Not sure if you missed it, or if you wanted me to close it.

**Comment by Windchild292** [comment]
Damn, missed that it was not autolinked. If you use the wording fixes #630 in future the issue will close automatically.

Fixed by #2018
