### ISSUE TITLE
[0.43.7-RC1] Technicians not available in Repair Bay on date of hire

### ISSUE THREAD

**Issue by RexPearce** [MegaMek/mekhq#632]
To reproduce:

1. Start a new campaign
2. Add any mech to the hanger and set its repair status to "Salvage"
3. Hire a Mech Tech
4. **Bug**: Note in Repair Bay that the Mech Tech is not listed
5. Advance day and the Mech Tech becomes available to perform work

**Comment by BLOODWOLF333** [comment]
Does one of the rulebooks say this is wrong?

**Comment by pheonixstorm** [comment]
The day you hire a tech he has ZERO time to do anything. Unless there is some rule that says the tech has to have time that day I don't see this as a bug.

**Comment by RexPearce** [comment]
Yeah, I was debating on whether or not to submit this. However, it seemed inconsistent that combat personnel were available for battle on the date of hire, but techs weren't available to repair on date of hire.

Not a big deal in either case. (Though it might help to clarify that in the UI somehow, not sure how to offhand though.)

**Comment by BLOODWOLF333** [comment]
CO pg51:

`The second step is determining how long the procured equipment takes to arrive. Once ordered, equipment and personnel take [7 – (1D6 + Availability)] ÷ 4 months to arrive, as determined by the Availability values in Stage 3 of Force Creation. No matter the dice roll result, it takes at least a month to acquire the equipment and personnel`

![github](https://user-images.githubusercontent.com/16950832/35367656-261ac0a6-0145-11e8-829d-64abb6d9a7b0.png)

**Comment by RexPearce** [comment]
I was going to suggest rolling for transit time on personnel acquisition - the same as is done for parts and units. I think that makes more sense than instantly teleporting them to the player's location. But I'm holding off on feature suggestions (I got a few queue up) until you guys get the stable out.

In any case, if the reason techs aren't available is due to transit time, maybe just mark them as such ( like is done for ordered units) and do that for all personnel, not just techs.

If that's too big of a change at this point, I think it'd be fine to leave it as-is - the only reason I even noticed it was in trying to reproduce the other bugs I reported.

**Comment by BLOODWOLF333** [comment]
I'm looking and dont see any other rules about time required for personnel to arrive at your unit.  It would make sense to me to treat this just like how parts and equipment are done but, at the same time for this to be an optional rules since I can see some players not wanting this to be forced on them since it's been like this in HQ for years and the community never seemed to mind.

**Comment by RexPearce** [comment]
Yeah, for sure - something like "Instant delivery from personnel market" and could go right beside "Instant delivery from unit market". (Though I would argue both should be off by default - but not a big deal either way.)

**Comment by BLOODWOLF333** [comment]
FM - Mercs(Rev) pg.176
`Hiring any or all of these recruits costs a mercenary command two months’ worth of standard pay for the new recruits’ quantity and type. New recruits arrive one month after they are purchased`
So we have a couple different options at least.
