### ISSUE TITLE
NullPointException in the Interstellar Map

### ISSUE THREAD

**Issue by Sir-Payback** [MegaMek/mekhq#634]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.

### Environment
What version of MekHQ does your issue apply to?  0.43.7-RC1
What operating system are you using?  Windows, Mac, or Linux?  Windows
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.  Version 8 Update 161

Map gets stuck on a new campaign.  Just panning it around makes it freeze.  MekHQ file attached.  Says something about NullPointException
[mekhqlog012518.txt](https://github.com/MegaMek/mekhq/files/1666025/mekhqlog012518.txt)

**Comment by HammerGS** [comment]
NPE from Log:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.gui.InterstellarMapPanel.isPlanetEmpty(InterstellarMapPanel.java:901)
	at mekhq.gui.InterstellarMapPanel.access$3200(InterstellarMapPanel.java:90)
	at mekhq.gui.InterstellarMapPanel$6.paintComponent(InterstellarMapPanel.java:703)
```

**Comment by NickAragua** [comment]
This can be fixed by grabbing the latest planets.xml from github.

**Comment by Sir-Payback** [comment]
Confirmed, does work.  Thank you!!

**Comment by bczretribution** [comment]
came here to report this same error, only to find it already done.  Thanks!

**Comment by jayof9s** [comment]
Error addressed and in for next release.
