### ISSUE TITLE
0.43.8 - RC2  When resolving a scenario, aero unit Avionics damage is set to 3 hits/destroyed

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/mekhq#636]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.

### Environment
What version of MekHQ does your issue apply to? Current development version
What operating system are you using?  **Windows**.
What java version are you using?  8.151
### Description
When resolving a scenario with aerospace units deployed, if the aero has suffered any Avionics damage, it is being treated as if the Avionics are destroyed and need replacing. 
This issue has been present for a while. I have reproduced it under 0.43.6, 0.43.7 and the current version in Eclipse recently. 
If you 'edit damage' within MekHQ and set avionics damage, the system has the correct number of hits and can be repaired. I have been able to reproduce the issue when resolving a scenario via MUL file or direct from MM. 
At present, I'm working on this one. 

### Files
Provide the .cpnx campaign file that this issue occurs in.
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the mekhqlog.txt file for any NPE's or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual mekhqlog.txt file

**Comment by mkerensky** [comment]
On further investigation, the damage is only set to 3 hits if the part fails an "other weapons and equipment surivives" roll (Default 10+ per SO).  This seems wrong and is being submitted to CGL for errata review.

**Comment by sixlettervariables** [comment]
@mkerensky is this still valid?

**Comment by mkerensky** [comment]
This is resolved
