### ISSUE TITLE
Dropship Damage or Broken Campaigns

### ISSUE THREAD

**Issue by jayof9s** [MegaMek/mekhq#638]
Using 0.43.7-RC1

Windows 7 - Java 8 update 161 (build 1.8.0_161-b12)

Adding a dropship to a campaign file can either result in broken parts the next time you save/reload (primarily bays and bay doors) OR cause the campaign to not load at all.

2 example campaigns added. The first loads with a broken bay that wasn't there on save. The second example has a 2nd dropship added and now the campaign file won't load at all.

[campaigns.zip](https://github.com/MegaMek/mekhq/files/1690600/campaigns.zip)

Note: this may be related to https://github.com/MegaMek/mekhq/issues/637

Update: Appears to be tied to the Variable Tech Level option if it is Off.

**Comment by NickAragua** [comment]
Looks like there's at least one dropship .blk files that has multiple bay declarations with the same bay number. This causes a variety of "unpredictable behavior" when loading/saving the affected dropships, such as the Outpost (3063). I'll make the fixes to the ones I'm aware of.

**Comment by jayof9s** [comment]
Are we going to have to keep an eye out for more blk files with the bay numbering issue?

This does explain why I wasn't seeing it on EVERY dropship but I did see it on more than just the Outpost.

**Comment by NickAragua** [comment]
Yeah. I've got an idea on how to fix it on the code end (basically, just ignore duplicate bay numbers in .blk files and assign a new one), but it's a pretty non-trivial refactoring of the .blk loading code.

To further confuse the issue, there's a comment in there that implies that two declared bays *can* share the same bay number, but I'm not really sure what that means in gameplay terms. Maybe someone more familiar with that code than I can shed some light on it.

**Comment by jayof9s** [comment]
Thanks, just wanted to make sure I was reading right.

I'm going to have to look closer or hopefully someone else can chime in. All we used to have was 'Type of Bay : Number of Bays : Number of doors' I see with the updates to vessels we have some more info but I'm not entirely clear why we need to assign a number to the bays inside the BLKs. I could see an ID for the part reference but that would seem better handled by the code reading how many there are and numbering them in order they loaded.

**Comment by NickAragua** [comment]
Made a change to .blk parsing code, so there should be no more issues with screwy transport bays. It's on the Megamek side, so you'll need to grab a Megamek jar.
