### ISSUE TITLE
Coolant failures not reset between missions

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/mekhq#64]
When using the MM Tac Ops coolant failure rule, the failed HS is not reset between scenarios. A save/reload will correct the issue.

I have only seen this happen so it may have just been a fluke but will attempt to reproduce.

**Comment by arlith** [comment]
Probably this comes down to `Campaign.clearGameData`.  MHQ creates `Entity` instances that it then reuses for different MM games.  `Entity` wasn't exactly designed to do this, and hence has no way to reset it's "game only" state.  MHQ attempts to do this in `Campaign.clearGameData` and inevitably there's yet another piece of state that isn't getting reset yet.

I would imagine this would be a fairly simple PR: just find what state in `Entity` that the failed coolant rolls use, and then add a line in `Campaign.clearGameData` to reset it.

**Comment by pheonixstorm** [comment]
Will look into it and try to create a PR

**Comment by pheonixstorm** [comment]
Looking over this it requires a change to MM by either making heatSinkCoolantFailureFactor public or creating a reset function. I have gone with the function so this issue will have two PRs up today.

**Comment by pheonixstorm** [comment]
This issue issue is now fixed in PR 216 and 85.

**Comment by djmbm** [comment]
Please don't close when the PRs aren't accepted yet... closed means the bug is fixed.

**Comment by pheonixstorm** [comment]
Ok, will reopen for now.

**Comment by pheonixstorm** [comment]
The fix for this has been merged
