### ISSUE TITLE
Exception Causing UI Issues while Unit is Being Refit

### ISSUE THREAD

**Issue by Flibjib** [MegaMek/mekhq#647]
### Environment
0.43.7 RC1
Mac 10.12.6
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)

### Description
Noticed a UI bug, I have a unit being refit and when time advances, the date does not change and the news feed starts stacking on itself. 

Can be fixed by forcing all mechs being refit to finish.

### Files
<img width="1398" alt="screen shot 2018-02-13 at 9 56 38 am" src="https://user-images.githubusercontent.com/32344358/36156212-6115ac66-10a4-11e8-9a4c-2ce33bc7ab99.png">

[Wolven Winter30410905.cpnx.zip](https://github.com/MegaMek/mekhq/files/1720319/Wolven.Winter30410905.cpnx.zip)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1720320/mekhqlog.txt)

**Comment by neoancient** [comment]
Please include custom units: Rifleman RFL-2W and Tornado PA(L) P13 'Blizzard'.

**Comment by Flibjib** [comment]
[Tornado PA(L) P13 'Blizzard'.blk.zip](https://github.com/MegaMek/mekhq/files/1720776/Tornado.PA.L.P13.Blizzard.blk.zip)
[Rifleman RFL-2W.mtf.zip](https://github.com/MegaMek/mekhq/files/1720778/Rifleman.RFL-2W.mtf.zip)
