### ISSUE TITLE
Magic ammo bins

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#648]
### Environment
mekhq 43.7 Java version 1.8.0_121

### Description
In the attached file the archer and highlander have developed magic lrm 20 ammo bins.  In the repair screen, they have a bin that is listed to be refilled that doesn't show on their stat card.  If you refill them ammo is consumed but the repair action never goes away (this is problematic for automated repair actions as it will keep being refilled until you run out of ammo).  If you go to the change ammo type menu in the hangar they are shown to have 1 more locations where ammo can be changed then they should have.  
[glitch.zip](https://github.com/MegaMek/mekhq/files/1720942/glitch.zip)

**Comment by scJazz2** [comment]
This is associated with refits. I believe the bug is fixed in RC1

**Comment by Flibjib** [comment]
I have seen this behavior sporadically in RC1, will try to replicate.

**Comment by scJazz2** [comment]
This was a bug in the refit code prior to RC1. Any affected units should be deleted and re-added. This ticket should be closed, probably.

**Comment by bczretribution** [comment]
Weird this issue occurred after I had moved to using rc1 (though the units were bought using 43.6)
