### ISSUE TITLE
RFE: Terran Hegemony RAT Generators

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#649]
also several other factions from the pre-succession wars era.

not sure if this should go here or in megamek.

**Comment by HammerGS** [comment]
They should be in the Megamek tracker.  Their are limited Canon sources for RATs.  The built in RAT generator does a good job however.

**Comment by bczretribution** [comment]
the built-in rat generator does do a good job, however, it has no settings for the hegemony, star league,  or the rim worlds republic, as well as a few other groups.  I am using atb, and when it generates scenarios for my contracts, I just get "no random assignment table found for faction", I have to use the "inner-sphere general" setting to add units in megamek.  (and yes I know I can change atb to use other RATS, but i like the generator, it give a nice variety)

**Comment by HammerGS** [comment]
Star League would be after it's inception date.  But here is the menu for 2500

![image](https://user-images.githubusercontent.com/13752452/36222440-8a00768a-117e-11e8-908c-55c34880439d.png)

**Comment by bczretribution** [comment]
thought I was blind, but just doublechecked, it isn't there on mine.  it would seem the rats for said factions have end dates earlier than the factions actual demise.
![no terran](https://user-images.githubusercontent.com/34722287/36222574-b186e386-118f-11e8-8273-fb3a659d1e55.jpg)

**Comment by HammerGS** [comment]
Well The Rim Worlds was Absorbed in 2779.  The Terran Hegemony died December 27th, 2766, and the council lords disbanded the Star League October 10th/2780.

So in 2782 those factions are gone, and the 1st SW is starting to simmer.

**Comment by bczretribution** [comment]
It would seem that the hegemony didn't get the memo that it's supposed to be dead.  I'm certain your dates are right, as I would expect you to be well informed on the matter.  Whatever the reality of the lore, however, it isn't properly represented in the software.  I guess I should change the title of this to "bug report: star league era into first succession wars map is off"  It's wrecked holy hell for me since campaign start jan 1, 2778, as now knowing the dates you just provided, the rats ended at the appropriate time, but the factions didn't.  I know the map is still under development so this might already be in progress. It might also be worth considering extending the generator's dates a little after the faction is gone as it would cover such incidents, while not actually getting used unduly by accident.
![jan 2783 contract](https://user-images.githubusercontent.com/34722287/36223617-f5f73824-1192-11e8-977a-75077827bc0a.jpg)
![jan 2783](https://user-images.githubusercontent.com/34722287/36223618-f604935c-1192-11e8-9c55-72d490c5000c.jpg)

**Comment by HammerGS** [comment]
The issue is the map is no where complete with dates and only dealing with broad eras.  The early you go the worse the map accuracy gets.  It's a long standing project, that requires a staggering amount of man hours to manually data mine the books and maps.

**Comment by bczretribution** [comment]
Understood, sorry for the trouble, and thanks for taking the time to clarify for me.  I knew the map was a WiP, had thought I had stumbled upon something else.

**Comment by Windchild292** [comment]
The RAT Generator now has a fallback for MekHQ, and thus this is fixed
