### ISSUE TITLE
New MekHQ method of resolving battles Manually

### ISSUE THREAD

**Issue by Mekslayer** [MegaMek/mekhq#658]
I cant seem to resolve my megamek battles man ually anymore. I used to load up separate files for the recovered units of my own, then the salvaged units from the enemy, and the state of disrepair was imported into HQ. Now if asks for a Battle record mul file. When I put all the salvaged and recovered unit into one combined mul file, it doesnt load anything and just asks if my mechs were a total loss or not, if I click " not lost" then it only shows my mechs as pristine and with no damage. no salvaged units can be found. What is going on? Why was this changed? I think it was good the way it was. Do the developers just assume that the HQ version always matches the Megamek version? I hope not. I dont move my cpnx file to a newer HQ version without a good reason... because prior to this I could use any megamek version that my opponent wanted and could still resolve the battles manually. Was this really changed to something that is broken?

I am using HQ version 43.2 and have been using a 43.5 version of Megamek on Win 7 with java version 8 update 151 (64bit)
I hope someone understands what I am referring to so I dont need to add screenshots.

I see no way of adding my cpnx file here. It says it doesnt understand the file type.

### Description
Describe the issue and provide screenshots ingame if able.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the campaign file if applicable.

### Files
Provide the .cpnx campaign file that this issue occurs in.
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the mekhqlog.txt file for any NPE's or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual mekhqlog.txt file

**Comment by Dylan-M** [comment]
For one thing, you should be using versions of MHQ and MM that are matched against each other these days. That way you know it was the version of MegaMek that MekHQ was built with, since MHQ uses MM as a library.

For another, the newer versions of MM output a combined MUL file already in the format MHQ is asking for, and thus you're doing something wrong if you're combining files. I don't believe this bug is valid, and you also didn't provide the files requested by the ticket template.

**Comment by Dylan-M** [comment]
If you try this with 0.43.8-RC2, _**properly version matched**_, we can re-open the issue if it still happens.

**Comment by Mekslayer** [comment]
so in which version of mekHQ did this combined mul file begin with?

Sent from Yahoo Mail on Android 
 
  On Thu, Feb 22, 2018 at 4:13 AM, Dylan Myers<notifications@github.com> wrote:   
For one thing, you should be using versions of MHQ and MM that are matched against each other these days. That way you know it was the version of MegaMek that MekHQ was built with, since MHQ uses MM as a library.

For another, the newer versions of MM output a combined MUL file already in the format MHQ is asking for, and thus you're doing something wrong if you're combining files. I don't believe this bug is valid, and you also didn't provide the files requested by the ticket template.
