### ISSUE TITLE
Magic failing campaign files

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#659]
as per discussion on slack.  campaign stopped working after a trip.  

### Environment
43.7 rc1

### Description
game loaded and ran fine made a few minor changes then saved agian and shut pc down to travel.  now campain refuses to load.  attached are log and campain files.

### Files
[glitch.zip](https://github.com/MegaMek/mekhq/files/1748452/glitch.zip)

**Comment by NickAragua** [comment]
Unfortunately, this campaign file is completely unrecoverable, with approximately the last third being completely blank.
