### ISSUE TITLE
Program cannot save game correctly

### ISSUE THREAD

**Issue by Shenaldrac** [MegaMek/mekhq#66]
I recently tried to save my AtB campaign in MechHQ and was greeted with a little popup saying the game couldn't be saved correctly and to report it as a bug here. So I am. Log file is attached. 

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/242620/mekhqlog.txt)

**Comment by pheonixstorm** [comment]
Zip and post the campaign file and any custom units, something odd is going on.

**Comment by Shenaldrac** [comment]
Here you go.

https://dl.dropboxusercontent.com/u/94245000/Shoeless%20Campaign.rar

**Comment by Shenaldrac** [comment]
So fiddling around, I found that by completing the modification to a dropship I was making (custom refit), and then reloading all the weapons and GM completing the tasks needed for it once it was done, the game became save-able once more. Dunno if that's good enough for you to close this, or if you wanna look for what was causing it and iron it out, but I figured I should let you know.

**Comment by pheonixstorm** [comment]
Akjosch has been working on the refit code. There are issues with the refits that sometimes cause the campaign to not load or they just cause other crashes/bugs. 

If you would, add Refit to the beginning of the issue title so this will get looked into during the refit rewrite.

**Comment by Shenaldrac** [comment]
Done and done.

**Comment by Dylan-M** [comment]
I'd prefer not to have people adding words like that to the titles. We have labels we can add as appropriate to what it is.

**Comment by neoancient** [comment]
The stack trace indicates an NPE when saving a refit equipped with a C3i. I could not replicate and the original campaign file is unavailable. Closing as out of date.
