### ISSUE TITLE
MekHQ ATB - Hangar is blank and cannot advance day properly

### ISSUE THREAD

**Issue by windwalker2** [MegaMek/mekhq#662]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.

### Environment
MekHQ v0.3.27 (Dylan's BT Emporium ATB version)/ Megamek 0.41.17
Windows 7 OS
Java Version 1.8.0_144

### Description
Two major issues -

First is that when proceeding a day the daily log doesn't update but the day still moves ahead. I can skip forward until our next ATB battle but the day at the top or in the log does not change.
Second issue is that when attempting to access the hangar it does not load correctly. If I drag and drop highlight I can see the units but other than that it will stay blank. 

Campaign file, custom units and MekHQLog are attached in a ZIP.

[CPNX and Customs.zip](https://github.com/MegaMek/mekhq/files/1778188/CPNX.and.Customs.zip)

**Comment by HammerGS** [comment]
That version is so out of date (April 2016) and was known to have numerous bugs and issues.  Try with the current Release Candidate - 

http://bg.battletech.com/forums/index.php?topic=60418.0

or here

https://github.com/MegaMek/mekhq/releases/tag/v0.43.8

**Comment by Dylan-M** [comment]
I'm pretty sure the bugs as described are fixed. Have you followed the suggestion to try a new version?
