### ISSUE TITLE
0.43.8-RC2 - Support Particle Cannons vastly overweight

### ISSUE THREAD

**Issue by Flibjib** [MegaMek/mekhq#669]
### Environment
0.43.8-RC2
MacOS 10.12.6
Jave vers. 1.8.0_65

### Description
As I was looking through my cargo capacity, and warehouse contents, I noticed that support particle cannons are looking **heavy**
<img width="1050" alt="screen shot 2018-03-13 at 10 41 47 am" src="https://user-images.githubusercontent.com/32344358/37349140-1eb0c75c-26ac-11e8-910a-6c4e3226233f.png">

### Files
[megameklog.txt](https://github.com/MegaMek/mekhq/files/1807375/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1807376/mekhqlog.txt)
[Wolven Winter30461026.cpnx.zip](https://github.com/MegaMek/mekhq/files/1807377/Wolven.Winter30461026.cpnx.zip)
[customs.zip](https://github.com/MegaMek/mekhq/files/1807381/customs.zip)

**Comment by Dylan-M** [comment]
Since all equipment is actually controlled by MegaMek, can you please report this on that tracker instead? Thanks.

**Comment by HammerGS** [comment]
Nope these are the correct weight.  From TM - 

* The Support Particle Cannon is considered to be a vehicle in itself, with an effective MP of 2 (Tracked); it may thus only be employed by Motorized/Mechanized (Tracked) infantry platoons.

**Comment by NickAragua** [comment]
Still, it should only weigh 1800kg per gun, not 1800t.

**Comment by HammerGS** [comment]
Right, I've got a fix but haven't committed it.
