### ISSUE TITLE
Scenario does not resolve - NPE in scenario resolution isCommander() 

### ISSUE THREAD

**Issue by SirChaos1** [MegaMek/mekhq#67]
As I posted in the release thread at the BT forum, all of a sudden scenarios won´t resolve, two times out of the three most recent ones I played. I can´t think of anything that was different in the two scenarios that wouldn´t resolve compared to the one in between that did, or to the dozens before in the same campaign that worked flawlessly.

The log contains error messages from, firstly, an attempt at automatic resolution, and secondly from an attempt at manual resolution.

[mekhqlog resolve bug.txt](https://github.com/MegaMek/mekhq/files/247418/mekhqlog.resolve.bug.txt)
[Hellfire Division30671221a.zip](https://github.com/MegaMek/mekhq/files/247419/Hellfire.Division30671221a.zip)
[ResolveBug.sav.gz](https://github.com/MegaMek/mekhq/files/247421/ResolveBug.sav.gz)
[customs.zip](https://github.com/MegaMek/mekhq/files/247422/customs.zip)

**Comment by SirMegaV** [comment]
Unit.isCommander bug.. already posted in SF for a while.. try manual
resolution.. if it 'hang', just click the 'x' window button for the
resolution screen on the upper right. For some reason, the manual
resolution will continue after that.

**Comment by SirChaos1** [comment]
I just tried that - I get the manual resolution dialog, but all my units are marked lost, and there´s no salvage.

What did, however, work, is going by the suggestion in the SF bug report entry, and deleting all commander hit criticals in the MUL before doing manual resolution.

I´m guessing then that this bug happens whenever a player-controlled vehicle gets a "commander injured" critical.

**Comment by pheonixstorm** [comment]
The SF report can be found here https://sourceforge.net/p/mekhq/bugs/961/

I tracked down the error and is has to do with the prisoner tank crew when the commander is listed as hit.

@SirChaos1 can you change the name of this report to NPE in scenario resolution isCommander() it would be more helpful and best reflect the nature of the bug report.

**Comment by HammerGS** [comment]
Title editted.

**Comment by pheonixstorm** [comment]
Thanks Hammer
