### ISSUE TITLE
Customize Bug

### ISSUE THREAD

**Issue by EMaher81** [MegaMek/mekhq#672]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.

### Environment
What version of MekHQ does your issue apply to? 0.43.2
What operating system are you using?  Windows, Mac, or Linux? Windows
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.

### Description
Describe the issue and provide screenshots ingame if able.
-When upgrading a Wraith TR1 to an XL Gyro (using freed up tonnage to max armor) the Gyro completely disappears from Crit slots.  Despite this the design validates, and plays in MegaMek.  Thinking it might be because there was a Jump Jet in CT I removed the Jump Jet before changing the Gyro to XL Gyro, but the bug repeated.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the campaign file if applicable.
-Reproduced this in both HQ and Lab

### Files
Provide the .cpnx campaign file that this issue occurs in.
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the mekhqlog.txt file for any NPE's or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual mekhqlog.txt file

**Comment by HammerGS** [comment]
You are using a very old version of the programs - Try with the latest release 
https://github.com/MegaMek/mekhq/releases

**Comment by Dylan-M** [comment]
Please update your test with a recent version of MHQ. If it still happens we'll re-open this. For now, closing to no response for 28 days.
