### ISSUE TITLE
AtB fails to generate opfor

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#674]
### Environment
mekhq 43.7 rc 2

### Description
AtB occasionally generates new battles and fails to generate an opfor.  shown image is the second time this contract.  note how there are no folders listing terran hegemony or LC units for this base defense
![glitch](https://user-images.githubusercontent.com/34722287/37734516-d0c42832-2d21-11e8-8285-3294d56b17e6.jpg)

### Files
[glitch.zip](https://github.com/MegaMek/mekhq/files/1835067/glitch.zip)

**Comment by NickAragua** [comment]
Next time you see this, could you post the mekhqlog file as well?

**Comment by bczretribution** [comment]
Just had it happen earlier today,  ill grab it on the next one.

**Comment by bczretribution** [comment]
[glitch.zip](https://github.com/MegaMek/mekhq/files/1862028/glitch.zip)
here you go, one campaign save with mekhq log file.  this one also contains a bonus potentially related bug where its assigning units to missions that were not deployed, as well as the no opfor bug.

**Comment by NickAragua** [comment]
Missing Clint CLNT-2-3b, Overlord (2775) Combined Arms customs.

**Comment by bczretribution** [comment]
Sorry about that, I haven't figured out yet how to tell which customs are required and which ones aren't.  this raises another interesting question, however, as there is no custom for the overlord.  I've scoured my folders and could not find one, I then loaded up the campaign file and double checked the stats of the overlord there with one opened from the cache in MML and confirmed that they were identical.  I've added the clint into the zip, but I am not sure what to do about the overlord.  If you want me to zip the entire mechfiles folder and upload a google drive link, let me know.

[glitch.zip](https://github.com/MegaMek/mekhq/files/1866112/glitch.zip)

**Comment by NickAragua** [comment]
Generally speaking, anything in mechfiles/customs should be supplied.

**Comment by NickAragua** [comment]
I think I see the problem. The Terran Hegemony doesn't have a RAT entry for the year you're playing in. Until the issue is addressed, you can always manually generate the allied forces (probably using a more generic RAT).

**Comment by bczretribution** [comment]
The lack of rat I'm familiar with and have been dealing with for quite a while using the method you just described.  Notice that in the posted pictures and (assuming) in the campaign file when you load it, that there is no opfor as well.  normally when it cant load TH rats it makes a folder for the allied units and fills it with a bunch of "cannot find rat for this faction" lines, and then there are still folders populated normally for all the other forces as well (turrets, civilians, enemy 1, enemy 2, enemy reinforcements, in the case of a base defence).  None of that is showing up here, there is no empty TH folder, no civilian folder, no enemy folder, etc.  if you look at some of the other completed missions you will see the described folders including the TH folder, much of the time the missions generate fine, but occasionally (and there seems to be a higher likelihood with base defence missions) nothing generates instead.

This campaign has over 3 dozen customs currently.  Only 3 need to be sent, which is why I try not to send them all, it would get messy.  and the overload isn't customized, so even if I sent them all there still wouldn't be a file for that.
