### ISSUE TITLE
Units not deploying in MegaMek

### ISSUE THREAD

**Issue by GomosDS5** [MegaMek/mekhq#679]
### Environment

What version of MekHQ does your issue apply to?
 **0.43.2**
What operating system are you using?  Windows, Mac, or Linux?
 **Win7**
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.
**V8 U151**

### Description

Describe the issue and provide screenshots ingame if able. 
**Units sent from MekHQ populate into the MegaMek lobby properly, but once deployed and on the game screen, some mechs won't actually deploy. It's only ever one unit per lance, and it seems to be at random.** 

And provide the steps you have taken to reproduce the issue in the campaign file if applicable. **Campaign file attached has a battle pending, and once started the unit commander's mech (HTM-27U) populates in the lobby, but once the game launches, it is not available to deploy onto the field. I have tried rolling back to previous saves and the issue repeats itself. It has happened previously with other mechs on other missions, but sparingly. It is now happening every match.**

### Files
Provide the .cpnx campaign file that this issue occurs in.

[DS5 3053 C 1.zip](https://github.com/MegaMek/mekhq/files/1844391/DS5.3053.C.1.zip)

Provide any custom units that you are using in this campaign so that it will load on the developers machine.
**Sorry, not sure how to provide the files. Hope this works...**

[DS5 C30580526_ExportedUnit.zip](https://github.com/MegaMek/mekhq/files/1844396/DS5.C30580526_ExportedUnit.zip)

I apologize if i've missed posts about this subject, but i searched here and on sourceforge, and found nothing like this. My SearchFu is weak.

Thanks for any help,

G

Edit: Could this be a mistake i've made with game settings, or some mechanic or feature i'm misunderstanding?

**Comment by Dylan-M** [comment]
0.43.2 is pretty old, and this has most likely been fixed in the current version. Every now and then we find a new thing that causes this, but if we don't have them all in 0.43.8, we should be very very close. Closing with invalid tag, but if you try it on the latest version and can replicate it, we can reopen the issue.

**Comment by BLOODWOLF333** [comment]
If this is the same situation as #242 and the unit that is not deploying had to eject last scenario then restarting HQ is the work around for this run-time bug.

**Comment by GomosDS5** [comment]
Bloodwolf, thanks for pointing that out, i'll give it a try.

Dylan, i downloaded the latest stable version, so you're saying i should just use the dev branch? I'll give it a try.

Thanks to both of you for the quick reply.

**Comment by Dylan-M** [comment]
@GomosDS5 the latest version is actually a release candidate for a new stable. It has a very large number is new bugfixes and features over the previous stable.

**Comment by GomosDS5** [comment]
Great, porting over now. Thanks.
