### ISSUE TITLE
Contract payment based on Large Craft unit value does not appear to work

### ISSUE THREAD

**Issue by BlueThing00** [MegaMek/mekhq#680]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.

### Environment
MekHQ: 0.43.9
OS: Windows 10
Java: 1.8.0_161-b12

### Description
Contract payment does not appear to be increased by enabling payment for Dropships and Jumpships.

I attached a sample campaign file exhibiting the issue.  Pay for Combat Units is set to the minimum 0.1%.  Dropship and Jumpship pay is set to the maximum 1%.

Note that the pay for most contracts is around 12k.  It looks like straight support will cover a chunk of the cost of the large craft, as the one contract with 80% straight support covers 2 million of the nearly 4 million cost of maintaining the large craft.

[bug_report.zip](https://github.com/MegaMek/mekhq/files/1844443/bug_report.zip)

EDIT: The campaign in the zip file should not require any custom units or other custom items.

**Comment by pheonixstorm** [comment]
The section of code handling payment seems to have been overwritten by another PR

Even so, why use percentage based maintenance? It might be ok for mechs and vees but adding in largecraft and you not be able to afford it.

**Comment by Dylan-M** [comment]
@pheonixstorm It would be useful to know what PR and what code it overwrote...

**Comment by pheonixstorm** [comment]
`Campaign.java` `getForceValue(boolean noInfantry)` currently line 7846

Believe it to be PR #439 CO peacetime cost was #441

**Comment by BlueThing00** [comment]
@pheonixstorm:
The percentage based maintenance is the AtB default, so I started with it on.  I was also hoping that it would be a good substitute for maintenance rolls to provide ongoing costs for my unit.  I find dealing with the results of maintenance rolls exceedingly tedious, but wouldn't mind also seeing a reasonable ongoing cost for maintenance.

Even with percentage maintenance off (and Large Craft contract payment percentages not working), the fact that Straight Support triggers off of the value of the Large Craft also greatly impacts contract values.  That may be an even bigger problem, as it can swing the value of a contract by more than 2 million a month for a single drop ship and jump ship in the unit.

**Comment by pheonixstorm** [comment]
The AtB rules spreadsheet does NOT use percentage based maintenance and I really wouldn't recommend using it with large craft. Percentage maintenance is an unofficial option so I don't see why it would be on by default.

I'm about to push a fix for this issue in a bit though so hopefully you won't have this issue next release.

**Comment by Dylan-M** [comment]
I use percentage maintenance for everything. You basically *have* to when you're using CO payment and getting paid for them, or you accrue far too much money too quickly.

**Comment by BlueThing00** [comment]
Regardless of what the spreadsheet says, the AtB preset option config in MekHQ has percentage based maintenance enabled by default.

@pheonixstorm 
Thank you for the quick fix.
