### ISSUE TITLE
AtB generates large OpFor in single Bot some missions

### ISSUE THREAD

**Issue by BlueThing00** [MegaMek/mekhq#684]
### Environment
MekHQ: 0.43.9
OS: Windows 10
Java: 1.8.0_161-b12

### Description
AtB generated a single 20 unit OpFor in a Chase(Defense) mission without having double vehicles enabled.  

Since Base Defense missions now have the OpFor split into multiple bots, I thought it would be nice if all missions could have that done for them if the size of the OpFor gets too large.  It noticeably reduces the time Princess thinks about turns.

This isn't exactly a bug, but I couldn't find anywhere to submit anything but "issues", so I hope this is the correct place for a (hopefully minor) feature request.  :)

### Files
N/A

**Comment by BlueThing00** [comment]
With the changes to OpFor generation in 0.50.01, this can be closed and a new bug created if there are problems in the new code.

**Comment by IllianiCBT** [comment]
Closing as either resolved or no longer relevant
