### ISSUE TITLE
Infantry Field Gunners ammo reload bug

### ISSUE THREAD

**Issue by monbvol** [MegaMek/mekhq#686]
### Environment
0.43.9 RC3
Windows 10 64 bit
Java 1.8
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1864480/mekhqlog.txt)

### Description
No matter how much ammo I have on hand I cannot reload my LB-10X field gunners but it still draws from my available ammunition stock.

Until MekHQ breaks from it's current loop or I recreate the issue best I can submit for now is the log.

**Comment by monbvol** [comment]
Not sure if this is also being caused by the extranious stuff that got copied over when adding quirks for some custom units or not but after taking out the errors my field gunners reloaded properly but I didn't recreate the exact same situation so not 100% sure.

**Comment by NickAragua** [comment]
The exceptions being thrown are exactly the same as for the restore units log. We'll close this for now, unless somebody encounters this issue again.
