### ISSUE TITLE
3.27 : ATB, allies generated use incorrect skill rating

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#69]
The contract is set to generate elite units for both the enemy and allied units, but the fedcom allies generated for the latest mission were not generated using the elite skill rating (it even has a 6/6 pilot)

[#battletech.zip](https://github.com/MegaMek/mekhq/files/255163/battletech.zip)

**Comment by neoancient** [comment]
The 'Mech forces were being generated with the correct skill rating. The contract values were not being applied to gun emplacements or an employer-loaned DropShip, which I changed. Civilian units (allied or enemy) are still generated as regular units.
