### ISSUE TITLE
Unable to GM Acquire clan ammo

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/mekhq#696]
[Logs.zip](https://github.com/MegaMek/mekhq/files/1882400/Logs.zip)
[Ulric's Behemoths30560805.zip](https://github.com/MegaMek/mekhq/files/1882401/Ulric.s.Behemoths30560805.zip)
[Customs.zip](https://github.com/MegaMek/mekhq/files/1882402/Customs.zip)

Version 43.8 
Windows

I have it set not allow buying clan parts. 
However I allow myself to buy clan ammo and armor (at 5 times cost) as in my head cannon (in 3055) you should be able to find some ammo or armor plate or have some machined for you if you pay enough. 
I ran out of LBX5 cluster ammo on the Rifleman C I found and tried to GM Acquire instantly in the missing parts tab of the repair bay. 
However instead of getting the ammo I got You shouldn't be here (AmmoBin.find()). in the log
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.

**Comment by NickAragua** [comment]
This will be fixed with PR #673
