### ISSUE TITLE
Income/Expenses Processed in wrong order

### ISSUE THREAD

**Issue by jayof9s** [MegaMek/mekhq#698]
0.43.8-RC2-windows

When advancing to a new day, expenses are paid prior to any income: this creates a problem if you do not have enough cash on hand without the payment.

Example: on the first of the month you usually receive contract payments and pay salaries and overhead. If you have 750k salary expenses, 500k cash on hand, and 2 million c-bill contract pay you will be told you have a shortfall. The Salary will attempt to pay prior to receiving the contract payments; even though they're received the same day.

Income should always be processed prior to expenses, assuming they're the same day.

**Comment by Dylan-M** [comment]
So, the code _looks_ like this should be impossible. However, I have refactored and cleaned up the newDay() method as a potential fix I'll make a PR with shortly. I split things out into sub-methods to make everything easier to understand and follow. As well as making smaller methods that do a single thing.
