### ISSUE TITLE
[0.43.10-RC4 : Bug] Old Contacts Appearing in Deployment Requirements

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#708]
### Environment

0.43.10-RC4

### Description

Old contracts showing up in the Deployment Requirements under the Briefing Room tab. No problem loading the same campaign file using RC3. No errors in log file.

![old contacts appearing in deployment requirements - rc3](https://user-images.githubusercontent.com/17064665/39081744-3dfca626-4579-11e8-9d31-0323edf1ae9c.png)

![old contacts appearing in deployment requirements - rc4](https://user-images.githubusercontent.com/17064665/39081746-48afa640-4579-11e8-9d07-5873c74d8df9.png)

### Files

[Old Contacts Appearing in Deployment Requirements - Customs - SirMegaV - Mechfiles.zip](https://github.com/MegaMek/mekhq/files/1934248/Old.Contacts.Appearing.in.Deployment.Requirements.-.Customs.-.SirMegaV.-.Mechfiles.zip)
[Old Contacts Appearing in Deployment Requirements - SirMegaV25071226.zip](https://github.com/MegaMek/mekhq/files/1934249/Old.Contacts.Appearing.in.Deployment.Requirements.-.SirMegaV25071226.zip)

**Comment by BairdEC** [comment]
I have this issue too, although my campaign only shows one of the prior contracts in the deployment requirements.  It did not matter if I loaded the campaign file from the MekHQ root folder or the campaigns folder.  It also persisted after completing a mission, saving the game, and restarting MekHQ.    I can add screenshots and the savegames if those will be helpful.

**Comment by NickAragua** [comment]
Looks like this is an issue for long-running campaigns that span multiple updates to planets.xml - some of the planets for older contracts no longer have the same "name" in newer versions of that file.

**Comment by SirMegaV** [comment]
Sorry for the late reply. Yes, nothing supposed to be showing.
