### ISSUE TITLE
Units that finish refitting are often missing ammo and components

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#71]
I have noticed that after completing a refit, the unit frequently will be missing ammo or components.

Here's an example : I refitted SRM carriers to a fuel cell variant. The 2nd SRM carrier ended up with 2 empty ammo bins and a missing fuel cell engine. If you right click it and go to customize in mek lab, It says that the vehicle needs a 180 fuel cell engine.

I then refitted a vulture prime, and it also ended up with 2 empty ammo bins. Customize in mek lab shows that it is missing a head component.

I can re-produce this pretty accurately even with simple refits like re-podding a Vulture prime to any other vulture variant. The ammo frequently stays in the warehouse instead of being used for the refit. Refits that modify engines, internal structure or armor frequently has the components sit in the warehouse instead of being used in the refit as well.

[#battletech.zip](https://github.com/MegaMek/mekhq/files/255870/battletech.zip)

**Comment by HammerGS** [comment]
The whole process around refits is being re-worked. @Akjosch can address specifics.

**Comment by Question2** [comment]
Alright. Another thing that I noticed was that when refitting a Elemental BA point (MG), mekhq calculates the starting weight incorrectly (mekhq says that the point has 3.52/5 tons of weight, thats definately not correct, megameklab shows that each BA has 0.88 tons of weight).

**Comment by Akjosch** [comment]
It's a lot of work to fix all the issues with refits (SF tracker is full of them too), basically necessitating a full rewrite. I'm working on it, so grabbing this one.

**Comment by Question2** [comment]
Similar refit issue : I tried to refit a VND-1R, and swapped the LRM-5 for a SRM-6. During the refit process, mehq used a SRM-6 inferno ammo bin instead of a normal SRM-6 ammo bin (even though i had chosen to use a normal ammo bin).


[test.gz](https://github.com/MegaMek/mekhq/files/675814/test.gz)

**Comment by purpledragon2** [comment]
There are different bins for inferno vs regular SRMs?  I've never seen that rule.

**Comment by Dylan-M** [comment]
@purpledragon2 Only in MHQ, it's how MHQ identifies the type of ammo for that mech when the bin is empty and needs to be reloaded. It's a poor design choice, and one that should be rectified by @Akjosch's complete revamp of the entire repair/refit system.

**Comment by neoancient** [comment]
The ammo bin issues were resolved in 4931ce0. I could not reproduce the issue with the head component. The engine issue was due to the engine part not having the tank engine flag set, which caused it not to match the engine in the refit target.

**Comment by neoancient** [comment]
While looking into SourceForge bug #983 I figured out the problem with the head component. Flags that indicate whether a head in the warehouse has sensors and/or life support were set differently for a newly created mech than one that had its head replaced. As these flags are irrelevant for a head installed on a mech I just had it ignore those flags when determining whether two heads are the same part unless neither is attached to a unit.
