### ISSUE TITLE
0.43.2 Migration to 0.43.9 causes Phantom Personel in Unit Breakdown

### ISSUE THREAD

**Issue by Khantemplation** [MegaMek/mekhq#714]
Summary: Migrating to latest build from MekHQ 0.43.2 causes phantom/non-existent personnel to appear in unit breakdown, lowering dragoons rating

### Environment
Migrating from MekHQ  0.43.2 to 0.43.9 and 0.43.10 (I've tried importing copies of the save into both, with similar results)

What operating system are you using?  Windows 10 Home, Version 1709, OS Build 16299.371
What java version are you using? Version 8 Update 171 (Build 1.8.8_171-b11)

### Description
Attempting to migrate to the latest version of MekHQ at the start of my new contract, Noticed my Dragoons rating drop from B to C on migrating. It seems that the latest version of MekHQ adds phantom (Nonexistant) regular personnel to my unit breakdown, dragging down my skill rating.

I've also been able to induce the same phantom personnel issue migrating saves from much earlier in the same campaign (created when I was running 0.43.2). I have been unable to reproduce the issue by creating new campaigns in 0.43.10 or 0.43.10

I've tried several things to remove these phantom persons from my unit, I've emptied my ToE of all units, removed only extra green/green/regular personnel from my unit, removed all prisoners from my unit, removed all personnel entirely (to include dependents, prisoners, retired personnel, KIA/MIA, and all support and combat personnel), nothing seems to fix it.

I've also tried creating a brand new campaign in MekHQ 0.43.2, getting 4 mechwarriors, 4 mechs, adding them to ToE, and then importing that into 0.43.9, but was unable to reproduce this bug that way.

### Files
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1945040/mekhqlog.txt)
[New Contract Mountaineers30510713.zip](https://github.com/MegaMek/mekhq/files/1945046/New.Contract.Mountaineers30510713.zip)
[customs.zip](https://github.com/MegaMek/mekhq/files/1945053/customs.zip)

**Comment by NickAragua** [comment]
Confirmed, will look into it.
