### ISSUE TITLE
[0.43.9-RC3 : Bug] Unit.isCommander Error

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#715]
### Environment

0.43.9-RC3

### Description

Screen corrupted with Unit.isCommander(Unit.java:3730) error. This has been going on for years, only now reporting.

To replicate, load campaign file attached.
1. At Personnel tab, sort by Unit Assignment.
2. At TO&E tab, go to 12th Combined Armored Infantry Company.
3. Select Sergeant Lizbeth Minet, right click, select Go to Pilot/Commander in Personnel.
4. Select **ALL** personnel in the same unit, right click, assign to "Motorized Platoon (SRM) ## 12th Combined Armored Infantry Company"
5. Click TO&E tab. Nothing will happen. Error "Unit.isCommander(Unit.java:3730)" found in the log. Log attached. 
6. Although the screen fail to refresh, if you scroll up and down, it will reappear.
7. Basically this will almost always happen when you remove all personnel from a unit that is currently in the TO&E.

### Files

[Customs - SirMegaV - Mechfiles.zip](https://github.com/MegaMek/mekhq/files/1945335/Customs.-.SirMegaV.-.Mechfiles.zip)
[Unit.isCommanderError.cpnx.zip](https://github.com/MegaMek/mekhq/files/1945336/Unit.isCommanderError.cpnx.zip)
[Unit.isCommanderError.txt](https://github.com/MegaMek/mekhq/files/1945337/Unit.isCommanderError.txt)

**Comment by NickAragua** [comment]
Fixed by PR #718
