### ISSUE TITLE
Current MHQ Master Edition has no MekHQ executable

### ISSUE THREAD

**Issue by Faolind** [MegaMek/mekhq#716]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first beforCurrent Master edition doesn't have e reporting so as not to make duplicates.

### Environment
What version of MekHQ does your issue apply to? Current Dev Snapshot 
What operating system are you using?  Windows, Mac, or Linux? Windows 10
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file. 

### Description
Describe the issue and provide screenshots ingame if able. 
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the campaign file if applicable.

### Files
Provide the .cpnx campaign file that this issue occurs in.
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the mekhqlog.txt file for any NPE's or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual mekhqlog.txt file

**Comment by mkerensky** [comment]
Did you perhaps download the source code by mistake?  I just played a game with the windows dev snapshot 0.43.10 RC4.  It came with all 3 executables...

**Comment by mkerensky** [comment]
https://github.com/MegaMek/mekhq/releases/download/v0.43.10/mekhq-0.43.10-RC4-windows.zip

Try that one.

**Comment by Faolind** [comment]
Sure. Is that the latest stable build? its only .10 past my file from a year ago though. Well regardless thankyou so much ^_^ Battletech wont work on my machine so now I'm plating this but with Battletech's soundtrack XD

**Comment by mkerensky** [comment]
Glad to help.    It is not technically  'stable' - that'll be 0.44,  but the RC4 means it's a release candidate for stable 0.44.  This one is *mostly* bug free.

**Comment by jayof9s** [comment]
I'm closing this as the issue seems to have been resolved.
