### ISSUE TITLE
[0.43.9-RC3 : Feature Request] Show Faction Availability in Purchase Unit

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#717]
Include faction availability information from data/forcegenerator in "Purchase Unit" window. This will aid players in selecting the correct units based on their faction.

**Comment by mkerensky** [comment]
I think the trick here is that the Purchase Unit dialogue is looking at the data contained in the MTF/BLK files, which don't include faction.  The RATs/forcegenerator are totally separate tables (forcegenerator being made from exhaustive review of the RATs and the sourcebooks to determine what faction most commonly uses which units).   Forcegenerator also includes salvage from other realms with which the chosen faction has frequent conflict, and blends two tables when the current year falls between tables.


All that said, you can currently use the Manage Campaign > Show GM Tools Dialogue and roll yourself up a faction-appropriate unit.   I would like to see the full ForceGenerator tool be made available for use here.   If we had this,  I would use forcegenerator to create a RAT for my force and then pick my units from Purchase Unit from that.

**Comment by neoancient** [comment]
The data used by the  force generator also includes a fair amount of guess work and speculation, as well as my own inadvertent biases. There simply is no definitive data to make this work. The closest would be http://masterunitlist.info, but that just lists faction availability by broad era. Factions listed for any given unit would have had it available at some point in that era but not necessarily in every year during that era. The MUL is also not complete for all eras.
