### ISSUE TITLE
Dropship in TO&E triggers scenario even though it is not assigned to a lance

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#72]
The overlord dropship in the TO&E somehow managed to trigger a scenario even though it was not assigned to a lance. Dropships in ATB are supposed to be included with at least one lance when a scenario is triggered, but this dropship managed to trigger a scenario by itself even though it was not in a lance.

[#battletech.zip](https://github.com/MegaMek/mekhq/files/260233/battletech.zip)

**Comment by Windchild292** [comment]
I'm not 100% certain, but I'm pretty sure I have seen this occur in one of my games in 0.46.0. If so, that means this is still a bug, albeit a rare one

**Comment by sixlettervariables** [comment]
You can now mark forces in the TOE as non-combat, which can be used to avoid this.
