### ISSUE TITLE
(43.10) Unable to create a New Contract (GM) prior to game year 3030

### ISSUE THREAD

**Issue by servo01** [MegaMek/mekhq#722]
Starting a new campaign, and I'm finding that 43.10 won't allow me to create a new contract with: 
Briefing Room/Add Mission/New Contract (GM Mode)

I downloaded 43.10 again and did a clean install, and the problem persists. I then started adjusting a variety of different settings (faction, RATs, etc...) in order to get it to work and discovered that advancing my in-game year from 3014 to at least 3030 makes it possible to GM Mode new contracts. 

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1980352/mekhqlog.txt)

 

### Environment
What version of MekHQ does your issue apply to?
What operating system are you using?  Windows, Mac, or Linux?
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.

### Description
Describe the issue and provide screenshots ingame if able.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the campaign file if applicable.

### Files
Provide the .cpnx campaign file that this issue occurs in.
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the mekhqlog.txt file for any NPE's or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual mekhqlog.txt file

**Comment by NickAragua** [comment]
Do you have a campaign save file?

**Comment by servo01** [comment]
[testsave.cpnx.zip](https://github.com/MegaMek/mekhq/files/1980566/testsave.cpnx.zip)

**Comment by NickAragua** [comment]
Ok, looks like there *is* an exception happening there, for which I have a fix in the pipeline. Mostly, the issue is that you're in the ass-end of nowhere, so the only potential options are contracts vs pirates and rebels - I'll also be better communicating that MekHQ was unable to generate a contract (rather than just failing silently).

**Comment by servo01** [comment]
Thanks for the response! 

No issues GM-ing to the core worlds, generating the contract, and then GM-ing back to the ass-end of nowhere.
