### ISSUE TITLE
Cannot choose "Rasalhague Dominion" as the faction

### ISSUE THREAD

**Issue by crazys1** [MegaMek/mekhq#727]
### Environment
What version of MekHQ does your issue apply to?

0.43.10-RC4

What operating system are you using? Windows, Mac, or Linux?

Windows 10

What java version are you using?

Version 8 Update 161, build 1.8.0_161b12

### Description
You cannot choose "Rasalhague Dominion" as the faction, even when the campaign year is set to 3103 or later. 3103 is when the Rasalhague Dominion was introducted, according to the factions.xml file.

To reproduce:

1. Start a new campaign.
2. Set the year to 3103 or later. You can leave all other settings at the default to save time.
3. Try to choose "Rasalhague Dominion" as the faction.

This issue is also true for loading an existing campaign and trying to change the faction to "Rasalhague Dominion."

**Comment by jayof9s** [comment]
As a work around you should be able to pick the Ghost Bears as your faction
and they should display as the Rasalhague Dominion once you're settled in
for that time period.

**Comment by crazys1** [comment]
I can't choose that faction, either. As a test, I just created a new campaign in the year 3110. For Clan factions, I see:

![image](https://user-images.githubusercontent.com/21768936/40194288-b647a708-59be-11e8-9930-69e6f7e04cc0.png)

**Comment by jayof9s** [comment]
Interesting. I guess that is tied to the changes to factions that have been
made recently. GB probably has an 'end date' in the 3080s (instead of how
the name previously just changed to RD) and no one thought to make the RD a
playable faction.

Shouldn't be difficult to fix at least, I'll take a look this evening. It
should just be a pretty simple change in the factions.xml file if you want
to give it a swing just to get it working sooner for your game.

**Comment by mkerensky** [comment]
I found some weirdness with the ghost bear factions too - ran into it while working with the Force Generator.  Since they change from Clan Ghost Bear to Ghost Bear Dominion to Rasalhague Dominion that's one of the more complicated factions to code...

**Comment by jayof9s** [comment]
[RD Should be a a playable option now](https://github.com/MegaMek/mekhq/commit/1ca0dbd81060809dc3a0b94be0525bff71cf7796)

**Comment by crazys1** [comment]
Excellent; thank you for the prompt action and the interim workaround!
