### ISSUE TITLE
[43.10] Can't access some characters right click menu, possible NPE

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#728]
### Environment
The issue is present in both 43.7 and 43.10.

### Description
In the attacked campaign file right click menu does not open for some characters in the personnel list but does for others.  The log file shows an NPE, unsure if it is related.  Issues seems to be somehow related to rank.  To replicate open campaign, select personnel tab.  sort for mech warriors only.  try right clicking on any character rank captain or above, the right-click menu should not appear.  if you repeat the process with any of the enlisted the right-click menu appears fine.  For lieutenant characters, it is half and half, but it is consistent as to which half work and which don't.

### Files
[glitch.zip](https://github.com/MegaMek/mekhq/files/2015469/glitch.zip)

**Comment by NickAragua** [comment]
Why close it?

**Comment by bczretribution** [comment]
discovered it was a self-inflicted issue.  I had accidentally modified one of the games .xml files when I had opened it to try to learn how the code handled SPAs.  It was that extra line that was causing the error.  restored the .xml to the original file and its working fine now.
