### ISSUE TITLE
[43.10 AtB] adjust contract pay doesn't seem to work

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#729]
### Environment
43.10

### Description
the "adjust contract payment for deployment limits" option in the AtB tab of the options seems to be nonfunctioning.  By its description, when it is selected it is supposed to identify when the leader's strategy skill allows fewer units to be deployed than a contract requires and adjust the contract's requirements and pay to match the strategy limit.  In the attached campaign contracts are generated requiring 9 lances be deployed by the leader's strategy limits deployment to 6.  the contracts, however, seem to continue to require 9 units be deployed.  

### Files
[glitch.zip](https://github.com/MegaMek/mekhq/files/2015537/glitch.zip)

**Comment by bandildo** [comment]
@bczretribution looks like some mechs are missing, which can hinder the debugging. Could you provide them, please?

![image](https://user-images.githubusercontent.com/12190053/42958806-8ab053dc-8b7e-11e8-8a1c-89399656466e.png)

Cheers

**Comment by bczretribution** [comment]
[glitch.zip](https://github.com/MegaMek/mekhq/files/2211291/glitch.zip)

many of the customs listed on that screenshot were in the files that were sent, this is every custom I have if this doesn't work then there would appear to be an issue with loading customs (this has happened once before with one of my bugs)

**Comment by bandildo** [comment]
@bczretribution in the first zip you only included "Aegis Consulting", I've noticed the ones missing are included in your second zip. I guess you just forgot to copy "The Cavalry", but no worries: I managed to circumvent the issue and the fix is pending now in #812  :)
