### ISSUE TITLE
feature request: ability to GM modify a contract's score (AtB)

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#730]
There have been several situations where being able to manually edit the contracts score (usually down) would be helpful.  A prime example comes from the AtB rules excel sheet.  

"Depending on the mercenary size and type of contract the employer will demand a certain number and type of lances to be deployed every week – failure to do so will result on minor contract breaches equal to the number of lances below the minimum number/type required."

There are situations where a player may wish to intentionally under deploy to a contract, such as when at a very high score for a garrison duty and wanting to take a subcontract and stay within strategy deployment limits.  MekHQ, however, does not apply the minor contract breach penalty when this is done, and so the ability to modify it using GM mode would be useful.

More generally the ability to manipulate the contract score would be a useful capability for a GM to have when managing a player campaign.

**Comment by NickAragua** [comment]
This was implemented with PR #760
