### ISSUE TITLE
[43.10 AtB] contracts become uncompleted

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#731]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.

### Environment
43.10

### Description
playing a clan star adder game in AtB.  finished my first contract as a narrow success.  handled my retirement roll and saved.  just loaded it up again after a few days and the contract is not completed.  completed it again and advanced the day, contract lost its complete status again.

### Files
[glitch (2).zip](https://github.com/MegaMek/mekhq/files/2020903/glitch.2.zip)

**Comment by bczretribution** [comment]
Have now had this issue occur with a different campaign file.  This one my long-running merc game.  terra subcontract 5 diversionary raid is having the issue.  It and subcontract 4 ended on the same day, and I completed both of them one successfully and one a failure.  Hit next day and subcontract 5 was in progress again, ended it again, advanced day, and its active again.

[glitch.zip](https://github.com/MegaMek/mekhq/files/2029631/glitch.zip)

**Comment by Flibjib** [comment]
Can confirm I'm seeing this behavior as well, across both old campaigns and fresh ones.

**Comment by NickAragua** [comment]
Fixed with PR #738
