### ISSUE TITLE
Campaign will not load

### ISSUE THREAD

**Issue by tgclightguard** [MegaMek/mekhq#732]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.

### Environment
What version of MekHQ does your issue apply to? mekhq-0.43.10-RC4
What operating system are you using?  Mac
What java version are you using?  1.8.0_171-b11

### Description
Describe the issue and provide screenshots ingame if able: I go to open a campaign file, and I get the error "The Campaign file could not be loaded. Please check the log file for details."
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the campaign file if applicable: Happens every time I load the campaign file. If I load an older file, it works fine.

### Files
Provide the .cpnx campaign file that this issue occurs in.
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the mekhqlog.txt file for any NPE's or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual mekhqlog.txt file

[FCS WD2 Campaign Issues.zip](https://github.com/MegaMek/mekhq/files/2023158
/FCS.WD2.Campaign.Issues.zip)

If I'm missing anything, I will gladly attach the missing files.

**Comment by NickAragua** [comment]
It looks like the campaign save file got truncated somehow. Hopefully, you've got a backup, as I don't think there's any way to recover it. Well, the unit list is partially there, but it cuts off in the middle of a Saladin Mk II HCV. Sorry.

**Comment by pheonixstorm** [comment]
I wish we could have seen the log when it was last saved. To not fully write the campaign out seems like there was an exception or some other glitch that could have shown up.

**Comment by NickAragua** [comment]
Issue is due to corrupted campaign file.
