### ISSUE TITLE
Just started.  Lovin' this program but can't get it to save anything!  Want to start a campaign so bad

### ISSUE THREAD

**Issue by KairosCommentary** [MegaMek/mekhq#734]
Using your newer snapshot windows 0.43.10-RC4  The stable version from 0.42.2 for windows just crashes as I confirm the initial settings from the very first window, lol.

I'll get my starting crew of 2 lances, parts, people, sorta organize 'em and get the ATB goin' and so far so good, and I'll try to export everything to each file like parts n' units, no error messages, but also nothing actually happens.  Saving campaign settings causes an error message 

- campaign  save attempt http://prntscr.com/jkwsjc

REALLY looking forward to getting this started.  You guys have basically created what I've always wanted for BT.  over the last generation or so.  Really grateful for this.

Unrelated to the bug, but while I have your attention, is there any chance there will be soundfx or perhaps anything similar to crescent hawk's revenge?  At least during the firing phase, some sort of 
 visualization of the attacks?  Just curious, willing to donate towards something like that.

**Comment by pheonixstorm** [comment]
This is not enough information. What java version, OS, log files??

**Comment by HammerGS** [comment]
As mentioned we need the log file the screenshot references.  As for sounds it's been requested but the nature of how the phases work in Megamek make it challenging and not likely any time soon.

**Comment by pheonixstorm** [comment]
The logs will be in the log directory. They are created as soon as you run the program. Java and Windows version should be fine so something else is causing the issue. W/o the log file there won't be much we can do to help. Go into the MekHQ directory -> logs and attach the mekhqlog.txt file

**Comment by KairosCommentary** [comment]
Y'all are fast as hell btw.

**Comment by HammerGS** [comment]
NPE from the Log

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.gui.dialog.CustomizeMissionDialog.btnOKActionPerformed(CustomizeMissionDialog.java:213)
	at mekhq.gui.dialog.CustomizeMissionDialog.access$000(CustomizeMissionDialog.java:40)
	at mekhq.gui.dialog.CustomizeMissionDialog$1.actionPerformed(CustomizeMissionDialog.java:177)
```

Do you happen to have the Megamek log as well, it would be in the same folder.

We aim to please :)

**Comment by pheonixstorm** [comment]
Only because you posted this when several of us were on lol Usually takes a few hours or a day.

**Comment by KairosCommentary** [comment]
[megameklog.txt](https://github.com/MegaMek/mekhq/files/2024589/megameklog.txt)

**Comment by KairosCommentary** [comment]
This all generally happened following this guy's guide, just with different mechs and in 3025, and a couple pilot promotions for CO/XO and generally making my TO&E up to snuff.  Was helpful just makin' sure I didn't click something wrong.  U guys have a discord btw?
![pdf](https://user-images.githubusercontent.com/13989335/40337681-2e8c9b0c-5d2e-11e8-8dbb-98066405428a.jpg)

**Comment by KairosCommentary** [comment]
http://www.mediafire.com/file/kffatbm11ffus7l/Against+the+Bot+Instructions+v2-5.pdf

**Comment by HammerGS** [comment]
No we've never set up a discord, we use Slack - http://megamek.org:3000/

**Comment by KairosCommentary** [comment]
Was asked to put this here:

Stable version of mechHQ 0.42.2 crashes when starting a new campaign.
Windows 10 64 bit, java (build 1.8.0_171-b11), 

I create a campaign, Intro window pops up asking me to name my campaign and everything.  Looking like this:  http://prntscr.com/jkxj09  Starting date 1/1/3025 

Program ends.

No log files.  Just this:  http://prntscr.com/jkxjp1

**Comment by PhoenyxCullen** [comment]
C:\Program Files*\ tends to have a admin-only write privilege to save there. Asked him to try to save to Documents folder for any campaign files, and it worked!!!

**Comment by KairosCommentary** [comment]
Yep, so far so good.

**Comment by NickAragua** [comment]
Issue was due to insufficient permissions in save folder. Generally, I would recommend not to manually install programs to system directories.

The exception, I believe, is unrelated, but happens when you type a "custom" planet name (not one of the auto-suggested ones) into the edit mission dialog. It'll fail silently, preventing progress out of that dialog via the ok button.

**Comment by NickAragua** [comment]
Fixed the issue uncovered by the provided log file as well.
