### ISSUE TITLE
Change megamek.info to megamek.org in github descritption

### ISSUE THREAD

**Issue by derNarr** [MegaMek/mekhq#735]
megamek.info seems to be a not so good working redirect to megamek.org, if you click the link on the github description of this project (http://megamek.info/mekhq) it gives you a 404, but if you browse to https://megamek.org/mekhq the proper side is displayed.

Side note, for megamek.org https works fine, for megamek.info not at all (no redirect).

For me as a newcomer it seems, that the description should point to https://megamek.org/mekhq directly.

**Comment by NickAragua** [comment]
This has been fixed with PR #753

**Comment by firefly2442** [comment]
This also needs to be changed on the Github page.  The description at the top.
