### ISSUE TITLE
3.27, ATB : RATs are not used correctly

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#74]
According to the ATB options, RATs at the top are supposed to be checked first. At the moment I have Era report 3053-3062 at the top and the game year is 3058...but the clan steel viper OPFOR is NOT using the 3053-3062 RAT...its using some other RAT.

I tested this by removing the Nova prime variant from the 3053-3062 clan steel viper RAT and the opfor would still keep generating Nova prime variants. There's nothing wrong with the RAT itself, generating units using the RAT in Megamek works fine, but ATB is using the incorrect RAT somehow.

[#battletech.zip](https://github.com/MegaMek/mekhq/files/264676/battletech.zip)

Also the unit market is always flooded with succession war variants even if you have late era RATs at the top and have the campaign year set to 3067 or later.

**Comment by neoancient** [comment]
Era Report 3062 has 3055 RATs for IS successor states in addition to the 3062 RATs. Other factions, including Steel Viper, have only 3062 RATs. Since this is after your campaign year, MekHQ is going to the next one on the list, which is ER 3052.
