### ISSUE TITLE
[43.10] BombsDialog, laser-guided bomb/AAA missile, ArrayIndexOutOfBoundsException again

### ISSUE THREAD

**Issue by Crutchmaster** [MegaMek/mekhq#740]
### Environment
43.10-rc4, Linux 3.16.0-38-generic #52~14.04.1-Ubuntu SMP
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)

### Description
Bombs dialog throw ArrayIndexOutOfBoundsException if I have LG bomb or aaa missile in warehouse.
(Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
	at mekhq.gui.dialog.BombsDialog.initGUI(BombsDialog.java:85)
        ...etc)

### Files
>Provide the .cpnx campaign file that this issue occurs in.

Bug works with clean campaign.

**Comment by NickAragua** [comment]
Fixed with Megamek PR #991
