### ISSUE TITLE
NPE at AbstractUnitGenerator.generateTurrets

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#745]
### Environment

mekhq-0.43.11-RC

### Description

NPE at AbstractUnitGenerator.generateTurrets

Can replicate this error. Load campaign file attached (Sunday). Press 'Advance Day' (Monday).

Either NPE at AbstractUnitGenerator.generateTurrets or NativeMethodAccessorImpl.invoke0 error will appear. 

Files attached for testing.

### Files

[Customs - SirMegaV - Mechfiles.zip](https://github.com/MegaMek/mekhq/files/2086556/Customs.-.SirMegaV.-.Mechfiles.zip)
[AbstractUnitGenerator.generateTurrets-campaign.cpnx.zip](https://github.com/MegaMek/mekhq/files/2086557/AbstractUnitGenerator.generateTurrets-campaign.cpnx.zip)
[AbstractUnitGenerator.generateTurrets-log-1.txt](https://github.com/MegaMek/mekhq/files/2086558/AbstractUnitGenerator.generateTurrets-log-1.txt)
[AbstractUnitGenerator.generateTurrets-log-2.txt](https://github.com/MegaMek/mekhq/files/2086559/AbstractUnitGenerator.generateTurrets-log-2.txt)

**Comment by neoancient** [comment]
I couldn't reproduce it, but based on the stack trace it looks like either there are no RATs available for gun emplacements or the earliest available is later than the current campaign year. I can add some checks that will allow a more graceful recovery.
