### ISSUE TITLE
[0.43.11-RC5 : Bug] NativeMethodAccessorImpl.invoke0 Error

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#747]
### Environment

0.43.11-RC5

### Description 

NativeMethodAccessorImpl.invoke-log.txt0 error when replacing cargo bay.

1. Load campaign
2. Go to repair bay
3. Select Black Eagle, replace cargo bay using GM
4. NativeMethodAccessorImpl.invoke0 error will appear in log

### Files

[NativeMethodAccessorImpl.invoke-log.txt](https://github.com/MegaMek/mekhq/files/2086583/NativeMethodAccessorImpl.invoke-log.txt)
[Customs - SirMegaV - Mechfiles.zip](https://github.com/MegaMek/mekhq/files/2086584/Customs.-.SirMegaV.-.Mechfiles.zip)
[NativeMethodAccessorImpl.invoke.cpnx.zip](https://github.com/MegaMek/mekhq/files/2086585/NativeMethodAccessorImpl.invoke.cpnx.zip)

**Comment by neoancient** [comment]
The Black Eagle in the provided campaign file does not have a damaged cargo bay. I tried repairing other components and was unable to reproduce the reported issue. The log shows this to be the same issue as #748.
