### ISSUE TITLE
Comstar Interdiction does not lift when contract is completed

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/mekhq#75]
HQ rolled an Interdict for me on the last month of an objective raid, once I completed the mission on the end date the interdict never stopped until I jumped all the way home and created/accepted a new contract.  

![image](https://cloud.githubusercontent.com/assets/16950832/15272275/367ab4e8-1a37-11e6-9d1d-3b5a1cf9cd09.png)

Obviously I can get around this by creating and accepting a new pre-deployment training mission back on the homeworld of Ziliang but, I would think the interdict should cease once the current contract is marked completed.  If a new contract is accepted and then deleted the interdict returns and cannot purchase parts due to unit rating and my admin's skill.

[Interdiction.zip](https://github.com/MegaMek/mekhq/files/264849/Interdiction.zip)

Also, when I mothball my mechs for the ride home to keep maint costs down is it supposed to count as my unit not having any mechs for the unit rating?  With mechs active I have a C(60) mercs:revised rating but, mothballed goes down to D(45).  I still have my mechs and would think it should still count whether mothballed or not but, I have not bought IO or Mercs:rev yet to check.

The 30260727 save is the end date for the current contract and it is marked as complete.
The 30261015 is when I had jumped all the way back home with the interdict still in effect.
Included my force and portrait images just because.

**Comment by neoancient** [comment]
When the contract ends, the parts availability is computed according to this chart:
![noncontract_rating](https://cloud.githubusercontent.com/assets/16927464/15987604/2cdac21c-2ff3-11e6-8cf8-a2d4da28ffdd.png)

I stepped through the code while it was calculating your parts availability and verified that it is using this method.
Your unit rating is C (2) and you have no admin/logistics (-2), resulting in a parts availability of zero.

**Comment by BLOODWOLF333** [comment]
I forgot to update this.  Yeah this is my derp, my mechwarrior 1LT (admin/logistics) promoted to a Captain (admin/command) which left me with no admin/logistics.  And I just didnt put two and two together.  So, now I just designate my 1LT, Maj, & LTC admin/transports to have the primary occupation of admin/logistics.  So, my bad.
