### ISSUE TITLE
[Feature Request] Option for automating marriages

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#765]
Currently female crew members can 'accidentally' get pregnant automatically (optional). Might as well add auto marriages (optional) too. But please remember to consider their ages too. Will be scary to receive 20+ with 80+ for 5 times in a week etc.

**Comment by pheonixstorm** [comment]
This feature should make it in the next dev cycle as it is one I have been working on.

The chance per day will be around the same as non-relationship conception which is pretty low. This way you will get a few marriages per month at most.

**Comment by SirMegaV** [comment]
As long as it's low, cos I think I have over a thousand crews.

**Comment by SirMegaV** [comment]
Hi pheonixstorm, was the auto marriage thingy implemented yet? 

At the same time, you know when you manually select a spouse, you mouse over the arrow to scroll down. Problem is I have thousand of crew and mouse over scroll takes a lot of time to reach older crews. :)

**Comment by Windchild292** [comment]
You can assign this to me, I'm going to add it with the ability to determine the probability of the event happening. I've got the basis down through my changes to the procreation logic, and will likely code this similarly to that.
