### ISSUE TITLE
Display issue in advance multiple days when days > 1

### ISSUE THREAD

**Issue by firefly2442** [MegaMek/mekhq#772]
### Environment
What version of MekHQ does your issue apply to?
* 9755ac915c19bb20aaffb3814a996cf5a388c68f

What operating system are you using? 
* Windows

What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.

```
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```

### Description
* Start a campaign
* Click "Advance Multiple Days"
* Click "Start Advancement" to advance 7 days
* See that all days are listed in the daily log in the open dialog box
* Set days to 7
* Click "Advance Multiple Days"
* Notice now only the first day is displayed and a bunch of horizontal lines.

![advancedays-error](https://user-images.githubusercontent.com/531175/41814116-8c79303a-7701-11e8-9a8b-0f441ffe6889.png)

The actual time advancement is correct but it seems the display of the results does not work correctly.  It always works on the initial start of the dialog but it doesn't work for subsequent time advances greater than 1 day.

## Fix
I started to work on this issue by converting the text strings to resourceMap for localization.  I then went to hunt the bug but I can't quite figure out where the problem is.
https://github.com/firefly2442/mekhq/tree/advance-days
If someone can point me in a direction I can try it and test.  Thanks.

**Comment by neoancient** [comment]
What was in the log?

**Comment by firefly2442** [comment]
I don't see any major Java errors.

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2130393/mekhqlog.txt)
