### ISSUE TITLE
AtB Popup "you do not meet deployment requirements" Should say what requirement is not being met. 

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#779]
AtB Popup "you do not meet deployment requirements" Should say what requirement is not being met.

Bumped into this today, accepted a contract, and got this popup, which was not helpful in determining the unfulfilled requirements.

**Comment by firefly2442** [comment]
Was it this message?  "You have not met the deployment levels required by contract. Do your really wish to advance the day?"  I believe that's referring to the deployment requirements in the bottom right corner of the briefing room tab.  Do you have any suggestions on how to make that message more clear?

**Comment by VampireSeraphin** [comment]
I believe that is the message I bumped into. A more clear version would read:

"Your force does not meet the following deployment requirements: dynamic list of unmet requirements here in red. Do you still want to advance the day?"

**Comment by giorgiga** [comment]
@BLOODWOLF333 
I had your same issue - see #886 (this ticket is about improving the popup message as far as I can tell)

**Comment by VampireSeraphin** [comment]
For anyone not on the slack, this has been clarified to be a bug wherein the message should not be triggering until the unit has arrived at the same planet as the contract. It is NOT a feature wherein players are getting advanced warning. 

Now, while I would like such a feature, after discussion I do not consider it tenable in a game where a Steiner scout lance is a thing. Trying to code a solution that detects when an assault lance is actually scouts versus actually an assault lance is almost certainly impossible. That way lies madness.

**Comment by sixlettervariables** [comment]
I believe this was handled in #1007.

**Comment by sixlettervariables** [comment]
This is still a problem in one case: the contract hasn't begun yet (all other cases were handled in #1007). This will be handled in #1038.
