### ISSUE TITLE
Add new tech and mek selection sub menus to personnel and hanger panels. 

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#780]
Hey guys, I love the new sub menu system for assigning techs and mechs in the TO&E. 

Can we get that same system brought over for assigning pilots/techs to units in the personnel panel, and techs to units in the hanger. Ty.

**Comment by pheonixstorm** [comment]
Can you be a little more specific on this not sure if I am understanding what you are asking correctly.

**Comment by VampireSeraphin** [comment]
![image](https://user-images.githubusercontent.com/19868605/42179347-96f730e6-7e01-11e8-87d5-f131a0e24689.png)

These nested menus are great. Can we get them for the personnel and hanger screens to assign pilots and techs by skill level/type.

**Comment by Windchild292** [comment]
I'll add this for the personnel window, as it has already been added to the hanger.

**Comment by Windchild292** [comment]
The code for this is ready, just waiting for #1599 to open.
