### ISSUE TITLE
[RFE] Add currently assigned unit to personnel tab

### ISSUE THREAD

**Issue by Mekslayer** [MegaMek/mekhq#784]
I'd like to to make a request...

I often wish to assign my mech pilots to mechs by their P/G skills... in mekHQ.

and so it is very frustrating for me to open pilots "mechwarriors" and "general" and not see their P/G skill. then when I list my mech pilots by P/G skills, I can't see what mech they are assigned to and which units they are in. this is very frustrating. Can we get a few more fields added and be able to sort by this fields? like its done in Excel?

thanks guys,

-McSlayer

Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.

### Environment
What version of MekHQ does your issue apply to?
What operating system are you using?  Windows, Mac, or Linux?
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.

### Description
Describe the issue and provide screenshots ingame if able.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the campaign file if applicable.

### Files
Provide the .cpnx campaign file that this issue occurs in.
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the mekhqlog.txt file for any NPE's or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual mekhqlog.txt file

**Comment by neoancient** [comment]
Where are you trying to sort them? The personnel tab has a number of display options, one of which is piloting and gunnery skills. It's pretty compact, but you can double-click on the table to expand it.
![image](https://user-images.githubusercontent.com/16927464/42488110-9ea335a6-83c9-11e8-8292-0a32c06752e5.png)

**Comment by Mekslayer** [comment]
Did you read what I wrote? Did you notice that your list shows none of the pilots assigned mechs?

If You can't find a pilot who is 4/5 that is not yet assigned to a mech, what good comes from all these useless fields?

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/44998285-e30d3f80-af79-11e8-92b4-c7ab1b9756b9.png)

So, your telling me it is too hard to sort your pilots by the skill column in the personnel tab where it shows if they are assigned to a unit or not?  And requires too much work to click on the person and see their exact P/G skills?  Also that it requires too much effort to delete the instruction text and fill out a bug report according to the instructions from our template when you make a bug report/feature request on here?

This is a volunteer project, nobody is getting paid for this, I dont like your tone that you just responded to Neo with, if you want to put ZERO effort into bug reports and using HQ, and then cock an attitude with the developers.....dont waste our time.  Nobody has to put up with that bullcrap.  If you can do it better, learn java, and then put forth the effort to make the GUI better.

**Comment by Mekslayer** [comment]
So yes... I am sorta, if you sort by skills you have to check if a pilot is 2/5 and not 3/4 so you have to go back and forth to find the right pilot who is say 2/5 to assign to the mech. If I am trying to make a specific BV I can do it with a 3/4 pilot but not a 2/5 pilot. So I have to go thru mechwarriors General view tab to find the pilot unassigned, look at each ones P/G see if it is the P/G I want, then I have to check if in his log he pilots the right tonnage of mech, one pilot at a time. It would be ,much easier if I could scroll through the spreadsheet list of pilots that shows their name / P/G / Mech assigned / Personal Log, but I cant do this.

**Comment by NickAragua** [comment]
So basically, this whole thread could have been condensed to "Please add assigned unit to the personnel tab". 

I've edited the title to be a little more clear as to what's being asked.

**Comment by Mekslayer** [comment]
Ahh yes... probably so... I don't do much in S/W so suck at doing bug tracking. Kinda out of my expertise.

**Comment by Windchild292** [comment]
Closing for abject rudeness to the development team.
