### ISSUE TITLE
SLDF Ranks Are Wrong

### ISSUE THREAD

**Issue by Patriot1776** [MegaMek/mekhq#785]
The ranks for the SLDF are wrong. They didn't have Lieutenant JG and Lieutenant SG. They just had Lieutenant. Warrant Officer is also missing from the list of ranks.

**Comment by giorgiga** [comment]
From http://www.sarna.net/wiki/Lieutenant it seems like the ranks have changed between SLDF instalments

**Comment by pheonixstorm** [comment]
Yes, the ranks were different slightly between the first and second SLDF.

**Comment by jschmetzer** [comment]
Is the better solution to update to SLDF v1 ranks, or to add second SLDF as a new rank system? I see how to do either, but I'm not sure which is better.

**Comment by HammerGS** [comment]
I haven't looked at this at all since posted, but I'd agree 2 versions of the SLDF ranks would be best.

**Comment by purpledragon2** [comment]
I don't know if this might should be a separate Request for enhancement, but, an answer might be to have multiple custom ranks available that could be saved locally.  Allow the user to name the ranks tab.  When users finish setting up the ranks as they wish, have them input a name for the rank structures they are using and show it in the ranks lists when they choose which set of ranks to use.  

I can only hope I am making sense with this.  It does in my mind.

**Comment by Windchild292** [comment]
@purpledragon2
#2200 and #2201 will handle those two cases
