### ISSUE TITLE
Purchase Parts menu is super slow, sometimes freezes

### ISSUE THREAD

**Issue by hell-fish** [MegaMek/mekhq#789]
### Environment
What version of MekHQ does your issue apply to? 0.44.0
What operating system are you using?  Windows, Mac, or Linux? Window
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.

### Description
Describe the issue and provide screenshots ingame if able. The Purchase Parts screen takes a while to load, and then there is significant lag with every action I take in the menu. Sometimes after purchasing some items, the PP menu will freeze for about one minute. It's also frozen so long (5 minutes or so) that I force-closed the game entirely. 

### Files
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2173107/mekhqlog.txt)
[1st Panserbjørne30660101.cpnx.txt](https://github.com/MegaMek/mekhq/files/2173108/1st.Panserbjorne30660101.cpnx.txt)

**Comment by firefly2442** [comment]
Can you attach your campaign and the mekhqlog.txt file?

**Comment by hell-fish** [comment]
Done

**Comment by firefly2442** [comment]
I loaded the campaign and was unable to replicate your issue.  Sorry.  My only other idea would be to make sure your version of Java that's installed is up-to-date.

**Comment by sixlettervariables** [comment]
Fixed in #1207.
