### ISSUE TITLE
[Feature Request] Mark TO&E Force as Non-Combat

### ISSUE THREAD

**Issue by ndrwstn** [MegaMek/mekhq#790]
I'd like to mark a Force in the TO&E as a "Non-Combat" (or other similar label) which would remove them from the "Current Assignments" in "Briefing Room". I have a number of non-line elements (e.g. combat support and support units) that aren't relevant in that section, and being able to exclude them would be wonderful.

**Comment by dannylambourne** [comment]
this would be great

**Comment by sixlettervariables** [comment]
If you mark a force as Non-Combatants, should all subforces be marked as such?

**Comment by ndrwstn** [comment]
I'd probably handle it as a per-force flag to allow maximum flexibility.

**Comment by purpledragon2** [comment]
I second or third this RFE.  This is something I have tried to request in the past but could not get devs to understand.

**Comment by Windchild292** [comment]
The code for this is ready, just waiting for #1599 to open.

**Comment by Windchild292** [comment]
Edit: wrong issue
