### ISSUE TITLE
Setup Travis Continuous Integration (CI) 

### ISSUE THREAD

**Issue by firefly2442** [MegaMek/mekhq#791]
[Travis CI](https://travis-ci.org/) has been helpful for another project I worked on.  It is free for open source projects.  It would run the Java Ant build and show any build errors right in Github before the merge into master.  You can even set it up in the repo to not allow merges if the build fails.  I'm not able to do it because I don't have admin on the repository.

https://docs.travis-ci.com/user/getting-started/

If someone can at least do this part, I can work on the `.travis.yml` file.

**Comment by sixlettervariables** [comment]
Implemented by #1065 using Azure.
