### ISSUE TITLE
Initiative, with more than 2 sides

### ISSUE THREAD

**Issue by inqistor** [MegaMek/mekhq#797]
0.44.0 on Windows 10

With 3 sides, where everybody fights with everybody. Queue of moving is based on side having least units. 

If one of them have only one unit, and two remaining have full lances, sides have to move ALL their units at once. Like AAAABBBBC. 
I think it should still divide movement for sides having more units, like ABABABABC. Initiative of C doesn't influence this behavior in any way. First, or last is always the same.

**Comment by pheonixstorm** [comment]
It is. 

@inqistor This should be asked in the MegaMek issue tracker.

**Comment by HammerGS** [comment]
Please re-open this on the Megamek Tracker.
