### ISSUE TITLE
Feature Request: Add Pintle Mounts to Vehicles

### ISSUE THREAD

**Issue by Necrofox91** [MegaMek/mekhq#798]
Hey kinda new here but,
I was Modifying some vehicles and I realised there weren't any Pintle Mounts.
Any chance they could be added?
Don't know if most people don't use them or what but at least completeness sake???
Sorry for not being much help.

**Comment by neoancient** [comment]
Pintle mounts can only be used on small support vehicles (see Tech Manual, p. 234). The closest equivalent for combat vehicles is the vehicular sponson turret (Tac Ops, p. 348), which is available in Other Equipment if your tech level is set to experimental or unofficial. If using variable tech levels they become advanced in 3079 and standard in 3080. Once they are placed in the side locations, you can move a weapon in that location into the sponson turret by right-clicking. Unlike the pintle mount they can carry heavy weapons but must be mounted in pairs.

**Comment by Necrofox91** [comment]
Errr don't watn to beat a dead horse but (Tech Manual, p. 235)
Unit Restrictions: Pintle mounts may only be used by ground-based **Combat** and Support Vehicles (those using a Wheeled, Tracked,
Hover or WiGE motive system), Combat and Support VTOLs, and Airship Support Vehicles.
The only restriction is weight (less than half a ton) and weight calculation is different for combat and support vehicles.
Sorry I didn't provide a reference before.

**Comment by Necrofox91** [comment]
Also they can't be armored. But Machine Guns, Small Lasers, Flamers and AP Gauss can be mounted.
And AMS too I suposse.
(Ammo is stored elsewhere)

**Comment by neoancient** [comment]
You're referncing an older edition of the Tech Manual. This has since been corrected to support vehicles only. See errata here: https://bg.battletech.com/errata/. These changes are reflected in the corrected third printing of the Tech Manual, released in 2013, which is what I cited in my previous response.

**Comment by Necrofox91** [comment]
Ok sorry. My bad then.
