### ISSUE TITLE
Automated Skill Purchases

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#80]
How it would work...
Probably a Menu command under Manage Campaign... Brings up a new Window with the following GUI elements

Design
1 ) Drop Down Menu for Personnel Type
2 ) Drop Down Menu for Skill Level (Green, etc)
3 ) Drop Down Menu for a Skill
4 ) Drop Down Menu for a Skill Rank*
5 ) Small Text Area for reporting results
6 ) A Check or Search Button
7 ) An OK or Execute Button
8 ) A Cancel Button
9 ) A Progress Bar

*It should use the values available in Skill Tab of Campaign Options. Including skipping certain ranks and the XP costs.

Example of Operation
1 ) Set Personnel Type to Administrators
2 ) Set Skill Level to Green
3 ) Set Skill to Small Arms
4 ) Set Skill Rank to 4

Click Check Button > In a small reporting area "N Personnel can Train"
Click Execute Button > In a small reporting area "N Personnel have trained" could also echo to Daily Log. Short version though... just the number of people who have trained skill (Name)

In the above example every Green Administrator who doesn't have Small Arms 4 will expend all available XP trying to get to 4.

Examples of the short text reports so that Daily Log isn't over-run.

Although not really necessary, I the Skill Level filter might be very useful in preventing horrifically long times to update.

**Comment by BLOODWOLF333** [comment]
We do need this.  For those who have 1000+ personnel a mass spend XP with conditions "macro" would be very useful to have and save them a lot of time with unit admin.  Maybe name it "Spend XP on Multiple..." under manage campaign.  And then creates a pop-up window like with hiring personnel:
![mekhq1](https://cloud.githubusercontent.com/assets/16950832/15524363/71460fca-21e7-11e6-91e5-c0f49af9b438.png)

Primary Role: [list of all available primary roles]
Skill Level: [Any-Elite]
Skill: [list of all available skills] SPAs can be done normally
Target Number: [what TN of the skill this function will spend XP on until it stops]

Search: [searches the entire personnel tab for entities that match the above criteria and then displays in the text box "xx persons selected" or "no persons match criteria"]

**Comment by scJazz2** [comment]
Thanks for the Mockup Carr (Bloodwolf). Title of window/command should be like "Batch Spend XP" since that actually makes more sense than anything I've said yet.

**Comment by Akjosch** [comment]
An initial implementation is in (and will be available in the next daily/release), though I'm sure there are a few issues with it still and it could need a few more filters to whittle down who exactly to level up (for example, a "which force this person is assigned to").

**Comment by Akjosch** [comment]
Seems to be satisfactory for now. Updates and new features please as a new RFE.
