### ISSUE TITLE
44.0 AtB morale calculation seems off

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#814]
### Environment
mekHq 44.0

### Description
attached is a save file right before the turn of hte month.  based on the excel sheet the morale calculation should be rolled at a -6 (A rated -2, 15+ victories in the month -3, no defeats -1), meaning the highest possible score of a 6 should keep the morale the same, at a 2% chance, otherwise, enemy morale should decrease.  multiple reloads and starts of the month show these odds to be very off.  I first started to expect this several contracts ago as anecdotally all my contracts seemed to have unusually high chances for morale to increase in the situations.  

### Files
[glitch.zip](https://github.com/MegaMek/mekhq/files/2215920/glitch.zip)

**Comment by bczretribution** [comment]
[glitch.zip](https://github.com/MegaMek/mekhq/files/2246651/glitch.zip)
new contract.  just turned the first month of the contract, according to excel morale roll should be at -5 (-1 green enemy, -2 A rated, -1 5 victories, -1 no defeats), meaning the maximum possible roll would be a 7: morale remains the same.  morale increased to 5, meaning a result of at least a 9

**Comment by sixlettervariables** [comment]
It looks like when we calculate the modifier based on your dragoon's rating, we didn't subtract it (instead adding to the modifier your difference from a C rating):
```java
		mod += dragoonRating - IUnitRating.DRAGOON_C;
```

**Comment by NickAragua** [comment]
Fixed with PR #814
