### ISSUE TITLE
Dropshop Baydoor unrepairable

### ISSUE THREAD

**Issue by CormacAers** [MegaMek/mekhq#819]
### Environment
mekhq 0.44.0 windows, no edited gamefiles (beside adding a new faction that's unused right now)

### Description
Union (2708) Dropship has a damaged mechbay door (2 damage), no matter what i do, the damage is not removeable. neither repairing them the normal way solves the issue, neither does complete (repair)task, nore does restore unit works, same with edit the damage. 
side note, the ship has in it's damaged state 90 heatsinks which are not listed as damaged, but after restoring the unit repairs the heat sinks up to 360, but even though it is makred as undamaged, the bay door is still destroyed. save&loading the game will remove the damaged heatsinks down to 90 again and does not fix the bugged/destroyed door (if it was repaired and was not showing in the repair bay list, it does now again.

the same door was damaged a day ago, to, but it was replaceable at that time without bug (even though i had problems getting the part to show up as in my last thread that i was unable to replicate myself later)

### Files

[Shaniels Order.zip](https://github.com/MegaMek/mekhq/files/2216630/Shaniels.Order.zip)

**Comment by neoancient** [comment]
I have a fix for the bay doors, but I don't understand what you're saying about the heat sinks.

**Comment by CormacAers** [comment]
doublechecked it. that may be different bug. if you load the game, the union has 90 heatsinks (whoch is the right amount, i'm seeing right now)
if you rightclick on the unit, under gm mode 'restore unit' it adds more heatsinks than it should be. befor, it 'restored' the heatsinks up to 360, when i repeat it now, it adds 90 heatsinks everytime i restore the unit (which is to much). after safe&reload i've got the correct amount of heatsinks again.
