### ISSUE TITLE
GM Mode: Convert Unit to Parts Option

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#822]
Intended for boneyard and parts file creation, can we get an option that converts a unit in the hanger to its spare parts. Ideally, this would be an option where you select multiple units, right click the Gm options, and have a choice to instantly convert all selected units into their constituent parts.

This would allow for importing a mul, stripping them to create a stating warehouse, then importing the mul again or generating a new force using the parts without needing to purchase everything one at a time.

**Comment by neoancient** [comment]
That sounds very useful and pretty simple to implement.

**Comment by sixlettervariables** [comment]
I've got this working and am wondering if it were Ok if the feature was simply, "Strip Unit" and it did not also remove the unit. On Slack it was discussed that this would enable the units to be stripped for parts, then restored (via the GM menu) saving you from reloading the MUL.

**Comment by VampireSeraphin** [comment]
As long as it works on multiple units at once it sounds great. This idea is
aimed at large formations.

**Comment by VampireSeraphin** [comment]
Cool. Ty.

This will make setting up large units much easier.
