### ISSUE TITLE
Allow Co-Op Team Scenario Resolution In Multiplayer Games

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/mekhq#833]
### Environment
MekHQ 0.44.0
Windows 8.1
Java 1.8

### Description
From Casual_joker who streams MekHQ on twitch on Saturdays:

> Problem:
> 
> MekHQ is normally is for running a single-player campaign. However, you can play the battles cooperatively in multiplayer by switching some (or all) of your units to other players in the MegaMek lobby. However, just before the battle is over, the other players must use the "traitor" command to give back the units to you. Alternately, everyone (including you) can save their surviving units to a mul file, then they can send the files to you and you can manually merge their mul files with your mul file. You can then manually resolve the scenario using the modified mul file.
> 
> Both of these methods are cumbersome, and it's easy to forget to do either and thus mess up the scenario resolution.
> Suggested Solution:
> 
> When MegaMek prompts if you want to save the surviving units to a mul file, after you click "Yes", MegaMek can display another dialog box that contains a list of all of the players who were on your team (including yourself) and that has the following text:
> 
> "Choose all players whose units will be included in the mul file."
> 
> You then put a check in a box by each name or click to highlight (whichever method is easiest to implement) for the players whose units will be included in the mul file. Your own name is chosen by default, although you can choose to exclude your own units. Who knows--there might be some situations in which the hosting player might not want his units included.
> 
> Have two buttons in the dialog box, "Select All" and "Unselect All", to make things a little easier for a game with a large number of players.
> 
> After choosing the players, you click "Next", "OK", or "Done" (whichever makes the most sense as compared to the existing MegaMek dialog boxes). You then get the existing dialog box that prompts you to enter the name of the mul file.
> 
> The resulting mul file will contain all of the players' units that you chose as if they were all units that you owned. This would include the pilot status, 'Mech damage, and kill records. The rest of the mul file will be the same as it is now.
> 
> While I described this method with the manual resolution method, if possible, also implement this idea with the automatic resolution.

### Files
NA

**Comment by NickAragua** [comment]
Since each unit in the player's campaign has a unique ID associated with it, it's actually a lot easier to keep track of player units given to other players. This will be in the next dev release.
