### ISSUE TITLE
Gradle Build System

### ISSUE THREAD

**Issue by firefly2442** [MegaMek/mekhq#835]
The [Gradle](https://docs.gradle.org/current/userguide/java_plugin.html) build system seems to have some benefits over the current [Ant](https://ant.apache.org/) build system.  One of the main benefits is the ability to utilize repositories of libraries and download .jar files.  Many of the libraries in `/lib/` could be automatically downloaded and not kept in the Git repo which is leading to the Git repo size going up via all the binary files.  Gradle can also automatically build up jar files for release, automatically build Eclipse projects, and much more.

I've started a branch with a start for Gradle.  It's not working currently but you can see what the build file looks like.  If other developers/maintainers are interested in this, please speak up and I can continue working on it.  I wanted to check with others before I continue time investment in it.

https://github.com/firefly2442/mekhq/tree/gradle/MekHQ

**Comment by neoancient** [comment]
I already told you that it's been under discussion.

**Comment by firefly2442** [comment]
That's fine, just trying to help...
