### ISSUE TITLE
Can't Change Personnel Market Types in Campaign Options

### ISSUE THREAD

**Issue by yukamichi** [MegaMek/mekhq#842]
### Environment
MHQ 0.45.0
Windows 10
Java 1.8.0_171-b11

### Description
Trying to set the Personnel Market type in the Campaign Options has nothing available in the pull-down menu. Choosing any of the presets when starting a new campaign also just defaults to the same unnamed Personnel Market. It appears to be using Dylan's by default.

**Comment by HammerGS** [comment]
Can you give us steps to re-produce? Is this a new game, and existing game?

**Comment by neoancient** [comment]
This might be another issue with the packaging script not building the jar correctly. I won't have a chance to look at it until this evening.

**Comment by mchapman1970** [comment]
I have the same issue both in a new campaign and also an existing campaign.

**Comment by MattDroz** [comment]
I noticed that in the plugin documentation, you use the Personnel Market as an example. But I also noticed that there is no plugins directory that was part of the 45 download.
