### ISSUE TITLE
[Feature Request] More Supported Folders in "userdata" Folder

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#854]
Currently the following folders cannot be used in the "userdata" folder.

1. data/boards
2. data/images/force
3. data/images/portraits
4. data/rat

**Comment by Windchild292** [comment]
This will be implemented as part of implementing #1477, and is covered there. This can therefore be closed.

**Comment by Windchild292** [comment]
Duplicate of #1477
