### ISSUE TITLE
Parts in transit not displayed correctly (0.45.0)

### ISSUE THREAD

**Issue by SirChaos1** [MegaMek/mekhq#855]
Parts in transit are not shown as such in the Repair Bay dialogues - neither within the task lists nor in the Parts Acquisition dialogue; in Parts Acquisition they show up as "in OmniPod", in the task lists they do not show up at all.

Parts on order, though, are displayed correctly in the Repair bay, and everything shows up correctly in the Parts in Use dialogue within the Overview tab.

Note that this only affects the way things are displayed - the parts are still ordered and delivered as they used to be.

To reproduce: Start a new campaign or open an existing one; scrap one part installed in a unit that does not have a replacement in storage. Now buy a replacement part either through Parts Acquisition or Purchase Parts or the Parts in Use dialogue; use GM mode "Procure part" if the purchase does not go through. Parts Acquisition now shows the part as "in OmniPod", and the entry in the task list for replacing the part says "0 in transit, 0 on order".

**Comment by sixlettervariables** [comment]
Able to reproduce, and I could keep on clicking the order button if I was allowed to make multiple acquisition rolls:
```
Jump Jet on Quickdraw QKD-4H scrapped.  

Major Bayani Tumbaga attempts to find Jump Jet 60 ton unit needs 3 and rolls 7: part found. It will be delivered in 5 days.  

Major Bayani Tumbaga attempts to find Jump Jet 60 ton unit needs 3 and rolls 7: part found. It will be delivered in 3 days.  

Major Bayani Tumbaga attempts to find Jump Jet 60 ton unit needs 3 and rolls 7: part found. It will be delivered in 1 days.  

Major Bayani Tumbaga attempts to find Jump Jet 60 ton unit needs 3 and rolls 5: part found. It will be delivered in 6 days.  

Major Bayani Tumbaga attempts to find Jump Jet 60 ton unit needs 3 and rolls 6: part found. It will be delivered in 5 days.  

Major Bayani Tumbaga attempts to find Jump Jet 60 ton unit needs 3 and rolls 9: part found. It will be delivered in 2 days.
```
All six of those acquired are in my warehouse, save/reload does not fix the status.
