### ISSUE TITLE
GM assign xp

### ISSUE THREAD

**Issue by purpledragon2** [MegaMek/mekhq#859]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
What version of MekHQ does your issue apply to?  0.45.0
Windows 10
JAVA 8 update 131

### Description
When creating a new unit commander:
cannot enter numbers to assign xp.  
up and down arrows work find; but if I'm adding hundreds of xp, it can be time consuming.
please allow for numpad entry on all those dropdowns that have up/down arrows.  

### Files
none provided.

**Comment by sixlettervariables** [comment]
Closed via #867
