### ISSUE TITLE
[0.45.0 : Bug] LinkedHashMap$LinkedHashIterator.nextNode Error

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#860]
### Environment
0.45.0

### Description
Not sure what happened, but my latest campaign cannot be loaded. LinkedHashMap$LinkedHashIterator.nextNode error found in log.

Campaign and log attached.

### Files
[LinkedHashMap$LinkedHashIterator.nextNode-SirMegaV25080401-1.zip](https://github.com/MegaMek/mekhq/files/2277026/LinkedHashMap.LinkedHashIterator.nextNode-SirMegaV25080401-1.zip)
[LinkedHashMap$LinkedHashIterator.nextNode-mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2277027/LinkedHashMap.LinkedHashIterator.nextNode-mekhqlog.txt)

**Comment by sixlettervariables** [comment]
A unit in your campaign has no salvageable parts and should have been removed. On load it tries to do that. However, the code in question was not "safe". I've got a fix, and I'm working on a fix for your campaign file.

**Comment by SirMegaV** [comment]
It's OK, no need to fix. I can play again. So what you are saying is that, there's a unit with nothing on it and should be removed from my list, but for some reason, it wasn't. Is that correct?

**Comment by sixlettervariables** [comment]
That is correct. On campaign load it tries to resolve that issue.

**Comment by SirMegaV** [comment]
Thanks. After the fix and merge, will the 'Mass Repair' still cause this issue?

**Comment by SirMegaV** [comment]
Oh.. I'm very sorry, I've forgotten about the custom units... here it goes.... 

[Customs - SirMegaV - Mechfiles.zip](https://github.com/MegaMek/mekhq/files/2277643/Customs.-.SirMegaV.-.Mechfiles.zip)

**Comment by SirMegaV** [comment]
Got it. Thanks.

**Comment by SirMegaV** [comment]
Just a side not, confirm it was caused by mass repair. I did a mass repair in another period, same error. I do it manually, it's OK.

**Comment by sixlettervariables** [comment]
@SirMegaV do you recall if any of these took multiple days?

**Comment by SirMegaV** [comment]
Sorry for the super late reply.. phone's gmail went dead without first telling me.. 

Not sure if it was multiple days work, just know that if I DON'T 'mass repair' then 'advance day', the save is OK. But if I 'mass repair' then 'advance day', the save will have error.

**Comment by sixlettervariables** [comment]
I found two spots where invalid units weren't removed after a repair, and have merged that code. 0.45.2 will contain that work.
