### ISSUE TITLE
Daily Log over filling

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#862]
I'm getting a bug where the daily log is posting multiple days in one pane.

![image](https://user-images.githubusercontent.com/19868605/43962757-80843342-9c86-11e8-9ee2-39f4a6b2240b.png)

Also, github won't let me upload a cpnx?

**Comment by sixlettervariables** [comment]
Yoy have to zip it or rename it `.txt`

**Comment by VampireSeraphin** [comment]
This is happening every time I advance the day normally. I have not tested with multiple days. 

[The Rebel Drifters30011111.zip](https://github.com/MegaMek/mekhq/files/2289007/The.Rebel.Drifters30011111.zip)

**Comment by kmstr113** [comment]
Thank you VampireSeraphin,
    I have just grabbed the campaign file you uploaded and will start looking deeper at the issue.

**Comment by MattDroz** [comment]
Here you go, I have two campaign files attached. the first (Test) was produced before I installed v45, and it opens and works fine regarding the logs, even after re-saving it from the v45 program. The second (Test2) was updated after I installed v45 and it does not work. Maybe they can help? 

(I'm sorry about the file sizes, my campaigns are heavy into generational mechawarriors)

[Team Banzai_Test2.zip](https://github.com/MegaMek/mekhq/files/2299994/Team.Banzai_Test2.zip)

**Comment by kmstr113** [comment]
Thank you I am looking at this tonight I think this may be a larger issue.

**Comment by kmstr113** [comment]
MattDroz,
   I was not able to load the Team Banzai files you submitted.  I am getting an error saying I cannot load specific mechs. I am looking at removing these mechs from the file to see if I can load them. But I am not sure that will be a good test. I will let you know what I find out.

![mech-load](https://user-images.githubusercontent.com/25588069/44347717-90eef900-a466-11e8-8ddf-20e89f87736d.png)

**Comment by kmstr113** [comment]
VampireSeraphin,
   I was able to load your Campaign file and I canclearly see that its not clearing the display when I advance a day. And to MattDroz's point the date is not updated in the Title Bar.
![display-failure](https://user-images.githubusercontent.com/25588069/44348635-f47a2600-a468-11e8-8248-76bb843857fd.png)

**Comment by MattDroz** [comment]
Finally tracked down the culprit in my case. It was a Rifleman that was being mothballed. As soon as I cancelled the mothball, saved the file, and relaunched the program. It was moving along fine.

**Comment by kmstr113** [comment]
I think I have resolved the log over filling. I am doing some further testing as the location I had to modify has other if statements in it that I must test to make sure my change did not impact them. I will start looking into the date updating in the title bar once I am satisfied the log changes did not impact anything else.

**Comment by kmstr113** [comment]
added for @Firefly2442
[Solo30270514.zip](https://github.com/MegaMek/mekhq/files/2363671/Solo30270514.zip)

**Comment by firefly2442** [comment]
@kmstr113 and I tried this via the current master branch and can't seem to replicate this issue.  Could other folks give it a try and see if they can replicate the problem?

**Comment by kmstr113** [comment]
I have tested this with the Current Master Branch myself and this issue does not appear to be happening anymore. @VampireSeraphin is there a chance you can test this again with your campaign? At this time with the most recent master I am not able to replicate the issue.

**Comment by VampireSeraphin** [comment]
![image](https://user-images.githubusercontent.com/19868605/45993913-1e71ca00-c05f-11e8-8e41-f9e69cd024ea.png)

[DoubleDay.zip](https://github.com/MegaMek/mekhq/files/2413840/DoubleDay.zip)

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2413842/mekhqlog.txt)

Managed to reproduce, now with bonus double mission generation when overfilling occurs and log.

**Comment by sixlettervariables** [comment]
I believe this was fixed in 0.45.X. Please let me know if it has not been and I'll reopen.
