### ISSUE TITLE
Clear log Enhancement

### ISSUE THREAD

**Issue by FastJack-MD** [MegaMek/mekhq#874]
I like to clear the logs of retired/MIA/KIA personnel to ease the file size of my campaigns. Can we get either one or both of the following?

- Clear Log when right-clicking on the personnel

- A parameter in Campaign options that will auto-clear the logs when a person is removed from active status

**Comment by sixlettervariables** [comment]
Out of curiosity, how large is the campaign file? And if possible, could you upload it here so we could test what savings a feature could provide?

**Comment by pheonixstorm** [comment]
Another item I have on my TODO list.

As for the size of the campaign file... the logs are a small part of it. The majority of what bloats the size of the campaign file are going to be units, parts, number of personnel, and campaign data (contracts and scenarios).

**Comment by MattDroz** [comment]
Yeah, I know. ;)

Still, every spare byte helps the load...

**Comment by sixlettervariables** [comment]
So we can get a baseline, how long does it take to load one of your campaigns?

**Comment by MattDroz** [comment]
With all the logs? About 45 seconds. It's not bad, but if I'm playing too long, or trying to do too much in one session, it can start to hang and I have to kill it Task Manager to bring it back up. Honestly, I know this is way less of a deal than the Scenario logs, but I thought I'd put it out there.

**Comment by sixlettervariables** [comment]
Ok, and the hangs are on campaign save? Load? Or just when using MHQ?

**Comment by MattDroz** [comment]
Using MHQ.

**Comment by repligator** [comment]
Implemented recently by https://github.com/MegaMek/mekhq/pull/4468 . Closing.
