### ISSUE TITLE
Dating vs Married

### ISSUE THREAD

**Issue by MattDroz** [MegaMek/mekhq#878]
Can we get a relation connection (can still use Spouse tag) that writes the logEntry as the couple is dating instead of married?

**Comment by rjhancock** [comment]
I think this would be beyond the scope of MekHQ as that can be a note in their file for role playing and has no other bearing on campaigns.

**Comment by neoancient** [comment]
Exactly as @rjhancock said. Courtship rituals vary considerably across human cultures, and in a futuristic science fiction setting could be anything. It is impossible for MekHQ to model all the possibilities and there is no need for it to model any of them.
