### ISSUE TITLE
Personnel Market not working

### ISSUE THREAD

**Issue by MattDroz** [MegaMek/mekhq#879]
When going to the Personnel Market in v45, the dropdown is null. 
![personnel market dropdown](https://user-images.githubusercontent.com/32368272/44303207-9b937c00-a308-11e8-87ca-2a25ef0c6a35.PNG)

Also, when looking in the Prereqs XML and the Campaign file, I notice that the <personnelMarketType> option is now <personnelMarketName>
![image](https://user-images.githubusercontent.com/32368272/44303216-d2699200-a308-11e8-9e89-d74eed56e060.png)

**Comment by neoancient** [comment]
Duplicate of #842
