### ISSUE TITLE
Bug: Interstellar Map tab - Current location null

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/mekhq#88]
Noticed this when moving to a new planet for a contract. About to jump from Ryde.
It shows:
Current Location
null (Lyran Commonwealth)
In transit to Kobe *snip*

There are no errors in the log so I am thinking its a value pulled from somewhere. If it shows this on the next planet I jump to I will update this to reflect it.
![nullplanet](https://cloud.githubusercontent.com/assets/1787879/15626141/c25399e6-248a-11e6-84b1-f4d5c51f6d5b.png)

**Comment by pheonixstorm** [comment]
Yep, same result for the next planet - Alexandria (LC) shows the same null for current location. Still no errors in the log
[nullLocation.txt](https://github.com/MegaMek/mekhq/files/287627/nullLocation.txt)

**Comment by Akjosch** [comment]
Should be fixed in next daily and release build.
