### ISSUE TITLE
Recruitment Type Options Disappear From Personnel Market

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/mekhq#880]
### Environment
> Starting MegaMek v0.44.0 ...
> 	Compiled on Sun Jun 24 17:02:01 CDT 2018
> 	Today is Tue Aug 07 15:05:46 CDT 2018
> 	Java vendor Oracle Corporation
> 	Java version 1.8.0_171
> 	Platform Windows 10 10.0 (amd64)
> 	Total memory available to MegaMek: 1,005,056 kB

### Description
The user from Casual_joker's Twitch and Discord channel stated that he set the toggle to make a paid recruitment roll next week for $100,000 and then accepted a contract and began transit to the planet.  After a few weeks into the contract he realized he still needed a pilot but, now the two options for the recruitment roll are gone.  I could not reproduce this with my campaign in MekHQ 0.45.0 so, I have no idea what is going on.

![image](https://user-images.githubusercontent.com/16950832/44311065-427a2580-a3a6-11e8-91d2-bee83bc610ec.png)

### Files
[RecruitmentOptions.zip](https://github.com/MegaMek/mekhq/files/2300098/RecruitmentOptions.zip)

**Comment by BLOODWOLF333** [comment]
Ok, I'm going to load his campaign then since I cant duplicate it but, he was saying it wasn't turning the paid recruitment off once it became disabled like it was still charging him 100k every week.  I'll see if I can reproduce with his campaign.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/44311011-8ae51380-a3a5-11e8-9a91-d7a70c04ab40.png)

Yeah in his cpnx it is still charging him 100k a week and I cant shut it off. That is bad.

**Comment by neoancient** [comment]
Ok, now I understand the issue. Yes, that's a bug.
