### ISSUE TITLE
Landing Dropship destroys a mech 6 hexes away submerged in depth 3 water

### ISSUE THREAD

**Issue by Mekslayer** [MegaMek/mekhq#885]
As the title says, it would seem ridiculous that I had a mech destroyed by a landing DS while my mech was in depth 3 water. If in fact that were the real case the DS would need to vaporize and ocean of water that I was surrounded by.  It would seem that this is a bug that defies logic, but I would have to leave it to the Devs to decide what is the right way to handle this situation.

**Comment by HammerGS** [comment]
Please reopen on the Megamek Tracker.
