### ISSUE TITLE
AtB "You have not met the deployment levels required by contract" but mission is not started yet

### ISSUE THREAD

**Issue by giorgiga** [MegaMek/mekhq#886]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
Running current git master.

### Description
When hitting "Advance Day" right after accepting a contract, I get the "You have not met the deployment levels required by contract", but the contract has not started yet.

<img width="1250" alt="bug" src="https://user-images.githubusercontent.com/471835/44399036-565c8d80-a546-11e8-8bd4-6274e0a72e10.png">

Assigning one of my lances to "Defend" (ie: meeting the requirements for the Riot Duty contract) does _not_ fix the popup – after confirming I want to advance day anyways, however, the popup doesn't show up no more.

**Comment by HammerGS** [comment]
Duplicate see #779
