### ISSUE TITLE
No Salvage List Appears

### ISSUE THREAD

**Issue by buzzzz2138** [MegaMek/mekhq#888]
### Environment
Version 0.44
Windows
Java 8 update 171

### Description
When processing the mission with resolve manual, doesn't allow any form of salvage.  Tried with a *.mul that had all units, and it would only do something with mechs attached to the campain and not with anything else.

### Files
[Mek HQ.zip](https://github.com/MegaMek/mekhq/files/2307009/Mek.HQ.zip)

**Comment by buzzzz2138** [comment]
Documentation probably needs to be included that the mul needs to be in recover tags instead of unit tags.

**Comment by sixlettervariables** [comment]
If there is a specific bug still blocking this let me know, but it sounds like documentation was the barrier here.

**Comment by buzzzz2138** [comment]
It's been awhile but yes, I believe it was documentation.  Thanks,    On Sunday, June 30, 2019, 05:26:18 PM CDT, Christopher Watford <notifications@github.com> wrote:  
 
 
If there is a specific bug still blocking this let me know, but it sounds like documentation was the barrier here.
