### ISSUE TITLE
AtB - NPE Setting Planetary Conditions

### ISSUE THREAD

**Issue by dericpage** [MegaMek/mekhq#89]
Happens on Monday when scenarios are generated.
[mekhqlog.zip](https://github.com/MegaMek/mekhq/files/287732/mekhqlog.zip)

**Comment by dericpage** [comment]
This appears to happen when the planet the unit is on is not fully defined.  We're currently located on Carmen, which only has a name, coordinates and faction data.  Probably need to define some defaults for other planetary conditions for AtB to pull rather than defaulting to nulls.

**Comment by Akjosch** [comment]
Yeah, likely my fault, what with the planets having all kinds of fields which are `null` actually returning `null` (for the benefit of being able to save those fields, among others). Given that the *are* already defaults set in the constructor, I'd suggest using them. Either explicit checks for `getPressure(...)` and `getGravity()` returning `null`, or simply ...

				atmosphere = Utilities.nonNull(p.getPressure(new DateTime(campaign.getCalendar())), atmosphere);
				gravity = Utilities.nonNull(p.getGravity().floatValue(), gravity);

**Comment by Akjosch** [comment]
By the way, pulling the info from the new branch you made *will* fuck up the current planetary history editor and the upcoming world editor, simply because there's no easy way to tell if a planet has 1.0 gravity because that's in the XML file or because it's the default value. The defaults *have* to stay `null` and every piece of code pulling them needs to be able to recognise and deal with those "unknown" values according to whatever the need is (which can be different for different parts of MekHQ).

**Comment by pheonixstorm** [comment]
How was it handled BEFORE the changes to the planet code/xml?

**Comment by Akjosch** [comment]
For the specific field in question: It was a non-nullable (`int` instead of `Integer`) field, defaulted to 1, and couldn't change due to catastrophes, terraforming or similar activities.

**Comment by dericpage** [comment]
@Akjosch 
Yeah, I pushed before I saw your suggestion.  Working on a different push.  However

`p.getGravity().floatValue()`

Will also throw an NPE if p.getGravity() is null.  I'm debating between

`Float.valueOf(String.valueOf(p.getGravity())`

and

`p.getGravity() == null ? null : p.getGravity().floatValue()`

**Comment by dericpage** [comment]
Then I came to my senses and decided on
`Utilities.nonNull(p.getGravity(), gravity).floatValue();`

**Comment by Akjosch** [comment]
There are a few cases where `Planet` has helper methods which are meant to be used for display and calculations and are guaranteed to return a default value if none is defined. Here's one example:

    public String getGravityText() {
        return null != gravity ? gravity.toString() + "g" : "unknown"; //$NON-NLS-1$
    }

The upside of those is that the underlying data isn't changed, you just ask the class for some *useful* data and don't mind if it's a default. If you foresee the gravity being used more often, here is another suggestion to add to `Planet`:

    /** @return the gravity in multiplies of standard gravities (9.80665 m/s²), or 1.0 if none if defined */
    public float getEarthGravity() {
        return (null != gravity) ? gravity.floatValue() : 1.0f;
    }

**Comment by dericpage** [comment]
Created pull request:
https://github.com/MegaMek/mekhq/pull/90
