### ISSUE TITLE
Date format issues in campaign file

### ISSUE THREAD

**Issue by giorgiga** [MegaMek/mekhq#891]
_Please note this ticket is about the date format in `.cpnx` files, **not** about what date formats are used in the GUI._

### Environment
Current github master.

### Description
Apparently, the time portion of all dates in `.cpnx` files is serialized as `12:00:00`, despite the times really being midnight.

This is due to the use of `hh:mm:ss` instead of `HH:mm:ss` in `SimpleDateFormat` specifications (`HH` is the hour from 0 to 23, while `hh` is 1-12 and meant to be used with am/pm).

Updating the date formats to use `HH`, however, is _not_ feasible because it's not backwards-compatible with existing campaign files (ie: `hh:mm:ss` reads `12:00:00` as midnight, `HH:mm:ss` reads the same string as midday).

Apparently, the time portion of the dates in `.cpnx` files is actually meaningless and can be altogether discarded: changing the date format from `yyyy-MM-dd hh:mm:ss` to just `yyyy-MM-dd` seems to do the trick in a backwards-compatible way (at least, if `SimpleDateFormat` is used everywhere).

These are most probably all the points this issue will impact:
```
$ grep -nr '"yyyy-MM-dd hh:mm:ss"' src | cat -n
     1	src/mekhq/campaign/LogEntry.java:44:        return new SimpleDateFormat("yyyy-MM-dd hh:mm:ss"); //$NON-NLS-1$
     2	src/mekhq/campaign/mission/Contract.java:556:        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
     3	src/mekhq/campaign/mission/Contract.java:590:        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
     4	src/mekhq/campaign/mission/Scenario.java:269:        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
     5	src/mekhq/campaign/mission/Scenario.java:328:        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
     6	src/mekhq/campaign/Kill.java:122:					SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
     7	src/mekhq/campaign/Kill.java:149:		SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
     8	src/mekhq/campaign/finances/Loan.java:399:        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
     9	src/mekhq/campaign/finances/Loan.java:433:                SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    10	src/mekhq/campaign/finances/Finances.java:206:            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    11	src/mekhq/campaign/finances/Finances.java:226:                SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    12	src/mekhq/campaign/finances/Transaction.java:233:		SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    13	src/mekhq/campaign/finances/Transaction.java:254:				SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    14	src/mekhq/campaign/personnel/AwardsFactory.java:54:    private static final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    15	src/mekhq/campaign/personnel/Person.java:1262:        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    16	src/mekhq/campaign/personnel/Person.java:1605:                    SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    17	src/mekhq/campaign/personnel/Person.java:1670:                    SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    18	src/mekhq/campaign/personnel/Person.java:1674:                    SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    19	src/mekhq/campaign/personnel/Person.java:1678:                    SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    20	src/mekhq/campaign/personnel/Award.java:75:    private static final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    21	src/mekhq/campaign/Campaign.java:3460:        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    22	src/mekhq/campaign/Campaign.java:5162:                            "yyyy-MM-dd hh:mm:ss");
```

### Related

#259 is a related issue, about allowing users to customise the date format used in the GUI

#260 is PR dating back to 2016 that was meant to address #259 and also unify the formats used in .cpnx files. The PR has been closed without merging it, due to excessive conflicts.

PS: _I suggest closing #259 and creating a new ticket about date formats in the GUI: the comments in #259 are a bit dispersive (some are off-topic and some actually discuss PR #260)._

**Comment by sixlettervariables** [comment]
Notes:
- `yyyy-MM-dd` does not actually resolve the issue, instead creating another one w.r.t. the time coming over as midnight AND a local time zone being applied.
- Per @giorgiga `java.time.LocalDate` may be more appropriate.
