### ISSUE TITLE
Techs not refreshing when advancing a day

### ISSUE THREAD

**Issue by 69chrisd69123** [MegaMek/mekhq#896]
I just downloaded the new version and began a new campaign. Haven't played the game in about 3 years. Anyways I just completed my first scenario and I got my stuff for the repairs paid for. When the techs have used up most of their allotted time. I click on advance day and nothing happens? 

I have attached the save game the 4 custom mechs and the mekhq log

### Environment
mekhq.0.45.0 windows
Windows 10
Current version
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2312403/mekhqlog.txt)
[Hawk's Ronin30480612.zip](https://github.com/MegaMek/mekhq/files/2312406/Hawk.s.Ronin30480612.zip)
[My Campaign.zip](https://github.com/MegaMek/mekhq/files/2312409/My.Campaign.zip)

### Description
Describe the issue and provide screenshots ingame if able.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the campaign file if applicable.
(Delete the above lines)

### Files
Provide the .cpnx campaign file that this issue occurs in.
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the mekhqlog.txt file for any NPE's or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual mekhqlog.txt file
(Delete the above lines)

**Comment by HammerGS** [comment]
NPE in the log.

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.campaign.Campaign.processNewDayATBScenarios(Campaign.java:2314)
	at mekhq.campaign.Campaign.processNewDayATB(Campaign.java:2503)
	at mekhq.campaign.Campaign.newDay(Campaign.java:2698)
	at mekhq.gui.CampaignGUI.advanceDay(CampaignGUI.java:1446)
	at mekhq.gui.CampaignGUI.access$2500(CampaignGUI.java:165)
	at mekhq.gui.CampaignGUI$52.actionPerformed(CampaignGUI.java:1264)
```

**Comment by 69chrisd69123** [comment]
Sorry I didn't mean to close the issue hopefully it's still open?

**Comment by HammerGS** [comment]
It's open all good

**Comment by 69chrisd69123** [comment]
How do I resolve this issue so I can get back to the game without having to start a new campaign

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by giorgiga** [comment]
@69chrisd69123,  this workaround fixed it for me:

1. enable GM Mode
2. go to the interstellar map
3. right-click on any planet but _Clayborne II_ and "GM Mode" -> "Move to selected planet"
4. repeat the process and move back to _Clayborne II_

**Comment by giorgiga** [comment]
Before I forget - the issue (visible in the posted .cpnx file) seems to be that `CurrentLocation` somehow ended up having an empty `JumpPath`.

Changing `CurrentLocation.generateInstanceFromXML(Node, Campaign)` to only output non-empty paths would allow the issue not to be persisted, but I wasn't able to determine what had caused it in the first place.

**Comment by 69chrisd69123** [comment]
I am not worried about it anymore I went to 0.44.0 and started a new campaign

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sixlettervariables** [comment]
We've not seen something like this in a long time, please reopen this issue if it occurs again on a current MHQ release.
