### ISSUE TITLE
Can't Assign patients to doctors

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/mekhq#91]
I have one doctor with 4 medics but can't assign my wounded to said Doctor.

Tried to hire a second doctor with the same result. Fired the medical staff and rehired the lot, advanced a day still the same. No errors show up in the log either.

**Comment by Akjosch** [comment]
Well, we'll need a campaign file, I think. At least I couldn't reproduce it.

**Comment by pheonixstorm** [comment]
Ok, will go kill some more infantry with a fresh campaign and post it

**Comment by pheonixstorm** [comment]
[doctorbug.zip](https://github.com/MegaMek/mekhq/files/288117/doctorbug.zip)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/288118/mekhqlog.txt)

Fresh campaign, this time w/o advanced medical and still got it to come up. Still no errors in the log.

**Comment by Akjosch** [comment]
1. Go the the Infirmary
2. Mark (left-click) a doctor.
3. Mark a potential patient.
4. Left-click "Assign" until they are all assigned.
5. In four days, everybody is ready to be thrown back into the grinder (no clue on how realistic or close to the official wound recovery rules that is).

Well, works for me. To be fair, I don't use this tab often, so I couldn't tell if something in the way it works changed. But it *does* work. Weird.

**Comment by pheonixstorm** [comment]
The assign button is grayed out though and clicking it does nothing

**Comment by pheonixstorm** [comment]
I stopped being able to do anything with doctors after the changes made in #79

**Comment by pheonixstorm** [comment]
I did find something odd but unrelated in the campaign file. Before the person endtag there is a <extraData/> tag that doesn't belong. Looks like something from the admin xp fix.

**Comment by Akjosch** [comment]
The `<extraData/>` part is simply a generic marker meaning "no extra data for this person". Given that patients don't reference or use that data part, it has no bearing on the infirmary either.

**Comment by Akjosch** [comment]
Playing a bit with the Infirmary, I can see two things worth fixing:

* "Assigned Patients" scrolls horizontally while "Unassigned Patients" scrolls vertically.
* Changing the selected doctor also changes the selection of the unassigned patients.

However, I think I found the problem (though it's strange that it doesn't hit me personally): the `getSelectedUnassignedPatients()` method pulls from the wrong model (the "assigned patients" one). Bundling the fixes for all of this into a PR right now.
