### ISSUE TITLE
Feature Request: Trailers

### ISSUE THREAD

**Issue by Necrofox91** [MegaMek/mekhq#912]
Okay, I've been scratching my head about how to get trailers/hitching to work. After some searches it seems that it isn't possible to do so in the current game. And I can't find any issue about it (open or closed) so hoping I didn't miss something or other, I'm formally requesting my fictitious supply chain and my artillery work as intended. 

(Please tell me there isn't something my google-fu missed that neoancient has to school me about, I mean I didn't find anything saying it wasn't gonna be implemented, just an old conversation on the bg.battletech forums saying it wasn't added yet)

**Comment by HammerGS** [comment]
They are currently not supported. But is on list for this development cycle. 

But no ETA.

**Comment by neoancient** [comment]
Leave it open. We'll close it when the feature is completed and merged in.

Sorry if I sometimes come across as stern or impatient. Mostly I'm trying to keep the issue trackers from getting too out of hand and I don't use a lot of words.

**Comment by neoancient** [comment]
I left my previous comment while on my phone and didn't see that this in on the MekHQ tracker. It needs to be on the MegaMek tracker.

**Comment by Necrofox91** [comment]
Err... okay but wouldn't the hitching which vehicle to which have to be handled in 'HQ?? Especially since this comes from my logistic chain that hasn't seen any combat at all yet? I mean I suppose that for artillery it would need a megamek counterpart but I haven't managed to find any in the unit market yet. Basically what I'm trying to say is that this is all about MekHQ, on my side at least.

**Comment by HammerGS** [comment]
Using trailers is a function of MegaMek.  Basically if it involves making a unit do something in Game, i.e. towing something, then it goes into Megamek.

Assigning crew, repairing, refitting, those would be MekHQ.  

So a unit has to exist in Megamek for MekHQ to do anything with it.

**Comment by Necrofox91** [comment]
Okay. Sorry, had trouble wrapping my head around it a this hour. Gonna go open there then. Have to remember to leave proper posting for when my head is working properly.

**Comment by Necrofox91** [comment]
Done shouldn't have done it at this hour and all rambling like always.
Issue 1125 on the megamek tracker for those who care.
