### ISSUE TITLE
Hire Full Compliment Regularly Hires Bondsmen

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/mekhq#917]
### Environment
MekHQ 0.45.0
Windows 8.1x64
Java 1.8

### Description
![image](https://user-images.githubusercontent.com/16950832/45127460-fff27000-b13d-11e8-900b-801ea8724324.png)

The cpnx has a bunch of empty units already added.  Right click > hire full compliment and HQ will sometimes hire bondsmen ranked personnel to man the units.  Bondsman is not a rank I am using (Custom), the person's status are on Active and clicking Change Rank System > Use Campaign Rank System does not change it.  I can change their ranks normally.  Just weird behavior.

### Files
[HireFullCompliment.zip](https://github.com/MegaMek/mekhq/files/2354961/HireFullCompliment.zip)
NPE's in log are from me messing with the awards feature.

**Comment by BLOODWOLF333** [comment]
Noticed it always seem to be for space units.
![image](https://user-images.githubusercontent.com/16950832/45127699-311f7000-b13f-11e8-8627-57eb71fa6193.png)

**Comment by neoancient** [comment]
The E0 rank name is missing for all professions except MechWarrior. When a rank is missing, MekHQ drops to the next lower rank, and in this case ends up at -1, which is the value used for Bondsman. The E0 field should be filled in for all professions, either with "Recruit" or with "--MW" to redirect to the MechWarrior column.

MekHQ's handling of the situation is confusing, so I've posted a fix that stops at E0 and would show the rank as -, which should be easier to figure out.
