### ISSUE TITLE
Cannot configure bot, auto disconnects from megamek lobby

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#93]
Sometimes mekhq fails to configure the bot in the lobby screen and will auto disconnect you from the lobby after loading all units. The log file just says that it could not configure the bot. Reloading the campaign save and trying to start the scenario again works though.

[#battletech.zip](https://github.com/MegaMek/mekhq/files/288331/battletech.zip)

**Comment by Dylan-M** [comment]
Is this still valid?

**Comment by Dylan-M** [comment]
No response, closing as invalid unable to reproduce.

**Comment by Question2** [comment]
I had it happen once with 41.25 but that was a pretty rare occurence (once out of 10+ battles). Log file had no errors and restarting mekhq fixed the problem. Everytime i would go into the lobby, it would load the units, then automatically close itself with no error messages.

I cant reproduce it on demand either as restarting mekhq fixes it.
