### ISSUE TITLE
Recovery GUI extremely slow if recovering enough units to require substantial scrollling

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#931]
I've noticed this for a while, and checked with another player who has also seen it. When recovering a unit in MekHq, the gui for that action scrolls extremely slowly if the number of units is very large (2 companies or more, esp infantry). For very large actions (multi-battalion) it is an almost unusable scroll speed.

I'm not sure what kind of log to post for this one.

**Comment by sixlettervariables** [comment]
If you could provide a save game at this point that'll help us trace down the performance problem.
