### ISSUE TITLE
Cannot use Purchase Unit in 45.1

### ISSUE THREAD

**Issue by Shin-Ji** [MegaMek/mekhq#936]
### Environment
45.1, Win 7, Java 8 update 181

### Description
Anytime I try to open the Purchase Unit menu option, there is a long hang, and in the end, no units are displayed. This issue does not occur with 45.0 or earlier versions. Thank you all so much for what you do!
![javaw_2018-09-16_15-16-10](https://user-images.githubusercontent.com/43322437/45599998-aef73d00-b9c3-11e8-8f9d-59b46536c4ff.png)
![javaw_2018-09-16_15-18-01](https://user-images.githubusercontent.com/43322437/45600005-ba4a6880-b9c3-11e8-822f-e7a12065a573.png)
[Choosers of the Slain30430521.zip](https://github.com/MegaMek/mekhq/files/2386913/Choosers.of.the.Slain30430521.zip)
[Enforcer ENF Choosers.zip](https://github.com/MegaMek/mekhq/files/2386914/Enforcer.ENF.Choosers.zip)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2386915/mekhqlog.txt)

**Comment by BLOODWOLF333** [comment]
Are you patching over your old version of HQ with a new version?  (pasting the new release over the old release's folder?)

**Comment by Shin-Ji** [comment]
No - I installed it in a new folder.

**Comment by giorgiga** [comment]
I just downloaded a clean 0.45.1 and could not replicate the problem, @Shin-Ji 

Must be either a windows-only issue (unlikely) or your installation (?)

Could you try and re-download another 0.45.1 (or extract to a different folder if you still have the zip) and see if you still have issues?

**Comment by Shin-Ji** [comment]
I did a clean reinstall, then copied over my customs, portraits, and campaign files, and it works fine now. Sorry to bother - guess I must have overwritten something at some point.
