### ISSUE TITLE
Planet xml in planet folder not updating the Interstellar Map

### ISSUE THREAD

**Issue by mchapman1970** [MegaMek/mekhq#939]
First of all I don't do bug reports I looked at 8 pages of it and could not find one that match my issue.
Second  It maybe just me since I have not seen anyone complain about it after I mentioned it in slack
Third  If this has been reported I am sorry
MekHQ  0.45.0  and 0.45.1
Windows 10
Java 8 update 181

When updating from 0.44.0 to 0.45.0 I transferred all the appropriate files like always but when I started up the game the map was wrong.
0.44.0 map
![image](https://user-images.githubusercontent.com/22855199/45910417-69c17980-bdce-11e8-922c-e46660b8318c.png)
![image](https://user-images.githubusercontent.com/22855199/45910419-7940c280-bdce-11e8-8745-070cf0ed05a1.png)

0.45.0 map
![image](https://user-images.githubusercontent.com/22855199/45910426-95446400-bdce-11e8-98af-df02bddbc1c2.png)
![image](https://user-images.githubusercontent.com/22855199/45910429-a1302600-bdce-11e8-8f33-ae6623fce610.png)

I have my faction transfer over I can make changes to the map om 0.45.0
![image](https://user-images.githubusercontent.com/22855199/45910451-cb81e380-bdce-11e8-8cf8-e633e38b81e8.png)
but when I put into the xml file in the folder 
![image](https://user-images.githubusercontent.com/22855199/45910468-f8ce9180-bdce-11e8-9b7c-3c469519213c.png)
it still does not change when selecting another campaign.

[customs.zip](https://github.com/MegaMek/mekhq/files/2407319/customs.zip)

[4th Davion Assault30300826.zip](https://github.com/MegaMek/mekhq/files/2407321/4th.Davion.Assault30300826.zip)

[factions.zip](https://github.com/MegaMek/mekhq/files/2407323/factions.zip)

[ranks.zip](https://github.com/MegaMek/mekhq/files/2407324/ranks.zip)

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2407327/mekhqlog.txt)

hopefully I did this correctly

**Comment by mchapman1970** [comment]
[War3030planets.zip](https://github.com/MegaMek/mekhq/files/2601386/War3030planets.zip)

**Comment by Windchild292** [comment]
This is outdated because of the planets rework, and I am thus closing it.
