### ISSUE TITLE
MekHq deploying support vees immobilized 

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#943]
Not sure whats causing this. I was messing around with age of war atb, just to see if I could, year 2400. Some of my support vees are deploying already immobile, including one mission where the bot had the same kind of units and was not immobile. I've tried messing with the options but that did not help.

[MMLogImob.txt](https://github.com/MegaMek/mekhq/files/2412438/MMLogImob.txt)

[SupportImobandOffboardUnload.sav.gz](https://github.com/MegaMek/mekhq/files/2412440/SupportImobandOffboardUnload.sav.gz)

**Comment by VampireSeraphin** [comment]
[AtBTest2.zip](https://github.com/MegaMek/mekhq/files/2413351/AtBTest2.zip)

[AtBNoMove.sav.gz](https://github.com/MegaMek/mekhq/files/2413353/AtBNoMove.sav.gz)

[megameklog.txt](https://github.com/MegaMek/mekhq/files/2413355/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2413356/mekhqlog.txt)


I did some more testing, and I think this is related to the strip/restore feature. What I noticed was that some equipment was not completely restored, fire control in this case. I had to manually edit damage for these units (estev AA). My best guess is that some other factor is not being correctly repaired by the restore function, resulting in the tanks having no ability to move.

**Comment by neoancient** [comment]
The tanks are already immobile in the saved game and there is no way to determine how they got there with the files provided.

**Comment by neoancient** [comment]
Closed due to lack of needed files, but they were provided while I was trying to see if the little information initially supplied would be enough, so reopened.
