### ISSUE TITLE
GM mode Restore unit draws armor and ammunition from warehouse, but not parts. 

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#944]
Related to the newly added strip unit option (which is awesome), I've noticed that when I go to restore units after using strip, MekHq uses the armor and ammo just added to the warehouse for the restore. In GM mode it should not use any parts for a restore and/or should generate a popup asking if it should use parts from the warehouse.

**Comment by sixlettervariables** [comment]
Seems like the restore feature needs to clone those parts instead.

**Comment by sixlettervariables** [comment]
I've got a PR #961 which fixes this, but it really really uglifies the code. I'm torn on whether or not to land it given how much more complicated it makes the whole parts tree.
