### ISSUE TITLE
Atb Civilian units do not respect the time line

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#945]
[AtBNoTimelineRespect.zip](https://github.com/MegaMek/mekhq/files/2412608/AtBNoTimelineRespect.zip)

Atb will generate civilian units that have not yet been invented. This applies to mechs, and seemingly turrets. (note the pulse laser turret.)

AtB will also award reward units without regard to intro date. I don't have a save for this, but did notice it.

**Comment by Windchild292** [comment]
Subsumed by #1416
