### ISSUE TITLE
Some personnel (techs and admins) no longer able to be right clicked.

### ISSUE THREAD

**Issue by Apocal43** [MegaMek/mekhq#946]
MekHQ 0.44.0
Windows 10
Java 1.8.0_181

Unable to right-click certain personnel, techs and administrators. Mechwarriors still right-clickable. I can't imagine what could have caused this issue, so I have included the last test campaign save when all personnel could be right-clicked and the very next save when they could not.

[apocal bugged campaigns.zip](https://github.com/MegaMek/mekhq/files/2413034/apocal.bugged.campaigns.zip)

Also included player-modified mechs (in "Customs") along with player-modified unit sprite (GRF-1ND2 in
"mechs") and mechset file. Just in case those have something to do with the issue. I don't believe so as the issue post-dates those modifications by approximately three weeks.

Even if an actual fix isn't forthcoming a workaround of some sort would be nice.

**Comment by giorgiga** [comment]
Exception from OP-provided log file:
```
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at mekhq.campaign.personnel.Rank.getRankLevels(Rank.java:134)
	at mekhq.gui.adapter.PersonnelTableMouseAdapter.maybeShowPopup(PersonnelTableMouseAdapter.java:1158)
	at mekhq.gui.adapter.PersonnelTableMouseAdapter.mouseReleased(PersonnelTableMouseAdapter.java:1095)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
```

**Comment by HammerGS** [comment]
I thought I saw something about ranks, as bug repot/fix recently.

**Comment by neoancient** [comment]
The problem has nothing to do with the E0 MW rank. It's a blank in the E1 tech rank:
```				<rank>
					<rankNames>Child,-,-,-,-,</rankNames>
					<officer>false</officer>
					<payMultiplier>1.0</payMultiplier>
				</rank> <!-- E1 -->
```

When the campaign is loaded the rank name array is created using `split(",")`, which does omits any trailing empty String and returns an array of four values instead of five. The reason why changing the E0 MW rank resolved it is because when the campaign options were saved the array was reinitialized with a length of five. Just loading the campaign options and saving it would have had the same result.

**Comment by giorgiga** [comment]
Confirmed: the E1 blank causes the issue.

Going to the "Rank System" options page and hitting "confirm" (without need to fill-up the E0 MW rank) fixes the issue, as "Profession Out of Bounds" appears in place of the blank; it is however quite possible to blank out any of the rightmost ranks and hit "confirm" to reproduce the issue.
