### ISSUE TITLE
Infinite reload in repair bay

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#957]
![image](https://user-images.githubusercontent.com/19868605/46325293-9727d780-c5c5-11e8-878c-4d562a461c57.png)

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2436226/mekhqlog.txt)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/2436227/megameklog.txt)

[Infinite reloads.zip](https://github.com/MegaMek/mekhq/files/2436230/Infinite.reloads.zip)

Seen here, this highlander is being reloaded infinite times. This has caused MekHq to hang and crash repeatedly while using the mass repair tool. Attempting to reload its lrm rolls for the action but does not remove it from the que.

**Comment by VampireSeraphin** [comment]
An additional observation. This seems to only effect units refit from a different config.

**Comment by sixlettervariables** [comment]
Looks like the refit messed up the configuration of ammo bin to mount location:
```
09:13:06,491 WARN [mekhq.campaign.parts.equipment.AmmoBin] {AWT-EventQueue-0} 
CASE is not valid equipment for LRM 20 Ammo Bin to restock ammo on unit Highlander HGN-732b
```

**Comment by sixlettervariables** [comment]
Ok looks like there is an extra ammo bin without any ammo:
```
Equipment Parts:
 2: SRM 6 Left Arm SRM 6 
 4: Gauss Rifle Right Arm Gauss Rifle 
 5: Jump Jet Left Torso Jump Jet 
 6: LRM 20 Left Torso LRM 20 
 8: SRM 6 Ammo Bin Left Torso SRM 6 Ammo 
 10: LRM 20 Ammo Bin Left Torso LRM 20 Ammo 
 11: LRM 20 Ammo Bin Left Torso CASE  (Missing)
 12: Jump Jet Right Torso Jump Jet 
 14: Medium Laser Right Torso Medium Laser 
 15: Medium Laser Right Torso Medium Laser 
 16: Gauss Rifle Ammo [IS] Bin Right Torso Gauss Rifle Ammo [IS] 
 17: Gauss Rifle Ammo [IS] Bin Right Torso Gauss Rifle Ammo [IS] 
 19: Jump Jet Center Torso Jump Jet 
 7: Artemis IV FCS Left Torso Artemis IV FCS 
 13: Medium Laser Right Torso Medium Laser 
 9: LRM 20 Artemis-capable Ammo Bin Left Torso LRM 20 Artemis-capable Ammo 
```

**Comment by sixlettervariables** [comment]
Likely a bad refit from the old refit code. If you need me to try and manually fix the unit in your CPNX let me know.
