### ISSUE TITLE
Damaged units not appearing in repair bay

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#958]
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2440136/mekhqlog.txt)

[NoRepairs.zip](https://github.com/MegaMek/mekhq/files/2440138/NoRepairs.zip)

I have several units which have suffered damage from maint checks and not appeared in the repair bay. Curiously, if I GM edit some damage onto another unit, all damaged units appear in the repair bay.

**Comment by NickAragua** [comment]
The only damaged units I saw in that save were the Highlander and the Rifleman. The Rifleman does not appear in the repair bay because it is mothballed. What other units in that campaign were damaged?

**Comment by VampireSeraphin** [comment]
I mis-typed. I had this bug occur several times, figured out how to fix the units, did so, but attached a save with only one damaged unit when the bug recurred. 

Gm editing the damage on the unit not appearing in the repair bay also causes it to reappear.

**Comment by sixlettervariables** [comment]
We couldn't repro this with the CPNX given, if you encounter this again let me know and I'll reopen the issue.
