### ISSUE TITLE
Acquired Units can never be paid for

### ISSUE THREAD

**Issue by swang300** [MegaMek/mekhq#967]
In Campaign:1997, the order of operations for the if statement results in acquiring a unit to always return false from "canPayFor".   Acquiring for a part works correctly (because the && is attached to the second part of the ||.

Pulling the actual canPayFor check into a separate check from the "is the options set up so I have to worry about this" check makes it more readable.  I will submit a pull request.

**Comment by swang300** [comment]
#968 Pull request created

**Comment by sixlettervariables** [comment]
Fixed by #968
