### ISSUE TITLE
Infinite Repair and Shorthanded.

### ISSUE THREAD

**Issue by pjfarland** [MegaMek/mekhq#976]
45.1 Environment
Windows 10
Java version 1.8.0_171

Occasionally repair times won't advance and a part will never repair without a GM 'Complete Task' intervention. Also, occasionally the techs end up short handed, but this could be fixed by releasing all the Astechs, then rehiring them. Now with Astechs that are part of the unit that fix no longer works, though hiring a few extra (but not just one), does fix it. I have more than enough Astechs in the unit as 'Bring All Tech Teams to Full Strength' does nothing, I have to manually add the Astechs for the fix. I think these problems might be related as the tech issue always seems to show up after the other though the 'non-advancing repair' doesn't always lead to it.

[megameklog.txt](https://github.com/MegaMek/mekhq/files/2572453/megameklog.txt)
[Inside Straight.zip](https://github.com/MegaMek/mekhq/files/2572464/Inside.Straight.zip)

**Comment by neoancient** [comment]
This is impossible to diagnose without a campaign file. I'm going to assume you intended to include it in the zip file with the custom units.

**Comment by pjfarland** [comment]
I hope that's the right one. Sorry it didn't attach.

[Inside Straight30401202.zip](https://github.com/MegaMek/mekhq/files/2586237/Inside.Straight30401202.zip)

**Comment by bczretribution** [comment]
I have also been having this issue.  Most repairs that overflow into the next day's work will not complete.  Here is a save that has several ongoing repairs that do not progress in case more data was needed.

[glitch.zip](https://github.com/MegaMek/mekhq/files/2631925/glitch.zip)

**Comment by sixlettervariables** [comment]
@pjfarland 
```
Could not load the following units: 
Maxim Heavy Hover Transport Assault
Karnov UR Transport RR
```

**Comment by sixlettervariables** [comment]
@bczretribution I was able to load your campaign and am looking at the bug now.

**Comment by sixlettervariables** [comment]
I'm not sure how you ended up in this situation, but I have a fix that will at least get you _out_ of the problem:
> Master Engineer John Vondracek attempts ... Not enough time, the remainder of the task on Talon TLN-5V - reserve refit **cannot be finished because there was no time left after maintenance tasks**.
The tech will be cleared from the task and it'll be available for another tech to complete.

**Comment by bczretribution** [comment]
This seems to tie into several interconnected repair issues.  Ill open a new ticket to explain and discuss
