### ISSUE TITLE
[0.45.1-git : Bug] sun.reflect.NativeMethodAccessorImpl.invoke0 Error

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#979]
### Environment
MekHQ 0.45.1-git

### Description
sun.reflect.NativeMethodAccessorImpl.invoke0 error when 'advance day'. Load save game and press 'advance day'. Also noticed ONCE that instead of sun.reflect.NativeMethodAccessorImpl.invoke0 error, some mothballing error was shown instead.

Save game and log attached.

Also please provide instruction on how to 'save' my campaign file too. Thanks.

### Files
[Customs - SirMegaV - Mechfiles.zip](https://github.com/MegaMek/mekhq/files/2575392/Customs.-.SirMegaV.-.Mechfiles.zip)
[sun.reflect.NativeMethodAccessorImpl.invoke0 - Log.txt](https://github.com/MegaMek/mekhq/files/2575393/sun.reflect.NativeMethodAccessorImpl.invoke0.-.Log.txt)
[sun.reflect.NativeMethodAccessorImpl.invoke0.zip](https://github.com/MegaMek/mekhq/files/2575394/sun.reflect.NativeMethodAccessorImpl.invoke0.zip)

**Comment by neoancient** [comment]
The InvocationTargetException is a wrapper around an exception that was thrown during event processing. The actual cause was this:
Caused by: java.lang.NullPointerException
	at mekhq.gui.DailyReportLogPanel.appendLog(DailyReportLogPanel.java:115)
	at mekhq.gui.CampaignGUI.refreshReport(CampaignGUI.java:3062)
	at mekhq.gui.CampaignGUI.handle(CampaignGUI.java:3122)

I know I've seen this before but I don't remember any details.

**Comment by neoancient** [comment]
I can't reproduce the reported issue. I have found the cause for the exception involving mothballing, which is related to the way aerospace vessels handle tech requirements differently.

**Comment by SirMegaV** [comment]
I’ll try again and update later. Thanks.

**Comment by SirMegaV** [comment]
Loaded the campaign save from my PC... this time after advancing a day, I receive NPE at mekhq.campaign.personnel.Person.isMothballing(Person.java:3019) instead. Attaching log.

[sun.reflect.NativeMethodAccessorImpl.invoke0 - Log 2.txt](https://github.com/MegaMek/mekhq/files/2579306/sun.reflect.NativeMethodAccessorImpl.invoke0.-.Log.2.txt)

Downloading and testing the campaign file that I attached here. Strange.. I'm not getting the NPE at mekhq.gui.DailyReportLogPanel.appendLog(DailyReportLogPanel.java:115). Instead, I'm getting the same earlier, NPE at mekhq.campaign.personnel.Person.isMothballing(Person.java:3019). Not sure why you are not getting any NPE.

**Comment by SirMegaV** [comment]
Tested by removing the mothballing dropship. No error. Error probably caused by mothballing dropships which you've fixed.
