### ISSUE TITLE
Advancing Day hangs and errors in custom designs

### ISSUE THREAD

**Issue by monbvol** [MegaMek/mekhq#98]
Whenever an AtB battle is generated MekHQ hangs for extended periods, often to the point of crashing.  Advancing Day to a new month will also cause MekHQ to hang.

Also noticed that one of my custom designs(PHX-1M Phoenix Hawk) is being given a full ton of machine gun ammo even though it is only supposed to have half a ton.  Could be more but I haven't noticed yet because I haven't used them yet in my campaign.

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/292347/mekhqlog.txt)
[1st Berzerkergang.zip](https://github.com/MegaMek/mekhq/files/292348/1st.Berzerkergang.zip)
[Monbvol.zip](https://github.com/MegaMek/mekhq/files/292349/Monbvol.zip)

**Comment by GustavKuriga** [comment]
I would also point out that MekHQ will often refuse to generate the
unit marketplace as well as contracts.

**Comment by Kurios** [comment]
I think I've been noticing this without the custom designs as well. Haven't sat down to figure out why though yet.

**Comment by Akjosch** [comment]
The exceptions in the log refer to already fixed bugs (planetary conditions settings for planets with no defined planetary conditions and forcing a refresh of forces in a scenario from @Kurios ). So far, I can't really notice any slowdown either. Can you try it out in the next daily release (the current one doesn't have the forces fix yet)?

**Comment by Kurios** [comment]
Yep! As soon as I get ahold of the forces fix, I'll compile up a copy of it to test.

**Comment by Dylan-M** [comment]
What's the status of this report?

**Comment by Dylan-M** [comment]
No response. Closing as invalid.
