### ISSUE TITLE
[0.45.2 : Bug] Load campaign save cannot load Vulture (Standard) and Monsoon Battleship (Standard)

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#983]
### Environment
0.45.2

### Description
Cannot load Vulture (Standard) and Monsoon Battleship (Standard) during load campaign. These units were previously present, and the name is the same as in MUL. 

![image](https://user-images.githubusercontent.com/17064665/48685835-7b1eda80-ebf3-11e8-87ce-ab27d8b5ff91.png)

**Comment by HammerGS** [comment]
Did you update the name_changes.txt file for the new release.  It should have caught the difference.

If note the Monsoon is now called - Monsoon Battleship (2368)
The Vulture is - Vulture (2312)

**Comment by SirMegaV** [comment]
I didn’t update anything, just install the latest release and copy over
user data. I’ll try to change the name in the campaign file later.

**Comment by SirMegaV** [comment]
Changed the name in the game save file and it worked. Also sorry, didn't notice that name_changes.txt exist for this purpose. Closing this ticket now.
