### ISSUE TITLE
[AtB] Breakthrough (Defender) Bots does not flee

### ISSUE THREAD

**Issue by luiges90** [MegaMek/mekhq#987]
### Environment
Starting MegaMek v0.45.2 ...
	Compiled on Sun Nov 18 15:27:28 CST 2018
	Today is Sun Nov 25 22:11:29 CST 2018
	Java vendor Oracle Corporation
	Java version 1.8.0_171
	Platform Windows 10 10.0 (x86)
	Total memory available to MegaMek: 1,013,632 kB

### Description
According to the AtB spreadsheet, Breakthrough(Def) Scenario:
> - If player is   Defender, set Bot with Forced Withdrawal and Immediate Withdrawal (North) and destroy more than ½ of   Bot units to win.

But apparently the bots are not correctly set and hence does not flee immediately.

Attached CPNX (zipped). Hit Start Game in the only pending scenario and proceed to play. Bot does not flee and no Escape message is shown.
[#K-Ao9H30260713.zip](https://github.com/MegaMek/mekhq/files/2620053/K-Ao9H30260713.zip)

**Comment by sixlettervariables** [comment]
There have been some significant updates to this area. Closing this for now. If it persists on 0.45.4+ please feel free to reopen this issue.
