### ISSUE TITLE
Deleting lots of units form the Hangar tab at once.

### ISSUE THREAD

**Issue by KristanDagley** [MegaMek/mekhq#990]
### Environment
What version of MekHQ does your issue apply to? **So far all of them I would guess.**
What operating system are you using?  Windows, Mac, or Linux? **Windows 10**
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.  **(Java 1.8)**

### Description
Describe the issue and provide screenshots in-game if able.

https://megamek.org/bb/thread-2579.html

Same text as in linked post: 
So, in short I have a MekHQ campaign file that has a **VERY LARGE** roster of personnel and assets in the Hangar tab. My computer can no longer provide the RAM necessary to reliably load a file with 100,000's of personnel and 10,000's of hangar assets each time (I am tired of waiting for nearly 2 hours of loading a campaign file only for a dialog box to pop up saying not enough RAM to support, 3 out of every 4 tries) so I have made the decision to compartmentalize my file into several campaign files each about a regiment in size.

The only way I can see to do so is to open a copy of the original file and delete away all the other personnel and assets not belong to one specific regiment at a time and save the remainder as a new campaign file with that regiments name. This works and I am fine with it. (Trying to save a .mul file of each regiment via a deployment, or exporting .mul's doesn't carry over the names of full vehicle crew or infantry platoons and seems to add their rank to their name not separate the two out when reloading into a new campaign file.

**The problem is** (if I can get the main file to load given its size) **I can easily delete personnel in bulk, but not units from the Hangar.**

In the "Personnel" Tab you can use the GM feature to select multiple persons and delete them all at once with the "Remove Person" option. That brings up a dialog box and warns you only once "Do you really want to remove X personnel?"  "X" equaling the number of personnel selected. This works great.

In the "Hangar" Tab however f you select an asset or multiple assets and use the GM feature to "Remove Unit" then for **EVERY** unit that you had selected for removal a dialog box pops up one after another after another, asking "Do you really want to remove _____?" "_____" being the name of each unit in turn that was selected. This takes **FOREVER!** I tried it once so far just to clear away all other units to save one single RCT as its own file and it took me nearly a week having to delete over 17,600 other units. A second attempt to free another RCT as it's own file has been failing repeatedly due to the time it takes and power outages (winter conditions here) and corrupted saved files that won't reload.

I am using no custom units that I recall (or perhaps just one at most) but have "tagged" a few as custom accidentally in the Hangar tab.

Is there any way to mass delete units in an organized fashion if they are not deployed in a "Force?"

Is there any way that I could make a copy of MekHQ where I can disable that time crushing warning dialog box? I have looked for a way to disable it myself but I can't seem to find it! Just pointers to events._ 

### Files
Provide the .cpnx campaign file that this issue occurs in.

Here is a slimmed down example for loading time purposes. This file has around 34,000 personnel and 7,800 unit assets.

[Kristan Dominion.zip](https://github.com/MegaMek/mekhq/files/2631831/Kristan.Dominion.zip)

**Comment by sixlettervariables** [comment]
The date in your CPNX is odd. It appears to be set to the year 12018! I assumed it was 3099 from some of the other entries in the XML.

Any idea why the date is so strange?

**Comment by sixlettervariables** [comment]
The date bit is interesting due to a limitation of a charting component, supporting only 1900-9999 as the year.

**Comment by KristanDagley** [comment]
I wouldn't know anything about that. :) But everything seems to be working just fine.

**Comment by sixlettervariables** [comment]
Implemented by #993.
